### ISSUE TITLE
如何部署proxy？

### ISSUE THREAD

**Issue by zpz1982** [dvajs/dva#100]
dora被定义为开发服务器，那么build以后如何部署proxy.config.js 里面的设置？有什么最佳实践吗？

**Comment by sorrycc** [comment]
proxy.config.js 的 mock 数据是给开发状态用的，部署之后自然是用真实的数据接口了。

**Comment by zpz1982** [comment]
其实我是在proxy里定义了一些跨域请求，不知在dva里如何做比较好。

**Comment by sorrycc** [comment]
理解下开发模式和生产模式的区别，然后考虑请求的域名配置之类的，应该不麻烦的。之后工具的 bug 可以考这边提，https://github.com/dora-js/dora-plugin-proxy/issues
