### ISSUE TITLE
用dva-cli创建model时报错

### ISSUE THREAD

**Issue by MrGoodBye** [dvajs/dva#1004]
![image](https://user-images.githubusercontent.com/20948305/27512971-eb26d46e-5986-11e7-8997-0d74701495d8.png)
@sorrycc 如图
dva-cli版本: `0.7.8`
项目中dva版本: `^1.2.1`
node版本: `6.9.2`
是按照你的[12步CRUD教程](https://github.com/sorrycc/blog/issues/18)来的,重新安装dva-cli,重新创建一个项目,还是会在`dva g model uses`报如上所示的错误

**Comment by jindada** [comment]
这个是 jscodeshift 的问题

**Comment by osoctz** [comment]
@jindada 同样问题   请教解决方法

**Comment by jindada** [comment]
将 dva_cli 依赖的jscodeshift 固定在0.3.30就可以了

**Comment by leeyuGitHub** [comment]
![image](https://user-images.githubusercontent.com/12027046/27681415-c1a663f2-5cf1-11e7-9b71-b160db5855fc.png)

一样的问题，依赖的jscodeshift如何固定0.3.30？

**Comment by leeyuGitHub** [comment]
直接在package.json中添加jscodeshift及版本也没用

**Comment by osoctz** [comment]
@jindada   谢   已解决！

**Comment by leeyu0329** [comment]
@osoctz  怎么解决的哦？

**Comment by osoctz** [comment]
@leeyu0329 实际是dva-ast依赖jscodeshift    我是改的dva-ast的package.json中的jscodeshift然后再update

**Comment by siYuanSiYuan** [comment]
@osoctz 我找不到dva-ast，请问在哪个目录下能找到？

**Comment by MrGoodBye** [comment]
@jindada @osoctz 感谢!已解决!

**Comment by jiliangmason** [comment]
@osoctz 我是改的dva-ast的package.json中的jscodeshift然后再update
请教一下如何update，重装一遍dva？

**Comment by MrGoodBye** [comment]
@jiliangmason 
![baidushurufa_2017-7-21_22-4-17](https://user-images.githubusercontent.com/20948305/28466992-d0baf04e-6e60-11e7-962f-d7d9c765352d.png)

**Comment by MrGoodBye** [comment]
`npm update`打错了...
