### ISSUE TITLE
如何通过 className 控制多级标签的样式

### ISSUE THREAD

**Issue by raisezhang** [dvajs/dva#101]
### 需求描述：

需要通过一个父级的 className 控制N多内部控件的样式，之前的处理方式是通过多级选择器来处理， 比如：
`div.active { }
 div.active .aside {}
`
这样我仅仅需要在 div 控件上通过 state 的值来判断是否需要 active 即可， 内部的控件自然会跟着状态来改变，但是目前 css 文件是不支持多级的选择器存在。

### 问题描述：

如何实现上述通过 active 实现内部标签的样式更新 

PS：目前倒是可以通过全部打散到每一个需要改变的元素上来实现，但这种方案感觉很 low，应该会有更加优雅的处理方式。   

多谢啦  @sorrycc

**Comment by raisezhang** [comment]
还有一种方案 倒是可以通过
`:global {
     .active {}
}` 
不知道还有没有其他解决方案 跪等 ::_::

**Comment by sorrycc** [comment]
我记得 css-modules 是支持多级选择器的。

**Comment by raisezhang** [comment]
又重新试了下 ... 貌似可以了     

之前好像是没有通过  styles.className 来做子标签的 className，而是直接通过 className="abc" 的方式添加， 这样会被认为没有匹配到样式会被删掉 -_-        sorry啦  sorry啦~   

多谢啦 ~
