### ISSUE TITLE
无限下拉怎么实现？是不是要到model里的subscription监听滚动条？

### ISSUE THREAD

**Issue by FatFatFox** [dvajs/dva#1010]
dva的概念中提到监听键盘输入和路径跳转都会触发sbuscription。
是不是滚动到页底，也是在这里触发？该怎么监听呢？
是不是有专门针对滚动的js模块对应支持？谢谢

**Comment by zjxpcyc** [comment]
监听 scroll 事件 判断 window.height + window.scrollTop >= body.height  (伪码)  就可以了

**Comment by zjxpcyc** [comment]
写到原生组件比如 div 的 onScroll 中.  window 对象是全局的, 可以直接只用。也可以使用  [https://www.npmjs.com/package/global](https://www.npmjs.com/package/global)

**Comment by FatFatFox** [comment]
谢谢，已经实现

**Comment by kolf** [comment]
@FatFatFox 监听滚动事件为什么我的不执行？？？？？？？？？？？click事件就行

**Comment by FatFatFox** [comment]
`<div onScroll={functionName}></div>`
