### ISSUE TITLE
请教一下关于effects与reducers不能采取异步的行为的问题

### ISSUE THREAD

**Issue by v19961996** [dvajs/dva#1012]
![image](https://user-images.githubusercontent.com/20790425/27631060-de48939a-5c29-11e7-9487-cf2dfc6175bc.png)

![image](https://user-images.githubusercontent.com/20790425/27630651-b216c900-5c28-11e7-8633-02bb7e1489ee.png)
![image](https://user-images.githubusercontent.com/20790425/27631106-05a49eca-5c2a-11e7-81d1-f65d3fa8e63a.png)

各位大大，我的问题就是。我发现我的 effects ，异步函数 call() 在还没返回数据就已经执行了下面的 put() 函数，导致数据没能正确赋值就跳到了下一步了。请教请教

**Comment by v19961996** [comment]
@sorrycc @yiminghe @JacksonTian @popomore @bang88

**Comment by popomore** [comment]
没写 await

**Comment by v19961996** [comment]
@popomore  谢谢。。我找到错误了。。非常感谢。。实在找不到错误所以才问你们的。。。谢谢!

**Comment by hatunet** [comment]
@v19961996 什么错误

**Comment by vipcxj** [comment]
是没写return吧，yield call传入的函数一般要返回一个Promise，axios没用过，但看api形式估计返回的也是Promise，问题是没有return啊，所以那个函数返回了一个undefined

**Comment by v19961996** [comment]
@hatunet 搞定了。是因为没有写 await 。。。这个知识点不熟导致的。

**Comment by v19961996** [comment]
@vipcxj  因为没有写await 。 所以异步去提交了，就没有阻塞直接执行下一步代码了

**Comment by vipcxj** [comment]
你写个return也可以吧，你返回一个promise，yield也会进行阻塞的，你什么都不返回，自然直接就走过去里。官方脚手架自动生成的最初例子，就是直接返回一个async函数里面直接返回request(XXX)，而request返回的就是一个promise，虽然我也纳闷async函数里竟然一个await都没有，但用起来并没有什么问题～

**Comment by v19961996** [comment]
@vipcxj  嗯呢~ 我刚刚试了一下，的确可以~ 这样就有两种解决方案了。(对知识点不熟在这浪费太多时间了)

**Comment by vipcxj** [comment]
其实我怀疑返回promise的情况下不用ansyc，直接用一般函数也是可以的，不过官方例子有ansyc，我也照猫画虎，反正加了ansyc也不会出什么问题

**Comment by v19961996** [comment]
@vipcxj 我能加下您的联系方式吗？有个问题想请教一下您

**Comment by v19961996** [comment]
@vipcxj  我直接在这里问您吧。是这样的。
![image](https://user-images.githubusercontent.com/20790425/27845688-ec2f787c-6163-11e7-8a4a-ce8f70490914.png)

![image](https://user-images.githubusercontent.com/20790425/27845652-a13dbce8-6163-11e7-89da-bcb57f2786c1.png)
![image](https://user-images.githubusercontent.com/20790425/27845704-14918094-6164-11e7-96b6-6329795edbae.png)

**Comment by v19961996** [comment]
@vipcxj 我的问题就是，不知道为啥。前几天还好好的。然后就突然报个dispatch 不是一个函数 或者 报错说 dispatch undefined 。

**Comment by MoneZhao** [comment]
@v19961996  dispatch改成this.props.dispatch试试

**Comment by vipcxj** [comment]
mapDispatchToProps这个参数不加试试~ 这个参数就是映射dispatch用的，你不指定，有默认行为，也就是直接就把dispatch给你了，你自己加了个空对象后什么效果我就不清楚了~

**Comment by bang88** [comment]
使用 `mapDispatchToProps`后如果你要在属性里面使用 dispatch 需要返回回去
```js
const mapDispatchToProps = dispatch => {
  return { 
    dispatch
  }
}
```

**Comment by v19961996** [comment]
刚刚已经加上了@bang88 的mapDispatchToProps写法。 的确可行。 @vipcxj   那个返回空对象那行代码是今天我自己尝试的时候不可行然后还没有删除。不过最大的疑问就是，其实之前一直没有用这个方法。也是可行的。今天打开之后就不可以了，我还以为一直子组件都是不用map也可以使用父组件的dispatch。这样心里的疙瘩~哎呀。不过还是非常感谢。

**Comment by vipcxj** [comment]
确实不用map就可以用dispatch，你多次一举改变了默认行为，自然就不行了~

**Comment by v19961996** [comment]
@vipcxj 老哥求指导。如果不用map呢。我想改回去。毕竟还有其他的模块很多之前不用map的也可以挑用dispatch

**Comment by vipcxj** [comment]
直接connect()喽

**Comment by v19961996** [comment]
@vipcxj ok~ 搞到了~
