### ISSUE TITLE
多页应用共用导航的问题

### ISSUE THREAD

**Issue by yxl2628** [dvajs/dva#1016]
大神们，有个问题，想咨询一下：
- 现状
我们后台的服务是按照模块做成了多个微服务，前端也想按照后台的服务，每个微服务做一个单页应用。
微服务A--->单页微应用A
微服务B--->单页微应用B
微服务C--->单页微应用C
也可以理解为，每一个一级菜单是一个单页应用。
之所以这么做，是想将来ABC可以组合成一个项目、BEF组合成另一个项目，所以每一个单页应用都是一个独立的dva工程。

- 设计思路
/manage
-- index.html //登录以及导航菜单，访问路径为：http://localhost:8000/#/login
-- index.js
-- /A
---- /A/index.html //微应用A，访问路径为：http://localhost:8000/A/#/main
---- /A/index.js
-- /B
---- /B/index.html //微应用B，访问路径为：http://localhost:8000/B/#/main
---- /B/index.js
即我需要用到哪些，就将哪些应用的文件夹扔进manage里面

- 问题
上面的思路中，我想做一个专门处理登录和权限应用manage，这个应用负责登录逻辑，以及登录之后，导航菜单的渲染，然后点击A、B、C就会跳转到相应的单页应用上，那么问题来了，关于导航菜单，我想在这个应用上做，然后ABC就相当于导航下iframe进来的，可是我又不想用iframe，能有解决办法么？

- 我自己的解决思路
我自己想了一个笨办法，不知道打什么有没有更好的办法，我感觉我的方法特别笨拙，不过也说一下，至少让大神们知道我用心想了。。。
我想在manage这个应用中除了index.js这个入口文件，在额外生成一个head.js，这个负责头的渲染，然后在ABC这些应用的index.html中，引入../head.js，用这个js来渲染导航。
但是这么做，我感觉ABC像是被侵犯了一样，特别不友好，不知道有没有更好的解决办法？

**Comment by zjxpcyc** [comment]
我也遇到了类似的问题。我现在的做法是，用 nginx 做转发。
