### ISSUE TITLE
dynamic-load 时，路由有多级路径时找不到拆分的.js文件

### ISSUE THREAD

**Issue by yinlsea** [dvajs/dva#102]
把user-dashboard示例按照dynamic-load示例只改造router.js，如下:
![image](https://cloud.githubusercontent.com/assets/21033870/18785051/a2f42994-81c8-11e6-9602-183c62aaba94.png)
history使用browserHistory时，如果路由到/demo/users路径，则会请求127.0.0.1:8989/demo/0.js，出现404报错
![image](https://cloud.githubusercontent.com/assets/21033870/18785123/f6174f98-81c8-11e6-8127-8542772a8671.png)
history如果使用hashHistory则没有问题,请求的是127.0.0.1:8989/0.js

如果直接路由到/users，则不管是hashHistory还是browserHistory都没有问题。

**Comment by yinlsea** [comment]
如果直接不采用dynamic-load模式，则路由到多级也是没有问题
![image](https://cloud.githubusercontent.com/assets/21033870/18785260/d4dd4606-81c9-11e6-9942-142b77ae8752.png)

**Comment by sorrycc** [comment]
webpack 的 publicPath 配成 '/' 试试。

**Comment by yinlsea** [comment]
![image](https://cloud.githubusercontent.com/assets/21033870/18790502/91232c42-81e1-11e6-84f3-f8423a93be08.png)

 加上publicPath后，根路径的路由/index.js就直接404了.

**Comment by xjdata** [comment]
@yinlsea  请问你的vsc，对react的项目支持如何？ 我用默认的，也尝试安装了几个扩展， 但是当遇到`{...foo,...bar}`格式的语句时，自动格式化就瘫痪了。  又不太想还其他的编辑器，没办法只有手工format。

**Comment by ohmyauthentic** [comment]
@xjdata 解析构符号也识别不了，你有什么插件嘛

**Comment by sorrycc** [comment]
用 idea 或 webstorm 啊，官方更新很快，支持也很全。

**Comment by xjdata** [comment]
@ohmyauthentic  木有~ 没办法换了webstorm~

**Comment by yinlsea** [comment]
解决了，用browserHistory,按需加载的时候需要这样写：
import { useRouterHistory } from 'dva/router';
import { createHistory } from 'history';

dva({
    history: useRouterHistory(createHistory)({basename: ‘ROOTPATH’}),
});

**Comment by yinlsea** [comment]
解决了，用browserHistory,按需加载的时候需要这样写：
import { useRouterHistory } from 'dva/router';
import { createHistory } from 'history';

dva({
    history: useRouterHistory(createHistory)({basename: ‘ROOTPATH’}),
});

**Comment by yinlsea** [comment]
解决了，用browserHistory,按需加载的时候需要这样写：
import { useRouterHistory } from 'dva/router';
import { createHistory } from 'history';

dva({
    history: useRouterHistory(createHistory)({basename: ‘ROOTPATH’}),
});

**Comment by lhg0302** [comment]
你好,我按你的方式解决了子目录的问题,但是现在多级路径,在一级路径入http://localhost:8989/indexpage按f5刷新可以,但是http://localhost:8989/indexpage/test1按f5就不行,报找不到.js文件

**Comment by yuanmao5200** [comment]
@yinlsea 请问下 ROOTPATH是指什么 ，我用<Link to='/xx/xx'> 可以 顺利进去多级路径，F5刷新进不了i

**Comment by yinlsea** [comment]
ROOTPATH就是你的根路径，例如:"/XXX/“,访问就是http://IP:PORT/XXX/
