### ISSUE TITLE
如何用dva的方式来清空form

### ISSUE THREAD

**Issue by AllenHK** [dvajs/dva#1020]
<img width="726" alt="screen shot 2017-06-29 at 6 28 32 pm" src="https://user-images.githubusercontent.com/3193216/27683693-7a7eb60c-5cf9-11e7-95dd-da3d626fde92.png">

我有一个页面里面有两个tab，有一个tab是用来创建商家，创建商家通过dispatch一个effect创建，我想在创建成功之后清空表单，请问下有没有比较好的方法？

**Comment by MrCuriosity** [comment]
antd Form组件有个方法参数`Form.create(mapPropsToFields)`可以将`props`map到受Form控制的表单域中, `props`的上游数据流又可以是redux, 所以思路可以是新增成功以后dispatch一个reset action
```js
const initialForm = {
  businessName: undefined,
  businessType: undefined,
  businessNumber: undefined,
  loginEmail: undefined,
  loginPwd: undefined,
  loginTel: undefined
}
reducers: {
  RESET_FORM(state, action) {
    return {...state, form: initialForm}
  }
}
effects: {
  *createBusiness(action, saga) {
    /** 业务 */
    if (/** request succeed */) {
      yield put({ type: 'RESET_FORM' })
    }
  }
}
```

```js
connect(mapStateToProps)(Form.create({
  mapPropsToFields({ yourNameSpace }) {
    const { form } = yourNameSpace
    Object.keys(yourNameSpace).reduce((acc, cv, ci) => {
      return {
          ...acc,
          [cv]: {
          value: form[cv]
        }
      }
    }, {})
  }
})(YourComponent))
```

**Comment by FatFatFox** [comment]
你用的是antd组件吧，有个form表单api里有个resetfield方法清空

**Comment by AllenHK** [comment]
@MrCuriosity 感谢回复，这是一个行之有效的方法，不过这样的话，我必须把表单的数据放到到全局的state中去，感觉稍微有点复杂，现在我的表单数据是通过payload传递过去的，我的困惑和这个问题https://github.com/redux-saga/redux-saga/issues/907很像，我想知道有没有一种比较简单的方式，可以做到saga和Component之间传递信息？

**Comment by AllenHK** [comment]
@MrCuriosity 感谢回复，这是一个行之有效的方法，不过这样的话，我必须把表单的数据放到到全局的state中去，感觉稍微有点复杂，现在我的表单数据是通过payload传递过去的，我的困惑和这个问题https://github.com/redux-saga/redux-saga/issues/907
很像，我想知道有没有一种比较简单的方式，可以做到saga和Component之间传递信息？

**Comment by MrCuriosity** [comment]
@AllenHK 
Redux与ReactComponent，通信只有`connect([mapStateToProps], [mapDispatchToProps], [mergeProps], [options])`, 并且数据流向是单向的，只能通过props呀，saga和component传递信息我只能想到改变state(即props)和利用map过去的dispatch回来改state了，这正好是个闭环，也是redux的思想。

**Comment by AllenHK** [comment]
@MrCuriosity 我认同你的理解，不过有时候都把应用状态都放在全局的话，会把问题复杂化，就好像loading这个状态，如果不是有dva-loading的话，处理起来也是挺麻烦的..
![screen shot 2017-06-30 at 4 55 31 pm](https://user-images.githubusercontent.com/3193216/27728565-fbd75428-5db4-11e7-9e4f-ba23058010b2.png)
我现在暂时的做法是这样，虽然违反了单向数据流的思想，不过确实使问题简单化了，期待有更优雅的解决方案..

**Comment by zjxpcyc** [comment]
弱弱地问大神们一句，用原生的 class 定义组件，不是很容易就解决这个问题吗？

**Comment by AllenHK** [comment]
@zjxpcyc 请教一下，如何轻易解决？

**Comment by AllenHK** [comment]
@sorrycc  https://github.com/redux-saga/redux-saga/issues/161 这个问题在saga项目也有挺多人讨论的。不知道有没有什么比较妥善的解决方案？

**Comment by zjxpcyc** [comment]
我简单说下，可能是我理解的不正确。

在 form 的 submit 事件向上传递的时候, 传递一个 callback , 这个 callback 清空 state ，是不是就可以？
