### ISSUE TITLE
组件和model中有dispatch和put方法可以触发action，其他地方如何触发action？

### ISSUE THREAD

**Issue by noonehide** [dvajs/dva#1022]
1. 组件和model中有dispatch和put方法可以触发action，其他地方如何触发action？
2.reduxRouter也需要put方法来触发，如何手动触发？

**Comment by noonehide** [comment]
例如，在一个网络请求的工具类里，需要使用dispatch来触发action，怎么做？

**Comment by v19961996** [comment]
网络工具类貌似一般都是拿来取数据的。为啥需要触发action

**Comment by Renascence** [comment]
看你在哪获取，组件里面获取到数据可以调用dispatch，models里面也可以

**Comment by bestsamcn** [comment]
同样遇到相同的问题，我是想，在request里面判断后台返回的code，来确认是否用户权限问题，比如，当用户没无权限的时候，dipatch一个action，然后清除本地缓存，再跳转登录页，现在不知道如何执行这个操作逻辑

**Comment by codercatmomi** [comment]
同问
