### ISSUE TITLE
请问在dva里面怎么加入socket.io

### ISSUE THREAD

**Issue by xjchilli** [dvajs/dva#1024]
请问在dva里面怎么加入socket.io，使之能监听服务端的消息，并在各个页面使用，谢谢。

**Comment by zjxpcyc** [comment]
在根 route 组件的 onEnter 里面就可以。

**Comment by sorrycc** [comment]
推荐在 subscriptions 里监听，然后根据过来的数据触发 action 走到 effect 写业务逻辑。

**Comment by cxl086** [comment]
请问如果是动态地连接多个websocket如何处理？

**Comment by zjxpcyc** [comment]
@cxl086 说一个题外的问题。动态 websocket 有很多坑。我大致列举下我遇到的

1. 页面刷新，如果恢复默认连接
2. 断线重连, 仅仅重新赋值变量不够。注意区分, 什么情况下确实要断开，而不需要重连
3. 心跳解决
4. chrome 与 ff 好像最大支持 48H 长连接, 超过了，再怎么设置也没用。我的解决方案是 每天 0 点 页面刷新一次

想到的就这么多，所以不推荐动态 ws , 有机会还是用长连接吧，比 ws 技术低，稳定性，兼容性各方面都比 ws 要好。

再回到正题， 动态连接 ws 区分时机，如果是页面加载，那么 在进入页面的时候。如果是 select 之类的页面内控制, 就只能写 effect 里面, 页面内去控制了。
