### ISSUE TITLE
state 为对象类型，修改对象属性有的视图能刷新，有的不能刷新

### ISSUE THREAD

**Issue by javahuang** [dvajs/dva#1027]
```
state:{
  master: {
   detail: {disabled: false},
   form: {transNo: ''},
  },
}
```
用的 ant-design，不通过 dispatch，我直接修改 master.form.transNo  ，视图 Tooltip 能渲染；
但是修改 master.detail.disabled  视图按钮却不能渲染，我重启一下开发者工具，视图就渲染了；
上面两种状态，通过 redux 插件查看属性都没有变化，但是重启一下开发者工具缺变化了；
请问不 dispatch，偷个懒，直接通过对象属性来控制某些 state 的变化可行吗？

**Comment by dkvirus** [comment]
使用框架是看框架提供了什么，然后去使用。
dva 框架修改  state 状态值只能通过 reducers 里的方法来进行修改，这一点作者在 [8个概念 ](https://github.com/dvajs/dva/blob/master/docs/Concepts_zh-CN.md)里明确说过。
你第一个直接修改 state 页面变化了只能说明是潜在bug，不建议这样操作。
