### ISSUE TITLE
使用browserHistory  后，刷新页面显示Not Found

### ISSUE THREAD

**Issue by hanagm** [dvajs/dva#103]
发生问题的环境是：

dva版本: v1
操作系统及其版本: windows8
浏览器及其版本:  Chrome 52
问题：
     使用browserHistory 后，手动刷新页面页面显示Not Found。
     如果是在 “/”下  通过Link to 跳转到users不会出现Not Found 

   dva默认的history刷新不会出现Not Found 

 代码：

index.js

import { browserHistory  } from 'dva/router';

// 1. Initialize
const app = dva({
  history: browserHistory,
});

router.js

  <Router history={history}>
      <Route path="/" component={IndexPage} />
      <Route path="/users" component={Users} />
    </Router>

预想结果
 
![image](https://cloud.githubusercontent.com/assets/6668952/18813142/3e5dd90e-8320-11e6-96d4-9269ef8947da.png)

实际结果
![image](https://cloud.githubusercontent.com/assets/6668952/18813145/ac0af810-8320-11e6-9bc4-a7c8f4f7ae71.png)

**Comment by sorrycc** [comment]
这需要服务器端支持，如果你用 dora 作为开发服务器的话，可以试试 [dora-plugin-browser-history](https://github.com/dora-js/dora-plugin-browser-history) 插件

**Comment by hanagm** [comment]
@sorrycc   如果不设置history为browerHistory，使用默认的hashHistory(我理解的是dva默认的history)，
 点击刷新按钮就不会报错，这是因为做了什么处理是么？

**Comment by codering** [comment]
@hanagm  你应该去了解下前端路由的实现方式

**Comment by hanagm** [comment]
@codering  @sorrycc  thanks，已经解决。

**Comment by zhump** [comment]
@hanagm 你刷新不会404 了吗

**Comment by zhump** [comment]
@hanagm 我也解决了

**Comment by freestyle21** [comment]
同遇到 使用 `browerHistory` 和 静态资源绝对地址后，开发环境可以刷新二级目录，生产环境刷新二级目录报错404问题。

搜索所有相关issue后，发现给的解决方案都不能完全搞定，折腾好了后这里记录下自己的方案：


综合多个issue有两种解决方案：

1.  Node(koa)批量处理路由，例如 [https://github.com/sorrycc/dva-boilerplate-isomorphic/blob/master/server/server.js#L22](https://github.com/sorrycc/dva-boilerplate-isomorphic/blob/master/server/server.js#L22)，由于之前项目开发了很长时间，迁移到这个方案会涉及到路径修改，文件大量迁移，增加webpack等，所以放弃了。

2.  Nginx 批量处理，代码如下
```
server {
        listen       80;
        server_name  www.example.com;
        root   /path/to/xx/dist;
        location  / {
            index  index.html index.htm;
            try_files $uri $uri/ /index.html =404;
        }
        location * {
          try_files $uri $uri/ /index.html =404;
        }
}
```

希望帮到后面遇到的人～
