### ISSUE TITLE
Spring boot 与DVA利用Fetch通信问题

### ISSUE THREAD

**Issue by yoster0520** [dvajs/dva#1031]
本人前端属于小白级别。目前前端环境是DVA+Redux+Ant，端口为8000，后段使用Spring boot+Spring Security，端口是9002。现在想问问大家有没有好的通信解决方案。
<br>问题：
<br>
认证在后台，所以我利用Fetch首先去将用户名和密码发送给后台，认证成功返回用户信息和一个`Set-Cookie`,但再请求其他链接时，并没有带上这个Cookie，所以利用`credentials: "include"`参数使Fetch带上跨域的Cookie，但这样设置以后，GET请求正常，其他请求都不可用，所以想咨询下，有没有好的解决方案？

**Comment by ameol** [comment]
我是用请求头传递的
   method: "POST",
    mode: 'cors',
    headers: {
      'xxx-token': tokenId,
    },

**Comment by yoster0520** [comment]
@ameol 你给Spring Security加了Filter？我知道这种方法，但这个要存储xxx-token，你是存在localStore还是sessionStore

**Comment by ameol** [comment]
@yoster0520 我们保存到localstorage，然后发送请求就在请求头带上，后端处理跨域，然后校验是否过期。没用cookie，感觉可能会比较麻烦。
