### ISSUE TITLE
求助，按照如下教程出现问题了

### ISSUE THREAD

**Issue by kylezhang** [dvajs/dva#1033]
- [Step 4. 生成 users 路由](https://github.com/sorrycc/blog/issues/18)出现如下error；
![qq20170704-175952](https://user-images.githubusercontent.com/3679798/27825950-e359d86c-60e3-11e7-8d1f-6f223d31da31.png)

**Comment by wenris** [comment]
将全局安装库 **jscodeshift** 降级至 *0.3.28* 版本，或直接修改全局安装库 **dva-ast** 的文件，将下面文件中的 `'jscodeshift/dist/Collection';` 改为 `'jscodeshift/src/Collection';` ：

1. dva-ast/lib/collections/Entry.js
2. dva-ast/lib/collections/RouteComponent.js
3. dva-ast/lib/collections/Router.js

详见 https://github.com/dvajs/dva-cli/issues/91

**Comment by kylezhang** [comment]
我觉得可以在目前使用`dva-cli`时，暂时在readme或者[教程](https://github.com/sorrycc/blog/issues/18)中明确的为开发者提示下可能出现此问题，包括[解决的方法](https://github.com/dvajs/dva-cli/issues/91)。
