### ISSUE TITLE
help！关于dva dispatch函数无法传递报错dispatch was undefined。

### ISSUE THREAD

**Issue by v19961996** [dvajs/dva#1034]

**Comment by v19961996** [comment]
![image](https://user-images.githubusercontent.com/20790425/27845941-0b6e74c0-6166-11e7-96ea-43ba36461b78.png)
![image](https://user-images.githubusercontent.com/20790425/27845952-24d0a082-6166-11e7-8fcc-1e7a77f3a254.png)
![image](https://user-images.githubusercontent.com/20790425/27845975-61619b5a-6166-11e7-8a75-feb046861580.png)

**Comment by v19961996** [comment]
个人感觉是dispatch参数不能传递到位。导致下面的组件也没法用。但是有一件神奇的地方是，model的subscribtion函数的dispatch是没有问题的。各位大大求指教。估计是哪里错了可是找不出来

**Comment by v19961996** [comment]
@wenris

**Comment by sorrycc** [comment]
看起来确实没啥问题，给个能重现的库或者压缩包吧。

**Comment by v19961996** [comment]
@sorrycc  老师，我刚刚把代码给成了
![image](https://user-images.githubusercontent.com/20790425/27860977-6d265cfa-61b1-11e7-82db-2289c9a0007c.png)
是可行的。组件可以得到dispatch。我题目上面的那个写法是因为我今早测试不行后才加上去的。现在换了写法可以运行了。可是我有个疑问。因为**按需加载**的原因，我一直以为子组件可以不用mapDispatchToProps这个方法去注入子组件。而且，之前我一般也是直接在子组件直接调用dispatch是没有问题的。现在感觉到非常的尴尬。

**Comment by v19961996** [comment]
@sorrycc  给个能重现的库或者压缩包吧。这句话是什么意思？我太菜了不是很懂。

**Comment by sorrycc** [comment]
> 给个能重现的库或者压缩包吧。这句话是什么意思？我太菜了不是很懂。

怎么最简化地重现你的问题？

**Comment by v19961996** [comment]
@sorrycc 我觉得现在代码里定位出现的问题有点困难。但是可以确定的是，子组件是无法直接调用父组件的dispatch。只能通过props进行传递了。

**Comment by sorrycc** [comment]
> 子组件是无法直接调用父组件的dispatch。只能通过props进行传递了。

是这样的。

**Comment by v19961996** [comment]
@sorrycc 可是之前我可以直接在组件里面调用dispatch。不用通过mapDispatchToProps 这种方式。我不知道这跟测试环境是否有冲突。

**Comment by mengwuhen** [comment]
mark
