### ISSUE TITLE
请问一下： 点击按钮，返回上页怎么处理

### ISSUE THREAD

**Issue by flashpig** [dvajs/dva#1036]
我在页面上有个按钮， 想点击按钮，返回上一页，使用routerRedux.goBack() 这个方法，没有效果。
返回的内容是包含  type: "@@router/CALL_HISTORY_METHOD"  的Object。

**Comment by sorrycc** [comment]
`routerRedux.goBack()` 返回的是 action，dispatch 了吗?

**Comment by flashpig** [comment]
神呐，收下我的膝盖吧。 

顺便再请教一下：
dispatch 
我是这样传递的，已经可以返回上一页了，但是 这样处理合适吗？
function IndexPage({ dispatch }) {
      。。。
      <Header dispatch={dispatch} />
      。。。
