### ISSUE TITLE
如何设置basename

### ISSUE THREAD

**Issue by bgdsh** [dvajs/dva#1037]
没使用dva之前是这样用的。
```
import { createHistory } from 'history'
import { useRouterHistory } from 'react-router'
import { syncHistoryWithStore } from 'react-router-redux'

const browserHistory = useRouterHistory(createHistory)({
  basename: '<yourBaseUrl>'
})
const history = syncHistoryWithStore(browserHistory, store)
```
现在应该如何配置呢？

**Comment by sorrycc** [comment]
试试这样：

```js
import { createHistory } from 'history'
import { useRouterHistory } from 'dva/router'

const browserHistory = useRouterHistory(createHistory)({
  basename: '<yourBaseUrl>'
})
const app = dva({
  history: browserHistory,
});
```

**Comment by bgdsh** [comment]
有个尴尬的问题，basename应该是加上了，但是打开的时候报了一个奇怪的错误。
![2017-07-06 10 14 48](https://user-images.githubusercontent.com/16064778/27892756-16e32b92-6234-11e7-8e88-6f0cbeff6843.png)

**Comment by bgdsh** [comment]
<img width="1131" alt="2017-07-06 10 21 04" src="https://user-images.githubusercontent.com/16064778/27892917-e50564b8-6234-11e7-889b-6726896a52e9.png">
这是变化的内容

**Comment by bgdsh** [comment]
不好意思，刚刚这个描述有点误导性。等下我会把遇到的问题重新描述一下。

**Comment by bgdsh** [comment]
现在还是会跳转到`/login`， 但预期的是跳转到`<basename>/login`。

**Comment by bgdsh** [comment]
如果能做到基于相对路径跳转也可以。
