### ISSUE TITLE
麻烦把tag 1.3.0-beta.4 push上来

### ISSUE THREAD

**Issue by kerryChen95** [dvajs/dva#1039]
麻烦把tag 1.3.0-beta.4 push上来，因为想要[使用经过版本更新的deps](https://github.com/dvajs/dva/commit/eb6d9fdafcbc7c4387501ce413563a1dd6a688c5)，但又不想根据master分支名来安装，想根据tag来安装，以免引入不确定性

**Comment by sorrycc** [comment]
`1.3.0-beta.4` 在 npm 上的。
