### ISSUE TITLE
【请教】dva是否可以搭配relay+Graphql使用？

### ISSUE THREAD

**Issue by jeasonstudio** [dvajs/dva#1041]
如题，如何在使用dva的同时使用relay，或者其他形式graphql

**Comment by sorrycc** [comment]
感觉用 relay 就没必要用 dva 了。

**Comment by bucaixiaot** [comment]
@sorrycc 确实没有不要用dva,估计一楼的意思是想使用使用dva中的antd

**Comment by jeasonstudio** [comment]
@bucaixiaot 最近团队在尝试新技术，准备上 Graphql，但由于担心 relay 在UI 层、或组件内状态的管理会出现短板之类的问题。。。
现在没有在用relay，正在尝试apollo-client，当然也用了dva

**Comment by bucaixiaot** [comment]
@jeasonstudio   @@我也是想在dva中使用relay,其实就是在roadhog中使用使用relay，无奈在rodhog中配置relay和graphql折腾了好久]

**Comment by bucaixiaot** [comment]
@sorrycc 我想在roadhog中使用relay,配置了好久折腾不出来

**Comment by jeasonstudio** [comment]
@bucaixiaot 感觉不论是用dva搭配relay还是apollo-client，都有一大半的功能重复、用不上。
他们各自有自己的一套状态管理，我们现在是完全抛弃了apollo-client的store，客户端数据层全用redux、redux-saga、dva管理，apollo-client只是相当于封装了之前的 ‘ajax’请求。
如果想要过度到graphql，这是个不错的选择。
![image](https://user-images.githubusercontent.com/17971291/28349784-7155405e-6c77-11e7-82e9-81fbb7bd7e67.png)

**Comment by bucaixiaot** [comment]
@jeasonstudio 我是直接用redux过渡到graphql的，graphql只是个通信协议，无非是redux发送请求的时候带上参数,其实graphql和relay没有多大关系，无非relay更倾向于graphql协议而已,

**Comment by bucaixiaot** [comment]
我在dva中引入relay,relay一直报错 好像是relay的问@jeasonstudio

**Comment by wuzhuzhu** [comment]
所以有人搞定了apollo吗？

**Comment by bucaixiaot** [comment]
为什么要用apollo？redux 用graphql 接口照样用，relay也可以用graphql 接口。Ajax 也可以用graphql 接口？没用过apollo 那玩意，如果会redux 没必要用apollo

**Comment by wuzhuzhu** [comment]
http://dev.apollodata.com/react/redux.html
Apollo并不是用来替代redux. Redux是状态管理工具， apollo stack是数据中间层和辅助的数据状态管理工具。redux可以做apollo可以做到的事，react state理论上一样可以做到redux可以做到的事。无非麻烦而已。
@bucaixiaot 
我们没必要在这里讨论有没有上apollo，您有您的需求，别人有别人的。既然dva是一个框架，我们往上加想要使用的工具，想找到方法而已。
开头的文档是apollo专门介绍怎么整合到已有redux的项目。从apollo client 0.1版本就有。如果apollo是设计出来替代redux的，还有必要自己写一个这样的文档吗？

**Comment by FerminYang** [comment]
@wuzhuzhu 改了一下官方的user-dashboard教程，把REST API替换成了GraphQL(https://graph.cool)，repo地址：https://github.com/FerminYang/dva-graphql-lokka-user-dashboard
