### ISSUE TITLE
想在dva中使用nprogress插件

### ISSUE THREAD

**Issue by mgoann** [dvajs/dva#1042]
想把nprogress插件引入进来，发现js执行没有问题，但是css并没有打包到index.html中，这是我.roadhogrc中的配置，
`"extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }],
        ["import", { "libraryName": "nprogress", "style": "css" }]
      ]`

这个是component中引入
`import nprogress  from 'nprogress';`
请大神帮忙看下这样配置有什么问题？

**Comment by not3** [comment]
https://github.com/zuiidea/antd-admin/blob/master/src/routes/app.js

这个工程也用了nprogress， 你可以参考下

**Comment by dicklwm** [comment]
`nprogress`的文件里面没有`index.js`和`index.css`，所以需要手动引入
`import nprogress from 'nprogress/nprogress.js'`
`import 'nprogress/nprogress.css'`
