### ISSUE TITLE
创建两个了model。另外一个model好像不生效啊，咋回事啊

### ISSUE THREAD

**Issue by Slice-dd** [dvajs/dva#1044]
我是这样调用的
`
export default connect(({users}) => ({users}))(Example);
`

**Comment by sorrycc** [comment]
没理解意思，这个代码看不出有两个 model 。

**Comment by Slice-dd** [comment]
新手小白。。。。
比如这样 ` export default {
    namespace: 'products',
    state: {
       
    }, 
} `我创建了两个这样的model，但是只有在index.js里面require的model （`app.model(require('./models/products'));`） 才能用，另外一个没有require的，就好像没有生效一样，

**Comment by bow3nwang** [comment]
@Slice-dd `app.model(require('./models/products'))` 就是引用model， 你没有引用就不会生效~

**Comment by Slice-dd** [comment]
但是我看到别人只require了一次啊，就是在index.js里面 ，别的地方没有用require啊

**Comment by Slice-dd** [comment]
@bow3nwang  @sorrycc  求解惑。。

**Comment by Slice-dd** [comment]
`// 3. Model
app.model(require('./models/products'));
`  
原来确实要像这样引用，但是如果要引用我创建的每一个model，在哪里引用会好一点（优雅一点）

**Comment by yanthink** [comment]
可以在路由配置里面通过require.ensure来按需加载model

**Comment by Slice-dd** [comment]
@yanthink 谢谢，这个是大家普遍的用法么
