### ISSUE TITLE
node做服务器代理到dva后报错

### ISSUE THREAD

**Issue by yueleiMaster** [dvajs/dva#1046]
我用node.js做的服务器 端口8090  然后监听路由 为http://localhost:8090/w/就代理到端口为8091的dva开发服务器中 现在页面是跳过来了 但是开发服务器被关闭了 而且热更新失效  可能是因为我现在的路径必须是http://localhost:8090/w/  dva服务器才会起作用  所以内部的配置并没有设置路径 所有 请大神们帮我看看该怎么改
![image](https://user-images.githubusercontent.com/25242674/27939850-02170686-62fa-11e7-9e71-4e2de32f3209.png)

![image](https://user-images.githubusercontent.com/25242674/27939876-18e9b0a2-62fa-11e7-81bd-1465b4bb04fd.png)
![image](https://user-images.githubusercontent.com/25242674/27939894-35fa09c6-62fa-11e7-9c45-988e7fab4835.png)
![image](https://user-images.githubusercontent.com/25242674/27939907-450f23ce-62fa-11e7-83a6-a503bd35e266.png)

**Comment by yueleiMaster** [comment]
页面显示，功能都正常

**Comment by sorrycc** [comment]
就是路由匹配问题吧。

**Comment by yueleiMaster** [comment]
我感觉有点像  dva的测试服务器ip没有修改导致找不到我代理的服务器 但是dva的测试服务器怎么修改IP地址呢
