### ISSUE TITLE
dva new dva-quickstart 文件为何这么大

### ISSUE THREAD

**Issue by zhouzefei** [dvajs/dva#1047]
dva new dva-quickstart
用这种方式不增加任何就一个页面打包出来就有288k，，，照理来说这么点内容最多几十k，，为什么会这么大？如何优化 @sorrycc

**Comment by acwong00** [comment]
感觉打包出来的index.js文件非常大，同样想知道怎么优化

**Comment by sorrycc** [comment]
用 `roadhog build --analyze` 分析下。

**Comment by liumin1128** [comment]
dva虽说是轻量级的框架，但依赖的可都是大部头，仅react+react-dom压缩后就120多k，可使用preact替换。redux不大，redux-saga体积较大，为了支持saga，以及部分es7特性，还要再算上babel-profill，280k已经不错了。
可以考虑将react，react-dom换成preact，将redux，redux-saga，reac-router单独打包成动态链接库。
参考[https://github.com/liumin1128/react-cli.git](https://github.com/liumin1128/react-cli.git)，剔除大部分依赖后，index.js约10kb。

**Comment by nalantianyi** [comment]
288k已经很不错了。。。如果还是看着难受，可以把react，react-dom，saga等单独拎出来，不要打包。这样看着舒服点，特别在使用CDN的时候 加载性能会好一些
