### ISSUE TITLE
关于sagas之间相互通讯的问题。

### ISSUE THREAD

**Issue by hopperhuang** [dvajs/dva#1049]
@sorrycc  作者你好（不知道这样的称呼对不对），我看了下dva的设计思路，确实解决了很多问题，比如sagas, 和reducers过于分散的问题，还有就是用对put方法和dispatch方法进行封装，在内部调用sagas的时候，因为吧namespace作为前缀封装了进去，调用起来很方便。

最近我也在像写一个类似dva的框架给自己用，在处理sagas的时候，我想到了一些问题。
dva对sagas的处理是为models里面的每一个effects提供一个namespaces + effectname作为一个前缀，然后根据opts，用takeevery或其他方法，生成一个watcher，然后fork这个生成的watch,再由这若干个watcher组合成一个相对于子页面来说的rootsaga，最后通过store.run方法，将这些子页面（或者说model）的rootsagas，启动。

但是我的想法是，真的有必要将每个effect都fork一次吗，每个effect都fork一次，这就意味着，从外部来说，其他Model，或者说页面也可以通过dispatch方法去调用这个saga。这是很多时候这些effects，并不需要用被其他页面调用，我们也不希望它被其他页面调用，或者与其他页面通讯，因为这些effects仅仅是用于处理流程中的某个环节的，这样暴露出来，我觉得是没有必要的，也是不安全的。

我更加希望我的sagas设计是这样的：
```
model-rootsaga-publicwatcher1-private_effect1
                          -private_effect2
                           -private_effect3
            -publicwatcher2-private_effect1
                                       -private_effect2
                                       -private_effect3
```
仅仅将需要的saga作为watcher暴露出来，而不是将全部saga暴露，这样设计不是会更好吗？

**Comment by sorrycc** [comment]
effect 不让被调用？effect 从设计上就是可以被其他 model 调用的啊。

**Comment by toplan** [comment]
model 的 effects 私有的话，那 model 咋个复用呢？

**Comment by hopperhuang** [comment]
@toplan model的复用一样可以extends， effest私有只是不想不相关的动作来调用effects。比如a板块是新闻，b板块是体育，effects私有，新闻板块就无法调用体育板块的effects去修改体育板块的数据。只是这样而已。
