### ISSUE TITLE
 没有加载css是怎么回事

### ISSUE THREAD

**Issue by somewhereMrli** [dvajs/dva#1050]
按照例子一步一步做的，可是最后
![image](https://user-images.githubusercontent.com/16183674/27990329-6aa5f450-6485-11e7-96ad-e4c7888e267a.png)
是没加载css么？

**Comment by sorrycc** [comment]
是没有 antd 的样式还是什么样式都没有，如果是 antd 的，需要配 babel-plugin-import，会自动引入响应组件的 css 。

**Comment by null22017** [comment]
我也是按照例子一步一步做的，和提问的同学遇到一样的问题。
https://ant.design/docs/react/practical-projects-cn
示例文档中如此说明：
**编辑 .roadhogrc，使 babel-plugin-import 插件生效。**
但是，我刚接触react，怎么样也找不到 这个文件：.roadhogrc，以至于无法使 babel-plugin-import 插件生效。 @sorrycc @somewhereMrli

**Comment by sorrycc** [comment]
新建的项目结构应该是[这样](https://github.com/dvajs/dva-cli/tree/master/boilerplates/app)，怎么会没有 `.roadhogc` 呢?

**Comment by null22017** [comment]
Thank you，刚切换成mac，不太适应，在隐藏文件里了，真是不好意思

**Comment by TongDaDa** [comment]
为什么 Production 中没有
