### ISSUE TITLE
如何单纯的绑定组件和model？

### ISSUE THREAD

**Issue by iceking112** [dvajs/dva#1056]
这边有一个业务场景，我想要在三个tab页中分别使用三个独立的页面功能（model，server，page），每个页面绑定各自的model，但是是没有链接path变化的，不通过route来做，想询问一下有没有什么办法可以链接组件和model？

**Comment by sorrycc** [comment]
`connect` 就是连接组件和 model 的，路由不是必选项。

**Comment by not3** [comment]
如何实现呢，有没有代码示例？

**Comment by iceking112** [comment]
@not3 
在pages里面
// 3. Model
app.model(require('routes/Category/model'));
app.model(require('routes/CategoryItem/model'));
app.model(require('routes/CategoryMark/model'));
注册3个不同的model
然后在routes里面建立3个页面，对应3个model，在route页面中使用connect连接相应的model即可
export default connect(({category}) => ({category}))(model)
