### ISSUE TITLE
roadhog server 开发环境如何使用browser history呢？

### ISSUE THREAD

**Issue by javaforlife** [dvajs/dva#1059]
请教下roadhog server 开发环境如何使用browser history呢？
现在遇到的问题是直接访问子url会报错，界面不显示任何东西。

**Comment by sorrycc** [comment]
> 界面不显示任何东西

应该是路由没匹配到，`roadhog server` 默认支持 browser history 的。

**Comment by javaforlife** [comment]
已解决
<script src="/index.js"></script> // index.js 使用绝对路径
