### ISSUE TITLE
dva应用如何优雅地组织项目目录结构

### ISSUE THREAD

**Issue by wonyun** [dvajs/dva#106]
今天第一次接触到dva，感觉让人眼前一亮；简化了项目中用action、store、reducers等目录来组织文件结构，避免来回切换导致思路的中断。但是使用dva的项目的目录结果是如何组织的呢，有什么最佳实践么？

**Comment by sorrycc** [comment]
用 [dva-cli](https://github.com/dvajs/dva-cli) 初始化。

```bash
$ npm i dva-cli -g
$ dva new myapp
$ cd myapp
$ npm start
```

然后在浏览器里打开 http://localhost:8989/ 。

**Comment by wonyun** [comment]
@sorrycc , dva-cli生成的就是推荐使用的目录组织结构呗

**Comment by sorrycc** [comment]
对。

**Comment by wonyun** [comment]
@sorrycc ，看dva文档说routes目录为`路由组件（页面纬度）`，但看到user-dashboard的demo，貌似这里都是container components，而components目录为`Presentational Component`，若是这样的话，container components组织到routes目录下有点不太直观，是不是有些误导的意思，虽然这些组件可以路由，用containers组织更合适呢？纯粹个人观点

**Comment by sorrycc** [comment]
原意是：route component 指的是 router.js 里关联的 component，可能是 container component，也可能是普通的 component 。然后 component 目录里可以存 container component，也可以存普通 component 。

**Comment by wonyun** [comment]
了解，非常感谢，准备用dva改造我们项目
