### ISSUE TITLE
有没有dva开源项目

### ISSUE THREAD

**Issue by heyunjiang** [dvajs/dva#1062]
想深入学习下dva、react一类技术，但是自己自学了这些，没有好的创意来实践它，代码组织不规范，就想参与下开源项目。之前用了示例demo中的antd-admin，用thinkphp替代了mock，写了一点，就不知道写什么了，https://github.com/heyunjiang/graduate

**Comment by liumin1128** [comment]
[https://github.com/liumin1128/ireader](https://github.com/liumin1128/ireader)
之前写的一个demo，有段时间了，参考下吧

**Comment by sorrycc** [comment]
目前没有统一收集。
