### ISSUE TITLE
动态加载路由，组件重复加载

### ISSUE THREAD

**Issue by Slice-dd** [dvajs/dva#1065]
路由代码
`
const routes = [
    {
      path: '/',
      component: IndexPage,
      getIndexRoute (nextState, cb) {
        require.ensure([], require => {
          registerModel(app, require('./models/products'))
          cb(null, { component: require('./routes/Products') })
        }, 'Products')
      },
      childRoutes: [
        {
          path: 'module1',
          getComponent (nextState, cb) {
            require.ensure([], require => {
              registerModel(app, require('./models/productsOne'))
              cb(null, require('./routes/ProductsOne'))
            })
          },
        }, {
          path: 'module2',
          getComponent (nextState, cb) {
            require.ensure([], require => {
              registerModel(app, require('./models/productsTwo'))
              cb(null, require('./routes/ProductsTwo'))
            })
          },
        }, {
          path: 'module3',
          getComponent (nextState, cb) {
            require.ensure([], require => {
              registerModel(app, require('./models/productsThree'))
              cb(null, require('./routes/ProductsThree'))
            })
          },
        }, {
          path: 'module4',
          getComponent (nextState, cb) {
            require.ensure([], require => {
              registerModel(app, require('./models/productsFore'))
              cb(null, require('./routes/ProductsFore'))
            })
          },
        }, {
          path: 'module5',
          getComponent (nextState, cb) {
            require.ensure([], require => {
               registerModel(app, require('./models/productsFive'))
              cb(null, require('./routes/ProductsFive'))
            })
          },
        }, {
          path: 'module6',
          getComponent (nextState, cb) {
            require.ensure([], require => {
               registerModel(app, require('./models/productsSix'))
              cb(null, require('./routes/ProductsSix'))
            })
          },
        }, 
`

是这样的，打开页面之后，会加载getIndexRoute 里面的加载的组件。但是我当我切换到module1的时候，加载的依然是getIndexRoute 里面获取的组件，然后我切换到module2的时候，就会刚刚没有加载的module1里面的组件，很奇怪。。。求大神解惑啊

**Comment by trexguo** [comment]
这样看没什么问题，把registerModel()贴出来
