### ISSUE TITLE
Error: spawn cmd ENOENT

### ISSUE THREAD

**Issue by hanagm** [dvajs/dva#107]
在windows环境下执行
dva new myapp 报错

系统环境: win7 64位

![image](https://cloud.githubusercontent.com/assets/6668952/18899907/f386435c-856e-11e6-983f-9e4e8b5531e3.png)

**Comment by clearbug** [comment]
同样有这个问题，尝试了多个node版本都是这样

**Comment by loongier** [comment]
为这边也是同样的问题，但添加C:\Windows\System32\环境变量后，问题解决了，可以参考
http://stackoverflow.com/questions/28624686/get-spawn-cmd-enoent-when-try-to-build-cordova-application-event-js85
