### ISSUE TITLE
roadhog build 后 index.html 打开一片空白？？？？

### ISSUE THREAD

**Issue by dkvirus** [dvajs/dva#1070]
使用 roadhog build 不是应该对项目进行打包成静态代码吗，然后放到服务器下应该能跑的才对啊，可是现在运行之后， index.html 浏览器打开一片空白，就没有人遇到这问题吗？？？？？？？？？？？

**Comment by dkvirus** [comment]
其它都开发完了，就差这最后一步了，死活不成功，了解了一下,roadhog 不是替代 webpack 简化配置进行代码打包吗，有没有知道的帮忙解答一下啊。

**Comment by lanxxg** [comment]
如果你用的是`browserHistory` 服务器配置可参考 https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

**Comment by dkvirus** [comment]
试了好久，发现在 tomcat 成功不了，使用的 nginx，配置了反向代理，现在已经可以跑起来了。不过又出现了新的问题，样式乱了，不知道是打包时没打上还是啥问题。

**Comment by dkvirus** [comment]
折腾半天还是自己给弄出来了，记录一下，给其它遇到该问题的人一个参考吧：
使用 npm run build 之后得到的 dist 目录里面都是静态资源，在 index.html 里面需要手动引入下样式文件
```
<html lang="en">

<head>
  <meta charset="UTF-8">
  <!-- 这句话要自己加，才会用到样式 -->
  <link rel="stylesheet" href="/index.css">
</head>

<body>
  <div id="root"></div>
  <script src="/index.js"></script>
</body>

</html>
```
