### ISSUE TITLE
dva如何个性定制主题色

### ISSUE THREAD

**Issue by likepearl** [dvajs/dva#1071]
我现在有个项目是dva框架。

要添加一个配置主题色的模块
模块的功能是可自由选择主题色，配置项目的主题色。
 请问dva编译主题样式是什么原理？要实现这个功能需要哪些步骤？

**Comment by nihgwu** [comment]
dva如何请求数据？
dva请求数据是什么原理？要请求数据需要哪些步骤？

**Comment by sorrycc** [comment]
主题定制不在 dva 所包含的范围之内。
