### ISSUE TITLE
dva是否支持服务端渲染，或者说可以较为方便的实现服务端渲染？

### ISSUE THREAD

**Issue by liumin1128** [dvajs/dva#1072]
如题，我没有找到实现ssr的相关介绍，最近需要搞seo，如果有比较快捷的解决方案请留言，O(∩_∩)O谢谢。

**Comment by marswong** [comment]
可以参考云谦的 [dva-boilerplate-isomorphic](https://github.com/sorrycc/dva-boilerplate-isomorphic)
