### ISSUE TITLE
dva 有没有单独使用的方式，是否必须配合dva-router才能使用？

### ISSUE THREAD

**Issue by marszhou** [dvajs/dva#1073]
原有项目用react-router，有没有不用app.router入口的方式？

文档里有
`app.router(() => <App />)`

但我只想在整个react项目的某一局部使用dva，这么做有可能么？这样写仍然需要用app.start，就不知道怎么写了

**Comment by marszhou** [comment]
我知道了app.start()不带参数返回一个react component

**Comment by bldf** [comment]
解决了没啊，我也遇到了这个问题

**Comment by LukerSpringtree** [comment]
> 解决了没啊，我也遇到了这个问题

我知道了app.start()返回一个react component
dva/router实际上是react-router

楼主答案已经 写在 这边了 自己试一试

但是不推荐 这样用.

**Comment by usercao** [comment]
> 但是不推荐 这样用.

@LukerSpringtree 请问这样用会有什么风险吗？
