### ISSUE TITLE
跟prop-types的检验有关 一大堆的warning

### ISSUE THREAD

**Issue by Slngle** [dvajs/dva#1075]
![image](https://user-images.githubusercontent.com/8002651/28316245-a1b0dc8c-6bf4-11e7-8203-317304813bdd.png)

发生如题的warning 
main.js:14317 Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types

好像跟prop-types的检验有关 一大堆的warning   这个是什么原因呢

**Comment by Slngle** [comment]
按照后面的github地址配置了也不行

**Comment by vipcxj** [comment]
依赖的原因，除了等第三方库自己升级外没得救~ 无视这个warning就好，反正是兼容性的提示

**Comment by nalantianyi** [comment]
第三方库导致的warning选择无视，自己项目代码中的建议修改下。

**Comment by yautah** [comment]
下个版本，PropTypes会从react核心库里移动到一个独立的proptypes库里
这个版本无视就好了
