### ISSUE TITLE
saga 组合

### ISSUE THREAD

**Issue by lllluke1993** [dvajs/dva#1077]
在saga内部yield put时，generator并不会等待执行结果；redux-saga给的建议是用 yield call来调用effect，请问在dva中可以通过yield call的方式来等待子effect的执行吗？

**Comment by sorrycc** [comment]
可以手动结合 take 和 put 来实现同步。或者等 dva@2，然后可以通过约定来解决这个问题，用例： https://github.com/dvajs/dva-core/blob/0fa6888/test/effects-test.js#L69-L70 。

**Comment by lllluke1993** [comment]
恩恩，感谢帮助，期待dva2啊~
