### ISSUE TITLE
dva可以通过less的方式引入antd样式吗？

### ISSUE THREAD

**Issue by likepearl** [dvajs/dva#1078]
@import "~antd/dist/antd.less";   
为什么我这样引入没有成功

**Comment by likepearl** [comment]
我在less文件里引用的

**Comment by likepearl** [comment]
要加webpack.config吗？

**Comment by likepearl** [comment]
我用的是.roadhogrc

**Comment by marswong** [comment]
`roadhog` 已经内置对 `less` 的处理，到 [Ant Design](https://github.com/ant-design/ant-design/issues) 提供一个可以复现的 demo 吧

**Comment by likepearl** [comment]
不能这样子引入吗？@import "~antd/dist/antd.less";
