### ISSUE TITLE
换成browserHistory，路由不起作用了

### ISSUE THREAD

**Issue by linginging** [dvajs/dva#108]
```
import { browserHistory } from 'dva/router';

// 1. Initialize
const app = dva({
history: browserHistory,
});

<Router history={history}>
  <Route path="/" component={IndexPage} /> 
  <Route path="/test" component={Test} /> 
</Router>
```

**Comment by hanagm** [comment]
我也提交了一个类似的bug，，竟然给我删除了。。。我很想知道哪错了..

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues/103#issuecomment-249780319

**Comment by sorrycc** [comment]
@hanagm 理解下我说的，有疑问可以 `reopen` 的。

**Comment by linginging** [comment]
已经搞定
先npm install dora-plugin-browser-history --save-dev
```
  "scripts": {
    "start": "dora --plugins \"proxy,webpack,webpack-hmr,browser-history?index=/src/index.html\"",
    "build": "atool-build",
    "test": "atool-test-mocha ./src/**/*-test.js"
  }
```

**Comment by wonyun** [comment]
@sorrycc ，@linginging 
我使用了dora的这个browser-history插件，但是感觉不好使啊，我的页面虽然没有报not found，但是指定index的里面的js、css都404啊。
比如我当前的页面url：`http://127.0.0.1:8989/dataSource/create`然后刷新，对应的js、css资源404导致页面白屏，指定browser-history的index的html内容用下面url形式加载资源的：
```html
<script src="common.js"></script>
<script src="index.js"></script>
```
当前页面刷新时network出现如下错误信息：
<img width="661" alt="err" src="https://cloud.githubusercontent.com/assets/4994497/18947533/0c2a7778-8666-11e6-9179-eeb503e71fe3.png">

请问这样问题是出现在哪里了？？？

**Comment by sorrycc** [comment]
```diff
- <script src="common.js"></script>
- <script src="index.js"></script>
+ <script src="/common.js"></script>
+ <script src="/index.js"></script>
```

**Comment by wonyun** [comment]
@sorrycc ，开发过程需要这么改，编译上线应该需要改回来吧？

**Comment by sorrycc** [comment]
这个要根据你们的开发模式来配了，每个团队会不同。可以灵活使用 hosts、proxy 等工具。

**Comment by Danjavia** [comment]
It works correctly but in productions it fails.

```
"scripts": {
    "start": "dora --plugins \"proxy,webpack,webpack-hmr,browser-history?index=/src/index.html\"",
    "build": "atool-build",
    "test": "atool-test-mocha ./src/**/*-test.js"
  }
```
