### ISSUE TITLE
请问是否官方创建的demo，现在.roadhogrc.mock是否已无法使用？

### ISSUE THREAD

**Issue by 18559909452** [dvajs/dva#1081]
访问都没识别出这个代理。。

**Comment by 18559909452** [comment]
挺急需的，看到了请帮忙回答

**Comment by sorrycc** [comment]
访问啥了？roadhog 的 mock 并非通过代理的方式实现的。

**Comment by 18559909452** [comment]
@sorrycc 
我就做这几步：
1、dva new dva-quickstart
2、npm install
3、const app = dva({
         history: browserHistory,
     });
4、.roadhogrc.mock.js
![image](https://user-images.githubusercontent.com/18180469/28446891-426b765c-6e00-11e7-9f43-c80afe4bd118.png)
5、tnpm start
问题是访问：http://localhost:8000/api/unified/auth/doAuth，
![Uploading image.png…]()
帮忙看看哈

**Comment by sorrycc** [comment]
`.roadhogrc.mock.js` 里写了什么?

**Comment by 18559909452** [comment]
![image](https://user-images.githubusercontent.com/18180469/28446934-72ecb5b6-6e00-11e7-9b44-8ae8f121a709.png)
只写了这个

**Comment by sorrycc** [comment]
`api` 前加个 `/` 试试

**Comment by 18559909452** [comment]
太感谢了；居然疏忽了这个
