### ISSUE TITLE
官方文档的项目实战启动会报错

### ISSUE THREAD

**Issue by oldturkey** [dvajs/dva#1082]
https://ant.design/docs/react/practical-projects-cn  

chrome报错：Warning: Each record in table should have a unique `key` prop,or set `rowKey` to an unique primary key.                        table中的record没有 unique key 属性

**Comment by oldturkey** [comment]
在table里增加了 rowKey="id"  但是页面没有渲染antui。  不知道原因出在哪， 是因为官方文档的版本是7.0的，现在已经是7.8了么？

**Comment by sorrycc** [comment]
antd 的问题请到 https://github.com/ant-design/ant-design/issues 提问。

**Comment by msdlisper** [comment]
https://dvajs.com/guide/getting-started.html#connect-%E8%B5%B7%E6%9D%A5 
这样目前也有这样的问题
解决: 在components/ProductList.js里加rowKey:
``` js
<Table rowKey="id"
      columns= {columns}
      dataSource={products}
    >
    </Table>
```
