### ISSUE TITLE
12步30分钟

### ISSUE THREAD

**Issue by huangchaofei** [dvajs/dva#1083]
已经按作者的走到第六步，全部做了修改，但是没有报错主页也没有变化，还是一个小丑，怎么回事

**Comment by marswong** [comment]
第四步已经报错了，你头也不回就这么走到了第六步🙈

**Comment by marswong** [comment]
教程有问题，还没有更新，建议直接运行 [dva-example-user-dashboard](https://github.com/dvajs/dva-example-user-dashboard)，对照着教程来学习：）

**Comment by sorrycc** [comment]
新建了路由，所以要切换到对应路由的页面才行，首页不会变的。
