### ISSUE TITLE
redux状态的持久化，保证页面刷新或者关闭后能恢复状态

### ISSUE THREAD

**Issue by shengbeiniao** [dvajs/dva#1084]
代码如下
```
let initialState={};
if(localStorage.getItem('store')){
  initialState=JSON.parse(localStorage.getItem('store'));
}

// 1. Initialize
const app = dva({
  history: browserHistory,
  initialState:initialState
});

window.onunload=function () {
  localStorage.setItem('store',JSON.stringify(app._store.getState()));
};
```

**Comment by htlhenry** [comment]
`window.onunload`只是页面关闭事件，如果要刷新要加上 `window.onbeforeunload`。

**Comment by marswong** [comment]
这个想法很久以前在 `redux` 社区就已经有好多人争论过，这样做仅仅是保存了 `store`，没什么实际意义，反而带来了更多问题：
* 怎么保证数据的实时性／时效性？
* 一个超级大的 `store` 你怎么存储？

**Comment by sorrycc** [comment]
如果要保存，别放 `window.onunload`，放 [onStateChange](https://github.com/dvajs/dva/blob/master/docs/API_zh-CN.md#onstatechangefn) 里吧。

**Comment by shengbeiniao** [comment]
@sorrycc onStateChange每次状态变化都会触发，保存在localStorage相当于一次IO操作，而state改变只是内存变化，严重影响效率。
@htlhenry onbeforeunload这个是IE的事件，chrome不支持。我实际测试过，onunload没问题
@marswong 数据的实时性代码已经保证了，我在很大的store里测试过，几十个页面，挂了几十个list，没有问题，一般性一个系统的store不会超过5M，如果超了就需要分拆页面了，像阿里云那样，一个子系统一个spa.

**Comment by shengbeiniao** [comment]
参考这篇文章，(Redux从设计到源码)[https://tech.meituan.com/redux-design-code.html]，Redux本质上就是一内存数据库

**Comment by shengbeiniao** [comment]
参考这篇文章，[Redux从设计到源码](https://tech.meituan.com/redux-design-code.html)，Redux本质上就是一内存数据库

**Comment by shengbeiniao** [comment]
今天遇到个问题，因为dva inititalState 优先级比model state高，整个状态持久化后，model State的结构改变，例如添加新key，会因为缓存导致无法应用，此方案有缺点。

**Comment by htlhenry** [comment]
我也遇到了这个问题，所以我尝试将单个namespace缓存。

**Comment by lsdiao** [comment]
@shengbeiniao 请问后面有找到方案解决嘛
