### ISSUE TITLE
出错后如何调试

### ISSUE THREAD

**Issue by steem** [dvajs/dva#1085]
请问出现如下图的js错误后，系统会出现提示消息。请问配置哪个地方，可以看到出错的代码行和文件名

![出错截图](https://user-images.githubusercontent.com/121950/28500344-430ca64e-6ff9-11e7-89d0-b3e5d0524940.png)

**Comment by sorrycc** [comment]
onError hook 里把出错信息抛出来就能在控制台里看到了。

**Comment by steem** [comment]
好的，看到相应的代码了
