### ISSUE TITLE
mock api 带有query参数时该如何配置

### ISSUE THREAD

**Issue by mjfunny** [dvajs/dva#1086]
参考了[roadhog mock 文档](https://github.com/sorrycc/roadhog#mock)的例子后写了demo如下;
`mock/user.js`
```
module.exports = {
  'GET /api/users/list': function (req, res) {
    res.json({
      success: true,
      data: dataBase,
    });
  },
  'GET /api/users': function (req, res) {
    res.json({
      success: true,
      data: userDetail.data,
    });
  },
};
```
`services/user.js`
```
import qs from 'qs';
import request from '../utils/request';

export async function query() {
  return request('/api/users/list');
}

export async function detail({ id }) {
  return request(`/api/users?${qs.stringify({ id })}`);
}
```
　　目前mock了两个接口, `/api/users/list` 请求用户列表已经跑通. 现在有个疑问,就是当调用带有query参数的接口, 比如上面的detail接口,带有参数id.
　　那么,在`mock/user.js` 文件中, 我该如何表示这类带有参数的api? 我现在写的是`/api/users`, 这样的话,
在chrome network中显示如下`Request URL:http://localhost:8000/api/users?`, 能够获得mock的数据,但是url并未完全显示? 后面的参数.
　　请问如何在`mock/user.js`中设置这类带有参数的mock api.

**Comment by sorrycc** [comment]
`query` 信息拿不到吗? 打印下 `req` 对象看。背后用的是 express，也可以看下 express 的 api，http://expressjs.com/en/api.html#req 。

**Comment by mjfunny** [comment]
打印了下,确实`req.query`为`{ }`,是在`effects 中 yield call 调用接口时传参出了点问题`,感谢指点!
