### ISSUE TITLE
antd-mobile引用报错

### ISSUE THREAD

**Issue by luajoy** [dvajs/dva#1087]
描述：使用\<div\>等原生的html标签没问题，引入antd-mobile标签就报错，不知道是什么原因
报错：
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `IndexPage`.

代码：
import React from 'react';
import {Button} from 'antd-mobile';
import { connect } from 'dva';
function IndexPage() {
  return (
    \<Button type="primary" size="large" >按钮\</Button>
);
}
IndexPage.propTypes = {
};

export default connect()(IndexPage);

**Comment by sorrycc** [comment]
`import {Button} from 'antd-mobile';` 没取到，取过来的值是 `undefined`，报错信息里说了。

**Comment by luajoy** [comment]
非常感谢，导入antd-mobile的时候按照文档配置babel-plugin-import就可以了
