### ISSUE TITLE
希望提供 model  init hook ,  以便于初始化数据

### ISSUE THREAD

**Issue by sandwich99** [dvajs/dva#109]
应用部分 model 的数据全局共享的, 例如 用户基本信息 / 省市区城市
完美情况是在 dva 初始化时传入 initialState 时传入
但是实际并不能也没必要做到同构应用,  为了更好的代码组织性 和 性能 也不希望在应用初始化之前通过 ajax 加载.
理想情况是 model 初始化时提供一个 hook ,  这样可以触发异步加载此类数据

```javascript
const model = {
    namespace: 'user',

    init({ dispatch }) {
        dispatch('fetchUser');
    }
}
```

**Comment by sorrycc** [comment]
subscriptions 就是在初始化时触发的，不知和你描述的 init 有区别吗?

**Comment by sandwich99** [comment]
囧, 抱歉.. , 对 subscriptions 理解不够. 示例里每次都是和 history.listen 混用的, 有点混淆了

非常感谢!

**Comment by wonyun** [comment]
@sorrycc 想请教一下，什么情况下dva初始应用时才需要配置这个initialState状态，另外，在配置这个initialState时是否是按照如下格式配置：
```javascript
dva({
  namespaceName:  {...} //对应某个namespace下的state
})
```

**Comment by sorrycc** [comment]
数据来自服务器端同步输出时给 initialState，格式为以 model 的 namespace 为 key 的 Object 。

```js
const app = dva({
  initialState: { count: 1 }
});
app.model({
  namespace: 'count',
  state: 0,
});

// count 初始化为 1，而不是 0。
```

**Comment by wonyun** [comment]
got it! thx
