### ISSUE TITLE
怎样用onReducer来初始化所有的model/state

### ISSUE THREAD

**Issue by yueleiMaster** [dvajs/dva#1090]
试了下这段代码 但是一直报错
const app = dva({
  onReducer: reducer => {
    return (state, action) => {
      if (action.type === 'RESET') {
        return initialState;
      }
      return state;
    };
  }
});

**Comment by sorrycc** [comment]
参考下这个，https://github.com/dvajs/dva/blob/ff197ca/test/reducers-test.js#L91

**Comment by yueleiMaster** [comment]
![image](https://user-images.githubusercontent.com/25242674/28606423-9964215e-7209-11e7-95f5-cfc21356b26e.png)
报这个错是怎么了？
