### ISSUE TITLE
whether to provide the app.model listening method?

### ISSUE THREAD

**Issue by yangbin1994** [dvajs/dva#1091]
eg
```javascript
dva({
 onModalRegister({effects, reducers}) {
 ...
 }
})
```

**Comment by sorrycc** [comment]
Why do you need this?

**Comment by yangbin1994** [comment]
I'm going to do the following ,eg
```javascript
dispatch({
 type: 'user/login',
 payload: { username, password }
})
```
=>
```javascript
dispatch(actionCreators.user.login({ username, password }))
```

**Comment by sorrycc** [comment]
You can use actionCreator now, and actionCreator does not matter with the above feature.

**Comment by yangbin1994** [comment]
Can you give me an example? I'm probably saying that actionCreator is generated through the model structure, which can continue to be used by bindActionCreators
