### ISSUE TITLE
redux-persist恢复数据比model的subscriptions步骤慢

### ISSUE THREAD

**Issue by young-lam** [dvajs/dva#1093]
由于数据缓存在本地了，通过model的subscriptions获取uri去请求数据时需要判断数据是否已经缓存，但是subscriptions比数据恢复快，因此这时拿不到缓存进去判断。请问怎么解决

**Comment by yangbin1994** [comment]
直接获取localStorage可以吗

**Comment by jerexyz** [comment]
同样碰到了这个问题

**Comment by iceOolongTea** [comment]
JS同步的问题？写个递归的定时器?
var storage = 0;
function a (){
  clearTimeout(b);
  storage ++;
  if( storage !== 2){
    var b = setTimeout(a,1000);
  }
  else{
    console.log('发送请求');
  }
}

**Comment by iceOolongTea** [comment]
JS同步的问题？写个递归的定时器?
`var storage = 0;
function a (){
  clearTimeout(b);
  storage ++;
  if( storage !== 2){
    var b = setTimeout(a,5000);
  }
  else{
    console.log('发送请求');
  }
}`

**Comment by iceOolongTea** [comment]
写个递归的定时器?
var storage = 0;
function a (){
  clearTimeout(b);
  storage ++;
  if( storage !== 2){
    var b = setTimeout(a,5000);
  }
  else{
    console.log('发送请求');
  }
}

**Comment by czewail** [comment]
同问

**Comment by blackkey520** [comment]
同问

**Comment by lhr000lhr** [comment]
is there any update?

**Comment by MonkeyDwwl** [comment]
> 由于数据缓存在本地了，通过model的subscriptions获取uri去请求数据时需要判断数据是否已经缓存，但是subscriptions比数据恢复快，因此这时拿不到缓存进去判断。请问怎么解决

你好，请问解决这个问题了吗？
