### ISSUE TITLE
关于服务端渲染

### ISSUE THREAD

**Issue by chenjinhao** [dvajs/dva#1094]

**Comment by chenjinhao** [comment]
手机输入，按错了。我想问个小问题，服务端渲染只能在node环境下之类的操作吧，编译后的静态是无法完成改功能的吧，虽然说dva和渲染没关系，但是当采用全局都是函数式编程的情况下，有办法在roadhog服务端运行，全局通过配置的形式一键切换为服务端渲染吗？

**Comment by sorrycc** [comment]
服务端渲染建议使用 next.js + dva 的组合。
