### ISSUE TITLE
如何在退出后初始化state中的数据

### ISSUE THREAD

**Issue by 4wei** [dvajs/dva#1099]
退出后再点击登录,数据还是之前的,这需要怎么处理,需要对一个个models中state从新初始化吗,还想非常麻烦啊,有什么好的思路吗

**Comment by sorrycc** [comment]
可以通过 onReducer hook 实现，参考这个用例：https://github.com/dvajs/dva-core/blob/7e6e89b/test/reducers-test.js#L60-L93

**Comment by 4wei** [comment]
谢谢,搞定
