### ISSUE TITLE
English support

### ISSUE THREAD

**Issue by mclouvem** [dvajs/dva#11]
Hi @sorrycc you are making a really nice job here, but it is quite difficult to follow all your ideas. Is there some plan to release an English version for project's documentation?

Thanks!

**Comment by sorrycc** [comment]
Thanks for attention, I will write documentation in English after 1.0 is released.

**Comment by mclouvem** [comment]
@sorrycc It would be really good. Your project is great. I'm a big fan of Choo approach, its namespace state is awesome.
Keep going, I'm looking forward to get 1.0 and try it out...

**Comment by sorrycc** [comment]
Hi, it's done. There are english version of readme, concept and getting-started now.

**Comment by samayo** [comment]
Can't find the english doc for some reason
