### ISSUE TITLE
mock 接口太辛苦，直接代理线上或线下的数据

### ISSUE THREAD

**Issue by raisezhang** [dvajs/dva#110]
RT~   

最近在做迁移工作，接口啥的服务端的已经存在（一般正常的开发流程也是后端在测试环境加完后开发），如果说手动 mock 接口太麻烦，  部署到测试环境文件太大又不方便...

所以能不能搞一把访问地址是本地的，但所有的接口全部访问测试或线上环境！ 

实现思路啥的很简单， 拦截接口 -> 拼装 url -> 抓取数据 -> 返回， 其中有一个登录cookie的问题，目前我是写在了配置文件中，如果想做的灵活一点的话，自己可以写一个获取 cookie 的接口（加个随机验证 token之类）！  

实现代码如下：  （代码太糙，大家凑活着看 -_-）

[代码预览效果太差，戳我](https://github.com/raisezhang/react/blob/master/dvajs_mock_remote.js)

依赖：npm install request    [链接](https://github.com/request/request)
使用：文件放置 ./mock 文件夹下， dvajs 会自动遍历文件夹下的文件并执行~

**Comment by sorrycc** [comment]
👍

**Comment by edire** [comment]
亲测可用，但我没有手动安装 request 依赖

**Comment by sorrycc** [comment]
https://github.com/dora-js/dora-plugin-proxy#规则定义
可以 forward 到你队友的服务器。
