### ISSUE TITLE
如果项目是多页应用，我应该如何配置能在执行build的时候不同的页面打包到dist里不同的文件夹

### ISSUE THREAD

**Issue by BenAnn** [dvajs/dva#1100]
之前使用webpack，在webpack配置项中通过不同的启动命令（npm run start：a；npm run start：b）和不同的打包命令（npm run build：a；npm run build：b）实现一个大项目的多页开发，并且最后打包到dist文件夹不同页面也会建立不同的文件夹，对不同页面做了区分，方便管理
现在项目打算用dva，还想用之前多页的开发方式，在看文档还有issues后发现，可以通过设置"multipage": true，然后"entry": ["src/pages/index.js","src/pages/login.js"]写成这种数组，通过写多个
![image](https://user-images.githubusercontent.com/17406160/28760632-104af58e-75db-11e7-8900-67b2fff9133e.png)还有多个router就实现了开发多页
现在就有一个问题，npm run start命令后面并不带对应页面名，无法实现每次只起某个页面的服务（一个npm run start把所以页面的服务都起来了），对应的npm run build就把所以页面的打包文件都扔到dist文件夹里了，由于每次打包都是把久的全删所以每次打包完所以文件更新日期都一样，不好对不同页面做区分，并且在使用require.ensure来实现按需加载的时候，多个页面的xx.async.js文件不会冲突吗（名字都一样），并且页面一多，可能这个文件夹里有上百个文件，如果只改某一页面的一点，就需要自己在这么多文件里找对应的几个文件显然不是很合适
不知道有没有人遇到这样的问题，有没有什么解决办法

**Comment by sorrycc** [comment]
多页应用用 next.js + dva 的组合吧，next.js 可以导出静态文件的。例子：https://github.com/dvajs/dva/tree/master/packages/dva-example-nextjs
