### ISSUE TITLE
还是之前,退出后数据初始化的问题

### ISSUE THREAD

**Issue by 4wei** [dvajs/dva#1101]
使用
![tim 20170731164558](https://user-images.githubusercontent.com/12912875/28769894-daa5269a-760f-11e7-916d-d12eca2ff6fe.png)

提供了很好的思路,不过在使用中发现,如果保存原始state是在app.start()之后,state的数据有可能已经被更改过了
![tim 20170731155649](https://user-images.githubusercontent.com/12912875/28769986-34e9d9ca-7610-11e7-8bcf-899aa88bbf34.png)

![tim 20170731155622](https://user-images.githubusercontent.com/12912875/28770042-5525726c-7610-11e7-8298-d268105d67ad.png)

可在app.start()之前就把原始的state保存下来,发现app._store.dispatch()与app._store.getState()还不可使用,
现在通过在app.model() 之后,手动通过app._models保存原始的state,,请问这个思路是对吗,有没有更好的办法,在app启动后保存下原始state,方便后面恢复?

**Comment by sorrycc** [comment]
`saveAndLoad` 里可以过滤数据的，不一定要全部保存。
