### ISSUE TITLE
用了dva，不知道后端代码在哪里写了。

### ISSUE THREAD

**Issue by yinxuan1128** [dvajs/dva#1102]
才开始接触前端。看了下dva的demo，例子里面都是用的mock，然后接口都在config里面定义，现在想写后端代码，从数据库获取数据，不知道该写在哪里，如何暴露接口出来，也不知新手的问题讲没讲清楚。

**Comment by sorrycc** [comment]
后端代码和 dva 无关，可以直接写后端可以不用管 mock 这一层。

**Comment by yinxuan1128** [comment]
后端代码是和dva在一个服务器里吗？才开始搞这个，确实不是太明白。dva-cli创建的程序框架里是有express吗？在express里可以通过router.get,router.post定义类似接口的东东，在dva框架里就看不太明白了。能否有个具体例子看看呢？谢谢。

**Comment by sorrycc** [comment]
后端代码需要你自己实现的，dva-cli 创建的不包含服务端以及 express 。

**Comment by longzhaobi** [comment]
是java的话，就写到eclipse或者idea，启动tomcat后，dva前端就可以访问你后端提供的接口获取json数据。
