### ISSUE TITLE
react-native升级到0.46.4后无法使用dva

### ISSUE THREAD

**Issue by liulinzhe** [dvajs/dva#1107]
error: bundling failed: "Unable to resolve module `react/lib/React` from `/Users/dry-game/work/react/game/node_modules/react-dom/lib/ReactMount.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."

react-dom已经安装了，但是Reload后还是会提示这个错误，按说明清除node_modules和cache后运行问题依然存在，请问有碰到类似问题的朋友吗？

基本上就是按照下面这个操作来进行的
react-native init demo
cd demo
npm install dva
npm install react-dom

import dva from 'dva/mobile';

**Comment by liulinzhe** [comment]
目前能确定的是升级了react 和 react-native导致的，但是具体还不确定是怎么回事儿。有人帮忙看一下吗？

**Comment by nihgwu** [comment]
我一直在用dva，0.46 0.47 都没有问题，建议你使用 1.3 版本，可以不用安装 react-dom

**Comment by liulinzhe** [comment]
@nihgwu 感谢您的建议
