### ISSUE TITLE
页面跳转问题

### ISSUE THREAD

**Issue by jackyren0** [dvajs/dva#1109]
models/main.js文件中

```
subscriptions: {
  setup({dispatch}) {
    dispatch({type: 'query'});
  },
},
effects: {
  *query({}, {call, put, select}) {
    //yield call(userlogin);
    //...
    yield put(routerRedux.push('login');
  },
```

routes/main.js文件中
render了一些组件

main是入口
如果models/main.js中不执行yield call(userlogin);，可以直接跳转到login，如果放开注释，会先render main中的组件，一闪以后跳转到login。
照着zuiidea/antd-admin学习的，逻辑一样，zuiidea/antd-admin却没有这种情况。
是配置的原因吗？

另外zuiidea/antd-admin中跳转login用的window.location = `${location.origin}/login?from=${from}`，如果我用这个方法也会先render main再跳login，他的就不会。

**Comment by sorrycc** [comment]
所以，你是想 login 判断结束前不想要 render main 中的组件？可以配个 state 比如 `isRenderMain` 决定是否渲染，login 结束后把这个值设为 true 。

**Comment by jackyren0** [comment]
我之前说的不清楚
main是入口，有models/main.js和routes/main.js。
models/main.js文件中
subscriptions: {
  setup({dispatch}) {
    dispatch({type: 'query'});
  },
},
effects: {
  *query({}, {call, put, select}) {
    //yield call(userlogin);
    //...
    yield put(routerRedux.push('index');
  },
在routes/main.js中打了log
我访问http://localhost:8000/，
发现进入一次main.js，location.pathname是/index
如果放开yield call(userlogin);的注释，发现两次进入routes/main.js，location.pathname分别是/和/index。
以“/”进入routes/main.js的原因是什么？yield的调用原因？
怎么能只以‘/index’进入routes/main.js？

**Comment by trexguo** [comment]
@jackyren0 把router配置贴出来

**Comment by jackyren0** [comment]
是我router配置和处理代码写的不好的问题，此问题可以关啦~
谢谢各位！
