### ISSUE TITLE
请问连续发两个请求应该怎么处理?

### ISSUE THREAD

**Issue by rrandom** [dvajs/dva#111]
我遇到这样的场景：某一个页面中需要连续发送两个请求，其中第二个请求的结果取决于第一个请求的动作，是不是这样的话写页面用stateless function不如用class 啊

**Comment by sorrycc** [comment]
在 effect 里 `yield call()` ? 没有限制异步逻辑数量的。

**Comment by rrandom** [comment]
那在组件里有先后顺序的dispatch可以吗？类似promise的，比如
```
dispatch({type: 'action1'})
.then((data)=>{
  dispatch(type:{'action2'}, payload: data)
})
```

**Comment by sorrycc** [comment]
不支持 `.then` 的写法，组件里只 dispatch action，然后后续的异步逻辑放到 effect 里。

**Comment by rrandom** [comment]
哦， 明白了，感谢~~
