### ISSUE TITLE
"Promise is undefined." popup in IE 11 Browser when access web-app based antd

### ISSUE THREAD

**Issue by simonclouds** [dvajs/dva#1110]
As you can see in Pic:
![promise-is-undefind](https://user-images.githubusercontent.com/2662533/28952773-0b3fb7ea-7906-11e7-9db5-698bb9fe9b6d.png)

**Comment by sorrycc** [comment]
Try to include [babel polyfill](https://babeljs.io/docs/usage/polyfill/) ?
