### ISSUE TITLE
使用browserHistory时候 如何设置forceRefresh

### ISSUE THREAD

**Issue by super-ai** [dvajs/dva#1111]
希望每次回退后 页面保持原来的状态 不做刷新

**Comment by sorrycc** [comment]
默认应该是不刷新的。回退后是路由发送了变化，刷新应该是你订阅了路由变化去请求导致的，检查下自己的代码看。

**Comment by super-ai** [comment]
A页面
browserHistory.push({ pathname: '/province', state: {areaname,dt} });
跳转到了B页面

B页面()
browserHistory.go(-1)
回到了A页面

此时A页面会刷新

我当前配置都是项目创建时候的默认配置 你说的订阅了路由 在哪进行配置

index.js
...
app.router(require('./router'));
...

router.js
…
function RouterConfig({ history }) {
  return (
    <Router history={history}>
      <Route path="/" component={IndexTabs} />
      <Route path="/province" component={Province} />
      <Route path="/district" component={District} />
    </Router>
  );
}
...

**Comment by super-ai** [comment]
router.js
…
```
function RouterConfig({ history }) {
  return (
    <Router history={history}>
      <Route path="/" component={IndexTabs} />
      <Route path="/province" component={Province} />
      <Route path="/district" component={District} />
    </Router>
  );
}
```
...

**Comment by nikogu** [comment]
可以通过生命周期方法（componentWillReceiveProps 等）自己控制是否渲染。
