### ISSUE TITLE
import DataTable from './DataTable'

### ISSUE THREAD

**Issue by wdssss** [dvajs/dva#1114]
1. 这个import好奇怪.. 后面跟的既不是相对路径,也不是绝对路径.. 而是一个相对文件夹. DataTable文件夹底下也没有index.js...  
2. 那他去引用的是什么文件?  这是什么语法啊

**Comment by nihgwu** [comment]
跟 dva 有半分钱关系？

**Comment by wdssss** [comment]
我没说和DVA有半毛钱关系 ....

**Comment by wdssss** [comment]
我只是问这是什么语法...

**Comment by nihgwu** [comment]
这里是问这种问题的地方？

**Comment by nikogu** [comment]
`./xxx` 是相对路径，只不过省略了后缀名，这个在 webpack 里面可以配置，具体请参看 webpack 文档
