### ISSUE TITLE
dva有什么思想吗？

### ISSUE THREAD

**Issue by cisen** [dvajs/dva#1115]
居然不像antd一样一堆格式限制，赞！赞！赞！

比如redux是单向数据流的全局状态管理器，sagas是异步管理器。dva的，看了文档和源码，感觉只是为了简化redux全家桶的上手速度而做的封装，理解不到dva大概是什么的一个概念，求指教。

**Comment by marswong** [comment]
不知道为何 antd 都可以躺枪，完全是两个世界的东西。。。

《[支付宝前端应用架构的发展和选择](https://github.com/sorrycc/blog/issues/6)》已经有非常详细的介绍

**Comment by cisen** [comment]
antd提个issues好麻烦。。。这里好方便，并不指代码。上面那篇文章我觉得解决不了我的问题

**Comment by marswong** [comment]
以后 dva 应该也会考虑向 antd 学习的。。。所以你的问题到底是什么。。。

**Comment by nikogu** [comment]
@cisen antd 格式的限制是更好的规范提 issue  同学的表达，让维护者更高效率的理解，并且让 issue 能够沉淀帮助更多的人。
