### ISSUE TITLE
希望修改css-modules的配置，每次写styles.xxx异常冗余

### ISSUE THREAD

**Issue by ouzhou** [dvajs/dva#1116]
查看了一下css-modules的插件发现babel-plugin-react-css-modules这个插件可以解决频繁写styles.xxx这样的代码，但是roadhog是支持css-modules的，那么如果我在.roadhogrc中配置这个插件是不是就冗余了？或者说roadhog本身的css-modules就支持这个特性？

**Comment by sorrycc** [comment]
不习惯写 `styles.`，在 .roadhogrc 把这个插件配上就好了。

**Comment by ouzhou** [comment]
![image](https://user-images.githubusercontent.com/7693866/29058026-c3482858-7c40-11e7-8aec-dac99acd6a22.png)
测试可用，已解决。。。

**Comment by ouzhou** [comment]
补充一点，在和roadhog一起使用的时候有可能会有hash不同的情况，这个时候可以配置react-css-modules里面的一个context的参数，原因是这里的context没有继承到roadhog内部的context，可以通过手动更改。
ps 幸好这里是js文件不是json文件，不然还不好写context绝对路径，babel7才有可能支持.babelrc.js

**Comment by qizhancheng** [comment]
怎么继承到roadhog内部的context？
