### ISSUE TITLE
subscriptions 的使用问题

### ISSUE THREAD

**Issue by pigongting** [dvajs/dva#1118]
subscriptions 数据源可以是当前的时间、服务器的 websocket 连接、keyboard 输入、geolocation 变化、history 路由变化等等。

例子中是 history 路由变化，其他的方式有没有可能提供一些例子？

**Comment by laketea** [comment]
redux-saga 的eventChannel 支持接收外部事件
官网有个websocket的例子： https://redux-saga.js.org/docs/advanced/Channels.html
