### ISSUE TITLE
关于dva组件状态的问题

### ISSUE THREAD

**Issue by yrcy0418** [dvajs/dva#112]
在使用dva过程中，如果在一个列表页面点击添加按钮，弹出一个modal窗口，窗口是否显示保存在model的state中，如果在model里的控件例如 ant.design的穿梭框（Transfer）需要靠model里state的值改变选中结果，这样每次选中改变后就会调用 reducers ，这样整个modal窗口就会重新弹出。 如何解决呢

**Comment by codering** [comment]
应该是使用方式不对，贴下代码

**Comment by sorrycc** [comment]
全部数据走 model，不要走 component 的 state 。混用会出现一些奇怪的问题，除非你很明白整套机制。

**Comment by yrcy0418** [comment]
@sorrycc 数据走的就是model，我把代码贴上来

弹出的modal 组件
`import React, { PropTypes } from 'react';
import { Form, Input, Modal, InputNumber, Select, Transfer } from 'antd';
import { connect } from 'dva';
const FormItem = Form.Item;
const Option = Select.Option;

const formItemLayout = {
  labelCol: {
    span: 6
  },
  wrapperCol: {
    span: 14
  }
};

const formItemLayout2 = {
  labelCol: {
    span: 8
  },
  wrapperCol: {
    span: 12
  }
};



var SetSpotsModal = ({cardtype, dispatch, form, type, item = {}, onOk, onCancel}) => {

  const { getFieldProps, validateFields, getFieldsValue } = form;

  const modalOpts = {
    title: cardtype.title,
    visible : cardtype.spotsVisible,
    maskClosable: false,
    onOk: handleOk,
    onCancel,
  };

  let allSpots=[];
  if(cardtype.allSpots!=null&&cardtype.allSpots.length>0){
      for(var i=0;i<cardtype.allSpots.length;i++){
      allSpots.push(<Option key={cardtype.allSpots[i].id}>{cardtype.allSpots[i].name}</Option>);
      }
  }



  function handleOk() {
    form.validateFields((errors) => {
      if (errors) {
        return;
      }
      const data = { ...form.getFieldsValue(), cardTypeId: item.cardTypeId };
      onOk(data);
    });
  }

  function handleChange(targetKeys, direction, moveKeys) {
      dispatch({
        type: 'card/type/tranfser/success',
        payload: {
          targetKeys: targetKeys,
        },
      });
  }

  return (
    <Modal {...modalOpts}>
      <Form horizontal>
        <FormItem
          label="卡类型："
          {...formItemLayout}
          hasFeedback
        >
        {cardtype.cardTypeName}
        </FormItem>
        <FormItem
          label="景区："
          {...formItemLayout}
          hasFeedback
        >
        <Select showSearch
          placeholder="请选择景区" multiple
          {...getFieldProps('scenicIds',{rules: [{ required: true, type: 'array',message: '请选择景区'}],initialValue: item['scenicIds']==null?[]:item['scenicIds']})}
        >
        {allSpots}
        </Select>
        </FormItem>
        <Transfer
           dataSource={cardtype.mockData}
           targetKeys={cardtype.targetKeys}
           onChange={handleChange}
           render={item => item.title}
        />

      </Form>
    </Modal>
  );
}

function mapStateToProps(state) {
  return { cardtype: state.cardtype };
}

SetSpotsModal = Form.create()(SetSpotsModal);

export default connect(mapStateToProps)(SetSpotsModal);
`

model
`import { call, put } from 'dva/effects';
import { hashHistory } from 'dva/router';
import { query, create, del, info, edit,getScenicspots,spotsinfo,setCardTtypeSpots} from '../services/cardtype';
import { message } from 'antd';

export default {

  namespace: 'cardtype',
  state: {
    list: [],
    tableLoading: false,
    currentItem: {},
    modalType: 'create',
    total: null,
    title: '新增卡分类',
    modalVisible : false,
    spotsVisible:false,
    currentSize: 10,
    current: 1,
    allSpots:[],
    cardTypeName:'',
    targetKeys: [],
    mockData:[],
  },

  subscriptions: [
    function(dispatch) {
      hashHistory.listen(location => {
        if (location.pathname === '/card/type') {
          dispatch.dispatch({
            type: 'card/type/tranfser',
          });
          dispatch.dispatch({
            type: 'card/type/query',
            payload: {'name':''},
          });
          dispatch.dispatch({
            type: 'card/type/allSpots',
            payload: {'name':''},
          });
        }
      });
    },
  ],

  effects: {
    *['card/type/tranfser']({}) {
      const targetKeys = [];
      const mockData = [];
      for (let i = 0; i < 20; i++) {
        const data = {
          key: i,
          title: `内容${i + 1}`,
          description: `内容${i + 1}的描述`,
          chosen: Math.random() * 2 > 1,
        };
        if (data.chosen) {
          targetKeys.push(data.key);
        }
        mockData.push(data);
      }
      yield put({
        type: 'card/type/tranfser/success',
        payload: {
          targetKeys: targetKeys,
          mockData: mockData,
        },
      });
    },
    // 卡分类查询
    *['card/type/query']({ payload }) {
      yield put({ type: 'card/type/showLoading' });
      const result = yield call(query, payload);
      if (result.body && result.body.success) {
        yield put({
          type: 'card/type/query/success',
          payload: {
            list: result.body.page.list,
            total: result.body.page.total,
            currentSize: result.body.page.pageSize,
            current: result.body.page.pageNum,
          },
        });
      }
    },

    // 增加卡分类
    *['card/type/create']({ payload }) {
        yield put({ type: 'card/type/hideModal' });
        yield put({ type: 'card/type/showLoading' });
        const result = yield call(create, payload);
        if (result.body && result.body.success) {
          message.success("添加卡分类成功");
          const result = yield call(query, {name:''});
          if (result && result.body.success) {
            yield put({
              type: 'card/type/query/success',
              payload: {
                list: result.body.page.list,
                total: result.body.page.total,
                currentSize: result.body.page.pageSize,
                current: result.body.page.pageNum,
              },
            });
          }
        }else if (result.body && !result.body.success) {
          message.success(result.body.errorMsg);
        }
        yield put({ type: 'card/type/hideLoading' });
    },

    // 删除用户
    *['card/type/del']({ payload }) {
      yield put({ type: 'card/type/showLoading' });
      const result = yield call(del, payload);
      if (result.body && result.body.success) {
        message.success("删除卡分类成功");
        const result = yield call(query, {name:''});
        if (result.body && result.body.success) {
          yield put({
            type: 'card/type/query/success',
            payload: {
              list: result.body.page.list,
              total: result.body.page.total,
              currentSize: result.body.page.pageSize,
              current: result.body.page.pageNum,
            },
          });
        }
      }
      yield put({ type: 'card/type/hideLoading' });
    },

    // 获取卡分类信息
    *['card/type/info']({ payload }) {
      const result = yield call(info, payload.id);
      if (result.body && result.body.success) {
        yield put({
          type: 'card/type/showModal',
          payload: {
            currentItem: result.body.data,
            modalType: 'edit',
          },
        });
      }
    },
    //获取所有景区
  *['card/type/allSpots']() {
      const result = yield call(getScenicspots);
      if (result.body && result.body.success) {
        yield put({
          type: 'card/type/allSpots/success',
          payload: {
            allSpots:result.body.data,
          },
        });
      }
  },
    //卡设置景区
    *['card/type/spotsinfo']({ payload }) {
      const result = yield call(spotsinfo, payload.id);
      if (result.body && result.body.success) {
        yield put({
          type: 'card/type/showSpotsModal',
          payload: {
            currentItem: result.body.data,
            title:'关联景区',
            cardTypeName:payload.name,
          },
        });
      }
    },
      // 更新卡分类信息
        *['card/type/setSpots']({ payload }) {
          const result = yield call(setCardTtypeSpots, payload);
          if (result.body && result.body.success) {
            yield put({ type: 'card/type/hideSpotsModal' });
            yield put({ type: 'card/type/showLoading' });
            message.success("设置景区成功");
            const result = yield call(query, {name:''});
            if (result.body && result.body.success) {
              yield put({ type: 'card/type/hideLoading' });
              yield put({
                type: 'card/type/query/success',
                payload: {
                  list: result.body.page.list,
                  total: result.body.page.total,
                  currentSize: result.body.page.pageSize,
                  current: result.body.page.pageNum,
                },
              });
            }
          }else if(result.body && !result.body.success) {
            message.success(result.body.errorMsg);
          }

        },

    // 更新卡分类信息
    *['card/type/edit']({ payload }) {
      yield put({ type: 'card/type/hideModal' });
      yield put({ type: 'card/type/showLoading' });
      const result = yield call(edit, payload);
      if (result.body && result.body.success) {
        message.success("编辑卡分类成功");
        const result = yield call(query, {name:''});
        if (result.body && result.body.success) {
          yield put({
            type: 'card/type/query/success',
            payload: {
              list: result.body.page.list,
              total: result.body.page.total,
              currentSize: result.body.page.pageSize,
              current: result.body.page.pageNum,
            },
          });
        }
      }else if(result.body && !result.body.success) {
        message.success(result.body.errorMsg);
      }
      yield put({ type: 'card/type/hideLoading' });
    },
  },

  reducers: {
    ['card/type/tranfser/success'](state, action) {
      return { ...state, ...action.payload};
    },
    ['card/type/showLoading'](state, action) {
      return { ...state, tableLoading: true };
    },
    ['card/type/hideLoading'](state, action) {
      return { ...state, tableLoading: false };
    },
    ['card/type/query/success'](state, action) {
      return { ...state, ...action.payload, tableLoading: false};
    },
    ['card/type/showModal'](state, action) {
      return { ...state, ...action.payload, modalVisible: true};
    },
    ['card/type/hideModal'](state, action) {
      return { ...state, modalVisible: false};
    },
    ['card/type/showSpotsModal'](state, action) {
      return { ...state, ...action.payload, spotsVisible: true};
    },
    ['card/type/hideSpotsModal'](state, action) {
      return { ...state, spotsVisible: false};
    },
    ['card/type/allSpots/success'](state, action) {
      return { ...state, ...action.payload};
    },
  },

}
`

**Comment by yrcy0418** [comment]
@sorrycc 问题我找到了

按你的方法  

`// 解决 Form.create initialValue 的问题
  // 每次创建一个全新的组件, 而不做diff
  // 如果你使用了redux, 请移步 http://react-component.github.io/form/examples/redux.html
  const UserModalGen = () =>
    <UserModal {...userModalProps} />;`

每次创建全新的modal组件如果更新model数据组件就会重新绘制，就会造成modal重新弹出

还成手动控制就行了

**Comment by wonyun** [comment]
借此问题提出一下组件的疑问，user-dashboard demo中的User.jsx中有这样一段：
```javascript
// 解决 Form.create initialValue 的问题
  // 每次创建一个全新的组件, 而不做diff
  // 如果你使用了redux, 请移步 http://react-component.github.io/form/examples/redux.html
  const UserModalGen = () =>
    <UserModal {...userModalProps} />;

  return (
    <MainLayout location={location}>
      <div className={styles.normal}>
        <UserSearch {...userSearchProps} />
        <UserList {...userListProps} />
        <UserModalGen />
      </div>
    </MainLayout>
  );
```

为什么User.jsx中引入的三个子组件里面只有UserModal组件需要重新包装一下，而UserSearch却没有，看注释说每次会生成一个全新的组件，为啥会这样，求大神指导一下，非常感谢

**Comment by nikogu** [comment]
@wonyun 

```
// 解决 Form.create initialValue 的问题
// 每次创建一个全新的组件, 而不做diff
// 如果你使用了redux, 请移步 http://react-component.github.io/form/examples/redux.html
```

antd2.0.0已经没有此问题
