### ISSUE TITLE
关于reducer的格式

### ISSUE THREAD

**Issue by ssshooter** [dvajs/dva#1121]
教程里reducer的格式是
`(state, action) => newState`
但是为什么实际上是
```javascript
add(state, { payload: todo }) {
  return state.concat(todo);
},
```
而不是
```javascript
add(state, { type: add, payload: todo }) {
  return state.concat(todo);
},
```
action 不是必须带有 type 属性吗?

**Comment by sorrycc** [comment]
这是 ES6 的语法，详见：https://github.com/dvajs/dva-knowledgemap#析构赋值

**Comment by ssshooter** [comment]
所以是dispatch发起action，然后action在reducers里面找同名reducer函数运行吗？

**Comment by xufei** [comment]
是的。在这里，`{ type: add, payload: todo }` 这段东西的含义并不是用来约束数据格式，而是代表只从里面取对应的值。在 reducer 执行之前，type 实际上已经被用来查找它了，在执行的时候并不需要，所以就不用取，也就不用写出来了。
