### ISSUE TITLE
打开新页面用什么方式比较好？

### ISSUE THREAD

**Issue by SuperNaturalGit** [dvajs/dva#1122]
项目中需要点击触发effects然后打开一个新页面。
react-router-redux好像没法打开新页面。
Link标签也不行，因为是在事件中判断触发的。
是不是只能用window.open方法？这样的话，url需要拼上一堆参数，有点丑。
求问有没有好的方式可以实现这个功能。

**Comment by HengCC** [comment]
用 routerRedux
```
import { routerRedux } from 'dva/router';
....

dispatch(routerRedux.push(.....))

或者 

yield put(routerRedux.push(.....))
```

**Comment by HengCC** [comment]
新页面似乎只能用window.open. 不过有个折中的方案. 

在open之前把参数通过post提交到服务器上去. 服务器在内存中临时保存请求参数. 然后返回一个ID给客户端.  客户端打开这个页面的时候直接带这个ID作为参数就行了

**Comment by sorrycc** [comment]
没啥其他办法。
