### ISSUE TITLE
第一次加载慢，优化问题。

### ISSUE THREAD

**Issue by yueleiMaster** [dvajs/dva#1128]
请问大神们，现在写的项目内容不多，但是第一次加载非常慢，应该从哪些方面去优化，非常感谢！

**Comment by sorrycc** [comment]
本地开发服务器启动慢？还是访问页面慢？

**Comment by yueleiMaster** [comment]
项目部署后，第一次加载很慢。

**Comment by sorrycc** [comment]
下载消耗的时间？还是 JS 运行消耗的？

**Comment by yueleiMaster** [comment]
index.js  耗时11.87s

**Comment by yueleiMaster** [comment]
大小1.7M

**Comment by sorrycc** [comment]
1.7M 是有点大了，分析下为啥这么大吧。

**Comment by xufei** [comment]
看一下是不是所有功能都需要在一开始就加载，可以把有些东西放在后面懒加载，比如，有些界面一开始不使用，就随着路由，用 require.ensure 处理一下，点到这个界面的时候才加载执行。

**Comment by yueleiMaster** [comment]
我没有处理页面加载问题，可能是都在一开始加载，require.ensure有文档吗？我看一看。

**Comment by yueleiMaster** [comment]
一般index多大才算正常？

**Comment by xufei** [comment]
看看这个 https://github.com/dvajs/dva-example-user-dashboard/blob/master/src/router.js#L17

在 getComponent 里面这段，构建会自动把里面的东西分离出去打包，用到才自动加载进来。

看你首页用到多少东西，一般来说，最多几百k吧，太大了就慢了

**Comment by yueleiMaster** [comment]
好的，谢谢！

**Comment by yueleiMaster** [comment]
按照文档使用getCompoent按需加载组件跟model了，但是还是没变化，依旧第一次加载十几秒，很难受
![qq 20170817173250](https://user-images.githubusercontent.com/25242674/29406268-1ee3cbf2-8373-11e7-9e88-509af47d36f3.png)

**Comment by yueleiMaster** [comment]
可能是我路由写得有问题 getCompoent里require()进来得组件报错，必须在上面先import组件 在给cb才能正常，我觉得不对劲

**Comment by yueleiMaster** [comment]
require()引入会报错
![image](https://user-images.githubusercontent.com/25242674/29407881-992428e4-8378-11e7-87c3-726b05fabc67.png)
![image](https://user-images.githubusercontent.com/25242674/29407906-ae8f6608-8378-11e7-8ca8-b0ca6feb6cd0.png)

**Comment by sorrycc** [comment]
不用保密的话把源码发出来，我帮你分析下。

**Comment by yueleiMaster** [comment]
好的 非常感谢  通过什么发给你？

**Comment by yueleiMaster** [comment]
我感觉跟我得webpack有关系，因为使用node.js代理到dva的原因，我开发服务一直出问题，导致现在浏览器热刷新也不能用，所以我觉得问题出在require.ensure()函数上

**Comment by sorrycc** [comment]
邮箱 sorrycc@gmail.com，或者传到 github 上。

**Comment by yueleiMaster** [comment]
额 ，被退回来了，邮箱

**Comment by sorrycc** [comment]
试试 yunqian@alibaba-inc.com

**Comment by yueleiMaster** [comment]
发过去了  非常感谢！！

**Comment by sorrycc** [comment]
- require.ensure 就是这么用的，没看出有啥问题
- 要把所有路由都通过这种方式处理
- g2, china-division 这类库，还可以再延迟渲染

**Comment by yueleiMaster** [comment]
![image](https://user-images.githubusercontent.com/25242674/29442905-0be6954a-8407-11e7-88b4-992957811211.png)
我在require上随便调下require就又可以了，要不然一直不出来页面，报这个错
![image](https://user-images.githubusercontent.com/25242674/29442917-29e37496-8407-11e7-849f-aef9661e0922.png)

**Comment by yueleiMaster** [comment]
是不是 build完后生成chunk文件夹就算成功了？

**Comment by yueleiMaster** [comment]
require.ensure跟roadhogrc服务有关系吗？

**Comment by steem** [comment]
可以参考我修改后的版本，https://github.com/steem/qwp-antd
参照这种方法，模块单独在不同的chunk里，动态加载，route数组分散到了不同模块目录下，如图
![route](https://user-images.githubusercontent.com/121950/29520197-cc7eaa6a-86b2-11e7-9ac6-cabc1c8222c5.png)

**Comment by ZGahou** [comment]
dva2.x版本的写法有吗
