### ISSUE TITLE
跨域访问，使用了proxy浏览器还是报No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by HeSwift** [dvajs/dva#1129]
如题，.roadhogrc文件配置了proxy浏览器还是报No 'Access-Control-Allow-Origin' header is present on the requested resource。Origin 'http://127.0.0.1:8000' is therefore not allowed access。错误。
.roadhogrc proxy配置。
  "proxy": {
    "/tracker/api": {
      "target": "http://tracker.xxx.com/",
      "changeOrigin": true,
      "secure": false,
      "pathRewrite": { "^/tracker/api" : "/tracker/api" },
      "logLevel": "debug",
      "headers":{
        "host":"http://tracker.xxx.com/"
      }
    }
  },

**Comment by sorrycc** [comment]
给 https://github.com/webpack/webpack-dev-server 提 issue 问吧，我也不熟 proxy 的配置。

**Comment by HeSwift** [comment]
好的

**Comment by levinzero** [comment]
@HeSwift 请问下你的service.js中传入request方法的URL格式是怎样的，我也遇到过，最初传的是/api/yuanxiao/prizesrecord 这样的格式，说是跨域，后来传了/api/yuanxiao/prizesrecord/ （即最后多了条斜杠）就能正常请求了。。具体原理不清楚，寻求文档无果
