### ISSUE TITLE
dva的model方法是否还可以增加数组形式的参数

### ISSUE THREAD

**Issue by wonyun** [dvajs/dva#113]
如题：

model方法除了模型object参数外，是否可以增加模型对象数组形式的参数呢，方便一次注册多个模型对象，避免多次调用model方式来实现，这样是否更方便呢？

**Comment by sorrycc** [comment]
数组形式的暂时不会提供。如果你用 webpack，批量 require 可以试试 [require.context](http://webpack.github.io/docs/context.html#require-context) 。
