### ISSUE TITLE
升级到 "roadhog": "^1.1.1"样式显示不出来

### ISSUE THREAD

**Issue by ouzhou** [dvajs/dva#1130]
原因是用了babel-plugin-react-css-modules， 他自带的hash:` '[local]___[hash:base64:5]'`和roadhog的hash值不同。但是在版本`"roadhog": "^0.5.2"`是相同的。
[相关issue](https://github.com/dvajs/dva/issues/1116)

-----补充
看了一下css-modules的原理，如果是类名相同，hash值肯定也应该是相同的。

**Comment by ouzhou** [comment]
https://stackoverflow.com/questions/36678077/blob-based-link-stylesheet-vs-standard-style-tag
不知道为什么样式显示不出来了，这个和blob有关系吗

**Comment by sorrycc** [comment]
那是 babel-plugin-react-css-modules 的问题？hash 计算方式不同吧。

**Comment by ouzhou** [comment]
但是在版本"roadhog": "^0.5.2"是可以使用的，计算方式应该是相同的

**Comment by sorrycc** [comment]
0.5.2 是 webpack1，1.x 是 webpack3，所以是 babel-plugin-react-css-modules 不兼容 webpack3 ？

**Comment by ouzhou** [comment]
没有不兼容，因为能有hash值算出来，只不过页面上引用的hash值和最后生成的css文件中的hash值不等，导致样式加载不出来。

**Comment by ouzhou** [comment]
样式有一部分以js异步加载的方式加载了，导致先出现dom元素，再加载样式的情况闪烁。请问这样的情况怎么处理？
![image](https://user-images.githubusercontent.com/7693866/29299711-4488a034-81a3-11e7-9bda-bd6cc1d79430.png)
![image](https://user-images.githubusercontent.com/7693866/29299739-954fea04-81a3-11e7-9fac-be9c1d2337bb.png)

**Comment by ouzhou** [comment]
结论是不使用babel-plugin-react-css-modules。。。
