### ISSUE TITLE
样式首次加载页面会闪烁

### ISSUE THREAD

**Issue by ouzhou** [dvajs/dva#1131]
![image](https://user-images.githubusercontent.com/7693866/29303424-583de852-81bf-11e7-9e45-80998fdb8e27.png)
![image](https://user-images.githubusercontent.com/7693866/29303447-8d6f9d90-81bf-11e7-82fd-aab239bb8d9b.png)

刷新可以看到先显示文字 在加载样式。。
如何配置让样式先加载？

**Comment by sorrycc** [comment]
本地开发时是内联样式，是会闪烁的，发布到线上就不会了。

**Comment by ouzhou** [comment]
@sorrycc 查明原因是因为在react-router里用的是按需加载的方式，导致了样式是在js中异步加载到页面上了，请问在这样的方式下能否解决闪烁的情况。

**Comment by sorrycc** [comment]
试试 build 后的效果，css 不通过 js 载入就不会闪。

**Comment by u3u** [comment]
https://github.com/sorrycc/roadhog/issues/385#issuecomment-346234845
