### ISSUE TITLE
subscriptions和effects的函数中怎么访问当前model的state数据？

### ISSUE THREAD

**Issue by freeant** [dvajs/dva#1135]
subscriptions和effects的函数中怎么访问当前model的state数据？

**Comment by freeant** [comment]
哦，找到方法了。
const role = yield select(state => state.app.user.role);
但是不得不说的是，这些文档里都没有啊

**Comment by no13bus** [comment]
@freeant 这个在那个30分钟学会curd里面有这段类似的代码，当然这个是redux-saga的东西
