### ISSUE TITLE
model层是一种什么概念

### ISSUE THREAD

**Issue by dib-nhnl** [dvajs/dva#1136]
model层给ui容器传递了props，我一开始以为model层的js文件其实也是一种组件，但是里面只有抽离出来的逻辑层和数据，所以model层到底算什么？
在react的学习中，容器被分成容器组件、展示组件，那么model层相对于他们，又算是什么样的东西呢？
难道就是mapDispatchToProps？
还请解惑。

**Comment by sorrycc** [comment]
- model 是数据层，不是组件
- react 只处理视图层的，不包含数据层，所以才需要一些配套的数据流方案，比如 redux、dva 等
