### ISSUE TITLE
remote-redux-devtools 调试

### ISSUE THREAD

**Issue by guai-ak** [dvajs/dva#1137]
请问dva如何使用remote-redux-devtools 进行debug

**Comment by sorrycc** [comment]
为什么用 remote-redux-devtools ？redux-devtools-extension 不能满足需求？

**Comment by guai-ak** [comment]
react-native 也可以吗

**Comment by sorrycc** [comment]
可以配 [extraEnhancers](https://github.com/dvajs/dva/blob/master/docs/API.md#extraenhancers)。
