### ISSUE TITLE
dora升级到roadhog后，刷新页面，history.listen函数就不会执行

### ISSUE THREAD

**Issue by nianhua110** [dvajs/dva#1139]
```
setup({ dispatch, history }) { 
      return history.listen(({ pathname, query }) => {
        if (pathname === '/e') {
          console.log('eeeeeeeeeeee');
          dispatch({ type: 'fetch', payload: query });
        }
      });

```
调试发现可以执行到history.listen这一行，
“if(pathname == '..”这一行就执行不了.

**Comment by sorrycc** [comment]
工具和代码应该无关吧。history v3 和 v4 默认是不会执行初始化的 history.listen 的，你是否有自行依赖了 history 的这两个版本？

**Comment by nianhua110** [comment]
这个怎么初始化呢？ 另外我把history改成browserhistory，那么fetch的发送的api请求，前面会跟上当前页面的路由。比如locahost:8000/api/users 变成了 localhost:8000/users/api/users.

**Comment by sorrycc** [comment]
整理个可重现的 demo 上来看下?

**Comment by nianhua110** [comment]
好的

**Comment by nianhua110** [comment]
应该是配置的问题，我把package.json文件换成你们列子里的，就可以了。
