### ISSUE TITLE
router中使用getComponent问题

### ISSUE THREAD

**Issue by yueleiMaster** [dvajs/dva#1140]
请问下，我在router中使用getComponent(),cb中require()无法使用，会报错，但是先import组件进来后在放cd中可以正常使用。
![image](https://user-images.githubusercontent.com/25242674/29441256-95a546ce-83fc-11e7-9386-a8304ca3443c.png)

**Comment by yueleiMaster** [comment]
![image](https://user-images.githubusercontent.com/25242674/29441333-2a6b9042-83fd-11e7-9e47-edcdc074c05e.png)

**Comment by yueleiMaster** [comment]
![image](https://user-images.githubusercontent.com/25242674/29441344-3bc22522-83fd-11e7-9c27-df3d04f2eb49.png)

**Comment by sorrycc** [comment]
npm run build 看看，有没有生成 chunk 文件。

**Comment by yueleiMaster** [comment]
![image](https://user-images.githubusercontent.com/25242674/29445080-1eb5bfba-8417-11e7-88a2-253a8f16de9a.png)
build完后这样对吗？

**Comment by sorrycc** [comment]
对。

**Comment by yueleiMaster** [comment]
![image](https://user-images.githubusercontent.com/25242674/29446549-5070d280-841f-11e7-8f59-a04124d0344d.png)
但是现在build出来可以，直接启动不行，页面出不来

**Comment by sorrycc** [comment]
不是有出错信息？index.js 访问不到吧。

**Comment by yueleiMaster** [comment]
这是直接启动的
![image](https://user-images.githubusercontent.com/25242674/29446611-beae3a8a-841f-11e7-9e57-ecde3e3ed869.png)

**Comment by yueleiMaster** [comment]
可以了  谢谢！
