### ISSUE TITLE
有publicPath时，subscriptions的pathname匹配

### ISSUE THREAD

**Issue by wuzhuzhu** [dvajs/dva#1141]
``` javascript
setup({ dispatch, history }) {
      return history.listen(({ pathname, query }) => {
           if (pathname === '/path') {
                 ...
            }
     }
}
```
当publicPath存在的时候，匹配会失败，这个可以理解..
可是pathname会从 '/path' 变成 'path' ， 而不是加上了publicPath...
这就很尴尬了...

**Comment by sorrycc** [comment]
publicPath 和这个 path 应该没有任何关系才对吧。publicPath 是加载资源文件的根路径，history 的 path 是当前 url 的 path 。

**Comment by wuzhuzhu** [comment]
可一加上puclic pah log出来就是不一样…
