### ISSUE TITLE
希望可以更新一下dva用的saga版本/I hope you can update the saga version of DVA 

### ISSUE THREAD

**Issue by hanzhangyu** [dvajs/dva#1142]
希望可以更新一下dva用的saga版本
I hope you can update the saga version of DVA https://github.com/dvajs/dva/blob/master/package.json#L65,

因为`0.14.0`是不支持`all`的。
Because the version `0.14.0` does not support to function `all`.

如果我手动安装`redux-saga`的时候，并引入我自己装的`saga`,
If I manually install the `redux-saga` module, and import my `saga`,
```js
import {all, call} from 'redux-saga/effects';
*query({payload}, {call}){
      const ddd = yield all([
        call(queryDicCode),
      ]);
      console.log(ddd)
}
```
在这种情况下all出的结果是：
In this case, the result of using `all` is:
![image](https://user-images.githubusercontent.com/19344269/29456699-8b3fcac2-8449-11e7-9111-278a015a24cd.png)
当我覆盖`dva/node_modules`下的`saga`时才会输出正常：
The output is normal when I override `dva/node_modules` under `saga`:
![image](https://user-images.githubusercontent.com/19344269/29456737-c11c0336-8449-11e7-9c7f-c36ce7af14ae.png)

> 我的猜测是dva可能对saga做了改动，虽然粗略的一看只是简单的传递export
My guess is that DVA may have made some changes to saga, although it look like is simply passing export

```js
*query({payload}, {call}){
      const ddd = yield a[
        call(queryDicCode),
      ];
      console.log(ddd)
}
```
当然这种写法是没问题。但是不用官方的API我浑身难受
Of course, it works by using this way , But without the official API, I feel sick

>当然哪位大佬教在下一波不使用`lock`和`shrinkwrap`的情况下，如何指定子模块版本号，在下也是感激不尽
Finally I'm so greatful for the your help.

**Comment by sorrycc** [comment]
Try dva@1.3.0-beta.4.

**Comment by hanzhangyu** [comment]
thanks
