### ISSUE TITLE
CSS modules引入全局动画库的问题

### ISSUE THREAD

**Issue by 521zzp** [dvajs/dva#1144]
请教前辈，在dva里面用那个CSS modules，我想引入一个全局的动画库animate.css，把它内部代码全放在:global{ }里面，他的类名和动画名都被局部化了（加上后缀）。然后把文件类型改成animate.less，把全部代码放到:global{ }里面，结果类名没有被局部化，@keyframes声明的动画名被局部化了，但是类名里面用到的动画名也没有局部化（加后缀），然后动画名不匹配就直接失效了。这种情况下如何引入全局的动画库呢？

**Comment by sorrycc** [comment]
这是正常的，仔细看下 css-modules 的文档吧。https://github.com/css-modules/css-modules
