### ISSUE TITLE
有没有接合next.js的例子，我想用ant+next.js 做SSR,但不知道怎么接合dva使用？

### ISSUE THREAD

**Issue by witwave** [dvajs/dva#1147]
有没有接合next.js的例子，我想用ant+next.js 做SSR,但不知道怎么接合dva使用？

**Comment by sorrycc** [comment]
next.js 有自己的路由处理，所以你可以引用 `dva/mobile` 无路由版。剩下的参考 https://github.com/zeit/next.js/tree/master/examples/with-apollo-and-redux 这个例子。

**Comment by witwave** [comment]
@sorrycc  谢谢， 这个例子我看过了，如果用原生的redux,是没问题，我是想用dva

**Comment by zzh3319** [comment]
有没有接合next.js的例子

**Comment by sumlight** [comment]
现在也想问这个问题, 因为首页加载太慢了

**Comment by sorrycc** [comment]
next.js 在 page 里只要返回一个 React Component 即可，可参考这个例子，https://github.com/dvajs/dva/tree/master/packages/dva-example-nextjs

**Comment by forever4313** [comment]
原先的model在next.js里怎么用.抱歉，新手，劳烦给指导下

**Comment by zjxpcyc** [comment]
@forever4313 你可以这样理解，next.js 里面，每个 page 都是一个 dva app 。

**Comment by forever4313** [comment]
@zjxpcyc 在next里怎么使用代码跳转页面 & 以前在dva中写代码的时候Page可以拿到history 和routes 等属性，在next里怎么获取（没用过next，请指导 下）

**Comment by zjxpcyc** [comment]
你的每个 page 是一个 app, 那么这个 page 相关的，你就可以直接用原来的方法。

但是 page 之间或者 跨 page 之间的路由跳转，这个我不清楚，我用的是 window.location 跳的，你可以研究下，然后分享下

**Comment by gongfuxiaocai** [comment]
> next.js 在 page 里只要返回一个 React Component 即可，可参考这个例子，https://github.com/dvajs/dva/tree/master/packages/dva-example-nextjs

打不开了哦，还有其他的demo嘛@sorrycc

**Comment by miss61008596** [comment]
> > next.js 在 page 里只要返回一个 React Component 即可，可参考这个例子，https://github.com/dvajs/dva/tree/master/packages/dva-example-nextjs
> 
> 打不开了哦，还有其他的demo嘛@sorrycc
maybe you need this one：
https://github.com/dvajs/dva/tree/master/examples/with-nextjs
