### ISSUE TITLE
求解决按需加载写法导致css闪烁的问题

### ISSUE THREAD

**Issue by ouzhou** [dvajs/dva#1148]
复现链接：https://github.com/ouzhou/dva-demo
原因在readme里

**Comment by codering** [comment]
@sorrycc 我也想请假下，异步加载的模块充斥大量css文件内容，该怎么处理呢？

**Comment by sorrycc** [comment]
感谢反馈，已重现，我找时间解决下。

**Comment by steem** [comment]
这个是否可以在dva提供路由变化开始和结束的通知就可以解决

**Comment by yangbin1994** [comment]
same issue+1

**Comment by sorrycc** [comment]
Try roadhog@1.2.1
