### ISSUE TITLE
全局state变换如何监听？

### ISSUE THREAD

**Issue by Otobelikethee** [dvajs/dva#1149]
我有个全局state，里头管理着子页面请求时需要携带的参数x。UI交互时触发全局state变化, 如何优雅地将这个变化通知到当前展示的页面子组件呢？这样它可以发出新的请求并完成本身UI渲染更新.看到redux有这个功能[subscribe](http://redux.js.org/docs/api/Store.html#subscribe)。

**Comment by Otobelikethee** [comment]
#895

**Comment by sorrycc** [comment]
> UI交互时触发全局state变化, 如何优雅地将这个变化通知到当前展示的页面子组件呢？

子组件绑定 state 数据，state 变化时自然会触发 rerender 。

**Comment by Otobelikethee** [comment]
@sorrycc 你指的是通过mapStateToProps这个函数去获取全局state是吗？

**Comment by sorrycc** [comment]
对。

**Comment by Otobelikethee** [comment]
@sorrycc 我是想要拿到更新后的全局state里头某个属性值，子页面会将它作为请求参数去重新获取新数据，再渲染UI的，因为我的所有的子页面，都跟全局state有关，所以有点头疼。。

**Comment by zhiyuanL** [comment]
> @sorrycc 我是想要拿到更新后的全局state里头某个属性值，子页面会将它作为请求参数去重新获取新数据，再渲染UI的，因为我的所有的子页面，都跟全局state有关，所以有点头疼。。

后来想到处理办法了么？

**Comment by HSQCoollaughing** [comment]
> > UI交互时触发全局state变化, 如何优雅地将这个变化通知到当前展示的页面子组件呢？
> 
> 子组件绑定 state 数据，state 变化时自然会触发 rerender 。

是不是所有依赖state的组件都会重新渲染
