### ISSUE TITLE
dva的onStateChange(fn)怎么用？

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#115]
我用了dva-loading插件，我希望当global.loading改变为true的时候，我想打开Toast.loading()，为false的时候，Toast.hide()，能通过onStateChange来实现么？

另外，如果我不用Toast，希望用ActivityIndicator ，又怎么做？我知道每个界面都放入ActivityIndicator 组件，能实现，就是繁琐。

看了dva-loading的代码，愣是没有看懂，有没有简单一点的文档可以参考的？

**Comment by sorrycc** [comment]
漏看这个 issue 了。。全局放一个 `ActivityIndicator` ? 要用 `Toast.loading()` 之类的调用式方法，最好也是封装成一个 React Component，监听 props 变动。

**Comment by bjwulin** [comment]
谢谢，明白了。@sorrycc，能不能写一篇详细的文档，介绍dva plugin的开发？

**Comment by hanagm** [comment]
同问，有没有比较详细的文档，
