### ISSUE TITLE
dvajs 微信互助群

### ISSUE THREAD

**Issue by no13bus** [dvajs/dva#1150]
> 注：已超过 100 人了，请加 no13bus 微信让拉入群吧。加人信息备注下"dva"

大家好，我是个后端工程师，因为业务需要最近开始写管理后台的页面，经由前端工程师介绍，接触了dva这个易于上手的框架，根据项目提供的知识地图拓展了es6, react, redux等知识点。现在已经写了一些管理后台页面了，觉得这框架对于我们这种小白后端来说真是不错。

另外，这几天我从头开始浏览已经关闭的issue，发现了好些人其实提的一些问题有关于dva的，也有关于其他方面的，有些人对react的整体全家桶也不是很熟悉，或者是es6不是很熟悉，我就创建了一个微信群，想着对dva感兴趣的同学可以进来一起讨论下，要是有能力和时间的话，还可以帮忙解决下issue，对自我的成长也是很有帮助的。

跟 @sorrycc 邮件沟通了下，得到其允许，加我的微信: no13bus 我拉你入群.

> 2017.11.25更新: 新增telegram入群链接  `https://t.me/joinchat/F9T5tkttuzZ6v9cmLj6Idg`

**Comment by no13bus** [comment]
备注下 
二维码如果后期失效后，可以加我的微信: no13bus 我拉你入群

**Comment by no13bus** [comment]
更新一次二维码
![](http://cdn.no13bus.com/17-8-29/4280518.jpg)

**Comment by nalantianyi** [comment]
不应该用钉钉吗🤣

**Comment by akliyiping** [comment]
@no13bus 链接失效了

**Comment by aihua** [comment]
@no13bus @sorrycc 微信群是否可以在开放下，更新下链接？

**Comment by aihua** [comment]
@no13bus @sorrycc 微信群是否可以再开放下，更新下链接？

**Comment by sorrycc** [comment]
已超过 100 人了，加 no13bus 微信拉入群吧。

**Comment by no13bus** [comment]
加我入群的时候，麻烦备注下"dva"

**Comment by liuboBobo** [comment]
能否再更新下二维码吗？

**Comment by loki315zx** [comment]
还有入群的联系方式嘛?

**Comment by no13bus** [comment]
@loki315zx 最顶上写了如何进群的方式

**Comment by loki315zx** [comment]
大神 已经申请好友了!
方便后面的朋友  再重复遍入群需加dalao的wxid:
no13bus

**Comment by zhenxianluo** [comment]
大家好,我实在是试了非常多遍了,roadhog2中.webpackrc文件可以配置sass,但是找了好久没有看到一个示例,node-sass的不是很明白,如果有知道怎么配的麻烦发个地址我看看,谢谢!

**Comment by Z-wave** [comment]
@zhenxianluo 请问你配置好sass了吗？

**Comment by athrunsun** [comment]
@no13bus 我申请加了你微信好友，头像跟我github的头像一样，可否通过一下？谢谢

**Comment by martinwithyou** [comment]
我加你了@no13bus.    拉我进dva交流群吧。谢谢
