### ISSUE TITLE
如何在Effect执行完毕后在ui执行一个提示（或者一个动作）

### ISSUE THREAD

**Issue by lihaichen** [dvajs/dva#1151]
场景：
新增一个user，点击增加按键dispath一个事件执行Effect（提交数据），effect执行完毕后，如何在ui上提示新增完成或者失败。
如果在model设置一个标志，如果这个标志ok就提示信息，如果这个ui刷新了，会一直提示添加完成的字样。

**Comment by lihaichen** [comment]
render() {
    if (this.props.user.get('requestStatus') === requestStatus.LOAD_LOADING) {
      this.context.router.push('/container/user');
      // window.location.href = '/container/user';
    }
    return (
      <div className={`${prefixCls}`}>
      </div>
    );
  }
}
这样跳转也是有问题的，this.context.router.push这个函数调用了setState

**Comment by steem** [comment]
参考[这个](https://github.com/steem/qwp-antd/blob/master/src/models/user.js)：

*create ({ payload }, { call, put }) {
      const data = yield call(userService.create, payload)
      let state = {
        lastCreateUserData: data.success ? 0 : payload.f,
      }
      if (data.success) {
        state._t = (new Date()).getTime()
      }
      yield put({
        type: 'updateState',
        payload: state,
      })
      showOpsNotification(data, l('Create user'), l('New user has been created successfully'))
    },
