### ISSUE TITLE
如何在页面渲染前执行操作？

### ISSUE THREAD

**Issue by xypisces** [dvajs/dva#1152]
例如：当我进入到某个页面要让其重定向别的页面，但是测试发现会渲染页面后再跳转。如何解决？
我使用的是onEnter，componentWillMount都不可以，都是会看到渲染。求大神解决。

**Comment by sorrycc** [comment]
加个 loading 效果。

**Comment by zjxpcyc** [comment]
印象里面  onEnter 不是有个 callback 参数吗， 执行 callback 组件才会开始渲染。
