### ISSUE TITLE
reducers的刷新问题

### ISSUE THREAD

**Issue by tears743** [dvajs/dva#1154]
在某个model 文件中写了一个如下reducer，
updateState(state,{payload}){
         return {
             ...state,     
             ...payload
      }
    }
但是每次更新时，页面全部状态都刷新了一遍，payload中我只传了state中的某一个状态也是全局刷新，请问能否局部刷新

**Comment by jdwdw** [comment]
@tears743  会全局刷新，因为你的state是新state会调用绑定了modal 的component的 render方法，如果你真的很想去局部刷新一个组件，你可以考虑把这个主件单独去绑定一 modal去，这个modal就这去监听当前组件自己的状态改变
