### ISSUE TITLE
使用dva-cli构建的新项目出现Unknown plugin "dva-hmr" 

### ISSUE THREAD

**Issue by kelekexiao123** [dvajs/dva#1155]
./src/index.js
Module build failed: ReferenceError: Unknown plugin "dva-hmr" specified in "base" at 3, attempted to resolve relative to "E:\\github\\WorkSpace\\chat-react-express\\client\\src"
    at Array.map (native)
编译失败卡在这里了，没弄明白哪里出错了，dva-hmr我也重新install过了。
求大神提点一下

**Comment by sorrycc** [comment]
依赖没安装好，dva-hmr 实际上是 babel-plugin-dva-hmr 。
