### ISSUE TITLE
急！关于这套dva如何使用css打印样式，因为在原生试验都没有问题，在dva里面就用不了

### ISSUE THREAD

**Issue by zikeng** [dvajs/dva#1156]
page-break-before: always; 这个样式在dva里面好像是无效，不知道是否与其他样式冲突

**Comment by sorrycc** [comment]
具体怎么写的？工具是用 roadhog?

**Comment by zikeng** [comment]
其实就是调用window.print(),然后用css把要打印的部分显示出来，用普通原生写法是没有问题的，但在react是不行的，后来网上找了资料改一下可以了，但是如果批量打印又不分页，试了好多办法了，解决不了，真的非常急呢

![2017-08-28 5 32 58](https://user-images.githubusercontent.com/18687474/29767960-fb466cc0-8c16-11e7-814f-521cd8b9f738.png)

**Comment by hanzhangyu** [comment]
你使用原生的肯定是沒錯，关键是要看一下react的寫法
![image](https://user-images.githubusercontent.com/19344269/29768549-3e5bb2ca-8c19-11e7-9d2d-01a1f5561cc2.png)
至少在我这里是没问题的，页面的确插入了分页符，我的基本配置和dva的新手大礼包是一样的。

**Comment by sorrycc** [comment]
是 css-modules 影响到了，用 `:global(.role) {}`

**Comment by zikeng** [comment]
我觉得也是css-module影响到了，但就是不知道怎么改，求大神帮忙指导一下，研究了好几天了，是这样写吗？我这边没有效果，在线等
![2017-08-28 6 01 15](https://user-images.githubusercontent.com/18687474/29768999-f263586c-8c1a-11e7-8a04-c4cc9dcf028f.png)
