### ISSUE TITLE
Error in ./src/index.js Module build failed: Error: Plugin 5 specified in "base" provided an invalid property of "libraryName"     at Array.map (native)  @ multi index

### ISSUE THREAD

**Issue by zteBill** [dvajs/dva#1159]
Failed to compile.

Error in ./src/index.js
Module build failed: Error: Plugin 5 specified in "base" provided an invalid property of "libraryName"
    at Array.map (native)
 @ multi index

**Comment by zteBill** [comment]
不知道这个是什么原因导致的？请教一下，谢谢~~

**Comment by sorrycc** [comment]
配置贴出来看下。

**Comment by zteBill** [comment]
package.json

{
  "private": true,
  "scripts": {
    "start": "roadhog server",
    "build": "roadhog build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "engines": {
    "install-node": "6.9.2"
  },
  "dependencies": {
    "antd": "^2.12.8",
    "babel-runtime": "^6.9.2",
    "dva": "^1.2.1",
    "react": "^15.4.0",
    "react-dom": "^15.4.0"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "babel-plugin-dva-hmr": "^0.3.2",
    "babel-plugin-import": "^1.4.0",
    "babel-plugin-transform-runtime": "^6.9.0",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "expect": "^1.20.2",
    "husky": "^0.12.0",
    "redbox-react": "^1.3.2",
    "roadhog": "^0.5.2"
  }
}


.roadhogrc

{
  "entry": "src/index.js",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        "import", { "libraryName": "antd", "style": "css" }
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime"
      ]
    }
  },
  "proxy": {
      "/api": {
        "target": "http://jsonplaceholder.typicode.com/",
        "changeOrigin": true,
        "pathRewrite": { "^/api" : "" }
      }
   }
}

**Comment by zteBill** [comment]
配置是这样的，帮忙看看吧，谢谢~~  @sorrycc

**Comment by sorrycc** [comment]
```diff
- "import", { "libraryName": "antd", "style": "css" }
+ ["import", { "libraryName": "antd", "style": "css" }]
```
