### ISSUE TITLE
dva的fetch在rn报错，找不到self变量

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#116]
我看dva封装fetch，代码：
`self.fetch.bind(self);`
应该是这儿在rn里面有问题。

**Comment by sorrycc** [comment]
fetch 是可选的，rn 不要用这个。

**Comment by bjwulin** [comment]
@sorrycc ，用什么？我现在替换为fetch-everywhere了，但是还是fetch。建议用什么？

**Comment by sorrycc** [comment]
https://facebook.github.io/react-native/docs/network.html
看了下 RN 的文档，直接用 fetch 就好了，别引 dva/fetch。

**Comment by sppsun** [comment]
由于dva依赖于isomorphic-fetch@2.2.1，一种比较麻烦的方法是修改之。做法为新建文件node_modules\isomorphic-fetch\fetch-npm-react-native.js，内容为var globalObject = typeof self === "undefined" ? global : self; module.exports = globalObject.fetch.bind(globalObject);
package中添加"react-native": "fetch-npm-react-native.js"，执行npm install，应该就可以了。另外，注意antd-pro中封装的request方法也要改下，我的改成了：
export default function request(url, option) {
  const options = {
    ...option,
  };
  /**
   * Produce fingerprints based on url and parameters
   * Maybe url has the same parameters
   */
  const defaultOptions = {
    credentials: 'include',
  };
  const newOptions = { ...defaultOptions, ...options };
  if (
    newOptions.method === 'POST' ||
    newOptions.method === 'PUT' ||
    newOptions.method === 'DELETE'
  ) {
    if (!(newOptions.body instanceof FormData)) {
      newOptions.headers = {
        Accept: 'application/json',
        'Content-Type': 'application/json; charset=utf-8',
        ...newOptions.headers,
      };
      newOptions.body = JSON.stringify(newOptions.body);
    } else {
      // newOptions.body is FormData
      newOptions.headers = {
        Accept: 'application/json',
        ...newOptions.headers,
      };
    }
  }
  return fetch(BASE_API_URL + url, newOptions)
    .then(checkStatus)
    .then(response => {
      // DELETE and 204 do not return data by default
      // using .json will report an error.
      if (newOptions.method === 'DELETE' || response.status === 204) {
        return response.text();
      }
      return response.json();
    })
    .catch();
}
