### ISSUE TITLE
新版的（roadhog）如何配babelrc

### ISSUE THREAD

**Issue by 951565664** [dvajs/dva#1160]
新版的（roadhog）如何配babelrc

**Comment by sorrycc** [comment]
不能直接配，不过可以在 .roadhogrc 里配 extraBabelPlugins 和 extraBabelPresets。

**Comment by 951565664** [comment]
@sorrycc 额，其实我是想在咱dva里用jest的，研究一下午，没跑起来。。。

**Comment by 951565664** [comment]
@sorrycc 咱dva有考虑加自动化测试方案吗？
