### ISSUE TITLE
node8 import antd报错

### ISSUE THREAD

**Issue by jianrongjia** [dvajs/dva#1164]
Failed to compile.

Error in ./~/_rc-trigger@1.11.3@rc-trigger/lib/Popup.js
Module not found: 'rc-align' in D:\js-react\base-service\dva-quickstart\node_modules\_rc-trigger@1.11.3@rc-trigger\lib

 @ ./~/_rc-trigger@1.11.3@rc-trigger/lib/Popup.js 39:15-34

----
试了多次，引入任意一个antd组件都报上面的错

**Comment by sorrycc** [comment]
antd 的问题应该在 antd issue 里提。
