### ISSUE TITLE
dva里怎么使用action creator较好

### ISSUE THREAD

**Issue by old-wang** [dvajs/dva#1165]
在dva中使用action creator，怎么设计比较好

**Comment by sorrycc** [comment]
dva 里不推荐用 action creator 。

**Comment by iShawnWang** [comment]
emmmmm, 请问下为什么不推荐... ?
`https://github.com/redux-utilities/redux-actions` 这个用起来还蛮舒服的... 

---

那么大家都是怎么组织 action 的呢 ? 

`dispatch({type: 'todo/create', payload: {text: content}})`

这样 magic 字符串 很丑陋... 

dva 的 model 层要不要也简单的封装一下 action
然后页面中 : 

```
import TodoModel from '../models/todo'

TodoModel.actions.create(dispatch, {text: '嘿嘿'})
```

我的大概思路是这样...

**Comment by lirenhao** [comment]
> dva 里不推荐用 action creator 。

为什么不推荐action creator？

**Comment by JoshYuJump** [comment]
We can get a cleaner component with `action creator`, why not recommend it?
