### ISSUE TITLE
Pie组件中Cell组件的fill不起作用，导致饼图使用了一个默认颜色fill="#808080"，请教一下大牛，这是什么原因呢？谢谢！

### ISSUE THREAD

**Issue by zteBill** [dvajs/dva#1166]
`<Pie data={this.state.termData} dataKey="value" cx={200} cy={200} startAngle={180} endAngle={-180} outerRadius={80} label={renderLabelContent}>
            {
               this.state.termData.map((entry, index) => {
                console.log(colors[index % 10]);
                  <Cell key={`slice-${index}`} name={entry.name} value={entry.value} fill={colors[index % 10]}/>
                }
                )
            }  `

**Comment by paranoidjk** [comment]
这跟 dva 有什么关系？

**Comment by zteBill** [comment]
和dva没有关系，只是想请教一下大牛们，我也在rechat提问了一下，希望知道的大牛给个指导，谢谢！

**Comment by zteBill** [comment]
@paranoidjk
