### ISSUE TITLE
使用ie打开，报错‘对象不支持“assign”属性或方法‘

### ISSUE THREAD

**Issue by old-wang** [dvajs/dva#1167]
使用ie打开，报错‘对象不支持“assign”属性或方法‘，使用dva-cli的，是roadhog配置问题吗

**Comment by xufei** [comment]
ie 里面没有 Object.assign，如果非要在 ie 下用，引个 polyfill 好了。

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by old-wang** [comment]
使用了babel-polyfill，然后报了另一个错误
Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `StatelessComponent`.
在其他浏览器上都是正常显示，就是IE出了这个问题

**Comment by sorrycc** [comment]
IE 几？

**Comment by blanky01** [comment]
我也遇到了和@old-wang同样的情况同样的情况，请问这个问题解决了吗？ @sorrycc

**Comment by spiroo** [comment]
index.js中加入polyfill可以解决
```
import babel-polyfill';
```
