### ISSUE TITLE
redux 不执行操作时，loading 为 undefined

### ISSUE THREAD

**Issue by lilonghe** [dvajs/dva#1168]
默认不执行任何动作
获得的 loading 为 undefined

**Comment by xufei** [comment]
这个没什么问题啊，你绑定 loading 展示的时候，undefined 跟 false 含义相同。

**Comment by lilonghe** [comment]
@xufei  好吧，antd 的某个加载组件不识别 undefined 
其次，undefined 和 false 差别还是挺大的
