### ISSUE TITLE
Ant Design官方明确指明dva也支持ssr服务端渲染，想问下有实例没？

### ISSUE THREAD

**Issue by longzb** [dvajs/dva#117]
有例子自然更好，对dva里的内部本来就不熟，自己弄根本无法下手。

**Comment by airt** [comment]
See <https://github.com/dvajs/dva#appstartselector>
> `app.start(selector?)`
> Start the application. `selector` is optional. If no `selector` arguments, it will return a function that return JSX elements.

```
import ReactDOMServer from 'react-dom/server'

// ...

const getReactElement = app.start()

const html = ReactDOMServer.renderToString(getReactElement())

// ...
```

**Comment by sorrycc** [comment]
只公用 View 的现在就可以用，用 `dva()` 会返回 JSXElement；公用 view + router 的方案还需要花时间研究下。

和 https://github.com/dvajs/dva/issues/85#issuecomment-249152559 重复，先 Close 了。
