### ISSUE TITLE
dva 可以配置 redux-devtools 么？

### ISSUE THREAD

**Issue by VanquisherMe** [dvajs/dva#1172]
\<DevTools/\>‘’不清楚放在哪

**Comment by sorrycc** [comment]
开发模式下默认就有加的。

**Comment by VanquisherMe** [comment]
@sorrycc  默认就有？您的意思是 通过 dva-cil，npm start 就有了？ 还是dva/DevTools 需要引入？还是要通过什么开启？

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/blob/eb6d9fd/src/createDva.js#L214-L216

**Comment by VanquisherMe** [comment]
明白了 您指的是 
![image](https://user-images.githubusercontent.com/4927398/29993284-73466b5e-8fe5-11e7-85c3-f53ca4a7fc69.png)
哈哈 可能问差了 我还停留在
![image](https://user-images.githubusercontent.com/4927398/29993290-b02ba9ee-8fe5-11e7-9a42-2ed84685be82.png)
