### ISSUE TITLE
关于 Model交互 和effects 的一些疑问

### ISSUE THREAD

**Issue by VanquisherMe** [dvajs/dva#1173]
已经阅读过：#895 ， https://github.com/sorrycc/github-stars 【简称：github-stars】，redux-saga

1.#895中所所描述的两种思路
① 在 mapStateToProps 获取当前 model 需要的 app model 数据
② app model 获取数据后，put 数据到其他需要的 model【应该就是github-stars 中的用法 put 同名数据的reducers 】
-------------疑惑-----------
【1】mapStateToProps 的传递应该只局限于 当前 model 下的子组件，可以夸模块传递？
可以将状态传递给 children？
【2】拥有 redux-saga 的 dva 是否 kake  takeEvery takeLatest 才是比较 优雅处理 异步关系的方式，#895 提及的② 方式可以舍弃了，还是有什么取舍？
【3】https://github.com/dvajs/dva/blob/master/docs/API_zh-CN.md 中说明
格式为 *(action, effects) => void 或 [*(action, effects) => void, { type }]。
type 类型有：
- takeEvery
- takeLatest
- throttle
- watcher
[*(action, effects) => void, { type }] 这个的用法是？

```
effects:{
[* query ({
      payload,
    }, { call, put }){
....
},{"takeEvery"}]
}
```

尝试了这样但是好像不对

**Comment by sorrycc** [comment]
> mapStateToProps 的传递应该只局限于 当前 model 下的子组件，可以夸模块传递？

model 和 component 是分离的，不存在对应关系，component 里需要啥数据在 connect 的时候传啥就好了。

> 可以将状态传递给 children？

可以通过 props 往下传给  children，也可以在子组件里 connect 所需的数据。

> 拥有 redux-saga 的 dva 是否 kake takeEvery takeLatest 才是比较 优雅处理 异步关系的方式，#895 提及的② 方式可以舍弃了，还是有什么取舍？

没理解。dva 默认是 takeEvery。

> 问题 3

参考用例 https://github.com/dvajs/dva/blob/d49e356/packages/dva-core/test/effects-test.js ，无效应该是用法不对。

**Comment by VanquisherMe** [comment]
> 拥有 redux-saga 的 dva 是否 kake takeEvery takeLatest 才是比较 优雅处理 异步关系的方式，#895 提及的② 方式可以舍弃了，还是有什么取舍？

个人理解：在model 中使用 kake 获取全局异步关系后的请求，component 中通过mapStateToProps 获取全局数据，当然model 也可以通过 在component 中dispatch 获得到 mapStateToProps而来的数据

> 可以将状态传递给 children？

场景：
https://github.com/zuiidea/antd-admin/blob/master/src/routes/app.js#L98
https://github.com/zuiidea/antd-admin/blob/master/src/router.js#L16
这个情况好像只能 使用 connect 传递数据

**Comment by sorrycc** [comment]
```js
yield put({
  type: 'stars/sync',
});
```

put 是 diapatch 一个 action，take 是件ring一个 action 。这两者没啥关联吧。类似问题可以加微信群交流吧， #1150  。

**Comment by VanquisherMe** [comment]
T_T 可能没有表述清楚，
例子中 用put 同步了 state 全局的数据，这样不会出现 model 在需要一个 全局数据的时候，却还是初始数据
【场景也就是 app.model 请求用户数据，a..model init请求需要  app.model updateState后的数据，应为都是异步。所以...】
const action = yield take('*');
const newState = yield select();
做了同样的事情
所以就问问 是不是 之前 put 同步的方式可以被 替代了 T_T ===》微信群交流已加

**Comment by weishijun14** [comment]
```take takeEvery takeLatest``` 是监听作用的。监听用户触发所产生的action。
```put call``` 是写在监听中的回调。 是当监听到某一action后，该执行任务的方式。
是2种完全不同的概念。
