### ISSUE TITLE
dva onerror 不能捕捉到异常

### ISSUE THREAD

**Issue by daxiong-liang** [dvajs/dva#1174]
在做测试时候，在做异步请求处理时候，发觉部分异常抛出，onerror方法没法接收并进行处理
有500的异常同404的异常。
出现404 异常出现情况如下：
1、将一个delete请求的url人为修改成错误的url，执行该行为的操作会在f12的控制台出现异常，但是onerror没有显示
request.js:50 DELETE http://localhost:8000/services/userRoles/system/A20/account/admin1234567/rosssle/248 404 (Not Found)
request.js:102 ex--- Error: (404)HTTP 404 Not Found
    at _callee$ (http://localhost:8000/index.js:118469:19)
    at tryCatch (http://localhost:8000/index.js:36218:41)
    at Generator.invoke [as _invoke] (http://localhost:8000/index.js:36456:23)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8000/index.js:36270:22)
    at step (http://localhost:8000/index.js:36916:31)
    at http://localhost:8000/index.js:36927:14
    at <anonymous>
2、出现500异常出现情况如下：
1、程序正常运行后，将本机网络转为不能连接数据库等的网络，类似外网切换内网后，执行delete的操作，同样会在f12的控制台出现异常，但是onerror没有显示
request.js:50 DELETE http://localhost:8000/services/users/account/liangxj 500 (Internal Server Error)
request.js:45 parse responseText error Error occured while trying to proxy to: localhost:8000/services/users/account/liangxj
request.js:102 ex--- Error: Internal Server Error
    at _callee$ (http://localhost:8000/index.js:118469:19)
    at tryCatch (http://localhost:8000/index.js:36218:41)
    at Generator.invoke [as _invoke] (http://localhost:8000/index.js:36456:23)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8000/index.js:36270:22)
    at step (http://localhost:8000/index.js:36916:31)
    at http://localhost:8000/index.js:36927:14
    at <anonymous>

request.js:99 Uncaught (in promise) Error: Internal Server Error
    at _callee$ (http://localhost:8000/index.js:118469:19)
    at tryCatch (http://localhost:8000/index.js:36218:41)
    at Generator.invoke [as _invoke] (http://localhost:8000/index.js:36456:23)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8000/index.js:36270:22)
    at step (http://localhost:8000/index.js:36916:31)
    at http://localhost:8000/index.js:36927:14
    at <anonymous>

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
步骤看上方

#### Expected behavior: (预期的正常效果)
所有throw处理的异常应该能够捕捉到

#### Actual behavior: (实际效果)
部分异常没法捕捉

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva：1.2.1

**Comment by sorrycc** [comment]
effect 里调用异步请求异常？需要把异步请求封装成 Promise，然后用 Promise 的 reject 返回错误。然后 `onError` 才能捕获到。

**Comment by daxiong-liang** [comment]
确实在effect那边调用了异步，但是因为后台不需要返回任何数据，所以异步发送过去之后就执行了成功的操作，然后异步出错，在request.js里面本来是捕捉到，但是throws出去之后，onerror没有捕获。是否在request.js里面，直接封装成promise返回错误

**Comment by daxiong-liang** [comment]
贴出代码：
model/user.js
	delete: reducers.deleteEffect(null, ({ user }) => {
      userService.deleteUser(user.account);
    }),
	
reducers.js
	export function deleteEffect(defaultAction, actionToExecute) {
	  function *effect(action, param) {
		let mergedAction = action;
		if (defaultAction) {
		  mergedAction = { ...defaultAction, ...action };
		}
		const { call, put } = param;
		const { resolve, reject } = mergedAction;
		try {
		  const result = yield call(actionToExecute, mergedAction, param);
		  yield put({ ...mergedAction, type: 'deleteS', ...result });
		  if (resolve) {
			resolve();
		  }
		} catch (e) {
		  if (reject) {
			reject();
		  }
		  throw e;
		}
	  }
	  return effect;
	}

	
service/userService.js
	export function deleteUser(userAccount, options) {
	  return request(`/users/account/${userAccount}`, {
		method: 'DELETE',
		...options,
	  });
	}
	
request.js
	export default async function request(url, options) {
	  const addr = url.startsWith('http') ? url : `${SERVICE_ROOT}${url}`;
	  const defOptions = defaultOptions();
	  const headers = { ...defOptions.headers, ...(options ? options.headers : {}) };
	  const ops = { ...defOptions, ...options };
	  ops.headers = headers;

	  let response;
	  let responseText;
	  try {
		response = await fetch(addr, ops);
		responseText = await response.text();
		if (response.status >= 200 && response.status < 300) {
		  const data = (responseText === undefined || responseText === '') ? {} : JSON.parse(responseText);
		  return { data };
		} else {
		  const errors = ops.errors;
		  if (errors) {
			const error = {
			  status: response.status,
			  respDesc: response.statusText,
			  ...parseErrorResp(responseText),
			};
			if (errors.indexOf(error.respCode) >= 0 || errors.indexOf(response.status) >= 0) {
			  return { error };
			}
		  }
		  throw new Error(`unhandled error ${response.status}`);
		}
	  } catch (e) {
		let error = { respDesc: e.message };
		let errorMsg;
		if (response) {
		  let respDesc = response.statusText;
		  if (response.status === 401) respDesc = '操作需要登录才能访问';
		  else if (response.status === 403) respDesc = '操作未授权';
		  error = {
			status: response.status,
			respDesc,
			...parseErrorResp(responseText),
		  };
		  if (error.respCode && error.respCode.endsWith(ERROR_VALIDATION)) {
			errorMsg = '请求参数校验异常';
		  }
		}
		if (ops.errors && ops.errors.indexOf('all') >= 0) {
		  return { error };
		}
		try {
		  const ex = new Error(errorMsg || error.respDesc);
		  ex.response = response;
		  ex.error = error;
		  console.log('ex---', ex);
		  throw ex;
		} catch (exi) {
		  console.log('exi---', exi);
		  throw exi;
		}
	  }
	}

**Comment by daxiong-liang** [comment]
model/user.js
	delete: reducers.deleteEffect(null, ({ user }) => {
      userService.deleteUser(user.account);
    }),
	
reducers.js
	export function deleteEffect(defaultAction, actionToExecute) {
	  function *effect(action, param) {
		let mergedAction = action;
		if (defaultAction) {
		  mergedAction = { ...defaultAction, ...action };
		}
		const { call, put } = param;
		const { resolve, reject } = mergedAction;
		try {
		  const result = yield call(actionToExecute, mergedAction, param);
		  yield put({ ...mergedAction, type: 'deleteS', ...result });
		  if (resolve) {
			resolve();
		  }
		} catch (e) {
		  if (reject) {
			reject();
		  }
		  throw e;
		}
	  }
	  return effect;
	}

	
service/userService.js
	export function deleteUser(userAccount, options) {
	  return request(`/users/account/${userAccount}`, {
		method: 'DELETE',
		...options,
	  });
	}
	
request.js
	export default async function request(url, options) {
	  const addr = url.startsWith('http') ? url : `${SERVICE_ROOT}${url}`;
	  const defOptions = defaultOptions();
	  const headers = { ...defOptions.headers, ...(options ? options.headers : {}) };
	  const ops = { ...defOptions, ...options };
	  ops.headers = headers;

	  let response;
	  let responseText;
	  try {
		response = await fetch(addr, ops);
		responseText = await response.text();
		if (response.status >= 200 && response.status < 300) {
		  const data = (responseText === undefined || responseText === '') ? {} : 
                  JSON.parse(responseText);
		  return { data };
		} else {
		  const errors = ops.errors;
		  if (errors) {
			const error = {
			  status: response.status,
			  respDesc: response.statusText,
			  ...parseErrorResp(responseText),
			};
			if (errors.indexOf(error.respCode) >= 0 || errors.indexOf(response.status) >= 0) {
			  return { error };
			}
		  }
		  throw new Error(`unhandled error ${response.status}`);
		}
	  } catch (e) {
		let error = { respDesc: e.message };
		let errorMsg;
		if (response) {
		  let respDesc = response.statusText;
		  if (response.status === 401) respDesc = '操作需要登录才能访问';
		  else if (response.status === 403) respDesc = '操作未授权';
		  error = {
			status: response.status,
			respDesc,
			...parseErrorResp(responseText),
		  };
		  if (error.respCode && error.respCode.endsWith(ERROR_VALIDATION)) {
			errorMsg = '请求参数校验异常';
		  }
		}
		if (ops.errors && ops.errors.indexOf('all') >= 0) {
		  return { error };
		}
		try {
		  const ex = new Error(errorMsg || error.respDesc);
		  ex.response = response;
		  ex.error = error;
		  console.log('ex---', ex);
		  throw ex;
		} catch (exi) {
		  console.log('exi---', exi);
		  throw exi;
		}
	  }
	}

**Comment by sorrycc** [comment]
request.js 里的出错需要用 reject 返回。

**Comment by daxiong-liang** [comment]
好的，我尝试一下

**Comment by daxiong-liang** [comment]
但是reducer里面已经执行到deleteS方法，就是在抛出这个异常的时候，已经执行成功方法，在request.js里面还能用reject么

**Comment by daxiong-liang** [comment]
其实这边是走到request.js方法里面，我看代码已经catch了异常，快走到const ex = new Error(errorMsg || error.respDesc);这个位置的时候，在方法名头就报错。。所以最后一直都抛不出异常，所以这里是不知道怎样解决

**Comment by daxiong-liang** [comment]
try {
      const ex = new Error(errorMsg || error.respDesc);
      console.log(errorMsg, error.respDesc)
      ex.response = response;
      ex.error = error;
      throw ex;
    } catch (exi) {
      throw exi;
    }
即使这样也捕捉不到异常

**Comment by sorrycc** [comment]
https://stackblitz.com/edit/dva-example-onerror
试着理解下这个例子。
