### ISSUE TITLE
img添加src会报错

### ISSUE THREAD

**Issue by ladybug2fire** [dvajs/dva#1179]
#### Actual behavior: (实际效果)

Uncaught TypeError: Cannot read property '__reactInternalInstance$m390w2805c' of null

#### Versions of packages used: (哪个库的哪个版本出现的问题)

dva 2.0, react 15.4

**Comment by sorrycc** [comment]
没理解问题。

**Comment by tanrenjie** [comment]
应该是语法错误吧。

**Comment by ladybug2fire** [comment]
@sorrycc 就是我通过dva-cli ，dva new project创建一个新项目，然后在indexpage.js 里面添加一个图片，控制台就会报如上错误，但是页面显示是正常的

**Comment by sorrycc** [comment]
怎么重现？

**Comment by ladybug2fire** [comment]
@sorrycc dva new project创建一个新项目，然后在indexpage.js 里面添加一个图片，控制台就会报如上错误

**Comment by sorrycc** [comment]
怎么添图片？

**Comment by sorrycc** [comment]
https://www.google.com/search?newwindow=1&q=__reactInternalInstance%24m%27+of+null&oq=__reactInternalInstance%24m%27+of+null&gs_l=psy-ab.3...25687.25687.0.26284.1.1.0.0.0.0.309.309.3-1.1.0....0...1..64.psy-ab..0.0.0.wMxMKQ9lXAY
这是  react 的问题。
