### ISSUE TITLE
把histroy属性设置成browserHistory无效

### ISSUE THREAD

**Issue by undefinedor** [dvajs/dva#118]
```
import {browserHistory } from 'dva/router';

const app = dva({
  history:browserHistory
});
```
这样不对吗？

一直不生效。

**Comment by sorrycc** [comment]
这个配置对的。

**Comment by WhatAKitty** [comment]
@undefinedor 如果不是依赖外部容器，调试的话，则需要设置启动脚本：`"start": "dora --plugins \"browser-history,proxy,webpack,webpack-hmr\"",`

**Comment by herrdu** [comment]
import createBrowserHistory from 'history/createBrowserHistory'
import './index.css';
  
// 1. Initialize
const app = dva({
  history: createBrowserHistory(),
  initialState: {
    products: [ 
      { name: 'dva', id: 1 },
      { name: 'antd', id: 2 },
    ]
  }
});
