### ISSUE TITLE
action被saga取消了

### ISSUE THREAD

**Issue by kakazuo** [dvajs/dva#1181]
场景是打开一个对话框，输入form之后点击ok，下面是代码
```
    *annvInitAndShowModal({ payload }, { call, put }) {
      const memdays = yield call(queryMemdays, payload)
      if (memdays.status === 0 ) {
        yield put({
          type: 'annvShowModal',
          payload: {
            annvList: memdays.value, 
            ...payload
          },
        })
      } else {
        throw '获取数据失败'
      }
    },
    *createAnnvScoreRule ({ payload }, { call, put }) {
       const data = yield call(createAnnvScoreRules, payload)
      if (data.status === 0) {
        yield put({ type: 'annvHideModal' })
        yield put({ type: 'queryAnnvScoreRule', payload})
      } else {
        throw data.msg
      }
    },
```
初始化对话框的时候调用annvInitAndShowModal，这里没有问题，点对话框中ok的时候调用createAnnvScoreRule，就不能创建了，chrome后台会显示 
`_callee has been cancelled `
然后再次调用annvInitAndShowModal 和 createAnnvScoreRule没有任何反应
我们是一开始用这一套框架，所以踩了很多坑，希望哪位大神帮忙看一下这个问题，万分感激！

**Comment by sorrycc** [comment]
应该是 `createAnnvScoreRule` 里执行出错了。

**Comment by kakazuo** [comment]
恩，应该是那里问题，但是与annvInitAndShowModal也有关系，我如果打开对话框的时候不执行初始化的工作（即直接调用action： annvShowModal），createAnnvScoreRule执行就没有问题，所以我这边就搞不清楚问题在哪里了，下面是call方法调用的service代码

```
export async function queryMemdays (params) {
  return request({
    url: memdays,
    method: 'get',
    data: params,
  })
}

export async function createAnnvScoreRules (params) {
  let url = `${corps}/${corpId}/memdayrules`;
  if(params.defaultStartTime){
    url = `${url}?defaultStartTime=true`;
  }else{
    url = `${url}?defaultStartTime=false`;
  }

  if(params.defaultEndTime){
    url = `${url}&defaultEndTime=true`;
  }else{
    url = `${url}&defaultEndTime=false`;
  }
  return request({
    url: url,
    method: 'post',
    data: params,
  })
}
```

还请大神仔细帮我看下，谢谢啊！！！！这个问题拦我好几天了

**Comment by sorrycc** [comment]
整理一个可重现的最小 demo 传到 github 上？

**Comment by szwork2013** [comment]
@kakazuo  在models文件里是最容易踩坑的，建议你 跟踪一下 
      const data = yield call(createAnnvScoreRules, payload) 
        yield put({ type: 'annvHideModal' })
        yield put({ type: 'queryAnnvScoreRule', payload})
这几个执行情况，简单点console相关信息出来，最好把这里的每一行都跟踪一下。如果某一句执行有问题她会停止，所以很多人不知是哪里出问题.

**Comment by kakazuo** [comment]
@sorrycc 
这里是我的代码，还麻烦你帮忙看下，重新步骤：
1. 打开连接http://localhost:8000/scorerule
2. 点击tab纪念日积分倍率
3. 点击创建按钮（可能要等下弹出对话框）
4. 按要求输入，点击确定
5. 看一下chrome的开发工具会打印出
```
takeEvery(scorerule/queryAnnvScoreRule, _callee) has been cancelled 
 _callee6 has been cancelled 
 _callee has been cancelled 
takeEvery(scorerule/annvInitAndShowModal, _callee) has been cancelled 
 _callee6 has been cancelled 
_callee has been cancelled 
The development server has disconnected.
Refresh the page if necessary.
```
6. 关闭这个对话框，在点击创建按钮，对话框无法打开（annvInitAndShowModal 这个action似乎就没法调用了）

[vipmgmt-front-dev-copy.zip](https://github.com/dvajs/dva/files/1276712/vipmgmt-front-dev-copy.zip)

@szwork2013 谢谢先，我跟踪了，但是这个saga可跟踪的太少了，莫名情况下任务就不执行了

**Comment by szwork2013** [comment]
我看看先。

**Comment by kakazuo** [comment]
@szwork2013 发现问题在哪了嘛

**Comment by kakazuo** [comment]
@sorrycc @szwork2013 我似乎找到问题，我再调用service的时候没有try，catch. 比如我把createAnnvScoreRule修改为
```
    *createAnnvScoreRule ({ payload }, { call, put }) {
      try{
       const data = yield call(createAnnvScoreRules, payload)
        yield put({ type: 'annvHideModal' })
        yield put({ type: 'queryAnnvScoreRule', payload})
      }catch(e){
        
      }
      //  const data = yield call(createAnnvScoreRules, payload)
      // if (data.status === 0) {
      //   yield put({ type: 'annvHideModal' })
      //   yield put({ type: 'queryAnnvScoreRule', payload})
      // } else {
      //   throw data.msg
      // }
    },
```
就没有上面的问题了，但是为什么一定要try，catch，我service层的调用并没有报错啊？？

**Comment by sorrycc** [comment]
`throw data.msg` 删了就不会提示 cancel 了。

**Comment by sorrycc** [comment]
src/index.js 的 onError() 函数里：

```diff
- conosle.log('error : ' + error)
+ console.log('error : ' + error)
```

建议加个 lint 校验吧，这种初级问题就不会出现了。。

**Comment by szwork2013** [comment]
@kakazuo vipmgmt-front-dev-copy.zip你这个压缩文件下载太慢，下里三次都失败了，根据我的经验，这个架构models是最容易抓狂的，我一般是用最笨的方法：确保你的服务器api返回你要的正确格式的数据，然后在关键的地方一行一行跟踪获得的值，最多的情况是一般数组，对象的操作可能出空值或格式出问题。

**Comment by szwork2013** [comment]
@sorrycc 您能回复一下我的问题吗？谢谢了！https://github.com/sorrycc/roadhog/issues/417

**Comment by kakazuo** [comment]
@sorrycc 好的

**Comment by yearnZero** [comment]
@kakazuo 你好，我也有一个跟你一样的bug,请问你最后怎么解决的啊
