### ISSUE TITLE
首页的动态路由链接404

### ISSUE THREAD

**Issue by akliyiping** [dvajs/dva#1184]
Support load model and routes dynamically: Improve performance (Example)

(Example)链接404

**Comment by akliyiping** [comment]
@sorrycc ？

**Comment by sorrycc** [comment]
点错，我修复下链接。

**Comment by akliyiping** [comment]
嗯，3q

**Comment by aihua** [comment]
The link for redux-saga is changed.

**Comment by aihua** [comment]
@sorrycc The link for [redux-saga](https://github.com/redux-saga/redux-saga) is changed.

**Comment by sorrycc** [comment]
@aihua Fixed.
