### ISSUE TITLE
import没有自动添加

### ISSUE THREAD

**Issue by leftluoyi** [dvajs/dva#1185]
IntelliJ Idea and Node.js 6.11.2.

完全按照的[https://github.com/dvajs/dva/blob/master/docs/GettingStarted.md](https://github.com/dvajs/dva/blob/master/docs/GettingStarted.md)的步骤进行coding。最后npm start的时候是发现keymaster这个包并没有自动加入到库中。

**Comment by sorrycc** [comment]
抱歉，工具层有变动，不会自动添加依赖了。需要手动。
