### ISSUE TITLE
dva2.0.1 history 怎么引入？

### ISSUE THREAD

**Issue by zjxpcyc** [dvajs/dva#1187]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
直接
```javascript
import { browserHistory } from 'dva/router';
```

#### Expected behavior: (预期的正常效果)
browserHistory 有值

#### Actual behavior: (实际效果)
browserHistory undifined

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva 2.0.1

你们有没有出现这么诡异的问题？

**Comment by zjxpcyc** [comment]
还有个问题，默认 history 是 hash 的，但是如果我的 Router 是  BrowserRouter , 这两个会不匹配

**Comment by sorrycc** [comment]
参考这个 [commit](https://github.com/dvajs/dva/commit/8480aac309b19364b13d1c88b435d310eec0d86a)。
