### ISSUE TITLE
dva 2.0.1 跳转不了

### ISSUE THREAD

**Issue by zjxpcyc** [dvajs/dva#1188]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
使用的 antd 的 [menu](https://ant.design/components/menu-cn/)
```javascript
<Menu.Item><Link to="/foo">foo</Link></Menu.Item>
```

路由的地方是这样
```javascript
<Router history={history}>
  <MainLayout>
    <Route path="/foo" component={Foo} />
  </MainLayout>
</Router >
```

或者
```javascript
<ConnectedRouter history={history}>
  <MainLayout>
    <Route path="/foo" component={Foo} />
  </MainLayout>
</ConnectedRouter >
```

或者
```javascript
<Router history={history}>
  <MainLayout>
    <Route path="/foo" component={withRouter(Foo)} />
  </MainLayout>
</Router >
```

#### Expected behavior: (预期的正常效果)
页面正常跳转或者组件刷新

#### Actual behavior: (实际效果)
浏览器地址栏已经改变, 但是页面没有任何反应，连错误都没有
但是如果刷新一下，则可以正常显示

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva 2.0.1

连续的出问题，我已经感觉，我 install 了一个假 dva

**Comment by yangbin1994** [comment]
```javascript
import createHistory from 'history/createBrowserHistory'

const app = window.app = dva({
  ...createLoading({
    effects: true,
  }),
  history: createHistory(),
  onError(error) {
    message.error(error.message)
  },
})
```
试一下看

**Comment by zjxpcyc** [comment]
@yangbin1994 跟我描述的现象一样，浏览器地址变了，但是页面没刷新

**Comment by yangbin1994** [comment]
@zjxpcyc 参考一下[这个](https://github.com/yangbin1994/antd-admin/tree/dva2.0)

**Comment by zjxpcyc** [comment]
@yangbin1994 修改成基本上是一致的，但是就是页面不刷新，浏览器地址倒是变了。除非手动去 F5

**Comment by sorrycc** [comment]
给个能重现的 demo 传上来？

**Comment by zjxpcyc** [comment]
@sorrycc 
样例工程 [https://github.com/zjxpcyc/dva-issue1188-sample](https://github.com/zjxpcyc/dva-issue1188-sample)

发现问题出在哪了，但是不知道原因。
在我的最外层 [Layout](https://github.com/zjxpcyc/dva-issue1188-sample/blob/master/src/routes/App.js#L29)

```javascript
export default connect(s => s.app)(App);
```

如果这里不使用 connect ，而是直接 export ，就是正常的。

我这里用 connect 的原因，主要是为了判断 [是否已经登录](https://github.com/zjxpcyc/dva-issue1188-sample/blob/master/src/routes/App.js#L9)

**Comment by zjxpcyc** [comment]
@sorrycc 为啥关了？原因找到了吗？
我现在降到1.2版本，等你搞好了，升2呢

**Comment by sorrycc** [comment]
呃，我以为你解决了。

**Comment by sorrycc** [comment]
Modify the `src/routes/App.js`:

```diff;
- import { Link } from 'dva/router';
+ import { Link, withRouter } from 'dva/router';

- export default connect(s => s.app)(App);
+ export default withRouter(connect(s => s.app)(App));
```

**Comment by zjxpcyc** [comment]
@sorrycc THX, 上午升级下，再试试

**Comment by zjxpcyc** [comment]
可以了
