### ISSUE TITLE
antd-tools,ant-tool,atool-build是什么关系?

### ISSUE THREAD

**Issue by lefter** [dvajs/dva#119]
搞晕了，这几个工具是什么关系，怎么分工的？
antd-tools
https://github.com/ant-design/antd-tools

ant-tool
https://github.com/ant-tool

atool-build
https://github.com/ant-tool/atool-build/

dora
https://github.com/dora-js/dora

dora-plugin-webpack
https://github.com/dora-js/dora-plugin-webpack

**Comment by sorrycc** [comment]
项目开发知道以下三个就可以了。

- atool-build, 打包工具
- dora, 开发服务器
- dora-plugin-webpack，dora 的插件，用于和 atool-buid 整合

另外两个：

- antd-tools，基于 atool-build 封装的开发 ant-design 用的工具，不需要关心
- ant-tool，group 名，也不需要关心

**Comment by junmaqiang** [comment]
贵谱系好乱，哈哈
