### ISSUE TITLE
如何使用dva构建react native

### ISSUE THREAD

**Issue by wudashuaige** [dvajs/dva#1195]
dva的工程目录是构建完react-native的工程后再手动的划分成dva的目录结构吗？还是有dva的react-native构建命令，react的是有dva构建工程命令的，感谢

**Comment by sorrycc** [comment]
> 构建完react-native的工程后再手动的划分成dva的目录结构吗？

是的，暂时没有 react-native 的脚手架，希望社区有同学能贡献一个方案。

**Comment by 96qbhy** [comment]
可以考虑用 react-native-template 来构建

**Comment by nihgwu** [comment]
https://github.com/nihgwu/react-native-dva-starter

**Comment by horiuchie** [comment]
I created an example too. 
https://github.com/horiuchie/react-native-dva-starter-with-builtin-router

**Comment by sppsun** [comment]
There is a much more completely [demo](https://github.com/sppsun/acgnfuns-app).
