### ISSUE TITLE
babel-plugin-dva-hmr 无效

### ISSUE THREAD

**Issue by Huyunxiu** [dvajs/dva#1196]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

node v8.1.2
npm 5.4.0

```bash
git clone git@github.com:dvajs/dva.git --depth=1
cd dva/packages/dva-example-user-dashboard/
npm i
npm start
```

执行以上步骤以后进入 `src/componentsMainLayout/Header.js`

修改 **15 - 17 行**

```
      <Menu.Item key="/">
        <Link to="/"><Icon type="home" />Home</Link>
      </Menu.Item>
```

为

```
      <Menu.Item key="/">
        <Link to="/"><Icon type="home" />HomeLayout</Link>
      </Menu.Item>
```

#### Expected behavior: (预期的正常效果)

预期可以进行HMR

#### Actual behavior: (实际效果)

实际上HMR无效

#### Versions of packages used: (哪个库的哪个版本出现的问题)

报错

![image](https://user-images.githubusercontent.com/19355142/30199296-c27c5692-9437-11e7-81dc-7d39f35f4b76.png)

**Comment by sorrycc** [comment]
Fixed in dva@2.0.2
