### ISSUE TITLE
动态路由, onEnter 如何在组件中做验证

### ISSUE THREAD

**Issue by pengfeiWang** [dvajs/dva#1198]
```js
const Routers = function Routers({ history, app }) {
  const routes = [
    {
      'path': '/',
      'component': App,
      getIndexRoute(nextState, cb) {
        require.ensure([], (require) => {
          cb(null, { 'component': require('./modules/index') });
        }, 'app');
      },
      'childRoutes': [
        {
          'path': 'mail',
          getComponent(nextState, cb) {
            require.ensure([], (require) => {
              cb(null, require('./modules/mail'));
            });
          }
        }
      ]
    },

    {
      'path': '*',
      getComponent(nextState, cb) {
        require.ensure([], (require) => {
          cb(null, require('./modules/404'));
        });
      }
    }
  ];

  return <Router history={history} routes={routes} />;
};
```

我想在 进入`mail` 时做一次数据请求验证, 如果验证通过, 则进入 `mail`,  
是不是应该在 `./modules/mail` 组件中利用 `onEnter` 来做处理呢, 不知道该如何写了

**Comment by shenggen1987** [comment]
`function RouterConfig({ history, app }) {
  const IndexPage = dynamic({
    app,
    models: () => [
    ],
    component: () => import('./routes/IndexPage'),
  });

  const Users = dynamic({
    app,
    models: () => [
      import('./models/users'),
    ],
    component: () => import('./routes/Users'),
  });
  const CRMs = dynamic({
    app,
    models: () => [
      import('./models/app'),
    ],
    component: () => {
      return ({ match }) => (
        <div>
          <Route path={`${match.url}/users`} component={Users}/>
          <Route path={match.url} component={IndexPage} />
        </div>
      )
    },
  });

  return (
    <Router history={history}>
      <Switch>
        <Route path="/crm" component={CRMs} />
        <Route component={NotFound} />
      </Switch>
    </Router>
  );
}`
不需要用onEnter

**Comment by sorrycc** [comment]
参考 react-router 官方的例子，https://github.com/ReactTraining/react-router/blob/v3/examples/auth-flow-async-with-query-params/app.js#L95
