### ISSUE TITLE
在components文件夹里面的less文件怎么引用

### ISSUE THREAD

**Issue by ouzhou** [dvajs/dva#120]
好像只能使用import style from './xx.less'  ， 能不能import './xx.less' (在components文件下 不是在src/index )

**Comment by sorrycc** [comment]
和在什么地方没关系，如果你是用 dva-cli 初始化出来的项目，因为使用了 css-modules，所以 `import './xx.less'` 打包出来的 className 会被 hash 化，自然没有效果。

https://github.com/dvajs/dva-knowledgemap#css-modules

**Comment by ouzhou** [comment]
所以说 要么自己用webpack搭建，要么就不这样import，或者自己去掉css-modules？ok
