### ISSUE TITLE
升级roadhog后  build:dll无法使用

### ISSUE THREAD

**Issue by dingyanqiang** [dvajs/dva#1203]
### 升级roadhog后（1.2版本）  build:dll无法使用
* build:dll可以正常
 * https://github.com/dvajs/dva-example-user-dashboard
* buld:dll报错
 * https://github.com/dvajs/dva/tree/master/packages/dva-example-user-dashboard

* 对比了下roadhog版本号不一致 改过后还是报错，不知问题出在哪儿
* 原来是xdllPlugin错了，应该是dllPlugin  而且dll.js文件地址跑到.nodemodule里面了
 ```
Creating dll bundle...
Compiled successfully in 2.5s.

File sizes after gzip:

  280.33 KB  /Users/dingyanqiang/Work/myapp/node_modules/roadhog-dlls/roadhog.dll.js
 ```

* 另外:想在一个项目里面放多个页面（多个spa），没找到对应文档

**Comment by sorrycc** [comment]
> 而且dll.js文件地址跑到.nodemodule里面了

在 node_modules 里是正确的。

> 想在一个项目里面放多个页面（多个spa），没找到对应文档

多页建议用 next.js + dva 的组合，参考 https://github.com/dvajs/dva/tree/master/packages/dva-example-nextjs
