### ISSUE TITLE
dva-loading peerDependencies warning

### ISSUE THREAD

**Issue by Jeepeng** [dvajs/dva#1206]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
```
npm install dva-loading --save
```
RN上没用到dva，用了dva-core，安装dva-loading后，出现warning。当然，不影响使用

#### Expected behavior: (预期的正常效果)
无warning

#### Actual behavior: (实际效果)
```
npm WARN dva-loading@1.0.0 requires a peer of dva@^2.0.1 but none was installed.
```

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva-core@1.0.1
dva-loading@1.0.0

**Comment by sorrycc** [comment]
这没啥好办法，忽略吧。
