### ISSUE TITLE
默认DVA启动后，index.css 无法返回正确内容

### ISSUE THREAD

**Issue by yyjs** [dvajs/dva#1207]
默认DVA启动后，index.css 无法返回正确内容

![qq20170911-111400](https://user-images.githubusercontent.com/9820142/30257153-867acdba-96e2-11e7-801b-53b3978ee8ea.png)

**Comment by sorrycc** [comment]
忽略这个错误，调试模式的样式是通过 JS 内联载入的（为了热更新），生产环境不会有这个问题。

**Comment by wangyazhen** [comment]
@sorrycc 你好 我在调试模式下遇到这个问题   **TTFB的时间太长**  我不知道如何解决.  any ideas?
是否需要 **new issues**
### 环境
-  os            windows
- roadhog   "^1.3.1"
- dva            "2.1.0"
- antd         "^2.13.7"

![test](https://user-images.githubusercontent.com/5687531/32826869-0ae3f35e-ca25-11e7-8e21-64be3b41d4cc.png)

![image](https://user-images.githubusercontent.com/5687531/32827176-2f8568b8-ca26-11e7-8f05-2e45ae8250c7.png)
