### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by liorix** [dvajs/dva#121]
Hi,

I played with dvajs and it looks like a really great project. I was wondering if there is support for server side rendering as I couldn't find any mention of that in the documentation.

Thanks,
Lior

**Comment by WhatAKitty** [comment]
#85

**Comment by sorrycc** [comment]
Thanks for the attention, it will be supported in next minor version. #85

**Comment by liorix** [comment]
Thanks for the update @sorrycc!

**Comment by timpler** [comment]
@sorrycc I'm starting new project. Do you recommend waiting for version 2.0 or to start with 1.0 (I need SSR)

**Comment by sorrycc** [comment]
Wait for 1.1, it's planned to release next week.

**Comment by timpler** [comment]
@sorrycc thanks! So it'll have server side rendering built in?

**Comment by sorrycc** [comment]
Try this [boilerplate](https://github.com/sorrycc/dva-boilerplate-isomorphic), it works with dva@1.1 .

**Comment by liorix** [comment]
@sorrycc - looks great! Is there a way to prefetch the relevant data from the server without explicitly having this url matching switch:

```
     switch (renderProps.location.pathname) {
        case '/':
          fetchList()
            .then(({ err, data }) => {
              if (err) {
                res.status(500).end(`Uncaught error: ${err}`);
                return;
              }
              const initialState = { user: data };
              const app = createApp({
                history: createMemoryHistory(),
                initialState,
              });
              const html = renderToString(app.start()());
              res.end(renderFullPage(html, initialState));
            });
          break;
        case '/about':
          const app = createApp({
            history: createMemoryHistory(),
          });
          const html = renderToString(app.start()());
          res.end(renderFullPage(html, {}));
          break;
        default:
          res.status(500).end(`Uncaught pathname: ${renderProps.location.pathname}`);
          break;
      }
```


What do you think about approach similar to this concept:
https://github.com/flowcommerce/redux-fetch

Thanks!
Lior
