### ISSUE TITLE
可以直接通过 import 的方式使用 location 和 dispatch 这两个吗

### ISSUE THREAD

**Issue by Mosaic91** [dvajs/dva#1211]
这两个对象通过 Route 层层向下传递太麻烦了，可以通过 import 的方式直接在需要的地方引入使用吗

**Comment by longzhaobi** [comment]
你在第一层直接弄成 window.dispatch = dispatch，window.location = location ，然后哪里都可以用，还不用引入，我没试过不知道行不行，你先传递麻烦可以去试试。

**Comment by Mosaic91** [comment]
可行，但是感觉不太优雅

**Comment by sorrycc** [comment]
参考 https://reacttraining.com/react-router/web/api/withRouter
