### ISSUE TITLE
dva counter 例子优化

### ISSUE THREAD

**Issue by monkindey** [dvajs/dva#1213]
我修改的代码对应的链接 https://stackblitz.com/edit/dva-example-count-hykf32

主要把下面的操作按钮抽离处理, 这样子做的好处是不跟页面更新的的count一起。
在setState的时候其实下面的按钮是没必要执行render的, 让redux的connect
帮我们进行`shouldComponentUpdate`对比。

**Comment by sorrycc** [comment]
理解了下，感觉是不是得把 `<h2>{ props.count }</h2>` 提成组件，然后 connect 这个组件才能达到你所说的效果？

**Comment by monkindey** [comment]
可以这样子

这个是之前的

```js
const App = connect(({ count }) => ({
  count
}))(function(props) {
  return (
    <div>
      <h2>{ props.count }</h2>
      <button key="add" onClick={() => { props.dispatch({type: 'count/add'})}}>+</button>
      <button key="minus" onClick={() => { props.dispatch({type: 'count/minus'})}}>-</button>
    </div>
  );
});
```

可以变成这样子

```js
const Footer = connect()(props => (
  <div>
    <button
      key="add"
      onClick={() => {
        props.dispatch({ type: 'count/add' });
      }}
    >
      +
    </button>
    <button
      key="minus"
      onClick={() => {
        props.dispatch({ type: 'count/minus' });
      }}
    >
      -
    </button>
  </div>
));

const App = connect(({ count }) => ({
  count
}))(function(props) {
  return (
    <div>
      <h2>{ props.count }</h2>
      <Footer />
    </div>
  );
});
```

把button抽离出来, 因为每一次的操作都会setState, 如果把button跟`{ props.count }`放在一起的话, 每一次都是需要执行button render操作的。

**Comment by szwork2013** [comment]
的确是有必要，我也fork 修改了一下：
https://stackblitz.com/edit/dva-example-count-xeyzz3

**Comment by nihgwu** [comment]
其实如果不是有明显的性能问题，没必要做特别的处理，使用 redux 因为不是不是响应式的，确实容易产生不必要的rerender，但是很多是时候是可以忽略的，就比如修改版里面的 handler 都是内联的，其实这种写法反而是应该尽量避免的

**Comment by monkindey** [comment]
对于您的回复我持半同意

> 尽量避免内联handler, 您指的内联handler应该是这个吧。

```js
  // 内联函数
  onClick={() => {
    props.dispatch({ type: 'count/minus' });
  }}
```

如果在多个list项的时候会有性能问题, 可以把它拿出来, 赋值给一个变量, 这个我同意。

> 使用 redux 因为不是不是响应式的，确实容易产生不必要的rerender，但是很多是时候是可以忽略的 

这个我不同意, 这样子的话react就没必要存在`shouldComponentUpdate`, connect也没必要帮你做prop比较, 勿以善小而不为, 优化从小事做起, 也是了解react缺陷的一个方式。 这个是vue的优势, 它可以依赖收集, 更加准确定位到需要修改的Component.

**Comment by nihgwu** [comment]
其实如果你真的有洁癖的话，用 redux 的话有很多地方都需要优化，这种自顶向下的 reduce 必然会造成各个环节的优化需求

我也没有说这种做法没有意义，我在开发 react app 的时候也很注意性能优化的问题，但是我觉得我们应该把更多的精力放在功能实现上，而不是被所用的框架所捆住

还有如果你很喜欢 Vue 那种指哪打哪的响应式更新，建议可以试试 mobx，这样很多优化都是 out of box 的

**Comment by monkindey** [comment]
引用 addy osmani的一句话, 对应twitter https://twitter.com/addyosmani/status/314785735171518464

> First do it, then do it right, then do it better

确实需要把精力放在功能实现上, 但是你只有想要去优化, 才会去深入了解react, redux的机制, 它有什么优缺点, 每个模式都有自己的优缺点, 针对自己的业务然后选择符合这个场景的技术, 这个才能真正做到`不被所用的框架所捆住`, 而不是通过逃避。当然这个是我个人的想法, 每个程序员最有成就感的时候应该是你能去优化, 达到了什么受益之类的, 就算是微不足道的优化措施。

> 建议可以试试 mobx，这样很多优化都是 out of box 的

感谢你的建议, 最近在选型, 有打算试试。

**Comment by sorrycc** [comment]
性能问题研究地少，通常在遇到真正的性能问题之前，我很少会主动地做性能优化。count 例子以演示 dva 功能为主，没做啥优化，这个 issue 就先关了。
