### ISSUE TITLE
dva-example-user-dashboard 这个例子跑不起来

### ISSUE THREAD

**Issue by wm3445** [dvajs/dva#1216]
dva-example-user-dashboard 这个例子跑不起来，疯狂爆warning啊。
![image](https://user-images.githubusercontent.com/5467635/30407805-26e30c26-992d-11e7-8b9e-38aca8b8cbba.png)

**Comment by sorrycc** [comment]
刚试了一遍，没发现问题。删除 node_modules 重新安装依赖试试吧。
