### ISSUE TITLE
babel-plugin-import  无法加载antd样式 

### ISSUE THREAD

**Issue by liujian969** [dvajs/dva#1217]
按照antd官方文档， 安装antd和 babel-plugin-import 后，并配置.
**.roadhogrc`**

{
  "entry": "src/index.js",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime"
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
	**["import", { "libraryName": "antd", "style": "css" }]**
      ]
    }
  }
}

**页面product.js** 

### import React from 'react';
import PropTypes from 'prop-types';
import { Table, Popconfirm, Button } from 'antd';

const ProductList = ({ onDelete, products }) => {
  const columns = [{
    title: 'Name',
    dataIndex: 'name',
  }, {
    title: 'Actions',
    render: (text, record) => {
      return (
        <Popconfirm title="Delete?" onConfirm={() => onDelete(record.id)}>
          <Button>Delete</Button>
        </Popconfirm>
      );
    },
  }];
  return (
    <Table
      dataSource={products}
      columns={columns}
    />
  );
};

ProductList.propTypes = {
  onDelete: PropTypes.func.isRequired,
  products: PropTypes.array.isRequired,
};

export default ProductList;

运行时，样式么有按需加载。
页面没有任何样式。

浏览器Console窗口依然提示
**You are using a whole package of antd,**** please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.

**Comment by longzhaobi** [comment]
你这个样式添加到了生产模式，你到开发模式那里也添加["import", { "libraryName": "antd", "style": "css" }]试试

**Comment by haohailong1990** [comment]
生成刷新就有样式antd和自定义样式没有加载进来
