### ISSUE TITLE
关于return的html组件里面，ref不知道怎样调用

### ISSUE THREAD

**Issue by daxiong-liang** [dvajs/dva#1219]
关于return的html组件里面，ref不知道怎样调用，我需要使用echarts这类的图形插件展示数据，但是echarts一般都需要获得dom去初始化自己的组件，因此需要ref属性
如果是原生的react 的话，是可以获取
但是使用dva之后，会报null异常，代码如下，希望作者能指点一下

原生的react是可以在生命周期的方法去获取ref属性，只是不知道dva的生命周期怎样走

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
const ReactEcharts = (props) => {
  const echartsInstance = echarts; // the echarts object.
  const echartsElement = this.echartsElementTest; // 此处已经报错
  console.log();
  
  return (
    <div
      ref={(e) => { this.echartsElementTest = e; }}
      style={props.style}
      className={props.className}
    />
  );
};

#### Expected behavior: (预期的正常效果)
正常能够获取div的dom

**Comment by nihgwu** [comment]
这个跟 dva 有什么问题？为什么在这开 issue？ stateless component 没有 ref

**Comment by zjxpcyc** [comment]
@daxiong-liang 不用是 stateless 的写法，直接 extends Component

**Comment by daxiong-liang** [comment]
@nihgwu  stateless component 是什么，我不清楚相关概念，已经改用了class这种了

**Comment by daxiong-liang** [comment]
zjxpcyc 已经改用了class这种了，说真的，对 stateless真的不了解

**Comment by monkindey** [comment]
@daxiong-liang  https://facebook.github.io/react/docs/refs-and-the-dom.html#refs-and-functional-components

> You may not use the ref attribute on functional components because they don't have instances

说是Stateless Component不严谨, 应该是functional Component

**Comment by lhx6538665** [comment]
https://github.com/dvajs/dva/issues/906#issuecomment-521501291
