### ISSUE TITLE
How to remove ?_k=7e0x9o from hash

### ISSUE THREAD

**Issue by Danjavia** [dvajs/dva#122]
I Try using 

```
import { browserHistory } from 'dva/router';

const app = dva({
    history: browserHistory
});
```

But after this. Application routes not function.

**Comment by longzb** [comment]
import { useRouterHistory } from 'dva/router';
import { createHashHistory } from 'history';
const app = dva({
  history: useRouterHistory(createHashHistory)({ queryKey: false }),
});

**Comment by longzb** [comment]
`import { useRouterHistory } from 'dva/router';
import { createHashHistory } from 'history';
const app = dva({
history: useRouterHistory(createHashHistory)({ queryKey: false }),
});`

**Comment by longzb** [comment]
```
import { useRouterHistory } from 'dva/router';
import { createHashHistory } from 'history';
const app = dva({
history: useRouterHistory(createHashHistory)({ queryKey: false }),
});
```

**Comment by Danjavia** [comment]
thanks
