### ISSUE TITLE
Server AnyProxy

### ISSUE THREAD

**Issue by luocong2016** [dvajs/dva#1223]
两个项目放在一个服务器上，两个项目切换就会出现下面错误
1.在服务器端会出现这种情况
Caught exception: Error: ENOENT: no such file or directory, open '/root/.anyproxy/cache_r452027/res_body_7'
at Error (native)
AnyProxy is about to exit with code: 0
环境：node 6.1.0

2.window 下我修改dora-anyproxy  后就能用

**Comment by sorrycc** [comment]
建议切换到 [roadhog](https://github.com/sorrycc/roadhog)，dora + anyproxy 的方式已经久不更新了。
