### ISSUE TITLE
路由配置正确，代码也没报错，但没有效果

### ISSUE THREAD

**Issue by archimate** [dvajs/dva#1226]
![image](https://user-images.githubusercontent.com/8114237/30508134-33f57fd4-9ac2-11e7-871a-f16975001476.png)

![image](https://user-images.githubusercontent.com/8114237/30508136-3fb8ab84-9ac2-11e7-8870-ff93a477fdab.png)

![image](https://user-images.githubusercontent.com/8114237/30508138-4515dc46-9ac2-11e7-9077-cf541e345866.png)
![image](https://user-images.githubusercontent.com/8114237/30508141-503c2058-9ac2-11e7-85ad-a8a838a0bf36.png)
谁知道哪里有问题

**Comment by sorrycc** [comment]
给的信息太少，帮不到你。问题请在 https://segmentfault.com/ 上提或者[加微信群互助](https://github.com/dvajs/dva/issues/1150)。

**Comment by 67775128** [comment]
@archimate 楼主解决了吗，我也遇到这个问题
