### ISSUE TITLE
请问 dva-loading 怎么用的？

### ISSUE THREAD

**Issue by zjxpcyc** [dvajs/dva#1230]
dva-loading 是什么？ 

是理解中的菊花转吗？ 

是只要一句 `createLoading()` 就可以了吗？ 怎么看不到菊花？

**Comment by nihgwu** [comment]
dva-loading 只是帮你内建了一些state，如何显示菊花是你自己根据这些state控制的，这种直接看源码就知道答案了

**Comment by zjxpcyc** [comment]
@nihgwu 谢谢
