### ISSUE TITLE
dva new myApp 启动后，IE下报语法错误

### ISSUE THREAD

**Issue by Bennes** [dvajs/dva#1233]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
dva new **，然后启动即可以发现

#### Expected behavior: (预期的正常效果)
初始化后正常显示

#### Actual behavior: (实际效果)
IE报语法错误

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"antd": "^2.13.2",
"babel-plugin-import": "^1.4.0",
"babel-runtime": "^6.9.2",
    "dva": "^2.0.3",
    "dva-loading": "^1.0.2",
    "react": "^15.4.0",
    "react-dom": "^15.4.0"

@sorrycc

**Comment by sorrycc** [comment]
IE 什么版本？

**Comment by Bennes** [comment]
"use strict";
eval("\n\nmodule.exports = () => {\n\tconst pattern = [\n\t\t'[\\\\u001B\\\\u009B][[\\\\]()#;?]*(?:(?:(?:[a-zA-Z\\\\d]*(?:;[a-zA-Z\\\\d]*)*)?\\\\u0007)',\n\t\t'(?:(?:\\\\d{1,4}(?:;\\\\d{0,4})*)?[\\\\dA-PRZcf-ntqry=><~]))'\n\t].join('|');\n\n\treturn new RegExp(pattern, 'g');\n};\n\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiMTU4LmpzIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4vbm9kZV9tb2R1bGVzL19hbnNpLXJlZ2V4QDMuMC4wQGFuc2ktcmVnZXgvaW5kZXguanM/MzAwYyJdLCJzb3VyY2VzQ29udGVudCI6WyIndXNlIHN0cmljdCc7XG5cbm1vZHVsZS5leHBvcnRzID0gKCkgPT4ge1xuXHRjb25zdCBwYXR0ZXJuID0gW1xuXHRcdCdbXFxcXHUwMDFCXFxcXHUwMDlCXVtbXFxcXF0oKSM7P10qKD86KD86KD86W2EtekEtWlxcXFxkXSooPzo7W2EtekEtWlxcXFxkXSopKik/XFxcXHUwMDA3KScsXG5cdFx0Jyg/Oig/OlxcXFxkezEsNH0oPzo7XFxcXGR7MCw0fSkqKT9bXFxcXGRBLVBSWmNmLW50cXJ5PT48fl0pKSdcblx0XS5qb2luKCd8Jyk7XG5cblx0cmV0dXJuIG5ldyBSZWdFeHAocGF0dGVybiwgJ2cnKTtcbn07XG5cblxuXG4vLy8vLy8vLy8vLy8vLy8vLy9cbi8vIFdFQlBBQ0sgRk9PVEVSXG4vLyAuL25vZGVfbW9kdWxlcy9fYW5zaS1yZWdleEAzLjAuMEBhbnNpLXJlZ2V4L2luZGV4LmpzXG4vLyBtb2R1bGUgaWQgPSAxNThcbi8vIG1vZHVsZSBjaHVua3MgPSAwIl0sIm1hcHBpbmdzIjoiQUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTsiLCJzb3VyY2VSb290IjoiIn0=\n//# sourceURL=webpack-internal:///158\n");


这一段报的，IE11，我模拟9，10，11都有这个问题

**Comment by sorrycc** [comment]
.roadhogrc 里配 `"devtool": ""` 试试。

**Comment by Bennes** [comment]
谢谢，用npm run build的成果物IE访问没有该问题,你那边是否能重现？

我配置后，如下
{
  "entry": ["src/login.js","src/index.js"],
  "disableCSSModules":true,
  "devtool": "",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }]
      ]
    }
  },
  "proxy": {
	  "/**.do": {
	    "target": "http://localhost:8080/",
	    "changeOrigin": true
	  }
	}
}

**Comment by spiroo** [comment]
我也碰到这个问题了，dva new xx出来得项目，启动后IE11下报错。
![image](https://user-images.githubusercontent.com/7858201/31313281-df7fd5a2-ac10-11e7-8a3f-c9e95b2231fa.png)

**Comment by grunmin** [comment]
开了sourcemap之后build出来的文件, IE访问会报语法错误

**Comment by afc163** [comment]
` "devtool": "",` 貌似没有效果，https://github.com/ant-design-pro/ant-design-pro 启动后在 IE11 依然报错。

```


/***/ }),
/* 188 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


module.exports = () => {
	const pattern = [
		'[\\u001B\\u009B][[\\]()#;?]*(?:(?:(?:[a-zA-Z\\d]*(?:;[a-zA-Z\\d]*)*)?\\u0007)',
		'(?:(?:\\d{1,4}(?:;\\d{0,4})*)?[\\dA-PRZcf-ntqry=><~]))'
	].join('|');

	return new RegExp(pattern, 'g');
};
```

**Comment by afc163** [comment]
https://github.com/sorrycc/roadhog/blob/142404295868df2d4c40c0fe0271ad1ea3532cb9/src/runServer.js#L165

好像写死了 hot

**Comment by yesmeck** [comment]
这个模块的问题 https://github.com/chalk/ansi-regex/issues/15

**Comment by yesmeck** [comment]
https://github.com/facebookincubator/create-react-app/issues/2691

**Comment by zjafei** [comment]
roadhog 0.6.0以后就有这样的问题了 
但是打包出来没有问题 
就是开发环境

**Comment by a298003154** [comment]
the same problem in IE9.
![image](https://user-images.githubusercontent.com/24939100/34345999-4c3cb682-ea2e-11e7-9ff0-bbfe1918d72c.png)
![image](https://user-images.githubusercontent.com/24939100/34346003-5e807acc-ea2e-11e7-8c26-58997ee89292.png)
