### ISSUE TITLE
浏览网站时为什么会先直接显示文字.再套上样式?

### ISSUE THREAD

**Issue by firemoon2000** [dvajs/dva#1237]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
启动项目

#### Expected behavior: (预期的正常效果)
直接显示网站

#### Actual behavior: (实际效果)
启动项目时会先用无样式的方式把文字列在画面上
随后1秒后才套上样式..
是代码问题.还是异步载入样式机制就是如此的?

#### Versions of packages used: (哪个库的哪个版本出现的问题)
最新的

**Comment by firemoon2000** [comment]
User Dashboard sample就是如此..
望指教..感谢哟.

**Comment by szwork2013** [comment]
me too

**Comment by sorrycc** [comment]
dev 模式下就是这样的，为了热替换，把 CSS 打包在 JS 里。production 下不会这样。
