### ISSUE TITLE
OnEnter没有了。。。。

### ISSUE THREAD

**Issue by babizhu** [dvajs/dva#1238]
升级到dva 2之后，相应的使用了 react-router@4，从而导致onEnter没有了，
我之前是采用这个做相关登录验证的，
那么请问现在怎么做相关的验证呢

**Comment by nihgwu** [comment]
看 react-router 的文档

**Comment by sorrycc** [comment]
https://css-tricks.com/react-router-4/
先看下文档，有讲如何做校验的。
