### ISSUE TITLE
不同命名空间之间能够监听action？

### ISSUE THREAD

**Issue by miserylee** [dvajs/dva#124]
比如有两个命名空间 A 和 B

A 的 `selectKey` 消息会影响到 B 的 `state` 更新。

A 发出的消息为 `A/selectKey`

在Dva里，model里面的effects的命名默认加上了命名空间，如果写成`A/selectKey` 会处理为监听 `B/A/selectKey`。

同理，如果 B 的model里面 put 了命名为 `loaded` 的action， 那么会处理为put了`B/loaded`

这种情况如何处理？

**Comment by sorrycc** [comment]
在 `A/selectKey` 里触发 `B/selectKey` ?

**Comment by miserylee** [comment]
@sorrycc 在A的effects里面写 put({type: 'xxxxx'})的时候，希望能被B的reducer监听并进行处理

**Comment by miserylee** [comment]
比如使用 redux-persist库的时候，需要在自己的reducer里面处理 persist 里面的 `REHYDRATE` 消息

**Comment by sorrycc** [comment]
https://facebook.github.io/react-native/docs/network.html
看了下 RN 的文档，直接用 fetch 就好了，别引 `dva/fetch`。

**Comment by sorrycc** [comment]
在 A 的 effect 里同时 `put({type: 'selectKey' });` 和 `put({ type: 'B/selectKey' }` ?

**Comment by miserylee** [comment]
简化一下问题：

已知有一个action的type 为`REHYDRATE`
现在需要在namespace为B的model里面的reducers里面处理`REHYDRATE`消息
但是reducer里面的消息名称在定义后会被dva自动加上namespace前缀
也就是说如果在B的reducer里面写了
```javascript
[REHYDRATE] (state) {
  // do sth.
}
```
会被处理为
```javascript
[B/REHYDRATE] (state) {
}
```

**Comment by sorrycc** [comment]
要通过 reducerEnhancer 来解决了，参考：
https://github.com/dvajs/dva/blob/f13e7eb/test/reducers-test.js#L35-L59

**Comment by miserylee** [comment]
嗯 这种方式是可以，只是这样写感觉不太优雅，所以才开了个issue，看能不能让dva优雅的支持这种问题

**Comment by sorrycc** [comment]
用例里的例子是不够优雅，真实项目可以考虑用高阶函数的方式组织。

```js
import createModel from '';
export default createModel()(/* YOUR MODEL */);
```

**Comment by miserylee** [comment]
我再琢磨一下吧，谢谢建议
