### ISSUE TITLE
在TypeScript环境遇到  [app.model] namespace should be defined 问题

### ISSUE THREAD

**Issue by fengylm** [dvajs/dva#1240]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
在TypeScript中使用dva/dynamic 动态加载 路由时候发现有个错误提示
> [app.model] namespace should be defined

追踪了下代码 发现在 node_modules\dva\lib\dynamic.js 中的 dynamic 函数里有一段代码
`_promise2.default.all([].concat((0, _toConsumableArray3.default)(models), [component]))
.then(function (ret) {/**/ })
`
这里得到的ret参数有问题

#### Expected behavior: (预期的正常效果)

正常的ret应该是一个model对象

#### Actual behavior: (实际效果)

实际得到的ret是一个带有 __esModule 和default属性的对象

__esModule属性是值是true,default属性的值是model对象

#### Versions of packages used: (哪个库的哪个版本出现的问题)
用的是最新的库版本

#### tsconfig

> {
  "compilerOptions": {
    "baseUrl": ".",
    "module": "esnext",
    "moduleResolution": "node",
    "target": "es2015",
    "jsx": "react",
    "sourceMap": true,
    "skipDefaultLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "removeComments": true
  },
  "exclude": [
    "bin",
    "node_modules"
  ],
   "typeRoots": [
    "node_modules/@types"
  ]
}

#### package.json
>{
  "name": "test",
  "private": true,
  "version": "0.0.0",
  "devDependencies": {
    "webpack": "^3.5.6",
    "typescript": "^2.5.2",
    "extract-text-webpack-plugin": "^3.0.0",
    "awesome-typescript-loader": "^3.2.3",
    "css-loader": "^0.28.7",
    "style-loader": "^0.18.2",
    "url-loader": "^0.5.9",
    "less": "^2.7.2",
    "less-loader": "^4.0.5"
  },
  "dependencies": {
    "@types/history": "4.6.0",
    "@types/react": "16.0.5",
    "@types/react-router": "4.0.15",
    "antd": "^2.13.2",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "dva": "^2.0.3",
    "dva-loading": "^1.0.2",
    "classnames": "^2.2.5"
  }
}

**Comment by sorrycc** [comment]
Fixed via https://github.com/dvajs/dva/blob/fa92d0a4df38dba8b35ae4a9722a5c876d5c3531/packages/dva/src/dynamic.js#L28

**Comment by yanghuayi** [comment]
这个问题，好像最新版本没修复，不知道什么时候更新修复@sorrycc
