### ISSUE TITLE
关于dynamic接口用法的一点疑问

### ISSUE THREAD

**Issue by SuperNaturalGit** [dvajs/dva#1243]
试用了一下dva@2.x新增的dva/dynamic接口，发现如果用这种写法：
`const IndexPage = dynamic({
    app,
    component:  import('./routes/IndexPage'),
  });`
页面会渲染不出来，而且会报大量的warning。
但是这是[dva@2.0升级日志](https://github.com/sorrycc/blog/issues/48)上提供的写法。
换这种写法：
`const IndexPage = dynamic({
    app,
    component: () => import('./routes/IndexPage'),
  });`
就能正常渲染。
区别只是多了一个箭头函数。
看warning内容，似乎这里只能接受function？

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
把dva-example-user-dashboard这个demo的router.js的写法调整一下就能复现。

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva@2.0.3
roadhog@1.2.0

如果参数中的models和component只能接收function，升级日志里应该改一下。

**Comment by longzhaobi** [comment]
具体请点击这个https://github.com/dvajs/dva/commit/6e0d7cdc16d15f44c85fffb9ddc62da1344006f4 
查看这个修改日志，好像是2.0.1修改成函数方式的，或许作者忘记修改那个升级日志了。

**Comment by longzhaobi** [comment]
至于为何要修改，请查看这个https://github.com/dvajs/dva/pull/1176

**Comment by sorrycc** [comment]
感谢反馈，已更新文档。
