### ISSUE TITLE
packages/dva-example-user-dashboard中的例子在手机部分浏览器url地址没有变化

### ISSUE THREAD

**Issue by szwork2013** [dvajs/dva#1244]
packages/dva-example-user-dashboard中的例子在手机部分浏览器url地址没有变化。

1  . 比如：正常下第二页浏览器地址应该显示：
http://localhost:8000/users?page=2
2.  但是在微信内置浏览器或小米手机自带的浏览器里url地址始终不发生变化(永远是原来首次输入的url地址)。电脑的浏览器或ios 自带的浏览器都没有出现这些问题。
3 .页面显示的内容正常。

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

https://github.com/dvajs/dva/tree/master/packages/dva-example-user-dashboard

#### Expected behavior: (预期的正常效果)

希望 url 地址能正常根据路由变化而变化。

#### Actual behavior: (实际效果)

url 地址没有任何变化（在部分手机浏览器中）。

#### Versions of packages used: (哪个库的哪个版本出现的问题)
      
    "dva": "^2.0.0-0",
    "dva-loading": "^0.3.0",
    "history": "^4.7.2",
     "roadhog": "^1.2.0"

**Comment by szwork2013** [comment]
@sorrycc 看看是什么问题？是history还是router 的问题？

**Comment by sorrycc** [comment]
不支持 browserHistory 吧，换 hashHistory。

**Comment by szwork2013** [comment]
@sorrycc   其实不是这个原因，我测试了browserHistory，hashHistory和memoryHistory都不行，dva2.0以下版本没有这个问题，请看@zuiidea作者的 http://antd-admin.zuiidea.com，升级dva2.0后就算是在pc浏览器，
他这个测试地址里涉及到分页的 url地址都不发生变化，比如 http://antd-admin.zuiidea.com/post，不管是第几页都是这个url地址.

**Comment by szwork2013** [comment]
找到原因里，只要浏览器不支持标准的H5 API: history.pushState ,就会出现问题，万恶的微信根据升级的版本不一样，bug 反复重现。
