### ISSUE TITLE
dva g route users在switch中位置错位

### ISSUE THREAD

**Issue by guanbiao33** [dvajs/dva#1247]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
dva g route users

#### Actual behavior: (实际效果)
在switch标签外

**Comment by sorrycc** [comment]
抱歉，`dva g route` 还不支持 dva@2。

**Comment by bingqichen** [comment]
那样的话，把公用部分提取出来为一个组件，在每个页面中引入，在路由页面统一注册model，这样的实践方式更好吧？

**Comment by sorrycc** [comment]
Use umi + umi-plugin-dva .
