### ISSUE TITLE
能否提供一个不使用路由的Demo?

### ISSUE THREAD

**Issue by drmaplesoul** [dvajs/dva#1249]
dva-no-router的Readme.md并没有说明无路由版本该怎么用

**Comment by zjxpcyc** [comment]
no-router 就是没有路由，是按照基本的文件映射的方式解析的，比如如果你访问 /foo ，需要你的服务器目录下有个 foo 的目录，里面有个 index.html 。如果访问 /foo/bar.html 需要你的 foo 目录下面有 bar.html 文档。

如果你使用类似 next.js 这种框架，则需要按照框架的说明来。我印象里面是有 next.js 的例子的。

**Comment by drmaplesoul** [comment]
所以有没有dva-no-router的用法的文档或者是Demo？

**Comment by zjxpcyc** [comment]
@drmaplesoul 刚刚找了下，是有 demo 的， [https://github.com/dvajs/dva/tree/master/packages/dva-example-nextjs](https://github.com/dvajs/dva/tree/master/packages/dva-example-nextjs)
