### ISSUE TITLE
里面打包用的roadhog。怎么部署到tomcat.报错404，请作者写个教程，说明太少了

### ISSUE THREAD

**Issue by zcxzmzy** [dvajs/dva#1250]

**Comment by zjxpcyc** [comment]
roadhog 需要部署到 tomcat 吗？
业务场景是什么？

不是应该，run build 之后，直接丢到 tomcat 里面吗？

**Comment by zcxzmzy** [comment]
丢里面不起作用啊404

**Comment by zjxpcyc** [comment]
那应该是 tomcat 的配置问题吧，这个我就不怎么清楚了

**Comment by zcxzmzy** [comment]
需要怎么配置，我靠这作者也不写个教程。搜也搜不到，教程真少

**Comment by SuperNaturalGit** [comment]
build之后的静态资源直接copy到tomcat下就行了。
404是找不到资源，这跟dva没关系，检查一下url路径，应该是tomcat或者nginx配置的问题。

**Comment by sorrycc** [comment]
和 dva 无关。

**Comment by zcxzmzy** [comment]
解决了，确实和dva无关

**Comment by bestsamcn** [comment]
请问如何处理呢，本地却没这个问题
