### ISSUE TITLE
dva2.0 能否只动态注册model?

### ISSUE THREAD

**Issue by duwei54** [dvajs/dva#1251]
写小控件的时候,为这个控件定义一个model  不需要路由,能不能在加载到这个控件之后再注册model然后传入控件呢?

**Comment by sorrycc** [comment]
手动执行 app.model 就好了吧。

**Comment by duwei54** [comment]
@sorrycc 手动执行注册 会不会重复注册的问题额?不能调用dynamic动态注册?

**Comment by sorrycc** [comment]
* 重复注册的问题，可以用 app.unmodel 也可以写个函数封装下，判断已注册过的 model
* `dva/dynamic` 主要是处理组件/路由组件的动态加载，model 是附带的
