### ISSUE TITLE
请问effects内写普通函数，用select获取不到state

### ISSUE THREAD

**Issue by swim1986** [dvajs/dva#1253]
HI，最近遇到一个问题，在引入外部sdk后（阿里百川IM SDK），其定义的SDK的某个回调函数只能是普通函数，不能是generator。
这样就导致effects内要使用普通函数来put action，但是如何在普通函数内拿到state值呢？

**Comment by zjxpcyc** [comment]
不了解。
换个思路呢，把 dispatch 传给你的 sdk 函数。然后 sdk 需要执行的函数， 再 通过 payload 传到 effect 里面执行

**Comment by swim1986** [comment]
@zjxpcyc 
`yield sdk.Event.on('MSG_RECEIVED', function(data){
            put({type: 'processMsg', payload: data})
        });`
举个栗子，代码中的function是一个websocket的onmessage回调。但是在回调函数中无法put action。请问有什么好的解决办法吗？
因为我的websocket连接建立需要前提条件，所以没法放在subscription中初始化。

**Comment by swim1986** [comment]
此问题已解决，将消息推送变为pullmsg的形式。
参考https://stackoverflow.com/questions/34859932/can-i-use-redux-sagas-es6-generators-as-onmessage-listener-for-websockets-or-ev

**Comment by zjxpcyc** [comment]
@swim1986 感谢，又 get 了一个新技能
