### ISSUE TITLE
dva知识地图中“切换 history 为 browserHistory”可能存在错误

### ISSUE THREAD

**Issue by EdenLiang** [dvajs/dva#1255]
尝试按照说明的方式将history切换为browserHistory

按照“dva知识地图”的描述无效，
import { browserHistory } from 'dva/router';
const app = dva({
  history: browserHistory,
});
地址如下所示
“https://github.com/dvajs/dva-knowledgemap#切换-history-为-browserhistory”

使用如下方式才能正确的切换
import createHistory from 'history/createBrowserHistory';
const app = dva({
  history: createHistory(),
});

dva版本2.0.3

**Comment by eoeac** [comment]
我也存在这个问题，相同的代码在dva2.0.3下无法正常切换路由。
browserHistory为undefined
