### ISSUE TITLE
Cannot read property 'asyncComponentsAncestor' of undefined

### ISSUE THREAD

**Issue by MinJieLiu** [dvajs/dva#1256]
* 环境：dva@2
 * 触发条件：升级到 `React 16.0.0`

报错：
```
Warning: Failed child context type: Cannot read property 'asyncComponentsAncestor' of undefined
    in AsyncComponent (created by Route)
    in section (created by CoreLayout)
    in CoreLayout (created by Route)
    in Route
    in Switch
    in Router
    in Provider
    in Unknown
```

**Comment by MinJieLiu** [comment]
https://github.com/ctrlplusb/react-async-component/issues/39

**Comment by sorrycc** [comment]
考虑把 react-async-component 给换了，还是自己实现吧。

**Comment by sorrycc** [comment]
试着升级 example 的 react 到 16，发现这个问题应该和升级  react@16 应该无关。https://github.com/dvajs/dva/commit/953966332558cdacfc106ee7360a74727b8e5f3e

**Comment by icodytan** [comment]
@sorrycc dva-example 路由没有异步加载，所以不会出现该错误。而 dva-example-user-dashboard 路由使用了升级异步加载，升级 react 16，则会出现该错误。

**Comment by caigehui** [comment]
使用到dynamic就会出现这个问题

**Comment by caigehui** [comment]
使用到dynamic就会出现这个问题

**Comment by idowe** [comment]
使用了()=>还是会报错，不知道为什么

**Comment by rtorino** [comment]
v2.0.3 does not include this fix. I'm waiting for this to be release on NPM. Thanks.

**Comment by caigehui** [comment]
+1

**Comment by MinJieLiu** [comment]
@sorrycc `react-async-component` 已经修复了此问题
https://github.com/ctrlplusb/react-async-component/commit/ccf76722ad3d750eeb08acd475eac08c444ec0d9
