### ISSUE TITLE
dva-loading中获取loading值

### ISSUE THREAD

**Issue by Hsinky** [dvajs/dva#1257]
dva-loading v1.0.2中 state.loading.models下如何自定义属性？如官方demo中state.loading.models.users，我的代码中只有models自有的私有属性，并没有其他的属性
![1](https://user-images.githubusercontent.com/10111222/30946537-4152ea58-a437-11e7-81f6-8254389c69ec.jpg)

**Comment by sorrycc** [comment]
1. `state.loading.models` 下存的是以 model 的 namespace 为 key 的布尔值，和 model 的 namespace 有关，和 model 的 state 里存什么无关
1. 你还没有执行过 effect，所以 models 里没有值

**Comment by Hsinky** [comment]
很抱歉，我是新学者
我使用的是antd这个脚手架，我在index.js中已经添加的了如下代码，想全局加载loading，比如初始化一个页面时就显示loading状态，但未成为我想要的结果

import createLoading from 'dva-loading';
// 1. Initialize
const app = dva();

// 2. Plugins
// app.use({});
app.use(createLoading({
  effects: true
}));

**Comment by xufei** [comment]
光加这个没有用的。

1. 初始化的时候，你要发起某个 action，才能修改 loading 状态，你只要发起就行了，修改是 dva 帮你做的。
2. 你需要在界面上添加 loading 相关的组件，把它的状态设置为刚才提到的 loading 状态，然后才会显示。

**Comment by Hsinky** [comment]
如何判断一个页面是否加载完成，需求是初始化一直显示loading状态，页面加载完成后就取消显示loading状态，可以提供一个简单的实例吗？
