### ISSUE TITLE
dva路由会进入两次

### ISSUE THREAD

**Issue by freelancersinchina** [dvajs/dva#1258]
以dva-cli生成的项目为例，输入地址 / ，会进入加载两次IndexPage。把`routes/IndexPage.js`改成
```javascript
class IndexPage extends Component{
  componentWillMount(){
     console.log('in index page');
  }
  
  render(){
     return <div>IndexPage</div>
  }
}
```
控制台就会出现两次`in index page`。按道理来说，进入这个路由之后，应该加载一次`IndexPage`组件，运行一次`componentWillMount`。运行两次应该是加载了两次。

这个问题已经有过了，但是好像现在还是存在。[#97](https://github.com/dvajs/dva/issues/97)

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva@2.0.3

**Comment by sorrycc** [comment]
会不会是 index.js 加载了两次？

**Comment by freelancersinchina** [comment]
@sorrycc 真的是index.js加载了两次。我在index.js里面加了个输出，发现真的输出了两次。这是什么情况？

**Comment by sorrycc** [comment]
src/index.ejs 里删除 index.js 和 index.css 的引用。
