### ISSUE TITLE
roadhog怎么优化打包大小？源码70M，打包后2OOM?@大佬

### ISSUE THREAD

**Issue by zcxzmzy** [dvajs/dva#1260]

**Comment by nihgwu** [comment]
为什么不去roadhog提

**Comment by nihgwu** [comment]
@sorrycc 建议以后这种不按template提的issue直接关掉

**Comment by longzhaobi** [comment]
打包后体积变大很正常啊！

**Comment by sorrycc** [comment]
用 `roadhog build --analyze` 查看占比，我对这么 70M 大的源码挺感兴趣的，如无保密需要可以发我邮箱（sorrycc@gmail.com），我来看下怎么优化。

另外，后面 roadhog 的问题请到 https://github.com/sorrycc/roadhog/issues 提。

**Comment by nihgwu** [comment]
我猜是k写成了m……

**Comment by xufei** [comment]
@nihgwu 70M代码在传统行业的中后台还是挺正常的。。。不过可能有大部分都是组件库之类，20M左右的代码就很常见了。

@zcxzmzy 构建之后的总文件大不是问题，做好路由拆分就行，不要一次全加载。如果你项目的菜单路由数量在200-1000个的规模，做掉这个之后，看下加载，如果第一个页面还是很大，在10M以上，把里面用到的某些组件也搞成动态加载，正常情况下，即使大部分常用组件都加载，做一次粗的优化，第一页应该能降低到2-5M，在中后台的场景能接受了。
