### ISSUE TITLE
redux-saga's take does not accept multiple actions

### ISSUE THREAD

**Issue by wiziple** [dvajs/dva#1261]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

```
        const action = yield take('signinSuccess'); // works
        const action = yield take(['signinSuccess', 'signinFailure']); // does not work anymore
```

#### Expected behavior: (预期的正常效果)

used to be working at version 1.x

#### Versions of packages used: (哪个库的哪个版本出现的问题)

dva.js 2.0.3

**Comment by sjy** [comment]
https://github.com/dvajs/dva/pull/1661 should restore the feature.
