### ISSUE TITLE
路由怎么根据用户是否登录来进行跳转

### ISSUE THREAD

**Issue by xiaohaiH** [dvajs/dva#1264]
在路由里写 onEnter 或者 onChange 不起作用

**Comment by zhouyingkai1** [comment]
我是在  router 文件中 监听路由变化

**Comment by xiaohaiH** [comment]
可以贴下代码参考下吗?

**Comment by zhouyingkai1** [comment]
`//监听路由变化
  hashHistory.listen(location => {
    const token = kits.getCookies('token')
    
    if (new RegExp('login').test(location.pathname)) {
      if (token) {
        app._store.dispatch(routerRedux.replace('/home'))
      }
    } else {
      if (!token) {
        app._store.dispatch(routerRedux.replace('/login'))
      }
    }
  })`

**Comment by zhouyingkai1** [comment]
![image](https://user-images.githubusercontent.com/19966486/31371733-1c562944-adc5-11e7-8b34-b0fcdea10fd5.png)

**Comment by xiaohaiH** [comment]
你这个是设置 cookie 的某个值(假使为a)等于后台返给你的 token ,然后通过判断 cookie 中的 a 是否有值来控制用户的登录是吧?  恩,这个可以实现  谢谢啊

**Comment by zhouyingkai1** [comment]
不是cookie的某个值等于后台返回的 token，而是登录之后就会把token存在cookie的这个值中， 判断下cookie中有没有这个值就行了。 不存在并且不在登录页 就跳到登录页。
 不过我这样做也有一个问题。

**Comment by zhouyingkai1** [comment]
这样 如果token 失效， 但是还是存在在cookie中的话不会跳登录页，要另做处理

**Comment by xiaohaiH** [comment]
这个可以把本地的时间戳或者由服务器返回的时间戳也存放进去,判断当前时间和时间戳的时间差来处理吧

**Comment by zhouyingkai1** [comment]
那这样的话需要去更新cookie？

**Comment by xiaohaiH** [comment]
恩,每次都得判断下..

**Comment by k365266378** [comment]
@zhouyingkai1 麻烦问下 代码中kits 引用的是什么module

**Comment by zhouyingkai1** [comment]
@k365266378  kits里面只是封装了一些方法， 上面截图用到的就是一个获取cookie的方法
