### ISSUE TITLE
疑似bug:model里面update state之后，组件没有重新渲染的情况

### ISSUE THREAD

**Issue by freelancersinchina** [dvajs/dva#1265]
使用dva构建了一个简单的项目，描述了这个具体问题。[dva-report](https://github.com/freelancersinchina/dva-report)

![console](https://ws1.sinaimg.cn/large/006tNc79gy1fk9vris4zyj30ho04et91.jpg)

在`Feeds`组件里面使用了`InfiniteScroll`，这个组件在列表滑到底部的时候，通过`loadMore`方法加载更多的`item`。

控制台里面第一行是第一次渲染，刚开始的时候`feeds`是一个长度为0的列表，所以`InfiniteScroll`会通过`loadMore`加载更多`Item`。

获取更多item是通过`home`模型的`queryFeeds`来完成，这里面只是简单的在原来的feeds里面添加三个数据，然后更新状态(updateState)。能够进入`updateState`,而且也更新成功了，按道理应该会在控制台里面出现第二个`render`，但是没有出现第二个`render`，也就是说，`feeds`状态变了，但是`Feeds`组件没有重新渲染。

所以出现了这个问题：model里面update state之后，组件没有重新渲染。

但是我通过修改`Feeds`的写法，也就是采用状态都由`Feeds`自己管理的方法，发现没有出现这个问题（也就是[ReactFeeds](https://github.com/freelancersinchina/dva-report/blob/master/src/components/ReactFeeds.js)这个文件)。所以是不是dva里面出现了bug?

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva-cli: 0.8.1

**Comment by szwork2013** [comment]
model 里没有任何page的东东呀！代码修改成这个(按以下修改后本地实测正常了)：
model目录：home.js

```javascript
export default {
  namespace:'home',
  state:{
    feeds:[],
    page:0
  },
  reducers:{
    updateState(state,{payload}){

      console.log('updatestate')
      return {
        ...state,
        ...payload
      }
    }
  },
  subscriptions:{
    
  },
  effects:{
    * queryFeeds({payload},{select,call,put}){

      console.log('load page:',payload.page)
      const data = {
        user:{
          avatar:'http://p2.wmpic.me/article/2017/04/05/1491359419_ufujpTOU.jpg',
          name:'天下无我'
        },
        date:'9月10日',
        content:"欢迎大家加入这个圈子，圈子的良好交流环境离不开阿加对规则的遵守，希望大家在圈内玩的开心"
      }

      let feeds = yield select(_=>_.home.feeds)

      for(var i=0;i<10;i++){
        feeds.push(data)
      }
      console.log('after push,feeds:',feeds)

      yield put({
        type:'updateState',
        payload:{
          feeds:feeds,
          page:payload.page
        }
      })
    }
  }
}

```
组件Feeds.js
```javascript
import React from 'react'
import {TextFeed} from './Feed'
import styles from './Feeds.less'
import InfiniteScroll from 'react-infinite-scroller'
import {connect} from 'dva'



const Feeds = ({dispatch,page,feeds})=>{


  console.log('render feeds:',feeds)
  let list = []
  for(let i=0;i<feeds.length;i++){
    
    list.push(<TextFeed feed={feeds[i]} key={'feed'+i}/>)
  }

  function  loadFunc(){
    dispatch({
      type:'home/queryFeeds',
      payload:{
        page:page+1
      }
    })
  }


  return (
    <InfiniteScroll
      pageStart={0}
      loadMore={loadFunc}
      hasMore={true}
      loader={<div className="loader">Loading ...</div>}
    >
      {list}
    </InfiniteScroll>
  )
}
 

const mapStateToProps = state=>({
  feeds:state.home.feeds,
  page:state.home.page
})

export default connect(mapStateToProps)(Feeds)

```
route目录下 Indexpage.js
```javascript
import React from 'react';
import { connect } from 'dva';
import styles from './IndexPage.css';
//import Feeds from '../components/ReactFeeds' // 现在正常，如果使用下面的Feeds组件就会出现问题
 import Feeds from '../components/Feeds'  

function IndexPage() {
  return (
    <div> 
    <Feeds />
    </div>
  );
}

IndexPage.propTypes = {
};

export default connect()(IndexPage);
```

**Comment by freelancersinchina** [comment]
@szwork2013 这样改确实是可以正常运行，但是还是没有解决我的问题。我的问题是model已经更新了，但是组件没有重新渲染，这是有问题的。

你这样修改之后，应该是避免了某个还不知道问题，一般情况下应该都不会遇到这个问题，都会正常。

**Comment by xufei** [comment]
```js
updateState(state,{payload}){
  return {
    ...state,
    feeds: payload.feeds.slice()
  }
}
```

**Comment by szwork2013** [comment]
@freelancersinchina 把feeds.js 修改 console.log('render feeds:',feeds.length)更直观，每滚动一页，feeds.length会增加10，怎么会不重新渲染呢？有图为证：
![report1](https://user-images.githubusercontent.com/8146801/31323116-3ef6fe9c-acd5-11e7-8bce-8ddf74d09d75.jpeg)

**Comment by szwork2013** [comment]
[dva-report-new.zip](https://github.com/dvajs/dva/files/1367371/dva-report-new.zip)

**Comment by szwork2013** [comment]
@freelancersinchina 你自己下载我修改后的文件，重新yarn install 或 cnpm install，在本地测试一下吧。

**Comment by nihgwu** [comment]
看xufei的回复，你只是再往array里append数据，并没有修改他的引用，所以React的默认行为认为这个state没有改变

**Comment by freelancersinchina** [comment]
@xufei 当时我确实想到应该是state被判断一致，所以没更新。下次我注意，谢谢！

@szwork2013 你的代码我运行过，可以正常，但是不是page的问题，而应该是xufei提到的问题。确实是我写代码有问题。
