### ISSUE TITLE
yield take()卡住

### ISSUE THREAD

**Issue by Kroderia** [dvajs/dva#1267]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
       ` yield put({
          type: 'updateState',
          payload: {data},
        });
        yield take('updateState/@@end');`

#### Expected behavior: (预期的正常效果)
正常执行

#### Actual behavior: (实际效果)
程序卡在yield take()，没有异常抛出。updateState正常执行完成。

#### Versions of packages used: (哪个库的哪个版本出现的问题)
2.0.3

**Comment by Kroderia** [comment]
sorrycc/blog#48的描述，reducer应该是不会触发这个action。
那么问题又来了，有foo和bar两个effect，foo需要bar返回的数据，应该用何种方式获取？
       · yield put({type: 'bar'});
        yield take('bar/@@end');
        const data = yield select(_ => _.data);`
这里并不能获取到bar的结果。

**Comment by programmer-yang** [comment]
@Kroderia
hi
> effect 前后会额外触发 /@@start 和 /@@end 的 action，可利用此约定实现 put 的同步执行

你的put操作必须是一个`effect`才能出发这个类型的`/@@start/end`take
