### ISSUE TITLE
Form 相关方法的问题

### ISSUE THREAD

**Issue by WildDylan** [dvajs/dva#1270]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

我希望在普通组件中加入Form的校验功能，在参考了一些项目的 Modal.js 发现是这样的：

```js
modal.propTypes = {
  form: PropTypes.object.isRequired,
  type: PropTypes.string,
  item: PropTypes.object,
  onOk: PropTypes.func,
}

export default Form.create()(modal)
```

但是我的组件是这样的：

```js
export default connect(({ moduleInfo, loading }) => ({ moduleInfo, loading }))(ModuleDetail)
```

请问该如何 让我的 ModuleDetail 组件 也拥有 Form的一些验证的方法，例如 `getFieldDecorator, validateFields, getFieldsValue`。

谢谢

参考的项目：antd-admin

**Comment by zhouyingkai1** [comment]
![image](https://user-images.githubusercontent.com/19966486/31418647-d60b9a96-ae69-11e7-8c42-2b764196f374.png)

**Comment by zhouyingkai1** [comment]
我是这样写的
![image](https://user-images.githubusercontent.com/19966486/31418669-f75d33f8-ae69-11e7-80e5-f88a6016f4cb.png)

**Comment by WildDylan** [comment]
恩 @zhouyingkai1 后来我也想到了这种写法。  对 connect 以及 dva 的一些机制还是不太熟悉。 感谢。
