### ISSUE TITLE
ENGLISH!

### ISSUE THREAD

**Issue by timLoewel** [dvajs/dva#1275]
There is a lot of documentation and bug reports in chinese.

You lock the rest of the world out from using your cool framework.

**Comment by zjxpcyc** [comment]
Most user are chinese, include me. Our english is not good, so, sorry

**Comment by nihgwu** [comment]
@zjxpcyc you don't need to say sorry
@timLoewel we are trying to make the repo more international intended, if you have any problem with this framework, just create an issue, we will try to solve it.

IMHO dva is quite simple, no new knowledges and concepts, just a combination of redux + saga( + react-router), except some bugs, you can always find the answers in the related projects

I can tell you that most of the issues of this repo are irrelevant to dva itself

**Comment by cihadturhan** [comment]
Dva is really a good set of tools and I love how it works out of the box. It really makes the processes simpler and help you write less and cleaner code. I used it in production without any bugs but I must confess I spent *really* much time translating the issues and trying the understand because I don't know know any Chinese, even a word though.

I'm glad you have an intention to make it international.

One tip: See examples on `http://scaffold.ant.design`  and read the code in these demos. That helped me much. Javascript is universal :)

**Comment by bunnyc1986** [comment]
@timLoewel many of us have learnt years of English to be a part of world. Maybe you could learn some Chinese or use google page translate if you don't want to be blocked by language barrier.

**Comment by timLoewel** [comment]
@bunnyc1986 English is not my native tongue either. I also have learnt years of English to be part of the world. The reason English is the world's language is, because it is rather easy to learn. Chinese on the other hand is extremely difficult to learn. I could use google translate, but the more effort I have to put into understanding a framework, the less likely it is that I use it. That was my whole point. If you want your framework to be used widely outside of China and Taiwan: use English.

**Comment by smithyj** [comment]
@timLoewel 想看懂我的回答，用下谷歌翻译！首先，国际化并不是单单指英语，还有众多大众语言和小众语言，这个世界有很多人，其次，台湾是中国的！最后，我想告诉你，BuZuoSiJiuBuHuiSi

**Comment by knownothingsnow** [comment]
@timLoewel Actually, you know, there a lot of Chinese developers are very willing to help you out your issues and questions, if you were not claimed that Taiwan isn't a part of China. And, just close this issue please, most people who have read this issue have get your point. The problem we discuss here is too widely and it have nothing to do with Dva itself. Let's just discuss exciting Dva!

**Comment by wyj580231** [comment]
@timLoewel Taiwan is  a part of China

**Comment by klouskingsley** [comment]
可以着手翻译一分英文文档

**Comment by khalibloo** [comment]
Hopefully, this is enough to get the ball rolling. I'm very new to dva and I don't know a word of Chinese, so I'm hoping some of us can pitch in to refine the translation over time.
#1905

**Comment by eparizzi** [comment]
Agreed, it's seems a great framework (specifically when using it with Umi in Ant Design Pro), but I'm having a hard time understanding the concepts.
It would be great if the guide was available in english, even a pour translation is better than nothing. Then, people that know english and is familiar with the framework can improve it.

**Comment by bunnyc1986** [comment]
@khalibloo has started a PR for english guides as he mentioned early. it's available here #1905

**Comment by quan17** [comment]
弄个英文的文档，我们帮你在美国推广～
