### ISSUE TITLE
dispatch另外一个namespace下的action不起作用

### ISSUE THREAD

**Issue by welkinlan** [dvajs/dva#1278]
### Code to reproduce the issue: (请提供可复现的代码或者步骤)
* 有两个model， users 和 departments。他们各自有*query effect
* 有两个界面(route) 界面A载入所有users 界面B载入所有departments
* 问题：我想在A界面载入所有departments. 

于是有以下代码

models/users.js
```
namespace: 'users',
...
subscriptions: {
    setup({ dispatch, history }) {
      history.listen((location) => {
        if (location.pathname === '/users') {
          const payload = location.query || { current: 1, pageSize: 10 }
          dispatch({
            type: 'query',
            payload,
          })
          dispatch({
            type: 'departments/query',
            payload,
          })
        }
      })
    },
  },
},

effects: {
    * query({ payload = {} }, { call, put }) {
        //blah
      }
    },
  ...
},
```

models/departments.js
```
namespace: 'departments',
  ...
  effects: {
    * query({ payload = {} }, { call, put }) {
        //blah
      }
    },
  ...
```

#### Expected behavior: (预期的正常效果)
users/query 和 departments/query 都可以完成

#### Actual behavior: (实际效果)
直接去界面A, 只有users/query完成，departments/query没有完成
<img width="512" alt="screen shot 2017-10-15 at 11 40 55 pm" src="https://user-images.githubusercontent.com/5298183/31595570-5831487c-b202-11e7-8fd0-1f55ac037e79.png">

但是，**如果我先去界面B，然后去界面A  那么两个dispatch都可以完成了**
<img width="511" alt="screen shot 2017-10-15 at 11 55 39 pm" src="https://user-images.githubusercontent.com/5298183/31595901-67695120-b204-11e7-868e-d9b34bda6477.png">

#### Versions of packages used: (哪个库的哪个版本出现的问题)
2.0.1

多谢帮忙！

**Comment by dkvirus** [comment]
你在 user.js 时候 models/departments.js 这个model 注册了没有，你要是使用动态加载的话，只有点开 B 页面，models/departments.js 这个model  才会开始注册，才能调用里面的方法。

**Comment by welkinlan** [comment]
@dkvirus 是的 我使用的动态加载 没有在users里加载departments 多谢帮助！

解决方法
Before:
```
{
      path: '/users',
      models: () => [import('./models/users')],
      component: () => import('./routes/users/'),
    },
```

After
```


...
}, {
      path: '/users',
      models: () => [import('./models/users'), import('./models/departments')],
      component: () => import('./routes/users/'),
    }, {
```

**Comment by dkvirus** [comment]
@welkinlan  其实我挺好奇你这个需求的。在 antd-admin 项目里分了 services 层，models 层和 routes 层，其中 services 层是获取数据层，相当于 Dao，而 models 层仅仅是处理业务逻辑。你在 users 模块的 models 里要获取 departments 的数据，不是直接去 services 层请求数据，为啥要调用 departments models 里的方法。还是我思维误区，方便的话讨论一下。

**Comment by welkinlan** [comment]
@dkvirus 你说的对，我的这个use case确实是 call departments 的 service更直接。你没有思维误区。

因为users model的state只包含user list, departments model的state只包含department list。
我的需求是users 页面（route）上同时需要这俩list，但是我又不想在users model state 里再加一个department list，所以索性就直接用 departments model的department list了。

这种做法的缺点是会initiate整个departments model的state。尽管我只需要其中的department list。
