### ISSUE TITLE
antd手动上传，会出现错误

### ISSUE THREAD

**Issue by daxiong-liang** [dvajs/dva#1279]
开发使用antd的upload组件上传相关文件，antd的upload组件选择文件后会自动上传文件，但是因为
业务需求，已经将upload改成手动上传文件，但是点击上传或者确认按钮后，会在前端弹出错误，
控制台没有输出异常，不过页面会提取错误，也没有到达后台。
错误信息为：Failed to execute 'fetch' on 'Window': The provided value is not of type '(sequence<sequence<ByteString>> or record<ByteString, ByteString>)'
目测是上传文件的类型不对，目前代码是参考了antd官网的去开发，因此不知道怎样修改，请作者指点一下

#### Expected behavior: (预期的正常效果)
components代码 :
<Modal
  title="调账批次发起"
  maskClosable={false}
  visible={props.batchLaunchCtrl.show}
  onCancel={props.batchLaunchCtrl.loading ? null : props.batchLaunchClose}
  onOk={() => { props.onOk(props.batchLaunchCtrl.fileList); }}
  width={500}
>
	  <Upload
		fileList={props.batchLaunchCtrl.fileList}
		beforeUpload={(file) => {
		  props.beforeUpload(file);
		  return false;
		}}
		onRemove={props.onRemoveFile}
	  >
		<Button type="primary" disabled={props.batchLaunchCtrl.btnDisabled}>
		  <Icon type="upload" /> 调账批次发起
		  </Button>
	  </Upload>
</Modal>

mapDispatchToProps代码：

function mapDispatchToProps(dispatch) {
  return {
	batchLaunchClose: () => {
	  dispatch(batchLaunchClose());
	},
	beforeUpload: (file) => {
	  dispatch(beforeUpload(file));
	},
	onRemoveFile: (file) => {
	  dispatch(onRemoveFile(file));
	},
	onOk: (fileList) => {
	  if (fileList.length !== 0) {
		dispatch(uploadFile(fileList));
	  } else {
		message.error('请选择需要上传的文件！');
	  }
	},
  };
}

model下的effect代码:

*uploadFile(action, { call, put }) {
  const { fileList } = action;
  const file = fileList[0];
  const formData = new FormData();
  console.log('2', formData)
  formData.append('file', file);
  try {
	const result = yield call(service.uploadFile, formData);
	yield put({ ...action, type: 'uploadFileS', data: result.data });
  } catch (e) {
	yield put({ ...action, type: 'uploadFileError' });
	throw e;
  }
},

#### Actual behavior: (实际效果)
     出现Failed to execute 'fetch' on 'Window': The provided value is not of type '(sequence<sequence<ByteString>> or record<ByteString, ByteString>)'
异常

#### Versions of packages used: (哪个库的哪个版本出现的问题)
 "antd": "^2.12.2",

    "dva": "^1.2.1",

**Comment by daxiong-liang** [comment]
最新发现是chrome5同chrome6兼容性的问题，chrome5是可以手动上传成功，chrome6会出现异常

**Comment by nihgwu** [comment]
那你觉得这是dva的问题还是antd的问题还是你自己的问题呢？

**Comment by Hearen** [comment]
Hey, man. So what's the final solution? Do you find one in the end? Thank you.
