### ISSUE TITLE
Run with error with redux-undo@1.0.0-beta

### ISSUE THREAD

**Issue by afc163** [dvajs/dva#128]
redux-undo@0.6.x is OK.

**Comment by sorrycc** [comment]
先用 0.6.x 吧，redux-undo@1.0.0-beta 和 redux-actions 不兼容。

https://github.com/omnidan/redux-undo/blob/1fa339ad4f231993606764f1253ad64402837ea4/src/reducer.js#L142

这里引入了一个 type 为 `undefined` 的 action，明显不规范。

**Comment by afc163** [comment]
给它提 PR ~

**Comment by sorrycc** [comment]
https://github.com/omnidan/redux-undo/issues/125

**Comment by sorrycc** [comment]
已修复。
