### ISSUE TITLE
开发环境下渲染时闪屏问题

### ISSUE THREAD

**Issue by taoyage** [dvajs/dva#1280]
用了less后在开发环境下css文件为什么没有自动打包到index.css中去加载，而是一个一个的加载，而且是在页面渲染后才加载，导致渲染被阻塞，出现闪屏的问题，我是直接用的roadhog来启动的，是不支持less还是哪里配置不对，求教

![2017-10-18 10 49 18](https://user-images.githubusercontent.com/7186771/31699018-2df71e62-b386-11e7-9891-769edeaf1265.png)

**Comment by 104gogo** [comment]
roadhog默认这样配置的。。方便热替换。。
