### ISSUE TITLE
router should be function, but got object

### ISSUE THREAD

**Issue by andriijas** [dvajs/dva#1281]
Trying to use react-app-rewire and create-react-app (instructions followed from antd) with dva and dva-hmr

Without dva-hmr it works. Not sure exact which features dva-hmr adds.

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
https://github.com/andriijas/create-react-app-playground

#### Expected behavior: (预期的正常效果)
When running npm start it should work

#### Actual behavior: (实际效果)
Router gets function but might be wrapped in object perhaps thats why it breaks?

#### Versions of packages used: (哪个库的哪个版本出现的问题)
Check package.json in repo

**Comment by gaohailang** [comment]
+1

**Comment by gaohailang** [comment]
I found the solution.
In index.js, change `app.router(require('./router'))` into something like that:

```js
import router from './router'
app.router(router)
```

**Comment by andriijas** [comment]
That didnt work before but seems to work now.  Thanks

**Comment by sorrycc** [comment]
Thanks for report, I will fix this problem in babel-plugin-dva-hmr.

**Comment by andriijas** [comment]
Thanks. I got it working with require("./router'").default but hmr did not work, page reload when I save footer.

**Comment by sorrycc** [comment]
It's fixed, try babel-plugin-dva-hmr@0.4.0 .

**Comment by buf1024** [comment]
在 production build里，这个问题好像没有解决，在[user-dashboard](https://github.com/dvajs/dva/tree/master/packages/dva-example-user-dashboard)这个例子生成后，方服务器会报这个错误。

**Comment by bobbychan** [comment]
在 create-react-app创建的项目中使用，依然会报错

**Comment by joriewong** [comment]
build后依然报错 #1572 
```
"babel-plugin-dva-hmr": "^0.4.0"
```

**Comment by lin-xibin** [comment]
> I found the solution. In index.js, change `app.router(require('./router'))` into something like that:
> 
> ```js
> import router from './router'
> app.router(router)
> ```

2022时光旅客~~~使用的时候同样遇到这个问题，归根到底是官方文档demo中CommonJS的模块语法与ES6的模块语法不正确混用，`./router.js`文件使用ES6中的export default命令导出，该处输出的是一个函数，而主文件中使用来自CommonJS的require命令获取到的是对象。纠正方法可以是像你一样完全使用ES6模块语法，也可以使用require(xx).default     [StackOverflow: Javascript require vs require .default](https://stackoverflow.com/questions/43247696/javascript-require-vs-require-default)
