### ISSUE TITLE
dynamic 不能导入model 

### ISSUE THREAD

**Issue by pssgo** [dvajs/dva#1283]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
```javascript
function RouterConfig({ history, app }) {
  return (
    <Router history={history}>
      <Switch>
        <Route
          path="/login"
          exact
          component={dynamic({
            app,
            models: () => import('./models/auth'),
            component: () => import('./routes/auth'),
          })}
        />
        <Route path="/" extact component={App} />
      </Switch>
    </Router>
  )
}

export default RouterConfig

```

#### Expected behavior: (预期的正常效果)

预期正常导入model  

#### Actual behavior: (实际效果)

实际效果 异步组件可以渲染 但是model 无法导入

#### Versions of packages used: (哪个库的哪个版本出现的问题)

dva 2.0.4

**Comment by pssgo** [comment]
models 写法错误

**Comment by linlinNB** [comment]
请问，你是怎么解决的？

**Comment by linlinNB** [comment]
@pssgo 我也发生了无法导入的问题

**Comment by linlinNB** [comment]
![image](https://user-images.githubusercontent.com/22005231/35034067-e41ab99c-fba7-11e7-9edf-a3583bd93890.png)

**Comment by pssgo** [comment]
@linlinNB   参考这个 
![image](https://user-images.githubusercontent.com/16378134/35036750-484cb02a-fbb0-11e7-842f-2118503ada2f.png)
我的错误是一个typo
