### ISSUE TITLE
Uncaught TypeError: Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by lany9527** [dvajs/dva#1285]
#### Versions of packages used: 

"antd": "^2.13.6",
    "babel-plugin-import": "^1.6.2",
    "babel-runtime": "^6.9.2",
    "dva": "^2.0.4",
    "react": "^15.4.0",
    "react-dom": "^15.4.0",

请问有哪位大神知道是怎么回事？

**Comment by HeWei-imagineer** [comment]
相同问题，请问有解决方案吗？

**Comment by LiuXiao617111** [comment]
同问
