### ISSUE TITLE
effect 中使用delay不延时

### ISSUE THREAD

**Issue by lhg0302** [dvajs/dva#1286]
我用的是dva:1.2.1版本,使用如下代码,却不能延时执行下面的put,不知道为什么,版本问题么?
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
effects: {
    * query({payload}, {call, put, select}) {
      try {
        let {data} = yield call(query, parse(payload));
        if (data) {
          debugger;
          yield call(delay, 3000);
          debugger;
          yield put({
            type: 'querySuccess',
            payload: {
              data: data.result,
              currentPage: data.currentPage,
              totalCount: data.totalCounts,
              cache: false
            },
          });
      }

**Comment by codering** [comment]
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

**Comment by lhg0302** [comment]
不好意思,之前就是写的那个,后来改错了,就是这样写的不能够延时,两个debugger一下子就过去了

**Comment by zjxpcyc** [comment]
最近好像好几个 issue 都在讨论 delay 的问题，请问下是什么场景呢？ 我这边怎么从来没遇到过需要 delay。

**Comment by lhg0302** [comment]
没人碰到么?

**Comment by codering** [comment]
你把两个debugger改成打印当前时间，看看时间差

**Comment by jindada** [comment]
```js
yield delay(2000)
```

**Comment by yoyo837** [comment]
那delay 咋取消呢
