### ISSUE TITLE
组件复用，model数据覆盖问题，求教

### ISSUE THREAD

**Issue by lcgyh** [dvajs/dva#1287]
我想要实现一个组件复用，但是在不同地方组件的数据是不同的，我都dispace到model势必导致数据覆盖，但是我的两个页面是可以同时存在的，求教改如何处理这种情况

**Comment by zjxpcyc** [comment]
可以理解为 基类-子类的关系吗？

你可以写个 modelBasic, 然后 extend 几个子 model

**Comment by longzhaobi** [comment]
https://github.com/dvajs/dva-model-extend 
这个应该就是你需要的把，我用的就是他，系统很多地方都是表格列表，所以就用这个把公共的全部提出来，有特殊的对应的model里写就可以了，也会覆盖公共里的方法
