### ISSUE TITLE
可以用create-react-app 创建的项目中使用dva吗？

### ISSUE THREAD

**Issue by zzr7** [dvajs/dva#1288]
如题，在开发过程中遇到一些坑，我想知道有人正在使用吗？
还是尽量使用dva-cli 手脚架去构建。
主要觉得 create-react-app 感觉挺不错的 - - 
如果有，用的create-react-app 版本是多少？

**Comment by sorrycc** [comment]
可以，dva 就是一个 npm 包，cra 创建项目后引入 dva 即可。

**Comment by WhatAKitty** [comment]
https://github.com/WhatAKitty/react-script-antd-pro
