### ISSUE TITLE
请教在model的effects中添加成功弹窗调用antd的modal组件问题怎么才好？

### ISSUE THREAD

**Issue by cigarx** [dvajs/dva#1292]
import { Modal, Button } from 'antd'

*add ({ payload }, { call, put }) {
      const data = yield call(add, parse(payload))
      if (data) {
        yield put({ type: 'hideAddModal' })
        yield put({
          type: 'normal',
          payload: location.query,
        })
        Modal.info({
          title: '添加成功',
          content: (
            <div>
              <p>some messages...some messages...</p>
              <p>some messages...some messages...</p>
            </div>
          ),
          onOk() {},
        })
      }
    },
这是主要的代码，这个是model里面的，想问下在model里面调用antd的组件是不是不好呢？
是不是应该通过改变state来触发呢？如果state来触发，那么成功后就显示一个提示信息，是不是也太绕弯了呢？

**Comment by Haibin-Yang** [comment]
You can handle such task with promise returned by `dispatch` in version 2.x

**Comment by zjxpcyc** [comment]
我是这样处理的，如果是全局的或者统一的，比如错误提示，就是放在 basic model 中的

如果是组件自己使用的, 就在组件中使用, 通过组件 state 控制，同时加上key

**Comment by fallingyou** [comment]
我是这样做的，在dispatch的时候传一个回调函数，当model的state改变完成后，执行回调函数
```
this.props.dispatch({
        type: 'novel/add',
        payload: fieldsValue,
        callback: () => {
          const { novel } = this.props;
          if (novel.success) {
            message.success('添加成功');
            this.handleModalVisible();
            this.props.dispatch({
              type: 'novel/fetch',
            });
          }
        },
      });
```
