### ISSUE TITLE
dynamic注册model，[app.model] namespace should be unique

### ISSUE THREAD

**Issue by 550326307** [dvajs/dva#1295]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

function RouterConfig({ history,app }) {
  const Layout = dynamic({
    app,
    models: () => [import('./models/layout')],
    component: () => import('./routes/Layout/index'),
  });
  const CCPOrg = dynamic({
    app,
    models: () => [import('./models/ccporg')],
    component: () => import('./routes/CCP/OrgManage/index'),
  });
  const CCPMember = dynamic({
    app,
    models: () => [import('./models/member') ],
    component: () => import('./routes/CCP/Member/index'),
  });
  return (
    <Router history={history}>
      <Route path="/" render={(props) => {
        return (
          <Layout {...props}>
            <Route exact path="/ccporg" component={CCPOrg}/>
            <Route exact path="/ccpmember" component={CCPMember}/>
          </Layout>
        );
      }}/>
    </Router>
  );
}
#### Actual behavior: (实际效果)
Uncaught (in promise) Error: [app.model] namespace should be unique
#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva@2.0.4

**Comment by huzhengke** [comment]
how do u resolve import error.

**Comment by fattypanda** [comment]
这个问题，就和字面上的意思一样，app.model 的 namespace 必须唯一。
但是，这里可能有两种情况。
1、你的所有组件都没有 namespace ，所以它们的 namespace 都一样。
2、你已经加载过这个 model ,再加载一次，它们的 namespace 当然是一样的。

我也出现了这个问题，我是属于第 2 种情况。

问题重现：
```
// src/index.js
app.model(require("./models/users"));

// src/router.js
const UsersPage = dynamic({
    app,
    models: () => [
      import('./models/users'),
    ],
    component: () => import('./routes/Users'),
});
```
问题原因：加载了两次 models/users ;

解决办法：
删除 ```src/index.js``` 中的 ```app.model(require("./models/users"))```;
