### ISSUE TITLE
打包上线后再更新时按需加载模块的缓存问题

### ISSUE THREAD

**Issue by sandywk** [dvajs/dva#1296]
用的按需加载，打包后会生成 1.1.js、2.2.js ....

上线之后，如果需要更新上线，覆盖服务器文件，index.html里的 js 文件后缀可以加上 ?版本号 来让用户浏览器，但是生成的 1.1.js、 2.2.js ... 按需加载的文件怎么办？

**Comment by HankChenCH** [comment]
你这个应该是roadhog问题，.roadhogrc文件配置hash:true，就会在打包好的文件后自动加hash。记得加个index.ejs的模板在index.js的同级目录。不然每次build完都要手动在html文件加hash名。

**Comment by sandywk** [comment]
谢谢 @HankChenCH 
roadhog 更新版本后加上 "hash" : true 就OK了，index.ejs也配置好，非常方便！

**Comment by GaLiGayGay-X** [comment]
加入"hash" : true打包后的文件的确加入了hash值，但是每次打包后的hash值一样，需要怎么解决？please....

**Comment by sandywk** [comment]
@GaLiGayGay-X 打包的hash文件一样说明对应模块代码没有更新，是正常的，你修改了对应模块代码自然会重新生成新hash的文件。

**Comment by TigerHee** [comment]
做成这样之后，router的嵌套路由失效怎么解决呢
