### ISSUE TITLE
run build 怎样让 css 嵌入 js 文件

### ISSUE THREAD

**Issue by sandywk** [dvajs/dva#1297]
打包会生成一个css文件，怎样配置可以不生成css文件，和开发时一样嵌入在页面？

**Comment by sandywk** [comment]
@xuyuan3 
没有
我是另外在 js 里加了段代码动态载入 css 文件

**Comment by xuyuan3** [comment]
请问怎么动态嵌入啊？ 谢谢
这是我的问题
https://github.com/dvajs/dva/issues/1307

**Comment by xuyuan3** [comment]
我解决了，谢谢

**Comment by joriewong** [comment]
#1572
