### ISSUE TITLE
Hot module replacement for dva-react-router-3 does not work .

### ISSUE THREAD

**Issue by ciqulover** [dvajs/dva#1298]
#### Code to reproduce the issue: 

Hot module replacement for `dva-react-router-3` does not work .
After upgrading from `dva@1.2.1` to `dva-react-router-3@1.0.2` , HMR disappears in console, all the change of watched file will cause browser to refresh.

Dependencies:

```
"dependencies": {
    "antd": "^2.13.6",
    "babel-runtime": "^6.9.2",
    "dva-loading": "^1.0.2",
    "dva-react-router-3": "^1.0.2",
    "emoji-exists": "^1.0.1",
    "id-validator": "^1.3.0",
    "query-string": "5.0.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0"
  },
  "devDependencies": {
    "babel-plugin-dva-hmr": "^0.3.2",
    "babel-plugin-import": "^1.1.0",
    "babel-plugin-module-resolver": "^2.7.1",
    "babel-plugin-transform-runtime": "^6.9.0",
    "redbox-react": "^1.3.2",
    "redux-devtools": "^3.3.2",
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-devtools-log-monitor": "^1.2.0",
    "roadhog": "^1.2.2"
  }
```

.roadhogrc.js

```
"env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", {"libraryName": "antd", "style": "css"}],
        ["module-resolver", {
          "alias": {
            "dva": "dva-react-router-3"
          }
        }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", {"libraryName": "antd", "style": "css"}],
        ["module-resolver", {
          "alias": {
            "dva": "dva-react-router-3"
          }
        }]
      ]
    }
  }
```
#### Expected behavior: 

`dva-react-router-3` works with HMR.

#### Versions of packages used: 

`dva-react-router-3@1.0.2`
`babel-plugin-dva-hmr@0.3.2`

**Comment by sorrycc** [comment]
Please provide a repo, so we can reproduce it.

**Comment by ciqulover** [comment]
It's too complicated to show in detail, thus it will cost you much time. I'll try to refactor the project to dva2 to avoid this problem.

**Comment by luofei2011** [comment]
就官方提供的DEMO：`dva-example-react-router-3`，启动后更改js文件也会导致浏览器refresh而不是热替换。

#### 现象

推送了`ed94a1d4d5db9b29fcbd.hot-update.json`更新文件，但页面还是彻底刷新了。

#### roadhog版本

`1.3.1`

**Comment by luofei2011** [comment]
React router v3 is not supported, if you want Hot Loader support, please use v4.
