### ISSUE TITLE
dva 2.0 style flicker

### ISSUE THREAD

**Issue by nikogu** [dvajs/dva#1300]
![aaaa](https://user-images.githubusercontent.com/1179603/31978667-173e87a0-b908-11e7-94f9-1310f23f73e5.gif)

Style loading after script, it will make some component break witch need computing styles.

like this issue: https://github.com/ant-design/ant-design/issues/7564#issuecomment-330420901

**Comment by contineu0818** [comment]
I have a similar problem，css load slower than js.  I prepared to user dva@1.2.1

**Comment by sorrycc** [comment]
搞定了吗？

**Comment by nikogu** [comment]
@sorrycc 业务上我们这边不太影响了...但是这个问题还是有的 ＝。-

**Comment by contineu0818** [comment]
这个问题我解决了，是roadhog的问题，我把roadhog的版本变成了0.5.2，然后加了public文件夹，里面放index.html

发自我的 iPhone
