### ISSUE TITLE
这个报错是啥意思呢？Failed to start the server, since you have enabled dllPlugin, but have not run `roadhog buildDll` before `roadhog server`.

### ISSUE THREAD

**Issue by jusheng** [dvajs/dva#1301]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
Failed to start the server, since you have enabled dllPlugin, but have not run `roadhog buildDll` before `roadhog server`.

**Comment by sorrycc** [comment]
先执行 `./node_modules/.bin/roadhog buildDll`，或者在 .roadhogrc 里禁用 dll 。
