### ISSUE TITLE
GettingStarts demo not work at Dva2.x?

### ISSUE THREAD

**Issue by suiyi8760** [dvajs/dva#1302]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
Have tried the same code with gettingstarts.md

#### Expected behavior: (预期的正常效果)
Add dispatched +1  and async minus dispatched to -1 after 1 second

#### Actual behavior: (实际效果)
In redux devTools only see add@start,add@end and minus,but it dosen't add 1 when click the plus button

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva@2.0.4

**Comment by lifecube** [comment]
same issue here, please guide. 
dva@2.0.4
