### ISSUE TITLE
effects和reducer中如何获取到dispatch

### ISSUE THREAD

**Issue by socrazy123654** [dvajs/dva#1303]
除了通过payload传递，能否直接在effects和reducer中拿到dispatch

**Comment by longzhaobi** [comment]
yield put()跟dispatch应该是一个意思吧！

**Comment by longzhaobi** [comment]
reducer里是用来改变state的，拿dispatch干嘛？

**Comment by socrazy123654** [comment]
想在effects里面传递一个callback，而这个callback需要修改state，如果直接写成put，callback调用时不会生效，如果用dispatch则是ok的

**Comment by longzhaobi** [comment]
state是在reducer里修改把，不管是put   reduer里函数的或者dispatch里的函数都能触发state修改啊！

**Comment by socrazy123654** [comment]
本以为是都能触发，但是实验了一下发现，在effects里面调用一个函数f，传递一个回调函数，f里面调用该回调函数。如果回调函数用put则不会触发修改state，如果用dispatch则会

**Comment by xufei** [comment]
你这个回调函数里怎么调用 put 呢，要 yield 啊，但是在回调里面你 yield 不起来吧
