### ISSUE TITLE
dva-loading opts effects not work

### ISSUE THREAD

**Issue by monkindey** [dvajs/dva#1306]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

```js
app.use(createLoading({
    effects: false
}));
```

#### Expected behavior: (预期的正常效果)

Disable effects level loading state.

如果我理解得没错的话, 看了代码, 好像没有处理 `opts.effects`, 而且看了测试用例也没有测试effects为false的。

说实在话, 我暂时还没有完全理解这个`opts.effects`的作用和使用场景, 纯粹好奇了解一下而已, 但是看了文档看不太懂, 看了代码也没有对`opts.effects`的处理。

#### Actual behavior: (实际效果)

Also enable.

#### Versions of packages used: (哪个库的哪个版本出现的问题)

dva-loading v0.3.0

**Comment by sorrycc** [comment]
dva-loading@1 默认开启了 effects，因为没有开启会在某些场景下 loading 状态不对，文档忘记更新了。
