### ISSUE TITLE
请问dva每次build后怎么把样式加进去？每次build都是没样式的。。

### ISSUE THREAD

**Issue by xuyuan3** [dvajs/dva#1307]
每次index.html 都没有index.css .都需要手动添加。
求解啊？怎么打包后自动生成引用
<link rel="stylesheet" href="/index.css" />

![image](https://user-images.githubusercontent.com/6204761/32091260-027a4a86-bab9-11e7-9814-557f3661ef12.png)

![image](https://user-images.githubusercontent.com/6204761/32091291-201d5ba0-bab9-11e7-854e-840b2b049b5d.png)

**Comment by xuyuan3** [comment]
自己笨了，本身index里面就没加。。

**Comment by joriewong** [comment]
#1572
