### ISSUE TITLE
dynamic import error

### ISSUE THREAD

**Issue by huzhengke** [dvajs/dva#1309]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
const Users = dynamic({
      app,
      models: () => [
      import('./models/users'),
    ],
    component: () => import('./routes/Users'),
});

#### Actual behavior: (实际效果)
Syntax error: Unexpected token (9:6) import

**ps:为什么import('./models/users')，这种写法我一直无法编译通过**

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva@2.0.4

**Comment by sorrycc** [comment]
编译工具的问题，babel 得加这个插件，babel-plugin-syntax-dynamic-import 。

**Comment by huzhengke** [comment]
我用的create-react-app脚手架，尽管加了babel-plugin-syntax-dynamic-import，还是无法报import编译错误。
