### ISSUE TITLE
model未加載

### ISSUE THREAD

**Issue by huzhengke** [dvajs/dva#1310]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
{
      path: '/',
      name: 'IndexPage',
      getComponent(nextState, cb) {
        require.ensure([], (require) => {
          registerModel(app, require('./models/article'));
          cb(null, require('./routes/IndexPage'));
        }, "aa");
      },
    },
    {
      path: '/people/:id',
      name: 'PeoplePage',
      getComponent(nextState, cb) {
        require.ensure([], (require) => {
          registerModel(app, require('./models/user'));
          cb(null, require('./routes/PeoplePage'))
        }, 'aa');
      },
    },

#### Expected behavior: (预期的正常效果)
预期从IndexPage页面跳转到peoplePage页面，peoplePage页面会加载好model：user
#### Actual behavior: (实际效果)
function mapStateToProps(state) {
  return {
    user: state.user,
    loading: state.loading.models.user,
  };
}
该state里面根本没有user对象
![image](https://user-images.githubusercontent.com/7312417/32129482-55116416-bb4d-11e7-995a-6afdb4754bd0.png)

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva@1.x

**Comment by sorrycc** [comment]
同样是编译工具的问题吧，定位下有没有执行到 `registerModel(app, require('./models/user'));` 。
