### ISSUE TITLE
请问为什么使用npm run build打包后的index.html

### ISSUE THREAD

**Issue by liyingpu0630** [dvajs/dva#1312]
使用npm run build打包后，index.html生成了两个css，这是为什么？怎么解决呢？
![image](https://user-images.githubusercontent.com/22017729/32205952-420a157e-be2d-11e7-916e-57d9d212a300.png)

**Comment by linyongping** [comment]
去掉模板文件 index.ejs 里的``` <link  rel="stylessheet" href="/index.css"  /> ``` roadhog打包会自动注入css和js
