### ISSUE TITLE
Is it possible to hook Dva store to Reactotron?

### ISSUE THREAD

**Issue by TsuryKnox** [dvajs/dva#1314]
[Reactotron](https://github.com/infinitered/reactotron)
Anyone managed to achieve it?
I tried following the [Reactotron-redux-saga plugin](https://github.com/infinitered/reactotron/blob/master/docs/plugin-redux-saga.md) but it didn't work.

**Comment by sorrycc** [comment]
Reactotron need to [create store use his method](https://github.com/infinitered/reactotron/blob/master/docs/plugin-redux.md#configuring), so we can't use it with dva now.

**Comment by ShMcK** [comment]
@sorrycc, you could try an approach similar to https://github.com/rematch/rematch for integrating reactotron. See notes: https://rematch.gitbooks.io/rematch/docs/recipes/devtools.html.

Though I feel this is primarily an issue with Reactotron, rather than Dva.
