### ISSUE TITLE
一个页面，怎样设置定时刷新，比如做一个监控界面，需要实时的刷新数据？

### ISSUE THREAD

**Issue by koupeng** [dvajs/dva#1316]

**Comment by sorrycc** [comment]
可以在 effect 里写个无限循环，比如：

```js
while (true) {
  yield fetch(data);
  yield delay(300);
}
```

然后，你可以需要适时地关闭或者开启他，可以在 state 里加个开关。比如：

```js
while (true) {
  const enableFetch = yield select(state => state.namespace.enableFetch);
  if (enableFetch) {
    yield fetch(data);
  }
  yield delay(300);
}
```

**Comment by koupeng** [comment]
谢谢，解决了我的问题。再请教一下。之前是通过 <Table columns={time_col}
             loading={loading.effects['stormsReport/query']}。来控制table的刷新loading效果，可是，这样改了后，这个query方法一直while刷新，，一直loading,,有什么好方法解决这个么？

**Comment by koupeng** [comment]
你好，又有了新的问题。请帮忙看下 @sorrycc 

[issues-1334](https://github.com/dvajs/dva/issues/1334)
