### ISSUE TITLE
dva/dynamic generate named chunks ?

### ISSUE THREAD

**Issue by hirohe** [dvajs/dva#1317]
使用dva/dynamic进行按需加载，编译后生成的异步加载js文件都是以数字开头的，是否可以像require.ensure的chunkName参数一样设置每个异步加载js的文件名？
`0.async.js -> chunkName.async.js`

**Comment by hirohe** [comment]
看了一下import()的[文档](https://webpack.js.org/guides/code-splitting/#dynamic-imports)，可以这样设置chunkName
```js
import(/* webpackChunkName: "chunkName" */'path/to/module/')
```
output: `chunkName.async.js`

**Comment by szwork2013** [comment]
同问！
