### ISSUE TITLE
less的使用问题

### ISSUE THREAD

**Issue by lcgyh** [dvajs/dva#1318]
我把css文件改为less文件，然后写
```
@model-width:"520px"
.login_con{
	width: @model-width;
}

```
报错Variable @model-width is undefined
求教，谢谢

**Comment by nihgwu** [comment]
和 dva 的关系是都是 web 技术？

**Comment by sorrycc** [comment]
https://www.google.com/search?ei=MaH9Wa2UOsHS0gTbkJCIBQ&q=less+variable&oq=less+variable&gs_l=psy-ab.3..0l10.4035.5658.0.5923.10.10.0.0.0.0.136.691.5j2.7.0....0...1.1.64.psy-ab..3.7.691...0i67k1j0i131k1j0i10k1.0.e_Kg5MTevMc
