### ISSUE TITLE
引入css好像报错了 

### ISSUE THREAD

**Issue by denggy** [dvajs/dva#1324]
按照官网的例子一步步上手
但是在需要引入组件的地方报错了

![1509949989 1](https://user-images.githubusercontent.com/3114067/32428168-7079add0-c2ff-11e7-9b4d-760cedc1dda4.jpg)

**Comment by chouqing15** [comment]
目测应该是0.8.2版本问题 ， 你可以将dva 版本降级到0.8.1 去，可以正常使用
