### ISSUE TITLE
在dva 2.0  中，如果设置了initialState， 同时用dynamic异步加载时似乎是不可以，这是一个bug吗

### ISSUE THREAD

**Issue by git-xyz** [dvajs/dva#1328]
在dva 2.0  中，如果设置了initialState， 同时用dynamic异步加载时似乎是不可以，这是一个bug吗

**Comment by sorrycc** [comment]
dynamic 是一个 util 方法，不会影响 dva 的运行的，两者之间没啥关联。

**Comment by wenJonSnow** [comment]
我刚才 试了 确实 dynamic会影响  initialState 的功能  。dynamic 加载时 initialState 设置无效。 "dva": "^2.3.1",
