### ISSUE TITLE
VSCode中打开dva创建的工程出现高CPU占用

### ISSUE THREAD

**Issue by Rhuaer** [dvajs/dva#1333]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
1. 在vscode中装上[csharp插件](https://github.com/OmniSharp/omnisharp-vscode)，并禁用其他所有插件
2. 使用dva创建一个新工程：`dva new highCpu`
3. 使用vscode打开新建的工程，然后就出现高cpu占用，高cpu进程是：`\Microsoft VS Code\resources\app\node_modules\vscode-ripgrep\bin\rg.exe `，cpu消耗达90%
4. 禁用c#插件，cpu使用正常
5. 非dva创建的项目目前没有发现该问题
6. 装了[HTML CSS Support](https://github.com/ecmel/vscode-html-css)也会出现该问题

#### Expected behavior: (预期的正常效果)
就算装了csharp插件，也不要出现高cpu占用

#### Actual behavior: (实际效果)
如上描述

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"dva": "^2.0.4",

#### 机主信息
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.13
vscode-markdownlint|Dav|0.11.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
jquerysnippets|don|0.0.1
xml|Dot|1.9.2
gitlens|eam|6.0.0
git-project-manager|fel|1.4.0
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.4.0
python|ms-|0.8.0
azure-account|ms-|0.2.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.17.0
code-settings-sync|Sha|2.8.5
stylelint|shi|0.30.0
code-spell-checker|str|1.4.12
jsx|Twe|0.0.1

(1 theme extensions excluded)

**Comment by sorrycc** [comment]
抱歉，帮不上你。感觉和 dva 无关，另外我不用 vscode 。

**Comment by spezz07** [comment]
@Rhuaer 
https://github.com/Microsoft/vscode/issues/35659
可以看下这个issues 好像是cnpm问题，底部有解决方法

**Comment by zhuanglong** [comment]
我也遇到这个问题，解决了吗

**Comment by joenil** [comment]
+1
