### ISSUE TITLE
页面跳转后，后台仍然刷新数据的问题

### ISSUE THREAD

**Issue by koupeng** [dvajs/dva#1334]
#### Code to reproduce the issue:
1、为了实现实时监控，需要做界面定时刷新。我按照sorrycc的建议，使用了如下方法，满足了需求！。
while (true) {
yield fetch(data);
yield delay(300);
}
然后，你可以需要适时地关闭或者开启他，可以在 state 里加个开关。比如：

while (true) {
const enableFetch = yield select(state => state.namespace.enableFetch);
if (enableFetch) {
yield fetch(data);
}
yield delay(300);
}
2、从定时刷新界面，点击链接到新的界面。
此时，上一个界面仍然在实时刷新！！！
3、为此，我的解决方法是如下：
     switchIsRefresh(false)，是定时刷新界面上的开关。
 return  <a href="javascript:;" onClick={
            function(){
              //跳转界面前设置刷新为false
              switchIsRefresh(false)
              //跳转界面时，待参数
              dispatch(routerRedux.push({
                pathname: '/storms',
              }));

            }
          }>{text}</a>;
4、有没有更好的解决方法，尤其是使用<Link>的时候，或者当跳转链接较多时，我希望有一个统一的处理。

#### Versions of packages used: (哪个库的哪个版本出现的问题)
版本如下：
 "dva": "^2.0.1",

**Comment by sorrycc** [comment]
subscription 里监听 url 变化，不是期望的页面时关闭刷新，否则开启。

**Comment by koupeng** [comment]
@sorrycc 那这样的话，岂不是每个界面的subscription都要监听？比如，我只有一个界面需要定时刷新，那我其他100个界面都要写上监听这个url，且关闭上一个界面的刷新？

**Comment by sorrycc** [comment]
不是单页应用吗？在一个 model 的 subscription 里监听就好了。

**Comment by koupeng** [comment]
不要意思，是我理解错了。每个model里的subscription可以监听到所有的url变化，只需要在刷新的界面去关闭或打开刷新就可以了。谢谢。

**Comment by koupeng** [comment]
@sorrycc 你好。仍然还有些问题需要请教~~~。用了这种方法后，发现在页面跳转后，经常出现loading.global=true的情况，导致页面一直有loading效果。这个有什么方法解决么？
app中的逻辑如下：
```
 if (lastHref !== href) {
    NProgress.start()
    if (!loading.global) {
      NProgress.done()
      lastHref = href
    }
  }

```

**Comment by yoyo837** [comment]
NProgress.start() 和  NProgress.done()你逻辑中 处理好边界，必然是因为有done没有收尾的情况
