### ISSUE TITLE
关于constants for action types and mapDispatchToProps

### ISSUE THREAD

**Issue by PengyuanZhao** [dvajs/dva#1335]
刚开始用dva，看了文档和一些demo代码，遇到两个问题：

1. 是否需要为action types定义constants？比如`dispatch({ type: 'user/signin' })`，直接输入`'user/signin'`是dva里的最佳实践吗?
2. 是否需要定义action creator和使用mapDispatchToProps shorthand？比如`dispatch({ type: 'user/signin' })` 可能被多处使用，定义`const sigin = () => ({ type: 'user/signin' })`使用`const mapDispatchToProps = { signin }`可以简单地复用`signin`。

如果要定义action type constants和action creator, 建议定义在哪里？model里吗？

谢谢

**Comment by iShawnWang** [comment]
emmmmmm 麻烦 cc 大大回复一下好吗.. 不理解为什么被关闭... 
还有 #1165 
🤕

**Comment by lirenhao** [comment]
为什么不推荐action creator functions?
