### ISSUE TITLE
项目打包后如何部署?怎么使用线上接口替换mock模拟的接口？

### ISSUE THREAD

**Issue by wufanglan** [dvajs/dva#1337]

**Comment by k365266378** [comment]
可以在nginx 里做转发！

**Comment by yvanwangl** [comment]
@wufanglan 我理解线上接口和mock接口应该是一样的吧，只是请求的ip地址不同，可以根据开发环境（process.env.NODE_ENV==='development'）和部署环境（process.env.NODE_ENV==='production'）对接口的ip地址进行控制。
