### ISSUE TITLE
在effects中使用async/await做异步不起作用？要必须使用*/yield吗？

### ISSUE THREAD

**Issue by huang6349** [dvajs/dva#134]
effects: {

    /**
     * 数据查询
     * 
     * @param {any} { payload }
     * @param {any} { select, call, put }
     */
    query: async function ({ payload }, { select, call, put }) {
      await put({ type: 'show_loading' });
      payload.page = payload.page || 1;
      payload.limit = payload.limit || 10;
      let data = await call(query, '/home/course', payload);
      if (data) {
        await put({
          type: 'query_success',
          payload: {
            list: data.data,
            total: data.count,
            current: data.currentPage,
          },
        });
      }
    }
  },

**Comment by huang6349** [comment]
effects: {

    /**
     * 数据查询
     * 
     * @param {any} { payload }
     * @param {any} { select, call, put }
     */
    query: function* ({ payload }, { select, call, put }) {
      yield put({ type: 'show_loading' });
      payload.page = payload.page || 1;
      payload.limit = payload.limit || 10;
      let data = yield call(query, '/home/course', payload);
      if (data) {
        yield put({
          type: 'query_success',
          payload: {
            list: data.data,
            total: data.count,
            current: data.currentPage,
          },
        });
      }
    }
  },

**Comment by sorrycc** [comment]
是的，effect 只支持 generator 的写法。`async` 和 `await` 可以在 effect 之外用，然后在 effect 里用 yield call 去调。

**Comment by huang6349** [comment]
了解了，谢谢大神

**Comment by llqgit** [comment]
请问，effect 有机会在将来支持 async 吗？ @sorrycc

**Comment by sorrycc** [comment]
async 没有 generator 可控，这也是 redux-saga 选择用 generator 的原因。

**Comment by llqgit** [comment]
哦

**Comment by miaojiuchen** [comment]
@sorrycc 请问generator异步操作在dva中要如何取消(cancel)？
比如call了一个验证操作，等待一会后想取消的情况

**Comment by miaojiuchen** [comment]
@sorrycc 请问要如何cancel一个effect呢？

**Comment by sorrycc** [comment]
@miaojiuchen 场景是啥? 为啥要 cancel effect ?

**Comment by Iamlars** [comment]
async 没有 generator 可控，比如不能 cancel，这也是 redux-saga 选择用 generator 的原因。

场景是啥? 为啥要 cancel effect ?

**Comment by xgenvn** [comment]
@sorrycc  我在遇到这样的场景：
- effect 1：请求成功，调用effect 2
- effect 2：while(true) => delay 然后 dispatch reducers

这样在一个页面没问题，但是如果访问其他页面，再返回上页面，就会重复effect 2.
怎么能在effect 1 先cancel effect然后再触发effect 2？
是不是得用路径subcriptions 调用@@CANCEL_EFFECTS?

谢谢。

**Comment by realeve** [comment]
@sorrycc 既然你这里也提出了什么场景需要使用cancel，事实上大多数情况下async/await足矣。目前的用法里，用 generator/yield 再去调用 async/await，这样太蛋疼了，作者可以考虑同时支持两种模式，让用户自己去选择，比如增加一个配置项，开启后调用async/await模式，或者自适应判断。

**Comment by fishedee** [comment]
可以试试[redva](https://github.com/fishedee/redva)，一样的dva框架，默认开启async/await和immer
