### ISSUE TITLE
代码改动后，浏览器会自动定位到当前项目的 tab

### ISSUE THREAD

**Issue by hangyangws** [dvajs/dva#1341]
我知道 dva 有 HMR 功能，代码修改了会自动加载新的资源

不过有个「值得吐槽」的地方：

1. 我现在浏览器中浏览一个页面，
2. 然后在编辑器编辑代码，按 cmd  + s
3. 浏览器自动加载，并且跳到当前页面 tab
4. 也就感觉很奇怪啊。HMR 不是只应该实现「热加载」么，怎么还实现自动切换 tab 了？

**Comment by OPY-bbt** [comment]
并没有发现这个问题啊

**Comment by sorrycc** [comment]
你估计改了配置吧，dev server 重启会跳转到当前 tab。
