### ISSUE TITLE
dva1的错误处理

### ISSUE THREAD

**Issue by zhangfengrui** [dvajs/dva#1346]
现在的项目使用的是dva1版本，在使用过程中出现以下的问题：1、model层报错之后，页面就无法继续点击（服务端报的错）2、如何将服务端返回的错误显示出来让用户知道（错误在model里怎么抓、、、）。
希望能给个合理的解决方案，找了好多资料了、、、、

**Comment by zjxpcyc** [comment]
model 层是什么层，不太懂。如果有错误， 不是可以 try catch 吗？ 另外，如果是远程访问的错误，我印象里面 request.js 里面是有处理，你可以修改下。

还有1.x 版本里面，是有 onEffect 的接口的, 也可以在这里处理。

不知道，这是不是能帮你解决问题。

**Comment by jindada** [comment]
配置全局的错误处理捕获你的异常就可以了
