### ISSUE TITLE
dva2.0中如何在ajax中调用props.或者调用react-router 进行跳转

### ISSUE THREAD

**Issue by whevether** [dvajs/dva#1347]
#### Actual behavior: (实际效果)  `if([401,400,403].indexOf(response.status) > -1)
        {
            notification.error({
                message: '没有权限',
                description: '请联系管理员!!!!',
                onClose: ()=>{
                    return Cookies.remove('token');
                }
            });
        }`

#### Expected behavior: (预期的正常效果)  `if([401,400,403].indexOf(response.status) > -1)
        {
            notification.error({
                message: '没有权限',
                description: '请联系管理员!!!!',
                onClose: ()=>{
                    this.props.dispatch({
                      type: 'user/logout'    //这个方法内实现了清空token,使用react 路由进行跳转回登入页面
                    })
                }
            });
        }`

**Comment by longzhaobi** [comment]
你通过window.location.href跳转到登录那个页面，在登录页面的生命周期里componentDidMount里清空登录信息不行？？？？？
