### ISSUE TITLE
dva-core中使用dva-loading给出警告

### ISSUE THREAD

**Issue by EagleWolf** [dvajs/dva#1348]
warning " > dva-loading@1.0.4" has unmet peer dependency "dva@^2.0.4".

![image](https://user-images.githubusercontent.com/4488399/33009515-1736195c-ce12-11e7-9854-9f005a1b4ed7.png)

为什么这个没有抽离出来那？

**Comment by sorrycc** [comment]
没有用 dva，而是直接用 dva-core ？

**Comment by EagleWolf** [comment]
是的，因为是vue版，所以单独引得dva-core
