### ISSUE TITLE
Cannot ask questions on StackOverFlow

### ISSUE THREAD

**Issue by Sashkan** [dvajs/dva#1349]
Very basic issue, default issue system suggests we ask questions on stackoverflow using the tag 'dvajs', unfortunately, this cannot be done as this tag doesn't exist, and cannot be created unless we have at least 15k points on SO.

If anyone has 15k points +, can he create the tag ? I've got a lot of questions about DVA, but cannot ask them the way you want.

**Comment by sorrycc** [comment]
https://stackoverflow.com/questions/tagged/dvajs
