### ISSUE TITLE
[app.start] container null not found（更改为browserHistory后）

### ISSUE THREAD

**Issue by WaSantu** [dvajs/dva#1351]
您好，我在更改browserHistory 后，发送了[app.start] container null not found的报错
初始化配置只更改了
`const app = dva({
    history: createHistory(),
    });`
router.js文件
`function RouterConfig({ history }) {
  return(
  <Router history={history}>
     <Switch>
      <Route exact path="/" component={lsPage}/>
      <Route exact path="/index" component={layout} />
      </Switch>
  </Router>
  )
} 
export default RouterConfig;`

访问index时出现报错

**Comment by sorrycc** [comment]
参考这个 commit，https://github.com/dvajs/dva/commit/8480aac309b19364b13d1c88b435d310eec0d86a

**Comment by WaSantu** [comment]
已解决 谢谢！

**Comment by dkvirus** [comment]
@WaSantu  哥们，咋解决的？我按照 sorrycc 的做法还是不行。

**Comment by upcgaolei** [comment]
@WaSantu 和楼上同问

**Comment by WaSantu** [comment]
@dkvirus @upcgaolei 时间有点久我有点回忆不起来当时是咋搞的了。但是是按照他给的方法解决的，两位可以仔细看看，多试试，依赖里加入history了吗

**Comment by ybning** [comment]
@dkvirus @upcgaolei @WaSantu 我也遇到了，各位怎么解决的？
