### ISSUE TITLE
多页面打包，提取公共部分，生成common.js【hash】，hash值每次都换改变，不修改任何东西。

### ISSUE THREAD

**Issue by zhouyi318** [dvajs/dva#1352]
"dva": "^2.1.0",
"roadhog": "^1.3.1",
"webpack": "^3.8.1",

请问如何操作，才能保证提取的公共common.js的hash值不变

**Comment by nihgwu** [comment]
跟 dva 无关，去看webpack的配置说明

**Comment by sorrycc** [comment]
https://github.com/pigcan/blog/issues/9
可以看下这篇文章的介绍。
