### ISSUE TITLE
有人尝试过在electron中使用吗？有没有什么问题

### ISSUE THREAD

**Issue by hengkx** [dvajs/dva#1353]

**Comment by sorrycc** [comment]
一样是浏览器环境，没有问题的，支付宝小程序 IDE 在用 dva 。

**Comment by t04041143** [comment]
@sorrycc 请问，为啥pack后运行程序后，加载不上图片呢？页面引用的路径是正确的

**Comment by yuzhouisme** [comment]
测试过一次，正常。具体步骤可以百度，也可以参考如下代码

在根目录下添加main.js入口文件
`
const electron=require('electron');
const app=electron.app;

const path=require('path');
const url=require('url');

const BrowserWindow=electron.BrowserWindow;

// 初始化并准备创建主窗口
app.on('ready', function () {
    // 创建一个宽800px 高500px的窗口
    mainWindow = new BrowserWindow({
        width: 800,
        height: 500,
    });
    // 载入应用的inde.html
    mainWindow.loadURL(url.format({
        pathname:path.join(__dirname,'/dist/index.html'),  
        protocol:'file:',
        slashes:true
    }));
    // 窗口关闭时触发
    mainWindow.on('closed', function(){
        // 想要取消窗口对象的引用， 如果你的应用支持多窗口，你需要将所有的窗口对象存储到一个数组中，然后在这里删除想对应的元素
        mainWindow = null
    });
});
`
在package.json下新增一种启动方式
`
    "start:electron": "electron ."
`
别忘了还需要npm install electron，然后运行就行啦
