### ISSUE TITLE
全局websocket放在dva的何处

### ISSUE THREAD

**Issue by linsmalldragon** [dvajs/dva#1354]
全局websocket connect放在dva的何处?
所有model共用一个websocket连接,并在subscriptions里加了
history.listen(({pathname})
但都要判断全局的websocket是否连上?因为页面刷新时有可能还在连接中

**Comment by qwlong** [comment]
同问

**Comment by qwlong** [comment]
是不是直接放在router中

**Comment by sorrycc** [comment]
subscriptions 里判断有什么问题呢？

**Comment by webee** [comment]
我觉得可以单独创建连接实例，在subscription中设置连接的相关回调方法。
在入口Component的componentDidMount中dispatch action开始连接，componentWillUnmount中断开连接。这样比在subscription中通过history监听pathname更合理一些，也不需要判断状态，因为就触发一次。比如可能你的路由是两个route: 1. /auth, 2. /(/, /a, /b等)，/auth是登录页面，你需要在进入第二个route(/)之后开始连接, 离开就需要断开。这种情况判断pathname实际是重复了router的逻辑。

**Comment by linsmalldragon** [comment]
subscriptions可以增加一个加载执行的次序,让全局的websocket优先执行完了后,各个子subscriptions才开始执行,这样做的话可以防止子subscriptions在websocket还没连接成功就去订阅
