### ISSUE TITLE
initialState无效

### ISSUE THREAD

**Issue by henrydf** [dvajs/dva#1356]
例如初始化
`const app = dva({
  history: browserHistory(),
  initialState: {
    login: {
      status: undefined,
    },
  },
});`

会有如下警告：
**Unexpected key "login" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "routing", "@@dva", "global". Unexpected keys will be ignored.**

**Comment by sorrycc** [comment]
这个警告的意思是没有对用的 model 处理 login 这个 state，你需要创建一个 namespace 为 `login` 的 model 并注册他。

**Comment by zhuanglong** [comment]
@henrydf 你解决了这个问题吗

**Comment by jzoe** [comment]
@sorrycc 在初始化的时候就注册了 global 这个 model，但是在修改完代码热更新的时候，还是有上面这个问题，请教一下是怎么回事呢？

具体问题我在 https://github.com/ant-design/ant-design-pro/pull/1290 这边描述了

**Comment by jzoe** [comment]
@sorrycc 测试后发现是正好修改 global 这个 model 的时候就会有问题，修改其它 model 触发的热更新就不会有问题。
