### ISSUE TITLE
Unable to resolve module `dva/mobile`

### ISSUE THREAD

**Issue by Herb-Sun** [dvajs/dva#1361]
<img width="324" alt="2017-11-27 18 02 18" src="https://user-images.githubusercontent.com/10445626/33261264-3ead519a-d39d-11e7-895e-40af8d4b4483.png">
<img width="255" alt="2017-11-27 18 01 44" src="https://user-images.githubusercontent.com/10445626/33261269-413cd69c-d39d-11e7-974a-d7c753a561b5.png">
![simulator screen shot - iphone x - 2017-11-27 at 18 01 59](https://user-images.githubusercontent.com/10445626/33261271-4350cf60-d39d-11e7-84ae-585460ba2f76.png)

**Comment by Herb-Sun** [comment]
![simulator screen shot - iphone x - 2017-11-27 at 18 01 59](https://user-images.githubusercontent.com/10445626/33261301-5723f576-d39d-11e7-88f8-7987eda59a91.png)

**Comment by nihgwu** [comment]
There is no `dva/mobile` any more, use `dva-no-router` or `dva-core` instead
