### ISSUE TITLE
Understanding dvajs put

### ISSUE THREAD

**Issue by RatchapongT** [dvajs/dva#1363]
I couldn't post on Stackoverflow as tag is missing.
I have just recently found out that this can be done. However, I don't really understand what happened in the background. I try reading `dva-core` sourecode but still can not really figure out

This is taken from `dva` example.

      reducers: {
        save(state, { payload: { data: list, total, page } }) {
          return { ...state, list, total, page };
        },
      },
      effects: {
        *fetch({ payload: { page = 1 } }, { call, put }) {
          const { data, headers } = yield call(usersService.fetch, { page });
          yield put({
            type: 'save',
            payload: {
              data,
              total: parseInt(headers['x-total-count'], 10),
              page: parseInt(page, 10),
            },
          });
        },
        *remove({ payload: id }, { call, put }) {
          yield call(usersService.remove, id);
          yield put({ type: 'reload' });
        },
        *reload(action, { put, select }) {
          const page = yield select(state => state.users.page);
          yield put({ type: 'fetch', payload: { page } });
        },
      },

There are two ways `put` is being used here

 - `yield put({ type: 'reload' });` is used to run another effect
 - `yield put({ type: 'save',..});` is used to run reducer.

I was reading `redux-saga` document and can not really find documentation regarding using `put` to run another effect. Is this something specific for `dvajs`?

**Comment by cihadturhan** [comment]
`put` dispatches the action which you defined as `type`
It's more like 
```javascript
dispatch({type: 'reload'})
``` 
doing in the background. However, execution won't stop when you call `yield put(...)` unlike `yield call(...)` so be aware of that.
If you dispatch an action and there are both effect (e.g. `*reload`) and reducer (e.g. `reload`) with the same name, both of them will be executed.

**Comment by RatchapongT** [comment]
@cihadturhan thanks! I am starting to understand redux saga more now. However are you sure about the last statement? 

`If you dispatch an action and there are both effect (e.g. *reload) and reducer (e.g. reload) with the same name, both of them will be executed. `

I tried this and only effect seemed to be executed. I haven't yet figure out why having the same name prevent reducer from running.

**Comment by cihadturhan** [comment]
@RatchapongT you are right. I forgot that how it works.

Here what it says:
> Reducer and effect with the same name will not fallthrough (both executed), but only execute effect

Source: https://github.com/dvajs/dva/releases/tag/dva%402.0.0

**Comment by RatchapongT** [comment]
@cihadturhan wow thank you so much for finding the actual statement. Do you possibly know where in the source code of dva that is controlling this behavior?

**Comment by cihadturhan** [comment]
Nope :) Actually it doesn’t matter as far as your job is done :)

Cihad Turhan

R.T <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (2 Ara 2017 04:28):


@cihadturhan<https://github.com/cihadturhan> wow thank you so much for finding the actual statement. Do you possibly know where in the source code of dva that is controlling this behavior?
