### ISSUE TITLE
windows开发环境上使用dva/dynamic页面渲染报错

### ISSUE THREAD

**Issue by wesleyJia** [dvajs/dva#1365]
在windows的开发环境上使用dva/dynamic接口
 component: () => import('./components/Home'),
这样的写法会导致页面无法渲染
Warning: defaultLoadingComponent(...): No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.

Uncaught TypeError: **inst.render is not a function(…)**

在mac ox系统上此问题就不存在
在windows上需要把component在RouterConfig之外import，就可以渲染

**Comment by bobbychan** [comment]
我是在router.js里加了一行这个就好了，你可以试下
`dynamic.setDefaultLoadingComponent(() => {
  return <div>Loading</div>
})`
