### ISSUE TITLE
增加对react hot loader3的支持

### ISSUE THREAD

**Issue by linsmalldragon** [dvajs/dva#1370]
仅仅用hmr保存不了状态,增加点如何配react-hot-loader3的文档,否则尼码要直接看dva源码后结合react-hot-loader3的文档才可以配出来,比较苦.
我这按以下配是可以用了,
但还是出现蛮多warning
App.js:

`
...
app.router(indexRouter);
export default app.start();

`

import React from 'react';
import ReactDOM from 'react-dom';
import {AppContainer} from 'react-hot-loader'
import registerServiceWorker from './registerServiceWorker';
import App from './App';

function render() {
    ReactDOM.render(
        <AppContainer>
            <App/>
        </AppContainer>,
        document.getElementById('root')
    )
}
render();
if (module.hot) {
    module.hot.accept('./App', () => {
        render();
    })
}

registerServiceWorker();`

`

**Comment by licaomeng** [comment]
请问应该怎样配置，我配过之后只有hmr的效果，并没有react-hot-loader的效果。

**Comment by licaomeng** [comment]
请问应该怎样配置，我配过之后只有hmr的效果，并没有react-hot-loader的效果。
