### ISSUE TITLE
DVA-Loading performance issue on Android

### ISSUE THREAD

**Issue by kala888** [dvajs/dva#1372]
We use DVA in ReactNative. We find that there are some performance issue after we add DVA-loading to our project on Android(The performance in IOS is OK, more faster than IOS). 
    "dva-core": "^1.1.0",
    "dva-loading": "^1.0.4",
    "lodash": "^4.17.4",
    "native-base": "^2.3.3",
    "rc-form": "^2.1.3",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.1",
    "react-navigation": "^1.0.0-beta.21",
    "react-redux": "^5.0.6",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.8.3"

![image](https://user-images.githubusercontent.com/1215976/33472239-56ccf9f8-d6ac-11e7-9597-d0c69bf2b969.png)

**Comment by poklau123** [comment]
may be you can refer to my pull request #1362 . The master branch of dva-loading will cause store changed when you dispatch any of effects, so I tried to add configration items: `only` and `except`, these will allow you to add dva-loading to effects only where you need it, and keep silent to other effects.

example usage[`src/index.js`]:
```javascript
app.use(createLoading({
    only: [
        'namespace/actionType'
    ]
}));
```
or
```javascript
app.use(createLoading({
    except: [
        'namespace/actionType'
    ]
}));
```
I hope this will help you.

**Comment by prionkor** [comment]
Please add these feature to the readme file.
