### ISSUE TITLE
redux-saga bundled twice with dva

### ISSUE THREAD

**Issue by andriijas** [dvajs/dva#1374]
using `BundleAnalyzerPlugin` with webpack i discovered that a typical dva project includes both es and lib dir for redux-saga check here:   https://i.imgur.com/HN25T20.png

I tried with ant-design-pro as well with same result

expect only es dir to be used when i bundle locally.

**Comment by andriijas** [comment]
example repo

https://github.com/andriijas/create-react-app-playground

`npm run build` and check `build/report.html`

**Comment by szwork2013** [comment]
I think you should delete "redux-saga" in config-overrides.js.

**Comment by szwork2013** [comment]
from the item of  "vendors "  .

**Comment by andriijas** [comment]
Same results.

Maybe its issue with redux-saga but I can see that there are references to redux-saga/lib in dva.

**Comment by andriijas** [comment]
https://github.com/redux-saga/redux-saga/issues/894

**Comment by andriijas** [comment]
you can also check dist/saga.js  in dva, its 96k

**Comment by andriijas** [comment]
Issue seem to be here:

https://github.com/dvajs/dva/blob/master/packages/dva-core/src/getSaga.js    

`import * as sagaEffects from 'redux-saga/effects';`   imports from `redux-saga/es`
```
import {
  takeEveryHelper as takeEvery,
  takeLatestHelper as takeLatest,
  throttleHelper as throttle,
} from 'redux-saga/lib/internal/sagaHelpers';
```  imports from `redux-saga/lib`

There is one more lib reference in https://github.com/dvajs/dva/blob/master/packages/dva-core/src/index.js

Also suggestion to upgrade redux-saga
