### ISSUE TITLE
怎样初始化多个model？

### ISSUE THREAD

**Issue by zhuanglong** [dvajs/dva#1380]
app.model(require('./models/global'));

**Comment by huzzbuzz** [comment]
@zhuanglong ``` require('./models').forEach(m => app.model(m));```

**Comment by zhuanglong** [comment]
@huzzbuzz 我在入口处提前挂载了user model，当登录成功后动态加载路由，又再次挂载user model，出现错误，怎么防止重复挂载

**Comment by zhuanglong** [comment]
ant-design-pro nav.js

// wrapper of dynamic
const dynamicWrapper = (app, models, component) => {
  // 排除重复的model
  const items = models.filter(m => {
    const hasModel = app._models.some(item => item.namespace === m);
    if (!hasModel) {
      return m;
    }
  });
  return dynamic({
    app,
    models: () => items.map(m => import(`../models/${m}.js`)),
    component,
  });
}

暂且这样做，不知道还有没有别的方法。

**Comment by sorrycc** [comment]
没啥好办法，自己做 cache 判断。
