### ISSUE TITLE
Unexpected keys xxx found in previous state received by the reducer.

### ISSUE THREAD

**Issue by yangbin1994** [dvajs/dva#1386]
> Unexpected keys "app", "heatmap/projectSearch" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "routing", "@@dva", "loading". Unexpected keys will be ignored

似乎是redux的升级导致的，需要作为bug修复一下吗

**Comment by Hansuku** [comment]
老哥解决了吗 我发现两年了 redux3.7.2还是这样。。。。
