### ISSUE TITLE
dva g route users 问题

### ISSUE THREAD

**Issue by myhui** [dvajs/dva#1389]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
dva g route users

#### Actual behavior: (实际效果)
![image](https://user-images.githubusercontent.com/7444978/33823288-896bbbec-de95-11e7-8874-07185fb95067.png)

#### Versions of packages used: (哪个库的哪个版本出现的问题)

dva-cli: 0.8.2

**Comment by sorrycc** [comment]
先不要用 `g route` 的功能，目前不兼容 dva@2 的。
