### ISSUE TITLE
使用dva/fetch请求时没有把cookie带上，导致每次请求session不一样

### ISSUE THREAD

**Issue by yunfeit** [dvajs/dva#139]
使用dva/fetch请求时没有把cookie带上，导致每次请求session不一样

浏览器默认请求会带上cookie
`GET http://localhost/jinxin/php/api/user/registerSeller HTTP/1.1
Host: localhost
Connection: keep-alive
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6
Cookie: PHPSESSID=2i3s2tp2p2oddsc8u1643epus3
`
使用fetc请求时没有把cookie带上导致服务器每次的session不一样，没法判断登录状态
`GET http://localhost/jinxin/php/api/user/registerSeller HTTP/1.1
Host: localhost
Connection: keep-alive
Origin: http://localhost:8989
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Accept: */*
Referer: http://localhost:8989/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6
`

**Comment by sorrycc** [comment]
封以下，参考：

- https://github.com/dvajs/dva-cli/blob/master/boilerplates/app/src/utils/request.js
- https://www.npmjs.com/package/whatwg-fetch#sending-cookies

**Comment by ityao** [comment]
`/**
 * Requests a URL, returning a promise.
 *
 * @param  {string} url       The URL we want to request
 * @param  {object} [options] The options we want to pass to "fetch"
 * @return {object}           An object containing either "data" or "err"
 */
export default function request(url, options) {
  options = {...options, credentials: 'include', headers: {'Content-Type': 'application/json; charset=utf-8'}, } //包含cookie信息
  return fetch(url, options)
    .then(checkStatus)
    .then(parseJSON)
    .then((data) => ({ data }))
    .catch((err) => ({ err }));
}
`

**Comment by hbrls** [comment]
@yunfeit 简单场景欢迎尝试 https://github.com/hbrls/vanilla.js

**Comment by bjwulin** [comment]
设置fetch的options就好，我的如下：
`const options= { method: "GET",mode: 'cors',credentials: 'include'};//same-origin`
我因为用cors，所以credentials设置为include，如果不跨域，那么same-origin就行了。

**Comment by summerinsect** [comment]
用了react-cookie
```javascript
let date = new Date();
date.setTime(date.getTime() + (7 * 24 * 60 * 60 * 1000));
cookie.save('loginName',state.username,{ expires: date ,path: "/"});
```
也用了js-cookie
```javascript
Cookies.set('loginName', state.username, { expires: 7, path: "/" });
```

把下面两项也加到了option里。
mode: 'cors',
credentials: 'include'

请求带了cookie
Cookie:SESSION=4a6cb1ea-2a37-4cc7-8b34-36e6f60ee22c
但是自己设的cookie还是没有带
