### ISSUE TITLE
Creating dll bundle... Failed to compile.

### ISSUE THREAD

**Issue by zhouyi318** [dvajs/dva#1393]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
Creating dll bundle...
Failed to compile.

Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @bg-dark: #EFEFF4;
| @progress-color: #08BF06;
|

#### Expected behavior: (预期的正常效果)
实现预编译

#### Versions of packages used: (哪个库的哪个版本出现的问题)
请问这个问题，如何解决？

**Comment by sorrycc** [comment]
别用 dll 了，下个版本的 roadhog 会下掉这个功能。
