### ISSUE TITLE
hashHistory 下的 _k 查询参数?

### ISSUE THREAD

**Issue by zhuanglong** [dvajs/dva#1394]
this.props.history.push({
      pathname: '/list/customer/edit',
      state: { name: 'zhangsan' },
});

使用的是ant-design-pro，带state跳转到编辑页，url中没有_k参数， 
在编辑页通过this.props.location.state可以获取到，这样是可以的，
但是刷新编辑页location.state就变为undefined。

hashHistory会出现以上问题，browserHistory正常。

**Comment by sorrycc** [comment]
state 是带过来的临时变量，刷新后自然没有了，用 search 传到 url 里吧。

**Comment by zhuanglong** [comment]
@sorrycc 我传的参数比较多，用search的话url会很长，按照react-router的文档，通过state传值过去，链接会带上 _k 查询参数，但是在ant-design-pro并没有。

**Comment by sorrycc** [comment]
参数比较多不方便传的话，就传关键字段比如 id，然后切换目标页面后在那边获取数据。另外 hashHistory 才会有 `_k`。

**Comment by zhuanglong** [comment]
@sorrycc 我用的是 hashHistory，url中有 `#`。

**Comment by sorrycc** [comment]
hashHistory 肯定带 _k 的。
