### ISSUE TITLE
静态资源比如声音文件的打包

### ISSUE THREAD

**Issue by lcgyh** [dvajs/dva#1395]
```
<video src={require('../assets/error.mp3')} controls="controls">
			您的浏览器不支持 video 标签。
</video>
```
引用的图片放在assets目录下可以打包到dist文件中，但是声音文件，excel等资源文件不能进行打包到里面，比如上面代码中引用的声音文件，像这类文件该如何处理

**Comment by sorrycc** [comment]
用的 roadhog？按[这个配置](https://github.com/sorrycc/roadhog/blob/master/src/config/common.js#L69-L82)来看，这些文件之外的都会 copy 到 dist 才对。
