### ISSUE TITLE
请问model effect 里边payload解构报错是什么问题？

### ISSUE THREAD

**Issue by ZHENGGEGE** [dvajs/dva#1398]
utils.js?711c:240 uncaught at _callee3 
 at _callee6 
 at takeEvery(province/fetchOneProvince, sagaWithCatch) 
 at sagaWithCatch 
 Error: TypeError: Cannot read property 'name' of undefined
这是浏览器报错信息

dva版本2.0.3

**Comment by Liqiankun** [comment]
@ZHENGGEGE 关掉了 是怎么解决的？
