### ISSUE TITLE
How to create a staging environment

### ISSUE THREAD

**Issue by xiaoxinmiao** [dvajs/dva#1400]
### Version
2.0.3

### Environment
"react": "^15.4.0",

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
**english**:
  I made the following configuration, but can not get env by const env = process.env.API_ENV,because process.env.NODE_ENV can not be manually assigned
**china**:
  我做了如下配置，但是通过  const env = process.env.API_ENV，无法得到env，发现process.env.NODE_ENV 是无法手动赋值的

export default {
  entry: 'src/index.js',
  define: {
    'process.env': {},
    'process.env.NODE_ENV': process.env.NODE_ENV,
    'process.env.API_ENV': process.env.NODE_ENV,
  },
  env: {
    development: {
      extraBabelPlugins: [
        'dva-hmr',
        'transform-runtime',
        [
          'import',
          {
            libraryName: 'antd',
            style: 'css'
          }
        ]
      ]
    },
    staging: {
      extraBabelPlugins: [
        'dva-hmr',
        'transform-runtime',
        [
          'import',
          {
            libraryName: 'antd',
            style: 'css'
          }
        ]
      ]
    },
    production: {
      extraBabelPlugins: [
        'transform-runtime',
        [
          'import',
          {
            libraryName: 'antd',
            style: 'css'
          }
        ]
      ]
    }
  }
}

### What is expected?
**english**:
   Look forward to: staging environment can also be used, when the implementation of **npm run build** statement, not just the product environment, through the configuration can be staging environment
**chinese**:
    期待：staging环境也能使用，即执行npm run build 不只是product，可以通过配置得到staging环境,现在是：只有dev 和 product能用

### What is actually happening?
**english**:
  Staging environment can not be used
**chinese**:
  staging环境不能使用

---
**english**:
  Specific description: In fact, staging and product are the same execution statement, are npm run build, but we visit background api configuration is different, such as: staging background address: https: //qa.com, product is: https: // prd .com
**chinese**:
  具体描述：其实staging和product都一样，都是npm run build，但是我们访问后台api的配置不一样，比如：staging的后台地址：https://qa.com，product的是：https://prd.com

**Comment by sorrycc** [comment]
我的想法是配置一个和 NODE_ENV 无关的环境变量，然后在代码里根据 API_ENV 切换 api 配置。

```js
define: {
  'process.env.API_ENV': 'staging',  // staging | production
},
```

**Comment by xiaoxinmiao** [comment]
如果这样配置的话，也只能得到一个，product 和 staging是两个发布，其实不想做两套代码
config.js
export const backendAddr = (() => {
  const env = process.env.API_ENV
  switch (env) {
    case 'staging': return {
      tokenUrl:'https://aaa.cn/1',
    };
    case 'production': return {

     tokenUrl:'https://aaa.cn/1',
    };
    default: return {
      tokenUrl:'https://aaa.cn/1',
    };
  }
})();


service.js

import { backendAddr } from '../utils/config';
export function getToken() {
    return request(backendAddr.tokenUrl
        ,
        {
            method: 'GET',
            // mode: 'no-cors',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
        }
    );
}

**Comment by jmolivas** [comment]
Which one will be the file, you will add this code @sorrycc? 
```
define: {
  'process.env.API_ENV': 'staging',  // staging | production
},
```

To be able to read `process.env.API_ENV` within a JS on the app as an example from the `src/constants.js` file.
