### ISSUE TITLE
如何手动控制路由跳转

### ISSUE THREAD

**Issue by Madridspark** [dvajs/dva#1401]
在1.x时，我使用的方法是

```
import { browserHistory} from "react-router"

browserHistory.push("path")
```

在2.x中如何实现？

我尝试过

```
import { routerRedux } from "dva/router"

routerRedux.push("path")
```

但是失败

也尝试过

```
history.pushState(null, null, "path")
```

也失败

求助，谢谢！

**Comment by Madridspark** [comment]
我尝试的第一种方法根本改变不了浏览器的href，而第二种虽然改变了url但组件没有刷新渲染

**Comment by sorrycc** [comment]
dva 1 和 2 的跳转方式一样的，参考 https://github.com/dvajs/dva-knowledgemap#%E5%9F%BA%E4%BA%8E-action-%E8%BF%9B%E8%A1%8C%E9%A1%B5%E9%9D%A2%E8%B7%B3%E8%BD%AC

**Comment by Madridspark** [comment]
谢谢

**Comment by weihomechen** [comment]
已经解决了么，我现在也遇到这种问题，[issues](https://github.com/dvajs/dva/issues/1474)
