### ISSUE TITLE
dispatch type 为空的事件时没有警告信息

### ISSUE THREAD

**Issue by xc1427** [dvajs/dva#1403]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
```
this.props.dispatch({
      type: '',
    });
```
如果不指定type， dispatch 出的 action 会被任意 reducer/effects所匹配，那么造成不可预期的错误信息。
#### Expected behavior: (预期的正常效果)
控制台打印警告类似「WARNING：you are dispatching an action with ANY type.」

#### Actual behavior: (实际效果)
没有警告信息。

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva-core 1.1.0

**Comment by yvanwangl** [comment]
@xc1427 经过测试，该问题确实存在，已经提交了 pr #1424
