### ISSUE TITLE
请问前辈们用dva搭建的项目run build打包后如何在打包的js文件中用代码读取外部的 json文件（其实就是项目的外部配置文件）？

### ISSUE THREAD

**Issue by sunhailongisme** [dvajs/dva#1406]

**Comment by yvanwangl** [comment]
@sunhailongisme 没看懂，为什么打包后要去读取配置文件呢？

**Comment by sunhailongisme** [comment]
是这样的，这套系统要部署到多个服务器上，需求就是前端要去读外部json文件，以达到在那个服务器部署就改下json的配置文件就行了。现在就是用webpack打包后dist文件夹就一个index.html，index.js，index.css这三个文件。如果我在打包后的 dist 文件夹内放一个config.json 或是config.js文件，我的react代码中如何能读取到这个文件。之前的jquery  $.getJSON（）方法可以解决，但是换到react  dva 中该如何做？有点没思路

**Comment by sunhailongisme** [comment]
@yvanwangl 是这样的，这套系统要部署到多个服务器上，需求就是前端要去读外部json文件，以达到在那个服务器部署就改下json的配置文件就行了。现在就是用webpack打包后dist文件夹就一个index.html，index.js，index.css这三个文件。如果我在打包后的 dist 文件夹内放一个config.json 或是config.js文件，我的react代码中如何能读取到这个文件。之前的jquery $.getJSON（）方法可以解决，但是换到react dva 中该如何做？有点没思路

**Comment by yvanwangl** [comment]
`jquery $.getJSON（）` 是在什么时机运行的？

**Comment by sunhailongisme** [comment]
@yvanwangl 是在服务器下运行的啊，不是可以读取到你前端静态资源的相对路径的json文件吗？就是类似于前端做城市三级选择，城市字典换成其他的json文件。

**Comment by sunhailongisme** [comment]
@yvanwangl 不能让webpack把这个json文件打包进去，要在打包后的index.js内的代码中读取这个外部json文件

**Comment by yvanwangl** [comment]
@sunhailongisme 我觉得可以有两个思路：
1、你去请求服务器接口，让服务端去读取配置文件
2、使用 fetch 代替 `jquery $.getJSON（）` , dva 中对 `fetch` 进行了一次封装，就在 'util/request.js'

```
request('/path/to/config.json').then(json => console.log(json));
```
不知是否能解决你的问题

**Comment by sunhailongisme** [comment]
@yvanwangl  还是要借鉴jquery 的 getjson 方法的思路 换成fetch就行了。多谢了。顺便问下，dva这个项目目前是您在维护吗？

**Comment by yvanwangl** [comment]
@sunhailongisme 不是啦，我也是 `dva` 的用户，让我们一起感谢 @sorrycc 带给我们这么好的 `dva`
