### ISSUE TITLE
dva2.x版本按需加载，分块打包如何写

### ISSUE THREAD

**Issue by ZGahou** [dvajs/dva#1407]

**Comment by dive2Pro** [comment]
请看示例代码  https://github.com/dvajs/dva/blob/master/packages/dva-example-user-dashboard/src/router.js

**Comment by chenshuai2144** [comment]
能不能关闭这个功能?

**Comment by dive2Pro** [comment]
正常使用就不会触发功能了

**Comment by iceberg211** [comment]
可以参考ant design pro
