### ISSUE TITLE
yield以及onError的问题

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#141]
1、我发现用if和else无法条件执行yield，比如：
```
if(data){
   yield put({type: 'logined' , payload:data.data });
}else{
   yield put({type: 'toLogin'});
}
```
断点调试的时候发现两个yield都执行了，我现在是合并到一条语句：
`yield put({type: data ? 'logined' : 'toLogin', payload: data ? data.data : undefined});`
总觉得写的难受，怎么写好一点？

2、fetch的时候，很多情况下，我不需要处理异常，直接交给onError，但是有一部分请求，我是需要处理异常，因此我代码改成以下：
```
function request(url, options,throwError=true) {
  return _fetch(fetch(url, options))
    .then(checkStatus)
    .then(parseJSON)
    .then((data) =>{
      const {status,message}=data;
      if(status!==1){
        const err = new Error(message,status);
        throw err;
      }
      return {data};
    }).catch((err) =>{
      if(throwError){
        throw err;
      }else{
        return {err};
      }
    });

}
```
加入throwError的参数，来决定是抛异常，还是传递错误的err，不知道这种写法是否正常？

**Comment by Notedown-cn** [comment]
我是直接在effects 方法里面抽一个自己api定义的全局异常.每个方法都复制一次就好.
request.好像用处不大.不能做很多事情
`*login({ payload }, { select, call, put }) {
            yield put({ type: 'loginLoading' });
            const { data,url } = yield call(login, parse(payload));
            yield  error({ ...data,loginToRedirect:url },{ payload }, { select, call, put })
            if(data.error_code > 0){
                yield put({type: 'loginError',payload: data.error_desc});
                message.error(`登录失败: ${data.error_desc}`)
            }else {
                yield put({type: 'loginSuccess'});
                const loginToRedirect = yield select(state => state.global.loginToRedirect);
                yield put(routerRedux.push(`${loginToRedirect}`));

            }
        }`

import error from '../utils/error'
`export default function* error(data,payload, effects) {
   const { select, call, put } = effects
    if(data.error_code === 6000){
        yield put({type: 'global/loginToRedirect',payload: window.location.hash.replace(/#/,'')});
        yield put(routerRedux.push('/login'));
        return false
    }
}`

**Comment by sorrycc** [comment]
1. 1 的问题理论上不应该存在啊。。你确定吗? 
2. promise 里用 reject，不要 throw Error 。

**Comment by sorrycc** [comment]
@Notedown-cn `yield call(error, ...args)` 会更标准点。
