### ISSUE TITLE
dva  new project 0.8.2

### ISSUE THREAD

**Issue by laisancun** [dvajs/dva#1410]
通过 npm 安装 antd
![image](https://user-images.githubusercontent.com/11416379/34206236-ac11f5d0-e5c0-11e7-8041-d25bf51a2c75.png)

**Comment by yvanwangl** [comment]
@laisancun 你需要先安装 react 和react-dom，react-router 和 antd 都配置了 `peerDependencies` ,如果你安装了，确认下版本对不对，antd 依赖 react@>=16
