### ISSUE TITLE
onAction 设置redux-logger报错

### ISSUE THREAD

**Issue by jkhmnk** [dvajs/dva#1413]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

onAction(fn | fn[])

在 action 被 dispatch 时触发，用于注册 redux 中间件。支持函数或函数数组格式。

例如我们要通过 redux-logger 打印日志：

import createLogger from 'redux-logger';
const app = dva({
  onAction: createLogger(opts),
});

---------------------------------------
按以上API文档 操作，会出现  middleware is not a function 的报错，加上这些中间件也是会报其它的错

#### Expected behavior: (预期的正常效果)
能如实按api里 演示代码运行

#### Actual behavior: (实际效果)
报错

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"dva": "^2.0.0",
"redux-logger": "^3.0.6"

**Comment by shizhiqian** [comment]
这么写:import { createLogger } from 'redux-logger';
