### ISSUE TITLE
关于@types/dva的提示

### ISSUE THREAD

**Issue by xiaoxiangmoe** [dvajs/dva#1415]
安装 @types/dva 得到如下提示

> This is a stub types definition for dva (https://github.com/dvajs/dva). dva provides its own type definitions, so you don't need @types/dva installed!

但是dva中并没有类型定义文件。

请问一个如何在typescript中正确使用dva呢？我使用的打包工具是 parcel。

**Comment by zhaojinxiang** [comment]
2.2.0-beta.2 版本，依旧没有.d.ts的存在

**Comment by zhaojinxiang** [comment]
找到bug的原因了：

发布的主要方法见于 [TypeScript: 发布
](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

```json
{
    "name": "awesome",
    "author": "Vandelay Industries",
    "version": "1.0.0",
    "main": "./lib/main.js",
    "types": "./lib/main.d.ts"
}
```

由于作者没有填写`main`和`types`，所以，我们得不到`.d.ts`文件。
望修复。

**Comment by zhuyangbing** [comment]
望修复

**Comment by consigliory** [comment]
+1

**Comment by 662** [comment]
+1

**Comment by aylei** [comment]
看起来 dva 使用 `index.d.ts` 可以不需要显式声明:

> Also note that if your main declaration file is named index.d.ts and lives at the root of the package (next to index.js) you do not need to mark the "types" property, though it is advisable to do so.

来自: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by sorrycc** [comment]
It's fixed in the master.
