### ISSUE TITLE
关于dva-loading与ajax的异常处理

### ISSUE THREAD

**Issue by woshiguabi** [dvajs/dva#1418]
在ajax发生异常时，通常希望在request中统一处理，而又不希望effects继续往下走（不然会引起一连串的错误），所以我选择了直接在requset中throw了错误，但这又会导致dva-loading不会结束掉loading。

例如以下使用场景
```jsx
<Button loading={loading.effects['list/delete']}>Delete</Button> 
```
```js
effects: {
  *delete({ payload }, { call }){
    yeild call(delete, payload);
    message.success('delete success'); // 不希望上面报错后继续执行
  }
}
```
如果在删除请求中报错，那么希望loading状态退出，按钮恢复可点击，但不希望出现删除成功的提示信息。
建议dva-loading在`yield effect`的时候catch到报错并退出loading状态

**Comment by woshiguabi** [comment]
看了一些代码后发现在dva中加了onError hook可以catch到报错，所以解决方法就是在初始化dva时加上onError就可以了

**Comment by qq5625655** [comment]
您好，我也碰到了这个问题，我想问一下，如何在catch捕获到？能否放点源代码？

**Comment by woshiguabi** [comment]
> 您好，我也碰到了这个问题，我想问一下，如何在catch捕获到？能否放点源代码？

在dva初始化配置中加入onError，如果你是使用umijs需要新建一个dva.js文件去配置

**Comment by jefferyssy** [comment]
我发现 onError 中已经捕获到错误了， 但是  dva-loading 状态还是没有还原。
