### ISSUE TITLE
How to integration with redux-persist V5?

### ISSUE THREAD

**Issue by kunhour** [dvajs/dva#1419]
Because:"redux-persist V5" remove autoRehydrate, I found that dva is based on Redux-persist V4,
How to use v5 in this dva;

#### Expected behavior: (预期的正常效果)
can use redux-persists v5

#### Actual behavior: (实际效果)
--

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva:v2.1
redux-persists:v5.4

**Comment by 662** [comment]
同求如何使用V5

**Comment by wuzhuzhu** [comment]
同求，v5需要用一个HOC：“persistReducer”来处理reducer， 但是dva并没有"reducerEnhancer "这种东西..只有extraReducer

**Comment by lyingd** [comment]
I have a demo about redux-persist V5: 
https://github.com/lyingd/antd-pro-standalone/commit/99364215646ad05096a0128efb7c2bb2d561f117
I hope this will help you.
@662 @kunhour

**Comment by kunhour** [comment]
@lyingd Thanks!

**Comment by lyingd** [comment]
new commit: https://github.com/lyingd/antd-pro-standalone/commit/24bfb77b501d2bec3f956607da9c80d66be55402

**Comment by programmer-RN** [comment]
Hi, I am new in redux persist. I am facing error of **Redux-persist failed to create sync storage, falling back to memory storage.** Please help me, thank you.
