### ISSUE TITLE
有个想法，关于 dva 做的后管系统中页面复用的讨论

### ISSUE THREAD

**Issue by dkvirus** [dvajs/dva#1421]
### 问题
使用 dva 开发后管系统很是方便，有个应用场景是：当需要开发多个后管系统，每个后管系统中都有几个相同的模块，比如用户管理，每次都重新开发很是麻烦，就算是复制粘贴代码也显得麻烦。

### 想法
能否将 `用户管理` 这个页面给打包成一个 npm 包，如果再有新的后管系统需要这个模块，通过引入 npm 的方式引入进来简单配置下就 OK 了。

这样做有个好处就是：当一个系统中的用户模块有修改时，只需要修改之后更新 npm 包，其它系统同步更新下 `用户管理` 的最新包即可。不用去每个系统单独修改用户管理模块。

### 疑惑

我试了下，单独的 react 组件是没问题的，但是在 dva 框架中组件（routes）会和数据（models）通过 connet() 连接起来，我引入 npm 包之后页面就出不来了。。。。。

不知道大伙儿有没有遇到类似问题，有什么好的解决方案。

![image](https://user-images.githubusercontent.com/29170168/34369326-eeb0d2a0-eaf5-11e7-8899-91fd07d0bb07.png)

**Comment by Elity** [comment]
1.其它项目的问题应该去对应的项目提issue
2.如果你觉得某个东西应该成为你们公司内部共用的组件/库，你们可以在公司内部搭建私有的npm服务
3.
> 我引入 npm 包之后页面就出不来了
您确定控制台没有报错提示？

**Comment by dkvirus** [comment]
@Elity 好吧，我只是遇到了这个应用场景，知道 dva 社区大牛比较多，所以过来这边取取经。

**Comment by yvanwangl** [comment]
@dkvirus 你说的问题不是dva的吧，而且dva并没有干涉你数据传递的逻辑，还是通过 react-redux 的 connect 连接组件和redux store 的。
如果你封装的npm包是傻瓜组件直接引入即可，根本涉及不到从redux获取数据的问题，如果封装的是智能组件，
```
import SmartComponent from 'npm-package';
import {connect} from 'react-redux';
export default connect()(SmartComponent );
```
这样应该是可以正常工作的。

**Comment by dkvirus** [comment]
控制台报错信息如下：

```
warning.js?6327:33 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `AsyncComponent`.
    in AsyncComponent (created by Route)
    in Route (created by Unknown)
    in Switch (created by Unknown)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by withRouter(Connect(App)))
    in withRouter(Connect(App)) (created by Unknown)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Unknown)
    in Provider (created by Unknown)
    in Unknown

utils.js?9bab:240 uncaught at _callee Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `AsyncComponent`.
    at invariant (webpack-internal:///9:42:15)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (webpack-internal:///411:72:23)
    at ReactCompositeComponentWrapper._updateRenderedComponent (webpack-internal:///860:758:24)
    at ReactCompositeComponentWrapper._performComponentUpdate (webpack-internal:///860:721:10)
    at ReactCompositeComponentWrapper.updateComponent (webpack-internal:///860:642:12)
    at ReactCompositeComponentWrapper.receiveComponent (webpack-internal:///860:544:10)
    at Object.receiveComponent (webpack-internal:///103:122:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (webpack-internal:///860:751:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (webpack-internal:///860:721:10)
    at ReactCompositeComponentWrapper.updateComponent (webpack-internal:///860:642:12)
```

**Comment by yvanwangl** [comment]
@dkvirus Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `AsyncComponent`. 查看一下你的 AsyncComponent render 方法返回的是个对象？

**Comment by dkvirus** [comment]
@yvanwangl 项目代码里并没有 `AsyncComponent` 这个东东，我全局搜了下也没有，所以很奇怪这个报错。

**Comment by yvanwangl** [comment]
@dkvirus AsyncComponent (created by Route) , react-router 创建的组件，检查一下你的路由配置吧

**Comment by dkvirus** [comment]
终于成功了，页面也可以发布 npm 包进行复用了。感谢 @yvanwangl  的启发。

记录中间遇到的一个坑：引入 npm 包后默认不能识别，报如下错误：

```
You may need an appropriate loader to handle this file type.
| import React from 'react';
| /*
| import { render } from 'react-dom'
```

解决方法：在 .roadhogrc 中添加配置 `extraBabelIncludes` 属性，具体如下。该属性中 "node_modules/test-user" 就是将 `用户管理` 页面打成的 npm 包的路径。

```
export default {
  "entry": "src/index.js",
  "hash": true,
  "extraBabelIncludes": [
    "node_modules/test-user"
  ],
  // ..........
}
```

**Comment by dkvirus** [comment]
终于成功了，页面也可以发布 npm 包进行复用了。感谢 @yvanwangl  的启发。

记录中间遇到的一个坑：引入 npm 包后默认不能识别，报如下错误：

```
You may need an appropriate loader to handle this file type.
| import React from 'react';
| /*
| import { render } from 'react-dom'
```

解决方法：在 .roadhogrc 中添加配置 `extraBabelIncludes` 属性，具体如下。该属性中 "node_modules/test-user" 就是将 `用户管理` 页面打成的 npm 包的路径。

```
export default {
  "entry": "src/index.js",
  "hash": true,
  "extraBabelIncludes": [
    "node_modules/test-user"
  ],
  // ..........
}
```

**Comment by yvanwangl** [comment]
@dkvirus 祝贺，`extraBabelIncludes` 的配置应该是增加额外给 babel 编译的文件的，你这么放也是可以解决的。但是感觉你引入包报错应该是你打的npm包有问题，不过条条大路通罗马，解决了就行。
