### ISSUE TITLE
I couldn't get any information of location provided by react-router-redux in store when upgraded to dva@2

### ISSUE THREAD

**Issue by ufohjl** [dvajs/dva#1425]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
in model
```
export default {
  namespace: 'test',
  effects: {
    *test({payload}, {call, put, select}) {
      console.log(yield select(state => state.routing))
    },
}
```

#### Expected behavior: (预期的正常效果)
some location information

#### Actual behavior: (实际效果)
```
{
  location: null
}
```

#### Versions of packages used: (哪个库的哪个版本出现的问题)
```"dva": "^2.1.0"```

**Comment by lyingd** [comment]
Same issue

**Comment by ufohjl** [comment]
Use ```<ConnectedRouter />``` instead of ```<Router />```
[https://github.com/reacttraining/react-router/tree/master/packages/react-router-redux](url)
```
import React from 'react'
import {Route, routerRedux, Switch} from 'dva/router'
import App from './App'

function RouterConfig({history}) {
  return (
    <routerRedux.ConnectedRouter history={history}>
      <Switch>
        <Route exact path="/" component={App}/>
      </Switch>
    </routerRedux.ConnectedRouter>
  )
}

export default RouterConfig


```

**Comment by lyingd** [comment]
@ufohjl , thx! It work! But there is a problem, time travel did not work for router.
