### ISSUE TITLE
使用dva-cli 创建项目  在ejs 模板中引入外部库报错

### ISSUE THREAD

**Issue by johnsky123** [dvajs/dva#1426]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
使用dva-cli 创建项目  在ejs 模板中引入外部库报错
![image](https://user-images.githubusercontent.com/11240977/34403636-608f732e-ebe4-11e7-8049-f103bb7b4916.png)

**Comment by yvanwangl** [comment]
@johnsky123 最好能够提供一下代码。

**Comment by johnsky123** [comment]
@yvanwangl  
![image](https://user-images.githubusercontent.com/11240977/34404952-8237a4b8-ebeb-11e7-9bd1-ef44a66d3315.png)
![image](https://user-images.githubusercontent.com/11240977/34405191-de86849a-ebec-11e7-9719-1c2d6cbc2183.png)

**Comment by yvanwangl** [comment]
@johnsky123 问题应该不在这个html里，你有在线的项目代码么？

**Comment by wuyunjiang** [comment]
@johnsky123 什么原因，朋友
