### ISSUE TITLE
在嵌套路由中动态加载model

### ISSUE THREAD

**Issue by zmayor** [dvajs/dva#1427]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
复现错误: `https://github.com/zmayor/dva-dynamic-route-model`

#### Expected behavior: (预期的正常效果)
我想在嵌套路由中动态加载 model, 我想通过上下文传递`app`, 然后动态加载model

#### Actual behavior: (实际效果)
确实实现了动态加载model的效果,但是会报错
`warning.js?6327:33 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the DynamicComponent component.`

**Comment by zmayor** [comment]
[这就是那个错误](url)
![dva-dynamic-router-model-error](https://user-images.githubusercontent.com/18019463/34514074-68238802-f0a6-11e7-9ed7-bdc64e1d3c80.png)

**Comment by liuzhenji** [comment]
这个app实例的传递真的很郁闷。我是通过把实例绑定到window对象是实现的，不过，你这个context上下文的方式可能更好

**Comment by Zeus-Iqd** [comment]
@liuzhenji 能分享下代码怎么实现的吗

**Comment by Zeus-Iqd** [comment]
@zmayor 您好，能私聊下吗？

**Comment by Zeus-Iqd** [comment]
@zmayor 为啥把仓库删了？

**Comment by zmayor** [comment]
我已经很久没有用dva了， 然后忘记了就给删除了。

**Comment by zmayor** [comment]
现在这个功能用umi很好实现啊，你可以去看看。

**Comment by Zeus-Iqd** [comment]
@zmayor 921971272，qq方便加下吗？拜托了🙏

**Comment by Zeus-Iqd** [comment]
@zmayor 想问下大佬怎么通过上下文传递app, 然后动态加载model的？我项目进行了一大半，现在再切换umi代价有点大。
