### ISSUE TITLE
关于动态路由的问题?

### ISSUE THREAD

**Issue by Josin22** [dvajs/dva#1428]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
router.js文件里
```
 const TestComponent = dynamic({
    app,
    component: () => import('../TestComponent') ,
  });
return (
    <Router history={history}>
      <Switch>
      <Route exact path="/index/:token" component={TestComponent} />
      <Switch>
    </Router>
)
```

#### Expected behavior: (预期的正常效果)
TestComponent组件里constructor方法里获得到token

#### Actual behavior: (实际效果)
console this.props.params.token 却变成undefined

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva 2.1.0

**Comment by neewbee** [comment]
`props.match.params`

**Comment by ZGM8** [comment]
Cannot read property 'match' of undefined

**Comment by kldcty** [comment]
存在props.match.params中

**Comment by ZGM8** [comment]
props.match.params 为空对象

**Comment by Josin22** [comment]
来一个正解,
```
let hash = _.get(props,'location.hash')
    if (!_.isEmpty(hash)){
      let hash_array = _.split(hash,'/')
      let last_value = _.last(hash_array)
      console.log('token',last_value)
    }
```
就可以拿到token了
