### ISSUE TITLE
`dva/dynamic` 对webpack有要求吗？

### ISSUE THREAD

**Issue by bochen2014** [dvajs/dva#1430]
如果我不用`roadhog`, 自己配`webpack.config`， 如何支持 `dva` 的 `dynmic`  ？
可否给一些不用`roadhog`的例子？ 谢谢

**Comment by sorrycc** [comment]
google 下 `webpack + import()`。

**Comment by bochen2014** [comment]
多谢！
https://webpack.js.org/guides/code-splitting/#dynamic-imports
