### ISSUE TITLE
使用BrowserRouter进去还是有#/

### ISSUE THREAD

**Issue by liu1131170225** [dvajs/dva#1434]
路由使用BrowserRouter进去还是有#/，跳转没有，刷新后也会出来#
需要怎么配置，还是加啥？

**Comment by shizhiqian** [comment]
根目录/src/index.js文件:
import browserHistory from 'history/createBrowserHistory';
const app = dva({
  history: browserHistory(),
});

**Comment by 951565664** [comment]
@shizhiqian 还是不可以啊
![image](https://user-images.githubusercontent.com/22285404/39557296-09de12d2-4eb9-11e8-976d-fb170d2506cf.png)
![image](https://user-images.githubusercontent.com/22285404/39557297-12746e64-4eb9-11e8-847d-e48388c40b31.png)
![image](https://user-images.githubusercontent.com/22285404/39557315-30c6bcf0-4eb9-11e8-9885-ffb9dddf75d6.png)
