### ISSUE TITLE
dynamic按需加载报Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.  Please check the code for the DynamicComponent component.

### ISSUE THREAD

**Issue by panshiyu** [dvajs/dva#1436]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
layout页面的路由----------：
`              {
                getRouteData('BasicLayout').map(item =>
                  (
                    <Route
                      exact={item.exact}
                      key={item.path}
                      path={item.path}
                      component={dynamic({
                        app,
                        ...item.component,
                      })}
                    />
                  )
                )
              }`

item.component 为-----
`const Setting = {
  models: () => [
    import('../models/user'),
  ],
  component: () => import('../routes/Personal/Setting'),
}`

#### Expected behavior: (预期的正常效果)
按需加载方法能实现，但会报Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.Please check the code for the DynamicComponent component.

#### Actual behavior: (实际效果)
请问这个应该如何解决？

#### Versions of packages used: (哪个库的哪个版本出现的问题)
 "dva": "^2.1.0",

**Comment by code-artisan** [comment]
我也遇到了同样的问题，作者出来瞄一眼呀 @sorrycc

**Comment by panshiyu** [comment]
升级到2.2就好了，已修复

**Comment by code-artisan** [comment]
2.2 啥时候发正式版？现在还是 beta。
