### ISSUE TITLE
编辑时，如何在编辑成功的时候再关闭弹窗，编辑失败时，不关闭弹窗？

### ISSUE THREAD

**Issue by wangyang851221** [dvajs/dva#1437]
如题，在    this.props.form.validateFields((err, values) => {
      if (!err) {
        onOk(values);
        this.hideModelHandler();
      }
    });
如何拿到onOk(values)成功失败结果

**Comment by zhao-xiaohu** [comment]
将this传入onOk函数中，在操作成功时执行this.hideModelHandler()。如果里面是一个请求，成功结果需等后端返回，那写在models层操作更合适。
