### ISSUE TITLE
通过yield call()发送请求拿到数据后要改变数据的数据结构，应该在哪改变。

### ISSUE THREAD

**Issue by curry-wxj** [dvajs/dva#1441]
请问：通过yield call()发送请求拿到数据后要 将数据结构改变成echarts的数据结构， 应该在effects里面直接改变在yield put()出去还是在reducers中改变，还是在组件中改变。

**Comment by yvanwangl** [comment]
@curry-wxj 你可以封装一个转换的工具类，在 effects 里面调用，effects 就是专门处理副作用的，将数据转换放在上游处理，下游使用的地方就很舒服。因为我个人感觉，对于 reducers 来说关注的应该是 state 值得变化，而对于组件更是如此，只关注数据流，不用关注数据转换。而且 。如果将转换放在 reducers 或 组件中，如果多个 action 或者多个组件都关注这个数据，岂不是要在多个地方都要处理。
个人观点，仅供参考 :)
