### ISSUE TITLE
在View层，如何执行dispatch的catch方法

### ISSUE THREAD

**Issue by jinyang1994** [dvajs/dva#1442]
#### Versions of packages used: 

我想在effect 发起一个异步请求，但是想捕获error，并在view中处理，现在目前可以通过then来判断，但是我想让代码语义化更强一些，想当有异常的时候，执行catch方法。怎样可以做到，谢谢

**Comment by lixiaolihua** [comment]
请问解决了吗

**Comment by jinyang1994** [comment]
Promise.reject()
