### ISSUE TITLE
dva generate is disabled

### ISSUE THREAD

**Issue by xiaohuoni** [dvajs/dva#1445]
dva g model test
dva generate is disabled since we don't have enough time currently.

**Comment by JackGit** [comment]
some issue here, is it a joke?

**Comment by xiaohuoni** [comment]
Read the source code，no find ‘’since‘’

**Comment by TivonChen** [comment]
same problem with 0.9.2

**Comment by liyang001** [comment]
some issus  : 
        dva g route List;
        dva generate is disabled since we don't have enough time currently.
dva version : 2.1.0

**Comment by Tim2011** [comment]
我也遇到同样的情况
