### ISSUE TITLE
使用动态加载时出现多次加载组件的情况

### ISSUE THREAD

**Issue by focus0802** [dvajs/dva#1449]
#### Expected behavior: (预期的正常效果)
子组件的 componentDidMount 只执行一次

#### Actual behavior: (实际效果)
子组件 componentDidMount 执行多次（根据父组件的更新而变）

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva@2.2.0-beta.2

```
router.js
---------
<Router history={history}>
    <Switch>
       <Route
            path="/"
            component={dynamicWrapper(
              app,
              ['auth', 'main', 'shop', 'cart'],
              () => import('./routes/Main'),
            )}
          />
    </Switch>
</Router>
```
```
Main.js
-------
...
<Switch>
    <Route
        exact
        path="/news"
        component={dynamicWrapper(
            app,
            ['news'],
            () => import('./News'),
        )}
   />
</Switch>
...
```

目前的状况就是 Main 也就是父组件更新就会导致 News 重新加载，我试了一下，如果把 dynamicWrapper(dynamic) 改成普通的加载方式（直接加载组件）就不会出现这种情况。

请问在使用动态加载的情况有什么解决方案可以解决这个问题？

**Comment by sxl53037072** [comment]
我也出现这种问题，有什么办法解决的吗，现在只要子组件更新state就会重新加载导致表单值全部重置为空

**Comment by likepearl** [comment]
这个问题解决了吗？ dynamic 有没有好的版本

**Comment by likepearl** [comment]
这个问题解决了吗？ dynamic 有没有好的版本
