### ISSUE TITLE
建议dva支持微信小程序的开发

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#145]
@sorrycc，我建议把dva集成到微信小程序开发。

**Comment by sorrycc** [comment]
还没有 微信小程序 的账号。

**Comment by bjwulin** [comment]
@sorrycc ,现在没有内测账号也可以开发，参考：https://www.v2ex.com/t/309591，dva非常不错，我现在pc和mobile都在用，我觉得要是支持微信小程序，对dva的推广有很大的好处。

**Comment by sorrycc** [comment]
感谢提供信息，我找时间研究下。

**Comment by bjwulin** [comment]
@sorrycc ,有人把redux和小程序结合：https://github.com/charleyw/wechat-weapp-redux，期待dva和小程序结合

**Comment by bjwulin** [comment]
现在的小程序开发工具不需要内测账号，部分功能受限，倒是不影响集成dva到小程序的开发。坐等@sorrycc集成了，咱们能够出点力么？

**Comment by bjwulin** [comment]
微信有个框架：https://github.com/maichong/labrador，@sorrycc可以参考下
