### ISSUE TITLE
请问npm start成功后，打开的页面是空白的。访问其它路由也全是空白的

### ISSUE THREAD

**Issue by zhuangtq** [dvajs/dva#1451]
请问npm start成功后，打开的页面是空白的。访问其它路由也全是空白的。。

![default](https://user-images.githubusercontent.com/29749908/34858703-c69d298c-f78c-11e7-97da-031cc838e51d.png)

**Comment by zhuangtq** [comment]
$ npm start

> @ start G:\HgygProject\RSIS\RSISFour\rsis\src
> set PORT=9111 && roadhog server

Starting the development server...

[babel-plugin-dva-hmr][INFO] got routerPath ./router
[babel-plugin-dva-hmr][INFO] got routerPath ./router
Compiled successfully in 25.5s!

The app is running at:

  http://localhost:9111/

Note that the development build is not optimized.
To create a production build, use npm run build.

请问下是什么原因，求大神们解答下，谢谢

**Comment by sorrycc** [comment]
不是有报错提示吗？

**Comment by huacheng26** [comment]
路由配置的问题，我想问一下，怎么配置多页面。
