### ISSUE TITLE
dispatch:action should be a plain Object with type

### ISSUE THREAD

**Issue by zouyan532** [dvajs/dva#1452]
点击按钮    
loginOnPress=(param)=>{
        console.log(this.state.password)
        this.props.dispatch({
            type:'demo/getToken',
            shipNumber:this.state.shipNumber,
            password:this.state.password,
            phone:this.state.phone,
            vCode:this.state.vCode,
           
       })     
    }
这是model里的
* getToken({shipNumber,password,phone,vCode},{put}){
			const res = yield put(service.login,shipNumber,password,phone,vCode)
			console.log(res)	
		},
报标题上的错误

**Comment by sunflower-tc** [comment]
hi I encountered the same problem.

**Comment by MingSeng-W** [comment]
me too, any solution this problem?

**Comment by wellenzhong** [comment]
I guess you guy use "yield put" to request an API, which is expected "yield call".
