### ISSUE TITLE
models里，文件名跟namespace不一致会提示namespace should be unique

### ISSUE THREAD

**Issue by longzhaobi** [dvajs/dva#1453]
roadhog版本：2.0.6
dva版本：2.1.0

我用antd-design-pro的项目也试了一下，发现models文件夹下的文件名和其namespace名称不一致时，就会namespace should be unique。

以前还没升级roadhog时，不会有这个提示的。

**Comment by sorrycc** [comment]
require 的时候要加 `.default`，参考 roadhog 的升级文档。

**Comment by sorrycc** [comment]
你确定吗？应该不是文件名的问题吧。。

**Comment by longzhaobi** [comment]
@sorrycc 确定 啊！都反复改来改去的弄几次了。既然关了，我就规定把namespace的值和文件名保持一致就是了。

**Comment by sorrycc** [comment]
我居然去测了一遍。。没有问题，请检查下自己的代码吧。

**Comment by longzhaobi** [comment]
@sorrycc  谢谢了，不过你们公司那个项目：ant design pro，我在他基础上改的，的确有这情况，我刚刚把ant design pro代码clone下来，就把models下的chart.js改成chartabc.js，再把router.js里引用的model改成chartabc就会提示：
```
[app.model] namespace should be unique
▶ 4 stack frames were collapsed.
(anonymous function)
d:/git/ant-design-pro/src/common/router.js:25
  22 | _models.forEach(function (model) {
  23 |   if (modelNotExisted(app, model)) {
  24 |     // eslint-disable-next-line
> 25 |     app.model(require("../models/".concat(model)).default);
  26 |   }
  27 | });
  28 | 
```

如果是代码有问题，应该是ant design pro有问题吧1

**Comment by longzhaobi** [comment]
@sorrycc 打扰了，这个问题在ant-design-pro的最新版本里有很多人提，不是dva的问题。
