### ISSUE TITLE
组件渲染完事后的回调写在哪里？

### ISSUE THREAD

**Issue by bibiehy** [dvajs/dva#1455]
roadhog版本：2.0.6
dva版本：2.1.0

例如：用户进入 /users 页面时，触发 action users/fetch 加载用户数据，当数据到达组件并渲染完毕后需要立即执行一些方法，在哪里执行啊

是使用 es6  class App extends React.Component({}); 的写法，写在 react 的生命周期 componentDidMount() 函数里面嘛？ 还是别的其他的方法

**Comment by sorrycc** [comment]
> 写在 react 的生命周期 componentDidMount() 函数里面嘛？

是的。
