### ISSUE TITLE
使用Browser history构建项目并发布到服务器上，页面访问的到但空白

### ISSUE THREAD

**Issue by bibiehy** [dvajs/dva#1457]
dva@2.1.0
roadhog@2.0.6

1. 直接 dva new 创建项目，打包/发布/访问正常，这是用的默认 hash #
2. 修改src/index.js文件，
    导入 import createHistory from 'history/createBrowserHistory';  
    配置 history: createHistory()
    这时npm start正常，npm run build 构建好的项目放在服务器上，浏览页面空白，页面能访问到，因为      添加的console.log();能输出来

    好像 roadhog@1.3 版本时候是可以的

**Comment by sorrycc** [comment]
路由没匹配。

**Comment by goonwzz** [comment]
html add  <base path='/'/> may worked

**Comment by goonwzz** [comment]
html need base path='/'

**Comment by bibiehy** [comment]
@sorrycc @goonwzz 自己的锅
因项目放在二级目录下面，RRv4 路由 basename 拼错了，导致空白。
二位，打扰了打扰了
