### ISSUE TITLE
who knows why 'dva g' command is disabled?

### ISSUE THREAD

**Issue by LuKun85** [dvajs/dva#1459]
tried many times, failed to executed commands dva g to create routes/coms.....who knows how to why and how to fix? thanks

lukun:test lukun$ dva g
/usr/local/lib/node_modules/dva-cli/bin/dva-generate
😢  dva generate is disabled since we don't have enough time currently.**_**_**
lukun:test lukun$ dva -v
dva-cli version 0.9.2
    dva version 2.1.0
roadhog version 2.1.0
lukun:test lukun$ dva g route menu
/usr/local/lib/node_modules/dva-cli/bin/dva-generate
😢  dva generate is disabled since we don't have enough time currently.
lukun:test lukun$

**Comment by erniu** [comment]
＋1

node: v8.5.0
dva-cli version 0.9.2
    dva version 2.1.0
roadhog version 2.1.0

**Comment by sorrycc** [comment]
What are you generating with `dva g` and what version of dva do you use? `dva g route` is not working since dva@2 is out.

**Comment by chencanbin** [comment]
我也遇到同样的问题，请问怎么解决

**Comment by chencanbin** [comment]
My dva version is 
dva-cli version 0.9.2
    dva version 2.1.0
roadhog version 2.2.0
