### ISSUE TITLE
项目在股沟、火狐、Edge、IE11上面完美运行，在IE9，IE10都报错，如下，请问怎么解决

### ISSUE THREAD

**Issue by bibiehy** [dvajs/dva#1461]
dva@2.1.0
roadhog@2.0.6

项目在股沟、火狐、Edge、IE11上面运行都完美，在IE9，IE10都报错，如下，请问怎么解决

dva new 新建项目 npm start 直接在 IE9,10上运行就会重现（win7 64, win10 64都会），不要用 Edge 浏览器带的 ie，

**捉急！**

![image](https://user-images.githubusercontent.com/35096473/34990274-7ed773ce-fb00-11e7-99ac-7a653419d1f6.png)
1. Map未定义点击定位到的
![image](https://user-images.githubusercontent.com/35096473/34990389-e6e603a4-fb00-11e7-9d1c-8382edfa0e32.png)

2. Promise未定义点击定位到的
![image](https://user-images.githubusercontent.com/35096473/34990501-583afe4c-fb01-11e7-8be6-82dfead5b58e.png)

**Comment by sorrycc** [comment]
加 babel-polyfill?

**Comment by bibiehy** [comment]
@sorrycc 可以的。

我一开始就加了，但位置错了，要在dva之前导入，文件变大了30k。

帮我看一下问题[1457](https://github.com/dvajs/dva/issues/1457)

**Comment by FuYiwei** [comment]
我的加了babel-polyfill，还是报一样的错误

**Comment by bibiehy** [comment]
@FuYiwei
加在index.js最上面，第1行
