### ISSUE TITLE
使用dva  在组件有轮询的项目中  dispatch  会有延迟  

### ISSUE THREAD

**Issue by johnsky123** [dvajs/dva#1462]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
使用dva  在组件有轮询的项目中  dispatch  会有延迟    是阻塞了吗

**Comment by sorrycc** [comment]
没明白，组件有轮询是什么意思？

**Comment by yvanwangl** [comment]
@sorrycc 我感觉他说的这个应该是 dispatch 多个相同 type 的 effect, 只有最后一个返回的 promise 可以被 决议 的问题  #1424 第二次提交。
