### ISSUE TITLE
关于单页应用注册一个之前注销的model时，effect、reducer中方法都被添加了前缀的bug

### ISSUE THREAD

**Issue by zxtyjx** [dvajs/dva#1466]
目前项目采用单页应用开发模式，问题步骤如下：
1、在A页面加载时注册了Amodel 
2、当页面跳转到B页面时，我注销了Amodel，并注册了Bmodel
3、当我再从B页面跳转回A页面时（同样的逻辑我需要注销Bmodel并注册Amodel）

这时问题出现了，根据警告信息看，Amodel中的所有effect和reducer方法名前都被添加了Amodel的namespace作为前缀，现象如下图，目前项目已经启动比较着急这个问题，麻烦帮忙看下！

#### Expected behavior: (预期的正常效果)
Amodel的定义如下：
{
    namespace: 'M01328020A020LP00301',
    state: {},
    effects:{
         * init(params,{select,put,call}){}
    },
    reducers:{
        initComplete(state,action){},
        updateFormData(state,action){}
    }
}

#### Actual behavior: (实际效果)

Warning: [prefixNamespace]: effect M01328020A020LP00301/init should not be prefixed with namespace M01328020A020LP00301
Warning: [prefixNamespace]: reducer M01328020A020LP00301/initComplete should not be prefixed with namespace M01328020A020LP00301
Warning: [prefixNamespace]: reducer M01328020A020LP00301/updateFormData should not be prefixed with namespace M01328020A020LP00301

这时发现Amodel中的init方法已经无法正常访问，因为方法名称已经从init变更为M01328020A020LP00301/init，而随着跳转的次数增加前缀也会根据次数增加，如下：
M01328020A020LP00301/M01328020A020LP00301/..../init

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"dva": "2.1.0"

**Comment by yvanwangl** [comment]
@zxtyjx 问题确实是存在的，应该在 model  注销时对 model 的 effects 和 reducers 做去前缀处理，然后再从 reduers 中删除。

**Comment by zxtyjx** [comment]
@yvanwangl 我在做注销操作的时候，model中的effect方法并没有前缀啊，是说我在注册的时候需要去掉前缀在注册吗？

**Comment by zxtyjx** [comment]
找到那个问题了，app.model注册后会在effect方法前增加命名空间前缀，但是该地址还是指向webpack的import缓存上，所以导致第二次import时由于地址不变也就是key不变，通过缓存取到的对象已经是被model修改过带前缀的对象了，目前的解决方案就是修改dynamic函数在注册model时，深克隆一下import后的model对象，再调用app.model方法注册。不过我觉得这应该算是个bug希望可以得到关注

**Comment by 104gogo** [comment]
我的项目使用了dva-hmr，保存model的修改之后，会执行unmodel方法
```
store.dispatch({ type: '@@dva/UPDATE' }); // 更新状态
```
然后触发组件执行，但是state因为reducer被删除了也没了，在组件中使用的时候会出现undefined报错
请问下这种情况有比较好的处理方式吗？

**Comment by rrandom** [comment]
这个项目。。怎么像死了一样

**Comment by rrandom** [comment]
这个错报的是warning, 但我这里该页的样式就加载不出来了，全乱了
