### ISSUE TITLE
执行unmodel后state中的数据并不会删除，当再次注册该model后，state中的数据还在

### ISSUE THREAD

**Issue by zxtyjx** [dvajs/dva#1468]
如题：今天主要使用了一下unmodel,model方法，感觉这个方法有很多需要改进的地方：
1、model方法直接去修改了effect中的原对象，导致二次注册时会在effect前增加多个前缀
2、unmodel方法执行后并没有把state中的数据删除，导致二次注册后state中的数据依旧存在

目前对于第一个问题的解决方法就是在注册的时候，对import后的model进行deep克隆再注册，第二个问题的解决方法就是在界面初始化的时候先执行一次state初始化的操作，会增加组件一次渲染，请问有没有好的方法，或者什么时候可以修改呢？一般一个迭代周期是多久呢？

"dva": "2.1.0",

**Comment by yvanwangl** [comment]
@zxtyjx 关联 #1466
