### ISSUE TITLE
使用了hashHistory仍然没出现_k参数

### ISSUE THREAD

**Issue by ITGraves** [dvajs/dva#1469]
使用了hashHistory仍然没出现_k参数，代码如下：

import createHistory from 'history/createHashHistory'

const app = dva({
  ...createLoading({
    effects: true,
  }),
  history: createHistory(),
})

**Comment by yvanwangl** [comment]
@ITGraves `const history = opts.history || createHashHistory();` dva 默认就会使用 hashHistory
