### ISSUE TITLE
dva for rn里面怎么用状态变化执行navigator.pop()

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#147]
dva for web弹出编辑窗口，可以用modalVisible这个状态变量来显示或者不显示modal，现在在rn里面，用navigator push和pop新界面，我怎么利用modalVisible这样的状态变量变化时执行push或者pop？

**Comment by sorrycc** [comment]
封装成 react component，监听 props 变动，执行 navigator 的方法。

**Comment by bjwulin** [comment]
我现在这样了，用两个状态变量：needOpen和needClose，当render时，发现needOpen=true的时候，我就push，然后发个action将needOpen：false，needClose同理。这样对不？感觉不如原来一个visible好使。
