### ISSUE TITLE
关于在effect下用select获取当前model里state数据问题

### ISSUE THREAD

**Issue by Cslove** [dvajs/dva#1471]
为什么在effect里用select获取当前model里state数据浏览器端直接报select not defined 问题！！！为什么呐

put  和call 都是正常的~~~~

**Comment by yvanwangl** [comment]
@Cslove 你贴下代码呢

**Comment by Cslove** [comment]
![_20180119113653](https://user-images.githubusercontent.com/23312535/35133879-b4cc3b54-fd0d-11e7-89b5-c28de723bfa6.png)
![_20180119114302](https://user-images.githubusercontent.com/23312535/35133933-02122270-fd0e-11e7-870d-0eae13b90ff2.png)

**Comment by yvanwangl** [comment]
@Cslove 需要这么写：
```
*addPost({payload}, {call, put, select}){
    ...
   const pay = yield select((state)=> ({domainId: state.modelName.stateKey})); 
   ...
}
```
你的代码里有两个错：
1、没有解构出 select 方法，
2、select 回调里的 state 是 redux 的state 对象，如果你想获取当前model 的需要 state.currentModelName
[参考文档](https://github.com/dvajs/dva-knowledgemap#select)

**Comment by Cslove** [comment]
额哈。。。也是忘了引入select，谢谢哈

**Comment by youngsailor** [comment]
select返回值做修改后会直接改state状态？为啥我的就直接改变了state了？
`                const roles = yield select(state =>state.organization.roles);
                console.log(roles);
                roles.forEach(function(curr,index,arr){
                    if(curr.id==payload.selectKey){
                        curr.action_list = payload.actionList.join();
                    }
                })
                return true;`
