### ISSUE TITLE
在最新版的dva中，发现组件没有按需加载了，麻烦看看

### ISSUE THREAD

**Issue by smithyj** [dvajs/dva#1476]
在最新版的dva中，发现组件没有按需加载了，就是只有一个index.[chunkhash].js文件，我记得之前版本是一个组件有一个.js文件的。
我的项目地址：http://github.com/smithyj/backend.yangyj.com
而且使用antd按照 antd使用babel-plugin-import配置，console居然有警告，搞不懂，求助
![qq20180119-201803](https://user-images.githubusercontent.com/9820142/35151019-a22c92a6-fd57-11e7-96b6-dd27905576b0.png)
![qq20180119-201928](https://user-images.githubusercontent.com/9820142/35151020-a26c3730-fd57-11e7-836d-6aed77fbd93a.png)

**Comment by chengnuo** [comment]
我会告诉你，只有 NODE_PATH = env 的时候，才可以么。
如果不可以，还是坐等大神，我只是看到你在env里面加了dva-hmr

**Comment by smithyj** [comment]
@chareice 你是指的哪个 antd 按需加载问题 还是  dva-hmr 的问题

**Comment by smithyj** [comment]
@chengnuo 你是指的哪个 antd 按需加载问题 还是 dva-hmr 的问题

**Comment by chengnuo** [comment]
dva-hmr

**Comment by smithyj** [comment]
@chengnuo dva-hmr 问题解决了，package.json 里面roadhog包版本问题

**Comment by sorrycc** [comment]
env.development.extraBabelPlugins 里也要把 import 加上。

**Comment by smithyj** [comment]
还以为会自动合并。感谢

**Comment by smithyj** [comment]
@sorrycc 还是没用，试过了

**Comment by smithyj** [comment]
@sorrycc 是引入组件的问题，如图，这样就会引入所有样式
![64be058f78c48a8e619f1498ab75603b](https://user-images.githubusercontent.com/9820142/35256475-0b262c5c-002f-11e8-83db-e25d215877f8.jpg)
