### ISSUE TITLE
dva/dynamic webpack配置

### ISSUE THREAD

**Issue by mei50923** [dvajs/dva#1477]
没有用roadhog自己配置webpack

const path = require("path");
//const webpack = require("webpack");
const HTMLWebpackPlugin=require('html-webpack-plugin');

module.exports = [{
    entry:{"index":"./src/index.js"},
    output: {
        path: path.join(__dirname, '/static/compiled-js'),
        filename: '[name].bundle.js',
        //chunkFilename: '[name].bundle.js',
    },
    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify(process.env.NODE_ENV)
            }
        }),
    ],
    resolve: {
        extensions: [".js", ".json", ".jsx"]
    },
    module: {
        rules: [{
            test: /\.(js|jsx)$/,
            exclude: /node_modules/,
            use: [{
                loader: "babel-loader",
                options: {
                    presets: [
                        "stage-0",
                        "env",
                        "react",
                    ],
                    plugins: [
                        "dva-hmr",
                        "transform-runtime",
                        "transform-decorators-legacy",
                        "transform-class-properties",
                        "transform-react-jsx",
                        "transform-object-rest-spread",
                        ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]
                    ]
                }
            }]
        },{
            test: /\.less$/,
            use: [{
                loader: "style-loader"
            }, {
                loader: "css-loader"
            }, {
                loader: "less-loader"
            }],
        }]
    }
}];

有设置对应的路由
访问后

![image](https://user-images.githubusercontent.com/14801491/35182051-6c40195e-fe08-11e7-8818-4baf0e217c6b.png)
对应的js没有引入进来
请问是还需要设置一些别的配置吗

**Comment by sorrycc** [comment]
webpack 配置问题，翻下 webpack 的文档吧，和 dva 无关。
