### ISSUE TITLE
在mode里面使用put没有效果

### ISSUE THREAD

**Issue by weihomechen** [dvajs/dva#1478]
```js
// aModel.js
// app是另一个`model`，我想在`message`的回调函数里面触发`app/routeChange`，但是没有成功
  message.success(msg, 2, () => {
       put({ type: 'app/routeChange', payload: { path: '/' } });
  });
```
怎样才能触发另一个`model`里的`effect`? 在`model`里面可以使用`dispatch`么

**Comment by yvanwangl** [comment]
@weihomechen 你没有 yield 住你的这个 effect，而 saga 是根据 yield 的指令来触发 middleware 执行的。

**Comment by weihomechen** [comment]
@yvanwangl  请问回调函数这里`generator`函数怎么写，老是语法报错😂
![image](https://user-images.githubusercontent.com/16172317/35269249-72ff1e7e-0066-11e8-9bfc-acc6c5e29334.png)

**Comment by yvanwangl** [comment]
@weihomechen 你把代码贴全，就整个 effect 方法都贴出来

**Comment by weihomechen** [comment]
@yvanwangl 
```js
// aModel.js 
* saveArticle({ payload }, { select, call, put }) {
      const { article } = yield select(state => state.articleEdit);
      article.content = payload.content;
      const { success, msg } = yield call(saveArticle, article);
      if (success) {
        message.success('保存文章成功', 2, () => {
        // 这里想要触发appModel里的effect
      });
        yield put({ type: 'saveSuccess' });
        yield put({ type: 'app/routeChange', payload: { path: '/' } });
      } else {
        message.error(msg);
      }
    },
```

```js
//appModel
    * routeChange({ payload }, { put }) {
      const { path = '/' } = payload;
      yield put(routerRedux.push(path));
    },
```

**Comment by yvanwangl** [comment]
@weihomechen 我感觉你这个 message 放model里不是特别合适。
你可以这么处理，在你触发 saveArticle 的地方：
```
dispatch({
     type: 'aModel/saveArticle'
}).then(result=> {
    if(result.success) {
        message.success('保存文章成功', 2, () => {
             dispatch({ type: 'app/routeChange', payload: { path: '/' } });
         });
    }else {
        message.error(result.msg);
    }
})

// aModel.js 
* saveArticle({ payload }, { select, call, put }) {
      const { article } = yield select(state => state.articleEdit);
      article.content = payload.content;
      const { success, msg } = yield call(saveArticle, article);
      if (success) {
        yield put({ type: 'saveSuccess' });
      }
      return  { success, msg };
    },
```

**Comment by weihomechen** [comment]
@yvanwangl  嗯嗯，message 放到 Component 里更好一些，谢谢解答～

**Comment by SanlinBlackball** [comment]
_this.props.dispatch(...).then is not a function 我使用这个方法 为什么会显示没有这个方法啊

**Comment by yvanwangl** [comment]
@SanlinBlackball 你 dispatch 的是一个 reducer 吧

**Comment by SanlinBlackball** [comment]
*submitMessage({payload}, { call, put ,select}) {
            const {messageType} = yield select(state => state.chatbox);
            const data = yield call(submitMessage, {payload: {messageType, mContent:payload.mContent}});
            if (data.data.code == ResponseCode.responseCodeSuccess) {
                // do something
                
            }
            return  { data: data.data};
        },

    this.props.dispatch({
            type: 'chatbox/submitMessage',
            payload: {mContent: document.getElementById("messageContent").value}})then((data) => {
                console.log(data);
            });
我用的是一个 effect啊 麻烦您帮我看一下 @yvanwangl

**Comment by yvanwangl** [comment]
@SanlinBlackball 你可以从以下两步排查一下：
1、把你 effect 里返回的数据打印一下看看是什么；
2、把 dispatch() 返回的结果打印一下看是不是 Promise 对象。

**Comment by SanlinBlackball** [comment]
我刚刚按您说的查询了一下 在Effect 中我的数据是

**Comment by SanlinBlackball** [comment]
我打印看了一下 我的在effect 显示的数据是
1. {data: {…}}
data:{code: 0, msg: "返回成功"}
__proto__:Object
2. dispatch() 返回的是一个 middleware
@yvanwangl

**Comment by yvanwangl** [comment]
@SanlinBlackball 你 dva 版本多少的

**Comment by SanlinBlackball** [comment]
"antd": "^2.7.3",
    "classnames": "^2.2.5",
    "dva": "^1.2.1",
    "dva-loading": "^0.2.0",
    "js-cookie": "^2.1.3",
    "object-assign": "^4.1.1",
    "react": "^15.4.0",
    "react-dom": "^15.4.2"
@yvanwangl

**Comment by SanlinBlackball** [comment]
"dva": "^1.2.1"

**Comment by yvanwangl** [comment]
@SanlinBlackball  dva 2.X 版本才会返回 Promise

**Comment by SanlinBlackball** [comment]
大神，如果我想在effect请求成功以后做相应处理，例如弹出alert 这应该怎么做啊 @yvanwangl

**Comment by yvanwangl** [comment]
@SanlinBlackball 你可以看看 #175 里面 @pizn 的回复，可以用这种方式自己包装一个Promise
