### ISSUE TITLE
Unsubscribing from a subscription

### ISSUE THREAD

**Issue by megawac** [dvajs/dva#1479]
I have a model that will subscribe a websocket to several expensive end points when the user is on particular routes. When the user leaves the route, I want to disconnect the websockets.

The [dva api docs][1] say

> Notice: if we want to unregister a model with `app.unmodel()`, it's subscriptions must return unsubscribe method.

However the docs do not include how to register a subscription with an `unsubscribe` method.

How does one create a subscription with an `unsubscribe` handler? I'd be happy to update the documentation if an example could be provided in this issue.

Thanks!

  [1]: https://github.com/dvajs/dva/blob/master/docs/API.md

**Comment by TimYi** [comment]
I think dva will invoke unsubscribe when your model is not in the current page, and it unmount this model.
If you want to change the subscribe state programatically, you should invoke your subscribe in an effect, and store the unsubscribe method in your state or offer a unsubscribe effect.
You can use saga eventChannel and take to implement this.

**Comment by yvanwangl** [comment]
@megawac If you want to return the unlisten function, you just do,
```
setup({dispatch, history}) {  // eslint-disable-line
            return history.listen(location => {
                ...
            });
        },
```
as `history.listen` will return a `unlisten` function. And in dva docs, it says:
```
subscription with format of ({ dispatch, history }) => unsubscribe
```
so, what you need do is just add a `return` : )

**Comment by megawac** [comment]
Thanks I missed that!
