### ISSUE TITLE
请教下问什么dva跑起来了，确无法访问接口

### ISSUE THREAD

**Issue by minzhang2** [dvajs/dva#148]
![image](https://cloud.githubusercontent.com/assets/15793061/19262919/263b0f00-8fcc-11e6-8492-f06f59030518.png)
显示接口无法访问，代码都是官方的，未曾改过

**Comment by sorrycc** [comment]
看不到图。

**Comment by minzhang2** [comment]
![image](https://cloud.githubusercontent.com/assets/15793061/19263226/e9759502-8fcd-11e6-90f3-5399c9d05ba8.png)

**Comment by nikogu** [comment]
接口要通过 `proxy` 插件起来的，你看看你的 `packege.json` 里面的 `start` 字段

**Comment by minzhang2** [comment]
![image](https://cloud.githubusercontent.com/assets/15793061/19267432/36f7e164-8fe1-11e6-9894-b1ba5d5a0577.png)
代码里面有的

**Comment by nikogu** [comment]
@minzhang2 看下终端是否有报错呢？
