### ISSUE TITLE
集成测试方案的一个想法

### ISSUE THREAD

**Issue by TimYi** [dvajs/dva#1480]
使用dva时，我经常需要测试一下静态页面的效果，有没有报错。这时候我会手动修改model里的state，让我可以直接看到某个页面的展示效果。
我想可以加一个页面测试的配置文件，这个文件的内容是一组地址和初始state的映射关系，另外增加一个启动命令，使用这个命令启动程序之后，访问已经配置的地址，会看到指定初始state所对应的展现效果。
Using dva, I ofen need to test some static page. In this condition, I would chang initial state in model, then start the program.
I think we can add a config file which stores a mapping of url and init state, we will also add a npm script which will use this config to start the program. So we go to the url in the mapping, we see what the page will be given the initial state.

**Comment by yvanwangl** [comment]
@TimYi dva 的 mock 解决方案是你想要的么？

**Comment by TimYi** [comment]
@yvanwangl 是的，看到你的回复我才看到有mock方案，谢谢！

**Comment by yvanwangl** [comment]
@TimYi 客气 ：）

**Comment by TimYi** [comment]
@yvanwangl 我看了现有的mock方案，是很强大了，但还是有一些不方便的地方。
我们的应用使用websocket推送所有的数据，这个mock的难度是一个问题。
另外我们目前只想测试dva运行时某些状态的渲染效果，现有的mock方案似乎只能mock请求，如果能直接替换initState就更加方便了。

**Comment by TimYi** [comment]
我想我应该多看看jest一类的测试工具。

**Comment by TimYi** [comment]
我有个想法，dva并不需要做什么改动，我可以写一个dva插件，增加一个可以修改全局state的extraReducer, 这样再app.start之后，如果我想做静态mock，我可以直接dispatch这个插件所指定的事件。
有一个问题就是dva的api并没有对外部暴露dispatch事件，看源码似乎可以通过_store.dispatch强制获得dispatch方法，但是最好的办法是dva提供一个onStarted(dispatch)之类的钩子，这样就可以通过插件机制实现静态mock测试功能。
@sorrycc @yvanwangl
