### ISSUE TITLE
关于path-to-regexp与subscriptions的问题

### ISSUE THREAD

**Issue by codenoobforreal** [dvajs/dva#1481]
假设有这么一个地址：'xxx/mary/applist'，当使用path-to-regexp匹配/:userId/(mary拟定为userid)和/applist时，结合订阅subscriptions分发不同action。

对于这个假设地址，两者都能够匹配，就导致dispatch同时分发两个动作。

我想要的效果是先让匹配userid的先触发，进行用户检验再进行applist的查询

有什么办法实现这样的设想？

**Comment by codenoobforreal** [comment]
userid和applist的匹配分别在不同的模块中

**Comment by yvanwangl** [comment]
@codenoobforreal 你就在 userid 所在的模块去匹配，然后进行用户校验，校验完成 再去 dispatch applist 模块里的action
