### ISSUE TITLE
app.unmodel 之后， dynamic 不会重复注册model

### ISSUE THREAD

**Issue by zzh-a** [dvajs/dva#1482]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
1，dynamic 注册一个model，
2，离开该组件时注销
``` javascript
 componentWillUnmount() {
    this.context.app.unmodel('direct');
 }
```
3, 在进入该路由时 model 不会重复注册

**建议**： [dynamic.js中](https://github.com/dvajs/dva/blob/470b68d6d1ca62bad66779446fbc851f88814d4b/packages/dva/src/dynamic.js#L6) 用本地的cache 去判断是否加载model，我建议应该实时从app中判断，这样会更符合预期。

#### Expected behavior: (预期的正常效果)
可以重复注册已 经注销的model

#### Actual behavior: (实际效果)
不会重复注册

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva@2.1.0

**Comment by zmayor** [comment]
请问有解决方法了吗

**Comment by Crown1991** [comment]
好像这个BUG还没有得到解决
