### ISSUE TITLE
dva2.0 hasHistory如何保留query 和key

### ISSUE THREAD

**Issue by kingsily** [dvajs/dva#1483]
dva 升级2.0 ，react-router 4.0后model的setup
`setup({ dispatch, history }) {    
      return history.listen(({ pathname, query }) => {})
    }`
之前是有query，地址里_k但是升级之后都没有了。这个如果还想保留要怎么配置

#### Expected behavior: (预期的正常效果)
保留原来的query和key
并且Link标签中也可以使用query

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva2.0 react-router 4.0

**Comment by yvanwangl** [comment]
@kingsily 详情见 [dva 2.0 说明](https://github.com/sorrycc/blog/issues/48)

**Comment by sorrycc** [comment]
楼上正解。
