### ISSUE TITLE
在与antd结合使用时候

### ISSUE THREAD

**Issue by WildDylan** [dvajs/dva#1484]
表单输入A
表单输入B

A 输入后，表单输入B 需要随之改变（100 减去 表单A输入的值），怎么操作呢？

**Comment by sorrycc** [comment]
表单数据通常不走 dva model 的。

**Comment by yvanwangl** [comment]
@WildDylan react 受控组件

**Comment by WildDylan** [comment]
恩，使用 onChange ...
