### ISSUE TITLE
prefixNamespace 应该是一个纯函数

### ISSUE THREAD

**Issue by angular-moon** [dvajs/dva#1486]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
prefixNamespace 不应该修改 model, 应该是一个纯函数
model -> unmodel  -> model 应为 model 被修改了, 会增加错误的 namespace

#### Expected behavior: (预期的正常效果)
prefixNamespace 应该是一个纯函数

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva-core: "^1.1.0"

**Comment by yvanwangl** [comment]
关联 #1468

**Comment by yvanwangl** [comment]
提交 PR #1493

**Comment by sorrycc** [comment]
Fixed via #1605
