### ISSUE TITLE
使用带参数配置Route path时报 Unexpected token <

### ISSUE THREAD

**Issue by lulei90** [dvajs/dva#1489]
```
<Switch>
        <Route path="/regHelp" component={RegHelp} />
        <Route path="/cardDetail"  component={CardDeatil} />
        <Route path="/noCredit"  component={NoCredit} />
        <Route path="/helpCenter"  component={HelpCenter} />
        <Route path="/loanDetail"  component={LoanDetail} />
        <Route path="/result"  component={Result} />
        <Route path="/record"  component={Record} />
        <Route path="/searchRecord/:id"  component={SearchRecord} />
        <Route path="/protocol"  component={Protocol} />
        <Route path="/declare"  component={Declare} />
        <Route path="/proDetail"  component={ProDetail} />
</Switch>
```

![image](https://user-images.githubusercontent.com/10334832/35480390-e365cf0c-0447-11e8-8c35-57b154c593cf.png)

把  path="/searchRecord/:id" 改为  path="/searchRecord"就好了

**Comment by sorrycc** [comment]
检查 SearchRecord 的语法问题，改成 `/searchRecord` 好了是因为没匹配上。

**Comment by lulei90** [comment]
换成其他路由 也都一样  只要加上参数配置都会报同样都错误 如不加配置页面都是能正常渲染都

**Comment by sorrycc** [comment]
引用的 index.js 没写成 `/index.js`？

**Comment by lulei90** [comment]
![image](https://user-images.githubusercontent.com/10334832/35480633-8af7ed4a-044d-11e8-8a96-fbf6340d59be.png)
![image](https://user-images.githubusercontent.com/10334832/35480636-b5ac888e-044d-11e8-8559-968dde44816d.png)
![image](https://user-images.githubusercontent.com/10334832/35480644-db071eb4-044d-11e8-9d00-a050cbb62c4c.png)
不知道原因 第一次用dva 之前项目使用路由带参数都配置 都是没问题 能正常渲染都

**Comment by sorrycc** [comment]
看不出原因，发个可重现的库上来可以帮你排查下。

**Comment by lulei90** [comment]
貌似跟createBrowserHistory有关
去掉后 使用默认哈希路由 就没问题了

**Comment by lulei90** [comment]
@sorrycc  [demo.zip](https://github.com/dvajs/dva/files/1680734/demo.zip)

**Comment by bobbychan** [comment]
此问题确实存在，我看ant design pro的路由模式也改成hash的了，就是因为会报错，希望能解决下

**Comment by bobbychan** [comment]
在ant-design-pro里看到已经修复了这个问题，可以关闭了。[#649](https://github.com/ant-design/ant-design-pro/issues/649)

**Comment by Przeblysk** [comment]
我修改public 下的index.js  写成  `/index.js` 就好了
