### ISSUE TITLE
能否把redux的store单独出来

### ISSUE THREAD

**Issue by skyblue** [dvajs/dva#149]
现在是在app.start()里初始化store
在使用react-hot-loader@^3.0.0 时 ,无法做到重新render保留store

**Comment by sorrycc** [comment]
用 [babel-plugin-dva-hmr](https://github.com/dvajs/babel-plugin-dva-hmr) 做 HMR。

**Comment by skyblue** [comment]
@sorrycc 我试了下examples里的project  使用HMR是会整体页面刷新?

**Comment by sorrycc** [comment]
用 dva-cli 创建一个项目试试，改 components, router.js, routes 会 HMR，models 和 services 的 HMR暂未支持。

**Comment by skyblue** [comment]
试了一下, 新创建的项目是可以HMR
但是index.js里默认代码是
```js
// 3. Model
// app.model(require('./models/example'));
```
如果去掉该行注释则修改会整页刷新

**Comment by sorrycc** [comment]
index.js 也是没法做 HMR 的。

**Comment by skyblue** [comment]
不是,我改动的是routes/IndexPage.js

**Comment by skyblue** [comment]
如果store 能提供一个get/set接口 应该就能使用了...

**Comment by sorrycc** [comment]
重装 dva-cli 创建试试，我测试过已经没有问题了。

相关 Release：

- https://github.com/dvajs/dva-cli/releases/tag/0.5.0
- https://github.com/dvajs/babel-plugin-dva-hmr/releases/tag/0.2.0
