### ISSUE TITLE
项目在页面开始加载的时候subscription方法会调用两次，点击按钮切换路由的话正常加载一。

### ISSUE THREAD

**Issue by ff-yang** [dvajs/dva#1490]
[reactDemo.zip](https://github.com/dvajs/dva/files/1670938/reactDemo.zip)

### 错误页面：/info 或者/login页面

1. npm start启动之后浏览器地址输入localhost:8000/info（或者localhost:8000/login）是错误界面
2. 在浏览器console下可以发现两次subscriptions的log，此log在src/models/info.js的subscription方法下
3. 上次出现此问题之后我用dva new project 创建一个新项目，把老项目代码拷贝到新项目中，subscription方法运行一次，但是这次又出现同样问题
4. 环境版本：
     OS：Deepin GNU/Linux 15.5 
     dva-cli version 0.9.2
     dva version 2.1.0
     roadhog version 2.2.0

**Comment by sorrycc** [comment]
原因是 index.js 引入了两次。1 次是 index.html 里写死的，另一次是以下配置注入的。

```
"html": {
  "template": "./src/index.ejs"
},
```

**Comment by ff-yang** [comment]
@sorrycc 谢谢了，你好，麻烦帮我看一下我使用BrowserHistory的时候访问二级路由会出现错误，具体在这个issue里，[切换BrowserHistory页面错误](https://github.com/dvajs/dva/issues/1475)，也是这个项目比如访问localhost:8000/exception/403路由就报错，但是访问/info或者/login就正常，辛苦了
