### ISSUE TITLE
怎么在组件外部获取store?

### ISSUE THREAD

**Issue by bowencool** [dvajs/dva#1491]
比如: 我想在`request.js`中拿到`store`中的`token`, 应该怎么做?
我看`redux`文档是这么写的:
``` javascript
import { createStore } from 'redux'
let store = createStore(todoApp)
```
可是`dva`创建的项目中, 这里的`store`好像并没有经过我手...

**Comment by sorrycc** [comment]
request.js 是从 effect 调的，effect 可以拿到 state，然后传给 request.js。

**Comment by bowencool** [comment]
那岂不是每次请求都要取一次token, 能不能在request.js里拿到token自动加上

**Comment by sorrycc** [comment]
不能，request.js 里不能直接取 state 。

**Comment by yvanwangl** [comment]
@bowencool 你这种需求可以自己创建一个全局对象，自己来维护，需要管理的数据就是数据量小，但是使用频繁的。

**Comment by bowencool** [comment]
@yvanwangl 多谢提醒

**Comment by xiaofengqqcom123** [comment]
model中，effects中，怎么调用state呢？？？

**Comment by nihgwu** [comment]
@xiaofengqqcom123 `select`

**Comment by nelhu** [comment]
可以通过app._store方式获取

**Comment by JimmyLv** [comment]
ref: [Dva 源码解析 | DvaJS](https://dvajs.com/guide/source-code-explore.html#store)

**Comment by 515445681** [comment]
这样获取呢，多看文档哈。
window.g_app._store
window.g_app._store.dispatch

文档地址：
https://umijs.org/zh/guide/with-dva.html#%E9%85%8D%E7%BD%AE%E5%8F%8A%E6%8F%92%E4%BB%B6

**Comment by jnoodle** [comment]
https://umijs.org/plugins/plugin-dva#usedispatch

用 getDvaApp() 来获取

getDvaApp()._store
