### ISSUE TITLE
GettingStarted无法运行

### ISSUE THREAD

**Issue by zhaoyao91** [dvajs/dva#1495]
从v1到v2的breaking change

> 同名 reducer 和 effect 不会 fallthrough（即两者都执行），而是仅执行 effect

导致现在的例子跑不起来

**Comment by yvanwangl** [comment]
@sorrycc 在 PromiseMiddleware 判断 isEffect 的逻辑里 增加一个 判断是否是 reducers 的方法 isReducer ，如果是 reducers 则 同时调用一下 next(action) 确保 reducer 也可以对该 action 进行处理。不知这么处理是否可行 ？
