### ISSUE TITLE
需要用BrowserRouter而不是Router，路由跳转后 location.pathname 没有改变，怎么办

### ISSUE THREAD

**Issue by bibiehy** [dvajs/dva#1498]
dva@2.10
roadhog@2.2.0

是这样的，我项目需要放在二级目录下面，所以用了BrowserRouter，然后在其basename属性中设置其二级目录路径，

当 Link to='/news' 时候，浏览器地址栏地址变为http://localhost:8000/news，然后再其对应Model.js里面监听subscriptions， location.pathname还是 '/' 而不是 '/news'，再次手动刷新会改变，这种情况该怎么办呢？ 

如果换成Router，传递history，一切正常，可我需要传递二级目录路径

**Comment by sorrycc** [comment]
basename 确认配对了吗？

**Comment by bibiehy** [comment]
@sorrycc  确认的
刚刚我 dva new 创建了一个demo，又确认了一下这个问题

dva@2.1.0
roadhog@2.20
win7 x 64
google 65.0.3322.4

我仅仅添加了一个 userModel.js，然后用的 BrowserRouter，代码贴图如下
package.json
![image](https://user-images.githubusercontent.com/35096473/35550363-fcc964c6-05c4-11e8-9bba-414a4f76ff01.png)
.webpackrc.js
![image](https://user-images.githubusercontent.com/35096473/35550996-ff0a3230-05c7-11e8-97b6-998397937b3c.png)
index.js
![image](https://user-images.githubusercontent.com/35096473/35550788-f7ae2f92-05c6-11e8-9009-10ec41020966.png)
router.js
![image](https://user-images.githubusercontent.com/35096473/35550828-19679d8a-05c7-11e8-9c6a-c832153cd96c.png)
model/userModel.js
![image](https://user-images.githubusercontent.com/35096473/35550483-7ec30842-05c5-11e8-8e14-2ba1bf81dc7a.png)
routes/User.js
![image](https://user-images.githubusercontent.com/35096473/35550503-93837956-05c5-11e8-8e8c-975eff21293e.png)

页面浏览，切换到 http://localhost:8000/user 后页输出的是默认的 state，location信息见console.log();
这时刷新一下，页面就更新内容为：user页面 - subscriptions
但是把 BrowserRouter 换成 Router 然后把 history 传给 Router 就一切正常。
![image](https://user-images.githubusercontent.com/35096473/35550873-6535a5cc-05c7-11e8-80ea-9e03fdc1556b.png)

**Comment by sorrycc** [comment]
参考 https://github.com/dvajs/dva/issues/1497 ？

**Comment by wanliyunyan** [comment]
为什么我切换页面的时候，url是变化了，但是根本不触发监听事件啊？
