### ISSUE TITLE
Module not found: Error: Can't resolve 'dva/dynamic' in ...

### ISSUE THREAD

**Issue by wangdedi1990** [dvajs/dva#1499]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
import dynamic from 'dva/dynamic'出现错误
![image](https://user-images.githubusercontent.com/28214000/35603305-c38e2152-0677-11e8-9d24-4d07f0b2ced4.png)

**Comment by sorrycc** [comment]
依赖没装好吧，node_modules 删了重装试试。

**Comment by wangdedi1990** [comment]
@sorrycc  dynamic 依赖了node_modules里面那个模块

**Comment by sorrycc** [comment]
从报错看，dva/dynamic 都没有 resolve 到。
