### ISSUE TITLE
effects报错显示优化讨论

### ISSUE THREAD

**Issue by nikogu** [dvajs/dva#15]
https://github.com/sorrycc/dva/blob/master/src/index.js#L148

`有try catch`
```
function* sagaWithErrorCatch(...arg) {
        try {
          yield _saga(...arg);
        } catch (e) {
          onError(e);
        }
}
```
报错反馈：
![image](https://cloud.githubusercontent.com/assets/1179603/16945685/9af2a424-4dd8-11e6-86a6-40af22515b5d.png)

可以看到，报错不明显，并没有告诉错误在哪个代码的哪一行，支持报了catch的地方，提示不好

`没有try catch`
```
function* sagaWithErrorCatch(...arg) {
    yield _saga(...arg);
}
```
![image](https://cloud.githubusercontent.com/assets/1179603/16945846/6fffbeb8-4dd9-11e6-965e-6c5092d9d744.png)

报错信息更加明显

**Comment by nikogu** [comment]
这个在实际项目中多次遇到，特别是effects写了多了以后，很难定位报错在哪里

**Comment by sorrycc** [comment]
试试给默认的 onError 加上 console.trace() 呢?

**Comment by nikogu** [comment]
建议采用 
```
const onError = opts.onError || function (err) {
    throw new Error(err.stack); // 可通过stack获取报错具体信息
};
```

**Comment by sorrycc** [comment]
印象中 `thow Error` 就应该会包含 stack 信息的，稍后我试下。

**Comment by nikogu** [comment]
@sorrycc 好的，你稍后试试，我这边测试的结果是，直接是追踪不到 :）

**Comment by sorrycc** [comment]
你的出错信息为啥是 terminal 里的? 浏览器 console 里的有 stack 信息吗?

**Comment by nikogu** [comment]
因为terminal里面好测，哈哈，其实就是因为在开发项目的时候发现报错跟踪不到才来调的，浏览器中只要是effects（sagas）里面报错，都只跟踪到onError，打出不了具体的报错代码，跟terminal中显示一致
