### ISSUE TITLE
dispatch一个reducer不是同步的么

### ISSUE THREAD

**Issue by weihomechen** [dvajs/dva#1500]
```js
// 在路由组件的 componentWillMount 生命周期中 dispatch 一个 reducer：'articleEdit/initState' 
init = (dispatch) => {
    dispatch({ type: 'articleEdit/initState' });
    dispatch({ type: 'adminCenter/getCateList' });
    const id = getQuery('id');
    id && this.getArticle(id);
  }
```

```js
// model中，initState 是一个 reducer
reducers: {
    initState() {
      return JSON.parse(initialState);
    },
}

// initialState
const initialArticle = JSON.stringify({
  title: '',
  abstract: '',
  author: JSON.parse(localStorage.getItem('userInfo') || '{}').name,
  content: null,
});

const initialState = JSON.stringify({
  isEditing: true,
  article: JSON.parse(initialArticle),
});

```

按照期望，是想`dispatch  initState`后，`model` 中的 `state` 应该同步被更改，然后再执行 `render` 函数，可是实际情况是 `dispatch initState `后，第一次执行 `render` 时，`model`中的`state`还未更改(如图，在dispatch后debugger看到的props)，等待第二次执行`render`时，`model`中的`state`才被更改；
![image](https://user-images.githubusercontent.com/16172317/35603363-f9585000-0677-11e8-80ea-6791d5e0a8e8.png)

如何确保initState生效（即model中的state更改后）再执行render函数？

**Comment by yupeilin123** [comment]
reducer应该要返回 state

**Comment by yupeilin123** [comment]
不推荐在componentWillMount里中dispatch一个reducer，因为会触发死循环。具体原因是，页面接收到父组件的值，触发componentWillMount生命周期，然后一个reducer又把modal的值修改了，又触发了componentWillMount。会导致死循环。至于你为什么没有触发这个逻辑，估计是语法原因了

**Comment by weihomechen** [comment]
dva中，reducer修改model后触发的是  componentWillReceiveProps 吧。。。
如果组件自己有state，setState 也可以在 componentWillMount 使用，因为它是 render 方法之前被调用，因此 setState 也不会导致重绘；
