### ISSUE TITLE
[app.router] router should be function, but got object

### ISSUE THREAD

**Issue by guopingzhao** [dvajs/dva#1504]
每次项目第一次编译都会出现这个错误，不需要改代码，热编译一次就好了，这是为啥啊
![image](https://user-images.githubusercontent.com/23192895/35785715-87627d24-0a5d-11e8-9222-22bc84d0510e.png)

**Comment by joriewong** [comment]
@guopingzhao build之后也会这样的问题，请问如何解决的？
