### ISSUE TITLE
为啥初始化的dva项目没有.roadhogrc文件

### ISSUE THREAD

**Issue by xujie-phper** [dvajs/dva#1506]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
使用npm i dva-cli -g
并dva new dva-demo

#### Actual behavior: (实际效果)
![image](https://user-images.githubusercontent.com/26377353/35856366-c436d272-0b70-11e8-8de8-3f113f17c09a.png)

**Comment by xujie-phper** [comment]
为啥初始化的dva项目没有.roadhogrc文件

**Comment by sorrycc** [comment]
roadhog@2 用 .webpackrc 作为配置文件了。
