### ISSUE TITLE
接口的数据是哪里来的呢？

### ISSUE THREAD

**Issue by zhanghaibin0712** [dvajs/dva#151]
接口的数据是哪里来的呢？

**Comment by sorrycc** [comment]
没明白问题是啥，详细点？

**Comment by zhanghaibin0712** [comment]
拿到用户列表的数据是通过mock模拟出来的吗？还有每次的数据都是这些中文名，是哪个地方可以配置的吗？还有一个问题就是新增删除的时候，数据都是保存到内存里面的吗？

**Comment by nikogu** [comment]
你说的是这个吧：https://github.com/dvajs/dva/blob/master/examples/user-dashboard/mock/users.js

mock的

**Comment by zhanghaibin0712** [comment]
@nikogu 是的，生产环境不会去这样子用的吧，一般都是调后台api，然后存数据库的吧

**Comment by nikogu** [comment]
生产环境走自己的服务就好了，你可以在 `package.json` 里面的 `start`字段看到，dora 的 proxy 插件，生产环境直接 build 了，不会走 mock 的

**Comment by zhanghaibin0712** [comment]
`const data = mockjs.mock({
    'data|100': [{
      'id|+1': 1,
      name: '@cname',
      'age|11-99': 1,
      address: '@region'
    }],
    page: {
      total: 100,
      current: 1
    }
  });
  tableListData = data;
  global.tableListData = tableListData;`
请教一下，上面的@cname是什么意思呢？看不明白~~

**Comment by zhanghaibin0712** [comment]
@nikogu  mock插件在这里的作用只是起了模拟数据请求，和拦截请求的作用是吧

**Comment by nikogu** [comment]
`@cname` 可以参看：https://www.npmjs.com/package/mockjs

proxy插件是个代理插件，所以能够把请求的数据代理到本地的mock文件

**Comment by zhanghaibin0712** [comment]
@nikogu 多谢哈！

**Comment by nikogu** [comment]
不客气！

**Comment by zhanghaibin0712** [comment]
感觉小型的个人项目用这个框架够呛的，显得复杂化了！你觉得呢？

**Comment by zhanghaibin0712** [comment]
或者是3个人以内的项目

**Comment by nikogu** [comment]
会稍微多一些代码，但是结构会清晰很多，后期的维护性会好一些
