### ISSUE TITLE
这个connect没怎么懂，有哪位大大讲解一下可以吗？也没找到connect的文档

### ISSUE THREAD

**Issue by cfx1314** [dvajs/dva#1510]
@connect(({ login, loading }) => ({
  login,
  submitting: loading.effects['login/login'],
}))

看到这段代码的时候，不怎么懂传的参数和返回的json跟effect的关系，也没找到这方面的文档，本人小白一个，刚接触react就看了这个，求指导

**Comment by sunplum123** [comment]
这个是Redux的东西，应该去看Redux的文档[Redux中文文档](http://www.redux.org.cn/)

**Comment by 510846** [comment]
submitting: loading.effects['login/login']
—— 这个搞不懂有什么意义？submitting 初始化还是 undefined，设置了会有什么不同？
