### ISSUE TITLE
异步chunks有加载失败的统一处理吗？

### ISSUE THREAD

**Issue by xioozq** [dvajs/dva#1513]
按照webpack文档里，动态import()会返回一个promise，可以捕获加载失败的错误。
但是在dva里，我们是直接写了一个函数交给dva按需调用了，
没法直接拿到那个promise，如果遇到chunk加载失败，就会由webpack抛出一个Unhandled Promise Rejection；
唯一找到的一个方法。是写动态路由时候给每个import加catch:
````js
export default [{
  // 登录
  path: '/login',
  component: () => import('../modules/common/login').catch(err => console.log(err)),
}]
````
但是这样很繁琐，没法集中处理错误；
问下大神有什么好的处理方式吗

**Comment by sorrycc** [comment]
写个方法封装起来，每个地方统一调不就好了？

**Comment by xioozq** [comment]
@sorrycc 错误以后的处理写一下倒无所谓，主要是错误的捕获，不能集中捕获，也就是 每个异步组件都需要在import(xxx)后面加.catch，然后执行处理，这个过程貌似没法省掉

**Comment by sorrycc** [comment]
`import(xxx)` 返回的是 Promise，一样可以封装的。

**Comment by xioozq** [comment]
@sorrycc 明白了，感谢～～ 之前思路错了，总想把path从import()里抽出来但是不行，现在当作一个整体处理就好说了 😂
