### ISSUE TITLE
关于redux 的使用问题？是否有必要使用redux?

### ISSUE THREAD

**Issue by liubin915249126** [dvajs/dva#1518]
情况是这样的：1.我现在会将两个组件(A,B)放置在同一个父组件(p)下面，通过父组件(p)的state来传递数据，实现组件间数据共享，具体流程:B组件触发父组件P传递下来的事件作出相应的动作继而setState(新的state数据可能是B组件传递的值，也有可能是父组件拿到值之后请求得到的数据)然后将state传递给A组件，A组件进行页面更新。
2.关于发送请求的地方，按照我上面说的，我在组件里面比如(componentDidMount,componentWillReceiveProps)里面直接调用封装的request(没有走redux,saga),
然后setState,进而更新页面。
3.尽量不用redux，除非组件嵌套太深，并且需要组件间共享数据时再用。
想问下这种作法是否可行，和redux那套做法有什么优缺点，因为公司同事一直在吐槽我的写法。
希望得到大神解答

**Comment by yvanwangl** [comment]
@liubin915249126 一些个人观点：
> 这么做是否可行
这么做写个可以运行的 demo 可行，但是如果是多人协作的应用开发，这么做会有以 7 下不妥：
1、没有使用 redux， 所以 redux 所有的优势你都无法体验，例如 time travel、函数式 reducer、不可变 等，及 react-redux 的性能优化。
2、应用的数据散落在各个父组件的 state 中，不便于数据的集中维护及调试
3、调用 setState 更新数据是异步的，所有数据的更新会变得不可控
4、按照软件设计的 MVC 框架来说，这种做法就是将 MVC 完美的耦合在一起
5、如果多个组件共享数据只能被包在一个父组件下，如果有一些全局的数据配置，还是要回到全局状态管理
6、违背 react 的设计初衷，react 就是一个视图层，现在确把所有的数据和逻辑都侵入到react中
7、无法写单元测试
...

> 和redux那套做法有什么优缺点
优点只有一个，你开心就好 : )

**Comment by liubin915249126** [comment]
找到官方关于我这种做法的解释
[https://reactjs.org/docs/lifting-state-up.html#lifting-state-up](lifting-state-up)

**Comment by zjxpcyc** [comment]
我觉得，这得分你的项目，跟团队合作的问题。如果你自己搞，或者项目小。你的方法是便捷可行的。

但是团队合作跟稍微大点的项目，你的方式就不合适了。因为，不是每个人都会按照你说的约定去写，每个人都有自己的 state 处理方式，这样会导致大家写的要么地方不一样，要么方式不一样。state 的状态基本上就没有办法去跟踪，甚至可能会出现死循环。

个人，还是偏向有规则的方式去写，如果放到组件里面，我可能自己都会被套进去，我到底哪里出现了问题。我们之前用 vue 开发，state 的管理就基本属于你说的情况，后来上了 vuex 就是类似 redux 才好转的。
