### ISSUE TITLE
做getting-started，demo的时候，当我设置effect为delay的时候，点击加号按钮的时候，current的值会变为-1这样不断减小

### ISSUE THREAD

**Issue by darrell0904** [dvajs/dva#1523]
#### Actual behavior: (实际效果)
全部代码复制到我本地之后，单击加号，current变为-1，recode不变。

**Comment by cqcmdwym** [comment]
{
  "private": true,
  "dependencies": {
    "dva": "^2.1.0",
    "keymaster": "^1.6.2",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "roadhog": "^2.0.0"
  },
  "scripts": {
    "start": "roadhog server",
    "build": "roadhog build"
  }
}
我也遇到了类似的问题，是不是版本的问题，add的reducer未触发
