### ISSUE TITLE
如何 监听 model 中 state的变化 

### ISSUE THREAD

**Issue by wkm-wangZhe** [dvajs/dva#1531]
有一个需求 需要监听state的变化 的 然后存入缓存 中

这是 VUE 中的实现方式

store.subscribe((mutation, { task_pyramid }) => {

localStorage.setItem('PYRAMIDTASK', JSON.stringify(task_pyramid.pyramid_list));
})

不知道 在dva.js 如何实现类似的效果

**Comment by jnotnull** [comment]
是啥导致state的变化呢

**Comment by yzzting** [comment]
改变stare只能是reducer里面的某个方法

**Comment by sorrycc** [comment]
可以在 onStateChange hook 里做，https://github.com/dvajs/dva/blob/master/docs/API.md#onstatechangefn
