### ISSUE TITLE
model如果不声明reducers字段的话，route component获取不到这个model

### ISSUE THREAD

**Issue by HuangFJ** [dvajs/dva#1534]
Model文件`models/test.js`如下：
```js
export default {
    namespace: 'test',
    state: {
        count: 1
    },
}
```

Route Component文件`routes/test/index.js`如下：
```js
import React from 'react';
import { connect } from 'dva';

const Test = (all) => {
    console.log(all);
    return ( <div></div> );
};

export default connect(({...args})=>({...args}))(Test);
```

其他的props都能获取，就是获取不到test的model。后来在model文件中加上reducers的声明才可以：
```js
export default {
    namespace: 'test',
    state: {
        count: 1
    },
    reducers: { },
}
```
不知道这算不算bug，不过确实被这个问题折腾了一会。

**Comment by yvanwangl** [comment]
@HuangFJ 这个不是bug， dva 在用 redux 注册 reducer 的时候，会判断 model.reducers 是否存在，只有存在的情况下，才会注册，再有 redux 的状态树是根据 reducer 构建的，如果没有reducer 在 store 中自然就没有，所以你通过 connect 获取 state 中自然就没有 test。

**Comment by dgeibi** [comment]
我认为是bug，原因如下：

调用 getReducer 有默认的 reducers  `{}`
https://github.com/dvajs/dva/blob/master/packages/dva-core/src/getReducer.js#L9

start 方法并没有判断 reducers 的有无，用了默认 reducers
https://github.com/dvajs/dva/blob/master/packages/dva-core/src/index.js#L148-L151

但调用 start 后，app.model 用 injectModel，无reducers的情况下不会生成新的 reducer
https://github.com/dvajs/dva/blob/master/packages/dva-core/src/index.js#L77-L80

see: https://github.com/dvajs/dva/pull/1473

**Comment by mengwuhen** [comment]
我也遇到这个问题了，
