### ISSUE TITLE
React Router无法渲染页面

### ISSUE THREAD

**Issue by leftluoyi** [dvajs/dva#1535]
使用的dva@2.1.0，在index.js中加入了
```
import createHistory from 'history/createBrowserHistory';

const app = dva({
  history: createHistory()
});
```
下面这个程序是可以执行并且正常显示的。
```
<BrowserRouter>
  <Layout className={styles.layout}>
    <Switch>
      <Route exact path="/app" component={IndexPage}/>
    </Switch>
  </Layout>
</BrowserRouter>
```

但是出现了两个问题：
1. 如果把`<Route exact path="/app" component={IndexPage}/>`改成`<Route exact path="/index" component={IndexPage}/>`，访问对应页面则会出现下图错误

![image](https://user-images.githubusercontent.com/7591374/36839121-12942290-1d7c-11e8-8d17-26763cea5642.png)

2. 如果把`<Route exact path="/app" component={IndexPage}/>`改成`<Route exact path="/app/general" component={IndexPage}/>`，访问对应页面则会出现`Uncaught SyntaxError: Unexpected token <`错误。

其他自动生成的代码没有修改。

怎么解决呢？

**Comment by liuhuihao** [comment]
修改index.html文件将js引入地址修改为/index.js
