### ISSUE TITLE
Where  the details of subscriptions.

### ISSUE THREAD

**Issue by xgj1988** [dvajs/dva#1537]
I can't find details of **subscriptions** in the docs. [https://github.com/dvajs/dva-docs/blob/master/v1/zh-cn/concepts.md](url)

I found difference code of  **subscriptions**  bind key board event. The code is below:
`subscriptions: {
    keyboardWatcher({dispatch}) {
      key('⌘+up, ctrl+up', () => {
        dispatch({type: 'add'})
      });
    },
  }`

`subscriptions: {
    keyEvent({dispatch}) {
      key('⌘+up, ctrl+up', () => {
        dispatch({type: 'add'})
      });
    },
  }`

They are have the same function ,but the key of subscriptions is different.
What's does the key which name is 'setup' mean? I see the code and I can guess the function. But where the docs of explains these parameters,function note ,etc.

**Comment by yvanwangl** [comment]
@xgj1988 Here is [doc about subscriptions](https://github.com/dvajs/dva-knowledgemap/blob/master/README_en.md#subscription)
