### ISSUE TITLE
   "dva": "^1.4.0-beta.1"  和   "dva": "^2.1.0"  两个版本的路由问题

### ISSUE THREAD

**Issue by xgj1988** [dvajs/dva#1538]
"dva": "^1.4.0-beta.1" 的路由方法history.listen 里面 的参数是  
`history.listen(({ pathname, query }) => {}));  (pathname和query)`
但是在    "dva": "^2.1.0" 
参数就只有 pathname 

那么我的问题是，以前我请求的地址是/users?id=1。是可以通过query来获取的，但是现在因为只有pathname，我如何获取后面带的参数呢？

**Comment by xgj1988** [comment]
虽然可以search 参数获取到?id=1，但是还是没有以前的query好用，以前的老版本是用json格式解析出来的，现在是一个字符串，自己还要去解析这个字符串，有更好的办法吗？

**Comment by SuperNaturalGit** [comment]
应该不是dva2.x的问题，是react router4.x的改动。建议用query-string这个包去解析search串，就能拿到你想要的json对象。

**Comment by xgj1988** [comment]
@SuperNaturalGit  好的。谢谢

**Comment by tsejx** [comment]
@eonezhang 可以参考一下这里 [https://www.npmjs.com/package/query-string](url)

**Comment by xgj1988** [comment]
@tsejx  @SuperNaturalGit  3Q
