### ISSUE TITLE
webpackrc  和 roadhogrc 是不同roadhog的不同说明文件吗？

### ISSUE THREAD

**Issue by xgj1988** [dvajs/dva#1539]
webpackrc  和 roadhogrc 是不同roadhog的不同说明文件吗？ 用新的dva new出来的项目没有 roadhogrc文件，只有webpackrc文件，而且webpackrc文件里面什么都没有 还有 -rc 这个后缀是什么意思呢？谢谢。

**Comment by sorrycc** [comment]
roadhog@1 用的 .roadhogrc，roadhog@2 用的 .webpackrc 。

**Comment by xgj1988** [comment]
那么以前 webstorm 有roadhogrc这个配置文件的插件，新版的 webpackrc有 webstorm 插件吗？
