### ISSUE TITLE
css样式怎么动态加载呢？现在是直接全部合并成一个index.css

### ISSUE THREAD

**Issue by bibiehy** [dvajs/dva#1543]
dva@2.1.0
roadhog@2.2.0

import dynamic from 'dva/dynamic';
路由是用dynamic方法动态创建的，css写在component里面
在开发环境切换路由可以看到css是组件引用哪个就加载哪个
在build后，合并生成一个index.css文件了，有办法按需加载嘛

**Comment by wyj580231** [comment]
请问js怎么动态加载的?

**Comment by bibiehy** [comment]
@wyj580231 看一下官方文档
https://github.com/dvajs/dva/blob/master/docs/API_zh-CN.md
dva/dynamic部分

**Comment by sorrycc** [comment]
css 按需加载比较麻烦，但是是有方案的。参考 umijs/umi#8
