### ISSUE TITLE
umi + dva，完成用户管理的 CURD...启动出现umi' 不是内部或外部命令

### ISSUE THREAD

**Issue by lty6429** [dvajs/dva#1546]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
>npm i dva-cli@next -g
dva -v
dva-cli version 1.0.0-bea.2

>dva new user-dashboard
cd user-dashboard
npm start

#### Expected behavior: (预期的正常效果)
能启动

#### Actual behavior: (实际效果)
启动时报错

>'umi' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: umi dev
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

前面以为是node_modules 依赖问题，后来把node_modules删除重新安装也会出现同样的错误
环境变量没问题
#### Versions of packages used: (哪个库的哪个版本出现的问题)
1.0.0-bea.2

**Comment by sorrycc** [comment]
非 dva 问题，检查下本地环境吧。

**Comment by lty6429** [comment]
已解决！
dva是安装在C盘，前面我新建的时候是在F盘新建，然后启动出现错误
在C盘新建就可以启动
*<strong>难道是因为这个？但是安装的时候是全局安装的</strong>*
待续...
