### ISSUE TITLE
dva 2.0 构建的项目中配置了 `proxy` 代理，在 `npm start` 中访问正常，使用 `npm  run build` 编译后用 nginx 代理不能访问后端API,请问这该如何处理？

### ISSUE THREAD

**Issue by boscheng** [dvajs/dva#1551]
## dva 2.0 构建的项目中配置了 `proxy` 代理，在 `npm start` 中访问正常，使用 `npm  run build` 编译后用 nginx 代理不能访问后端API,请问这该如何处理？
配置代码：
```json
  "proxy": {
    "/api": {
      "target": apiUrl,
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    }
  }
```
这是npm start 访问的信息：
![image](https://user-images.githubusercontent.com/17395520/37193971-fddbe87a-23a6-11e8-8997-cad3a25a4206.png)
这是 npm run build 访问的信息：
![image](https://user-images.githubusercontent.com/17395520/37194009-20e5a7ca-23a7-11e8-9ee4-d12c1b787bbe.png)

**Comment by haiing** [comment]
你好，我也遇到了，请问解决了吗？？
