### ISSUE TITLE
dva-cli新建项目在chrome里面调试source里面的代码为什么不是es6的源码？

### ISSUE THREAD

**Issue by zhangzhi93** [dvajs/dva#1553]
请问一下dva-cli生成的项目，在chrome调试的时候source里面为什么不是es6源码而是转成es5之后的代码？看了下dva已经内置了devtool。
webpackrc配置：
`{
    "extraBabelPlugins": [
        ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]
    ],
    "devtool":"source-map"
}`
react相关代码：
`const Apps = () => (
    <ul className={styles.app_list}>
        <li>
            <Link to="/apps/1">Application1</Link>：<Link to="/apps/1/detail">Detail</Link>
        </li>
        <li>
            <Link to="/apps/2">Application2</Link>：<Link to="/apps/2/detail">Detail</Link>
        </li>
    </ul>
);`

![image](https://user-images.githubusercontent.com/16435301/37269907-80d2fd74-2607-11e8-9131-902a85cfe611.png)

**Comment by wufanglan** [comment]
我也发现了 对于断点调试非常不友好

**Comment by sorrycc** [comment]
在 roadhog 最新版里已修复的。

**Comment by Sir0xb** [comment]
比较愚钝，在 webpackrc 和 roadhogrc 里都配置过，都是定义到唯一一个压缩后的文件的同一个地方，所有错误都是。有没有可以参考的解决方案？
