### ISSUE TITLE
[建议]直接通过dispatch.modelName.effect[reducer](payload)来调用方法

### ISSUE THREAD

**Issue by jimlaren** [dvajs/dva#1556]
再rematch上看到了这个实现，这种方式调用比较符合方法调用习惯，通过dispatch({ type: 'count/increment', payload: 1 })这种方式太繁琐了，不知道是否可以改进。

import { dispatch } from '@rematch/core'
// state = { count: 0 }
// reducers
dispatch({ type: 'count/increment', payload: 1 }) // state = { count: 1 }  【繁琐】
dispatch.count.increment(1)                       // state = { count: 2 }  【舒服】

**Comment by jimlaren** [comment]
`// wrapper of dynamic
const dynamicWrapper = (app, models, component) => {
  if (component.toString().indexOf('.then(') < 0) {
    models.forEach((model) => {
      if (modelNotExisted(app, model)) {
        // eslint-disable-next-line
        app.model(require(`../models/${model}`).default);
      }
    });
    return (props) => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return createElement(component().default, {
        ...props,
        routerData: routerDataCache,
      });
    };
  }
  loadActions(app);
  // () => import('module')
  return dynamic({
    app,
    models: () => models.filter(
      model => modelNotExisted(app, model)).map((m) => {
      const model = require(`../models/${m}`).default;
      addModelAction(app, model);
      return model;
    }),
    // add routerData prop
    component: () => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return component().then((raw) => {
        const Component = raw.default || raw;
        return props => createElement(Component, {
          ...props,
          routerData: routerDataCache,
        });
      });
    },
  });
};
const loadActions = (app) => {
  app._models.filter(model => model.name !== '@@dva').forEach((model) => {
    addModelAction(app, model);
  });
};
const addModelAction = (app, model) => {
  const { dispatch } = app._store;
  const modelNameSpace = model.namespace;
  if (dispatch[modelNameSpace]) {
    return;
  }
  dispatch[modelNameSpace] = {};
  Object.keys(model.reducers || {}).forEach((reducer) => {
    const { name } = model.reducers[reducer];
    dispatch[modelNameSpace][name] = createDispatcher(dispatch, modelNameSpace, name);
  });
  Object.keys(model.effects || {}).forEach((effect) => {
    const { name } = model.effects[effect];
    dispatch[modelNameSpace][name] = createDispatcher(dispatch, modelNameSpace, name);
  });
};
const createDispatcher = (dispatch, modelName, reducerName) => {
  return (payload) => {
    dispatch({
      type: `${modelName}/${reducerName}`,
      payload,
    });
  };
};`

**Comment by jimlaren** [comment]
已经实现个简单版本，通过修改common/router.js里的动态加载来实现了这个功能。
<pre>
// wrapper of dynamic
const dynamicWrapper = (app, models, component) => {
  if (component.toString().indexOf('.then(') < 0) {
    models.forEach((model) => {
      if (modelNotExisted(app, model)) {
        // eslint-disable-next-line
        app.model(require(`../models/${model}`).default);
      }
    });
    return (props) => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return createElement(component().default, {
        ...props,
        routerData: routerDataCache,
      });
    };
  }
  loadActions(app);
  // () => import('module')
  return dynamic({
    app,
    models: () => models.filter(
      model => modelNotExisted(app, model)).map((m) => {
      const model = require(`../models/${m}`).default;
      addModelAction(app, model);
      return model;
    }),
    // add routerData prop
    component: () => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return component().then((raw) => {
        const Component = raw.default || raw;
        return props => createElement(Component, {
          ...props,
          routerData: routerDataCache,
        });
      });
    },
  });
};
const loadActions = (app) => {
  app._models.filter(model => model.name !== '@@dva').forEach((model) => {
    addModelAction(app, model);
  });
};
const addModelAction = (app, model) => {
  const { dispatch } = app._store;
  const modelNameSpace = model.namespace;
  if (dispatch[modelNameSpace]) {
    return;
  }
  dispatch[modelNameSpace] = {};
  Object.keys(model.reducers || {}).forEach((reducer) => {
    const { name } = model.reducers[reducer];
    dispatch[modelNameSpace][name] = createDispatcher(dispatch, modelNameSpace, name);
  });
  Object.keys(model.effects || {}).forEach((effect) => {
    const { name } = model.effects[effect];
    dispatch[modelNameSpace][name] = createDispatcher(dispatch, modelNameSpace, name);
  });
};
const createDispatcher = (dispatch, modelName, reducerName) => {
  return (payload) => {
    dispatch({
      type: `${modelName}/${reducerName}`,
      payload,
    });
  };
};
</pre>

**Comment by jimlaren** [comment]
本来想通过插件，插件调用的参数好像访问不到store，只好通过这个方式来实现了。

**Comment by zjxpcyc** [comment]
如果按照这个思路扩展的话， [vuex](https://vuex.vuejs.org/zh-cn/api.html) 的 mapActions 这种方式不是更好。

也不需要 `dispatch.count.increment(1)`, 就是直接  `increment(1)`

**Comment by jimlaren** [comment]
此方法build后会找不到函数定义，还在寻找更好的办法。
