### ISSUE TITLE
项目是webpack+dva，请问不用roadhog怎么配置webpack的dva热更新 

### ISSUE THREAD

**Issue by hushiyi** [dvajs/dva#1558]
问题如题，在roadhog已经提过，比较着急再dva又骚扰大神一遍望见谅。

**Comment by xioozq** [comment]
webpack-dev-middleware
webpack-hot-middleware
看这两个的文档，一起用，然后再加上dva-hmr的babel-plugin

**Comment by hushiyi** [comment]
谢谢 ，没有用express，因为项目用的webpack-dev-server，babelIrc里面这样配置能实现react 的hmr生效。但是对于使用@connect(state => ({
  login: state.login
})) connect的组件，会把所有的数据都清掉。
{
  "plugins": [
    ["import", { "libraryName": "antd-mobile", "style": "css" }],
    "transform-runtime",
    "transform-decorators-legacy",
    "transform-class-properties"
   ],
  "presets": [
    [
     "es2015", 
     { "modules": false ,"loose": false},
    ],
    "react",
    "stage-0"
  ],
  "env": { 
    "development": { 
      "presets": [ 
        "react-hmre" 
      ] 
    } 
  } 
}

**Comment by vipcxj** [comment]
所以最后有没有搞定？

**Comment by dickeylth** [comment]
同遇到 
> 对于使用@connect(state => ({
> login: state.login
> })) connect的组件，会把所有的数据都清掉。

只用 dva 不用 roadhog 有没有什么解决方案？

**Comment by hustyxl** [comment]
不用roadhog，connect数据清空，最后有解决吗？

**Comment by hustyxl** [comment]
> 谢谢 ，没有用express，因为项目用的webpack-dev-server，babelIrc里面这样配置能实现react 的hmr生效。但是对于使用@connect(state => ({
> login: state.login
> })) connect的组件，会把所有的数据都清掉。
> {
> "plugins": [
> ["import", { "libraryName": "antd-mobile", "style": "css" }],
> "transform-runtime",
> "transform-decorators-legacy",
> "transform-class-properties"
> ],
> "presets": [
> [
> "es2015",
> { "modules": false ,"loose": false},
> ],
> "react",
> "stage-0"
> ],
> "env": {
> "development": {
> "presets": [
> "react-hmre"
> ]
> }
> }
> }

大佬解决了吗，目前在升级roadhog+dva老项目，roadhog社区已经暂停维护了，升级成webpack5，打包成功，但是页面报错，connect中的数据都为undefined
