### ISSUE TITLE
动态加载Model和Route导致的一个问题

### ISSUE THREAD

**Issue by fred1218** [dvajs/dva#1559]
动态加载不错，加快访问速度，减少打包体积，但是：
使用的是dynamic import

所以，在路由加载的时候，动态加载路由对应的组件和model时候，组件都会重新生成，而不是re-render，即使某个组件已经有了，但路由变更的时候，依然会被重新创建。

这就导致复杂交互的页面（pc端），state丢失等等（相当于按了f5）。

请问大神：这种问题如何解决？还是pc端这种复杂交互，就不适合使用dynamic import来加载组件

**Comment by sorrycc** [comment]
state 保存在 dva store 里，路由变更的时候应该在的吧。

**Comment by fred1218** [comment]
是这个场景：比如我左边是很长的menu，我滚动到了最后，点击其中一个item，在右边打开这个对应的视图，当然url也会变，这个时候，左边的滚动条就回到了顶（top）。这就是问题，因为左边这个menu被重新创建生成了，是个新的了，而不是刚才滚动的那个~~~在constructor中打日志可以看到执行了constructor

**Comment by sorrycc** [comment]
那就想办法让左边的不要重新渲染，比如把他挪到 `<Router>` 外面。

**Comment by fred1218** [comment]
比如左边的menu也会是在某个路由下才会出现的菜单~~这就尴尬了

**Comment by sorrycc** [comment]
这是 react-router 的使用问题，翻翻他的文档和 issue 看吧，这里先关了。

**Comment by HuangFJ** [comment]
和 [https://github.com/dvajs/dva/issues/1514](https://github.com/dvajs/dva/issues/1514) 应该是同一个问题。我也遇到过，后来用react-loadable替换dva/dynamic就不会了。只是这样的话，只能预先把model全都注册给dva对象。
