### ISSUE TITLE
dva-cli 1.0版本 中文路径构建出来的项目无法运行

### ISSUE THREAD

**Issue by NexxLuo** [dvajs/dva#1561]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
1. dva-cli创建项目 ： dva new 中文demo
2.npm start

#### Expected behavior: (预期的正常效果)

正常访问localhost:8000,显示首页

#### Actual behavior: (实际效果)

启动报错：

Module not found: Can't resolve 'e:WebRootSolution1MyWebSitedva中文demo

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva-cli version 1.0.0-bea.2
    dva version 2.1.0

**Comment by sorrycc** [comment]
英文路径可以？

**Comment by NexxLuo** [comment]
英文路径可以

**Comment by sorrycc** [comment]
在 https://github.com/umijs/umi/issues/214 跟进。
