### ISSUE TITLE
antd-pro中使用yield call获取返回的数据为udnefined

### ISSUE THREAD

**Issue by naWang1227** [dvajs/dva#1565]
代码如下：
![default](https://user-images.githubusercontent.com/25194203/37501386-2aee0ad4-2909-11e8-90ef-20e1ec6b4c6f.png)
![default](https://user-images.githubusercontent.com/25194203/37501365-10d23d28-2909-11e8-861b-150c71fd3e6a.png)
![default](https://user-images.githubusercontent.com/25194203/37501334-e565a9fe-2908-11e8-9425-169876cff087.png)
![default](https://user-images.githubusercontent.com/25194203/37501337-ee6b1048-2908-11e8-8a95-b15e880941e1.png)
![default](https://user-images.githubusercontent.com/25194203/37501350-ffe26038-2908-11e8-80a5-45e80eb2ec23.png)

问题描述：fetch请求返回的response.json()中是拿到数据了的，但是在yield call 操作却无法获得数据

**Comment by JYDwayne** [comment]
是不是跨域,试试使用fetch-jsonp代替fetch
