### ISSUE TITLE
请问一下dva在model层怎么发请求(model中其中一个js调用另一个js，effects中的方法)

### ISSUE THREAD

**Issue by curry-wxj** [dvajs/dva#1568]
* deleteTree({ payload }, { call }) {
      const res = yield call(
        deleteTree,  
        { areaId: payload.areaId },
      );
       if (res.success) {  //删除成功
         //这里 需要再次发送请求 渲染页面
      }
},
解决方法我所知道的就只有 进rander方法里发请求,或者 回调的形式, 但都不太符合dva的规范，打破了数据的流向。
请问一下dva可以在model 调用 其他model.js中effects中的方法吗

**Comment by codering** [comment]
完全可以啊

**Comment by curry-wxj** [comment]
@codering  请问一下 如何实现了

**Comment by ishenli** [comment]
加个namespace，比如model A 直接调用model B的effect
```js
yield put({
   type: 'modelB/effectMethod',
})`

**Comment by curry-wxj** [comment]
好的，已解决！

**Comment by yoyo837** [comment]
如果要获得返回结果呢

**Comment by yoyo837** [comment]
不存储state的
