### ISSUE TITLE
升级到dva2.0之后，无法使用routerRedux.push进行跳转？

### ISSUE THREAD

**Issue by yeelone** [dvajs/dva#1569]
最近升级到dva2之后，项目总算跑起来了，但还有一个问题折腾了一个晚上没有解决，不明白原因在哪里。
升级到dva2之后，我原先使用routerRedux.push进行跳转不起作用了。
代码如下：
[app 入口代码](https://github.com/yeelone/yeetiku-admin/blob/master/src/index.js)

[routes代码 ](https://github.com/yeelone/yeetiku-admin/blob/master/src/routes/questions/index.js)

```
onPageChange (page) {
      dispatch(routerRedux.push({
        pathname,
        query: {
          ...query,
          page: page.current,
          pageSize: page.pageSize
        },
      }))
    },
```
[models代码](https://github.com/yeelone/yeetiku-admin/blob/master/src/models/questions.js)
```
subscriptions: {
    setup ({ dispatch, history }) {
      history.listen( ({pathname,search}) => {    //search永远为空
        var query = queryString.parse(location.search)

        if (pathname === '/admin/questions'  ) {
          dispatch({
            type: 'query',
            payload: query,
          })
        }
      })
    },
  },
```

** 我期待的是 ： 使用routerRedux.push,url 会变成 /admin/questions?page=1&pageSize=20 
但是现在 url 始终为  /admin/questions ，无法传递参数。

请问问题在哪里呢？如何去解决呢？
非常希望能够得到回复，谢谢。

**Comment by yeelone** [comment]
明白了。
参考：https://github.com/ReactTraining/history/blob/v3/docs/Location.md

解决如下：
```
dispatch(routerRedux.push({
        pathname: '/admin/questions',
        search:'?field='+fieldsValue.field+'&keyword='+fieldsValue.keyword
      }))
```

**Comment by ybning** [comment]
```
    handleStandardTableChange = (pagination, filtersArg, sorter) => {
        let { current, pageSize } = pagination;
        this.props.dispatch(
            routerRedux.push({
                pathname: '/order/list',
                query: { curPage:current, pageSize },
            })
        );
    }
```
![image](https://user-images.githubusercontent.com/3725612/42159224-887eec1a-7e25-11e8-82f4-7da8b254f83e.png)

取不到query，是啥问题？
@yeelone
