### ISSUE TITLE
请问一下dva  model层里面的js文件如何互相调用请求

### ISSUE THREAD

**Issue by curry-wxj** [dvajs/dva#1570]
*deleteTree({ payload }, { call }) {
const res = yield call(
    deleteTree,
    { areaId: payload.areaId },
);
if (res.success) {  // 删除成功
    //这里需要调用请求 *updataTree
}
},

**Comment by jincan39** [comment]
推荐写法：  this.props.dispatch({
        type: 'tree/deleteTree',
       }).then(()=>{
    this.props.dispatch({type: 'tree/updataTree',}) 
})
