### ISSUE TITLE
求教dva中如何实现js按需加载的(示例地址失效了)

### ISSUE THREAD

**Issue by wyj580231** [dvajs/dva#1571]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
项目比较复杂,请问如何实现js文件按需加载的,先在是整个打包到一个index.js中了,dva官网的示例地址访问不了了,网上找的也没起作用,请教各位前辈.谢谢

**Comment by sorrycc** [comment]
google `webpack code splitting`.
