### ISSUE TITLE
umi 中怎么引用redux-persist

### ISSUE THREAD

**Issue by yuhaoz** [dvajs/dva#1573]
之前在dva 中，引用 redux-persist的方式如下
import { persistStore, autoRehydrate } from 'redux-persist';
const app = dva({
  extraEnhancers: [autoRehydrate()],
});
persistStore(app._store);

现在改用umi后，不用app=dva() 来创建实例，该如何引入？

**Comment by sorrycc** [comment]
在 umijs/umi#249 跟进。
