### ISSUE TITLE
dva源码阅读, sagaWithCatch中为什么使用yield而不是yield*

### ISSUE THREAD

**Issue by bj75326** [dvajs/dva#1575]
<pre><code>
function *sagaWithCatch(...args) {
    try {
      yield sagaEffects.put({ type: `${key}${NAMESPACE_SEP}@@start` });
      const ret = yield effect(...args.concat(createEffects(model)));
      yield sagaEffects.put({ type: `${key}${NAMESPACE_SEP}@@end` });
      resolve(key, ret);
    } catch (e) {
      onError(e);
      if (!e._dontReject) {
        reject(key, e);
      }
    }
  }
</code></pre>
yield* 可以将next委托给effect，yield不行，getSaga中返回的effect函数为什么使用的是yield..

**Comment by hopperhuang** [comment]
yield * 是自动执行generator函数了，而且要求yield * 后面的函数全部都是generator, yield是返回一个后面执行函数的结果，然后把这个执行结果交给redux-saga的执行器去判断，需要多结果做什么样子的操作。
