### ISSUE TITLE
dva中如何获取一个div的height，这个div的height是获取请求后遍历数据动态生成的input填充而来的

### ISSUE THREAD

**Issue by curry-wxj** [dvajs/dva#1576]
componentDidMount   ref 拿不到其真正的height,因为里面的内容是 发送请求 渲染后得到的，此时componentDidMount 已经执行过了。  我需要拿到这个div的高 然后setState 去改变另一个div的高，让两个div高相同。

**Comment by sorrycc** [comment]
这和 dva 无关啊。

**Comment by zjxpcyc** [comment]
dom 操作一般都是在 componentDidMount  里面写的。另一个 div 高度的问题，你也不用去 setState，直接在  componentDidMount  里面操作 ref 应该就可以的。

另外，两个 div 等高，如果是一行同排的这种布局，可以用 css flex 试试。

**Comment by curry-wxj** [comment]
好的 明白了 谢谢
