### ISSUE TITLE
dva 对 typescript 的支持

### ISSUE THREAD

**Issue by demohi** [dvajs/dva#1577]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
```js
  "files": [
    "lib",
    "src",
    "dist",
    "dynamic.js",
    "fetch.js",
    "index.js",
    "router.js",
    "saga.js"
  ]
```

#### Expected behavior: (预期的正常效果)
包含 *.d.ts 文件

#### Versions of packages used: (哪个库的哪个版本出现的问题)
^2

**Comment by EngsShi** [comment]
https://github.com/dvajs/dva/commit/fd32ee67e7b5263510fff38457e1485e1206e25b
打包未包含d.ts文件
