### ISSUE TITLE
关于dva的connect({login,loading})参数从哪里来的问题

### ISSUE THREAD

**Issue by helloiloveu** [dvajs/dva#1578]
大神好，请问关于connect({login,loading})，我的理解是login和loading都来自于store，但我不知道dva是如何组装store的，login我理解来自于model，但loading并不在model中，它是怎么到store里的呢？

**Comment by codering** [comment]
https://github.com/dvajs/dva-loading

**Comment by ybning** [comment]
@helloiloveu [https://github.com/dvajs/dva-knowledgemap#%E9%80%9A%E8%BF%87-connect-%E7%BB%91%E5%AE%9A%E6%95%B0%E6%8D%AE](https://github.com/dvajs/dva-knowledgemap#%E9%80%9A%E8%BF%87-connect-%E7%BB%91%E5%AE%9A%E6%95%B0%E6%8D%AE)
