### ISSUE TITLE
dva 如何配 .eslintignore ?

### ISSUE THREAD

**Issue by Vuchan** [dvajs/dva#1584]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
我在项目(基于ant-pro)中使用了第三方的编辑器，百度的 UEditor，当我引入文件的时候，出现了很多 eslint 的 error。在之前使用 vue-cli 的时候我可以使用 .eslintignore 文件，但是在 dva 的项目中，.eslingignore 却无法工作。

.eslingignore 文件内容：

```json
node_modules
src/ueditor/*.js
*.sh
```

#### Expected behavior: (预期的正常效果)
希望 .eslintignore 配置文件可以工作

#### Actual behavior: (实际效果)
.eslintignore 不工作

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva-cli version 0.9.2
    dva version 2.1.0
roadhog version 2.2.0

**Comment by sorrycc** [comment]
感觉和 dva 无关啊。

**Comment by Vuchan** [comment]
那么大佬，简单问就是 dva 中 .eslintignore 配置文件 如何生效？
