### ISSUE TITLE
effect返回promise catch 捕捉不到错误

### ISSUE THREAD

**Issue by hnsylitao** [dvajs/dva#1586]
catch并捕捉不到错误
只有在effect 用try catch 才能捕捉到

```js
  dispatch({
      type: 'product/list',
    })
  .then((data) => {
    console.log(data);
  })
  .catch((e) => {
    console.log(e);
  });
```

**Comment by lahvey** [comment]
```js
try {
  await dispatch(...);
} finally {
}
```
也发现这个问题，catch和finally都没执行，在effect里面可以try catch

**Comment by sorrycc** [comment]
是不是定义了 onError hook，被 onError catch 掉了？

**Comment by sorrycc** [comment]
有问题再 reopen 。

**Comment by hnsylitao** [comment]
没有全局onError ，不过现在有一个hack的写法
```js
const app = dva({
  onError(){}
});
```
这样写dispatch 调用的时候能够catch 到错误

**Comment by napalm272** [comment]
同样问题，必须得用@hnsylitao 说的hack

**Comment by napalm272** [comment]
dva版本 2.3.1

**Comment by dyf19118** [comment]
关注，dispatch的捕错与onError中e.preventDefault的冲突实在恼人。

**Comment by xiaobo1234** [comment]
关注 +1！
本来是想在某个 dispatch 中的 catch 进行业务处理，结果发现在 onError 中 e.preventDefault 之后，dispatch 的 catch 并没有调用，等于直接截断了业务处理逻辑。
如果不在 onError 中 e.preventDefault 的话，效果是达到预期了，但是没有加 catch 的 dispatch 在开发模式下就会有错误弹窗。
如果说要给所有的 dispatch 都添加 catch，代码又过于冗余。

PS：说到这儿，突然有个期望的效果：如果 dispatch 带有 catch 或者添加了错误回调之类的处理，就不调用 onError，否则就调用 onError。然而，不知道这样会不会引起其他问题。

**Comment by YinRenjie1993** [comment]
## 
# 
### ****__ 
``` 

``` 
` `

**Comment by 349989153** [comment]
@hnsylitao 感谢
