### ISSUE TITLE
model 的 namespace 必须和 文件名字同名吗？

### ISSUE THREAD

**Issue by xgj1988** [dvajs/dva#1588]
比如我的model 里面namespace 是 test,文件名子叫 helloTest.js 这样不行吗？

export default {
  namespace: 'test',
  .....
}

helloTest.js

**Comment by codering** [comment]
不是必须的

**Comment by billgo** [comment]
不是必须的，但是 namespace 得是唯一

**Comment by xgj1988** [comment]
@billgo  不是必须的 为什么我用antd pro 项目 会加载不到model呢？
