### ISSUE TITLE
请指导dva的模式下，数据请求的一些经验，或方案。

### ISSUE THREAD

**Issue by xjdata** [dvajs/dva#159]
菜鸟一枚，通过的dva才算对rudex有了直观的认识。感谢各位大神的无私。

我用dva+antd。我的疑惑是，后台系统，尤其是列表界面，对排序筛选等功能一般都会配套。 这个时候读取rest api获取的数据源， 比如我请求的时候20条一页。 后端可以进行本次的所有查询、过滤、排序条件进行当前的输出缓存。

但是前段呢？ 假设我查询、过滤、排序等所有的条件都不变化， 点击了第二页，之后又返回第一页。 这个时候我看http请求，以及我现在了解到的处理方式， 第一页的数据依然是全新的一次处理过程。 可以说没有利用到http缓存，不论是点击浏览器后退按钮还是手动指定到第一页数据。

请问这部分是否有什么好的处理方式呢？ 或者已经有了类似的解决方案，我还不了解？ 

请各位指导，谢谢。

**Comment by nikogu** [comment]
你可以把你的的状态变化通过参数带到请求上，让前后端状态同步，数据和展示就同步了

**Comment by xjdata** [comment]
![image](https://cloud.githubusercontent.com/assets/4524983/19353016/9e41add2-9194-11e6-91e2-165c84e0b6b8.png)
参数没变化的  我的意思是 在这些参数没变化的时候， 比如图片中的ico文件 就会从缓存加载什么的。
但是api的请求不可以。 

我个人理解（当然纯菜鸟，不对还请多多指导）。

类似dva-hacknews 那样，每次请求的时候多取一些回来比如一次拿100条，之后 分页，排序等本地进行。同时将不同参数的列表请求回来后存储在state中。model中自己维护一个逻辑，如果参数相同（或缓存时间内），走本地state中的数据，否则请求服务器。 

或者是我的经验实在太差， 后台系统中的这些列表本就应该是实时显示的。不应该考虑缓存等问题。（因为可能确实有业务操作造成了列表变动）。

或者根据实际的场景决定具体如何解决。比如数据变动不大的时候考虑缓存方式，频繁读写列表就直接实时方式。


没有类似的经验，还请各位多多指导，谢谢。

**Comment by nikogu** [comment]
额，你纠结的是缓存的问题吗，缓存有很多方案，从前端到后台到中间件到数据库，回到dva上面来，你可以做前端缓存的，专门做一个module做缓存，或者建一个 dva-plugin 来搞
