### ISSUE TITLE
roadhog build 打包项目 会报 JavaScript heap out of memory 

### ISSUE THREAD

**Issue by GONDON** [dvajs/dva#1598]
想知道问题出在哪里。

**Comment by GONDON** [comment]
报错信息如下：
<--- Last few GCs --->

[9245:0x102801c00]  1257383 ms: Mark-sweep 1419.8 (1676.8) -> 1419.7 (1676.8) MB, 1200.3 / 0.0 ms  allocation failure GC in old space requested
[9245:0x102801c00]  1258596 ms: Mark-sweep 1419.7 (1676.8) -> 1419.6 (1624.8) MB, 1212.6 / 0.0 ms  last resort GC in old space requested
[9245:0x102801c00]  1259811 ms: Mark-sweep 1419.6 (1624.8) -> 1419.6 (1603.8) MB, 1214.0 / 0.0 ms  last resort GC in old space requested

**Comment by GONDON** [comment]
报错信息：
<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x23bbae9a5ec1 <JSObject>
    0: builtin exit frame: stringify(this=0x23bbae989021 <Object map = 0x23bbca002ba1>,0x23bbe4002311 <undefined>,0x23bbe4002311 <undefined>,0x23bbfaabcda1 <Object map = 0x23bbe29e1109>)

    1: arguments adaptor frame: 1->3
    3: toString [0x23bbe4002311 <undefined>:8276] [bytecode=0x23bbf423bdb1 offset=28](this=0x23bb2c807701 <Object map = 0x23bbf3d584c9>)
    8: /* anonymous */ [/Volumes/wor...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [/usr/local/bin/node]
 7: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
 8: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
 9: v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
10: v8::internal::Builtin_Impl_JsonStringify(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x3f4f49c0441d
12: 0x3f4f49c05d1b
13: 0x3f4f49cf45fc

**Comment by GONDON** [comment]
是业务代码写的不好，让内存泄漏了，还是提高node的内存。还是说什么问题。因为业务环境的问题，roadhog@0.5.2，dva@1.2.1 都是较低版本的。

**Comment by syaivin** [comment]
@GONDON 我也一直被这问题给难到了，你有方法解决了吗？
