### ISSUE TITLE
希望框架能委托全局dom/bom事件

### ISSUE THREAD

**Issue by marginchan** [dvajs/dva#16]
在react ui组件里面要监听全局的dom事件很麻烦。
比如一个组件需要监听document点击的事件来判断是否点击的是自身， 现在的方案是要在该ui组件里实现一遍document click监听并判断， 如果一个页面上有多个不同组件有这样的监听需求，显得代码非常冗余。

不知道有没有更优雅的方法实现上面的需求。

如果框架能统一监听这些事件，并通过类似react的componentDidMounted（documentClicked）这样的钩子方法暴露给组件就好了。

并不止是click事件。

**Comment by marginchan** [comment]
redux只是提供了一个空的框框，react又只关注渲染
要么只让react做ui层， 如果引入框架的话倒是很希望框架能做这些事

**Comment by nikogu** [comment]
> 比如一个组件需要监听document点击的事件来判断是否点击的是自身， 现在的方案是要在该ui组件里实现一遍document click监听并判断， 如果一个页面上有多个不同组件有这样的监听需求，显得代码非常冗余

场景略显模糊，每个组件都是独立的，应该自身处理对应的事件，为什么要让全局监听呢

**Comment by marginchan** [comment]
@nikogu  比如：
我有一个table列表，列表的最后一栏是操作项，这个操作项有很多按钮我用了一个下拉把按钮收起来，每次点击这个下拉可以toggle展开或闭合。  这个下拉展开的时候，当我点击页面上其他任务一个地方，都需要把这个下拉闭合收起来。  
不仅操作栏有这样的下拉，表头有也这样的下拉（用于字段过滤）， 这些下拉整体是单例模式（同时只能有一个展开，点击页面上其他区域下拉都要收起来）

这些下拉又长得不一样，不是同一个组件，诸如此类的情况

**Comment by nikogu** [comment]
@marginchan 根据你的描述，合理的情况：

1. 下拉应该是一个组件，如果UI样子不一样其实是设置UI主题的，但是往往在设计规范的项目中，下拉的样式应该是统一的；
    - 可参考[antd组件](http://ant.design/components/dropdown)
2. 退一步讲，假设是一个组件，那么所有相关联操作就在此组件中，它的使用类似于：

```
const config = [
    {
        name: 'a',
        onClick: ()=>{}
    },
    ...
]
<DropDownButton buttons={config} />
```

组件内部只需要自己绑定一个全局事件去收起来即可，具体实现有很多种，比如

```
// 组件内部
componentDidMount(){  
    window. addEventListener('click', (e)=>{
        // 1. 可通过ref来判断
        // 2. 可通过id
        // ...
    })
}
```

所以此部分跟框架本身无关

**Comment by nikogu** [comment]
我的理解，在react项目中，`事件`是组件的行为，它应该是聚合在组件内部的，并不会像之前jquery项目中会有很多事件托管的情况出现

**Comment by nikogu** [comment]
@marginchan 是否解决你的问题，解决了请close一下issue :）
