### ISSUE TITLE
subscriptions中用什么方法可以获取到model中的state？

### ISSUE THREAD

**Issue by utali** [dvajs/dva#1600]
subscriptions中用什么方法可以获取到model中的state，需要将其作为参数传递

**Comment by sorrycc** [comment]
不能获取到，dispatch 一个 action，然后在 effect 里获取 state 以及做其他的处理。

**Comment by eggachecat** [comment]
@sorrycc 大大好,可以请问以下场景如何解决吗?: 有一个在全局state里的变量叫A_ID, 当A_ID变化的时候, 某个websocket需要重新初始化(ws的url用到了A_ID), 此时好像就是订阅了A_ID? (并且这个A_ID并不在pathname中所以history的事件帮不上忙)
