### ISSUE TITLE
state 更新后，组件没有重新渲染

### ISSUE THREAD

**Issue by Nothingexp** [dvajs/dva#1601]
![image](https://user-images.githubusercontent.com/21405348/38483137-74a9bd4a-3c04-11e8-8dc9-9fa2d10ca9d8.png)
![image](https://user-images.githubusercontent.com/21405348/38483164-9437c0f8-3c04-11e8-8f7c-b09ddd0837bd.png)

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

changeState 更新 state 后，组件没有更新

**Comment by sorrycc** [comment]
检查下代码，绑的数据不对，或者更新的方式不对。这个基本流程由 redux 保证，应该是不会有问题的。

**Comment by Nothingexp** [comment]
多次确认绑定的数据是无误的，但是在请求数据时改变 state 又能重新渲染组件
![image](https://user-images.githubusercontent.com/21405348/38484835-6c35d5d0-3c0a-11e8-8baf-640c43e434bc.png)
