### ISSUE TITLE
build发布后控制台显示的文件大小远小于文件的实际大小

### ISSUE THREAD

**Issue by wyj580231** [dvajs/dva#1606]
![Uploading C7A3F511-4A13-4781-9209-FFE774B5F618.png…]()

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
npm run build打包,控制台显示 js文件468kb , css文件31kb.
而实际文件js有1.7m , css也有200多kb.
请问是显示bug还是操作有问题?

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva 2.1 
roadhog 2.0.0

**Comment by sorrycc** [comment]
显示的是 gzip 之后的尺寸。

**Comment by wyj580231** [comment]
解决了,非常感谢
