### ISSUE TITLE
  "dva": "^2.2.0"报 Module not found: Can't resolve '@babel/runtime/helpers/objectSpread

### ISSUE THREAD

**Issue by hzq001** [dvajs/dva#1613]
升级    "dva": "^2.2.0",

 ./node_modules/dva-core/lib/index.js
Module not found: Can't resolve '@babel/runtime/helpers/objectSpread

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
删除 node_modules， 重新使用 安装还是出现改问题

#### Versions of packages used: (哪个库的哪个版本出现的问题)

 "dva": "^2.2.0"

**Comment by sorrycc** [comment]
如何重现？

**Comment by hzq001** [comment]
应该是 yarn.lock 文件 依赖的问题，我删除该文件再重新下载包文件就没问题了。

**Comment by sorrycc** [comment]
更新方法不对？

**Comment by TDiDa** [comment]
@sorrycc 删除 node_modules，还是有这问题， 在部署的时候出现的

**Comment by sorrycc** [comment]
感觉还是 lock 的问题，试试用 npm ？检查过 dva 和 dva-core 的依赖，都是有 `@babel/runtime` 的依赖的。

**Comment by TDiDa** [comment]
使用cnpm就可以了

**Comment by Renderz** [comment]
@TDiDa 出现同样问题,删掉package-lock.json和node_modules, 重新安装解决...

**Comment by huandie2012** [comment]
Module not found: Can't resolve 'dva/index' in ''
'dva/index'也是一个模块吗？
