### ISSUE TITLE
浏览器直接访问形如"/a/b"这样的多级browserhistory路由会报错

### ISSUE THREAD

**Issue by HuangFJ** [dvajs/dva#1614]
dva版本2.2.2，nodejs版本v8.11.1。
我用`dva new myapp`，然后只对src/index.js和src/router.js两个文件做微小改动。
src/index.js文件新增一行import并改了dva配置使之支持browserhistory：
```js
...
import createHistory from 'history/createBrowserHistory';

// 1. Initialize
const app = dva({
    history: createHistory(),
});
...
```

src/router.js文件新增一行Route：
```js
...
        <Route path="/a/b" exact component={IndexPage} />
...
```
然后`npm start`启动。
页面里面加`<Link to="/a/b">hell</Link>`跳转是正常的。
但是如果用浏览器直接访问或刷新`http://localhost:8000/a/b`就报错，控制台提示："Uncaught SyntaxError: Unexpected token <"。
后来试了一下，凡是url path是多级的，浏览器直接访问都会出错。。

还请社区帮忙看一下是哪里问题，还是说我的写法不对。

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva-cli/blob/master/boilerplates/app/public/index.html#L12
这里的 index.js 改成 /index.js

**Comment by HuangFJ** [comment]
可以了，谢谢你！

**Comment by haohailong1990** [comment]
> https://github.com/dvajs/dva-cli/blob/master/boilerplates/app/public/index.html#L12
> 这里的 index.js 改成 /index.js
你好啊，改成这个还是报错呀

**Comment by haohailong1990** [comment]
> https://github.com/dvajs/dva-cli/blob/master/boilerplates/app/public/index.html#L12
> 这里的 index.js 改成 /index.js
你好啊，改成这个还是报错呀
