### ISSUE TITLE
dva添加onError钩子，然后打包好页面的运行在IE浏览器中报 Minified React error错误

### ISSUE THREAD

**Issue by xiaozhi93** [dvajs/dva#1618]
使用Ant Design Pro框架 在dva添加onError钩子，在开发环境下所有的浏览器都没有问题，打包放在生产环境中google等现代浏览器都没问题，但是在IE浏览器中报 Minified React error错误导致白屏。

**Comment by sorrycc** [comment]
这和 onError hook 有关？

**Comment by xiaozhi93** [comment]
添加了onError `hook打包运行在IE浏览器中
![qq 20180412182442](https://user-images.githubusercontent.com/16452712/38671866-1c451848-3e7f-11e8-8daa-ddf06fc1af58.png)，开发环境没有问题，然后打包运行在IE中出现这个问题导致白屏。

**Comment by sorrycc** [comment]
不添加 onError 没问题？

**Comment by xiaozhi93** [comment]
不添加完全没有问题，已经测试好多遍。使用的Ant Design Pro是1.2.1，里面的dva版本是2.1.0

**Comment by sorrycc** [comment]
onError 里写什么了？

**Comment by xiaozhi93** [comment]
里面添加了 
```
notification.error({
      message: error.name,
      description: error.message,
 });
```
测试了下是由于这段代码导致的，移除这段代码没有问题。。只能通过其他方法进行错误处理了

**Comment by SanPy** [comment]
这个问题  没有能保留onError的处理方式吗
