### ISSUE TITLE
请教：dispatch是否有回调函数

### ISSUE THREAD

**Issue by garzekangba** [dvajs/dva#1620]
刚刚开始接触redux，项目中某个事件函数内部
更改某个state之后，希望能够马上取到这个state
`handle(){
   this.props.dispatch(
              {type:"model/save",
                payload:{
                     var:0
                     }});
   console.log(this.props.model.var)
       }`
expected  print 0

**Comment by sorrycc** [comment]
异步的，这样同步执行肯定是取不到的。

**Comment by garzekangba** [comment]
感谢大神回复，是否存在setState({},cb)中这样的回调函数呢，state更新完成后再执行后面的逻辑

**Comment by sorrycc** [comment]
dispatch effect 是有返回 Promise 的，dispatch reducer 没有。

**Comment by gitWhatever** [comment]
那对于reducer，该怎么拿到已经更改的state呢，同样遇到这个问题，求解。

**Comment by Hadroning** [comment]
this.props.dispatch( {
      type:"model/save", 
      payload:{ 
          data: { var: 0 },
          cb: (res) => {
               console.log(野路子回调")
           }
      }
}

**Comment by 97z4moon** [comment]
> this.propsdispatch( { type:"/save", payload:{ data { var: 0 }, cb: (res) => { console.log(野路子请求") } } }

dispatch本身会return出去，在payload传callback没有意义。

**Comment by Hadroning** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
