### ISSUE TITLE
dva-core里的REDEX_DEVTOOLS不能使用

### ISSUE THREAD

**Issue by captainbob** [dvajs/dva#1621]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
我不知道REDEX_DEVTOOLS是不是版本升级了，导致了dva-core中的关于devtools的代码不能起作用了
原始代码如下：
let devtools = () => noop => noop;
  if (process.env.NODE_ENV !== 'production' && window.__REDUX_DEVTOOLS_EXTENSION__) {
    devtools = window.__REDUX_DEVTOOLS_EXTENSION__;
  }

  const enhancers = [
    applyMiddleware(...middlewares),
    ...extraEnhancers,
    devtools(window.__REDUX_DEVTOOLS_EXTENSION__OPTIONS),
  ];

现在出现问题
[我查看了REDEX_DEVTOOLS的git](https://github.com/zalmoxisus/redux-devtools-extension)
这现在是
  import { createStore, applyMiddleware, compose } from 'redux';

+ const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
+ const store = createStore(reducer, /* preloadedState, */ composeEnhancers(
- const store = createStore(reducer, /* preloadedState, */ compose(
    applyMiddleware(...middleware)
  ));
这样的
所以这段请修改掉，谢谢

**Comment by sorrycc** [comment]
无法重现，我测了下没发现问题。
