### ISSUE TITLE
dva-core v1.2.0 introduces a Breaking Change

### ISSUE THREAD

**Issue by pedroteixeira** [dvajs/dva#1622]
Hello,

Mutating the passed action by injecting `__dva_reject` and `__dva_resolve` `functions` is a big deal.. It breaks code that relies on `the action object not being mutated` 

In this particular case, it specially breaks plain object serialization (for ex: it breaks code that used WebWorker postMessage calls) since `functions` are not serializable. Also breaks any tests that make assertions on the action object by ways of value equality.

> Isn't better to have an actions map that keeps state outside the action descriptor object itself?
(we could use a ES6 Map() and use the object references as key I suppose)

I really feel the `action` obj should be treated as immutable by `dva`... Feel free to chat here if want any help on this.

best regards

**Comment by sorrycc** [comment]
Is there any example to reproduce the problem?

**Comment by pedroteixeira** [comment]
```js
const action = {type: "MyAction", payload: {}}
const before = JSON.stringify(action)

dispatch(action)
const after = JSON.stringify(action)

expect(before).toEqual(after)
```

my current workaround was to copy the action object with only the keys `type` and `action` so I do not get errors from the new keys that were injected.

**Comment by WavinFlag** [comment]
[FSA says](https://github.com/redux-utilities/flux-standard-action#payload):
> `payload` property MAY be any type of value

also:
> if `error` is `true`, the `payload` SHOULD be an error object

So I think requiring the whole `action` to be plain object would be too restrictive for most scenarios.
(though modified actions are not FSA-compatible in dva currently, but simply moving `__dva_resolve` and `__dva_reject` into the `meta` property will make it satisfied)
