### ISSUE TITLE
app.model: namespace should be defined

### ISSUE THREAD

**Issue by youstde** [dvajs/dva#1624]
线上代码好好的，突然今天就报这个错，什么鬼

**Comment by sorrycc** [comment]
如何重现？

**Comment by dmy147** [comment]
我也遇到了，用的webpack 4
只接用`app.use(require('path'))`就会报错
要么你先 import 
要么 你得加个用在`require`之后加个 `default`  ,像这样 `app.use(require('path').default)`

**Comment by heyunjiang** [comment]
是roadhog对webpack 的 require 扩展了吗？

**Comment by tylerrrkd** [comment]
> 我也遇到了，用的webpack 4
> `router` ,`model `都是的
> 直接用`app.router(require('path'))`就会报错
> 要么你先 import
> 要么 你得在`require`之后加个 `default` ,像这样 `app.router(require('path').default)`

问题是解决了，但是显得很奇怪，同一个路由里，别的`model`都不需要`.default`，就单单这个`model`需要，显得有点离谱。

![image](https://user-images.githubusercontent.com/8706896/87657631-ab829780-c78d-11ea-9644-420c953185dc.png)
