### ISSUE TITLE
升级2.2.2版以后linux编译报错

### ISSUE THREAD

**Issue by wanliyunyan** [dvajs/dva#1633]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
错误1.
import {Link, Redirect, Route, Switch} from "dva/router"; 

错误2.
*clearNotices({ payload }, { put, select }) {
      const count = yield select((state) => state.global.notices.length);
      yield put({
        type: "user/changeNotifyCount",
        payload: count,
      });
    },

错误3.
           dispatch(routerRedux.push({
              pathname: "***",
              payload: {
                glqyym: "*****",
              },
            }));

#### Expected behavior: (预期的正常效果)
2.2.1版linux正常编译

#### Actual behavior: (实际效果)
错误1 2.2.2版 linux 报 Module '"***/node_modules/dva/router"' has no exported member 'Link'
错误2 2.2.2版 linux 报 Type 'Action' has no property 'payload' and no string index signature.
错误3 2.2.2版 linux 报 Argument of type '{ pathname: string; payload: { glqyym: string; }; }' is not assignable to parameter of type 'LocationDescriptor'.
  Object literal may only specify known properties, and 'payload' does not exist in type 'LocationDescriptor'.
#### Versions of packages used: (哪个库的哪个版本出现的问题)

2.2.1 一切正常，但是看到说2.2.2新增对ts 的支持，我的项目就这样了，编译不过去，目前退回了

**Comment by wanliyunyan** [comment]
刚刚试验了2.2.3也报出同样的错误

**Comment by sorrycc** [comment]
给个能重新啊的库？

**Comment by wanliyunyan** [comment]
@sorrycc https://github.com/wanliyunyan/test-dva- 我刚上传的

**Comment by wanliyunyan** [comment]
我的天，我的项目重新按照2.2.1版运行也报错了，我的package根本没有更新，但是不知道为什么会出错，我怀疑是路由的插件更新了。。。。。。

**Comment by wanliyunyan** [comment]
import {Link} from "react-router-dom"; link 我用 这个组件了，不在用dva中的router就不报错了，
routerRedux.push 传值 我也不用query 改用 search了，也好了，应该是react router方面更新了

**Comment by wanliyunyan** [comment]
@sorrycc 兄弟，我不知道别人什么情况，我自己这么改就可以了，我先关闭这个issue了
