### ISSUE TITLE
菜鸟求助，能否给一个带生命周期组件的例子呢？

### ISSUE THREAD

**Issue by xjdata** [dvajs/dva#164]
我有个部门选择的下拉菜单，是公共组件，现在希望，每次加载组件时，触发一个远程请求的事件。

componentDidMount，但是实在不会写~~~ 文档说`class App extends React.Component({});` 使用这种方式来写带生命周期的组件。但是这样写以后，传参什么的彻底不会。。。我搜索了整个dvajs所有项目，都没有类似的可以学习的代码。

使用subscriptions的话， 因为是公共组件， 所以没办法根据 history 判断路劲来决定是否加载。
同时subscriptions 也不会访问当前模型的state内容， 所以也没办法根据 数据判断是否加载。

还请各位指导。谢谢。

**Comment by xjdata** [comment]
照猫画虎写了个。 还是不行。。。。。。 呃。。。。郁闷。

```
import React, { Component, PropTypes } from 'react';
import { Button } from 'antd'

const propTypes = {
    buttonText: PropTypes.any,
};

class testComponent extends Component {
    constructor(props, context) {
        console.log('component constructor');
        super(props, context);
    }

    componentDidMount() {
        console.log('componentDidMount');
    }

    render() {
        return (
            <div id="testComponent">
                <Button onClick={this.props.onClick} >{this.props.buttonText || '确定'}</Button>
            </div>
        )
    }

}

testComponent.propTypes = propTypes;
export default testComponent;
```

**Comment by xjdata** [comment]
.。。晕，有搜索了一会。

```
componentDidMount() {
        console.log('componentDidMount');
    }
```

改成
```
    componentDidMount = (e) => {
        console.log('componentDidMount');
    }
```

好了。。。。 我继续去学习。。。。 哎。。。菜就是没办法。

**Comment by xjdata** [comment]
还是不会。。。。。 

请问能否将这个组件怎么才能改写成带生命周期的样子呢？

[https://github.com/dvajs/dva/blob/016494f4ea9bf01f8686ecc14e912593d2e44077/examples/user-dashboard/src/components/Users/UserSearch.jsx](url)

**Comment by xjdata** [comment]
根本原因还是基础差，dva更适合有react，redux等等，并且已经大概了解es6语法规则的。
我水平太差了。。 需要学的东西太多。

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva-knowledgemap
按这个学，react 声明周期查下 react 官网文档吧。

**Comment by xjdata** [comment]
谢谢@sorrycc 回复。
请问 下面的组件在的参数 from，是在哪里进行赋值的呢？ 我看了userSearchProps 声明部分，并没有找到显示声明的代码。

https://github.com/dvajs/dva/blob/master/examples/user-dashboard/src/components/Users/UserSearch.jsx#L9
```
...
form: {
    getFieldDecorator,
    validateFields,
    getFieldsValue,
    },
...
```

https://github.com/dvajs/dva/blob/master/examples/user-dashboard/src/routes/Users.jsx#L63
```
  const userSearchProps = {
    field,
    keyword,
    onSearch(fieldsValue) {
      dispatch({
        type: 'users/query',
        payload: fieldsValue,
      });
    },
    onAdd() {
      dispatch({
        type: 'users/showModal',
        payload: {
          modalType: 'create',
        },
      });
    },
  };

```


额。。。你给的文档我看过了，水平太差，单个看现在都能看懂，但是自己遇到问题就是不会。 包含表单类的组件，使用react的生命周期的这么个事情，我就耗了整整一晚上还不行。 郁闷啊。

**Comment by sorrycc** [comment]
`Form.create()(UserSearch);` 时附加上的，要了解这一点，需要看下 antd 的 form 组件。

**Comment by xjdata** [comment]
果然。  谢谢。 耽误你时间十分不好意思。 知道水平差，提出的问题水平也差，还请包涵。
```
class CustomizedForm extends React.Component {}

CustomizedForm = Form.create({})(CustomizedForm);
```

`经过 Form.create 包装的组件将会自带 this.props.form 属性，this.props.form 提供的 API 如下：。。。。。。`


请问，form类行的 和用户交互的组件，我现在想的这种实现方式是不是太另类？ 

我的计划是 在组件加载后去服务器去数据。但是我看了dvajs的所有例子，都没有我这种想法的实现。

是我的方向不对呢？ 还是这种实现其实很简单或者很菜。简单到大家都不愿意用。。。。

**Comment by sorrycc** [comment]
> 在组件加载后去服务器去数据

用 dva 就要在 model 层组织数据，视图只是负责渲染，所以不需要用到组件的生命周期。

那么在 model 中如何加载数据? 

1. effect 中通过 `yield call` 调用异步函数加载数据
1. subscription 中 dispatch action 触发刚才定义的 effect

**Comment by xjdata** [comment]
嗯，我的需求是一个公共组件。 该组件的model我是在启动app的时候加载的。

然后我在model的中打印了下 subscriptions 执行的时机。 发现该订阅是在加载model时就被触发了。

````
app.model(require('./models/dept'));

// /model/dept.js
...
  subscriptions: {
    setup({ dispatch, history }) {
      console.log('dept model setup');
    },
  },
...

```


因为我这个组件需要每次展示时都请求服务器获取新的数据。 当然这在subscriptions 可以根据当前url部分来判断，但因为是公共组件，如果判断那可能会有很多，虽然维护一个数组不是很麻烦的事情，但是依然还是另一个可能出bug的地方。 也在自己的水平范围内仔细看了下 dva的文档，感觉上只能依靠react的生命周期来解决这个需求了。 

简单说就是每次组件被mount的时候，触发effect/query的方法。

要么就变通一下，每次请求包含该组件的route时，我在url中增加个hash，标注下，这样估计可以满足subscription中进行判断的。但是感觉不是很优雅。所以就一直在纠结这个问题了。 谢谢。

**Comment by sorrycc** [comment]
组件展示应该是由 action 触发的吧，在那个 action 里触发数据请求? 如果搞不定，那就用 react 的生命周期的方法吧，在 componentWillMount 里 dispatch action 加载数据。
