### ISSUE TITLE
npm install antd 时卡住

### ISSUE THREAD

**Issue by zhumengyue** [dvajs/dva#1641]
在运行 `dva new` 命令初始化一个新项目后，运行 `npm install antd babel-plugin-import --save` 时卡住

![TIM截图20180420170841.png](https://i.loli.net/2018/04/20/5ad9ae32e767f.png)

已使用SS科学上网 - -

**Comment by sorrycc** [comment]
试试 cnpm 。

**Comment by smallsixFight** [comment]
用全局代理，我改成全局代理就好了 -.-
