### ISSUE TITLE
如何添加类似hover，focus的样式？

### ISSUE THREAD

**Issue by zhumengyue** [dvajs/dva#1643]
我知道在项目中，添加样式有className={styles.xxx}方法  或者style={ {xxx:xxx, xxx:xxx } }

但如果我想对某个组件（比如button）重写其hover和focus的样式，

或者，设置层级选择型的样式，比如  .xxx > .xxx ，请问要怎么做呢

尝试过在一个css文件里单独写这类样式，然后在index.html里link这个css文件，但是貌似不起作用

**Comment by Worish** [comment]
我也遇到这样的问题,不知道如何解决啊...你这问题都已经11天了.....看来没人回答了..

**Comment by sorrycc** [comment]
非 dva 问题啊。

**Comment by sjy** [comment]
@zhumengyue  确实和dva没什么关系，像这种问题，建议去网上stackoverflow查或者看开源的代码例子
这里有一个例子 https://codepen.io/javiayala/pen/zvQbbb
