### ISSUE TITLE
pro new 的项目报以下错误

### ISSUE THREAD

**Issue by muchengit** [dvajs/dva#1644]
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"]
but instead got null
    at Array.map

**Comment by sorrycc** [comment]
## Property right of AssignmentExpression expected node to be of a type ["Expression"]

### 报错

```
Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
```

### 解决

删除 `.webpackrc.js` 里的 `transform-decorators-legacy`。

### 参考

https://github.com/ant-design/ant-design-pro/pull/1345
