### ISSUE TITLE
使用dva/dynamic需要配置webpack或roadhog吗

### ISSUE THREAD

**Issue by 750973092** [dvajs/dva#1648]
如何有roadhog能不能提供个例子啊

**Comment by sorrycc** [comment]
roadhog 直接用就行，无需配置。

**Comment by 750973092** [comment]
@sorrycc 但roadhog2版本新增了个commons配置项，这个怎么用，它不是配置按需加载的吗，有roadhog2版本的文档说明吗，

**Comment by 750973092** [comment]
@sorrycc 还有如果我有5米umi那是不是也不需要配置，并且从roadhog迁移到umi那是不是不用做任何改变？
