### ISSUE TITLE
如果我想使用 react-hot-load，不是dva提供的babel-plugin-dva-hmr，redbox怎么处理？

### ISSUE THREAD

**Issue by wanliyunyan** [dvajs/dva#1649]
https://github.com/commissure/redbox-react/blob/master/examples/react-hot-loader/index.js
我想这样使用redbox，
https://github.com/wanliyunyan/dva-typescript-antd-starter-kit 这是我的仓库，没有使用babel-plugin-dva-hmr，完全用的 react-hot-load，但是不知道该怎么样使用redbox，有样例吗？

**Comment by wusongV5** [comment]
我现在也遇到了这个问题，有解决方法吗？

**Comment by wanliyunyan** [comment]
我已经解决这个问题了， https://github.com/wanliyunyan/dva-typescript-antd-starter-kit ，看我的仓库

**Comment by licaomeng** [comment]
https://github.com/wanliyunyan/dva-typescript-antd-starter-kit 
这个项目我有run，似乎只有hmr的效果

**Comment by wanliyunyan** [comment]
@licaomeng 嗯，没办法，页面state留不住

**Comment by licaomeng** [comment]
想问下有调查原因吗，是dva的问题？

**Comment by wanliyunyan** [comment]
@licaomeng 不清楚啊，没有state就是麻烦点，我是凑合用了
