### ISSUE TITLE
build之后，部署到服务器，页面空白

### ISSUE THREAD

**Issue by zhumengyue** [dvajs/dva#1650]
在使用 `npm run build`之后，dist文件仅一个html文件，一个css文件，一个js文件，static文件夹里是几张图片
![1.png](https://i.loli.net/2018/04/27/5ae27e42c56d6.png)

把dist文件夹放到服务器里
![2.png](https://i.loli.net/2018/04/27/5ae27e9703176.png)

打开浏览器，输入地址，浏览器显示空白，资源（css、js）已加载，没有报错
![3.png](https://i.loli.net/2018/04/27/5ae27f4b7fa7d.png)

但是如果在**本地dist目录**下启动一个服务器
![4.png](https://i.loli.net/2018/04/27/5ae27f86d0582.png)
浏览器打开localhost:5000可以正常浏览

请问这是什么原因呢？或者我还需要提供哪些代码

**Comment by sorrycc** [comment]
用的 browserHistory 吧，默认 base 是 `/`，你访问 http://domain/dist，base 是 `/dist`，所以匹配不上。

**Comment by zhumengyue** [comment]
那请问服务器的配置思路是什么呢，项目已经完成了，就差上线，又不想要那个#

**Comment by zhumengyue** [comment]
多谢，我还有一个问题，build之后部署，已经可以看到，但是antd组件样式错乱（好像只有Table组件样式不对，其余样式和本地正常），这是什么原因呢

**Comment by zhumengyue** [comment]
第一张是本地的情况，第二张是部署后的情况
主要问题应该就是table组件的column的width及align没有生效
![5.png](https://i.loli.net/2018/04/27/5ae28ac865de3.png)
![6.png](https://i.loli.net/2018/04/27/5ae28ac8677fd.png)

**Comment by zhumengyue** [comment]
@Jimi6 就是上面说的方法，配base和部署到根目录都可以
