### ISSUE TITLE
一些全局样式，build后，css选择器自动添加字段，导致样式无效

### ISSUE THREAD

**Issue by zhumengyue** [dvajs/dva#1651]
有一些组件里细微的改动，我直接写在了全局的index.css文件里，没有使用import，只是在index.html里引入了这个文件
![7.png](https://i.loli.net/2018/04/27/5ae29e911b167.png)
但是在build之后，这些样式的选择器会自动添加一些字段，像下面这样
![9.png](https://i.loli.net/2018/04/27/5ae29f3e64f77.png)

这样样式就不生效了。现在这样定义的很少，我还可以手动把后缀删掉

请问有什么科学的解决办法没

或者就我遇到的原始问题（想对某个组件的细微部分调整，比如 `Table` 组件的表头的某一个单元格），有什么好的解决办法没

**Comment by zhumengyue** [comment]
是不是像第一条那样，加个global就行。。。。

**Comment by codering** [comment]
我觉得可以在 public目录写个全局css, 手动在index.html里面引入试试

**Comment by zhumengyue** [comment]
@SuperNaturalGit 意思是我加了global的话，打包后这部分样式表不会添加后缀了是吗

**Comment by SuperNaturalGit** [comment]
@zhumengyue 是的
