### ISSUE TITLE
react-router-redux 5默认reducer key变了

### ISSUE THREAD

**Issue by zhongqiu123** [dvajs/dva#1652]
react-router-redux@5.0.0-alpha.9默认把路由location数据挂载在state.router上了，而非老版的state.routing
[https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/selectors.js#L3](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/selectors.js#L3)

dva引了里react-router-redux 5，但是路由数据还是挂载在state.routing上
[https://github.com/dvajs/dva/blob/master/packages/dva/src/index.js#L17](https://github.com/dvajs/dva/blob/master/packages/dva/src/index.js#L17)

如果想调用react-router-redux5 新增的createMatchSelector API就会有问题

**Comment by mrbone** [comment]
临时解决办法是用 hook:

```js
const app = dva({
  extraReducers: {
    router: routerRedux.routerReducer
  }
});
```
