### ISSUE TITLE
希望添加 dva-core的d.ts，便于typescript项目里使用，谢谢

### ISSUE THREAD

**Issue by YahuiWong** [dvajs/dva#1658]
希望添加 dva-core的d.ts，便于typescript项目里使用，谢谢

**Comment by fangkyi03** [comment]
直接使用dva就可以 所有的index.d.ts都写在dva里面了

**Comment by YahuiWong** [comment]
@fangkyi03 有直接使用dva的react-native  typescript的演示例子吗？我想快速入手下

**Comment by YahuiWong** [comment]
好吧 ，我自己写了一个 还望高手斧正  https://github.com/YahuiWong/Dva-RN-TS

**Comment by YahuiWong** [comment]
但是还是需要一个 dva-core的官方 d.ts， @sorrycc 希望大神考虑下，谢谢

**Comment by vincentmrlau** [comment]
跪求

**Comment by Symous** [comment]
同求dva-core的ts版。

**Comment by swdenglian** [comment]
简单的写了个 https://github.com/swdenglian/dva-rn
