### ISSUE TITLE
dva用browerHistory的路由方式，在npm start时可以进行代码运行，但是在npm run build时可以打包代码，但是打包出来的代码进行访问时确不进行渲染

### ISSUE THREAD

**Issue by minzhang2** [dvajs/dva#166]
![image](https://cloud.githubusercontent.com/assets/15793061/19410096/e15fbbcc-9315-11e6-9a4a-2881a7e52891.png)
![image](https://cloud.githubusercontent.com/assets/15793061/19410098/e727dc88-9315-11e6-9ec4-ba52ab059e09.png)
我尝试着改了dva的源码发现还是有这个问题

**Comment by sorrycc** [comment]
调试和 build 直接好像只有压缩的区别，有查到原因吗? 用 hashHistory 没有问题?
