### ISSUE TITLE
使用browserHistory后，刷新页面报错

### ISSUE THREAD

**Issue by zhumengyue** [dvajs/dva#1662]
使用了browserHistory，并设置了basename，但是页面刷新会报错

本地调试报错
`Uncaught SyntaxError: Unexpected token <`

部署后报错
`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by sjy** [comment]
能不能提供一个最小化可重新此问题的代码例子或者提供更多的报错和代码信息

**Comment by dawnChen666** [comment]
@sjy 如果您需要，我可以写一个给您，希望您给点指导 不知如何发送给您

**Comment by jogasa** [comment]
同遇到这个问题...

**Comment by dawnChen666** [comment]
@jogasa 尝试使用dva+umi

**Comment by gjqiang** [comment]
同样遇到这个问题。。historyApiFallback 可以自己配置嘛？

**Comment by jianhunxia** [comment]
解决了吗？老铁们，我也想用browserHistory。

**Comment by zhumengyue** [comment]
@jianhunxia  
是这样的，history是pushstate修改的，刷新后浏览器就不知道了，会根据这个路径发送真实的请求，服务器上当然没有这个路径，所以空白或者404。部署环节服务端处理一下就好了，nginx rewrite到index.html就可以了。
可以这样理解，对服务端来说，history api再怎么操作，服务端认为访问的都是index.html，刷新后就不一样了，服务端会根据路径去找，肯定找不到。对前端来说，这是SPA，入口时index.html，route是根据location.href获取的，history api会影响location.href

**Comment by littleLane** [comment]
1、正式环境配置 nginx，具体怎么配置，网上一大推

2、用 node 跑服务加一个 connect-history-api-fallback 插件
代码配置 app.use(require('connect-history-api-fallback')());
