### ISSUE TITLE
 couldn't open the modal when you  dispatch a side-effect action to redux-store (Fixed)

### ISSUE THREAD

**Issue by engineerFrankLiu** [dvajs/dva#1663]
I am so thank you for reading my issue,
I am back-end developer, for some reason ,I use dva(that is long story), I am not very similar with front-end stack; dva is difficult for me ,such as react, reduce,saga...blalbalab

here is code

```
 showModal = (record, e) => {
        if (record.status == 0) { 
          this.setState({ visible: true, });
            this.props.ChangeStatus(record.id);
        } else if (record.status == 2) {
            this.props.IsAllowedReply(record.id);
             this.setState({ visible: true, });
        } else if (record.status == 1) {
            this.setState({
                visible: true,
                disable: true,
                isShowButton: false
            });
        }
    }
```

I find setState doesn't wok, the modal does't show; but if I remove the 

`this.props.xxxx()`

it's wok (the modal is showing.)
I don't know reason.....and it is blocking me for next step, I hope some can help me out

thanks sincerely~

**Comment by sjy** [comment]
Hi, @engineerFrankLiu, could u please provide more detailed info, you can create a jsfiddle (or something like this) to share the code sample which can produce the scenario.

**Comment by sjy** [comment]
I create a code sandbox sample to reproduce your problem:  https://codesandbox.io/s/13n9vp32l3.
Every time you dispatch a side-effect action to redux-store, as a result some store-connected parent component's props changed, as a result the sub-component  class re-construct;

**Comment by engineerFrankLiu** [comment]
Hi~Johnson,Thanks your answer, I send request in PModal.js directly instead of dispatch a side-effect(Honestly,I am not familiar with reduce-saga...), it works~ thanks again, have a nice day~
