### ISSUE TITLE
Roadhog Compile Long Time

### ISSUE THREAD

**Issue by jafri** [dvajs/dva#1665]
Roadhog v2, compilation takes 2 to 3 minutes using `npm start`. Is it supposed to take this long?

**Comment by sjy** [comment]
Please provide more info about your project structure and configuration.  If it is some possible issue caused by roadhog ,  commit a issue here  https://github.com/sorrycc/roadhog.

**Comment by sorrycc** [comment]
Is roadhog@2.2 have this problem?
