### ISSUE TITLE
How to hold modal state,when you dispatch a side-effect action to redux-store

### ISSUE THREAD

**Issue by ghost** [dvajs/dva#1673]
Hi~ thanks your attention for this iussue

here is scenario：
when you click the show-Modal button,at the same time you dispatch a side-effect action to redux-store;
you cannot show the modal;(I find other solution )

when you open the modal,(such as,show user detail in table list ),when table list data resource change(refresh),the modal will close; 

with @sjy  help,I understand the reason why it will close;

here is my last issue: https://github.com/dvajs/dva/issues/1663
here is Johnson example to reproduce the problem: https://codesandbox.io/s/13n9vp32l3

here is my new scenario:

in order to get fresh data in user's table list automatically in some interval , I set timer to loop the service(I know there is better way,but this is not what I want to discuss here), when I get new data ,I click show-detail button to do something , but next refresh will cause the modal close,......but ....I want to keep it staying open state, so .......Is there any good way to  meet this requirements

**Comment by gitVera** [comment]
I have the same problem
