### ISSUE TITLE
dynamic加载class方式的组件在IE9下报错

### ISSUE THREAD

**Issue by yukinight** [dvajs/dva#1677]
函数式定义的组件没问题，
class方式定义的组件在使用dynamic路由时在IE9下报错
function _classCallCheck(instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");
  }
}

**Comment by yukinight** [comment]
Warning: The <DynamicComponent /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change DynamicComponent to extend React.Component instead.

**Comment by sjmmm** [comment]
我也遇到了，ie10就有报这个错，你解决了吗？

**Comment by sorrycc** [comment]
参考：https://github.com/umijs/umi/issues/413
