### ISSUE TITLE
dva model 使用takeLates，新的action要等待老的action触发的异步请求返回之后才触发save

### ISSUE THREAD

**Issue by oldturkey** [dvajs/dva#1682]
按照文档介绍的写法写了如下代码：
```
 fetchCurrentDevice: [
      function* fn({ payload }, { call, put }) {
        const response = yield call(getalertlist, payload);
        yield put({ type: 'save', payload: { alertList: response } });
      },
      { type: 'takeLatest' },
    ],
```
场景：第一次触发的aciton所做的异步请求耗时较长，在此期间用户触发了一个耗时很短的action，希望页面能够快速显示用户第二次action返回的结果，终止第一次的effect

问题：最终结果确实只save了第二次的操作结果，但是save触发的时间是在第一次action触发的异步请求返回之后才得到结果，请问有什么方法可以处理此类情况？

**Comment by oldturkey** [comment]
@sorrycc 望解答。

**Comment by sorrycc** [comment]
不是触发的同一个 action 吗？为啥一个长一个短？

**Comment by oldturkey** [comment]
是同一个action，但是payload不一样，类似于要查杭州的房价数据和不知名小城市的房价数据，因为数据量不同，返回速度不同

**Comment by Qquanwei** [comment]
这种是正常的吧？

**Comment by oldturkey** [comment]
理想的效果应该是程序不用考虑第一个请求的耗时和结果，直接返回第二个请求的结果。 实际情况是，第二个请求要等到第一个请求结束才把结果渲染出来。

**Comment by Qquanwei** [comment]
我用的自带的例子没发生这个问题，点击无数次按钮，最后一个end也只会在1秒后执行。

```javascript
 addThenMinus: [function*(action, { call, put }) {
      yield put({type: 'add'});
      console.log('start');
      yield call(delay, 1000);
      console.log('end');
      yield put({type: 'minus'});
    }, {
      type: 'takeLatest'
    }]
```

**Comment by oldturkey** [comment]
这个例子的意思和我表达的意思不一样额，你的这个效果在我这边是一样的（加console的话也只会触发一次），我的代码里无论多少次触发action，但是save确实只会发生一次，但是save发生的时间会受之前最慢的异步请求影响。也就是说视图的渲染，要等到最慢的异步请求有结果才会渲染最终结果。
