### ISSUE TITLE
put select 不同步

### ISSUE THREAD

**Issue by dly667** [dvajs/dva#1684]
### 1.model文件
  effects: {
    * getTransactionById({
      payload,
    }, { call, put ,select}) {
     
      yield  put({
        type: 'user/query',
        payload:{
          query: payload.query
        }
      })
  
      const todos = yield select(state => state);
      console.log('fiset',state,)
    },
)}

### 2.另一个model/user文件
`
    * query ({ payload = {} }, { call, put }) {
    
      const data = yield call(query, payload)
      if (data) {
        //设置语言
 
        yield put({
          type: 'querySuccess',
          payload: {
            list: list,//data.datas.list,
      
            },
          },
        })
        console.log(22,Date.parse( new Date()))
        const hha = yield select(state=>state)
        console.log('user',state,)
      }else{
        throw data
      }
    },
`

第一个文件的yield put  完， yield select 没数据。在第二个文件select 有数据。yield不是同步执行吗，这是为什么

**Comment by sjy** [comment]
Not  dva related，but here is a example; 

```js
const stepsGen = function* () {
    yield 1;
    console.log(2);
    yield 2;
};

const steps = stepsGen();

console.log('step 1', steps.next());

// log 2 after last yield
console.log('step 2', steps.next());
```

**Comment by luke93h** [comment]
因为redux-saga的fork是无阻塞调用，不会等子任务执行完，而redux的reducer是阻塞调用

**Comment by luke93h** [comment]
注册的takeEvery函数触发sagaWithCatch时，遇到了yield sagaEffects.put({ type: `${key}${NAMESPACE_SEP}@@start` });导致子任务被暂时挂起
`function* sagaWithCatch(...args) {
    const { __dva_resolve: resolve = noop, __dva_reject: reject = noop } =
      args.length > 0 ? args[0] : {};
    try {
      yield sagaEffects.put({ type: `${key}${NAMESPACE_SEP}@@start` });
      const ret = yield effect(...args.concat(createEffects(model)));
      yield sagaEffects.put({ type: `${key}${NAMESPACE_SEP}@@end` });
      resolve(ret);
    } catch (e) {
      onError(e, {
        key,
        effectArgs: args,
      });
      if (!e._dontReject) {
        reject(e);
      }
    }
  }`
