### ISSUE TITLE
调试时IE打开正常,部署后IE就打不开了,已经引入babel-polyfill

### ISSUE THREAD

**Issue by wyj580231** [dvajs/dva#1688]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
调试情况下IE打开是正常的,但是部署之后ie就打不开了,控制台js报错,已经在index中引入了babel-polyfill

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva 2.2.3
babel-polyfill:6.26.0

**Comment by 951565664** [comment]
@sorrycc

**Comment by mmzhw** [comment]
i have the same question,how to resolve this question?

**Comment by sorrycc** [comment]
报什么错？感觉和 https://github.com/umijs/umi/issues/413 是同一个问题。

**Comment by wyj580231** [comment]
图片上传不了,部署后是压缩的代码,报的错误不明确,npm start 调试时是正常的

**Comment by sorrycc** [comment]
不压缩试试。

**Comment by 951565664** [comment]
@sorrycc 已经弄好了可复现的代码，https://github.com/951565664/dva-bug  就是用dva-cli 生成的加一个babel。在ie 下如果加了babel-polyfill 则报错
![image](https://user-images.githubusercontent.com/22285404/39994813-067b5116-57ad-11e8-841f-4cf7fa18991f.png)

**Comment by sorrycc** [comment]
加 `@babel/polyfill` 而不是 `babel-polyfill`。

**Comment by feitingjun** [comment]
在index.js第一行加  import ‘@babel/polyfill’  就好了，记得是第一行

**Comment by feitingjun** [comment]
在index.js第一行加 import ‘@babel/polyfill’ 就好了，记得是第一行

**Comment by feitingjun** [comment]
在index.js第一行加 import “@babel/polyfill”， 就好了，记得是第一行

**Comment by 951565664** [comment]
并不可以啊。你可以看下我的示例代码，已经加了 import 'babel-polyfill';

**Comment by feitingjun** [comment]
在index.js第一行加 import @babel/polyfill就行了，记得是第一行

**Comment by 951565664** [comment]
@feitingjun  你的@babel/polyfill 是多少版本的？

```
"dependencies": {
    "@babel/polyfill": "^7.0.0-beta.46",
    "antd": "^3.5.0",
    "babel-plugin-import": "^1.7.0",
    "babel-polyfill": "^6.26.0",
    "babel-runtime": "6.9.2",
    "dva": "^2.2.3",
    "react": "15.6.2",
    "react-dom": "15.6.2"
  },
```

**Comment by feitingjun** [comment]
![tim 2](https://user-images.githubusercontent.com/23121594/40034207-716d1762-582e-11e8-874f-990d8711b0e9.png)
也是刚刚才解决的
![tim 3](https://user-images.githubusercontent.com/23121594/40034236-9b6bd3e6-582e-11e8-8f1c-f77e8f54a6f7.png)
打包之后最好还是放在服务器里面跑

**Comment by 951565664** [comment]
你是用的生命周期式还是函数式的组件？@feitingjun 。。如果你是用的函数式，改一个生命周期式的跑跑呢？我把生命周期式的组件注掉 是可以的

**Comment by feitingjun** [comment]
不知道你是说的router 入口文件还是页面组件，router的入口文件是函数式组件，其他的就都是生命周期式的了

**Comment by 951565664** [comment]
@feitingjun 稍等，我更新下demo，传到github上

**Comment by wyj580231** [comment]
换成了@babel/polyfill在build之后在ie下也打不开.

**Comment by wyj580231** [comment]
@sorrycc     将build命令改成cross-env ESLINT=none COMPRESS=none roadhog build设置不COMPRESS后ie11可以打开了,这是压缩的问题?

**Comment by sorrycc** [comment]
在 roadhog 最新版本里已修复的。
