### ISSUE TITLE
图片等静态资源放在哪儿

### ISSUE THREAD

**Issue by llqgit** [dvajs/dva#169]
请问，按照 [dva-doc 的结构划分](https://github.com/dvajs/dva-docs/blob/master/v1/zh-cn/tutorial/02-划分结构.md) 发现没有静态资源的目录，比如字体啊，图片啊。
另外问下，如果我自己在根目录创建了一个 ```static``` 文件夹用来存放静态资源，那，我应该用什么样的方法引入静态资源到程序中才更加妥当？

**Comment by sorrycc** [comment]
1. 我们是直接传 cdn 然后用 cdn 地址的
1. 也可以建立 `static` 目录，然后用相对路径 `import`

**Comment by llqgit** [comment]
Okay

**Comment by a573367014** [comment]
如果是同构呢，不起作用啊

**Comment by git-lt** [comment]
在哪个文件夹下建立static目录，我在routes目录和根目录建立static都不行，最后打包还是都打包到dist目录下去了，css和图片并不同有打包到dist/static目录下@sorrycc

**Comment by sorrycc** [comment]
css 引的图片按相对路径引就好了，webpack 会自动处理的，打包到 dist 下，是运行时有啥问题吗?

**Comment by yuzhouisme** [comment]
应该是说在.js或.jsx文件中使用img标签直接引用本地文件，会“找不到文件”，只有在CSS中引用才可以

是这样的现象吧？

我也遇到了，不是太懂，求助云谦

**Comment by sorrycc** [comment]
<img> 引用应该是相对 html 的吧，可以通过 webpack-copy-plugin 复制到 dist 目录下。

**Comment by yuzhouisme** [comment]
嗯嗯，是相对index.html的，我试试，谢谢

**Comment by llqgit** [comment]
我刚好昨天学了下 `webpack-copy-plugin` 
现在可以在 npm run build 的时候，把` img/` 什么的复制到那个 dist 下。
但是那个 url-loader 好像有个什么 **如果图片过小，直接base64 放到页面中** 的那个配置没搞懂。
怎么在 dva 中加载 loader 也没搞懂，本来 webpack 能力就有限。说明一少，就满脸懵b啦
