### ISSUE TITLE
华为荣耀8内置浏览器无法打开应用

### ISSUE THREAD

**Issue by devin-yuan** [dvajs/dva#1692]
**版本：**
dva-cli: 0.9.2
dva: 2.2.3
roadhog: 2.3.0

**手机及浏览器版本：**
手机：华为荣耀8
浏览器：手机内置浏览器，内核：X5内核 036711GPU-S

**手机端调试工具：**
[eruda](https://github.com/liriliri/eruda)

**问题：**
基于dva开发的应用，被查出在上述浏览器中打不开，一直觉得是es6的新特性在该浏览器内核中不支持，调了很久都没有解决，然后就试着用[ant-admin](https://github.com/zuiidea/antd-admin)测一下，同样的也打不开，只好用 dva new 的方式新建了一个空项目，在index.html中加入eruda调试工具测，发现同样的问题，且调试工具里不报任何错误，所以想来请教一下

**浏览器版本图：**
![image](https://user-images.githubusercontent.com/6328085/40115556-74324902-5943-11e8-856c-4c9e275e2138.png)

**用dva命令行生成的新项目图：**
![image](https://user-images.githubusercontent.com/6328085/40116351-fff8eba6-5945-11e8-907e-eb4f8cd3b124.png)

**Comment by Chryseis** [comment]
window.onerror  获取下错误，猜测加载index.js的就报错了

**Comment by devin-yuan** [comment]
浏览器阻止了alert的弹出

**Comment by devin-yuan** [comment]
测试了一下，该机型的内置浏览不执行window.onerror，用try catch的方式捕获了一下，报了ReferenceError: Set is not defined的错误，由于没有指定报错行号，去编译好的源码里看了下，是有一段new Set的代码，初步估计是x5低版本的内核不支持Set特性

**Comment by devin-yuan** [comment]
dva new 的项目加了import '@babel/polyfill' 可以了

**Comment by Chryseis** [comment]
babel-polyfill 加在webpack entry 的前面 ：entry:{app:['babel-polyfill','./src/index']} 试试 @devin-yuan

**Comment by Liqiankun** [comment]
@Chryseis 这个在什么File里边？请问

**Comment by Chryseis** [comment]
@Liqiankun 
With webpack.config.js, add babel-polyfill to your entry array:
`module.exports = {
  entry: ["babel-polyfill", "./app/js"]
};`

**Comment by gaohelong** [comment]
@Liqiankun  Chryseis已经写了
```javascript
entry: {
    main: [ 'babel-polyfill', './src/index' ]
} 
```

**Comment by devin-yuan** [comment]
antd-admin和我自己项目，加了在荣耀8的浏览器里还是会报ReferenceError: Set is not defined的错误，我还在尝试解决方案

**Comment by devin-yuan** [comment]
因为我第三方库是直接引入的cdn，在webpack的externals中抛出来的，所以导致低版本浏览器对cdn文件中（react-dom）中es6语法不支持，导致直接报错，改为@gaohelong 的方法后，问题得到解决，感谢

**Comment by data4truthafei** [comment]
兄弟，你的加了babel-polyfill就好了么。我的怎么不行

**Comment by devin-yuan** [comment]
@data4truthafei 你看是不是webpack里用了externals引用中间件，我是用了externals，第三方中间没有走babel才报错的

**Comment by data4truthafei** [comment]
![image](https://user-images.githubusercontent.com/40824535/42990973-da340846-8c36-11e8-8fa3-22169db1399d.png)
没有呀

**Comment by wjljan** [comment]
这个问题我也遇到了，也是华为荣耀手机，安卓版本是7.0，手机自带的华为浏览器版本是4.0.3。本人没用dva，是用creeate-react-app，结合react.js，react-rotuer，react-redux自己撘的架子。手机上安装的第三方浏览器或者微信内核浏览器都能正常访问。

表现：
屏幕白的，啥都没，react的DOM没挂载上去，没有任何报错。但是直接写在index.html的DOM内容和脚本是能够显示出来，并能够打出log到控制台。并且和项目大小无关系，我尝试只使用ReactDOM.reander去渲染一个DIV，结果也是白屏，DIV的内容显示不出来，react的DOM还是没挂载上。
这就说明，webpack打包后的main.js，在index.html外链进来的时候(默认的是相对路径)，没有执行，或者说根本没有外链上。

尝试：
后来尝试写了一个简单的js文件，也是通过相对路径外链进来，发现控制台是能打出东西的，说明这个文件里的代码是执行了的。
然后我把相对路径改为绝对路径，这个main.js就执行了，整个界面完美的出来了。
后来又尝试把main.js的内容写到了index.html的<script>标签行内，不通过外链的方式，这种办法，界面也能够完美的出现。

定位：
也就是说这可能是因为js文件的引入方式不同而造成的，还有可能是webpack的模块化运行时在外链进来的时候，没有正常工作。
出现白屏，只要没有控制台报错，那么一定就不是polly-fill的问题。

**Comment by jingkeke** [comment]
@wjljan 请问一下你有用过umi吗...我用umi框架也是华为手机空白,其他正常.用weinre调试了一下,也是id='root' 的是空的............
