### ISSUE TITLE
Incorrect Typescript definition for router

### ISSUE THREAD

**Issue by shapel** [dvajs/dva#1693]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

`
// inside some.tsx`

`import { Link } from 'dva/router'`

#### Expected behavior: (预期的正常效果)
Works like in 2.1.0

#### Actual behavior: (实际效果)
TS2305: Module '"node_modules/dva/router"' has no exported member 'Link'.

#### Versions of packages used: (哪个库的哪个版本出现的问题)
2.2.3

Looks like it need to export definitions from 'react-router-dom' instead of 'react-router' like in 
https://github.com/dvajs/dva/blob/master/packages/dva/router.js#L1

https://github.com/dvajs/dva/blob/master/packages/dva/router.d.ts#L3

**Comment by sorrycc** [comment]
Would you like to make a PR for this?

**Comment by shapel** [comment]
Sure you can see it at https://github.com/dvajs/dva/pull/1698
