### ISSUE TITLE
一点奇怪的现象

### ISSUE THREAD

**Issue by YinRenjie1993** [dvajs/dva#1694]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
Model中定义state	state: {
		DeviceList: [],
		DeviceMapInfo: {},
		Count: 0,
	},effects方法中执行
![image](https://user-images.githubusercontent.com/11569655/40176113-cb0cdd4a-5a0c-11e8-92a4-a4f1e3d85b15.png)
![image](https://user-images.githubusercontent.com/11569655/40176128-e15cb70a-5a0c-11e8-8f62-a012e517f7ee.png)
不会 触发控件的页面componentWillReceiveProps方法，页面收不到值。加上count后就控件就可以收到值了

**Comment by winjeysong** [comment]
我也碰到类似的问题：父组件传给子组件的props变化时，没有触发componentwillreceiveprops。请问你最后是怎么解决的
