### ISSUE TITLE
业务组件中 执行路由跳转，url变了，UI没有更新

### ISSUE THREAD

**Issue by jsrider** [dvajs/dva#1695]
// help：业务组件中 执行路由跳转，url变了，UI没有更新
dispatch(routerRedux.replace(ROUTE_MENU_TEXT));

Expected behavior: (预期的正常效果)
页面正常跳转&组件刷新

Actual behavior: (实际效果)
浏览器地址栏已经改变, 但是页面没有任何反应，连错误都没有
但是如果刷新一下，则可以正常显示

Versions of packages used: (哪个库的哪个版本出现的问题)
dva 2.2.3
react 16.3

**Comment by blueskink** [comment]
我也是。。。

**Comment by sorrycc** [comment]
用 [withRouter](https://reacttraining.com/react-router/web/api/withRouter) 包一下。

**Comment by blueskink** [comment]
使用withRouter还是不行。用hash history的时候是好的，换成browser history后出现这种问题，url变了，subscriptions里能监听到，数据也请求了，就是ui不更新。

**Comment by jsrider** [comment]
试过了，只有 在 dispatch.then() 异步回调里面执行的 history.push 之类的方法，url变了，UI没更新

**Comment by archerU** [comment]
@jsrider 这个问题怎么解，我也是无法更新UI
