### ISSUE TITLE
COMPRESS后build部署的ie下打不开(其他浏览器正常)

### ISSUE THREAD

**Issue by wyj580231** [dvajs/dva#1696]
dva-cli创建的项目,使用默认的roadhog build,npm run build之后ie下打不开(包括ie11),chrome打开正常,找了很多方法,试了下cross-env ESLINT=none COMPRESS=none roadhog build命令不压缩build之后ie11终于能正常打开了. 请问有什么解决方法,压缩后的代码ie也能正常.   
还有 已经在index.js中首行引入import "@babel/polyfill";,但是IE11以下的就报Set未定义
#### Expected behavior: (预期的正常效果)
不设置COMPRESS-none下ie能正常访问,
ie9及以上能正常访问

#### Actual behavior: (实际效果)
默认roadhog build后的ie全线打不开,chrome正常
设置COMPRESS-none后ie11能打开,11以下报Set未定义

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva-cli 0.9.2
dva 2.2.3
roadhog 2.3.0-beta.1
@babel/polyfill  7.0.0-beta.44

**Comment by wyj580231** [comment]
已经在index.js中首行加入 import "@babel/polyfill"

**Comment by wyj580231** [comment]
更新roadhog到2.4.1解决了

**Comment by wyj580231** [comment]
压缩的问题解决,但是在index.js首行引入了babel/polyfill (版本7.0.0 beta.47)情况下IE11及以下还是报set未定义

**Comment by sjmmm** [comment]
解决了吗？我也遇到了index.js里面import "@babel/polyfill"，也是ie11以下报错

**Comment by wyj580231** [comment]
@sjmmm 没有,ie11以下报Set未定义

**Comment by sorrycc** [comment]
set 未定义就是 polyfill 的问题了，正确引用 `@babel/polyfill` 或专门的 set polyfill 解决。
