### ISSUE TITLE
Typescript: Property '_store' does not exist on type 'DvaInstance'.

### ISSUE THREAD

**Issue by Levino** [dvajs/dva#1697]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
```js
import dva from 'dva'
import * as React from 'react'
import { persistReducer, persistStore } from 'redux-persist'
import { PersistGate } from 'redux-persist/integration/react'
import storage from 'redux-persist/lib/storage'
import App from './App'
import { model } from './components/model'

const persistConfig = {
  key: 'root',
  storage,
  whitelist: ['global', 'user'],
}

const app = dva({
  onReducer: (rootReducer) => persistReducer(persistConfig, rootReducer),
})

app.model(model)
app.router(() => (
  <PersistGate persistor={persistStore(app._store)} loading={null}>
    <App />
  </PersistGate>
))
app.start('#root')
```

#### Expected behavior: (预期的正常效果)
The code compiles with typescript

#### Actual behavior: (实际效果)
Typescript won't compile. Gives error: `Property '_store' does not exist on type 'DvaInstance'.`

#### Versions of packages used: (哪个库的哪个版本出现的问题)

- redux-persist: `5.9.1`,
-  dva: `2.2.3`

**Comment by sjy** [comment]
There is no definition for `_store` field ,  this prop is 'hidden' by design @sorrycc ?
related link:
https://github.com/dvajs/dva/commits/master/packages/dva/index.d.ts
as a workaround, you can code like this
```jsx
<PersistGate persistor={persistStore((app as any)._store)} loading={null}>
    <App />
  </PersistGate>
```
or add your customized typing definition for 'dva'

**Comment by Levino** [comment]
In the `Concepts.md` the [usage of this field is recommended](https://github.com/dvajs/dva/blob/master/docs/Concepts.md#state). It must either be made public and typed or it should not be recommended to use it. Either way this is a bug.

**Comment by sjy** [comment]
🤔 waiting for @sorrycc

**Comment by banyudu** [comment]
any update?

**Comment by banyudu** [comment]
I extends type for it finally with

```typescript
import 'dva'

declare module 'dva' {
  interface DvaInstance {
    _store: any
  }
}
```
