### ISSUE TITLE
在.webpackrc.js设置了proxy, npm start工作正常，npm run build后提示404（not found）

### ISSUE THREAD

**Issue by wangcray** [dvajs/dva#1699]
设置如下proxy，供服务访问使用

.webpackrc.js
```
{
  "proxy": {
    "/atrium": {
      "target": "http://127.0.0.1:5000/api/v1.0/",
      "changeOrigin": true,
      "pathRewrite": { "^/atrium" : "" }
    },
  }
}
```

services中
```
export function fetch() {
  return request(`/atrium/commands`);
}
```

#### Expected behavior: (预期的正常效果)
npm start，页面加载正常，访问数据工作正常

#### Actual behavior: (实际效果)
npm run build后，尝试过使用nginx和http-server分别建立服务器，页面加载正常，但不能访问导数据，控制台打印如下：

```
GET http://127.0.0.1:8900/atrium/commands 404 (Not Found)
```

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"dva": "^2.1.0"

**Comment by wangcray** [comment]
自己奋战了几小时，从nginx端进行proxy搞定了。
但还是不是很懂里面的院里，在.webpackrc.js中定义了proxy，run build后就不起作用了么？

**Comment by K68** [comment]
npm start 是开发调试，webpackrc文件会生效，方便前后端独立开发，绕过跨域等问题

npm build 生成的文件，webpackrc文件不生效，需要根据各自的产品环境做反向代理

**Comment by huangxiaohao** [comment]
您好，我也遇到了相似的问题。我这边请求测试环境数据，在.webpackrc.js中配置了
<img width="544" alt="1" src="https://user-images.githubusercontent.com/13390763/43451566-d466c318-94e7-11e8-8b20-e4489e3c494e.png">


service中进行get请求：
```
export function fetch() {
   return request('/api/v1/hospital')
}
```

虽然没有报错，但是他访问的是我本地：
<img width="422" alt="2" src="https://user-images.githubusercontent.com/13390763/43451571-d78d0cbe-94e7-11e8-9141-a181de18039e.png">

如果我变成psot请求：
<img width="471" alt="3" src="https://user-images.githubusercontent.com/13390763/43451606-eb4614e4-94e7-11e8-9eab-c956236c2bc7.png">

会直接报错，同样也是访问我本地：
<img width="452" alt="4" src="https://user-images.githubusercontent.com/13390763/43451658-06b0fd8e-94e8-11e8-8648-b0f6f40ffdef.png">

请问这个该然后处理？
