### ISSUE TITLE
请问一个model中访问另一个model的属性的做法是否合适？

### ISSUE THREAD

**Issue by xjdata** [dvajs/dva#170]
又来提一些莫名其妙的问题了。 谢谢大家。

有modela，b。

请问是否可以在modela中 访问到modelb？  获取modelb的某个属性的值？

这样的方式 是否推荐？ 如果不推荐 大家是否有这样的需求呢？ 如何解决的呢？

谢谢。

**Comment by sorrycc** [comment]
可以在 effect 里获取其他 model 的 state 。https://github.com/dvajs/dva-knowledgemap#select

**Comment by xjdata** [comment]
谢谢！云谦。
