### ISSUE TITLE
fetch的post请求在mock中没法获取req.body ,axios可以，是我少配置什么了吗？

### ISSUE THREAD

**Issue by jeffery021121** [dvajs/dva#1705]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
export function query (param) {
  const options = {
    method: 'POST',
    body: param
  }
  console.log('参数：', options)
  return request(apis.query, options)
}
这个用的是dva中提供的fetch，get方法可以获取到query中的值，post中req.body:{}
下面是axios：
export function query() {
  axios.post('/api/users', {
    firstName: 'Fred',
    lastName: 'Flintstone'
  })
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
}
可以获取到req.body的值，和预期一致

#### Expected behavior: (预期的正常效果)
body: { firstName: 'Fred', lastName: 'Flintstone' },

#### Actual behavior: (实际效果)
fetch中body: { },
axios中body: { firstName: 'Fred', lastName: 'Flintstone' },

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"roadhog": "^2.0.0"

**Comment by yaoyuande** [comment]
为什么我的fetch  报Failed to execute 'fetch' on 'Window': Failed to parse URL from 192.168.1.93:8080/live/api/customer/login

**Comment by klouskingsley** [comment]
`192.168.1.93:8080/live/api/customer/login`加上`http://`试试？

**Comment by klouskingsley** [comment]
@jeffery021121 fetch加上 content-type 试试

**Comment by yaoyuande** [comment]
@klouskingsley 少了http，谢谢啊
