### ISSUE TITLE
能否跳过model直接请求service

### ISSUE THREAD

**Issue by peakandyuri** [dvajs/dva#1712]
按照正常的流程，应该是组件关联模型，模型请求服务得到数据，将其缓存在state中。我现在使用了一个ag-grid插件，它是一个比较强大的表格控件，有不同的数据源设置。
如果是采用分页来查询数据，正常来说，每一次翻页都重新请求数据。但是我现在用的数据源设置，它会将对每一页请求的数据进行缓存，再回到之前请求过的那一页，它会直接从缓存当中取数据，不会再去重复请求，体验当然也好，历史数据加载更快，但是这就造成了一个问题，它不能用通过modal的state来取数据，而是请求新数据时要直接拿到数据，所以我是应该直接调用service呢，还是也通过modal的effects返回service请求的数据呢？
我现在是直接请求的service，因为它并不和modal产生什么关联，但是不知道在开发上是否属于不好的行为，希望大神能为我提供一个思路。

**Comment by s97712** [comment]
写个包装层 让控件从state 获取数据

**Comment by s97712** [comment]
一般这类控件需要用callback或promise去更新数据，你可以把 callback或 promise作为 dispatch的参数，让effects去调用callback和 resolve

**Comment by yoyo837** [comment]
抛开Redux 的思路就是你想要的样子
