### ISSUE TITLE
Failed to execute 'fetch' on 'Window' 

### ISSUE THREAD

**Issue by yaoyuande** [dvajs/dva#1716]
用脚手架的fetch代码提示 Failed to execute 'fetch' on 'Window': Failed to parse URL from 192.168.1.93:8080/live/api/customer/login

**Comment by sorrycc** [comment]
没有以 `https://` 协议开始？

**Comment by yaoyuande** [comment]
刚才加上http了，就是因为这个原因。多谢  大神指导。
