### ISSUE TITLE
dva,在IE9~10上的报错

### ISSUE THREAD

**Issue by SDDwen** [dvajs/dva#1717]
@sorrycc @yiminghe @JacksonTian @popomore 
##在IndexPage.js文件夹中，代码如下

```
`class IndexPage extends React.Component{
  
  render(){
    return(
      <div>Demo</div>
    )
  }
}
export default IndexPage;`
```

## 浏览器出现一下报错

> Warning: The <IndexPage /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change IndexPage to extend React.Component instead.

> The above error occurred in the <IndexPage> component:

> in IndexPage (created by Route)

>  in Route (created by DvaRoot)

> in Switch (created by DvaRoot)

> ····
##但是如果是以下代码，可以在IE9~10显示
```
`const IndexPage = () => (
  <div>Demo</div>
)
export default IndexPage;`
```
请问如何解决？？

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/issues/413#issuecomment-389016598

**Comment by yoyo837** [comment]
IE10确实不行，IE9fetch会不支持，主要想兼容到IE10...


![image](https://user-images.githubusercontent.com/6134547/41950014-b3c709bc-79f6-11e8-9fe4-b3f27b050eab.png)

**Comment by yoyo837** [comment]
See https://github.com/umijs/umi/issues/544

**Comment by sorrycc** [comment]
参考这个加 polyfill 就可以了，https://github.com/umijs/umi/blob/master/packages/umi-plugin-polyfill/src/global.js

**Comment by SDDwen** [comment]
可以的。问题已经解决了

**Comment by pwxyz** [comment]
我同样遇到了这个问题，可以问下是如何解决的么？  @SDDwen 
在src目录下的index.js这个入口文件顶部引入了一下代码
```
import 'babel-polyfill' // -v ^7.0.0-beta.3   或者 import '@babel/polyfill'  -v ^7.0.0-beta.56
import 'core-js/es6/promise';

// React depends on set/map/requestAnimationFrame
// https://reactjs.org/docs/javascript-environment-requirements.html
import 'core-js/es6/set';
import 'core-js/es6/map';
import 'raf/polyfill';

// https://github.com/umijs/umi/issues/413
Object.setPrototypeOf = require('setprototypeof');
``` 
在ie9 ie10下均没有效果 ，还给了我这个Set未定义，当前版本  
 dva --2.3.2    
roadhog -- 2.4.2     
antd -- 3.4.0

**Comment by SDDwen** [comment]
@pwxyz 如果你得项目中有umi相关的依赖import 'babel-polyfill‘这个是可以不要的。你把这个引入去掉试一试。

**Comment by pwxyz** [comment]
谢谢回复，我也尝试过不引入‘babel-polyfill’和'@babel/polyfill'，没有效果。。。  
尝试使用umi-plugin-polyfill插件，报错。。  api.register 未定义   。。
@sorrycc 我看umi已经更新了babel，dva有升级babel的打算么

**Comment by Symboler** [comment]
@SDDwen 你好，请问一下你上面截图的ie9下出现的错误最后具体是怎么解决的？我的问题和你一样的，但是做了很多尝试还是没有解决掉呢。。

**Comment by 104gogo** [comment]
我也遇到了上面的问题，搞了好久
- 引入了下面这个 polyfill，在简单的项目中不会报错了，但是在复杂的项目里面还是照样报错
```javascript
Object.setPrototypeOf = require('setprototypeof');
```
- 不使用 `dva-hmr` 是正常的，使用之后还是会报上面的错

为了不报错，还能使用 dva-hmr，提供个简化配置：
```javascript
module.exports = () => {
  const env = process.env.NODE_ENV;

  return {
    presets: [
      require.resolve('babel-preset-react-app')
    ],
    plugins: [
      [
        require.resolve('@babel/plugin-proposal-decorators'),
        { legacy: true }
      ],
      env === 'development' && [
        require.resolve('babel-plugin-dva-hmr'),
        { disableModel: true }
      ],
    ].filter(Boolean),
  };
};
```
