### ISSUE TITLE
effects action name duplicate reducer action name

### ISSUE THREAD

**Issue by racketprogram** [dvajs/dva#1718]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
```
effects: {
    *action(_, { _, put }) {
        yield put({
            type: 'action',
        });
    },
}

reducers: {
    action(state, action) {
      return { ...state };
    },
},
```
#### Expected behavior: (预期的正常效果)

call effects action then call reducer action

#### Actual behavior: (实际效果)

call effects action then call effects action then effects action ....

#### Versions of packages used: (哪个库的哪个版本出现的问题)

"dva": "^2.2.3",

**Comment by s97712** [comment]
```
effects: {
    *action(_, { _, put }) {
        yield put({
            type: 'action',
        });
    },
}

```
This is a recursion and will never end

**Comment by sjy** [comment]
agree with @s97712, @racketprogram 
* you should avoid name the action and saga/effect with same name
* you should not put saga/effect recursively without break out condition

**Comment by ghostriderxx** [comment]
名字不能重....我都是....给reducer里面的方法加上 Success 后缀....，比如：effect: addUser --> reducer: addUserSuccess.....

**Comment by yoyo837** [comment]
@ghostriderxx `dispatch`也可以直接发到`reducer`上的
