### ISSUE TITLE
Use a different router plugin

### ISSUE THREAD

**Issue by gmattar** [dvajs/dva#1719]
Is it possible to run DVA with a router other than `React Router`?
I would like to use `redux-first-router` (https://github.com/faceyspacey/redux-first-router) or `redux-little-router` (https://github.com/FormidableLabs/redux-little-router).

In case of positive, do you have any example?

**Comment by sorrycc** [comment]
Try [dva-no-router](https://github.com/dvajs/dva/tree/master/packages/dva-no-router) or use [dva-core](https://github.com/dvajs/dva/tree/master/packages/dva-core) directly.
