### ISSUE TITLE
怎么在 封装的requst 请求中 请求服务器的接口

### ISSUE THREAD

**Issue by johnsky123** [dvajs/dva#172]
在用dva开发时 ，用封装的request请求    在写上  108.XX.XX.XX/login  的url  为什么 请求的链接 在浏览器中 就变成了 本地调试的  localhost:8989/ 108.XX.XX.XX/login    这样的链接   导致请求无法发送成功  请问我改怎么修改

**Comment by sorrycc** [comment]
加 `http://` 前缀。

**Comment by johnsky123** [comment]
谢谢
