### ISSUE TITLE
怎么在effects里面加载model

### ISSUE THREAD

**Issue by wuyunjiang** [dvajs/dva#1720]
用户进入系统发送请求判断用户登录状态，（在`app` model 的`subscriptions`调用`effects`）
如果用户已经登陆才加载其他model模块
未登录跳转到登录页

那在effects里面怎么加载其他模块啊

**Comment by zjxpcyc** [comment]
如果用户未登录，就加载了 其他 model ，这个没有多大影响吧 ？

另外，你试一下 dynamic 是否能满足你的要求。

**Comment by wuyunjiang** [comment]
> 如果用户未登录，就加载了 其他 model 

@zjxpcyc 用户进入系统加载`app Model`，在subscriptions判断登录状态
现在 在`other Model`中subscriptions有个接口请求，这个接口需要携带登录的token
如果在登录判断之前就加载了`other Model`，就会重定向到/login页面。
所以必须保证`other Model`在登录判断过后加载，否则会一直重定向到登录页

**Comment by zjxpcyc** [comment]
@wuyunjiang 没理解你的意思。subscriptions 里面应该是有路由判断的吧？ 应该不会出现你说的情况。

建议你的 subscriptions 里面增加对 /login 路由的判断，一旦进入这个路由，直接 return 。 不再继续后面的动作。
