### ISSUE TITLE
升级dva、umi、umi-plugin-dva到最新版，npm start显示”Uncaught SyntaxError: Unexpected token <“错误

### ISSUE THREAD

**Issue by wangcray** [dvajs/dva#1723]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

基于范例user-dashboard构建的程序，在该配置下，运行正常

```
  "dependencies": {
    "dva": "^2.1.0",
    "umi": "^1.0.0-0",
    "umi-plugin-dva": "^0.7.2"
  },
```

升级dva、umi、umi-plugin-dva到最新版
```
   "dependencies": {
-    "dva": "^2.1.0",
+    "dva": "^2.2.3",
-    "umi": "^1.0.0-0",
-    "umi-plugin-dva": "^0.7.2"
+    "umi": "^1.3.4",
+    "umi-plugin-dva": "^0.7.3"
   }
```

#### Expected behavior: (预期的正常效果)
npm start应正常运行

#### Actual behavior: (实际效果)
页面title显示“Dva Demo”，页面空白无内容。console输出：

```
Uncaught SyntaxError: Unexpected token <                                                   index.js:1 
```

**Comment by sorrycc** [comment]
index.js? 为什么会引用到这个？

**Comment by wangcray** [comment]
@sorrycc npm start运行就会报出该信息

**Comment by sorrycc** [comment]
这些依赖都是 `^` 开头，所以你修改的内容应该没啥影响吧，改不改重新安装依赖都是最新的。

**Comment by wangcray** [comment]
折腾了一下午了，一直到现在，现象及其飘忽。
好像和版本无关，好像和package-lock.json有关
目前复现的流程是这样的：
1. checkout 出最后正常版本，
```
rm -rf node_modules;npm install;npm start
```
工作正常；
2. 删除package-lock.json
```
rm package-lock.json
rm -rf node_modules;npm install;npm start
```
故障出现

**Comment by wangcray** [comment]
故障出现后，git diff的内容见附件
```
git diff > aaa.log
```

[aaa.log](https://github.com/dvajs/dva/files/2053978/aaa.log)

**Comment by wangtaicheng** [comment]
我现在升级后也遇到问题了，fecth post 请求 ，后端用 @RequestBody 接收直接报错了
```
const body = {limit:10,page:1};
  let requestConfig = {
    // credentials: 'include',
    method: 'POST',
    mode: 'cors',
    headers: {
      'Content-Type' : 'application/json',
    },
    body:  JSON.stringify(body)

  }
const response = await fetch(url, requestConfig);
```
说是跨域问题，但是没有找到开发环境下的解决方案，编译完成后放到ng上是可以请求的。

**Comment by wilkinsleung0712** [comment]
我现在也有同样的问题，在umi里 index page 的渲染会有这个错误， 但是其他page的渲染没有问题。￼
<img width="492" alt="wx20180820-223217 2x" src="https://user-images.githubusercontent.com/6415733/44340688-f4aa0e00-a4c8-11e8-8174-cde964d35318.png">

`  "dependencies": {
    "antd": "^3.8.1",
    "babel-plugin-import": "^1.8.0",
    "dva": "^2.4.0",
    "dva-loading": "^2.0.5",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "umi": "^1.3.18",
    "umi-plugin-dva": "^0.9.1"
  },`

**Comment by commonzhou** [comment]
@wilkinsleung0712  感谢兄台，我也遇到类似的问题，删除public里的index，然后重新start可以解决。
