### ISSUE TITLE
状态变化时如何执行navigator.push这样的界面组件的方法？

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#173]
比如说，app启动后，我自动向后台发出登录请求，如果成功，则push到首页，否则replace到登录页。这两个方法都是Navigator组件的方法，我原来是用一个状态变量，在组件的componentDidUpdate判断变量是否为真，然后执行方法，然后设置变量为假，防止两次弹出，总觉得这样实现很别扭。

```
 componentDidUpdate(prevProps, prevState) {
    const {hideConfirm}=this.props.doingTaskStore;
    const {navigator}=this.props;
    if (hideConfirm) {
      popRoute(navigator, TaskConfirmUi);
      this.props.dispatch({type: 'doingTaskStore/updateState', payload: {hideConfirm:false}});
    }
  }
```
正确的方式是什么呢？在web里面好像都是组件的visible来做弹出和关闭，如果是方法，该怎么做呢？

第二个问题：在mobile app里面，会有很多push，那么也就是很多界面都存活的，这个时候，状态发生变化，每个组件都重新在内存计算了一次，会不会对性能有影响？

**Comment by sorrycc** [comment]
> app启动后，我自动向后台发出登录请求，如果成功，则push到首页，否则replace到登录页

按这个描述，不是应该全部放在 effect 里做掉吗? 为啥要走到 component 层? 

> 每个组件都重新在内存计算了一次，会不会对性能有影响？

性能问题在遇到之前先不用考虑吧。

**Comment by bjwulin** [comment]
@sorrycc ,push是用this.props.navigator.push({})这样的方法压入新页面的，不是组件的visible属性。而且navigator也不在model里面。

**Comment by bjwulin** [comment]
我开始想过把navigator，这个页面的属性传到model里面，但是那样更不合理。

**Comment by sorrycc** [comment]
好吧，那看起来没啥好方法了。
