### ISSUE TITLE
引用typescript写的第三方组件，一直报Unexpected token *错误

### ISSUE THREAD

**Issue by huzhengke** [dvajs/dva#1737]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
1、dva工程中引入拖拽组件（https://github.com/Foveluy/Dragact）
2、npm start

#### Expected behavior: (预期的正常效果)
dragact组件生效

#### Actual behavior: (实际效果)
![image](https://user-images.githubusercontent.com/7312417/40868779-007a5e70-6643-11e8-9acc-6b1184ef7d10.png)
![image](https://user-images.githubusercontent.com/7312417/40868782-0f41ce66-6643-11e8-9cbd-531127b4480f.png)

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva库是最新版

**Comment by nsuedu** [comment]
为什么要引入所有呢， 试试下面这样会不会报错
```
import React, { PureComponent, Component} from 'react';
```
