### ISSUE TITLE
dva/router.d.ts miss type definition for “react-router”

### ISSUE THREAD

**Issue by wanliyunyan** [dvajs/dva#1738]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
import { Redirect, Route, Router, Switch } from "dva/router";

#### Expected behavior: (预期的正常效果)
working regularly without angthing wrong

#### Actual behavior: (实际效果)
TS2305: Module '"node_modules/dva/router"' has no exported member 'Redirect'.
TS2305: Module '"node_modules/dva/router"' has no exported member 'Route'.
TS2305: Module '"node_modules/dva/router"' has no exported member 'Router'.
TS2305: Module '"node_modules/dva/router"' has no exported member 'Switch'.
#### Versions of packages used: (哪个库的哪个版本出现的问题)
2.3.0

see https://github.com/dvajs/dva/issues/1693, 他改类型定义的时候不该替换react-router，而是添加react-router-dom就好了

i think dva/router.d.ts should like this 

`
import * as routerRedux from 'react-router-redux';   
export * from 'react-router';   
export * from 'react-router-dom';   
export { routerRedux };
`

@shapel  Do you agree with me?

**Comment by shapel** [comment]
May be you need to install `@types/react-router-dom` as dev dependency in your project.

**Comment by wanliyunyan** [comment]
@shapel After installation, the problem is solved,however, @types/react-router-dom became a required package.
