### ISSUE TITLE
怎么能够异步初始化initialState

### ISSUE THREAD

**Issue by wingsblack** [dvajs/dva#1739]
```
dva({
   initialState:{ username:"123"}
})
能否dva({
   initialState:()=>{        
       return await xxxx()
  }
})

```

**Comment by zjxpcyc** [comment]
好像不能。什么场景呢 ？

**Comment by huanhuan1987** [comment]
@zjxpcyc 在开发react-native时,每次操作我把本地整个state保存到缓存,  当下次启动初始化时我想把保存的state赋予initialState,但是获取本地缓存的是个异步方法...

**Comment by zjxpcyc** [comment]
@huanhuan1987 
没感觉有什么好的方案. 下面三个，你看看哪个适合你
1、subscriptions 里面 setup 
2、使用 redux-persist [https://github.com/dvajs/dva/blob/master/docs/API.md#extraenhancers](https://github.com/dvajs/dva/blob/master/docs/API.md#extraenhancers)
3、在 app 初始化完成之后使用 app._store.dispatch
