### ISSUE TITLE
dva 是否与 umi 绑定的太紧了

### ISSUE THREAD

**Issue by yibn2008** [dvajs/dva#1740]
首先, dva 确实是一个很赞的框架, 我已经用它做过好几个项目, 在易用性上比直接采用 redux 和 redux-saga 要少很多麻烦.

最近在看 dva 上的一个 demo 时, 发现 dva 的依赖已经不见了, 取而代之的是 umi. 我知道这个是作者现在新主推在一站式框架, 相当于一个全家桶, 然后这并非我所期望的. 当我想查看 dva 的用法时, 我以为它应该提供的是基于 dva 本身的示例, 但如今却还需要再去了解 umi 是什么.

这里并非评判 umi 好或坏, 只是觉得 dva 与 umi 绑定的这么紧, 是否合适? 建议在 dva 官方提供 demo 时, 尽量采用相对纯粹一点的方式, 保持简单, 这样使用者只需要关心 dva 如何用就可以了.

**Comment by zjxpcyc** [comment]
我也感觉是的。

以前 dva 用的 roadhog ，不知道这个跟 umi 是什么关系。而且，总感觉 umi 有什么地方不对劲，但是说不上来。

**Comment by TongDaDa** [comment]
个人项目，慎用.... 真的

**Comment by sorrycc** [comment]
@yibn2008 感谢建议，后面会尽量保护 dva 作为数据流库的纯粹性。

**Comment by TongDaDa** [comment]
接手一个项目，从roadhog的配置转到af-webpack,然后又去看umi的配置，两个配置文件转换的太快了把，而且我觉得readme中应该标明从哪个版本有什么什么大的改变... 目前如果使用 umi 中的这些东西，可配置性太差了，而且不断的跟进它的版本，隔了个中间层真心不好办啊。。。我只喜欢 dva-core 中与saga绑定层... 以后可以单独使用它

**Comment by sorrycc** [comment]
> 接手一个项目，从roadhog的配置转到af-webpack,然后又去看umi的配置，两个配置文件转换的太快了把

你指 roadhog@1 到 roadhog@2 的差异？可以参考这份[升级文档](https://github.com/sorrycc/roadhog/blob/master/migrate-from-1.x_zh-cn.md)，主要是把 .webpackrc 到 .roadhogrc 改了个名，以及由于使用 babel@7 而引起的更新。

**Comment by napalm272** [comment]
非常同意，尤其是https://github.com/dvajs/dva-hackernews/commits/master 这个例子。从dva1直接跳到umi了。给我的感觉是dva2不怎么受重视（最起码在文档方面），要直接到umi？有点跟不上大佬的节奏

**Comment by napalm272** [comment]
@sorrycc 可以确认一下dva2会有长期独立支持吗？
