### ISSUE TITLE
希望提供onEffect的详细例子

### ISSUE THREAD

**Issue by kwzm** [dvajs/dva#1742]
我的dva是1.x版本的，我想在创建、删除，修改的effects执行成功后显示提示框，但是每个模块都写感觉有些麻烦，所以我在想能不能再onEffect里面统一实现呢，但是又没有找到详细的介绍该如何使用onEffect，希望能给些例子，谢谢了。

**Comment by sorrycc** [comment]
可以参考[用例](https://github.com/dvajs/dva/blob/master/packages/dva-core/test/effects.test.js#L406)以及 dva-loading 和 dva-immer 的实现。

**Comment by kwzm** [comment]
非常感谢！
