### ISSUE TITLE
dva1.x版本如何动态加载model和路由呢

### ISSUE THREAD

**Issue by kwzm** [dvajs/dva#1745]
我的dva是1.2.1版本的，该版本的Readme文档提供的[例子](https://github.com/dvajs/dva/tree/master/examples/dynamic-load)已经无法访问了(404)，能提供新的链接或例子吗？

**Comment by tsejx** [comment]
https://github.com/dvajs/dva-example-user-dashboard/blob/master/src/router.js

**Comment by zjxpcyc** [comment]
1.x 版本好像没有 dynamic 函数。但是好像可以通过 webpack 的动态打包实现：
```javascript
route = {
  path: 'xxx/xxx/xxx',
  getComponent: (nextState, cb) => {
    require.ensure([], (require) => {
      cb(null, require('./xxx'));
    });
  },
}
```
现在这个方式不知道对你还适不适用，好像 webpack 也升级了。

**Comment by kwzm** [comment]
感谢以上两位，我是采用webpack的动态打包`require.ensure`

另外还找到了一个例子：https://github.com/zuiidea/antd-admin/blob/4.3.4/src/router.js
