### ISSUE TITLE
在model的effects,调用call请求后端数据，当后端数据长时间不返回时，其它页面调用effects里面的方法不会被执行

### ISSUE THREAD

**Issue by ksh033** [dvajs/dva#1746]
有问题？请在 [SegmentFault](https://segmentfault.com/t/dva.js) 上提问或者[加微信群互助](https://github.com/dvajs/dva#community%E4%B8%AD%E6%96%87)。
发现 bug？请填写以下内容，尽量详细。
-->
在model的effects,调用call请求后端数据，当后端数据长时间不返回时，其它页面调用effects里面的方法不会被执行
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

==============service===============
```
export async function generatePayCode(params) {
	return request('api/pay/getGeneratePayCode', {
		method: 'GET',
		body: params,
	})
};
```
==============Model===============
```
export default {
   namespace: 'qrcode',
   state: { showPanel:false},
  effects: {
    * generatePayCode({payload}, {call, put}) {
          let {data} = yield call(generatePayCode, {bcId});
     }
     * showPanel({payload}, {call, put}) {
        	yield put({
						type: "saveShowPanel",
						payload: {showPanel: true}
			})
     }
    }
｝
```
==============调用顺序===============
1.dispatch({type:"qrcode/generatePayCode"})
当后端长时间不返回，此时页面其它按钮调用dispatch({type:"qrcode/showPanel"}),页面状态都不会被更新
![Alt text](https://raw.githubusercontent.com/ksh033/test/4c6d950d7c20a40babb01464c43ee628cf29cd32/images/error.png)
<!--

当后端及时返回，页面正常

**Comment by yoyo837** [comment]
准确一点的说法是，effects A调用未正常结束，无法再次调用此effects A...比如call api 抛出异常...

**Comment by yoyo837** [comment]
试试takeLatest
