### ISSUE TITLE
版本1.2.1 我想要将history切换为browserHistory

### ISSUE THREAD

**Issue by lovebslq** [dvajs/dva#1747]
我现在到底应该用哪一种方式来做这个调整？
1，
import { browserHistory } from 'dva/router';
const app = dva({
history: browserHistory,
});
2，
import createHistory from 'history/createBrowserHistory';
const app = dva({
history: createHistory(),
});

方式1，我改了不起作用，页面刷新还是会有#/这样的东西自动跳出来
方式2，直接就报错，找不到history,但我的版本库里明明是有这个依赖的
![001](https://user-images.githubusercontent.com/38315431/41084108-c47e9b58-6a65-11e8-9792-24480aa0920b.png)
我的版本：
("history": "~1.17.0",)

**Comment by zhouhuiquan** [comment]
第二种试过没有问题,你的问题可能是版本问题.history@4.7.2,history不是直接引用的,而是通过dva@2.3.0

**Comment by lovebslq** [comment]
那我现在要怎么调整呢？ “history@4.7.2,history不是直接引用的,而是通过dva@2.3.0”这是什么意思，我的package.json里在有这个：
![2](https://user-images.githubusercontent.com/38315431/41086471-bca28b18-6a6c-11e8-8838-356704409eec.png)
我是还要在其它地方去做 什么修改么?

**Comment by zhouhuiquan** [comment]
package.json是dva中的么?如果是的话,我建议卸载了history  npm uninstall history--save 然后再 npm install history --save
