### ISSUE TITLE
打包后的css文件里面图片路径问题导致界面上图片显示不出来

### ISSUE THREAD

**Issue by sandm1227** [dvajs/dva#1748]
项目中用到的是less文件，引入的图片路劲：
![default](https://user-images.githubusercontent.com/25194203/41087842-5f4f1c34-6a70-11e8-9ed4-66b616d3019d.png)
打包之后，部署到服务上，图片没显示出来，需要修改打包后的css文件里面图片路径，才可以显示出来，请问如何解决？

**Comment by sorrycc** [comment]
publicPath 配置的啥？

**Comment by zxuqian** [comment]
我这里也显示不出来，less文件中图片路径并没有指向打包后生成的"/static"目录，而是原来指定的"/src/assets..."路径
