### ISSUE TITLE
刷新页面 onStateChange 会自动触发两次   没有修改state

### ISSUE THREAD

**Issue by wkm-wangZhe** [dvajs/dva#1750]
目标：
    监听 model: user 中的  state 变化   然后 储存到 缓存中 
   const app = dva({
   history: createHistory(),
       onStateChange: function () {
         console.log('触发 onStateChange')
       }
   })
状况是： 
    刷新 页面  会触发两次     页面跳转会触发一次 
![onsatechange](https://user-images.githubusercontent.com/26277572/41137308-143a8678-6b0d-11e8-8b24-6c7b6166b09b.png)
     我这里  model  是通过 app.model() 挂载在全局  是否有关系

**Comment by sorrycc** [comment]
框架内部触发的 action 做一些初始化的事情，忽略就好。

**Comment by wangkai123456** [comment]
如何忽这些

**Comment by wangkai123456** [comment]
@sorrycc
