### ISSUE TITLE
由于正在整理 dvajs.com，收集下各种 dva 教程、扩展库、插件等资源

### ISSUE THREAD

**Issue by sorrycc** [dvajs/dva#1751]

**Comment by elowes** [comment]
[generator-dva](https://www.npmjs.com/package/generator-dva)，自己基于 yeoman-generator 写的一个react+dva的脚手架

**Comment by zjxpcyc** [comment]
才写了个 tiny 版的自动同步状态插件  [dva-plugin-autosync](https://github.com/zjxpcyc/dva-plugin-autosync)

**Comment by xuan45** [comment]
dva结合react native的脚手架[dva-native-cli](https://github.com/xuan45/dva-native-cli)

**Comment by dkvirus** [comment]
实际工作中遇到的 dva 相关问题但是没有文档的：[我学dva那些事](https://www.jianshu.com/p/96b5d9d9ad80)

**Comment by sunnysk** [comment]
@sorrycc  看图里面react生命周期componentDidMount里面写到可以执行setState，目前项目里面eslint规则不允许在didMount里面用setState。
https://segmentfault.com/q/1010000014789687/a-1020000014790390

**Comment by dgeibi** [comment]
[dva-hot: HMR plugin for dva without babel](https://github.com/dgeibi/dva-hot)

**Comment by sorrycc** [comment]
https://www.rails365.net/playlists/qing-song-xue-dva

**Comment by sorrycc** [comment]
https://github.com/Jetsly/dva-vue

**Comment by QinZonger** [comment]
> [generator-dva](https://www.npmjs.com/package/generator-dva)，自己基于yeoman-generator写的一个react + dva的脚手架

安装包的时候会报错

**Comment by elowes** [comment]
> > [generator-dva](https://www.npmjs.com/package/generator-dva)，自己基于yeoman-generator写的一个react + dva的脚手架
> 
> 安装包的时候会报错

我这边在Windows和MacOS系统下均测试正常，安装依赖的话，如果是node-sass报错的话，是因为被墙了，需自行翻墙或使用cnpm
