### ISSUE TITLE
请教下 dva2.0 使用 typescript 的问题

### ISSUE THREAD

**Issue by dkvirus** [dvajs/dva#1753]
# 1. 需求

现在需要将用 dva 写的项目升级为 typescript 版本，在 issue 库里翻了许久，基本都是说使用 typescript 遇到报错信息的，只有一个 issue 提供一个 [typescript + dva demo](https://github.com/sorrycc/dva-boilerplate-typescript)，我跑了一下，发行运行都报错。看了下版本，dva 还是 1.1 版本的。

# 2. 期望

求 dva2.0 + typescript 的完整 demo 供学习参考。或者已经做过集成的同学提供下思路。

# 3. 疑惑

最后有个不太明白的地方。就是 typescript 是 javascript 的超集，本身就已经兼容 es6 语法，之后使用 tsc 变异成 es5 的代码，那为什么我看到有些代码还用到 babel，这样岂不是重复了吗？？

**Comment by sjy** [comment]
1. 可以尝试提PR写个更新的例子
2. 简单来说 babel更加灵活可配置，各种插件支持也好；tsc可以保证美好的类型检查
 > Proper type-checking, but compilation handled by Babel 😎

相关链接： https://www.zhihu.com/question/34867499
推荐阅读： http://artsy.github.io/blog/2017/11/27/Babel-7-and-TypeScript/

**Comment by dkvirus** [comment]
@sjy 受教了兄台。我是刚接触 typescript 的小白，看官网例子单独用 ts 还可以，写完之后用 tsc 编译一下运行，把它和 dva 揉到一起就不知道咋弄了，难道是先 tsc 编译，再 roadhog 启动项目..............

想着如果有代码能参考，也是极好的，提 pr 有压力呀。

**Comment by sorrycc** [comment]
https://github.com/umijs/umi-examples/tree/master/ts
umi + dva 有个 ts 的例子，dva 的还没有整理。

**Comment by iceberg211** [comment]
我用roadhog+dva+typescript跑起来了demo，只是热更新不知道怎么去配。

**Comment by dkvirus** [comment]
@iceberg211 哥们，能否提供下你写的 demo 地址，参考学习一下。

**Comment by dkvirus** [comment]
找到个哥们写的 demo，实测有用： [ts-dva](https://github.com/huang6349/ts-dva)

**Comment by ImJoeHs** [comment]
一是 babel 的各种plugin，二是 ts 并不处理 polyfill 的问题，最终还是要手动引入。

**Comment by WinwardZ** [comment]
我倒是在写了一个  dva + react +  typescript + scss 的 项目。
也在封装  react + typescript + redux 的脚手架   。
