### ISSUE TITLE
dynamic.d.ts签名是否有误？

### ISSUE THREAD

**Issue by dicklwm** [dvajs/dva#1758]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
```js
// dynamic.d.ts
declare const dynamic: (resolve: (value?: PromiseLike<any>) => void) => void;
```
```js
// component?: React.ComponentType<RouteComponentProps<any>> | React.ComponentType<any>;
component={dynamic({
  app,
  dynamics
})}
```

#### Expected behavior: (预期的正常效果)
component应赋给ComponentType

#### Actual behavior: (实际效果)
dynamic返回void，且接收参数对照API文档，好像不太对

#### Versions of packages used: (哪个库的哪个版本出现的问题)
v2.3.1

**Comment by zyc017** [comment]
@sorrycc

**Comment by sorrycc** [comment]
有兴趣提个 PR 吗？

**Comment by zyc017** [comment]
![image](https://user-images.githubusercontent.com/18179573/43812165-85f3b432-9af2-11e8-934e-7ed9ceb63000.png)
![image](https://user-images.githubusercontent.com/18179573/43812184-9907e02a-9af2-11e8-9c35-5d66a0036995.png)
![image](https://user-images.githubusercontent.com/18179573/43812187-a15f283c-9af2-11e8-8caa-d75ffc4b347f.png)
感觉函数和函数签名并没有对应上
@sorrycc

**Comment by moJiXiang** [comment]
这个还请过一下pr吧，不然现在使用dynamic检查不通过的。

**Comment by dicklwm** [comment]
#1876 @sorrycc @moJiXiang

**Comment by wanliyunyan** [comment]
这个问题很久了，作者呢。。。。。。用ts的人都卡在这里了，没法动态加载

**Comment by zyc017** [comment]
自己覆写下吧

**Comment by narrowizard** [comment]
same error

**Comment by wanliyunyan** [comment]
这issue要被关闭了.....

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/54339928-2b1bc600-4671-11e9-8c39-9ae9165a1c0a.png)

有人关心就不会被 Close。

**Comment by wanliyunyan** [comment]
哥们，咱们用ts的用dynamic类型报错，我不知道怎么改，要不然我肯定pr了，ts的类型太复杂了，你看看你能改一下吗

**Comment by yangjunjie520** [comment]
请问这个·参数对不上问题

> 自己覆写下吧

请问下 是复写dynamic的类型断言么

**Comment by BoBoooooo** [comment]
同问
