### ISSUE TITLE
npm start 报错  windows 64 系统

### ISSUE THREAD

**Issue by aizhimin** [dvajs/dva#176]
E:\dva-quickstart>cnpm start

> @ start E:\dva-quickstart
> dora --plugins "proxy,webpack,webpack-hmr"

          proxy: load rule from proxy.config.js
temp certs cleared
          proxy: listened on 8989
'openssl' 不是内部或外部命令，也不是可运行的
程序
或批处理文件。
'openssl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
=============
rootCA generated at :
C:\Users\aizhimin\.anyproxy_certs
=============
rootCA generated
please trust the rootCA.crt in C:\Users\aizhimin\.anyproxy_certs\
or you may get it via anyproxy webinterface
�  1/3 build modules'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
�  457/457 build modules
webpack: bundle build is now finished.

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues/39#issuecomment-239738951
改下 package.json ，禁用 proxy 插件，这个插件在 window 下安装比较麻烦。

**Comment by aizhimin** [comment]
对开发没影响吧？  在mac上有这个问题吗？

**Comment by sorrycc** [comment]
不能用 mock 的功能，mac 上没问题。

**Comment by Wkevin8** [comment]
可以npm install cross-env
"start": "dora --plugins \"proxy,webpack,webpack-hmr\"",

**Comment by Wkevin8** [comment]
可以npm install cross-env
start命令增加一个
"start": "cross-env dora --plugins "proxy,webpack,webpack-hmr"",
