### ISSUE TITLE
build 后报错

### ISSUE THREAD

**Issue by Rpeanut** [dvajs/dva#1760]
#### 本地开发没问题，build 后，访问服务器，报错
umi.14bec85c.js 文件报错（umi.14bec85c.js:1 TypeError: e is not a function
    at umi.14bec85c.js:1
    at Array.map (<anonymous>)
    at umi.14bec85c.js:1
    at r (umi.14bec85c.js:1)
    at r (umi.14bec85c.js:1)
    at Object.r (umi.14bec85c.js:1)
    at Object.t [as start] (umi.14bec85c.js:1)
    at t.value (umi.14bec85c.js:1)
    at Sn (umi.14bec85c.js:1)
    at Rn (umi.14bec85c.js:1)）

#### Versions of packages used:  
    "dva": "^2.3.0",
    "nprogress": "^0.2.0",
    "umi": "^1.0.0",
    "umi-plugin-dva": "^0.7.1"

**Comment by Rpeanut** [comment]
@sorrycc 云谦大大帮忙看下呗

**Comment by Rpeanut** [comment]
umi 升级到1.38还是报错 @sorrycc

**Comment by sorrycc** [comment]
umi-plugin-dva 更新到 0.9 试试？

**Comment by Rpeanut** [comment]
@sorrycc 不好意思，我这边配置有问题，找到了不该如下配置，麻烦啦
```javascript
import { message } from 'antd'
import { createLogger } from 'redux-logger'

const logger = process.env.NODE_ENV === 'production' ? () => {} : createLogger
export default {
  onAction: logger(),
  onError (e) {
    e.preventDefault()
    message.error(e.message)
  },
}
```
