### ISSUE TITLE
effects里面使用put不进入reducer

### ISSUE THREAD

**Issue by wuyunjiang** [dvajs/dva#1766]
在effects中使用循环多次请求接口，我不希望他阻塞。在请求完成后自动去then中改变State。但是现在的问题是可以打印出data，却不能进入到`changeState`reducer里面
```javascript
for (var i = 0; i < dataArr.length; i++) {
  请求数据( ).then(data => {
    console.log(data)
    put({
      type: 'changeState',
      payload: { 
        type: type,
        data: data
      }
    })
  })
}
```
非常感谢，能帮我解决下 @sorrycc

**Comment by wuyunjiang** [comment]
有人能帮忙解决下吗？

**Comment by xujie-phper** [comment]
一个effect就干一件事，你如果想请求多个接口，就拆分成多个effect，不要整一起。而且effects中的请求接口通过call来完成，使用generator，你这是在组件里面的用法，不应该在effects里面使用

**Comment by wuyunjiang** [comment]
其他地方我确实是你说的这样做的，不过这里有个需求比较特殊，我实际第一次请求获得的一个id数组，想再根据id获得每个详细信息。而这个需求在项目很多地方用到，所以我不能写在组件里面

**Comment by wuyunjiang** [comment]
for里面的每个请求是一个耗时的操作，我希望每完成一个就自动设置给state，页面也同时做出响应，而不是等所有都完成。这样用户体验不是很好

**Comment by fangkyi03** [comment]
那你改成在里面put就行了 没啥影响

**Comment by wuyunjiang** [comment]
这样就只能在上个请求完全完成后，才能开始下个请求。没法同时发起请求。总的时间是没有变化的

**Comment by fangkyi03** [comment]
在call以后直接put就可以了 没影响

**Comment by wuyunjiang** [comment]
嗯，我先试试，谢谢

**Comment by wuyunjiang** [comment]
我使用yield call的方式并不能同时去请求，
![image](https://user-images.githubusercontent.com/16558218/41699938-d591f4a0-7558-11e8-9e8a-c346c2fc275a.png)
我希望请求方式是这样的
![image](https://user-images.githubusercontent.com/16558218/41700014-29d5f552-7559-11e8-8d49-d2b9d1b59bb3.png)

**Comment by wuyunjiang** [comment]
@fangkyi03 现在的问题是，使用then的方式，`console.log(data)`可以被执行到，但却进不了reducer方法里

**Comment by wuyunjiang** [comment]
@sorrycc @yinheli @yiminghe 可以帮我看一下吗，非常感谢

**Comment by sorrycc** [comment]
试试这样？

```
const results = yield all([
  call(a),
  call(b),
]);
yield put(actionWithResults);
```

`yield all` 用于并行发起多个请求。

**Comment by sorrycc** [comment]
另外，在 effect 里的函数里是不能再使用 yield 的，比如 `.then(() => ...)`。

**Comment by wuyunjiang** [comment]
嗯，感谢，现在确实是同时发起的请求，不过还是不太明白  怎么在每个请求完成后去设置state的值

**Comment by wuyunjiang** [comment]
现在还是要等待所有的都完成了才能设置state的值，如果某一个很耗时，就会影响到其他数据的展示

**Comment by yinheli** [comment]
@wuyunjiang 那还是应该拆成多个 effect 来处理。

**Comment by wuyunjiang** [comment]
我试过在这个effect调用另一个effect，但是这里用的put，没法像dispatch一样后面跟then

**Comment by wuyunjiang** [comment]
很奇怪的是，我调用另一个effect，依然是能打印出data，却不能进入reducer
#### `effectA`
```javascript
for (var i = 0; i < dataArr.length; i++) {
  yield put({
    type:"effectB",
    payload:{
      type:type,
    }
  })
}
```
#### `effectB`
```javascript
let data = yield call(请求方法, parse(payload))
if(data){
  console.log("data",data)//这里能打印
  put({
    type: 'updateState',//这里进不去reducer
    payload: { 
      data: data
    }
  })
}
```

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/41780670-fdbc5ab4-7667-11e8-8e24-af0f6b63af05.png)
如果你要没一条数据请求完就刷新 在这里处理就可以了
