### ISSUE TITLE
使用 antd  报错  【windows】

### ISSUE THREAD

**Issue by aizhimin** [dvajs/dva#177]
UnKnown   plugin “import” specified in "base"

webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd',
    style: 'css',
  }]);

这样添加有问题吗？

**Comment by sorrycc** [comment]
没安装 `babel-plugin-import` 依赖?

**Comment by aizhimin** [comment]
怎么检查是否安装？我已经执行过  命令 ： npm install antd babel-plugin-import --save

不过是通过  cnpm

**Comment by sorrycc** [comment]
babel 版本?

**Comment by sorrycc** [comment]
package.json 贴上来看下。

**Comment by aizhimin** [comment]
{
  "private": true,
  "entry": {
    "index": "./src/index.js"
  },
  "dependencies": {
    "dva": "^1.1.0",
    "react": "^15.1.0",
    "react-dom": "^15.1.0"
  },
  "devDependencies": {
    "atool-build": "^0.7.6",
    "atool-test-mocha": "^0.1.5",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-dva-hmr": "^0.1.0",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-runtime": "^6.9.2",
    "dora": "0.3.x",
    "dora-plugin-webpack": "0.6.x",
    "dora-plugin-webpack-hmr": "^0.1.0",
    "expect": "^1.20.2",
    "redbox-react": "^1.2.10"
  },
  "scripts": {
    "start": "dora --plugins \"webpack,webpack-hmr\"",
    "build": "atool-build",
    "test": "atool-test-mocha ./src/**/*-test.js"
  }
}

**Comment by sorrycc** [comment]
没看到 `babel-plugin-import` 依赖。

**Comment by aizhimin** [comment]
我已经安装了   需要在这里配置？
怎么配置？

**Comment by aizhimin** [comment]
执行完安装命令之后，需要配置  package.json？不是自动写进去的？文档上没写清楚。
要配置的话，我怎么查刚刚安装好的 babel-plugin-import  版本？

**Comment by sorrycc** [comment]
自动写进去的，你是在项目根目录执行的命令吗? 或者 npm install 没执行成功? 这个问题太基础了，建议多了解下 node/npm 的机制。

**Comment by aizhimin** [comment]
是没在项目跟目录执行该命令
