### ISSUE TITLE
关于一个model去访问另外一个model的action的问题

### ISSUE THREAD

**Issue by haydonduan** [dvajs/dva#1776]
前提：一个model绑定一个namespace
问题：如果在一个model对应的页面去dispatch另一个model的action，就会调不通

我觉得dva的设计可能就是利用model想把不用业务或者不同领域的action分开

但是如果有一个通用的组件（把dispatch写到了这个组件里），在不同的model对应的页面在发dispatch请求，会调不通。

所以我现在的做法是把namespace传到这个通用的组件中，但是很2。在两个model中都要定义这个action。

有什么好的方法吗？或者我是不是搞错了？或者这种设计就不对？I want you!

**Comment by ghostriderxx** [comment]
dispatch("namespace/effect或reducer")这样可以，附加命名空间。。

**Comment by dkvirus** [comment]
@haydonduan  检查下你有没有注册另一个 model。

**Comment by haydonduan** [comment]
对不起，我刚看到配置model时是一个数组。。。 谢谢大家
