### ISSUE TITLE
fecth应该封装个中止请求

### ISSUE THREAD

**Issue by wushuxuan** [dvajs/dva#1778]
页面离开之后，要关闭一些正在等待中的请求，所以要中断这些无用的请求

**Comment by sorrycc** [comment]
可以提需求给 whatwg/fetch 。

**Comment by ybning** [comment]
我也遇到这个问题点 https://github.com/dvajs/dva/issues/1838

**Comment by neewbee** [comment]
> [https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort](url)

```javascript
var controller = new AbortController();
var signal = controller.signal;

var downloadBtn = document.querySelector('.download');
var abortBtn = document.querySelector('.abort');

downloadBtn.addEventListener('click', fetchVideo);

abortBtn.addEventListener('click', function() {
  controller.abort();
  console.log('Download aborted');
});

function fetchVideo() {
  ...
  fetch(url, {signal}).then(function(response) {
    ...
  }).catch(function(e) {
    reports.textContent = 'Download error: ' + e.message;
  })
}
```

**Comment by evanoxu** [comment]
> 可以提需求给 whatwg/fetch 。

关于如何取消 fetch，曾有过许多讨论，也有很多的方案被提出来。

1 最初的讨论：whatwg/fetch#27
2 Cancelable promise 的方案被否了：tc39/proposal-cancelable-promises#4
3 其它方案继续讨论：whatwg/fetch#447
4 讨论出的提案：whatwg/fetch#447 (comment)
5 whatwg 最终给出的标准：https://dom.spec.whatwg.org/#dom-abortcontroller-abortcontroller
6 MDN 使用文档：https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController
