### ISSUE TITLE
onError问题，请问如何在异步请求Promise里，报错时触发onError

### ISSUE THREAD

**Issue by DXDZY** [dvajs/dva#1782]

**Comment by sorrycc** [comment]
onError 只覆盖 effect 和 subscription 的场景。

**Comment by DXDZY** [comment]
@sorrycc 我是想在effect中，发起异步请求的时候，异步请求是封装的公共方法，如果后端返回的是错误码，并带有错误信息，我想统一将错误信息抛出，并由onError统一处理，而不是将整个后端返回的数据反给effect，请问这种场景可以用onError解决吗。

**Comment by sorrycc** [comment]
> 发起异步请求的时候，异步请求是封装的公共方法

封装成 Promise，Promise reject 时就会走到 onError 的。

**Comment by DXDZY** [comment]
@sorrycc 好的 ，我试试，谢谢您的解答
