### ISSUE TITLE
为什么首次加载时间那么久

### ISSUE THREAD

**Issue by joknic** [dvajs/dva#1788]
![tim 20180701114749](https://user-images.githubusercontent.com/38077872/42130881-0c342c20-7d25-11e8-80de-84b88f257c11.png)

**Comment by sg-zzk** [comment]
蓝色的是下载耗时，但是有个很奇怪的现象，你那个 322KB 的JS为什么是在前面 86.6KB 的 JS 加载完之后才开始下载的 ？
正常情况应该在页面打开之后立即开始下载，好好看下是不是有不应该的依赖关系。

建议这种和框架本身没什么关系的问题去 seagmentfault 提，来仓库 issue 说真的有点业余了。
