### ISSUE TITLE
npm start 时，如果修改启用端口？

### ISSUE THREAD

**Issue by edire** [dvajs/dva#179]
因为多个项目想同事跑起来。

**Comment by nikogu** [comment]
https://github.com/dvajs/dva/blob/master/examples/user-dashboard/package.json#L34

`"start": "dora -p 7001 --plugins \"proxy,webpack,webpack-hmr\"",`

**Comment by edire** [comment]
fanmingfeideMacBook-Pro:dva fanmingfei$ npm start

> @ start /Users/fanmingfei/360work/dva
> dora -p 7001 --plugins "proxy,webpack,webpack-hmr"

          proxy: load rule from proxy.config.js
          proxy: listened on 8989
Caught exception: Error: listen EADDRINUSE :::8989
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1238:14)
    at listen (net.js:1274:10)
    at Server.listen (net.js:1370:5)
    at /Users/fanmingfei/360work/dva/node_modules/dora-anyproxy/proxy.js:125:38
    at /Users/fanmingfei/360work/dva/node_modules/dora-anyproxy/node_modules/async/lib/async.js:607:21
    at /Users/fanmingfei/360work/dva/node_modules/dora-anyproxy/node_modules/async/lib/async.js:246:17
    at iterate (/Users/fanmingfei/360work/dva/node_modules/dora-anyproxy/node_modules/async/lib/async.js:146:13)
    at /Users/fanmingfei/360work/dva/node_modules/dora-anyproxy/node_modules/async/lib/async.js:157:25
AnyProxy is about to exit with code: 0

**Comment by nikogu** [comment]
如果是需要改代理端口，参看文档：https://github.com/dora-js/dora-plugin-proxy

**Comment by edire** [comment]
https://github.com/dora-js/dora-plugin-proxy/blob/master/src/index.js#L19
这句话 里面的 query.port 需要怎么传过来。。 没找到demo

**Comment by sorrycc** [comment]
```
"start": "dora -p 7001 --plugins \"proxy?port=8888,webpack,webpack-hmr\"",
```

**Comment by edire** [comment]
谢谢~

**Comment by ryli** [comment]
```
// 项目 A
"start": "dora -p 8001 --plugins \"proxy?port=8002&watchDirs=./mock,webpack,webpack-hmr\"",

// 项目 B
"start": "dora -p 9001 --plugins \"proxy?port=9002&watchDirs=./mock,webpack,webpack-hmr\"",
```

访问 8001, 9001 端口，不能使用代理。
访问 8002, 9002 端口，会有一个退出。

```
npm start

> @ start /Users/x/context/react/d1
> dora -p 8001 --plugins "proxy?port=8002&watchDirs=./mock,webpack,webpack-hmr"

          proxy: load rule from proxy.config.js
(node:31158) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8002
📦  2/5 build modules[babel-plugin-dva-hmr][INFO] got routerPath ./router
📦  464/464 build modules
webpack: bundle build is now finished.

Caught exception: Error: ENOENT: no such file or directory, open '/Users/x/.anyproxy/cache_r154031/res_body_6'
AnyProxy is about to exit with code: 0
```

**Comment by ityao** [comment]
顶楼上, 同问, 我也遇到这个问题, 不能同时打开桌面端和移动端的来开发测试

**Comment by sorrycc** [comment]
@ityao npm start 里内容贴出来看下？dora 和 roadhog 对于端口设置的方案不同。

**Comment by luocong2016** [comment]
遇到一模一样的问题

// 项目 A
"start": "dora -p 3100 --plugins \"proxy?port=8989\"",

// 项目 B
"start": "dora -p 31001 --plugins \"proxy?port=8988\"",

项目每次打开 pm2 会重启服务，
nginx 会返回502
