### ISSUE TITLE
文档官网（ant.design）打不开了

### ISSUE THREAD

**Issue by engineerFrankLiu** [dvajs/dva#1791]
亲~ https://ant.design/ 打不开了
坐标：国外
非常确定；电脑是联网了的；google 什么都没问题

![image](https://user-images.githubusercontent.com/40782860/42197713-51a83a0a-7eae-11e8-8334-740fe6e82009.png)

**Comment by yinlv** [comment]
亲，作为专业人士，打不开分很多种情况。
首先你总得说下哪些是好的哪些是坏的？

DNS 解析是否正常？ 服务器是否能连接？ 服务器资源下载速度是不是为0？
