### ISSUE TITLE
react dva怎么在生产环境删除console

### ISSUE THREAD

**Issue by Wish-ljh** [dvajs/dva#1794]

**Comment by Wish-ljh** [comment]
在生产环境怎么配置把console删除

**Comment by yinlv** [comment]
```
plugins: [
      new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: '"production"',
          isDev: 'false'
        }
      }),
      ······
]
```
生产环境需要严格设置 process.env.NODE_ENV = 'production'
很多库都会读这个变量来确定你是不是生产版本，
开发版本的值是 development

**Comment by Wish-ljh** [comment]
目前方法已经找到 
env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
    },
    production:{
      extraBabelPlugins:[["transform-remove-console"]],
      publicPath: '/static/',
    }
  },
我是这样配置的

**Comment by yinlv** [comment]
吓晕，你还能强制删除 console 的！！！
那你代码抛错和抛警告怎么办！？？

**Comment by Wish-ljh** [comment]
这个只会删除console.log 并且只会在生产环境生效 这个是babel的一个插件
地址 ： https://babeljs.io/docs/en/babel-plugin-transform-remove-console/

**Comment by yinlv** [comment]
emmmmm, 不过我还是很好奇，为啥你的 dva 会有一堆 console.log ，
我的好好地啥也没有啊 ~ 开发环境也没一堆 console.log
