### ISSUE TITLE
dynamic 每次点击没有加载过的路由都要重新渲染整个页面？

### ISSUE THREAD

**Issue by 6691** [dvajs/dva#1795]
代码如下：

import React from 'react';
import {Router, Route, Switch} from 'dva/router';
import dynamic from 'dva/dynamic'

function RouterConfig({history,app}) {

	const AdminIndex = dynamic({
		app,
		models: () => [import('./models/admin/index')],
		component: () => import('./routes/Admin/Index'),
	});
	const AdminHelp = dynamic({
		app,
		component: () => import('./routes/Admin/AdminHelp'),
	});

	const GameKeep = dynamic({
		app,
		models: () => [import('./models/admin/game/keep')],
		component: () => import('./routes/Admin/Game/Keep/Index'),
	});
	
	return (
		<Router history={history}>
			<Switch>
				<Route path="/admin/index" exact component={AdminIndex} />
				<Route path="/admin/help" exact component={AdminHelp} />
				<Route path="/admin/game/:id/keep" exact component={GameKeep} />
			</Switch>
		</Router>
	);
}

问题： 每次点击没有加载过的路由都要重新渲染整个页面，这是怎么回事？？
问题： 每次点击没有加载过的路由都要重新渲染整个页面，这是怎么回事？？
问题： 每次点击没有加载过的路由都要重新渲染整个页面，这是怎么回事？？

{  
  "dependencies": {
    "antd": "^3.6.3",
    "babel-plugin-import": "^1.8.0",
    "blueimp-md5": "^2.10.0",
    "dva": "^2.3.1",
    "dva-loading": "^2.0.3",
    "moment": "^2.22.2",
    "path-to-regexp": "^2.2.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "babel-plugin-dva-hmr": "^0.3.2",
    "eslint": "^4.14.0",
    "eslint-config-umi": "^0.1.1",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "husky": "^0.12.0",
    "redbox-react": "^1.4.3",
    "roadhog": "^2.0.0"
  }
}

**Comment by yinlv** [comment]
额，大佬不妨看看是不是 history 对象的问题？
感觉 router 应该不会导致页面直接重载，
如果需要某些页面持久不重载，那你应该有一个 父 Route  path="/"，
在父 Route 对应的页面里写 Switch 再写 route
