### ISSUE TITLE
Using multiple global models will make reducers be called twice on subscription

### ISSUE THREAD

**Issue by SHITianhao** [dvajs/dva#1797]
I find DVA accepting the global model (prefixed model) as an array from [here](https://github.com/dvajs/dva/blob/79d4cfec1640e2b67cbdc13c59075e8793544b20/packages/dva-core/src/index.js#L60). From my perspective, it should be fine when multiple models are defined through `app.model` function. But somehow the reducers are called **twice** when I dispatch the action inside setup.

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

Having two prefixed models

```js
// 1. Initialize
const app = dva();
// 2. Model
app.model(require('./models/first'));
app.model(require('./models/second'));
``` 
In  **./models/first**

```
export default {
  namespace: 'first',
  state: {
     done: false,
  },
  subscriptions: {
    setup({ dispatch }) {
      dispatch({ type: 'doSthFirst' })
    },
  },
  effects: {
    *doSthFirst(_, { put }) {
      yield put({ type: 'doneFirst' });
    },
  },
  reducers: {
    doneFirst(state, action) {
      console.log('First Done')
      return { ...state, done: true };
    },
  },
};
```
In  **./models/second**

```
export default {
  namespace: 'second',
  state: {
     done: false,
  },
  subscriptions: {
    setup({ dispatch }) {
      dispatch({ type: 'doSthSecond' })
    },
  },
  effects: {
    *doSthSecond(_, { put }) {
      yield put({ type: 'doneSecond' });
    },
  },
  reducers: {
    doneSecond(state, action) {
      console.log('Second Done')
      return { ...state, done: true };
    },
  },
};
```
#### Expected behavior: (预期的正常效果)

```
First Done
Second Done
```

#### Actual behavior: (实际效果)

```
First Done
Second Done
First Done
Second Done
```

#### Versions of packages used: (哪个库的哪个版本出现的问题)
DVA 2.3.1

**Comment by SHITianhao** [comment]
This "bug" comes from Redux DevTools. Somehow it dispatch the actions twice

**Comment by sg-zzk** [comment]
看一下是否是因为 subscription 执行了两次呢？

**Comment by SHITianhao** [comment]
subscription, effects 都是只有一次，只有reducer 执行了两次
