### ISSUE TITLE
Unexpected key 'XXX' found in previous state received by the reducer

### ISSUE THREAD

**Issue by vipcxj** [dvajs/dva#1803]
# 问题原因
这是在调用dva的unmodel时由redux发出的警告，经过深入调试，发现问题出在dva源码[这一行](https://github.com/dvajs/dva/blob/master/packages/dva-core/src/index.js#L114)，在调用`createReducer`时，已有的state中被unmodel掉的那个key还存在着，但redux在新传入的reducers中找不到这个key，于是就发出了这个警告。
# 解决方案
在unmodel前，清理掉state中对应的数据

**Comment by sorrycc** [comment]
有兴趣提个 PR 吗？

**Comment by vipcxj** [comment]
有空的话可以试试，不过得先请教几个问题~ 
- dispatch一个action一定是能同步得到结果的吗？
- dva源码中哪里可以插入一个全局的reducer（不局限于某个namespace）

我想到的解决步骤是这样的
- 初始化dva时，加一个全局的reducer（不局限于某个namespace），这个reducer接受特定action用于清除某个namspace下的state
- 在unmodel前dispatch上面提到的特定action来清除过期state，这里自然必须保证dispatch这一步是同步的。
