### ISSUE TITLE
antd+dva 发送post 请求 (404) get请求是ok的(200) 求大神啊 搞了一天了

### ISSUE THREAD

**Issue by RisingSunYZ** [dvajs/dva#1805]
```
`export async function doApprove(params) {

  // return request(`/portal/api/process/saveSp.jhtml?${stringify(params)}`);//这个是好的
  return request('/portal/api/process/saveSp.jhtml', {
    method: 'POST',
    body: params
  });
}`
```

roadhogrc.mock.js 文件

`  'POST /portal/api/process/saveSp.jhtml': (req, res) => {
    res.send( {code:'1',
      msg:'操作成功',
      data:{
      }});
  },`

**Comment by s97712** [comment]
POST 不是你想换, 想换就能换

**Comment by RisingSunYZ** [comment]
现在post不是404了 但是参数穿不过去 接受不到 后台是springmvc

**Comment by memoryza** [comment]
@RisingSunYZ  这要看你发送的Content-Type 是什么类型啊，请求能过去，无法携带参数就要看headers 的配置了

**Comment by littleLane** [comment]
推荐使用 formdata 格式传递数据，更简单的方法就是用 qs
