### ISSUE TITLE
如何把dva的 redux 打包放进另外的库中使用？是否可行？

### ISSUE THREAD

**Issue by shenqihui** [dvajs/dva#1806]
想在 Taro 这个小程序框架中使用 dva 模式的 redux ，看了下类型的方案，都没有 dva 的模式好。

看了些 dva-core ，想把它迁移进 Taro 来小程序的开发。

不知道可行否？目前正在尝试中。

**Comment by vipcxj** [comment]
redux不是dva的一部分～ 不如说是dva封装了redux～

**Comment by shenqihui** [comment]
@vipcxj dva 的封装的 redux 比较好，想偷懒点，用 dva 封装的方法直接扔进新框架。

**Comment by vipcxj** [comment]
那你直接用个dva-core就行了吧

**Comment by shenqihui** [comment]
实现了，直接用 dva-core 直接不用复杂操作。

**Comment by shenqihui** [comment]
@sorrycc  
https://github.com/shenqihui/taro_scaffold   
这是我写的 Taro 的脚手架，[集成了 dva](https://github.com/shenqihui/taro_scaffold/commit/f6cb9e03ad8c3bf0e9b67b64f469323c9385eebf) 。  里面的 dva-core 及 dva-loading 插件都是直接放进 src 目录的。只是进行了 module.export 的改动，其他基本没变化。

目前 Taro 不会编译 node_modules 下面的文件(只能放进 src)，所以里面的依赖也不会自动编译完成。所以如果想使用 npm 版本的包，我感觉需要打包出一个完整依赖的包才能直接调用。

**Comment by shenqihui** [comment]
类似于
https://github.com/shenqihui/taro_scaffold/issues/2#issuecomment-405574054

**Comment by zuoge85** [comment]
已经成功 https://github.com/zuoge85/taro-dva
@shenqihui
