### ISSUE TITLE
ie11下报SCRIPT5022引发了但未捕获异常错误

### ISSUE THREAD

**Issue by Y-wson** [dvajs/dva#1807]
1.开发环境在ie11下没有问题，部署以后在ie11下就出现这种问题

![2222](https://user-images.githubusercontent.com/17841561/42618741-92ce28a0-85e8-11e8-82f3-dd275d5ecc9b.jpg)
点击script5022，
![3331](https://user-images.githubusercontent.com/17841561/42618816-cc03d2aa-85e8-11e8-94a9-aa6cde783437.jpg)

点击对应代码
![4444](https://user-images.githubusercontent.com/17841561/42618912-f84bb15c-85e8-11e8-9754-828d73fbcaa6.jpg)
ie11一直空白出不来，请问是什么问题

@sorrycc

**Comment by SHITianhao** [comment]
相关issues 
* https://github.com/dvajs/dva/issues/1688
* https://github.com/dvajs/dva/issues/1696

**错误提示**
`roadhog dev` 下一切正常, `COMPRESS=none roadhog build` 编译后出错
```
React.Children.only expected to receive a single React element child
The above error occurred in the <Provider> component:
                   in Provider (created by DvaRoot)
                   in DvaRoot
```
**尝试解决方案**
1. 正确在`index.js` 第一行引入 `import '@babel/polyfill'` 任然报错
2. 使用`COMPRESS=none`编译依然报错
3. roadhog 已经是最新版本`2.4.2`

@sorrycc

**Comment by SHITianhao** [comment]
@Y-wson `roadhog` 切换到**2.4.1**试一下

**Comment by SHITianhao** [comment]
## 原因已找到
就是这个 https://github.com/facebook/react/issues/8379 
`react` 在 IE11 中需要对 `Symbol` 提供 polyfill。但是由于我是通过 CDN导入react, 所以在`index.js`第一行 `import '@babel/polyfill'` 会导致polyfill 在`react`之后运行。

@sorrycc 但是**不清楚**为何将 `NODE_ENV` 设为 `production` 会导致这个问题。

**Comment by yoyo837** [comment]
把你的@babel/polyfill也改为cdn的吧
