### ISSUE TITLE
关于subscriptions订阅和BrowserRouter的问题

### ISSUE THREAD

**Issue by wanliyunyan** [dvajs/dva#1814]
我一直在使用Router，今天控制台突然报了很多错误，比如
 ` You should not use <Link> outside a <Router>`
` The above error occurred in the <Link> component`
上网查说需要改成 BrowserRouter，然后依然报这两个错误，求解！！
![image](https://user-images.githubusercontent.com/10751248/42755962-b220ecbe-892c-11e8-8a02-242eab24fff8.png)

初始化dva 的时候，因为报错，用默认的history是不报错的，我就想改成createBrowserHistory 
`import createBrowserHistory from 'history/createBrowserHistory';`
`const app = dva({history: createBrowserHistory()});`
![image](https://user-images.githubusercontent.com/10751248/42755839-4f57d89a-892c-11e8-8dcc-2d1feb00336b.png)

`
export default function({ history }) {    
  return (    
    <ConnectedRouter history={history}>    
      <BrowserRouter>   
        <Switch>    
          <Route path="/login" component={UserLayout} />
          <Route path="/" component={BasicLayout} />
        </Switch>
      </BrowserRouter>
    </ConnectedRouter>
  );
}
`
![image](https://user-images.githubusercontent.com/10751248/42755799-31b6dca0-892c-11e8-95f7-85097e24fd6a.png)

我采用这种方式
model中 
![image](https://user-images.githubusercontent.com/10751248/42755571-4d02a38c-892b-11e8-8335-c3f43ccd976c.png)
当切换路由的时候，根本就不触发这个监听事件啊？？？怎么办？？？？求解！！！
我只有刷新页面才会触发 订阅事件
 https://github.com/dvajs/dva/issues/1498
https://github.com/dvajs/dva/issues/1497

我也都看过了，帮帮我，我实在无能为力了

**Comment by wanliyunyan** [comment]
当我删去 BrowserRouter ，订阅事件就好使了，但是我始终不知道 BrowserRouter 该加在哪里

**Comment by wanliyunyan** [comment]
我弄明白了BrowserRouter 其实就是Router中包裹了一个history，所以不能用，为了不让控制台报错，我用了一个不是办法的办法
在link外 加一层这个 `<Router history={this.props.history}>`
起码控制台不报错了

**Comment by wanliyunyan** [comment]
https://github.com/react-component/menu/pull/175

**Comment by huaentandd01** [comment]
em....这个不是真正的解决方案吧...

**Comment by huaentandd01** [comment]
目前我也遇到了这个问题，使用BrowserRouter的时候subscription不起作用....
我的需求是要使用BrowserRouter的getUserConfirmation 😢

**Comment by huaentandd01** [comment]
看了一下后发现是由于使用的history实例不同，所以可以在dva配置那里直接传了

```js
function getUserConfirmation(dialogKey, callback) {
  // dosomething

  callback(true);
}

appOptions.history = createBrowserHistory({
  getUserConfirmation
});

const app = dva(appOptions);
```
