### ISSUE TITLE
Got `You should not use <Link> outside a <Router>` error when running the user-dashboard example

### ISSUE THREAD

**Issue by ericxinzhang** [dvajs/dva#1815]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
1. git克隆dva代码库到本地
2. 去到 `examples/user-dashboard`目录
3. 运行 `npm install` 安装依赖
4. 运行 `npm start` 

#### Expected behavior: (预期的正常效果)
`http://localhost:8000/` 应该返回user-dashboard的例子

#### Actual behavior: (实际效果)
出错
`You should not use <Link> outside a <Router>`

#### Versions of packages used: (哪个库的哪个版本出现的问题)
1. 运行正常的电脑是node v8.11.0, npm v5.6.0.
2. 运行出错的电脑的环境是node v10.4.0, npm v6.1.0.

我上传了两个package-lock.json文件供参考。
[user-dashboard.zip](https://github.com/dvajs/dva/files/2199748/user-dashboard.zip)

刚才用家里的电脑（node v8.11.0, npm v5.6.0）又试了下，把package-lock.json和node_modules删除以后再次安装，还是一切正常。貌似和npm的版本有关了，即npm6.1.0安装的依赖有版本冲突。

**Comment by wanliyunyan** [comment]
看来你也是这问题，react router 建议用 BrowserRouter 但是，没有用明白。。。。

**Comment by ericxinzhang** [comment]
> 看来你也是这问题，react router 建议用 BrowserRouter 但是，没有用明白。。。。

我还没有找到根本原因，现在的情况是，我几天前用node 8.x npm 5.6安装的可以跑，但是今天在另一台电脑上node 10.x npm6.1.0就不行了，代码应该完全一样，出错的这台电脑用旧那份package-lock.json就ok.

**Comment by wanliyunyan** [comment]
@ericxinzhang https://github.com/dvajs/dva/issues/1814 我是这么解决的，不知道和你是不是一个问题
