### ISSUE TITLE
支持 redux-saga 的 channel

### ISSUE THREAD

**Issue by s97712** [dvajs/dva#1818]
调用  put(channel, action) 后报错: dispatch: action should be a plain Object with type
这个类型检测我发现是由 dva检测的, 是否没有考虑到 channel?

**Comment by sorrycc** [comment]
channel 具体在啥场景下会用呢？

**Comment by s97712** [comment]
可以缓存action,  我目前是想用它来实现任务队列的.

**Comment by yoyo837** [comment]
我这里的场景是effect里callback的控制

**Comment by liji19910307** [comment]
effect里其他内容调用的callback的控制 这个怎么解决啊

**Comment by sjfkai** [comment]
现在支持 channel 了吗？ 或者说在dva下实现 多并发任务队列 有什么好的办法吗？

**Comment by yoyo837** [comment]
@sjfkai `put.resolve` ?

**Comment by xc1427** [comment]
watcher 里面自己自定义各种编排不行吗？
