### ISSUE TITLE
在subscriptions中定义setup方法，想通过history获得当前的location

### ISSUE THREAD

**Issue by huang6349** [dvajs/dva#182]
我在 subscriptions 中 定义了一个 setup 方法
我想通过 location 来初始化 menu 的 默认选择 菜单项，
在 react-router 中 有 history.getCurrentLocation() 来获得当前路由，
我 将 history 打印出来后，并没有找到 getCurrentLocation，
我该如何活到当前的 location ，我不想使用listen，因为我只想在应用初始化的时候调用一次

**Comment by sorrycc** [comment]
应用初始化的时候也会走 listen 的。

**Comment by huang6349** [comment]
那我使用 listen 会不会造成 菜单 多次被初始化的状况呢

**Comment by sorrycc** [comment]
你可以试下，`history.listen` 会在初始化以及路由变更的时候执行。

**Comment by huang6349** [comment]
我大致有了思路，我在listen之前申明一个变量，如果菜单已经被初始化过后就不再让菜单初始化了。

**Comment by huang6349** [comment]
3Q，感谢大神的指教
