### ISSUE TITLE
关于dispatch（） .then用法的疑惑

### ISSUE THREAD

**Issue by amelonsamy** [dvajs/dva#1823]
dispatch().then（），then的参数当中是否可以直接返回请求的结果，或者具体想知道then中是不是有默认返回的参数呢，还是直接是空的。

**Comment by sorrycc** [comment]
> then中是不是有默认返回的参数呢

会返回 effect 的返回值。

**Comment by Gzbox** [comment]
这是我调用的地方
![image](https://user-images.githubusercontent.com/21010051/54734974-3aa18e80-4bde-11e9-81c5-e4c01d998217.png)

打印的是response 是后台的数据，已获取到数据，resp  是我打印的.then返回的数据，没有值
![image](https://user-images.githubusercontent.com/21010051/54734990-560c9980-4bde-11e9-8ed4-b3f8fd9a00cf.png)

这是我的effect
![image](https://user-images.githubusercontent.com/21010051/54735049-9bc96200-4bde-11e9-907e-c482a3f22c3f.png)

这是我调用的api 
![image](https://user-images.githubusercontent.com/21010051/54735057-a8e65100-4bde-11e9-970c-c193f64b438c.png)


按着@sorrycc陈大你说的，应该有返回值的啊   是我哪里用的不对吗？

**Comment by johanazhu** [comment]
return response

**Comment by LPink777** [comment]
@sorrycc dispatch触发之后可以在dipatch({}).then中获取全局state的最新状态吗？

**Comment by ChanseaCem** [comment]
我也想知道dispatch触发之后可以在dipatch({}).then中获取全局state的最新状态吗？ @LPink777 @Gzbox @amelonsamy @

**Comment by xc1427** [comment]
@LPink777 @ChanseaCem 不行的。dispatch().then 推荐用来做比较 "轻量" 的操作，比如说通知 UI 层某个 effect 调用的结束，可以关闭 xx，可以提示 xx。

对于异步逻辑的组织应该尽量在 effect 中完成

**Comment by ChanseaCem** [comment]
你的意思是
effects: {
    *getProList({ payload }, { call, put }) {
      const res = yield call(getProList);
      if (res && res.code === 200) {
        yield put({
          type: 'setPro',
          payload: {
            data: res.data
          }
        })
      }
    },
}
then的意义表示这个yield call(getProList);的请求结束，而并不是 
       yield put({
          type: 'setPro',
          payload: {
            data: res.data
          }
        })
到reducers进行更新赋值结束。如果要拿最新的state就要使用userSelector。
比如：
@connect(({ yieldrate_group, loading }) => ({
  ...yieldrate_group
}))
class YieldRateGroup extends Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    this.initData();
  }
  saveData = (dispatch, data, fn) => {
    dispatch({
      type: 'yieldrate_group/setState',
      payload: {
        data: data
      }
    }).then(() => {
      if (fn) {
        fn(dispatch);
      }
    })
  }

  initData = () => {
    const { dispatch } = this.props;
    this.getProList(dispatch);
  }

  // 获取产品列表
  getProList = (dispatch) => {
    dispatch({
      type: 'yieldrate_group/getProList',
      payload: {}
    }).then(() => {
      this.getGrouptList(dispatch)
    })
  }

  //分组
  getGrouptList = (dispatch) => {
   const { pro_code, start_time, end_time, hours } = this.props;
    dispatch({
      type: 'yieldrate_group/getYieldAllList',
      payload: {
        values: {
          pro_code: pro_code,
          start_time: start_time,
          end_time: end_time,
          hours: hours,
          sort: type == 'ok' ? 'desc' : 'asc',
          type: type
        }
      }
    }).then(() => {
      ......
    })
  }

  ......
}

这里的获取产品列表的then后面调用的getGrouptList 方法里，
const { pro_code, start_time, end_time, hours } = this.props 这句代码，不应该直接调用，而是换成userSelector获取。
我这样的理解对吗？
顺便问下，之前我都用这个方式进行获取，都啥问题，就是偶尔会遇见获取最新state的时候是旧数据。我的理解是，这个时候的this.props里面包含的是redecers完结后的数据，所以我怕对then的理解，和this.props这个的理解是不是哪里冲突了或者哪里搞错了

**Comment by ChanseaCem** [comment]
你的意思是
effects: {
*getProList({ payload }, { call, put }) {
const res = yield call(getProList);
if (res && res.code === 200) {
yield put({
type: 'setPro',
payload: {
data: res.data
}
})
}
},
}
then的意义表示这个yield call(getProList);的请求结束，而并不是
yield put({
type: 'setPro',
payload: {
data: res.data
}
})
到reducers进行更新赋值结束。如果要拿最新的state就要使用userSelector。
比如：
@connect(({ yieldrate_group, loading }) => ({
...yieldrate_group
}))
class YieldRateGroup extends Component {
constructor(props) {
super(props);
}

componentDidMount() {
this.initData();
}
saveData = (dispatch, data, fn) => {
dispatch({
type: 'yieldrate_group/setState',
payload: {
data: data
}
}).then(() => {
if (fn) {
fn(dispatch);
}
})
}

initData = () => {
const { dispatch } = this.props;
this.getProList(dispatch);
}

// 获取产品列表
getProList = (dispatch) => {
dispatch({
type: 'yieldrate_group/getProList',
payload: {}
}).then(() => {
this.getGrouptList(dispatch)
})
}

//分组
getGrouptList = (dispatch) => {
const { pro_code, start_time, end_time, hours } = this.props;
dispatch({
type: 'yieldrate_group/getYieldAllList',
payload: {
values: {
pro_code: pro_code,
start_time: start_time,
end_time: end_time,
hours: hours,
sort: type == 'ok' ? 'desc' : 'asc',
type: type
}
}
}).then(() => {
......
})
}

......
}

这里的获取产品列表的then后面调用的getGrouptList 方法里，
const { pro_code, start_time, end_time, hours } = this.props 这句代码，不应该直接调用，而是换成userSelector获取。
我这样的理解对吗？
顺便问下，之前我都用这个方式进行获取，都啥问题，就是偶尔会遇见获取最新state的时候是旧数据。我的理解是，这个时候的this.props里面包含的是redecers完结后的数据，所以我怕对then的理解，和this.props这个的理解是不是哪里冲突了或者哪里搞错了  @xc1427
