### ISSUE TITLE
全局model里的effects，被调用时返回promise，私有model里的effects，被调用时返回的是object，为什么会这样

### ISSUE THREAD

**Issue by lichengfei911** [dvajs/dva#1824]

**Comment by ibreathebsb** [comment]
调用的是时候是不是没用 `yield call` 直接用的`call`?

**Comment by lichengfei911** [comment]
namespace: 'system/company/companyModel'
我知道问题了，因为我为了避免namespace重名，就把目录的路径加入了进去
我改成namespace: 'companyModel'，就可以正常返回promise了
请问如何避免不同目录namespace重名问题

**Comment by s97712** [comment]
namespace重名应该由库来检测并报错吧, 你弄个重名看看dva有没有这个

**Comment by narrowizard** [comment]
dva will check if an action is an effect here. it takes the first segment of the action type as model's namespace.  
since we cannot add '/' in function name, will it be better to support '/' in namespace? @sorrycc 
> https://github.com/dvajs/dva/blob/b25bd5a26da48acb05f3374e23a0bf06048c9fc8/packages/dva-core/src/createPromiseMiddleware.js#L21-L22
