### ISSUE TITLE
求帮助：关于工程为多页面工程的动态，动态加载问题

### ISSUE THREAD

**Issue by as569951728** [dvajs/dva#1825]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
1）我更改工程rcwebpack配置中的entry属性，将工程分为多页面应用。 2）因为设置了旧不同的入口，所以我把src下面的 index.js那入口文件给删除掉了。
3）我把多页面应用的每个页面，都弄成单页面应用，也就是，入口文件的index.js，也有自己的router。
4）我把router加载用dynamic分化，期望能动态加载，将路由的页面单独打包出来以减小主js的大小，减少页面加载的时间
5）我尝试配置rcwebpack，期望能让不同入口打包出来的资源放入不同的文件内
#### Expected behavior: (预期的正常效果)
1、期望打包出来的js，能是分化好的js，一个主js和一些动态加载的js
2、不同入口打包好的js，放于同一目录的不同文件夹

#### Actual behavior: (实际效果)
1）多页面应用的路由，并没有动态加载，也就是打包出来都是放在一个js文件中的
2）不同入口的页面，打包出来还是放在dist下面，有点拥挤

**Comment by sorrycc** [comment]
感觉不太好配，我没有这么做过。

**Comment by shenqihui** [comment]
我选择使用多条打包指令。详情可以查看下 https://github.com/61qt/61qt-dva2-scaffold ，可以在 src/modules 下配置多个入口，然后单独启动。

后面未发布的版本（公司版本）写了各种 sh 脚本，一键打包全部（每个单独运行的）。
所以，也会不存在 common 的 js ，每个项目都是单独打包的。

**Comment by as569951728** [comment]
好的，谢谢，我去学习下。

发送自 Windows 10 版邮件应用

发件人: 大饼
发送时间: 2018年8月18日 18:05
收件人: dvajs/dva
抄送: as569951728; Author
主题: Re: [dvajs/dva] 求帮助：关于工程为多页面工程的动态，动态加载问题 (#1825)

我选择使用多条打包指令。详情可以查看下 https://github.com/61qt/61qt-dva2-scaffold ，可以在 src/modules 下配置多个入口，然后单独启动。
后面未发布的版本（公司版本）写了各种 sh 脚本，一键打包全部（每个单独运行的）。
所以，也会不存在 common 的 js ，每个项目都是单独打包的。
