### ISSUE TITLE
uncaught at check call: argument [object Object] is not a function

### ISSUE THREAD

**Issue by xiaochunyu** [dvajs/dva#1829]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
官方文档：
在dva中，可以用namespace去指定接受action的model，所以可以通过类似这样的方式去组合：

yield call({ type: 'a/foo' });
yield call({ type: 'b/foo' });
yield call({ type: 'a/bar' });

我的代码：

```js
a.js
export default {
  namespace: "global",
  state: {
  },
  effects: {
*checkLoginStatus(_, { call }) {
       const res = yield call({
              type: "b/refreshToken",
              payload: {
              }
            });
     if(res) {
       //....
      }
}
}
```
```js
b.js
export default {
  namespace: "b",
  state: {
  },
  effects: {
*refreshToken(_, { call }) {
       //......
}
}
```

#### Expected behavior: (预期的正常效果)
预期:
checkLoginStatus执行call  modal: b 的refreshToken Effect，返回数据 继续下面操作

#### Actual behavior: (实际效果)
uncaught at check call: argument [object Object] is not a function

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"dva": "^2.3.1"

**Comment by sorrycc** [comment]
看不出问题，给个可重现的仓库吧。

**Comment by sevenboom** [comment]
``` js
yield call({ type: 'a/foo' });
yield call({ type: 'b/foo' });
yield call({ type: 'a/bar' });
```
这里应该用put，这样'yield put({type:'a/foo'});'，文档写错了
