### ISSUE TITLE
IE10- super(props)失效

### ISSUE THREAD

**Issue by Aoobruce** [dvajs/dva#1831]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
发现组件的constructor内部 不能使用this.props 像是super(props)没有执行
组件的构造函数：
constructor(props){
  super(props);
  console.log(this.props);
}

#### Expected behavior: (预期的正常效果)
控制台打印出props

#### Actual behavior: (实际效果)
IE10-环境：
控制台输出为 undefined

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva@v2.3.1
代码中引入了 import "@babel/polyfill";    polyfill@v7.0.0-beta.46

**Comment by yinlv** [comment]
使用 es7 ，轻松摆脱 super(props) 的困扰~
