### ISSUE TITLE
优化建议：同时开启多个页面

### ISSUE THREAD

**Issue by enginnerFrankLiu** [dvajs/dva#1835]
最近，一直在用dva做开发，首先，感谢大神的杰作。。。
这里又一个小小的优化建议(或则，已经有了，我没找到^_^)

需求描述：
我打开page1查看dashborder的实时数据动态变化，但是此时，我又想打开page2去用户页面进行相关操作；为了不覆盖page1，我就需要在浏览器中开启一个新的tab；（也就是要打开两个浏览器的tab）

dva 有没支持下面这样的，在context中异步加载多个页面，这样页面之间切换，就会容易很多；

![image](https://user-images.githubusercontent.com/41586100/43363700-d300172c-9334-11e8-96cf-ee6db2624744.png)

**Comment by memoryza** [comment]
@enginnerFrankLiu 按照你的说法你想tab切换多个页面？ 这个页面功能自己去实现就可以了啊，state是全局的状态，你select  可以选出来然后操作，再不行在subscriptions 定义订阅的时候指定那几个页面可以在某个path下同时触发==！

**Comment by enginnerFrankLiu** [comment]
嗯嗯，说的有道理，确实可以这么做~

**Comment by enginnerFrankLiu** [comment]
@memoryza  嗯嗯，说的有道理，确实可以这么做~
