### ISSUE TITLE
多个请求，有且返回401后，如何优雅地阻止后续请求？

### ISSUE THREAD

**Issue by ybning** [dvajs/dva#1838]
有这样一个场景：
订单新增页，需要请求：客户列表接口 和 商品列表接口，
然而token过期了，访问这个页面时，2个接口同时返回401，
如何优雅地处理：第1个接口返回401后，后续的接口不再请求。

**Comment by ybning** [comment]
@sorrycc 大神帮帮忙

**Comment by yupeilin123** [comment]
猜测是并行。用const [data1,data2] = yield all[ call() , call() ] . if(data1.error || data2.error) {     }

**Comment by fangkyi03** [comment]
这个很好解决
https://github.com/fangkyi03/dvajs
用我这个 如果数据发生异常的时候
直接发起一个取消的dispatch就可以取消之后网络请求的队列执行
