### ISSUE TITLE
项目大了之后，全局store数据过多，如何管理store

### ISSUE THREAD

**Issue by laojun** [dvajs/dva#1839]
项目大了后，有很多model文件，所有的请求都通过model的effects，然后存在全局的store中。
这样有两个问题：
1、全局store中的数据，不会根据组件销毁而销毁，需要手动clear，否则下次渲染组件会有瞬间的残留数据
2、请求回来的很多store中的数据只在某个组件中使用，这样的数据需要放在全局store中吗？

我自己的理解是，需要和其他组件共享的数据才需要放在全局store中，否则能否跳过model的effect调用，通过另外一种统一的途径由组件自身请求和管理

望请教

**Comment by laojun** [comment]
@sorrycc  大神帮帮忙

**Comment by xueye515** [comment]
正是我想问的问题，mark下。我还有个疑问，一个页面对应一个model吗？
例如我有一个页面A，下面有四个图表，a,b,c,d。当我改变d图表上的一个日期时需要重新请求数据，重绘d图表里面的数据。但是 model是connect  A上面的，通过dispatch 后，model改变了，然后通过props由A穿给d组件。这时候不需要重绘 a,b,c 也会走重绘(是能通过shouldupdate判断，但是感觉不好)。
大神们有什么解决方案吗？ 
还是像楼主提的这样 数据直接存储在 a,b,c,d 四个组件里面？

**Comment by ybning** [comment]
我也遇到你 @laojun  描述的忧虑点，常见的做法：
这个数据，如果其他组件用的上，而且当组件unmount再mount回来，数据需要在，就放到store里，否则，放在state上。

**Comment by tomcatjerrymouse** [comment]
按需加载就可以吧，在index.js里启用modal是全局的，在router下启动就是当前的。比如
{
      path: '/article/list',
      exact: true,
      models: () => [ import('models/article/article.js') ],
      component: () => import('./index.js'),
    },

**Comment by yeatszhang** [comment]
2. 可以参考 https://markus.oberlehner.net/blog/how-to-structure-a-complex-vuex-store/ 。  个人现在的处理方法是，判断是否业务组件，业务组件作为单例全部放在 store，否则作为 pure component 做到无依赖。 根据这个原则就不用纠结状态放在哪了，碰到性能问题之后再针对性优化
1. 放在 store 中的状态自己控制刷新和销毁，通过钩子或者代码结构来保证代码的简洁~
3. 怎么拆 store， 这个就是业务的理解和工程经验问题了，没人能给你个标答
