### ISSUE TITLE
引入antd 组件,在dva中,css样式不生效

### ISSUE THREAD

**Issue by ZhaoDaMing** [dvajs/dva#1841]
版本:![image](https://user-images.githubusercontent.com/30341077/43500698-7eaf8548-9584-11e8-8131-3d7327f30762.png)

代码
![image](https://user-images.githubusercontent.com/30341077/43500715-92072998-9584-11e8-917d-3c9c3e81b5f5.png)
![image](https://user-images.githubusercontent.com/30341077/43500725-9af55a5c-9584-11e8-9222-322135e2e28d.png)
但是样式不work, 我是按照https://ant.design/docs/react/practical-projects-cn方式创建的dva new demoproject
这是项目目录,我没改过
![image](https://user-images.githubusercontent.com/30341077/43500802-e1592906-9584-11e8-90c9-b0bc04d63693.png)
.webpackrc有按照步骤加插件
![image](https://user-images.githubusercontent.com/30341077/43500813-eb3da7da-9584-11e8-8722-4cac7bac6f41.png)

**Comment by sorrycc** [comment]
dva 默认是用 css modules 的，需要用 css modules 的用法。
