### ISSUE TITLE
dva-loading 是否可以支援自动记录所有model的effect？

### ISSUE THREAD

**Issue by 8089wang** [dvajs/dva#1845]
如题，如果在subscription中没有dispatch effect的话，loading state就没有对应model的记录，这样页面中点击按钮就无法引用到对应的loading了。

所在在这种情况下，我还是要自己写loading start， loading end? 还是在subscription中能够自动塞入loading state，不过subscription无法访问state？

**Comment by sorrycc** [comment]
effect 执行过后就会有 state 的，和 subscription 没啥关系。

**Comment by 8089wang** [comment]
Thanks。antd的spin无法判断undefined，我已经手动判断。
