### ISSUE TITLE
'fileList' cannot be assigned on redux while using Antd Upload component and dva-immer

### ISSUE THREAD

**Issue by Renderz** [dvajs/dva#1854]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
antd 3.5.0 
dva 2.2.3
dva-immer 0.2.1

### Environment
system :macOS 10.13.6; browser :chrome 68.0.3440.84; 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y0k68mr3vx)

### Steps to reproduce
1. when click 'upload', the 'fileList' suppose to be assigned to redux(dva-core with dva-immer) 
2. the error will be showed on this step: 'Cannot assign to read only property 'percent' of object '#<Object>'

### What is expected?
The onChange callback supposed to be invoked 3 times as same as 'fileList' be assigned to redux 3 times. 

### What is actually happening?
While which successfully assigned at first time and then throw an error 'Cannot assign to read only property 'percent' of object '#<Object>',
when i remove using dva-immer, everything goes fine

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/43811142-a8403664-9aed-11e8-844f-a2b44f80263d.png)

**Comment by Renderz** [comment]
所以这个应该是antd组件的问题么...
感觉说不上是bug的样子...
