### ISSUE TITLE
dva-loading 如何重置请求过的接口状态

### ISSUE THREAD

**Issue by codeXian** [dvajs/dva#1855]
需求：
1. A页面从后台请求过接口，先出现loading，后出现后台数据。
2. A页面点击按钮跳转到B页面
3. B页面回退至A页面
4. A页面因为有dva-loading的状态(false)，会先显示原先的数据，再去请求接口，用户体验不好

想法： 
能否提供dispatch方法重置dva-loading的值
感谢

**Comment by ldwonday** [comment]
一样遇到这个问题，有方案解决吗？

**Comment by codeXian** [comment]
我现在的做法是在当前页面的顶级父组件state里，设置一个isFirstLoad的变量，这样比较弱智的解决了这个问题。 @ldwonday

**Comment by INTMIN** [comment]
我也碰到了这个问题，有没有什么好的解决方案，我这个更加严重，因为要判定权限，但是数据没有清空，数据遍历会有一瞬间没有值，然后页面直接崩了

**Comment by Gzbox** [comment]
有没有其他的解决方案吗?

**Comment by wo-de-ping-er** [comment]
请问一下，有木有更为简便的解决方案？  dva本身提供dva-loading，如果不使用dva提供loading中的effects方法，总感觉怪怪的。有点多余。

**Comment by EEETA** [comment]
同问有无其他解决方案，现在是isFirstLoading的值，配合componentDidUpdate使用，在render中除了判断loading.effects的值外，还要判断是否首次进入这个组件。
