### ISSUE TITLE
使用browserhistory模式的时候，带参路由报错

### ISSUE THREAD

**Issue by innoccent** [dvajs/dva#1863]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

![143b2839dd6cbed645c2ebae66d5157](https://user-images.githubusercontent.com/29913699/44037352-b3a3b848-9f46-11e8-82ed-26007645ebd3.png)
![013bf090826a52dcec37e833676369f](https://user-images.githubusercontent.com/29913699/44037405-d588dd44-9f46-11e8-8141-91203d45642b.png)
![552f86cc355d00f1ab52106974526da](https://user-images.githubusercontent.com/29913699/44037417-dd91dd2e-9f46-11e8-859f-a7a1bd387c88.png)

#### Expected behavior: (预期的正常效果)
正常应该到test/xx页面，可以获取到params里面的参数

#### Actual behavior: (实际效果)
![338d43e0aa33c324669dcd7d2b51530](https://user-images.githubusercontent.com/29913699/44037393-cb79b1c0-9f46-11e8-88b0-745616dc26c4.png)
![deac8965bbbda381f98148bc5aa0fd3](https://user-images.githubusercontent.com/29913699/44037398-cf52e4ce-9f46-11e8-9589-c6a3abd20a3a.png)

#### Versions of packages used: (哪个库的哪个版本出现的问题)
2.1.0

**Comment by Pecking** [comment]
我遇到同样的问题，你解决了嘛？

**Comment by HiMrHu** [comment]
请求404,推测是某个请求预期响应一个js文件，但是返回了一个html文件，导致解析错误，请提供一个最小复现例子

**Comment by Pecking** [comment]
![image](https://user-images.githubusercontent.com/27414779/44580165-85cffc00-a7cb-11e8-891d-f75e2a50172f.png)

**Comment by wanglei949758173** [comment]
@innoccent @Pecking 在public/index.html中 引用js文件使用绝对路径即可解决,例如:`<script src="/index.js"></script>`
