### ISSUE TITLE
如何向组件传入router的props

### ISSUE THREAD

**Issue by yrcy0418** [dvajs/dva#187]
`const Home = props => (
  <div>
    <div className="demo-nav">
      <Link to="/">Home</Link>
      <Link to="/apps">Application List</Link>
    </div>
    {props.children || 'Home'}
    <div
      style={{
        marginBottom: 15,
        marginTop: 15,
        paddingBottom: 15,
        borderBottom: '1px dashed #ccc',
      }}
    >
      Click the navigation above to switch:
    </div>
    <Breadcrumb {...props} />
  </div>
);`

使用ant.design面包屑组件，如何传入router的props呢

**Comment by sorrycc** [comment]
在 route component 里可以获取到 router 相关的 props，然后层层传入直到面包屑组件。

**Comment by yrcy0418** [comment]
在route component 中如何获取呢

**Comment by nikogu** [comment]
@yrcy0418 一样的，通过 props 获取，route component 本身就会被传 router 相关属性的

**Comment by yrcy0418** [comment]
![image](https://cloud.githubusercontent.com/assets/12506829/19636810/1efd5fa4-99fe-11e6-9e74-6a22666aa476.png)
我这样传进来是undefined

**Comment by nikogu** [comment]
额，不是这么玩的。。。

```

var SysUser = ({ params, locatoin, sysuser, form ....}) => {}

```
router 中传入的也是你 props 的属性之一，而不是叫 props

**Comment by yrcy0418** [comment]
![image](https://cloud.githubusercontent.com/assets/12506829/19637086/b8da000e-99ff-11e6-994b-f04f84f187a9.png)
我用的是动态的router加载，如何传输pr呢

我现在是这样弄得

![image](https://cloud.githubusercontent.com/assets/12506829/19637099/d47bad76-99ff-11e6-9129-606039ccf154.png)
![image](https://cloud.githubusercontent.com/assets/12506829/19637105/de07d176-99ff-11e6-8ac5-69de2cffdf52.png)

**Comment by yrcy0418** [comment]
@nikogu 好用了，我那个路径写错了，传入就行了
