### ISSUE TITLE
use the latest route version and set history: createHistory, dynamic load page   get  'Loading chunk 2 failed' error

### ISSUE THREAD

**Issue by wengjincheng** [dvajs/dva#1874]
# 
when i use this url( http://localhost:8000/landlord/test ) in my dva appliction.
get the error:  Unhandled Rejection (Error): Loading chunk 2 failed.

#### 
my index.js code: 

> import dva from 'dva';
import createHistory from 'history/createBrowserHistory';
import './index.less';
// 1. Initialize
const app = dva({
  history: createHistory(),
});
// 2. Plugins
// app.use({});
// 3 Model
app.model(require('./models/auth').default);
app.model(require('./models/myAccount').default);
// 4. Router
app.router(require('./router').default);
// 5. Start
app.start('#root');

my route: 

> <Router history={history}>
      <Switch>
        <Route
          path="/landlord/test"
          render={(props) => <LandlordLayout {...props} />}
        />
        <Route
          path="/"
          render={(props) => (
            <GlobalLayout {...props} {...routeBeforeEnterProps} />
          )}
        />
      </Switch>
    </Router>

#### Actual behavior: (实际效果)
display  'Loading chunk 2 failed' on the page

#### Versions of packages used: 
my dependencies:  
> "dependencies": {
    "antd": "^3.8.1",
    "axios": "^0.18.0",
    "babel-plugin-import": "^1.8.0",
    "dva": "^2.4.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "babel-plugin-dva-hmr": "^0.3.2",
    "eslint": "^4.14.0",
    "eslint-config-umi": "^0.1.1",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "husky": "^0.12.0",
    "redbox-react": "^1.4.3",
    "roadhog": "^2.4.4"
  }

**Comment by 951565664** [comment]
Can you show the code of ./models/auth,I guees you have don’t export
