### ISSUE TITLE
watcher effects中take无效

### ISSUE THREAD

**Issue by ibreathebsb** [dvajs/dva#1875]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

数据模型 `discover.ts`
```typescript
export const discover: Model = {
  namespace: 'discover',
  state: {
    loading: true,
    active: 0,
 
  },
  effects: {
    watchAdd: [function* ({ take, put, call }) {
      console.log(2)
      const delay = (time: number) => new Promise((resolve) => setTimeout(resolve, time) )
      while (true) {
        yield take('add')
        console.log('start')
        yield delay(1000)
        console.log('end')
        // yield put({ type: 'add', payload })
      }
    }, { type: 'watcher' }],
  },
  reducers: {
  }
}

```
组件内触发

```typescript
this.props.dispatch({
      type: 'discover/add',
      payload: 0
   })

```
#### Expected behavior: (预期的正常效果)

控制台应该打印start, 延迟一秒后，打印end

#### Actual behavior: (实际效果)

控制台没有任何输出

将 ` yield take('add')` 修改为 ` yield take('discover/add')`后可以正常工作,
但是控制台警告不要把namespace放到take里面:
`Warning: [sagaEffects.take] discover/add should not be prefixed with namespace discover`

#### Versions of packages used: (哪个库的哪个版本出现的问题)

2.4.0

**Comment by luqihang** [comment]
要先触发watchAdd，再触发add才有效

**Comment by brickspert** [comment]
和你碰到同样的问题了
