### ISSUE TITLE
无法获取到旧的state数据

### ISSUE THREAD

**Issue by free-pan** [dvajs/dva#1878]
结合umi和dva使用,触发reducers的方法时,无法获取到旧state数据(或者说与预期不同). 得到的旧的state数据为Proxy类型

我的代码:

## 路由组件

`import React from "react";
import Start from './start';
import { ErrorBoundary } from './ErrorBoundary';
import { connect } from 'dva';
import { IntlProvider, FormattedMessage } from 'react-intl';
import { LocaleProvider, Select, Calendar, message } from 'antd';

const Option = Select.Option;

class IndexClass extends React.Component {

    constructor(props) {
        super(props);
        // console.log(dispatch);
        // console.log(langMap);
        // console.log(location);
        // console.log(history);
        console.log(this.props);
        this.state = {
            langMap:props.langMap,
            lang:props.lang
        }
        this.dispatch = props.dispatch;
        this.changeLang = this.changeLang.bind(this);
    }

    onPanelChange(value, mode) {
        // this.person.name='张三';
        // console.log(value, mode);
    }

    changeLang(val) {
        this.dispatch({ type: 'index/changeLan' })
    }

    render() {
        return (
            <LocaleProvider locale={this.props.lang.antd}>
                <IntlProvider locale='en' messages={this.props.lang.intl}>
                    <div>
                        <Select defaultValue="zh" style={{ width: 120 }} onChange={this.changeLang}>
                            <Option value="zh">中文</Option>
                            <Option value="en">English</Option>
                        </Select>
                        <div>{this.props.lang.txt}</div>
                        <FormattedMessage
                            id="HELLO_WORLD" values={{ name: '张三' }}
                        />
                        <Calendar fullscreen={false} onPanelChange={this.onPanelChange} />
                        {this.props.children}
                    </div>
                </IntlProvider>
            </LocaleProvider>
        )
    }
}

function mapStateToProps(state) {
    return state.index;
}
export default connect(mapStateToProps)(IndexClass)`

## Model

`import enUS from '../locales/en-US.json';
import zhCN from '../locales/zh-CN.json';
import zh from 'antd/lib/locale-provider/zh_CN';
import en from 'antd/lib/locale-provider/en_US';

export default {
    namespace: 'index',
    state: {
        langMap: {
            zh: {
                txt: '中文',
                antd: zh,
                intl: zhCN
            },
            en: {
                txt: 'English',
                antd: en,
                intl: enUS
            }
        },
        lang: {
            txt: '中文',
            antd: zh,
            intl: zhCN
        }
    },
    reducers: {
        changeLan(state, { lan, langMap }) {
            console.log(arguments);
            // console.log(lan)
            // console.log(langMap);
            // return {
            //     ...state,
            //     langMap,
            //     lang: langMap[lan]
            // }
        }
    },
    effects: {

    },
    subscriptions: {
        setup({ dispatch, history }) {
            return history.listen(({ pathname }) => {
                // if (pathname === '/user') {
                //     dispatch({ type: 'list' });
                // }
            });
        },
    },
}`

当进行语言切换时(触发模型组件的changeLan方法), 我预期的state数据应该和模型组件定义的state一致, 但实际为Proxy数据类型
`Proxy
[[Handler]]
:
null
[[Target]]
:
null
[[IsRevoked]]
:
true`

是哪里写错了吗? 我要怎么拿到旧的state数据?

**Comment by jeffrey-fu** [comment]
1。要拿到Prevstate，有状态组件不使用Dva
```
this.setState((prevState, props) => ({
  counter: prevState.counter + props.increment
}));
```
2。你的代码是把dva的值传给有状态组件的state里没什么意义。(直接用props传值就可以了，state里放私有的状态）
在reducer里获取到旧state数据
```
reducers: {
  changeLan(state, { lan, langMap }) {
    let prevState = state.lan;
    ....
  }
}
```
在effects里获取到旧state数据
```
effects: {
  *fetch(action, { select }) {
    let prevState = yield select(state => state.namespace.lan);
    ....(state.namespace.lan) this namespace is defined by yourself.
  }
}
```
