### ISSUE TITLE
Warning: You cannot use state without a queryKey it will be dropped 

### ISSUE THREAD

**Issue by snecker** [dvajs/dva#188]
使用 `<Link to={{pathname:'url',state:obj}}>` 的时候出现问题,提示,
> Warning: You cannot use state without a queryKey it will be dropped 
跳转后location.state并无此对象

后来去掉 history: useRouterHistory(createHashHistory)({queryKey: false,}),这个配置, location.state可以拿到obj,

请问,可以在去掉 queryKey的前提下传递数据给另一个路由的页面吗

**Comment by sorrycc** [comment]
`queryKey` 不要拿掉吧，会有各种不可预知的问题。
