### ISSUE TITLE
dva/dynamic路径的问题（求助）

### ISSUE THREAD

**Issue by jeffery021121** [dvajs/dva#1882]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
使用dva/dynamic动态加载路由，本地环境是ok的，例如生成了0.async.js
点开对应的路由以后默认会去找http://localhost:8000/6.async.js这个文件。

问题：我线上的文件地址并不是在这个地址下的。我打包好的文件0.async.js文件例如在https://www.aa.com/faeker/scripts/6.async.js，但是现在它还是会默认去找https://www.aa.com/6.async.js
于是就发生找不到的情况了，所以这个路径有地方可以配置吗？

#### Expected behavior: (预期的正常效果)
打包到自己配置的路径下

#### Actual behavior: (实际效果)
不知道去哪里配置，所以还是打包到了默认路径下

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva2.1.0，也不是dva的问题，只是不知道去哪里配置

**Comment by xiahdfsq** [comment]
我也有这个问题，想改变打包后的文件名字

**Comment by pengxiaobao** [comment]
+1

**Comment by jeffery021121** [comment]
配置publicPath就可以了
