### ISSUE TITLE
静态打包问题打开index.html白屏

### ISSUE THREAD

**Issue by Mjian-chen** [dvajs/dva#1885]
问题：如果将dva的项目打包成静态资源文件供原生APP去加载使用，查看Issues都说要部署到容器里，但是在混合APP里面，原生只是打开一个webview去加载H5资源文件，此时跟直接在dist下打开index.html是一样道理，此时白屏，查看资源加载都没有报错。ps: 我使用的是browserHistory 路由。
想问一下：dva如何打包成可以直接访问的静态文件。因为同一套代码要用到web端和app里面

**Comment by joriewong** [comment]
### reason 1

``` conf
location / {
   try_files $uri $uri/ /index.html;
}
```

### reason 2

``` html
<link rel="stylesheet" href="/index.css">
```

### reason 3

- 国产浏览器使用兼容模式时界面空白，需切换至极速模式
