### ISSUE TITLE
dispatch 发送后，会重新渲染一次？

### ISSUE THREAD

**Issue by shaodawei2017** [dvajs/dva#1895]
dispatch 发送到 model 层的effects函数中，该effect是个空函数，并没有往后台发送请求，也没用使用put调用reducers改变状态，为什么回重新渲染组件？
因此，如果调用后台，拿到返回值并更改model层状态，会渲染两次。

**Comment by free-pan** [comment]
是否进行重新渲染由shouldComponentUpdate的返回值决定, 另外, 即使mapStateToProps被触发多次,貌似,只要之前被映射到组件的state未改变,组件也不会重新渲染(至少Pure组件是这样)

**Comment by enginnerFrankLiu** [comment]
previously, i run into almost the same question; you should check the previous issue before post new issue;
here is detail:
https://codesandbox.io/s/13n9vp32l3

https://github.com/dvajs/dva/issues/1663
