### ISSUE TITLE
dva 懒加载

### ISSUE THREAD

**Issue by Rpeanut** [dvajs/dva#1897]
### 版本：
 "dva": "^2.3.0",     "umi": "^1.3.8",  "umi-plugin-dva": "^0.9.0"
### 问题：
我用了dva的懒加载，但是面临的问题是如a model调用了 b model的effect，但是此时页面b和model b还没有加载，a model中试图传递给model b的数据首次就会丢失，后续再去相同的操作（即model加载成功后），a model传递过来的数据就会正常，请问这种情况下除了抛弃懒加载和传递数据零时存储在app model（或common model）中还有别的更好的方式吗？如有木有提供判断b model加载成功的方法？
@sorrycc @yiminghe 
希望云谦大大告知

**Comment by sundi78634** [comment]
a 页面加载 a model 的时候把 b model 也加载
