### ISSUE TITLE
用dva推荐的无状态函数的方式写组件怎么实时监听

### ISSUE THREAD

**Issue by jindada** [dvajs/dva#190]
比如 回到顶部 我怎么才能实时监听到滚动条的状态  来更改state 控制组件的显示 隐藏？

**Comment by sorrycc** [comment]
滚动条状态的监听可以放 subscription 里吧。

**Comment by jindada** [comment]
我也想到放在subscription里 我试试看吧

**Comment by jindada** [comment]
还是想不太明白该如何去写  有subscription详细一点的文档吗 或者能给点思路吗

**Comment by sorrycc** [comment]
subscriptions 里写：

```js
window.onScroll = function() {
  dispatch(ACTION);
}
```

**Comment by jindada** [comment]
非常感谢 看了你给的提示和之前你对大家提出关于subscriptions的解答 终于将问题解决了

**Comment by lincenying** [comment]
这么写绑定事件是可以了, 但是组件注销时, 怎么注销事件呢? 不然会导致其他组件也有该事件...

**Comment by sorrycc** [comment]
随组件走的话就用组件的生命周期，别用 subscription 。

**Comment by jindada** [comment]
subscription 中 怎么获取 state的 值啊

**Comment by sorrycc** [comment]
subscription 里不能获取 state，触发 action，让 effect 去做逻辑上的事。

**Comment by jindada** [comment]
effect可以获取到当前的state吗？  我想弄一个滚动条到底部自动分页的东西  subscriptions中监控滚动条 然后dispatch action 但是我要传当前的页数+1  当前的页数在state里面 这个怎么获取到那？

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva-knowledgemap#select

**Comment by jindada** [comment]
了解了 谢谢 我好好看看knowledgemap在开始搬砖吧
