### ISSUE TITLE
dva-cli升级的最新就这个错,一直找不到

### ISSUE THREAD

**Issue by xuxucong** [dvajs/dva#1904]
index.js:25493 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `DvaRoot`.
    in DvaRoot

**Comment by BiaoZhiWang** [comment]
use <Redirect  > instead of <IndexRedirect> when define routes, I fixed same error

**Comment by Caroline-Wang** [comment]
I have the same problem,have you solve it?
