### ISSUE TITLE
effect中通过put调用reducer，如果reducer抛出异常，并不会冒泡到window

### ISSUE THREAD

**Issue by awmleer** [dvajs/dva#1907]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

复现demo：

[dva@1.2.1版本](https://stackblitz.com/edit/dva-example-error-in-put-1-2-1?file=index.js)
[dva@2.3.2版本](https://stackblitz.com/edit/dva-example-error-in-put-2-3-2?file=index.js)

#### Expected behavior: (预期的正常效果)

两个按钮点击后都能log出`error is caught!`

#### Actual behavior: (实际效果)

![image](https://user-images.githubusercontent.com/16526078/45747433-6b593900-bc38-11e8-9c3e-1c1b25bf6e6b.png)

![image](https://user-images.githubusercontent.com/16526078/45747620-fdf9d800-bc38-11e8-98e6-150549492b30.png)

如上图，点击左边的按钮，调用`throwErrorEffect`，然后通过`yield put`调用了`throwErrorReducer`，`throwErrorReducer`中抛出了异常，但是这个异常并没有被`window.onerror`捕获
然而点击右边的按钮，直接调用`throwErrorReducer`，却可以正常地将异常冒泡到window

#### Versions of packages used: (哪个库的哪个版本出现的问题)

`dva@1.2.1`和`dva@2.3.2`都存在这个问题

**Comment by shinima** [comment]
这个其实是 redux-saga 0.16.x 的问题，这个版本下 redux-saga 会直接将 reducer 抛出的异常吞了。

这个问题在 redux-saga 1.0.0-beta.x 已经解决，不过需要等待 dva 升级 redux-saga 的版本。

**Comment by awmleer** [comment]
原来如此，非常感谢～
