### ISSUE TITLE
在使用routerRedux.push()方法修改query时，query没有发生改变，浏览器的url也没有发生变化

### ISSUE THREAD

**Issue by cgd199158** [dvajs/dva#1916]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
**问题：在使用routerRedux.push()方法修改query时，query没有发生改变，浏览器的url也没有发生变化，路由使用的hashHIstory,在使用BrowserHistory的时候location.query正常改变,但是URL没有发生变化**
路由配置
![image](https://user-images.githubusercontent.com/18514077/46200734-ff1bbb00-c344-11e8-840d-6f948c96b669.png)

页面中按钮触发的路由跳转
![image](https://user-images.githubusercontent.com/18514077/46200769-165aa880-c345-11e8-804d-5e7e75654016.png)

#### Expected behavior: (预期的正常效果)
![image](https://user-images.githubusercontent.com/18514077/46200480-52d9d480-c344-11e8-9505-c28db7a434be.png)

#### Actual behavior: (实际效果)
![image](https://user-images.githubusercontent.com/18514077/46200495-6127f080-c344-11e8-88d8-2815a3aabcf6.png)

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"dva": "^2.2.3"

**Comment by lixuguang1988** [comment]
设置search:”?test=123”

**Comment by zhang0ZGC** [comment]
你找到解决办法了吗？我也是希望有能体现到url上去

**Comment by zjxpcyc** [comment]
push  state ? 印象中并不会有什么作用吧
