### ISSUE TITLE
使用react-app-rewired创建的dva项目，ie10上报错

### ISSUE THREAD

**Issue by liuguoxionglang** [dvajs/dva#1920]
调试窗口报错
function _classCallCheck(instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");  //此处跑出错误 
  }
}
控制台报错
Warning: The <DynamicComponent /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change DynamicComponent to extend React.Component instead.
SCRIPT5022: 引发了异常但未捕获

**Comment by liu1131170225** [comment]
metoo，
你解决了吗？

**Comment by weiq** [comment]
关注
