### ISSUE TITLE
_react2.default.createcontext is not a function;

### ISSUE THREAD

**Issue by enginnerFrankLiu** [dvajs/dva#1926]
1. firstly thanks your time to view my issue sincerely

I want to use editable row; I follow this demo https://ant.design/components/table-cn/#components-table-demo-edit-cell

but run into this error:
_react2.default.createcontext is not a function;

the google give me the reason is lower react version; so I upgrade the react more higher,
but I run into this error:
DataTable.js?16b1:104 Uncaught TypeError: Cannot read property 'oneOfType' of undefined

 I guess that is problem about compatibility;

so

1.should I upgrade the react to use editable row or chose other way to interaction

 if I should, which version I should upgrage?

here is my package Info:

![image](https://user-images.githubusercontent.com/41586100/47216710-77bbe780-d3d8-11e8-8125-7d37a8d3cd7e.png)

**Comment by prionkor** [comment]
Not sure if your problem is anything to do with dva. You have created the issue in wrong place.
