### ISSUE TITLE
快速上手例子的bug

### ISSUE THREAD

**Issue by zengyunchun** [dvajs/dva#1929]
![image](https://user-images.githubusercontent.com/19870340/47286788-bd6bf080-d622-11e8-8260-70244b16b739.png)
上面没有return返回值，应该如下

```
const Products = (props) => (
  return <h2>List of Products</h2>;
);
```

**Comment by nalantianyi** [comment]
请学习下es6的箭头函数

**Comment by nalantianyi** [comment]
请学习下es6箭头函数，
传送门http://es6.ruanyifeng.com/#docs/function#%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0
