### ISSUE TITLE
Subscription   API不完整

### ISSUE THREAD

**Issue by 15207799874** [dvajs/dva#1935]
Subscription 语义是订阅，用于订阅一个数据源，然后根据条件 dispatch 需要的 action。

数据源可以是当前的时间、服务器的 websocket 连接、keyboard 输入、geolocation 变化、history 路由变化等等。

为什么 文档只给出了  history 和 keyboard的API？   websocket，geolocation 是要人们去看源码吗？

**Comment by Dollyn** [comment]
顶，文档里关于Subscription讲的过于简单些了，看完还是不知道怎么用

**Comment by shiny** [comment]
最绝的是刚刚还能找到 history 的示例，再进去又找不到了，搜都搜不出来，真是绝了。

**Comment by iceberg211** [comment]
大佬最近的精力都放在umi上了

**Comment by xiaosongxiaosong** [comment]
使用第三方服务时也碰到了这个问题，通过缓存 dispatch 的方式实现了订阅第三方数据，下面是代码以及使用方式，可以参考一下
@15207799874 

```js
const eventTarget = (() => {
  let handle;
  const off = () => (handle = undefined);
  return {
    on(fn) {
      handle = fn;
      return off;
    },
    off,
    trigger(e) {
      if (handle) {
        handle(e);
      }
    },
  };
})();
```

```js
  subscriptions: {
    setup({ dispatch }) {
      return eventTarget.on(dispatch);
    },
  },
```
下面的代码相当于使用 dispatch 调用
```js
eventTarget.trigger({ type: 'save', payload });
```

**Comment by zjxpcyc** [comment]
这个 subscriptions 不是你理解的那个真正含义的订阅，这个是 redux 里面的概念。至于为什么只给出了 history 的例子，你可以写个 subscription func(...args) 把  args 打出来就知道了。

另外，你说的 websocket、keyboard、geolocation 等等不是 dva 考虑的东西，它没有一一去实现。要你自己想办法去解决。

总的说来，这个 subscriptions  不是广义上的订阅的含义。没有什么 setup, 或者 onload 或者 onready 上的含义。它只是 redux action 执行之前的一个调用

**Comment by 951565664** [comment]
看源码只是监听了history.listen 吧。可能我看到不自信
