### ISSUE TITLE
能否解决react-redux升到最新版本build失败的问题？

### ISSUE THREAD

**Issue by lhkg1988** [dvajs/dva#1937]
在2.4.1版本中将react-redux的版本固定成5.0.7了，但是现在遇到别的库里引用的react-redux是默认安装最高版本的，然后就还是不能build了，请问能不能在react-redux最高版本中解决这个问题？
发现 bug？

**Comment by xjoyzaza** [comment]
这是因为 这个项目用的是 react-router-redux  ，要换成connected-react-router 才能更新

**Comment by sorrycc** [comment]
@lhkg1988 这其实是工具层的问题。roadhog 版本多少？2.x 的话试试 2.5.0-beta.2 。
