### ISSUE TITLE
dvajs 安装

### ISSUE THREAD

**Issue by sin-ning** [dvajs/dva#1940]
During the dvajs installation process, npm install dvajs -v needs to add sudo to avoid some users do not know, the documentation.

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
npm install dvajs -g

#### Actual behavior: (实际效果)
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Sin/.npm/_logs/2018-11-05T09_22_18_200Z-debug.log

#### Versions of packages used: (哪个库的哪个版本出现的问题)
All version.

**Comment by zjxpcyc** [comment]
root 安装试试

**Comment by sin-ning** [comment]
During the dvajs installation process, npm install dvajs -v needs to >>> add sudo <<< to avoid some users do not know, >>>> the documentation. <<<<

**Comment by sorrycc** [comment]
Local environment issues, not related to dva.
