### ISSUE TITLE
请问 “基于 action 进行页面跳转” 的应用场景是？

### ISSUE THREAD

**Issue by NicholasNC** [dvajs/dva#1944]
[dva.js 知识导图-基于 action 进行页面跳转](https://github.com/dvajs/dva-knowledgemap#%E5%9F%BA%E4%BA%8E-action-%E8%BF%9B%E8%A1%8C%E9%A1%B5%E9%9D%A2%E8%B7%B3%E8%BD%AC)

以上内容
```
import { routerRedux } from 'dva/router';

// Inside Effects
yield put(routerRedux.push('/logout'));

// Outside Effects
dispatch(routerRedux.push('/logout'));

// With query
routerRedux.push({
  pathname: '/logout',
  query: {
    page: 2,
  },
});
```

不是很理解这里的 `dispatch(routerRedux.push('/logout'));` 应用场景是？

`dispatch(routerRedux.push('/logout'));` 和直接 `routerRedux.push()` 的区别是？

**Comment by NicholasNC** [comment]
另外试了一下，如果是 umi 中的 router 则不能使用
```
import router from 'umi/router';

dispatch(router.push('/404')); // 这样会报错
```

这样的话就更加不理解 `dispatch(routerRedux.push());` 使用场景是什么了~

**Comment by lixuguang1988** [comment]
登陆页，登陆成功后跳转到另一个页面，不可能然后让用户点链接的，
不带dispatch是不执行跳转的，
