### ISSUE TITLE
remove react-router

### ISSUE THREAD

**Issue by plandem** [dvajs/dva#195]
Do you ever considered to remove react-router? It's bloated library with non-stop breaking changes - already for few years. 

Consider at least differ choices, E.g.: https://github.com/callum/redux-routing

p.s.: i'm using this one in our project and quite fine with it.

**Comment by sorrycc** [comment]
I need to find time to do research. Does it support dynamic load?

**Comment by plandem** [comment]
What do you mean "dynamic load"? It's pure redux based (isomorphic) router. No any connection with React. It's up to you how you will connect it with React.

**Comment by sorrycc** [comment]
https://github.com/ReactTraining/react-router/blob/master/docs/guides/DynamicRouting.md

**Comment by plandem** [comment]
ok, as I said - by default it has no any integration with React, it's up to you how to integrate with React. Finally, you can create something like this HOC component for "dynamic" routes. But this library is lightweight and does only required task - routing. Consider it like low-level routing library.

**Comment by plandem** [comment]
https://github.com/callum/redux-routing/blob/master/example/Root.js

It's example how to integrate with React. I don't see any trouble to dynamically "require" component.

**Comment by liorix** [comment]
@plandem , @sorrycc -
For what it's worth, I'm not sure I'd go with https://github.com/callum/redux-routing as it doesn't seem like an actively maintained library so I'm not that I'm a big fan of using it as my routing solution...

**Comment by plandem** [comment]
@liorix it's stable and what a reason to update stable library? react-router updating often and still with breaking changes for few years! So we have:

1) unstable library with often updated and breaking changes are common
2) stable library that updates only when bug-fixing.

as for me i would prefer (2).

**Comment by soulmachine** [comment]
@plandem how does react-router 4 compare to redux-router ?

**Comment by plandem** [comment]
compare by what?! consider it as low-level core library, that can be used to build own router for React. It's just **redux** router, not **react**.

**Comment by plandem** [comment]
So? If you think it's only me, then you can look here:
https://news.ycombinator.com/item?id=12511419

**Comment by plandem** [comment]
here is some another libs to consider (without need to create own HOC for low-level router):
https://github.com/STRML/react-router-component
https://github.com/kriasoft/universal-router

**Comment by sorrycc** [comment]
Track progress in #530
