### ISSUE TITLE
[Feature] 能否支持 connected-react-router 呢

### ISSUE THREAD

**Issue by onpaik** [dvajs/dva#1951]

**Comment by onpaik** [comment]
https://reacttraining.com/react-router/web/guides/redux-integration

**Comment by zhao-xiaohu** [comment]
赞同，前不久 `react-router-redux` 已经正式不再维护了，而 `connected-react-router` 和 `react-redux` 也都刚升到 6.x 版本，来兼容 `react@16.4.x` 的新特性。

**Comment by lf7817** [comment]
同求

**Comment by wanliyunyan** [comment]
貌似作者好像不怎么维护，愁死了

**Comment by sorrycc** [comment]
connected-react-router 和 react-router-redux 相比有什么不同？

**Comment by wanliyunyan** [comment]
@sorrycc react-router-redux 不在维护了，这个就算是很大的不同了

**Comment by sorrycc** [comment]
@wanliyunyan 看需求吧，我觉得功能一致的话就没有换的必要了。

**Comment by wanliyunyan** [comment]
@sorrycc 肯定是以功能为准，但是我还是建议第三方库尽量用新版的，就怕起初差的不多，慢慢的，随着版本迭代，越差越多，最后造成很大的变动

**Comment by onpaik** [comment]
@sorrycc 
这是[connected-react-router](https://github.com/supasate/connected-react-router#main-features)的官方介绍的特性，支持Immutable 、TypeScript ...
并且react-router-redux 的主版本不支持react-router v4, 尽管有个5.0.0-alpha.9版本，但是不更新不维护会带来技术上越来越滞后的体验，不能很好的体验react生态带来的好处

**Comment by sorrycc** [comment]
我的想法，

1. immutable 和 dva 没有关系，TypeScript 现在的方案也是支持的，功能强大并不一定是好事，功能多意味着代码量也大
2. 技术滞后我觉得说不上，不管是 react-router-redux 还是 connected-react-router，实现的功能就是通过 action 处理 history 方法，这类功能很稳定，我觉得功能没变化就不需要跟进，引入不必要的 break-change

**Comment by onpaik** [comment]
嗯，说得也对，开发者和使用者思考的方向不一样。

可能要等dva什么时候出个新的大版本才会考虑了吧。哈哈，作为使用者，当然想什么都有了 😀
