### ISSUE TITLE
dva-loading如何监听静态资源的加载

### ISSUE THREAD

**Issue by 791045873** [dvajs/dva#1952]
目前的dva-loading插件会在effect触发前start progress，在effect结束后done progress。仅仅是针对effect进行状态变化。
请问如何用dva-loading监听带静态资源的加载，当跳转到一个简单的静态页面时，因为路由的跳转，开启了progress，如何在静态资源加载结束后done progress呢？
观察到dva.com官方网站上的进度条会在静态资源加载结束后done掉。不知道相关解决方案能否分享？

**Comment by INTMIN** [comment]
同问

**Comment by 791045873** [comment]
> 同问

https://github.com/791045873/notes/issues/8
我这样解决了，你有需要的话可以看一下
