### ISSUE TITLE
Couldn't find any versions for "scheduler" that matches "^16.6.2"

### ISSUE THREAD

**Issue by tomandyudezhi** [dvajs/dva#1954]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
dva new my-app过程中npm install下载报错

#### Expected behavior: (预期的正常效果)
不报错，

#### Actual behavior: (实际效果)
报错，导致后面安装antd也报错

#### Versions of packages used: (哪个库的哪个版本出现的问题)
Couldn't find any versions for "scheduler" that matches "^16.6.2"

**Comment by sorrycc** [comment]
react 的问题，应该已经解决了。参考 https://github.com/facebook/react/issues/14208
