### ISSUE TITLE
dva.start(); 报错 Provider is undefined

### ISSUE THREAD

**Issue by mmddgg** [dvajs/dva#1956]
之前用的 redux-saga 能正常渲染，代码如下：
`ReactDOM.render(
    <IntlProvider 
    locale={window.appLocale.locale}
    messages={window.appLocale.messages}
    formats={window.appLocale.formats}
    > 
        <LocaleProvider  locale={window.appLocale.antd}>
        <Provider store={store}>
            <BrowserRouter history={browserHistory} >
                <div className="rootRoute">
                    <Route  exact={true} path={path.rootPath} component={EnetryIndex} />
                    <Route  exact={false}  path={path.dashboard.rootPath} component={Dashboard} />
                </div>
            </BrowserRouter>
        </Provider>
        </LocaleProvider>
    </IntlProvider>
    ,
    document.getElementById(ROOTNODEID)
);`

现引入 dva  (  "dva": "^2.2.3",  )
修改 reducer 成为model 后，在   app.start() 函数中报错：

修改后代码如下：
const app = dva({ history: browserHistory });

for(let x = 0 ; x < models.length ; x++){ app.model(models[x])}

`app.router(({ history, app }) => {  
    return  <BrowserRouter history={history} > <div className="rootRoute"> <Route  exact={true} path={path.rootPath} component={EnetryIndex} /> <Route  exact={false}  path={path.dashboard.rootPath} component={Dashboard} /></div></BrowserRouter>
})`

`const AppRoot = app.start();
ReactDOM.render(  <IntlProvider  locale={window.appLocale.locale} messages={window.appLocale.messages} formats={window.appLocale.formats}
    >  <LocaleProvider  locale={window.appLocale.antd}><AppRoot  /></LocaleProvider></IntlProvider> ,  document.getElementById(ROOTNODEID)
);
`
报错信息：
arning: Failed prop type: The prop `children` is marked as required in `Provider`, but its value is `undefined`.
    in Provider (created by DvaRoot)
    in DvaRoot
    in LocaleProvider
    in IntlProvider

The above error occurred in the <Provider> component:
    in Provider (created by DvaRoot)
    in DvaRoot
    in LocaleProvider
    in IntlProvider

嗯，Provider 是react-redux 里提供的 顶级UI组件，应该在 封装后的dva 执行 start 初始化的时候，自动创建了吧。。但是这里，，，

**Comment by QinZonger** [comment]
可以的 挺好用
