### ISSUE TITLE
dva-loading 报错 Can't resolve '@babel/runtime/core-js/object/keys

### ISSUE THREAD

**Issue by flyinhigh** [dvajs/dva#1957]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
![image](https://user-images.githubusercontent.com/681094/48602789-4de1ea80-e9af-11e8-9579-4134e77c548c.png)

**Comment by sorrycc** [comment]
参考 https://github.com/dvajs/dva/issues/2032#issuecomment-473610299 解决，相同的问题。
