### ISSUE TITLE
dva/dynamic动态加载Modal出错

### ISSUE THREAD

**Issue by designersmallweb** [dvajs/dva#1958]
使用dva/dynamic动态导入Modal，有initialState就会报错
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
```
const app = dva({
  history: createHistory(),
  initialState: {
    products: [
      {
        name: 'dva',
        id: 1
      }
    ]
  }
})
const Products = dynamic({
  app,
  models: () => [
    import('./models/products'),
  ],
  component: () => import('./routes/Products')
})
```

#### Expected behavior: (预期的正常效果)
正常使用

#### Actual behavior: (实际效果)
Unexpected key "products" found in previous state received by the reducer.

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"dva": "^2.4.1"

**Comment by i-johnxz** [comment]
我也遇到这个问题，貌似是initialState 的 products的问题，我发觉
![image](https://user-images.githubusercontent.com/5093106/53298345-73f90f80-3867-11e9-8925-3fa9abcf1de8.png)
这里有个deafault 是空的，可以初始化进去，目前不清楚有问题问题。
