### ISSUE TITLE
如何在组件以外调用action或者dispatch

### ISSUE THREAD

**Issue by Murphycx94** [dvajs/dva#1960]
我封装了一个axios，需要在拦截器里调用models方法，应该怎么做？
不是在组件中this.props.dispatch(xxx)

**Comment by ppjjddhh** [comment]
那是在哪里?

**Comment by Murphycx94** [comment]
> 那是在哪里?

已经解决了
store中可以取dispatch，就可以在组件外使用了

**Comment by Johnjiang2016** [comment]
> > 那是在哪里?
> 
> 已经解决了
> store中可以取dispatch，就可以在组件外使用了

store怎么拿？ app._store？
