### ISSUE TITLE
dva可用用在react native中吗

### ISSUE THREAD

**Issue by 2534290808** [dvajs/dva#1965]

**Comment by jinyang1994** [comment]
我自己写了个[demo](https://github.com/concise-online/mobile-app)，仅供参考

**Comment by QinZonger** [comment]
是用的xcode 还是什么；
我的是mac

**Comment by jinyang1994** [comment]
IDE用的是WebStorm，运行的时候用的Xcode或者命令行

**Comment by 2534290808** [comment]
？？？？？？？？？？？？？？？？？

**Comment by taichiyi** [comment]
https://github.com/nihgwu/react-native-dva-starter

**Comment by sppsun** [comment]
https://github.com/sppsun/acgnfuns-app
