### ISSUE TITLE
dva-hmr热更新无效（已按文档配置）

### ISSUE THREAD

**Issue by EasyTuan** [dvajs/dva#1969]
正常配置dva-hmr后，页面显示日志：

[HMR] inited with babel-plugin-dva-hmr

更新代码后浏览器直接刷新,无热更新模块

"roadhog": "^2.5.0-beta.2"
"babel-plugin-dva-hmr": "^0.4.1",

**Comment by ImJoeHs** [comment]
提错repo了，这显然是roadhog的问题。
而roadhog这个问题存在也有段时间了，维护者当前似乎没有空处理，可以先切换回1.x的版本解决。

**Comment by zjjjjjjjjjjd** [comment]
所以现在是无解？

**Comment by tylerrrkd** [comment]
惨。
