### ISSUE TITLE
dvajs.com的https证书过期了

### ISSUE THREAD

**Issue by stanye** [dvajs/dva#1970]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

访问https://dvajs.com/

#### Expected behavior: (预期的正常效果)

提示https警告

#### Actual behavior: (实际效果)

正常访问

#### Versions of packages used: (哪个库的哪个版本出现的问题)

<img width="832" alt="dvajs" src="https://user-images.githubusercontent.com/10014869/49060830-16dec500-f24a-11e8-95f0-b8cfa5408d05.png">

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/49064258-54951b00-f255-11e8-8dc6-bf6183a71ca9.png)

试了下，没有问题？

**Comment by stanye** [comment]
0 0 没问题就好
溜了溜了~
