### ISSUE TITLE
dva  一个严重的问题 文档不全 

### ISSUE THREAD

**Issue by wkm-wangZhe** [dvajs/dva#1977]
举个例子: 
 
 put  call  yeild     put.resolve()  这些API  没有写在文档上面

**Comment by shiny** [comment]
dva 的文档不全真是让人很烦恼啊，入门例子都还没有别人写的好懂。再比如一个 subscriptions 就搞得人一头雾水。

**Comment by wkm-wangZhe** [comment]
const { success } = await this.props.dispatch({});  这个写法文档上也没有,  写代码感觉就是在悟道

**Comment by tsejx** [comment]
put call 这些 api 都是 Redux-saga 的 api，直接看 redux-saga 文档就行了

**Comment by tokenl** [comment]
请问cancel在dva里面怎么使用啊，有大佬了解的不，看了saga的，但是感觉和dva里面有挺大区别的

**Comment by xiaosongxiaosong** [comment]
@tokenl 
和 react-saga 文档中调用方式一样的，dva 和 saga 区别比你想象的小
https://redux-saga-in-chinese.js.org/docs/advanced/TaskCancellation.html

**Comment by xiaosongxiaosong** [comment]
@wkm-wangZhe 
dispatch 时 react-redux 提供的 API， dva 是一个基于其他开源库上的最佳实践，很多 API 是其他基础库提供的，这些 API 的文档应该去看基础库的文档，dva 也不应该将所有设计的接口文档都整合进来
> const { success } = await this.props.dispatch({}); 这个写法文档上也没有, 写代码感觉就是在悟道

**Comment by lx70770** [comment]
@xiaosongxiaosong 请教一下哟   如果连续多次dispatch这个query  怎么取消之前的请求  只取最后的一次呢？？不知道用cancel这个API如何优雅的实现   望不吝赐教
![image](https://user-images.githubusercontent.com/24996868/56134456-32602780-5fc1-11e9-9346-8d7f205746c0.png)

**Comment by luania** [comment]
> @wkm-wangZhe
> dispatch 时 react-redux 提供的 API， dva 是一个基于其他开源库上的最佳实践，很多 API 是其他基础库提供的，这些 API 的文档应该去看基础库的文档，dva 也不应该将所有设计的接口文档都整合进来
> 
> > const { success } = await this.props.dispatch({}); 这个写法文档上也没有, 写代码感觉就是在悟道

至少给个链接吧

**Comment by ZeekoZhu** [comment]
@lx70770  试试这个 https://redux-saga-in-chinese.js.org/docs/basics/UsingSagaHelpers.html

相关的文档应该是 https://dvajs.com/api/#effects

**Comment by lx70770** [comment]
@ZeekoZhu 谢谢   已经在项目里面使用

**Comment by dalaoque** [comment]
namespace 如何优雅的实现 cancel  effects ？？？？？？？？？

**Comment by SHITianhao** [comment]
@dalaoque 并不能，只能一次永久cancel 所有effects
`${namespace}/@@CANCEL_EFFECTS`
https://github.com/dvajs/dva/issues/1749

**Comment by qxchen6** [comment]
![image](https://user-images.githubusercontent.com/25380801/59401497-78711600-8dcd-11e9-8c41-a1496e55bf5a.png)



![image](https://user-images.githubusercontent.com/25380801/59401321-e79a3a80-8dcc-11e9-9755-a02bc01eda54.png)

我在一个effects中新增了一个条目（创建paymentsAccount）
创建成功后需要触发另一个model中的effects（更新paymentsAccounts的字典）。
涉及到在一个model中调用另一个model的effects。

第一张图是文档的写法。
第二张图我照猫画虎写的。
报错内容 object is not a function .
看起来 call第一个参数 只接受函数 。
所以文档该怎么读。。

**Comment by ZeekoZhu** [comment]
@qxchen6 在 effects 里面，`put` 相当于 `dispatch`，所以你应该用 `put` 而不是 `call`

**Comment by qxchen6** [comment]
@ZeekoZhu 
道理俺都懂，我就想知道第一张黑色背景的图是啥意思。那可是官方文档。

`put` 当然可以调用其他`model`里的`reducers`。
但是我想调用其他`model`中的`effects`。
因为另一个`model`中的`effects`中有大量的逻辑。
如果只能`put`其他`model`的`reducers`却不能`call`其他`model`的`effects`的话。
那我只能
- 在当前`model`重新写一遍`effects`
- 或者把行为从`model`移动到组件去重新`dispatch`。。。
以上任何一种都很蛋疼。。。

**Comment by ZeekoZhu** [comment]
> 如果只能`put`其他`model`的`reducers`却不能调用其他`model`的`effects`的话。

你试试，`put` 应该是可以调用 `effects`

**Comment by qxchen6** [comment]
@ZeekoZhu 
还真的可以2333 
感谢道友带我悟道！肥肠感谢！！！

另外我还试了一下
- 如果另一个`model`中的`effects`和`reducers`同名的话，会发生什么？

在我的项目中

1.  我在 `model b` 中 定义了一个 `effects` 叫做 `test` 。同时在 `model b` 中定义了一个`reducer` 也叫`test` 。

2. 我在 `model a ` 中这样做了

```
yield put({
    type:'modelb/test'
});

```

然后我的应用进入了死循环，网页崩溃 233333

**Comment by LukerSpringtree** [comment]
> 举个例子:
> 
> put call yeild put.resolve() 这些API 没有写在文档上面

应该是没学好saga吧 

dva 不是一个 初级入门的框架,用dva 需要很多基础知识的.

**Comment by qxchen6** [comment]
@LukerSpringtree 

你敢说我没学好saga？？
我告诉你 —— 不是没学好，我根本就没看saga。 😂

心急着急搭建项目，直接硬啃ant pro 了 2333.

楼上说得对，确实其他库的文档不应该写在dva里。

但是我觉得应该给个友好的链接什么的 🤣

不过现在已经熟练了，没啥问题了，pro确实帮我省下了很多功夫！

文档太不友好了！嗯，真香。

**Comment by LukerSpringtree** [comment]
@qxchen6 
哈哈哈  加油!
我爱 dva dva 爱我

**Comment by swdenglian** [comment]
其实可以看 dva-core 与 dva 的相关单元测试
