### ISSUE TITLE
dva中如何应用第三方的react组件

### ISSUE THREAD

**Issue by fangxukun** [dvajs/dva#198]
使用第三方组件如：codemirror(https://github.com/JedWatson/react-codemirror/blob/master/example/src/example.less )，发现样式无法加载进来。如何能够和antd一样加载外部组件的css?

**Comment by nikogu** [comment]
![image](https://cloud.githubusercontent.com/assets/1179603/19682430/1ef1894e-9ae0-11e6-9fbb-e4592569dee6.png)

css中：https://github.com/dvajs/dva/issues/199

**Comment by fangxukun** [comment]
ok,thanks
