### ISSUE TITLE
2.4.1 版本依赖 @babel/runtime 7.0.0-beta46 导致可能存在的 babel helper 函数 module not found 问题

### ISSUE THREAD

**Issue by hijiangtao** [dvajs/dva#1980]
首先想问下 2.4.1 往后的版本最近有正式发布的计划么，由于 2.4.1 版本 package.json 中写死了 @babel/runtime 版本为 7.0.0-beta46, 而 @babel/runtime 从 7.0.0-beta56 开始重命名了 es6 文件夹（详见 https://github.com/babel/babel/pull/8266#issuecomment-405059388 ），于是导致一个问题：

如果引用的包对 @babel/runtime 的依赖是 `^7.0.0` 那么实际安装的版本便会是 7.0.0及以后（现在是 7.2.0）版本，而 dva2.4.1 依赖的是 7.0.0-beta46，这样就会导致其他依赖最新 babel 的包可能找不到模块（如果模块开发者依赖的是最新 babel 版本，。并在代码中写了类似的 helper import 代码），类似：

```
Module not found: 
Can't resolve '@babel/runtime/helpers/esm/assertThisInitialized' in 
'/site/node_modules/_luma.gl@6.3.1@luma.gl/dist/esm/webgl'
```

由于让其他依赖库回滚对 babel helper 写法是不现实且不推荐的，且我看 dva 2.5.0 beta 已经 merge 了相关依赖（详见 https://github.com/dvajs/dva/pull/1908 ），所以如果 dva 能尽快更新该版本至正式版，会是当下我认为最好的解决方案。

**Comment by xiamu14** [comment]
我在 2.4.1 也遇到了这个问题， 官方是不打算处理了吗?

**Comment by sydboys** [comment]
折腾了很久，最后简单粗暴的处理
npm i @babel/runtime-corejs2 -D
npm i @babel/plugin-transform-runtime -D
然后在webpack的配置中设置alias: '@babel/runtime': '@babel/runtime-corejs2'

**Comment by wangweida** [comment]
这个问题不管了吗？这架子三天两头打包就报错 真是服了

**Comment by sorrycc** [comment]
参考 https://github.com/dvajs/dva/issues/2032#issuecomment-473610299 解决，相同的问题。

**Comment by 104gogo** [comment]
还可以在需要的项目里面安装最新的 `@babel/runtime` 来解决这个问题。避免 dva 以后发布新版本了，resolve.alias 的设置没意义。
最后想知道，dva 什么把 beta 版本正式发布了？

**Comment by sydboys** [comment]
我是基于自定义webpack+dva 的方案 @babel/runtime 里已经删除了core-js
现在需要@babel/runtime-corejs2 + @babel/
plugin-transform 然而按官方设置runtime， 转换插件无效 所以使用alias强制使用corejs2的包 这样就可以解决问题了 
对于直接使用dva脚手架的同学 可以不需要设置alias 直接创建 webpack.config.js 然后删除掉modules的设置即可 这样
dva 会自己使用私有node_modules的runtime包

**Comment by cszo** [comment]
> 折腾了很久，最后简单粗暴的处理
> npm i @babel/runtime-corejs2 -D
> npm i @babel/plugin-transform-runtime -D
> 然后在webpack的配置中设置
> alias: '@babel/runtime': '@babel/runtime-corejs2'
> babel配置中启用插件“@babel/plugin-transform-runtime”
> 
> 最新的@babel/runtime 已经删除了core-js的包
> 
> 当然webpack 别设置resolve.modules参数也可以不需要按上面那个设置
只用了dva-core+自己配置webpack  遇到这个问题折腾了两天   整个babel文档都研究了一遍  现在解决了  感谢大佬

**Comment by sydboys** [comment]
每个人使用的cli不同，有的自己定义，有的使用官方cli,  然后依赖的包不同导致出现各种问题。
其实只要解决一个问题：让dva依赖它本来需要依赖的那个@babel/runtime 版本。

关于resolve.alias的问题, 有的commit里是删除，有的是增加，其实都会有问题：
因为有些配置导致resolve.alias里重定义了@babel/runtime的版本，而导致dva的依赖失效，这时设置@babel/runtime的alias还是删除alias根据情况自己定义，总之能让dva找到它写死的那个@babel/runtime包，问题就不会出现，就算出问题也不是这个问题。

**Comment by cszo** [comment]
> 还可以在需要的项目里面安装最新的 `@babel/runtime` 来解决这个问题。避免 dva 以后发布新版本了，resolve.alias 的设置没意义。
> 最后想知道，dva 什么把 beta 版本正式发布了？
我的项目中只使用dva-core  1.4.0  这个最新版的是一年前了。。。不打算单独维护了吧。。
最新版的@babel/runtime 把core-js删了  同时目录结构helpers/esm   而之前7.0.0版本@babel/runtime的还有core-js但是又是helpers/es6  用了这个虽然dva-core没问题了，但是又导致很多新版本的其他库又报错。所以只能用@babel/runtime-corejs2  又有core-js又是helpers/esm。
