### ISSUE TITLE
dva-core 不支持 iOS8

### ISSUE THREAD

**Issue by starandtina** [dvajs/dva#1981]
最近项目有做基于 dva-core@1.5.0-beta.2 的小程序版本，在做兼容性测试时，发现出现白屏，是在 dva-core 下面这段代码(`for of`)报出来的，根本原因是最新版本升级至了 babel@7 并使用了 @babel/runtime，编译之后的代码里有 `Symbol`，而 iOS8 并不支持 `Symbol` 语法导致。

```JavaScript
    for (const m of app._models) {
      reducers[m.namespace] = getReducer(
        m.reducers,
        m.state,
        plugin._handleActions
      );
      if (m.effects)
        sagas.push(app._getSaga(m.effects, m, onError, plugin.get('onEffect')));
    }
```

目前有二种方案可以临时解决，一是切换 dva-core 至 dva-core@1.1.0(babel@6) ，二是在项目代码中设置 bable-loader 支持编译 `node_modules` 目录。**babel** 那边也有类似的讨论 https://github.com/babel/babel/issues/7597

有二个问题，

- dva 会支持到 iOS8 吗？
- 这个问题需要解决吗？还是等 babel 那边？还是自己解决？

#### Expected behavior: (预期的正常效果)
![image](https://user-images.githubusercontent.com/613990/49845608-5688dd80-fe02-11e8-957c-7096c2863eab.png)

#### Actual behavior: (实际效果)
![image](https://user-images.githubusercontent.com/613990/49845604-512b9300-fe02-11e8-8ebf-bf651ab4407c.png)

#### Versions of packages used: (哪个库的哪个版本出现的问题)
1.5.0-beta.2

**Comment by sorrycc** [comment]
可以提 pr 解决，应该是需要在构建时不启用 symbol 特性。

**Comment by starandtina** [comment]
@sorrycc 如果使用 `@babel/runtime-corejs2` 是可以编译 `Symbol` 的，因为它包含了 [core-js 依赖](https://github.com/babel/babel/blob/master/packages/babel-runtime-corejs2/package.json#L12)。

我查看 `dva-core/package.json` 的历史提交记录，发现之前有[提交过一个 PR ](https://github.com/dvajs/dva/pull/1908)就是修改 `@babel/runtime` 为 `@babel/runtime-corejs2`，但是当天就 revert 了，想问问中间是有什么问题吗？可以再使用 `@babel/runtime-corejs2` 吗？DEMO 和测试用例是可以跑过的。

https://github.com/dvajs/dva/commits/master/packages/dva-core/package.json

**Comment by starandtina** [comment]
@sorrycc any comment? :)
