### ISSUE TITLE
多个相同 effects ，其中一个结束，会导致 loading 值提前为 false

### ISSUE THREAD

**Issue by tianfanfan** [dvajs/dva#1984]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
dva-loading 在稍微复杂的异步触发 effect 时候，记录不准确

``````js
const query = async params => {
  const data = await new Promise(resolve => {
    setTimeout(() => {
      // 模拟请求响应延迟
      resolve({data:1});
    }, 2000);
  });
  return data;
};

// modle  foo.js
export default {
  effects: {
    queryTest: function*({payload},  { call, put } ) {
      yield Promise.resolve();
      const { data } = yield call(query, payload);
    }
  }
}

// page index.js
function products(props) {
  return <div>Loading: {JSON.stringify(props.loading)}</div>;
}

export default connect(state => {
  const loading = state.loading.effects['foo/queryTest'];
  return {
    loading
  };
})(products);

// 控制台输入：
window.g_app._store.dispatch({type:'a/queryTest'}) 
// 模拟请求发送延迟
setTimeout(() => {
  window.g_app._store.dispatch({type:'a/queryTest'}) 
}, 1000);

``````

#### Expected behavior: (预期的正常效果)

| 时间 | loading值 |
| ------ | ------ |
| 1s | true |
| 2s | true |
| 3s | true |
| 4s | false |

多个相同 effects ，其中一个结束，会导致 loading 值提前为 false。
建议是全部结束，才会恢复为 false。
建议增加，计数功能。和

#### Actual behavior: (实际效果)

| 时间 | loading值 |
| ------ | ------ |
| 1s | true |
| 2s | true |
| 3s | false |
| 4s | false |

#### Versions of packages used: (哪个库的哪个版本出现的问题)
最新版本 dva loading 库

**Comment by Nuoky** [comment]
有一样的问题，发生在用户重复请求时接口返回的顺序不同。

**Comment by WavinFlag** [comment]
也就是说，某种 action type 的 effect 的结束与否，需要用计数器、而不只是布尔值来表示。

**Comment by zjxpcyc** [comment]
@tianfanfan 你说的是 Promise.all 的场景， Promise.race 的场景又该怎么去处理 ？

感觉，你应该从你的业务逻辑或者 `queryTest` 的方法去解决问题。
