### ISSUE TITLE
typescript没有语法错误检查的问题

### ISSUE THREAD

**Issue by inuyasha0618** [dvajs/dva#1988]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
dva new test-project, 进入文件src/index.js将其改名为 src/index.ts， 并在文件中加入代码const str: number = {};  然后npm start启动服务

#### Expected behavior: (预期的正常效果)
npm start编译并启动服务时检查typescript文件中的语法错误并输出在控制台

#### Actual behavior: (实际效果)
ts文件中有语法错误时（如const str: number = {}）,npm start能正常编译通过且不会提示有任何语法问题。

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"dva": "^2.4.1"

**Comment by mangoZT** [comment]
我也是 配置了后能正常使用tsx，但是类型错误也不报错，该配的都配了
