### ISSUE TITLE
关于reducers和effects 使用相同名字会造成死循环

### ISSUE THREAD

**Issue by sunguoxing0628** [dvajs/dva#1996]
以下代码是我的`models`文件夹下的`system.js`文件，`reducers`和`effects` 使用的名字相同`fetch`

```
import { query } from '@/services/api';

export default {
  namespace: 'system',

  state: {
    list: [],
  },

  effects: {
    * fetch({ payload }, { call, put }) {
      const response = yield call(query, payload);
      yield put({
        type: 'fetch',
        payload: response,
      });
    },
  },

  reducers: {
    fetch(state, action) {
      return {
        ...state,
        list: action.payload,
      };
    },
  },
};
```

#### Expected behavior: (预期的正常效果)

接口使用的是`post`请求，正常情况下会对服务器发送两次请求：`options`和`post`，执行后返回结果数据。

#### Actual behavior: (实际效果)
通过对发送的请求监控（chrome 开发者工具，找到Network），接口在一直带着空参数进行请求。

#### Versions of packages used: (哪个库的哪个版本出现的问题)
`dva 2.4.0`

#### Other:（我的问题）

1、同名造成死循环是否是因为`BUG`。

2、很多刚接触dva的人来说，很少注意这个问题，希望在官网里增加关于这个问题的注意事项。

**Comment by Bubbleinpit** [comment]
这不能写成同名啊。。不然你dispatch的时候，到底是要执行哪一个呢？

**Comment by Bubbleinpit** [comment]
不过的确我也觉得官方文档里省略了很多需要注意的内容，可能因为默认大家都是会用dva依赖的那些npm包的？

**Comment by sunguoxing0628** [comment]
> 不过的确我也觉得官方文档里省略了很多需要注意的内容，可能因为默认大家都是会用dva依赖的那些npm包的？

@Bubbleinpit  我开始用的时候以为是`dispatch`的时候只会用到`effects`里的方法，而`effects`用`reducers `里的方法，这样即使同名也没有关系，然后，并不是，最主要的是官方文档里没提示注意，当时看到浏览器差点卡死，心都碎了。
@sorrycc 是否可以在文档里增加注意事项呢？

**Comment by INTMIN** [comment]
我也碰到这个问题，然后项目很复杂，我还以为我哪个地方写错了，打了大半天的debug
