### ISSUE TITLE
dispatch触发action，model和page内建议保持一致 —> namespace/type

### ISSUE THREAD

**Issue by Confetti7** [dvajs/dva#1997]
如果在 model 外调用，需要添加 namespace
如果在 model 内调用，默认不添加 namespace，如果添加dva会给一个waring

#### Expected behavior: (预期的正常效果)

dispatch触发action时，建议保持一致，就是namespace/type。
model和page内调用不一致给人的感觉比较乱。

现在虽兼容写法，但是会有一个waring，建议去掉waring，并抹去model内的简写写法。

**Comment by SHITianhao** [comment]
这个warning纯属大佬个人代码偏好。感觉这个项目对issue的回应还有更新都特别不积极，估计都去搞umi了

**Comment by Confetti7** [comment]
> 这个warning纯属大佬个人代码偏好。感觉这个项目对issue的回应还有更新都特别不积极，估计都去搞umi了

嗯嗯 我挺喜欢dva的设计的。  
个人感觉umi没有太大必要，webpack4配置简化好多了，大佬们如果给出一个基础好用的结构配置就ok了。

**Comment by Confetti7** [comment]
@SHITianhao 
嗯嗯 我挺喜欢dva的设计的。
个人感觉umi没有太大必要，webpack4配置简化好多了，大佬们如果给出一个基础好用的结构配置就ok了。

**Comment by SHITianhao** [comment]
@Confetti7 你可以看那个roadhog， 根据我在`umi-notification` 里看到的信息，那个项目应该从三月就要停止维护了。
我也觉得umi 是个很好的愿景，但是这种convention over configuration的开源项目不是太适合公司使用。因为每个公司的业务逻辑需求是不一样的，对于项目组织架构也会有不同的需求。不过还是很有启发性

**Comment by Confetti7** [comment]
@SHITianhao 
嗯嗯 感谢前辈
我只是简单用了下便妄下结论，还是自己去好好学习源码之后再做评价。
虽然不喜欢无休止的轮子，但是想想每一个轮子都有他非常好的思想，都值得学习。
再次感谢~

**Comment by nelhu** [comment]
为什么close，希望无论model内外，都保持一致：dispatch: namespace/type。或者提供option控制开关， warning的存在很别扭。
