### ISSUE TITLE
ReactDOM.render渲染的组件无法通过connect访问redux里的数据，怎么解决？

### ISSUE THREAD

**Issue by heyizhiyuan** [dvajs/dva#1999]
ReactDOM.render渲染的组件无法通过connect(dva)访问redux里的数据，怎么解决？

![hg8tyi2n1n7hb 6c4gt 5r](https://user-images.githubusercontent.com/39208129/51595352-78ad6980-1f31-11e9-8b3a-371876e672e6.png)

**Comment by shellphon** [comment]
正巧遇到了这个问题，见这里没说明，我在这里补充一下我临时解法：按提示是要给Connect包裹后返回的组件，传store。
store可以通过`getDvaApp()._store`获得。启发自：https://github.com/dvajs/dva/issues/1491#issuecomment-641166733
不过如果组件内还有组件，还是会报同样问题。
