### ISSUE TITLE
什么时候可以引入react-intl

### ISSUE THREAD

**Issue by t04041143** [dvajs/dva#20]
这个好像不难，在provider外面包下，然后做些polyfill的工作就好

**Comment by sorrycc** [comment]
现在就可以和 react-intl 配合使用，因为 `app.start()` 返回的是一个 React Component，可以给他外面套一层 IntlProvider，然后给 ReactDOM 渲染。比如：

```bash
import { IntlProvider } from 'react-intl';
import ReactDOM from 'react-dom';
import dva from 'dva';

const app = dva();
app.model();
app.router();

const App = app.start();
ReactDOM.render(<IntlProvider><App /></IntlProvider>, htmlElement);
```

**Comment by t04041143** [comment]
真是棒极了

**Comment by xgenvn** [comment]
just a small remark of above code:
`htmlElement = document.GetElementById('root');`

**Comment by herozeng** [comment]
这样的话，浏览器其它地方国际化了，但是title标签还是没有国际化，有什么办法统一处理

**Comment by sorrycc** [comment]
@herozeng https://github.com/gaearon/react-document-title

**Comment by ZeroJsus** [comment]
这样处理了之后 会导致 App 下挂的组件 不能进行热加载 。。。。。

**Comment by junbinxu** [comment]
![image](https://user-images.githubusercontent.com/5479604/60955256-0db2ec00-a333-11e9-9c7c-7eea4056ad42.png)
你好，怎么我的会报错？

**Comment by AngYang123** [comment]
> 现在就可以和 react-intl 配合使用，因为 `app.start()` 返回的是一个 React Component，可以给他外面套一层 IntlProvider，然后给 ReactDOM 渲染。
> 
> 比如：
> 
> ```shell
> import { IntlProvider } from 'react-intl';
> import ReactDOM from 'react-dom';
> import dva from 'dva';
> 
> const app = dva();
> app.model();
> app.router();
> 
> const App = app.start();
> ReactDOM.render(<IntlProvider><App /></IntlProvider>, htmlElement);
> ```

这样是可以将语言传到子组件了，但是切换语言的操作这里怎么感知呢，我的切换操作是在header组件中进行的

**Comment by Mr-Kapok** [comment]
> > 现在就可以和 react-intl 配合使用，因为 `app.start()` 返回的是一个 React Component，可以给他外面套一层 IntlProvider，然后给 ReactDOM 渲染。
> > 比如：
> > ```shell
> > import { IntlProvider } from 'react-intl';
> > import ReactDOM from 'react-dom';
> > import dva from 'dva';
> > 
> > const app = dva();
> > app.model();
> > app.router();
> > 
> > const App = app.start();
> > ReactDOM.render(<IntlProvider><App /></IntlProvider>, htmlElement);
> > ```
> 
> 这样是可以将语言传到子组件了，但是切换语言的操作这里怎么感知呢，我的切换操作是在header组件中进行的

同问如何切换语言，老哥找到方案了吗

**Comment by georgezouq** [comment]
@AngYang123 @lauhuawei 切换语言的问题解决了吗 ？

**Comment by junbinxu** [comment]
您好，您的邮件我已收到，我会及时认真处理，祝您生活愉快。
