### ISSUE TITLE
fetch.d.ts

### ISSUE THREAD

**Issue by imhele** [dvajs/dva#2000]
About fetch.d.ts
```
Type originates at this import. A namespace-style import cannot be called or constructed, and
will cause a failure at runtime. Consider using a default import or import require here instead.
```

#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

Create a new file:
```ts
import fetch from 'dva/fetch';
fetch('https://example.com');
```

#### Expected behavior: (预期的正常效果)

```ts
export { default } from 'isomorphic-fetch';
```

#### Actual behavior: (实际效果)

```ts
import * as isomorphicFetch from 'isomorphic-fetch';

export = isomorphicFetch;
```

#### Versions of packages used: (哪个库的哪个版本出现的问题)

fd32ee67e7b5263510fff38457e1485e1206e25b

**Comment by calefy** [comment]
vscode提示我要改成这样才对：
```js
import isomorphicFetch from 'isomorphic-fetch';

export = isomorphicFetch;
```

**Comment by imhele** [comment]
> vscode提示我要改成这样才对：
> 
> ```js
> import isomorphicFetch from 'isomorphic-fetch';
> 
> export = isomorphicFetch;
> ```

是的，这种方法同样是拿到 export.default

**Comment by imhele** [comment]
升级 TS 版本之后似乎没有报错了
