### ISSUE TITLE
dva 依赖的 react-redux@5.0.7 与 React@16.6.0 版本部分新特性不配套

### ISSUE THREAD

**Issue by xiaosongxiaosong** [dvajs/dva#2002]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
1. 使用 React.memo 代替 React.PureComponent 时 connect 会出错
2. 查看 react-redux 更新日志，5.1.0 版本开始支持 React.memo 等新特性
3. 检查 dva 依赖，react-redux 版本锁定在 5.0.7
> react-redux v5.1.0 更新日志
> https://github.com/reduxjs/react-redux/releases/tag/v5.1.0

> dva 依赖 react-redux 版本锁定在 5.0.7
> https://github.com/dvajs/dva/pull/1932

**Comment by SHITianhao** [comment]
同上，能否考虑升级`react-redux` 同时使用`DefinitelyTyped` 的ts定义？

**Comment by basicfu** [comment]
从react-redux@5.0.6升级到6.0+时，使用connect会出现以下错误
![image](https://user-images.githubusercontent.com/26153901/52630055-217a3380-2ef6-11e9-959d-b3339ad5bb08.png)

**Comment by wooline** [comment]
可以试一下类似框架：[react-coat](https://github.com/wooline/react-coat)，兼容react-redux 6.0，typescript编写

**Comment by succulen-plants** [comment]
React.memo 需要redux 5.1.0望升级  这个问题怎么解决
