### ISSUE TITLE
'delete'(state, { payload: id }) 报错

### ISSUE THREAD

**Issue by HUANGLIWEN** [dvajs/dva#2003]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

https://dvajs.com/guide/getting-started.html#%E5%AE%9A%E4%B9%89-model

export default {
  namespace: 'products',
  state: [],
  reducers: {
    'delete'(state, { payload: id }) {
      return state.filter(item => item.id !== id);
    },
  },
};

#### Actual behavior: (实际效果)
'delete'报错

**Comment by lishuai1021** [comment]
delete加引号后还是方法名吗

**Comment by esymeptoo** [comment]
['delete']() {}试试

**Comment by esymeptoo** [comment]
delete是关键字啊大哥

**Comment by rocLv** [comment]
> delete是关键字啊大哥

为什么可以这样写？
