### ISSUE TITLE
怎么实现部分状态使用redux-undo?

### ISSUE THREAD

**Issue by neoimale** [dvajs/dva#2004]
如题。现在官方给的例子都是在onReducer中存储完整state。

**Comment by happier2** [comment]
自己写reducer，然后使用dva的extraReducers

**Comment by happier2** [comment]
> 如题。现在官方给的例子都是在onReducer中存储完整state。

自己写reducer，然后使用dva的extraReducers

**Comment by nihgwu** [comment]
```
import undoable from 'redux-undo';

export default {
  namespace: 'xxx',
  reducers: [
    {...},
    reducer => undoable(reducer, { filter: action => action.type.indexOf('xxx/') === 0 }),
  ]
}
```

see https://github.com/dvajs/dva/pull/69#issuecomment-245157593

**Comment by RockyF** [comment]
> ```
> import undoable from 'redux-undo';
> 
> export default {
>   namespace: 'xxx',
>   reducers: [
>     {...},
>     reducer => undoable(reducer, { filter: action => action.type.indexOf('xxx/') === 0 }),
>   ]
> }
> ```
> 
> see [#69 (comment)](https://github.com/dvajs/dva/pull/69#issuecomment-245157593)

您给出的代码跑不通，这种接入`redux-undo`的方式不行
也尝试了`reducer => (state, action) => undoable(reducer, {})(state, action)`，也不行
会导致整个state为undefined的运行时错误！
请完善一下`examples/with-redux-undo`，让我们能够直观得看懂如何实现model level的undo！
谢谢！
