### ISSUE TITLE
在dva项目中引入本地js库已经引入成功可以调用这个本地js中的方法，但是调用本地js方法发送网络请求 前缀为locahost

### ISSUE THREAD

**Issue by johnsky123** [dvajs/dva#201]
请求的链接 是  http://localhost:8989/plangh__XXXXX/  这样的  发送请求不成功接收不到返回数据

**Comment by sorrycc** [comment]
没明白问题点，是指发出请求的 URL 不对?

**Comment by johnsky123** [comment]
嗯  本地js库发出请求的url不对应该为http://www.XXX.com/plangh_xxxx    实际发起请求的链接为http://localhost:8989/www.XXX.com/

**Comment by sorrycc** [comment]
感觉是路径问题，换成绝对路径就好了。

**Comment by johnsky123** [comment]
我没有在js中写请求路径   js 请求路径是引入的js文件封装好的

**Comment by johnsky123** [comment]
@sorrycc   求大神传授方法   刚我把调用外部js的方法 写在组件外部   发起的请求还是不正确   写把调用方法 写在componentDidMount ()   和 componentWillReceiveProps ()  都没有反应

**Comment by sorrycc** [comment]
给个能重现的 repo 吧，还是不太能理解到问题的点。

**Comment by nikogu** [comment]
你是组件的 url 参数写错了吧，比如：

```
ajax({})

```

**Comment by johnsky123** [comment]
不是的 抱歉 我描述的不清楚  我引用了一个外部的js库    在组件render方法后 调用外部js库的方法  这个方法可以发送请求  但发送请求的  url  为 http:// localhost:8989/undefined/opensource/12345    这就造成了 无法请求到数据   实际应该发送的请求为 http://www.XXX.com/opensource/12345  这些请求的链接是外部js封装好的   我无法改变这些请求链接   我应用外部库的方法是 在index.js 中   import a  from 'a.js'     window.a=a  export default a        @sorrycc @nikogu

**Comment by nikogu** [comment]
@johnsky123 贴关键代码吧，你首先需要搞清楚你的请求是怎么发出去的，无论内部库还是外部库，你看下它怎么发请求的不就知道了
