### ISSUE TITLE
请求返回的结果为纯字符串时，会报错

### ISSUE THREAD

**Issue by UlyC** [dvajs/dva#2018]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

 ` * operate({drill, action, payload}, {call, put}) {
            try {
                const rsp = yield call(tasksService.operateTask, drill, action, payload);
                alert(rsp)
            } catch (e) {
                alert(e)
            }
        },`

#### Expected behavior: (预期的正常效果)
请求返回的结果 rsp为纯字符串时，正常处理此结果

#### Actual behavior: (实际效果)
请求返回的结果为rsp纯字符串时，就会报错。请问是dva故意为之的吗

**Comment by sorrycc** [comment]
不是，这和 dva 无关，`tasksService.operateTask` 里处理出错了吧。
