### ISSUE TITLE
支持 model namespace 检测命名冲突 console 提示

### ISSUE THREAD

**Issue by nightink** [dvajs/dva#203]
在开发阶段经常会通过 `cp` 创建新的 model，忘记修改 `namespace`。
导致页面报错，这个时候需要小小的排查一下，才能焕然大悟忘记改 namespace 了。

所以希望在开发阶段 `namespace` 能提检测命名冲突的提示

**Comment by jerexyz** [comment]
可以用es6 [Symbol](http://es6.ruanyifeng.com/#docs/getFieldDecorator) 来定义namespace,这样就不会冲突了。

**Comment by iwege** [comment]
@jerexyz cp的场景下面这个namespace 是错误的，可能需要warn一下。

**Comment by sorrycc** [comment]
感谢反馈，下个版改进。另外可以关注下 https://github.com/dvajs/dva-cli/pull/13 ，可通过 `dva g model modelName` 生成 model 并自动注册到 entry 。

**Comment by nightink** [comment]
@sorrycc goooood~~~~~

**Comment by hanagm** [comment]
越来越像mantra了

**Comment by sorrycc** [comment]
@hanagm https://github.com/kadirahq/mantra 这个?

**Comment by sorrycc** [comment]
这个已经支持了，namespace 冲突会报错。
