### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by zhilianbi520** [dvajs/dva#2030]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
控制台报错信息：
![Jietu20190315-112709](https://user-images.githubusercontent.com/16549630/54406653-de3dfb00-4715-11e9-9fe8-27775092b24f.jpg)
![Jietu20190315-112838](https://user-images.githubusercontent.com/16549630/54406674-f281f800-4715-11e9-9ca1-0697f285b94a.jpg)

出现以上报错的操作如下：
频繁点击页面，对页面多次操作后，会出现一直loading的状态。

#### Expected behavior: (预期的正常效果)
不报错，正常请求接口获取数据

#### Actual behavior: (实际效果)
一直loading，需手动刷新浏览器才能正常显示

#### Versions of packages used: (哪个库的哪个版本出现的问题)
ant-design-pro  2.1.2 版本
dva 2.4版本
umi 2.5版本

**Comment by zhilianbi520** [comment]
https://github.com/webpack/webpack/issues/7502 在webpack上找到同样的issue

**Comment by sorrycc** [comment]
请给出复现仓库和步骤。
