### ISSUE TITLE
启动之后打开页面报错 Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`.

### ISSUE THREAD

**Issue by bestXie** [dvajs/dva#2035]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
1.dva new app
2.新建 webpack.config.js，内容如下：
export default function(webpackConfig) {
  delete webpackConfig.resolve.alias['@babel/runtime'];
  return webpackConfig;
}
2.npm start

#### Expected behavior: (预期的正常效果)
浏览器正常显示页面

#### Actual behavior: (实际效果)
浏览器控制台输出 Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva-cli version 0.10.0

**Comment by bestXie** [comment]
<img width="866" alt="WechatIMG24" src="https://user-images.githubusercontent.com/18387321/54489669-b43d3200-48e9-11e9-82bf-5933b04400d1.png">

**Comment by sorrycc** [comment]
请给出可复现步骤。

**Comment by bestXie** [comment]
1.dva new app
2.新建 webpack.config.js，内容如下：
export default function(webpackConfig) {
delete webpackConfig.resolve.alias['@babel/runtime'];
return webpackConfig;
}
2.npm start
3.浏览器查看控制台

index.js:2177 Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.

**Comment by sorrycc** [comment]
warning 信息忽略，不影响使用，下个版本会解决。

**Comment by mystylemylife** [comment]
> 1.dva new app
> 2.新建 webpack.config.js，内容如下：
> export default function(webpackConfig) {
> delete webpackConfig.resolve.alias['@babel/runtime'];
> return webpackConfig;
> }
> 2.npm start
> 3.浏览器查看控制台
> 
> index.js:2177 Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.



> 1.dva new app
> 2.新建 webpack.config.js，内容如下：
> export default function(webpackConfig) {
> delete webpackConfig.resolve.alias['@babel/runtime'];
> return webpackConfig;
> }
> 2.npm start
> 3.浏览器查看控制台
> 
> index.js:2177 Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.

![image](https://user-images.githubusercontent.com/21253828/54526858-09914600-49b3-11e9-8afa-0cafa3c38039.png)
这个问题怎么解决的？求助

**Comment by sorrycc** [comment]
@mystylemylife 给复现步骤。。

**Comment by mystylemylife** [comment]
> @mystylemylife 给复现步骤。。



> @mystylemylife 给复现步骤。。
解决了，之前因为启动_history@4.9.0报错，所以按照@bestXie 的方法增加webpack.config.js移除'@babel/runtime'，不报错了，但又报的是我之前截图的错误，现在去掉这个js，并升级roadhog版本为2.5.0-beta.4就好了

**Comment by huyawei** [comment]
老项目重新安装nodemodule 就报错一看是_history@4.9.0的问题
更新dva吧就跟楼主一样
什么鬼现在

**Comment by mystylemylife** [comment]
> 老项目重新安装nodemodule 就报错一看是_history@4.9.0的问题
> 更新dva吧就跟楼主一样
> 什么鬼现在

升级roadhog版本为2.5.0-beta.4就好了

**Comment by pvfhv** [comment]
import { createBrowserHistory } from 'history'

**Comment by mikexfreeze** [comment]
这都几个月了，真是上了贼船了。

**Comment by Harhao** [comment]
> > 老项目重新安装nodemodule 就报错一看是_history@4.9.0的问题
> > 更新dva吧就跟楼主一样
> > 什么鬼现在
> 
> 升级roadhog版本为2.5.0-beta.4就好了

升级roadhog版本为2.5.0-beta.4也是会出现这个问题的

**Comment by aiyuchen** [comment]
**解决：**

1. 在项目中`node_modules`中的`dva`文件夹，修改`lib/index.js`
2. 找到这行代码如下
```
var _createHashHistory = _interopRequireDefault(require("history/createHashHistory"));
```
3. 修改`require中的路径,如下：
```
var _createHashHistory = _interopRequireDefault(require("history").createHashHistory);
```
保存关闭编译器，重新启动服务 就好了

**Comment by m430** [comment]
dva感觉已经不维护了吗？这个问题这么久还存在，为什么关闭了

**Comment by xiaodun** [comment]
通过代理原生的console.warn和console.error解决
```
      (() => {
        //过滤掉一些无用的警告、没有价值的报错
        //代理console.warn方法
        const _consoleWarn = console.warn;
        console.warn = (...rest) => {
          if (
            ![
              'react-error-overlay is not meant for use in production. You should ensure it is not included in your build to reduce bundle size.',
              'Warning: componentWillReceiveProps has been renamed',
              'Warning: componentWillUpdate has been renamed',
            ].some((item) => rest[0].indexOf(item) !== -1)
          ) {
            _consoleWarn(...rest);
          }
        };
        //代理console.error
        const _consoleError = console.error;
        console.error = (...rest) => {
          if (
            ![
              `Warning: Please use \`require("history").createHashHistory\` instead of \`require("history/createHashHistory")\`. Support for the latter will be removed in the next major release.`,
              'ui socket init',
            ].includes(rest[0].toString())
          ) {
            _consoleError(...rest);
          }
        };
      })();
```

**Comment by FaberSober** [comment]
自己写了一个补丁，每次启动前，替换`./node_modules/dva/lib/index.js`中`require\\("history/createHashHistory"\\)`替换为`require("history").createHashHistory`：
1. yarn add -D replace;
2. 在根目录下增加`patch.js`文件，内容如下：
```js
const replace = require("replace");

replace({
  regex: 'require\\("history/createHashHistory"\\)',
  replacement: 'require("history").createHashHistory',
  paths: ['./node_modules/dva/lib/index.js'],
  recursive: true,
  silent: true,
});
```
3. 在`package.json`中增加如下代码，在`start`命令前增加`npm run patch && `，增加`"patch": "node ./patch.js"` `npm`命令：
```js
{
  ...
  "scripts": {
    "start": "npm run patch && cross-env APP_TYPE=site umi dev", // start命令之前先运行patch.js
    ...
    "patch": "node ./patch.js"
  },
  ...
}
```

**Comment by Tridu33** [comment]
> 请给出可复现步骤。

https://stackblitz.com/edit/dva-example-count-vuhqet?file=index.js
