### ISSUE TITLE
dva-loading 怎么删掉没必要的loading

### ISSUE THREAD

**Issue by yehoan** [dvajs/dva#2036]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
![image](https://user-images.githubusercontent.com/22631753/54527385-bc15d880-49b4-11e9-9834-2ee06e60c1ee.png)

#### Expected behavior: (预期的正常效果)

有些请求没必要显示loading  但是我看使用了dva-loading 以后自动加上了 想咨询下 怎么删掉没必须要的loading
#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva-loading

**Comment by K68** [comment]
`// 2. Plugins
app.use(createLoading({
    only: [ // only these effects will trigger loading
        'search/queryUsers',
    ],
}));`
类似我上面的配置，只对你需要的effects开启loading
