### ISSUE TITLE
createHashHistory引用的warning，控制台有warning

### ISSUE THREAD

**Issue by mankeheaven** [dvajs/dva#2039]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
var _createHashHistory = _interopRequireDefault(require("history/createHashHistory"));

Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.
#### Versions of packages used: (哪个库的哪个版本出现的问题)

2.4.1

**Comment by ahKevinXy** [comment]
me ye to what happen to solve this question

**Comment by Zronel** [comment]
遇到了同样的问题，在dva/lib/index.js  里头修改之后就没这个warning了

**Comment by 951759534** [comment]
+1

**Comment by jonyjayang** [comment]
怎么解决有老哥说一下嘛

**Comment by meowtec** [comment]
我看了下 commit 记录，前些时候这个问题已经改好了，但是不知道什么时候 publish @sorrycc

**Comment by WinwardZ** [comment]
+1

**Comment by BETH-zhang** [comment]
等待版本更新，我们也好及时升级

**Comment by schwanncheung** [comment]
这个问题在这个提交已经修复了 https://github.com/dvajs/dva/pull/2023 ，但不知道为啥没有发布。

**Comment by hmz5** [comment]
为什么都是使用的2.4.1有的报错有的不报错？

**Comment by sorrycc** [comment]
+ [dva@2.6.0-beta.1](https://github.com/dvajs/dva/releases/tag/dva%402.6.0-beta.1)

**Comment by furylee** [comment]
最新版还是有啊

**Comment by Herrengit** [comment]
最新版本也有这个问题

**Comment by SherryQueen** [comment]
大佬  啥时候能解决一下额

**Comment by FrankFan** [comment]
升级到最新版本(`2.6.0-beta.3`)老问题还存在，此外还多了一个新问题。

![image](https://user-images.githubusercontent.com/1589433/56708759-7f29c800-6750-11e9-8b1c-ff9a334942ef.png)

**Comment by IversonzZ** [comment]
> 遇到了同样的问题，在dva/lib/index.js 里头修改之后就没这个warning了

可以贴下具体的代码吗？

**Comment by Lxjazni7** [comment]
![image](https://user-images.githubusercontent.com/18001272/56859599-e00b0780-69bf-11e9-8c86-e768be482823.png)
直接修改不知道会不会有问题

**Comment by crazybear** [comment]
求正式版能发布一个小版本，这个警告看着太不舒服了

**Comment by hwendy** [comment]
有解决方案嘛 大佬

**Comment by sorrycc** [comment]
```
require("history").createHashHistory
```

或者

```
import { createHashHistory } from 'history';
```

**Comment by sorrycc** [comment]
@hwendy 升级到 beta 版本。

**Comment by alun-430** [comment]
> * dva@2.6.0-beta.1

这个版本可以解决router的warning，但是运行之后还会报错：
```
React: ReferenceError: regeneratorRuntime is not defined
```
解决办法是在入口文件 index.js 中
```
import @babel/polyfill
```
至于打包之后会有什么问题，现在是不可预见的

**Comment by running-snail-sfs** [comment]
这个问题解决一年了，太难了。。。。

**Comment by laosandegudai** [comment]
> 这个问题解决一年了，太难了。。。。

仍然在困难中进行。

**Comment by yaojin2070** [comment]
我服了

**Comment by alun-430** [comment]
没有去掉吗


 原始邮件 
发件人: yaojin<notifications@github.com>
收件人: dvajs/dva<dva@noreply.github.com>
抄送: Alun_sdz<960826725@qq.com>; Comment<comment@noreply.github.com>
发送时间: 2020年5月13日(周三) 22:29
主题: Re: [dvajs/dva] createHashHistory引用的warning，控制台有warning (#2039)


我服了

**Comment by Shijiuwei** [comment]
问题依旧

**Comment by sRect** [comment]
看着那个警告就难受，现在还有
