### ISSUE TITLE
打包异常

### ISSUE THREAD

**Issue by hezhii** [dvajs/dva#2040]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

导入 antd 的 message 组件，然后定义一个箭头函数，该函数接受一个 message 参数。在调用该函数时传入一个对象，打印对象和对象的一个属性。

```js
import {message} from 'antd'

class Text extends React.PureComponent {
  componentDidMount() {
    this.onMessage({ data: 'test' })
  }

  onMessage = (message) => {
    console.log(message)
    console.log(message.data)
    if (message.data === 'test') {
      console.log('success')
    }
    console.log(message)
  }

  ...
}
```
#### Expected behavior: (预期的正常效果)

对象的内容和属性都可以正常打印出来

#### Actual behavior: (实际效果)

对象可以正常打印，但是对象的属性缺失 undefined，打包后的代码和期望的不一样。

![result](https://user-images.githubusercontent.com/25079915/54731739-eb059780-4bca-11e9-8234-249df7470cc3.png)

![webpack](https://user-images.githubusercontent.com/25079915/54731766-14262800-4bcb-11e9-86f4-53ef8703b437.png)

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva: v2.1.0
antd: v3.8.2

**Comment by sorrycc** [comment]
和 dva 无关吧。

**Comment by hezhii** [comment]
我觉得这和 webpack 有关，于是我查找依赖找到了 `roadhog 2.0.0`->`af-webpack 0.13.7`->`webpack 3.5.6`，然后基于此版本的 webpack 写了个简单的例子尝试复现，但是没有成功。我不确定是我的例子没有真实还原还是其他依赖导致的问题，所以我才直接提了这个 issue。

**Comment by sorrycc** [comment]
我觉得和 webpack 也没有关系。

**Comment by hezhii** [comment]
基本上可以确定是 babel-plugin-import 插件的问题了，不使用插件按需加载就不会出现这样的问题。谢谢回复
