### ISSUE TITLE
mock功能是否存在缺陷？个人感觉十分鸡肋

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [dvajs/dva#2043]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
.roadhogrc.mock.js下配置代理服务器，然后我想mock掉其中一个接口
`export default {
	'POST /api/*' : 'http://192.168.0.88:8112',
  'GET /api/*' : 'http://192.168.0.88:8112',

	'POST /api/getMenu': (req, res) => {
    res.json({
      data: [{
        name: "demo",
        url: "/demo",
      }]
    })
  }, 
};`

#### Expected behavior: (预期的正常效果)
我的mock接口应该优先级最高，成功拦截并生效

#### Actual behavior: (实际效果)
没有生效，返回的还是线上代理的接口

#### Versions of packages used: (哪个库的哪个版本出现的问题)
roadhog是2.4.9，dva是2.4.1

**Comment by sorrycc** [comment]
代理用 proxy 配置，不要用 mock 。

**Comment by zjjjjjjjjjjd** [comment]
> 代理用 proxy 配置，不要用 mock 。

大佬意思是，不要使用roadhog的mock了吗？我发现如果是做了wepack的proxy，roadhog的mock也是无效的，除非全用webpack

**Comment by sorrycc** [comment]
proxy 和 mock 可以共用的，mock 不要用字符串（代理）的功能。

**Comment by zjjjjjjjjjjd** [comment]
> proxy 和 mock 可以共用的，mock 不要用字符串（代理）的功能。

emmm，我不知道是我哪里配置不对吗？
我在.webpackrc配置了proxy如下
`"proxy": {
        "/api/*": {
            "target": "http://192.168.0.88:8112",
            "changeOrigin": true
        }
    },`
在.roadhogrc.mock.js做了如下mock，发现还是使用的代理服务器的接口
`export default {
	'POST /api/getMenu': (req, res) => {
    res.json({
      data: [{
        name: "demo",
        url: "/demo",
      }]
  })
};`

**Comment by zjjjjjjjjjjd** [comment]
> proxy 和 mock 可以共用的，mock 不要用字符串（代理）的功能。

大佬，是否现在无法做到mock拦截的优先级高于proxy？

**Comment by zjjjjjjjjjjd** [comment]
> proxy 和 mock 可以共用的，mock 不要用字符串（代理）的功能。

找的问题所在了，原因出在roadhog的mock执行顺序在proxy之后，导致优先匹配到proxy且注册webpack-dev-server之后mock的调用失效，只需要调换一下执行顺序，已经提交了PR。另外在使用中发现proxy默认没有传changeOrigin导致会有跨域问题。
