### ISSUE TITLE
dynamic 模板与资源分离导致的问题

### ISSUE THREAD

**Issue by WinwardZ** [dvajs/dva#2048]
dva/dynamic 处理后的 组件动态加载   build 之后   分割成多个  async 脚本， 在服务器模板上  访问的时候 还是相对地址，能配置成 绝对路径么？（模板在java应用上，资源在资源服务器上）

#### Actual behavior: (实际效果)
实际效果 为  访问 相对路径，即为 /java模板的路径/1.async.js      404

#### Versions of packages used: (哪个库的哪个版本出现的问题)

可以配置打包路径么？或者针对这种情况 有什么 解决方案么？谢谢

**Comment by WinwardZ** [comment]
已经找到webpack相关配置解决方案，自己关闭。

**Comment by bonniePxx** [comment]
怎么解决的呀

**Comment by ThenMorning** [comment]
> 怎么解决的呀

https://segmentfault.com/a/1190000020739078
