### ISSUE TITLE
使用V2.4.1报出的警告

### ISSUE THREAD

**Issue by BETH-zhang** [dvajs/dva#2051]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
```
Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release
```

#### Expected behavior: (预期的正常效果)
不要有这样的警告出现，代码文件地址：dva/src/index.js  第三行：
```js
import createHashHistory from 'history/createHashHistory';
```

#### Versions of packages used: (哪个库的哪个版本出现的问题)

版本：V2.4.1

**Comment by BETH-zhang** [comment]
@sorrycc 大神，这是个小问题，就是控制台报warning警告，看着不舒服

**Comment by sorrycc** [comment]
重复问题了，在 #2039 统一跟进。
