### ISSUE TITLE
TS plugin onEffect 签名有问题

### ISSUE THREAD

**Issue by justnewbee** [dvajs/dva#2052]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

自己实现了 dva-loading plugin 相关逻辑

plugin 中的定义 onEffect 签名为

```
onEffect(effect: Function, {
  put
}: EffectsCommandMap, model: Model, actionType: string)
```

而 app.use 中要求的参数为 Hooks，它的 onEffect 定义为 `() => void`

这就导致 ts 报警说参数不兼容

#### Expected behavior: (预期的正常效果)

ts 不会报警

#### Actual behavior: (实际效果)

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/2276086/55374698-fdbd8c00-553b-11e9-8df1-b9d2e4abbd30.png">

#### Versions of packages used: (哪个库的哪个版本出现的问题)

2.5.0-beta.2

**Comment by justnewbee** [comment]
目前只能靠 as Hooks 绕过..

**Comment by SHITianhao** [comment]
```
import { EffectsCommandMap, Model, Hooks as DvaHooks } from 'dva'

type SagaWithCatch = (action: AnyAction) => Iterator<any>

// Need to omit onEffect from Dva definition
interface Hooks extends Pick<DvaHooks, Exclude<keyof DvaHooks, 'onEffect'>> {
  onEffect?: (effect: SagaWithCatch, command: EffectsCommandMap, model: Model, actionType: string)
    => (action: AnyAction) => Iterator<void>,
}
```
@justnewbee 可以参考这样自己定义

@sorrycc 能否更新ts定义？
