### ISSUE TITLE
跨iframe无法及时获取到更改后model中state数据

### ISSUE THREAD

**Issue by Petter-li** [dvajs/dva#2053]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
A组件上嵌套一个iframe，页面来自同级的B组件，路由配置为./B;在A组件中connect公共Model,
点击A组件上的元素，修改Model中数据，同时打开一个弹窗，内嵌iframeB，在B组件的render中去获取更改后的Model数据，获取的依然是没有更改的数据。

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"dva": "^2.5.0-beta.2",

**Comment by mode365Dong** [comment]
我也遇到了这个问题，我需要iframe页面中不要请求数据，直接使用modelstate的数据，因为我解决不了iframe重复请求接口的问题

**Comment by mode365Dong** [comment]
> 我也遇到了这个问题，我需要iframe页面中不要请求数据，直接使用modelstate的数据，因为我解决不了iframe重复请求接口的问题

我解决了这个问题。
父组件的dva加载完成后直接 调用iframe.window.methods （自定义的方法），传入model.state。
我们项目对dva分类比较详细，所以这里我直接传入当前分类的整个state。
iframe接收方法，直接setState，将信息同步。
完成~
