### ISSUE TITLE
How To Add Routing Transition Effect

### ISSUE THREAD

**Issue by gorvinsky** [dvajs/dva#2058]
Hi, I would like know if there is a way to add some native app like route transition effect by using animation libraries like react-transition-group or react-pose? Is there an example?

**Comment by sorrycc** [comment]
Please google [react-router+transition](https://www.google.com/search?q=react-router+transition&oq=react-router+transition&aqs=chrome..69i57j0l5.5862j0j7&sourceid=chrome&ie=UTF-8).

**Comment by gorvinsky** [comment]
> Please google [react-router+transition](https://www.google.com/search?q=react-router+transition&oq=react-router+transition&aqs=chrome..69i57j0l5.5862j0j7&sourceid=chrome&ie=UTF-8).

I have seen a few tutorials before coming to ask here. The thing is most of them made use of location.key which I'm not entirely sure where to get from dva/router.
