### ISSUE TITLE
引入dva-loading后，在componentDidMount中dispatch会造成componentDidMount不断调用导致死循环

### ISSUE THREAD

**Issue by forzalianjunting** [dvajs/dva#2062]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
引入dva-loading后，在componentDidMount中dispatch

#### Expected behavior: (预期的正常效果)
正常触发dispatch

#### Actual behavior: (实际效果)
componentDidMount会不断调用，导致死循环，移除dva-loading后又好了

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"dva": "^2.4.1",
"dva-loading": "^2.0.6",

**Comment by sorrycc** [comment]
可能原因是当前路由被销毁了，你也可以试试把初始 dispatch 逻辑移到 subscription 里处理。

**Comment by forzalianjunting** [comment]
@sorrycc 放入 subscription 中确实是可以的，只是不太明白这个路由销毁的问题，求指点

**Comment by sorrycc** [comment]
只是猜测，componentDidMount 理论上只会执行一次，只有销毁了重新创建才会多次执行，销毁的原因可能是 location 变化。

**Comment by forzalianjunting** [comment]
@sorrycc 疑似和这个 [bug](https://github.com/dvajs/dva/issues/1449) 有关系

**Comment by forzalianjunting** [comment]
@sorrycc 异步组件接受 dva 实例 app 作为参数，返回dynamic({...})，导致<Route component={Home(app)}  />的每次 Render 都会使 Home 重新mount
