### ISSUE TITLE
Take监听多个时，必须指定namespace，若指定同namespace action，则会显示警告

### ISSUE THREAD

**Issue by shengbeiniao** [dvajs/dva#2068]
## 最小可复现仓库
> 代码段如下
```
export default {
  namespace: 'user',

  state: _.cloneDeep(initState),

  subscriptions: {},

  effects: {
    *watch(_, { take, put }) {
      while (true) {
        const { type } = yield take([
          'system/setCurrent',
          'user/cancelWatch'
        ])
        if (type === 'user/cancelWatch') {
          break
        }
        yield put({
          type: 'clear'
        })
        yield put({
          type: 'query',
          payload: {
            query: defaultQuery
          }
        })
      }
    },
```

## 复现步骤，错误日志以及相关配置
其中user/cancelWatch会显示警告
index.js:1 Warning: [sagaEffects.take] user/cancelWatch should not be prefixed with namespace user

## 相关环境信息

- **Umi 版本**：2.x
- **Node 版本**：10.x
- **操作系统**：MAC OS

**Comment by shengbeiniao** [comment]
如果不指定namespace，则take监听失效

**Comment by sorrycc** [comment]
可能是 bug，有兴趣提 PR 修复吗？

**Comment by shengbeiniao** [comment]
> 可能是 bug，有兴趣提 PR 修复吗？

找了下bug触发的代码，见[prefixType文件](https://github.com/dvajs/dva/blob/99ec56cbedbdba7e3e91befe341f109e038363c6/packages/dva-core/src/prefixType.js#L6)
这里面有个判断model中含有指定的reducer或effect函数，才会加前缀

问题是上面的Demo代码，take multi中的cancelWatch只是一个信号量，用来终止while循环，不需要加额外的reducer处理函数，所以是否应该去掉这个判断，又或者可以变更警告的代码，参加[getSaga](https://github.com/dvajs/dva/blob/99ec56cbedbdba7e3e91befe341f109e038363c6/packages/dva-core/src/getSaga.js#L126)
