### ISSUE TITLE
arning: Please use `require("dva").router` instead of `require("dva/router")`. Support for the latter will be removed in the next major release.

### ISSUE THREAD

**Issue by majiang666** [dvajs/dva#2069]
![微信图片_20190412154644](https://user-images.githubusercontent.com/6973077/56020656-34fd1b80-5d3a-11e9-97cf-a5ea60de4334.png)
报错：
Warning: Please use `require("dva").router` instead of `require("dva/router")`. Support for the latter will be removed in the next major release.
Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.

package.json配置

{
  "private": true,
  "scripts": {
    "start": "roadhog server",
    "build": "roadhog build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "antd": "^3.16.2",
    "babel-plugin-import": "^1.11.0",
    "dva": "^2.6.0-beta.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "babel-plugin-dva-hmr": "^0.3.2",
    "eslint": "^4.14.0",
    "eslint-config-umi": "^0.1.1",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "husky": "^0.12.0",
    "redbox-react": "^1.4.3",
    "roadhog": "^2.5.0-beta.4"
  }
}

**Comment by sorrycc** [comment]
问题是啥？

**Comment by majiang666** [comment]
> 问题是啥？

就是一直抱错，也没啥影响的。
现在又有一问题，只要配置，就报错Uncaught ReferenceError: regeneratorRuntime is not defined，重新安装了了一下npm i --save-dev babel-plugin-transform-runtime还是不行。谢谢
`effects:{
        *asyncAdd(action,{ put,call }){       
            yield call(delay,1000);
            yield put({type:'jia'})
        }
    }`

**Comment by zhoumh1988** [comment]
？？？怎么解决的？完全没看懂～那里引入啊？

**Comment by majiang666** [comment]
> ？？？怎么解决的？完全没看懂～那里引入啊？

入口文件index.js

**Comment by andefine** [comment]
第一个报错我也遇到了，`dva` 版本 `2.6.0-beta.12`，这样可以避免报错：
```js
import { router } from 'dva'

const { Router, Switch, Route } = router
```

**Comment by WLyKan** [comment]
https://github.com/dvajs/dva/blob/fa5b8a4809d92466c8c2950d4235855830d37c1e/packages/dva/src/index.js#L146
`export { routerRedux };`

routerRedux 可以直接从dva导出了，dva的文档真的无力...
