### ISSUE TITLE
user-dashboard的几个功能是属于bug么？或者有好的解决方案么？

### ISSUE THREAD

**Issue by logyLiang** [dvajs/dva#207]
@sorrycc 云大大。 我是后台开发程序猿，基本上对前端只局限于使用和简单的改造，目前发现user-dashboard查询和分页这有点问题可能应用到实际项目中可能会很致命，也许是因为demo的原因吧，我想应用到实际项目当中，问问大大有没有好的解决方案，最好对小白来说通俗易懂的：
原有问题：
    输入查询条件后页面数据超过1页，点击分页时，查询条件参数丢失。（我查找华南的用户，查询后共13个，点击第二页时候，查询参数没有了）
解决方法：
    我在model内把所有查询参数都放在了state内，在触发onPageChange方法时候把查询参数硬塞进去，暂时解决了查询后点击分页查询信息丢失的问题：
现在疑虑：
    查询不触发路由跳转，参数不显示在url上面，这个是正常的，也安全。但是点击分页时候，触发的是路由跳转，所有参数都显示在url上面，不友好不安全不说，如果查询数据过多的话，超过url长度限制会崩溃掉的，如果还是namespame/method形式访问action，页面是不刷新的。
我是小白很尴尬，求大大解惑！``

**Comment by nikogu** [comment]
@logyLiang 你说的问题，刚我试了最新的 dva 的 user-dashboard demo 已经没有这个问题了

关于你的疑虑：
是否将查询参数放到url上取决于你自己，前端的路由跳转并不会刷新页面，所以你的参数什么的信息还在你的内存里面

**Comment by nikogu** [comment]
先关了，有问题再 reopen
