### ISSUE TITLE
类型“Readonly<{}> & Readonly<{ children?: ReactNode; }>”上不存在属性“login”。ts(2339)

### ISSUE THREAD

**Issue by dragooncjw** [dvajs/dva#2070]
我在使用ts+dva+umi的时候，vscode提示了这个错误，但是程序是能正常运行的，页面也能打印出props中的login属性的值，但是ts报错显示'this.props.login'属性不存在。
我是用脚手架搭建的应用，查了一下使用的依赖版本如下：
umi@2.6.12
typescript@3.3.3
tslint@5.15.0
希望大神能帮忙解惑

**Comment by sorrycc** [comment]
和 dva 无关，可能是 @types/react 更新引起的。

**Comment by dragooncjw** [comment]
已经解决了，是ts类型问题。写一个泛型就能解决了。麻烦大神了。

**Comment by c690554125** [comment]
> 已经解决了，是ts类型问题。写一个泛型就能解决了。麻烦大神了。

hi, how to solve this problem ?
