### ISSUE TITLE
跳转问题

### ISSUE THREAD

**Issue by pipijoe** [dvajs/dva#2072]
一个post请求成功之后，如何做成功跳转操作，或者失败的提示，跳转如何携带请求的返回内容。谢谢

**Comment by zhangxuanlin** [comment]
browserHistory.push()跳转，提示用message.error(),跳转携带参数可以在push里加
例如: browserHistory.push(pathname: '/routerName',state: { key: value })

**Comment by pipijoe** [comment]
是在effects里面做？还是reducers？
