### ISSUE TITLE
[Question]Function components cannot be given refs. Attempts to access this ref will fail

### ISSUE THREAD

**Issue by yoyo837** [dvajs/dva#2073]
2.6.0-beta.3 `connect`后有如下警告，不知道其他人是否有:

`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()`

**Comment by yoyo837** [comment]
是 class 组件。

**Comment by Renderz** [comment]
相同问题

**Comment by yoyo837** [comment]
@Renderz 你使用Antd吗？

**Comment by yoyo837** [comment]
https://github.com/react-component/form/issues/287

**Comment by Renderz** [comment]
> @Renderz 你使用Antd吗？

是的. 
Form里的组件如果是普通antd组件OK
如果在这个组件上connect一层就会报错.
