### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by awexianshen** [dvajs/dva#2076]
dva@2.6.0beta.3版本,在浏览器控制台要求routerRedux的导入方式从
import { routerRedux } from 'dva/router'
改为
const { routerRedux } = require('dva').router,
但是改成后面这种方式之后,使用routerRedux.push会报错
Error: TypeError: Cannot read property 'push' of undefined

**Comment by sorrycc** [comment]
试试这样？

```
import { routerRedux } from 'dva';

routerRedux.push
```

**Comment by awexianshen** [comment]
哦哦,是这样的,谢谢作者大佬

**Comment by warmhug** [comment]
> 试试这样？
> 
> ```
> import { routerRedux } from 'dva';
> 
> routerRedux.push
> ```

这样  `const { routerRedux } = router`  从 router 获取 routerRedux、有的地方可行，有的地方不行 是 undefined，是为什么？
