### ISSUE TITLE
effects中请求失败，再次请求loading不会为true。

### ISSUE THREAD

**Issue by Henri-Zhang** [dvajs/dva#2077]
## What happens?
需求是这样的，多次连续请求，取消掉上次请求，只保留最新的。但是请求被取消（或者其他原因失败）后，loading为false，再次请求不会变为true。
版本3.0.2

![image](https://user-images.githubusercontent.com/15962610/56486196-72676300-6509-11e9-9274-7d66d7718b03.png)

**Comment by dmwin72015** [comment]
me too!!
