### ISSUE TITLE
支持React.forwardRef

### ISSUE THREAD

**Issue by nelhu** [dvajs/dva#2079]
## What happens?

现阶段使用```import {connect} from 'dva';```此版本connect不支持React.forwardRef(),需要升级dva内置依赖react-redux至v5.1.0以上，issue：(https://github.com/reduxjs/react-redux/issues/914)。 否则会报如下错误
![image](https://user-images.githubusercontent.com/24311105/56674089-02650280-66ec-11e9-99c4-b68ff66923e6.png)

**Comment by sorrycc** [comment]
用 dva@next。
