### ISSUE TITLE
启动dva项目报错err with request :Error: socket hang up  /

### ISSUE THREAD

**Issue by sq892246139** [dvajs/dva#208]
git clone https://github.com/dvajs/dva-hackernews.git  
npm install
npm start
open http://localhost:8989
报错如下：
> @ start /dva-hackernews
> dora --plugins "proxy,webpack,webpack-hmr"

(node:59719) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8989
📦  515/515 build modules
webpack: bundle build is now finished.
err with request :Error: socket hang up  /
err with request :Error: socket hang up  /favicon.ico

请问这是什么问题

**Comment by sorrycc** [comment]
把 package.json 里的 `proxy` 删掉再 `npm start` 试试。

**Comment by sq892246139** [comment]
删掉proxy后再npm start ，控制台没有报错，但是
![image](https://cloud.githubusercontent.com/assets/17660679/19756416/0976efb2-9c4f-11e6-8bed-0fb1f70dbb83.png)

**Comment by sorrycc** [comment]
端口是 8000?

**Comment by sq892246139** [comment]
![image](https://cloud.githubusercontent.com/assets/17660679/19758127/3b7eb198-9c59-11e6-8626-a205fcfa3401.png)

**Comment by sorrycc** [comment]
命令行日志看下。

**Comment by sq892246139** [comment]
![image](https://cloud.githubusercontent.com/assets/17660679/19759296/eacf8d2a-9c5e-11e6-8f06-c334171fc7b0.png)
大神能建个QQ交流群吗

**Comment by sorrycc** [comment]
不清楚问题所在了，自己排查下吧，理论上打开 http://localhost:8000 是没问题的。

**Comment by fzypzl** [comment]
@sq892246139 不要用127.0.0.1，用localhost

**Comment by sq892246139** [comment]
Thank you!使用localhost后正常了！

**Comment by shengxuesun** [comment]
这个问题根源在哪，有大神知道吗
