### ISSUE TITLE
为什么是dva.router？dva.router中JSX.Element无法被IntlProvider包裹。

### ISSUE THREAD

**Issue by SixYearsInFebruary** [dvajs/dva#2080]
## What happens?

在`dva.router`中，我们通常会写几种不同的layout布局，举例来说，有个BasicLayout，这个layout内会呈现一些界面，由于国际化，我们通常会在BasicLayout内渲染page的component外包裹一层injectIntl。
但在react-intl@2.8.0版本中：`<IntlProvider> needs to exist in the component ancestry.`

用根组件挂载界面时，通常是`ReactDOM.render(<IntlProvider><App /></IntlProvider>, element);`这里的`<App />`就是`dva.start()`返回的组件。

那么问题是，`dva.router(....)`里的router其实并没有被包裹在`IntlProvider`内。最终会抛出`Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.`

[`react-intl`官方wiki](https://github.com/yahoo/react-intl/wiki#creating-an-i18n-context)对这里有说明，如下：
*All apps using React Intl must use the <IntlProvider> component.*

The most common usage is to wrap your root React component with <IntlProvider> and configure it with the user's current locale and the corresponding translated strings/messages:

```
ReactDOM.render(
    <IntlProvider
        locale={usersLocale}
        messages={translationsForUsersLocale}
    >
        <App/>
    </IntlProvider>,
    document.getElementById('container')
);
```

已确认dva@2.4.0与react-intl@2.4.0一起使用没有上述问题。

## 最小可复现仓库

非常抱歉，由于公司限制，我无法提供复现的仓库。后续如果有时间我会在家里提供复现仓库。

## 相关环境信息
windows 10
nodejs 10.8.0

@sorrycc

**Comment by SixYearsInFebruary** [comment]
下面是dva的源码。
```
// 路由必须提前注册
invariant(
  app._router,
  `[app.start] router must be registered before app.start()`,
);

```
所以，有什么解决办法吗？

**Comment by sorrycc** [comment]
这是常见场景，我觉得是你的使用问题，先提供可复现仓库吧。

**Comment by SixYearsInFebruary** [comment]
[contextType of injectIntl is overridden by child component contextType](https://github.com/yahoo/react-intl/issues/1269)
自己定位了下，最终确认应该是react-intl依赖的组件版本较低导致的。跟dva没关系。
非常抱歉。
