### ISSUE TITLE
dispatch 失效问题

### ISSUE THREAD

**Issue by superchow** [dvajs/dva#2081]
当 dispatch 后触发500后，返回原页面，该类型的 dispatch 就无法被触发了
```
 this.props.dispatch({
      type: 'libraryCategory/delCategory',
      payload: { categoryCode }
    });
```
比如，上面的那个方法，一旦服务器出错，原页面 就无法再次 dispatch 了，F5刷新页面后才能正确触发

请问，dva 是否有个内置机制标志了dispatch的type是不可用的？

如何解决不刷新就无法重新 dispatch 的问题?

**Comment by SixYearsInFebruary** [comment]
try {
  //  your dispatch
} catch (e) {
}

**Comment by superchow** [comment]
> try {
> // your dispatch
> } catch (e) {
> }

影响的不是外部的代码，而是 dispatch 本身

**Comment by sorrycc** [comment]
因为出错了，可以加 try catch，或者加全局的 onError 处理。

**Comment by superchow** [comment]
> 因为出错了，可以加 try catch，或者加全局的 onError 处理。

那为什么同组件内的其他 dispatch 依旧可以触发？

**Comment by sorrycc** [comment]
因为出错了。。

**Comment by jiamianmao** [comment]
你好，全局的onError处理异常怎么使用呢？return Promise.reject() 么？  这样重复点击依然不会触发dispatch

**Comment by superchow** [comment]
> 你好，全局的onError处理异常怎么使用呢？return Promise.reject() 么？ 这样重复点击依然不会触发dispatch

这个地址：https://dvajs.com/api/#app-use-hooks

**Comment by haoyinag** [comment]
@superchow @sorrycc 请问最终是怎样解决的，我用的是dva+ant，用trycatch和onError都无法再次触发

**Comment by haoyinag** [comment]
@superchow 请问这个问题要怎么解决

**Comment by superchow** [comment]
pro 里是在src下建一个app.js 文件
`import { message } from 'antd';
const app = dva({
  onError(e) {
    message.error(e.message, /* duration */3);
  },
});`

**Comment by jcai** [comment]
@superchow 您解决了吗？我用的umijs4，也出现这个问题了，只要effect中出现问题，整个dva的dispatch就失效了。
