### ISSUE TITLE
请问 PropTypes.array.isRequired 是干啥滴？

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#209]
`
ProductList.proptypes = {
  onDelete: PropTypes.func.isRequired,
  products: PropTypes.array.isRequired,
};`

请问以上代码中的 `products: PropTypes.array.isRequired,` 是啥意思？
有它没它有啥区别？

**Comment by sorrycc** [comment]
这属于 React 的知识范围了，请看 React 的官方文档。
http://react-new-docs-temporary-preview.surge.sh/react/docs/typechecking-with-proptypes.html
