### ISSUE TITLE
yield all中放put而出现的问题

### ISSUE THREAD

**Issue by TtTRz** [dvajs/dva#2094]
在effects中使用yield all时，数组里传入三个put如
![image](https://user-images.githubusercontent.com/32873545/57394799-01a69300-71f9-11e9-88d3-4a26591099da.png)
在页面中dispatch包含这个 all方法 的effects，在这个effects的then里面console一个字符串 这个字符串出现的位置在那四个put 的action的 start后 而不是在那三个put action最后执行的end的后面。

如果我单单的dispatch 那四个put 其中的一个action，在其then里面console一个字符串，这个字符串会在这个action的end后出现。

是不是使用all 会使得这个effect在执行完all中的put后马上就触发then而不是等待这三个put中的异步执行完。

**Comment by objectisundefined** [comment]
将 `put` 替换成 `put.resolve`
put 不会等待 相应的 effect 执行结束

docs:
https://redux-saga.js.org/docs/advanced/RunningTasksInParallel.html
https://redux-saga.js.org/docs/api/
