### ISSUE TITLE
effect yield中如何优雅的进行异常捕获

### ISSUE THREAD

**Issue by Symous** [dvajs/dva#2097]
## What happens?

在effect中，我们使用yield发起请求，如下:
```js
effect: {
  *fetch({payload},{call, put}) {
     const res = yield call(callSomeService, payload);
     //TODO...
 }
}
```
设想，如果callSomeService请求过程中产生了异常并进行了抛出，我们想要在这里进行捕获，并做一些后续操作，除了try catch还有什么更好的方法呢？

## 相关环境信息

- **Umi 版本**：2.3.0
- **Node 版本**：10.13.0
- **操作系统**：Windows 10 64bit

**Comment by LukerSpringtree** [comment]
我的项目中 我是在 
fetch 里面做了 统一处理.
把所有的 报错和错误都在 fetch 里面处理掉了 

我觉得 比写在 effect 里面要简洁和高效很多

**Comment by Symous** [comment]
@LukerSpringtree  这样还是有些不足的，比如在特定的页面中我们要针对每一个异常做一些特殊的操作或提示。

**Comment by Myh-cs** [comment]
@Symous 统一处理  处理函数可以适当加工比如 导入一个**错误码：处理函数** 表（如果类别大的话多个也不是不可以） 然后当发生错误的时候优先去匹配错误码，做处理，当不批配时才进行统一的报错处理。

如果需要在特定页面结合当时的数据进行处理，我们可以在相应错误码的处理函数中将错误继续抛出，方便在调用的地方捕获错误

**Comment by Symous** [comment]
@Myh-cs 是的，实际上这也是我之前的做法。发起这个issue的本意是想看看在effect中有没有除了try...catch意外的其他的解决方案。

**Comment by Myh-cs** [comment]
@Symous dva的effect处理用的是redux-saga 在它的错误处理部分的文档结尾找到这么一段 
[redux-saga 错误处理(中文)](https://redux-saga-in-chinese.js.org/docs/basics/ErrorHandling.html)
[redux-saga 错误处理(英文)](https://redux-saga.js.org/docs/basics/ErrorHandling.html)
> 当然了，你并不一定得在 try/catch 区块中处理错误，你也可以让你的 API 服务返回一个正常的含有错误标识的值。例如， 你可以捕捉 Promise 的拒绝操作，并将它们映射到一个错误字段对象。
```js
import Api from './path/to/api'
import { call, put } from 'redux-saga/effects'

function fetchProductsApi() {
  return Api.fetch('/products')
    .then(response => ({ response }))
    .catch(error => ({ error }))
}

function* fetchProducts() {
  const { response, error } = yield call(fetchProductsApi)
  if (response)
    yield put({ type: 'PRODUCTS_RECEIVED', products: response })
  else
    yield put({ type: 'PRODUCTS_REQUEST_FAILED', error })
}
```

**Comment by LukerSpringtree** [comment]
> @Symous dva的effect处理用的是redux-saga 在它的错误处理部分的文档结尾找到这么一段
> [redux-saga 错误处理(中文)](https://redux-saga-in-chinese.js.org/docs/basics/ErrorHandling.html)
> [redux-saga 错误处理(英文)](https://redux-saga.js.org/docs/basics/ErrorHandling.html)
> 
> > 当然了，你并不一定得在 try/catch 区块中处理错误，你也可以让你的 API 服务返回一个正常的含有错误标识的值。例如， 你可以捕捉 Promise 的拒绝操作，并将它们映射到一个错误字段对象。
> 
> ```js
> import Api from './path/to/api'
> import { call, put } from 'redux-saga/effects'
> 
> function fetchProductsApi() {
>   return Api.fetch('/products')
>     .then(response => ({ response }))
>     .catch(error => ({ error }))
> }
> 
> function* fetchProducts() {
>   const { response, error } = yield call(fetchProductsApi)
>   if (response)
>     yield put({ type: 'PRODUCTS_RECEIVED', products: response })
>   else
>     yield put({ type: 'PRODUCTS_REQUEST_FAILED', error })
> }
> ```

就是在 fetch 里面做了统一处理啊 哈哈哈.
