### ISSUE TITLE
webpack 配置问题

### ISSUE THREAD

**Issue by Restry** [dvajs/dva#210]

**Comment by Restry** [comment]
dva是不是把webpack包装了一层，那之前的webpack打包的项目直接接着这种方式迁移过来还是有什么好办法？？    比如分块文件 、入口文件（这个在dva的webpack也没有了）

**Comment by sorrycc** [comment]
分块文件指的啥? 入口文件可以在 `webpack.config.js` 里配的，比如：

```js
...
webpackConfig.entry = { ... };
```

**Comment by Restry** [comment]
不好意思，没有组织好语言。我主要是在用docker的时候有以下几个问题：

1. 因为hot reload的问题，之前我是用webpack-dev-server 可以设置watchOptions.poll:true解决，但是在这里我就不明白怎么弄了。
2. dva init的时候默认的webpack.config.js里面有一段：
    `
  // Don't extract common.js and common.css
  webpackConfig.plugins = webpackConfig.plugins.filter(function(plugin) {
    return !(plugin instanceof webpack.optimize.CommonsChunkPlugin);
  });`
我想知道这里是不是想表达不要使用CommonsChunkPlugin这个插件

所以通常生成出来的js都是上10MB了，我就是想知道怎么解决这个问题，如何像用webpack一样生成多个js。并用生成一个HTML入口页面。

3.类似html-webpack-plugin的插件能不能用。

**Comment by Restry** [comment]
再问一个有没有像Webapck-dev-server那样可以指定一个
` devServer: {
    contentBase: './src',
    hot: true,
    inline: true,
    host: '0.0.0.0',
    port: 3000,
    watchOptions: {
      poll: true
    },
    proxy: {
      '/sopsapi/api/*': {
        target: 'http://127.0.0.1:9999',
        secure: false
      }
    }
  },`

配置的地方

**Comment by sorrycc** [comment]
抱歉，漏掉这个 issue 了。。

首先，你可以换用 webpack-dev-server，实际上 dva-cli 的下个版本也会考虑用 webpack-dev-server，现在的 proxy 方案问题比较多。

1. watchOptions 的配置都在 dora-plugin-webpack 中，比如：`$ dora --plugins webpack?{"watchOptions":{"poll":true}}`，详见：https://github.com/dora-js/dora-plugin-webpack#options
1. 你理解的没错，是禁用 `CommonChunkPlugin` 的意思。10M 感觉有点太大了，可以用 webpack-visualizer-plugin 分析下构成（另外不要用 npm2，npm2 下可能会有重复依赖)
1. webpack 插件在 `webpack.config.js` 中加上就好了，`webpackConfig.plugins.push(...)`

**Comment by Restry** [comment]
谢谢你的回答，很好的解决了大问题
