### ISSUE TITLE
是不是应该把组件内的state都放到 model里面

### ISSUE THREAD

**Issue by 569202812** [dvajs/dva#2103]
比如: 

- 我有一个取到数据`{a: '1', b:[{}, {}]}` ,更新model里面的state,渲染到页面 **b**为**可配置项(字体之类)**

- 我点击**b**的时候他的### 配置项应该对应成他的**样式** (这里是应该点击调用dispatch暂存这一项,然后更新view)

-  我在更改**b**的配置项(根据暂存的id dipatch 修改数据 但是是暂存的应该先更新暂存的,在更新最一开始一开始存储的才能对应)

- 这样要是一直用model 的数据是不是过于繁琐(求大佬给些思路)

**Comment by majiang666** [comment]
个人觉得，需要组件之间共享的state放到model，其他的state还是放组件内。

**Comment by 569202812** [comment]
> 个人觉得，需要组件之间共享的状态放到模型，其他的国家还是放组件内。

我也是这样认为的
