### ISSUE TITLE
官方网站首页 404 无法浏览

### ISSUE THREAD

**Issue by zxhycxq** [dvajs/dva#2104]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，选择 `app`，然后选上 `dva`，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：window 

如下图所示

![image](https://user-images.githubusercontent.com/11674203/57983039-c0777400-7a7f-11e9-94cc-61f916b4f8c7.png)

**Comment by StrangeClow** [comment]
同楼上

**Comment by okfantasy007** [comment]
网站无法访问

**Comment by lx2328** [comment]
+1

**Comment by feleventh** [comment]
同楼上,404,   这个库是不打算维护了吗

**Comment by papibabi** [comment]
???dva 也不搞了？

**Comment by wuhao5436** [comment]
dva 官网挂掉了

**Comment by UlyC** [comment]
> 同楼上,404, 这个库是不打算维护了吗

不会吧, umi不也依赖的dva嘛..

**Comment by xulei9507** [comment]
是不维护了么

**Comment by fukai007** [comment]
我擦 还不能访问

**Comment by feleventh** [comment]
> > 同楼上,404, 这个库是不打算维护了吗
> 
> 不会吧, umi不也依赖的dva嘛..

umi不依赖dva吧，只是推荐用dva

**Comment by wangyichen1064431086** [comment]
同……请问是啥情况

**Comment by xulei9507** [comment]
大佬说在看了 大概下午能恢复

**Comment by EryouHao** [comment]
已经恢复
