### ISSUE TITLE
[RFC] 希望可以加一个配置开关来取消某些警告

### ISSUE THREAD

**Issue by DiamondYuan** [dvajs/dva#2111]
## 背景

用了 dva-model-creator 或者 typescript-fsa 时，所有 action 都带有namespace

## 思路

增加一个配置开关

![image](https://user-images.githubusercontent.com/9692408/58447923-a7825900-8138-11e9-8148-8785e79ef31f.png)

**Comment by sorrycc** [comment]
增加一个配置项吧，`namespacePrefixWarning: false` 时不给 warning。

**Comment by DiamondYuan** [comment]
感觉改动有点大，工具函数访问全局配置有些困难。

**Comment by DiamondYuan** [comment]
> namespacePrefixWarning

看了一下，如果要读取配置的话，需要一层层传递下去。

**Comment by justable** [comment]
TypeScript中DvaOption的namespacePrefixWarning别必填呀，不可以选填给个默认值吗，本来编译通过的代码都不能通过了

**Comment by DiamondYuan** [comment]
> TypeScript中DvaOption的namespacePrefixWarning别必填呀，不可以选填给个默认值吗，本来编译通过的代码都不能通过了

不好意思，是我的失误，我现在提交 pr。

**Comment by DiamondYuan** [comment]
> TypeScript中DvaOption的namespacePrefixWarning别必填呀，不可以选填给个默认值吗，本来编译通过的代码都不能通过了

不好意思，安装最新代码就可以了。
