### ISSUE TITLE
[Feature Request] 允许自定义 REDUX DEVTOOLS 的参数

### ISSUE THREAD

**Issue by freeznet** [dvajs/dva#2119]
## Background

当前 Dva 在 createStore 的阶段调用了 redux devtools 的 Enhancer 来实现历史显示的功能，https://github.com/dvajs/dva/blob/3f1f90e2042adeb3cc2f1c709f5a254df6a0656f/packages/dva-core/src/createStore.js#L31
但是这样做以后无法支持用户自定义其他的参数 ref ( https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md )

由于我们的项目中会存储稍微大量的数据在state中，此时会出现使用 devtools 占用过多内存的问题，ref( https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Troubleshooting.md#excessive-use-of-memory-and-cpu )，但当前dva中无法自定义actionSanitizer和stateSanitizer。

如果尝试在项目中新增一个 devtools 的 包含 actionSanitizer 和 stateSanitizer 的 Enhancer，则会触发 devtools 的错误 

> Error: DevTools instrumentation should not be applied more than once. Check your store configuration.

## Proposal
 
允许用户自行配置 REDUX DEVTOOLS 的参数

**Comment by yoyo837** [comment]
直接发PR 吧
