### ISSUE TITLE
dva结合nextjs，store注入的问题

### ISSUE THREAD

**Issue by montilloo** [dvajs/dva#2124]
## What happens?
看官方的示例，是在pages/index.js文件中用WithDva装饰了组件，那么pages/下面的其他文件也是同样的方式来装饰下组件吗？

## How To Reproduce
**Steps to reproduce the behavior:**
无

**Expected behavior**
1.可否在pages/_app.js文件中注入store？如果可以的话有个example给看下吗？感谢

## Context

- **Dva Version**:"dva-no-router": "^1.2.1",
- **Node Version**:10.15.3
- **Platform**:macOS 10.14.5

**Comment by smithyj** [comment]
https://github.com/smithyj/nextjs-dva-ssr

**Comment by Nick930826** [comment]
> https://github.com/smithyj/nextjs-dva-ssr

官方提供的store.js引入_app.js有问题，还是这个回答给力

**Comment by chaserstrong** [comment]
> https://github.com/smithyj/nextjs-dva-ssr

页面404了。。。

**Comment by smithyj** [comment]
> > https://github.com/smithyj/nextjs-dva-ssr
> 
> 页面404了。。。

@chaserstrong 可以考虑更换方案
