### ISSUE TITLE
[Feature Request] 将Effect等相关类加入泛型定义

### ISSUE THREAD

**Issue by xiaopanghhh** [dvajs/dva#2125]
## Background
在基于 ANTD PRO 4 开发的时候，采用了 TypeScript 在用于 DVA 的时候，将 status 独立写义了类型。
如果  Effect 能像  如redux 当中的 Reducer 一样的话。
开发的时候，就不需要 
```
export type Effect = (
  action: AnyAction,
  effects: EffectsCommandMap & { select: <T>(func: (state: {}) => T) => T },
) => void;

```
像这样，重新定义  Effect 了。

**Comment by tangye1234** [comment]
开发 Antd Pro 4，着实烦啊，各种ts定义不全，包括 put.resolve 也是没有定义的。
