### ISSUE TITLE
请问一个antd使用时props传数组和用数组的问题

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#213]
我用了antd的导航菜单组件 Menu，
想通过路由组件传值的方式让当前被访问的菜单点亮。

**我在父组件写法如下**
`<Header selectedKeys={['3']}/>`

**子组件没问题的写法如下：**
`<Menu selectedKeys={['3']}>`

**子组件出问题的写法如下：**
`<Menu selectedKeys={this.props.selectedKeys}>`

antd官方[Menu 组件](https://ant.design/components/menu/) API 要求 selectedKeys 值为数组，我想我传的也是数组类型啊，为啥没有效果呢？

**Comment by junmaqiang** [comment]
这个问题我自行解决了，这里分享下
`<Menu selectedKeys={props.selectedKeys}>`
去掉this就可以了。

**Comment by lincenying** [comment]
继承写法才需要this, 函数式没有this.props这东西
