### ISSUE TITLE
dva2.6以上版本使用router进行页面跳转时history.listen陷入死循环

### ISSUE THREAD

**Issue by Moicen** [dvajs/dva#2130]
## What happens?

在用户登录之后，希望直接跳转到指定页面，而不是默认的首页。实现方式是在全局model中监听路由变化，然后重新跳转页面。代码如下

```javascript
import router from 'umi/router';
import cookie from '@/utils/cookie'
const TokenKey =  'UMI_TEST_TOKEN'

export default {

  namespace: 'global',

  state: {},

  subscriptions: {
    setup({ dispatch, history }) {
      return history.listen(({ pathname }) => {
        let logged = cookie.get(TokenKey);
        console.log(pathname, logged);
        if (!logged) {
          if (pathname !== '/login') {
            router.replace('/login');
          }
        } else {
          if (pathname === '/login' || pathname === '/') {
            router.replace('/profile');
          }
        }
      });
    },
  },

  effects: {
    * login({ payload }, { call, put }) {
      cookie.set(TokenKey, 1);
      // window.location.href = '/'
      router.replace('/');
    },

    * logout({ payload }, { call, put }) {
      cookie.remove(TokenKey);
      // window.location.href = '/login'
      router.replace('/login');
    },

  },


  reducers: {
    save(state, action) {
      return { ...state, ...action.payload };
    },
  },

};

```
问题是在`login`方法里使用`router.push`或者`router.replace`跳转到首页，就会陷入死循环，路由不断在'/profile'和'/'之间变化，最终导致内存溢出或抛出'Maximum call stack size exceeded'错误。而如果使用`window.location.href = '/'`的方式跳转，则不会出现问题。执行`logout`时有概率正常，但多数情况也会出现同样的问题。

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

git@github.com:Moicen/umi-router-issue.git

## 复现步骤，错误日志以及相关配置

1. 下载项目，安装package，并运行`npm start`启动
2. 在浏览器查看http://localhost:8000，打开开发者工具。点击 login按钮
### 期待结果
页面立即跳转到/proife页
### 实际结果
实际页面卡住，过一会儿后会跳转到/profie页，查看开发者工具的控制台，不断输出'/`和'/profile'两个pathname

## 相关环境信息

- **Dva 版本**：^2.6.0-beta-4
- **Node 版本**：v10.14.1
- **操作系统**：mac OSX 10.14.5

**Comment by sorrycc** [comment]
这是实现的逻辑问题吧，location.href 不出现问题是因为不会触发 history 的 listen 事件。

**Comment by Moicen** [comment]
> 这是实现的逻辑问题吧，location.href 不出现问题是因为不会触发 history 的 listen 事件。

这个实现逻辑上没问题吧 ，如果使用2.5.* 版本的dva就完全正常工作。

另外试了下使用`dispatch(router.push('/'))`或者`yield  put(router.push('/'))`，不会出现这个死循环的错误，但是会报另外一个"Cannot read property 'type' of undefined"的错误，按dva的介绍，应该是可以直接使用 `dispatch(router.push('/'))`这样的，这是umi里的router做了额外处理？

**Comment by neighbourwang** [comment]
same question

**Comment by wiziple** [comment]
i have a same issue

**Comment by LukerSpringtree** [comment]
看来大佬正在写 dva 3.0

**Comment by sdcnljg** [comment]
大佬们怎么解决的这个问题？

**Comment by Dongfengjie** [comment]
我也有这个问题

**Comment by lx70770** [comment]
希望优先解决这个bug

**Comment by lilifan** [comment]
@sorrycc 云大还没修复计划么....我也遇到这问题了

**Comment by qq645381995** [comment]
赞，可算解决了，当时遇到死循环，是改了代码逻辑才好了，但是总觉得不顺。
