### ISSUE TITLE
react-redux@5.0.7能否升级到6版本以上

### ISSUE THREAD

**Issue by LiYanGang** [dvajs/dva#2131]
需要用到connect函数中的第四个参数中forwardRef，但是该api要求6版本以上
![屏幕快照 2019-06-17 下午2 45 07](https://user-images.githubusercontent.com/20022163/59583747-c90aab00-910e-11e9-8de8-1f9252c2d880.png)

**Comment by wangxingkang** [comment]
最新版本已更新到7.1.0

**Comment by wangxingkang** [comment]
可以问下 啥时候可以发布正式版

**Comment by cike8899** [comment]
同问，什么时候发正式版？

**Comment by sorrycc** [comment]
暂不发正式版，先用 beta 吧，有 break change。

**Comment by 662** [comment]
时间又过去了一个月，问问什么时候发布正式版

**Comment by aidenwei** [comment]
请求什么时候发布正式版啊，期待
