### ISSUE TITLE
请使用 react-redux 提供的 typings 信息

### ISSUE THREAD

**Issue by meowtec** [dvajs/dva#2133]
dva 虽然内置了 connect 的类型签名，但是阉割了太多东西，基本上相当于 any 了。
而 react-redux 的类型是很有用处的，能保证 `mapStateToProps` `ownProps` 等数据的类型的正确性，dva 里面的阉割版本就完全做不到。

**Comment by sorrycc** [comment]
有兴趣提个 PR ？

**Comment by meowtec** [comment]
周末看一下

**Comment by Ryuurock** [comment]
周末结束了
