### ISSUE TITLE
文档改更新了！

### ISSUE THREAD

**Issue by DanielWLam** [dvajs/dva#2134]
文档目前明显滞后，按照快速上手进行操作，很多不同步的地方，包括umi，使用antd的webpack.rc等等

**Comment by 1232209** [comment]
确实该更新了，今天细致的读了一遍Dva的快速上手文档，然后想做一个例子，文档和代码不一致。

**Comment by 159965658** [comment]
按着文档操作，按需加载路由页面，出现了错误。

**Comment by jsonshao** [comment]
这里是不是没人维护了啊

**Comment by peakandyuri** [comment]
确实是，最新版本的dva已经使用原生redux的connect了，官网示例还是以前的方式
