### ISSUE TITLE
subscriptions 未订阅

### ISSUE THREAD

**Issue by lifegit** [dvajs/dva#2138]
![image](https://user-images.githubusercontent.com/33006878/60083746-dd7f2100-9768-11e9-87cb-b0cfd61727a2.png)

subscriptions 的 setup 未运行。

package.json:
...
  "devDependencies": {
  ...,
    "umi": "^2.6.16",
    "umi-plugin-react": "^1.7.5"
  },
...

**Comment by RGXMG** [comment]
我遇到了同样的问题，请问你解决了吗？
