### ISSUE TITLE
很想知道这里的参数是什么作用

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#214]
我在 [decs](https://github.com/dvajs/dva-docs/blob/master/v1/zh-cn/tutorial/06-添加Reducers.md) 下的 关联模型 下面看到如下代码：

`function Users({ location, dispatch, users }) {

  const {
    loading, list, total, current,
    currentItem, modalVisible, modalType
    } = users;`

请问  `location, dispatch, users `  这三个参数是几个意思

**Comment by codering** [comment]
同学多看看react基础知识吧。。。。
这里有常见用法，https://github.com/dvajs/dva-knowledgemap

**Comment by afc163** [comment]
源码在这里：https://github.com/dvajs/dva/tree/master/examples/user-dashboard

建议自行研究。

另外，不要重复提 issue。

**Comment by junmaqiang** [comment]
代码已经翻了几遍也没发现 location 是哪里冒出来滴。

**Comment by lincenying** [comment]
这是react的路由相关数据
function Users(props) {
  const { location, dispatch, users } = props
}
