### ISSUE TITLE
webpack 编译错误

### ISSUE THREAD

**Issue by Tomny2016** [dvajs/dva#2141]
## What happens?
yarn start 的时候，谷歌浏览器报一下错误
```
index.js:1375 Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.
```

同样的问题，出现在`dva/fetch`，`dva/router`，`dva/dynamic`，等

## 相关环境信息

- **Umi 2.8.5**：
- **Node 10.16.0**：
- **windows**：

**Comment by sorrycc** [comment]
# require('dva/xxx') 报 Warning 怎么处理？

## 错误示例

比如：

```bash
Warning: Please use require("dva").routerinstead ofrequire("dva/router"). Support for the latter will be removed in the next major release.
```

```bash
Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.
```

## 原因

dva@2.6 beta 全部走 esm，然后项目中开 tree-shaking 把没用到的功能摇掉，推荐用 `require('dva')`，而不是 `require('dva/router')`，所以给了警告。

## 解决

修改代码，比如：

```diff
- import { Link, Switch } from 'dva/router';
+ import { router } from 'dva';
+ const { Link, Switch } = router;
```

```diff
- import dynamic from 'dva/dynamic';
+ import { dynamic } from 'dva';
```

有个特殊的是 routerRedux，直接从 dva 下取就好了，

```diff
- import { routerRedux } from 'dva/router';
+ import { routerRedux } from 'dva';
```

## 参考

* [https://github.com/dvajs/dva/issues/2141](https://github.com/dvajs/dva/issues/2141)
* [https://github.com/dvajs/dva/issues/2112](https://github.com/dvajs/dva/issues/2112)
* [https://github.com/dvajs/dva/issues/2039](https://github.com/dvajs/dva/issues/2039)
* [https://github.com/umijs/umi/issues/2373](https://github.com/umijs/umi/issues/2373)

**Comment by zhaozilong123** [comment]
import { router } from 'dva';
这个router是undefined 
dva版本：2.4.1

**Comment by Lpbzzz** [comment]
> import { router } from 'dva';
> 这个router是undefined
> dva版本：2.4.1

兄弟咋样了啊，我也遇到了
