### ISSUE TITLE
引入dva，出现警告

### ISSUE THREAD

**Issue by Tomny2016** [dvajs/dva#2143]
## What happens?
仅仅在项目中引入dva就出现，如下警告
```
 Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.
```

仓库地址
https://github.com/Tomny2016/react-dva-antd-project/blob/master/src/index.js

项目代码
```
import React from 'react';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

import dva from 'dva';
// 创建应用

const app = dva()
// 注册视图
app.router (() => <App />);
// 启动应用
app.start ('#root');

serviceWorker.unregister ();

```

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Dva Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
# require('dva/xxx') 报 Warning 怎么处理？

## 错误示例

比如：

```bash
Warning: Please use require("dva").routerinstead ofrequire("dva/router"). Support for the latter will be removed in the next major release.
```

```bash
Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.
```

## 原因

dva@2.6 beta 全部走 esm，然后项目中开 tree-shaking 把没用到的功能摇掉，推荐用 `require('dva')`，而不是 `require('dva/router')`，所以给了警告。

## 解决

修改代码，比如：

```diff
- import { Link, Switch } from 'dva/router';
+ import { router } from 'dva';
+ const { Link, Switch } = router;
```

```diff
- import dynamic from 'dva/dynamic';
+ import { dynamic } from 'dva';
```

有个特殊的是 routerRedux，直接从 dva 下取就好了，

```diff
- import { routerRedux } from 'dva/router';
+ import { routerRedux } from 'dva';
```

history 的同理，你应该会解决的。

## 参考

* [https://github.com/dvajs/dva/issues/2141](https://github.com/dvajs/dva/issues/2141)
* [https://github.com/dvajs/dva/issues/2112](https://github.com/dvajs/dva/issues/2112)
* [https://github.com/dvajs/dva/issues/2039](https://github.com/dvajs/dva/issues/2039)
* [https://github.com/umijs/umi/issues/2373](https://github.com/umijs/umi/issues/2373)

**Comment by chenyulun** [comment]
你这修复的是bate的版本，2.4.1不打算修复了吗？
