### ISSUE TITLE
webpackrc文件配置环境变量启动后会报错

### ISSUE THREAD

**Issue by xiuxiumomo** [dvajs/dva#2144]
## What happens?
在配置文件中想根据环境变量来配置baseUrl的信息，webpackrc文件配置如下
` "extraBabelPlugins": [
            ["import", { "libraryName": "antd", "style": true }]
    ],
    "disableCSSModules": true,
    "define": {
        "process.env": {
            "NODE_ENV": process.env.NODE_ENV,
            "API_ENV": process.env.API_ENV
        }
    },
    "env": {
        "development": {
            extraBabelPlugins: ['dva-hmr'],
        }
    }`
在package.json中
`"scripts": {
        "start": "cross-env API_ENV=dev roadhog server",
        "build": "cross-env API_ENV=prod roadhog build",
        "lint": "eslint --ext .js src test",
        "precommit": "npm run lint"
    }
`
npm run start 时候出现**Unexpected token p in JSON at position 197**，应该是getUserConfig文件出错了。

## Context

- **Dva Version**: 2.4.1
- **Node Version**:10.15.1
- **Platform**:window10

**Comment by thomb** [comment]
Assuming that you have posted the entirety of yr `webpackrc` above, it is malformed... hence the error.

Trying running a json linting tool on both of the files
