### ISSUE TITLE
antd-admin，点击Dashboard菜单 或 Posts菜单 会发起多次请求，貌似和dva有关

### ISSUE THREAD

**Issue by ybning** [dvajs/dva#2145]
#### 重现步骤：
点击user菜单，再点击Dashboard菜单 或 Posts菜单，同一接口会触发2次请求，貌似和dva有关

follow：
https://github.com/zuiidea/antd-admin/issues/988#issuecomment-506940957
https://github.com/zuiidea/antd-admin/issues/988#issuecomment-506968216

![image](https://user-images.githubusercontent.com/3725612/60391626-572a5c80-9b25-11e9-8a1c-0647eb6f6d36.png)

**Comment by superlbr** [comment]
dva fallback to 2.4.1 is fine.
