### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by lameone1** [dvajs/dva#2148]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi`, select `app`, choose `dva`, then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.安装dva
2. dva new dva-quickstart
**Expected behavior**
1../src/index.js
Module build failed: Error: Cannot find module 'F:\dva-quickstart\node_modules\eslint\lib\api.js/package.json'

## Context

- **Dva Version**:2.41.1
- **Node Version**:v10.15.3
- **Platform**:win 64

**Comment by thomb** [comment]
Might be a dumb question, but have you run `npm install` (or whatever package manager you use)

**Comment by lameone1** [comment]
> Might be a dumb question, but have you run `npm install` (or whatever package manager you use)

i removed the node_moudules and redo...can't resolve
