### ISSUE TITLE
自定义webapck配置如何做到按需加载？

### ISSUE THREAD

**Issue by 404cat** [dvajs/dva#2149]
## 自定义webapck配置如何做到按需加载？

路由使用的是dva@2版本的 dva/dynamic，在webpack进行打包的时候只会生成一个index.js文件，做不到按路由来切割代码。

路由表配置 /utils/routesTree.js：
![image](https://user-images.githubusercontent.com/34706182/60692000-1e63fc00-9f06-11e9-90c6-e9e0a28fdea3.png)

路由路口  ruote.js ：

```js
import React from 'react'
import PropTypes from 'prop-types'
import { Route, routerRedux, Switch } from 'dva/router'
import dynamic from 'dva/dynamic'
import App from './routes/App/index'
import { routes } from './utils/routesTree'

const { ConnectedRouter } = routerRedux

function Routers({ history, app }) {
  const error = dynamic({
    app,
    component: () => import('./routes/error'),
  })

  return (
    <ConnectedRouter history={history}>
      <App>
        <Switch>
          {routes.map(({ path, ...dynamics }) => (
            <Route exact key={path} path={path} component={dynamic({ app, ...dynamics })} />//...dynamics解构出来的未 component 和 model
          ))}
          <Route component={error} />
        </Switch>
      </App>
    </ConnectedRouter>
  )
}

Routers.propTypes = {
  history: PropTypes.object.isRequired,
  app: PropTypes.object.isRequired,
}

export default Routers
```

现在打包出来的结果:
![image](https://user-images.githubusercontent.com/34706182/60692074-7b5fb200-9f06-11e9-8a56-03c96ced9dc9.png)

期望：
希望打包出来后能像roadhog一样得到多个chunk文件
![image](https://user-images.githubusercontent.com/34706182/60692060-6aaf3c00-9f06-11e9-97bc-a37b8144efc7.png)

- **Dva Version**:"^2.0.1",
- **Node Version**:v10.15.3
- **Platform**: windows

谢谢！

**Comment by wanliyunyan** [comment]
https://github.com/wanliyunyan/dva-typescript-antd-starter-kit 不知道会不会对你有帮助

**Comment by 404cat** [comment]
> https://github.com/wanliyunyan/dva-typescript-antd-starter-kit 不知道会不会对你有帮助

halo，谢谢您的回复，但是链接项目看了一遍并没有发现那里做了路由按需打包呢。
