### ISSUE TITLE
componentWillReceiveProps  如何再无状态组件下工作？

### ISSUE THREAD

**Issue by nianhua110** [dvajs/dva#215]
antd里有些控件是函数形式调用的，如message， message.error()。
这些不能放到无状态组件的return里面。
场景： 当网页打开时候，订阅事件得到网页id，通过effects，去请求后台数据，如果得不到数据，就触发个reducer， 这个reducers 来修改state里面的一个变量表示没有收到数据。那么stateless component 如何调用messge.error()来提示用户没有收到数据呢。
在class组件模式下，可以在componentWillReceiveProps里面实现message.error()的调用，stateless componet如何实现呢？

**Comment by codering** [comment]
要用生命周期函数，就不要使用组件函数组件.

dva没要求一定要使用纯函数组件。
