### ISSUE TITLE
dva/dynamic 打包后仍然只有一个index.js

### ISSUE THREAD

**Issue by catXiaoXiao** [dvajs/dva#2150]
期望：按照路由打包成不同js，模块加载

**Comment by catXiaoXiao** [comment]
需要配置.webpackrc.js 里的env.production吗

**Comment by sorrycc** [comment]
roadhog 项目？

**Comment by catXiaoXiao** [comment]
> roadhog 项目？

是的

**Comment by catXiaoXiao** [comment]
> roadhog 项目？

如何在.webpackrc配置里配置vendor呢？

**Comment by catXiaoXiao** [comment]
在webpackrc.js里添加了如下配置拆分vendor：
![image](https://user-images.githubusercontent.com/26037975/60787252-b888a600-a18b-11e9-9026-1b354504623a.png)
成功的：
![image](https://user-images.githubusercontent.com/26037975/60787285-d8b86500-a18b-11e9-8594-de23083a3624.png)
可是dva/dynamic路由模块拆分并没有生效

**Comment by catXiaoXiao** [comment]
disableDynamicImport: false就可以了，但是会有打包内存溢出问题，dev下加node --max_old_space_size=4096 node_modules/roadhog/bin/roadhog dev打包成功了
