### ISSUE TITLE
[app.start] container null not found

### ISSUE THREAD

**Issue by hejuejina** [dvajs/dva#2157]
使用browserHistory  后访问index会出现[app.start] container null not found错误，配置如下

import { createBrowserHistory as createHistory } from 'history';

const app = dva({
  history: createHistory()
});

history 的版本为4.9.0

**Comment by three-ago-zhou** [comment]
跟history没什么关系 。是app.start()中传入的值有关系。源码中是默认查找html中匹配的第一个标签元素。你确定你app.start传入标签的id了？

**Comment by xhuanhuan** [comment]
这个问题要怎么解决呢，我也遇到了

**Comment by dbwcooper** [comment]
确保你的 html 模板中，是否直接引入的 index.js ;;
配置 webpack html plugin
```js
   new HtmlPlugin({
      template: join(paths.src, 'index.ejs'),
      scriptLoading: true,
      inject: true, // set true to automatic inject js and css
    }),
```
并且查看 html 模板是否直接引入了 index.js 
```js
<script src="index.js"></script> //this line will run before html initialization is complete
```

更新为 

```js
<script defer src="index.js"></script>
```
