### ISSUE TITLE
dva支持qiankun框架问题

### ISSUE THREAD

**Issue by gaorubin1990** [dvajs/dva#2159]
## Background

想在qiankun微前端框架中集成dva子应用

## Proposal

qiankun框架需要配置webpack的output相关信息（library、libraryTarget、jsonpFunction），dva只能使用webpack.config.js配置文件（不兼容roadhog2），配置后页面出现文件夹目录。请问qiankun框架集成dva子应用的正确姿势什么什么？

**Comment by xc1427** [comment]
这是个伪命题，qiankun 不感知子应用的打包方式，子应用只要暴露相应的钩子供 qiankun 调用就可以。如果是 umi 应用，请参考 umi-plugin-qiankun 。

**Comment by gaorubin1990** [comment]
> 这是个伪命题，qiankun 不感知子应用的打包方式，子应用只要暴露相应的钩子供 qiankun 调用就可以。如果是 umi 应用，请参考 umi-plugin-qiankun 。

使用parcel解决了
