### ISSUE TITLE
访问不同组件希望可以通过传参方式让页面title显示不同可以吗？

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#216]
求参考

**Comment by codering** [comment]
这问题应该时React的使用问题。
同学，建议多看看react的基础知识吧

**Comment by sorrycc** [comment]
https://github.com/gaearon/react-document-title
试试这个。

**Comment by DickyT** [comment]
挖个坟, 推荐一下这个package
https://github.com/nfl/react-helmet
react-helmet作者基于react-document-title写出来的, 除了title别的都能改, 我实际环境用这个一段时间了, 推荐一下
