### ISSUE TITLE
先执行一个effects，然后将数据put ，再执行另一个effects,用select获取第一个effects中put的state信息，得到的是上一次的数据

### ISSUE THREAD

**Issue by wangxv** [dvajs/dva#2161]
## What happens?
先执行一个effects，然后将数据put ，再执行另一个effects,用select获取第一个effects中put的state信息，得到的是上一次的数据

## How To Reproduce
1.执行getCourseInfoByCouseIdAndUserId
2.再执行getCourseExamResultList  
3.在getCourseExamResultList中获取的userInfo是上一次getCourseInfoByCouseIdAndUserId获取的值
但是确实是先执行了getCourseInfoByCouseIdAndUserId并且得到的也是新值，put的也是得到的新值
![image](https://user-images.githubusercontent.com/30195186/61422369-f8931a00-a93d-11e9-80db-ed4faaa3fe97.png)

## Context

 "dayjs": "^1.8.10",
taro:1.2.7

**Comment by trexguo** [comment]
put是非阻塞的，用：
yield put.resolve({type: 'getCourseInfoByCouseIdAndUserId'})
