### ISSUE TITLE
路由跳转新页面触发上一页面reducers中的方法

### ISSUE THREAD

**Issue by zhilianbi520** [dvajs/dva#2162]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi`, select `app`, choose `dva`, then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.在当前页面执行reducers中的方法，
2.路由跳转至新的页面，上一页面reducers中的方法被执行

**Expected behavior**
1.在当前页面执行reducers中的方法，
2.路由跳转至新的页面，上一页面reducers中的方法不被执行

## Context
- **Dva Version**:2.4
- **Node Version**:10.15.3
- **Platform**:

**Comment by yoyo837** [comment]
我这里遇到路由到下一个页面上一个页面componentDidMount 又执行一次

**Comment by trexguo** [comment]
你reducers中的方法具体是通过什么方式执行的？

**Comment by zhilianbi520** [comment]
@trexguo 当前页是点击事件触发dispatch()，然后调用的。
