### ISSUE TITLE
如何为dva-immer书写声明文件？

### ISSUE THREAD

**Issue by Sayid1** [dvajs/dva#2163]
## What happens?

我在ANT DESIGN PRO 4.0中使用了typescript和dva-immer, 但我不知道如何为dva-immer编写声明文件，因为引入dva-immer的时候，ts提示无法找到模块'dva-immer'的声明文件

```javascript
declare module 'dva-immer' {
  type immer = () => { [ key: string ]: any }
  
  const useImmer: immer;
  
  export = useImmer;
}
```

## 相关环境信息

- **Umi 版本**：2.8.9 
- **Node 版本**：10.16.0
- **操作系统**：macOS

**Comment by xc1427** [comment]
dva-immer 只是一个插件，没有对外的 api
