### ISSUE TITLE
子组件怎么从后台取到数据

### ISSUE THREAD

**Issue by Benpaodejiezai** [dvajs/dva#2164]
![image](https://user-images.githubusercontent.com/51696361/61849086-be4bee80-aee2-11e9-977f-8f0d503589a4.png)

页面是使用 this.props.XXX 来获取数据的，直接访问此页面是可以正确运行的，但是把它嵌入到其他页面，this.props 就取不到数据了，应该怎么办呢？
![image](https://user-images.githubusercontent.com/51696361/61849143-eb989c80-aee2-11e9-9bce-8ca55d92e97b.png)
我分析是嵌入到其他页面里，props 就变成从父页面传过去的那些数据了，没有子页面自己从后台获取的数据了

**Comment by LukerSpringtree** [comment]
啥?你在说啥?
