### ISSUE TITLE
为什么2.5-2.6全都是beta版？

### ISSUE THREAD

**Issue by xue-chao** [dvajs/dva#2167]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，选择 `app`，然后选上 `dva`，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by cike8899** [comment]
什么时候2.6才发布正式版？

**Comment by suncunhu** [comment]
下一个大版本应该是dva@3吧？ 
年内会发布出来吗？
