### ISSUE TITLE
onError问题， 请教下在request.js里面如何触发onError

### ISSUE THREAD

**Issue by z-lionel** [dvajs/dva#2168]
代码如下：
...
return fetch(url, newOptions)
    .then(checkStatus)
    .then((response) => {
      return response.json();
    }).catch((err) => {
      return Promise.reject(err);
    });
}
想在request.js里面统一处理错误提示信息， 而不用去effects里面每个方法单独加 ：
比如登录的时候，提示密码错误，或者用户名错误；
想在上面的代码加上throw new Error() 出发全局的onError事件。
请问该如何修改？

**Comment by xc1427** [comment]
在 model.effects 里面的抛错才会触发 onError 回调。

我推荐你使用 umi-request，然后拦截器配置可以满足你的要求。
