### ISSUE TITLE
dva router 路由可选参数无效

### ISSUE THREAD

**Issue by jinyindu** [dvajs/dva#2173]
dva router 路由可选参数无效

![image](https://user-images.githubusercontent.com/18224886/62184735-e4b1d400-b391-11e9-9237-eac6e105632b.png)

访问 http://localhost:8001/100//home 这个地址  这样访问访问不到页面提示404 ，storeId 可以微为空

**Comment by jinyindu** [comment]
function RouterConfig({ history }) {
  return (
    <Router>
      <Switch>
        <Route path="/" exact component={IndexPage} />
        <Route path="/:pid/:storeId?/home" exact component={Index} />
      </Switch>
    </Router>
  );
}

**Comment by jinyindu** [comment]
<Router>
      <Switch>
        <Route path="/" exact component={IndexPage} />
        <Route path="/:pid/:storeId?/home" exact component={Index} />
      </Switch>
    </Router>

**Comment by jinyindu** [comment]
<Router>
      <Switch>
        <Route path="/" exact component={IndexPage} />
        <Route path="/:pid/:storeId?/home" exact component={Index} />
      </Switch>
    </Router>

**Comment by jinyindu** [comment]
<Router>
      <Switch>
        <Route path="/" exact component={IndexPage} />
        <Route path="/:pid/:storeId?/home" exact component={Index} />
      </Switch>
    </Router>

**Comment by LukerSpringtree** [comment]
@jinyindu 

朋友你可能这边理解的有问题.

你先去看看这个库 https://www.npmjs.com/package/path-to-regexp
这个库是 React-Router 实现的解析路径的 处理库

官方确实有提到  :id?问号的用法

```js
const regexp = pathToRegexp('/:foo/:bar?')
// keys = [{ name: 'foo', ... }, { name: 'bar', delimiter: '/', optional: true, repeat: false }]
 
re.exec('/test')
//=> ['/test', 'test', undefined]
 
re.exec('/test/route')
//=> ['/test', 'test', 'route']
```
但是: 访问的路径 应该为
http://localhost:8001/100/home
而不是
http://localhost:8001/100//home

请知悉, 这个问题和  dva 没有任何关系,是你用错了
