### ISSUE TITLE
effect中发起一个action，第二个 action如果采用如图中所示的写法，当response.data为空数组时会造成action无法执行，state无法更新的问题。想问一下原因？

### ISSUE THREAD

**Issue by wo-de-ping-er** [dvajs/dva#2175]
Feature 
![image](https://user-images.githubusercontent.com/23158766/62518413-20e6a800-b85c-11e9-9c39-68d690d6eb69.png)

**Comment by 662** [comment]
`response.data` 为空的话，会抛出异常 ‘Cannot read property 'week' of undefined’
这个`put`也就不能正确调用了

**Comment by cyulin** [comment]
response.data && response.data[0] && response.data[0].week
