### ISSUE TITLE
dva-core在0.60以上版本的React Native项目中启动crash

### ISSUE THREAD

**Issue by guaiguaimao** [dvajs/dva#2176]
#    使用@connect报错：Module AppRegistry is not a registered callable module
## 使用版本
    "dependencies": {
         "dva-core": "^1.4.0",
         "dva-loading": "^3.0.12",
         "react": "16.8.6",
         "react-native": "0.60.3",
         "react-native-gesture-handler": "^1.3.0",
         "react-navigation": "^3.11.1",
         "react-navigation-redux-helpers": "^3.0.2",
         "react-redux": "^7.1.0"
     },
    "devDependencies": {
        "@babel/core": "^7.5.5",
        "@babel/plugin-proposal-decorators": "^7.4.4",
        "@babel/runtime": "^7.5.5",
        "@react-native-community/eslint-config": "^0.0.5",
        "@types/react": "16.8.6",
        "@types/react-native": "0.60.3",
        "babel-eslint": "^10.0.1",
        "babel-jest": "^24.8.0",
         "babel-preset-react-app": "^9.0.0",
         "eslint": "5.1.0",
         "eslint-plugin-prettier": "2.6.0",
         "eslint-plugin-react": "7.8.2",
         "eslint-plugin-react-native": "3.5.0",
         "jest": "^24.8.0",
         "metro-react-native-babel-preset": "^0.55.0",
         "react-test-renderer": "16.8.6"
       },
## 使用@connect连接model报错
      import { connect } from 'react-redux'
      @connect(({ answer, loading }) => ({
       ...answer,
          isLoad: loading.effects["answer/getAnswerList"] || false
       }))
       class AnswerSceen extends React.Component {
        constructor() {
          super(...arguments)
         }
       }

> 如果不使用@connect，项目运行正常
> 使用@connect，项目启动不了，报错
    Unhandle JS Exception:
    Module AppRegistry is not a registered callable module

**Comment by lp4298707** [comment]
怎么解决的啊

**Comment by innocces** [comment]
放到下面connect就好了
