### ISSUE TITLE
如何直接在函数中获取model中的值？

### ISSUE THREAD

**Issue by zzyyzz1992** [dvajs/dva#2179]
## What happens?
例如在antd pro中的getAuthority函数，要获取用户的授权，这个函数调用并不在特定的React Component中调用。

antd pro官方的写法是从localStorage中读取。
我尝试使用@connect方法调用，
```
@connect(user => ({ currentUser: user.currentUser }))
export function getAuthority(currentUser: { auths: string[] }): string | string[] {
    const authorityString = currentUser.auths; //typeof currentUser === "undefined";
    if (typeof authorityString === "undefined" || authorityString === null) {
        return [];
    }
   ...
}
```
但是IDE提示
> TS1206: Decorators are not valid here

请问如何直接获取到dva的model对象？

我是结合umi一起使用的。

**Comment by zzyyzz1992** [comment]
![image](https://user-images.githubusercontent.com/3894825/63162074-3fb31e80-c054-11e9-8844-4ec2e1f4f049.png)
window.g_app._store好像也不行

**Comment by lishuai1021** [comment]
getAuthority 写个工具方法不行？哪个组件用在哪引

**Comment by zzyyzz1992** [comment]
@lishuai1021 我放弃了，乖乖用localstorage了，在调用这个函数的母控件上connect以后运行提示store为空还是啥来着。
