### ISSUE TITLE
dva-knowledgemap css module图片有问题

### ISSUE THREAD

**Issue by jindada** [dvajs/dva#218]
![image](https://cloud.githubusercontent.com/assets/16317349/19797634/ea5d763e-9d1e-11e6-9e24-e5bf7365fc9f.png)
我没太懂css module 可以详细说明一下吗 我理解的这jsx文件里面引入的文件名是错误的吧

**Comment by jindada** [comment]
![image](https://cloud.githubusercontent.com/assets/16317349/19798515/1620017e-9d24-11e6-8298-b090b23a217e.png)
![image](https://cloud.githubusercontent.com/assets/16317349/19798533/3482dae2-9d24-11e6-88e7-de1bda440996.png)
路径是没有问题的 我这么配置 styles打印出来是{} 但是 import ‘./loginForm.less’ 是可以的 而且build之后样式名称也没有像css module那样被重命名

**Comment by sorrycc** [comment]
推荐阮老师的 css modules 入门，http://www.ruanyifeng.com/blog/2016/06/css_modules.html
