### ISSUE TITLE
如何手动取消 loading 呢

### ISSUE THREAD

**Issue by kwzm** [dvajs/dva#2187]
## What happens?
当 effects 里面报错之后我将错误抛出，但是同时导致 loading 没有 hide，所以想问一下有没有可以手动取消 loading 状态的方法

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，选择 `app`，然后选上 `dva`，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.8.16
- **Node 版本**： 10.13.0
- **操作系统**： win7

**Comment by yoyo837** [comment]
要保证  effects  里不抛出异常，异常在其他地方处理

**Comment by yoyo837** [comment]
#1746

**Comment by sorrycc** [comment]
在 effect 里加 try...catch 或者全局配 onError。

**Comment by dogXgod** [comment]
使用dva-loading插件，代理effects中的loading状态。就可以不用手动配置loading状态了。

**Comment by MSK0379** [comment]
> 使用dva-loading插件，代理effects中的loading状态。就可以不用手动配置loading状态了。

使用dva-loading后端报错返回了， 怎么结束loading。

**Comment by yoyo837** [comment]
看上面
