### ISSUE TITLE
传参问题求助！

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#219]
我想从routes/users.jsx 模块
传参给 components/layout/admin.jsx 这个布局组件
这个布局组件调用了下面的 components/layout/admin/Header.jsx 头部文件
我所传的参数是用于Header.jsx 里面的

请问我要咋写 哈哈哈！
求大哥们帮助下！

**Comment by sorrycc** [comment]
React 只有 props 传参一条路，整理下思路，你应该可以想出来的。

**Comment by junmaqiang** [comment]
找到方法了，原来传参数到子组件之后 写法不正确
