### ISSUE TITLE
dva-core test

### ISSUE THREAD

**Issue by Malarkey-Jhu** [dvajs/dva#2191]
截图来自 https://github.com/dvajs/dva/blob/master/packages/dva-core/test/effects.test.js

![image](https://user-images.githubusercontent.com/36290564/64224012-9354b180-cf08-11e9-965f-753f1c1cfe37.png)

**能请问下如果是takeLatest，只拿到最新的action的话，为何setTimeout里是200ms，意思是第一个delay也被call了吗**

![image](https://user-images.githubusercontent.com/36290564/64224215-48876980-cf09-11e9-8d55-6a7d0a2f0d07.png)

**另外throttle的注释里写 // Only catch the last one.但不是应该只拿到第一个吗，然后为何setTimeout里也是200ms，难道不是只拿到第一个action，只delay一次而吗，谢谢**

**Comment by DiamondYuan** [comment]
200ms 只是为了确保测试一定成功吧，改成 150 应该也没问题，
