### ISSUE TITLE
提一个建议，把文档能好好补全一下么，谢谢！

### ISSUE THREAD

**Issue by dmwin72015** [dvajs/dva#2198]
提一个建议，把文档能好好补全一下么。谢谢

**Comment by Cooper-beiyuan** [comment]
都是集成的别人的东西，他自己都不好意思写文档，就标题取得好。
蛋疼的ant pro用这个东西，看了两天打印，都没搞明白没什么要怎么搞，结果就是把各种别人的东西组合在一起的玩意，居然还这么多star，唉

**Comment by ywy94ywy** [comment]
集成，融合，优化，不然全部自己造轮子么，再做一个webpack？

**Comment by dmwin72015** [comment]
> 集成，融合，优化，不然全部自己造轮子么，再做一个webpack？

确实是没必要造轮子，但是CV民工需要一份文档

**Comment by sunyum** [comment]
这文档就不是让人看得，从头到尾都没看到一个model完整的示例说明
