### ISSUE TITLE
dva如何集成原有的redux应用？

### ISSUE THREAD

**Issue by Frank1e0927** [dvajs/dva#2199]
类似https://rematch.github.io/rematch/#/lang/zh-cn/api-wen-dang/init-redux-api?id=init-redux-api

**Comment by Jeremyyang** [comment]
我也有类似需求。
尝试将内层项目(可以视作一个内核，基于react+redux)的 store 放到外层项目(基于dva)进行创建，让整体只有一份 store。
但是外层 _store.getState() 获取到的 state 又比内层需要的多一层级，有没有映射的办法中间件什么的???

**Comment by chaserstrong** [comment]
@Jeremyyang @Frank1e0927  我也有类似的需求，请问你们后面怎么弄的？
