### ISSUE TITLE
history模式下，subscriptions里面的console都打印不出来，hash模式是可以的

### ISSUE THREAD

**Issue by wanlixi** [dvajs/dva#2200]
```
subscriptions: {
    setup({ history }) {
      return history.listen(({ pathname, search }) => {
        console.log(pathname, search)
      })
    },
  },
```
history模式下，跳转页面 console都打印不出来

**Comment by closertb** [comment]
> ```
> subscriptions: {
>     setup({ history }) {
>       return history.listen(({ pathname, search }) => {
>         console.log(pathname, search)
>       })
>     },
>   },
> ```
> 
> history模式下，跳转页面 console都打印不出来

我遇到过，这其实是BrowserRouter问题，他不支持history属性，而是内部会自动生成一个history实例，就造成了history与Dva的history不是同一个。建议使用：
```js
import { Router } from 'react-router-dom';

然后
<Router history={history}>
</Router>
```
