### ISSUE TITLE
能否升级一下路由组件，消除组件警告

### ISSUE THREAD

**Issue by yaeSakuras** [dvajs/dva#2204]
react升级到16.9，router4版本使用了旧的生命周期方法会有警告提示。

![image](https://user-images.githubusercontent.com/7360502/65828727-5e9e0500-e2d0-11e9-98b7-4e8f9aaa1676.png)

**Comment by endink** [comment]
消除警告 +1 ，有点刷屏

**Comment by closertb** [comment]
强迫症患者，只有先关闭了chrome的警告
