### ISSUE TITLE
[Feature Request] we need typescript！！！！！！！！

### ISSUE THREAD

**Issue by uchihaobito10086** [dvajs/dva#2205]
is there any plan to surport typescript?
because it hard to spell all word correct when we type the dipatch type。
and if it surport typescript to constraint the payload info is better

**Comment by samayo** [comment]
project seems like dying, I don't suggest you use dva specially now + non english doc

**Comment by ManuRodgers** [comment]
> is there any plan to surport typescript?
> because it hard to spell all word correct when we type the dipatch type。
> and if it surport typescript to constraint the payload info is better

try dva-model-creator for ts
