### ISSUE TITLE
为什么hooks的写法中dispatch({}).then中取不到全局中最新改变的state，但是class写法可以

### ISSUE THREAD

**Issue by LPink777** [dvajs/dva#2206]
直接上截图
![image](https://user-images.githubusercontent.com/19523872/66499758-00083080-eaf3-11e9-82f9-eacb889f5b52.png)
![image](https://user-images.githubusercontent.com/19523872/66499799-13b39700-eaf3-11e9-99b6-45a0011308d8.png)

除了在modal中effects里return response，怎么样可以在hooks的写法中取到截图中的data值

**Comment by AimLuo** [comment]
useEffects

**Comment by LPink777** [comment]
> useEffects

可以直接在函数中获取吗，不在useEffects中获取

**Comment by AimLuo** [comment]
> > useEffects
> 
> 可以直接在函数中获取吗，不在useEffects中获取

好像不行，

**Comment by LPink777** [comment]
> > > useEffects
> > 
> > 
> > 可以直接在函数中获取吗，不在useEffects中获取
> 
> 好像不行，我一般都是return yielid put(foo)

为什么有这种差异呢？

**Comment by AimLuo** [comment]
> > > > useEffects
> > > 
> > > 
> > > 可以直接在函数中获取吗，不在useEffects中获取
> > 
> > 
> > 好像不行，我一般都是return yielid put(foo)
> 
> 为什么有这种差异呢？

因为是异步的。

**Comment by LPink777** [comment]
> > > > > useEffects
> > > > 
> > > > 
> > > > 可以直接在函数中获取吗，不在useEffects中获取
> > > 
> > > 
> > > 好像不行，我一般都是return yielid put(foo)
> > 
> > 
> > 为什么有这种差异呢？
> 
> 因为是异步的。

clss组件的写法中不是异步的吗？
