### ISSUE TITLE
redux中的数据，刷新了页面就重置了，如何处理

### ISSUE THREAD

**Issue by LemonTree-shine** [dvajs/dva#2209]
redux中的数据，刷新了页面就重置了，如何处理

**Comment by LemonTree-shine** [comment]
需要自己手动维护吗？因为本身redux是会存在这个问题，有个redux-persist可以处理这个问题，那在dva中是否可以引入这个npm包来实现数据持久化。

**Comment by irfanabliz** [comment]
Same here, how we can implement redux-persist in dva.js?

**Comment by caidongwei** [comment]
dva 是否可以引入redux-persist
