### ISSUE TITLE
请教下URL和模块export问题

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#221]
本地访问路径：http://localhost:8989/#/config?_k=ooztd2
我看很多例子的Routes/下面的每个组件就对外暴露一个default的方法，

我有两个疑问
1，**我想知道可以用export多暴露一些方法？**

2，**用export暴露后访问路径可以是 http://localhost:8989/#/config/SystemConfig 这样？**

**Comment by sorrycc** [comment]
1. 可以，比如 `export function a {}`
1. 不可以

**Comment by junmaqiang** [comment]
也就是说我们只能通过routes下面的组件传参的方式访问喽
