### ISSUE TITLE
dva支持taro吗？

### ISSUE THREAD

**Issue by liuyaochen04** [dvajs/dva#2212]
dva支持taro吗？
如果支持怎么集成呢？

**Comment by closertb** [comment]
> dva支持taro吗？
> 如果支持怎么集成呢？

使用Dva-core来做你的model控制

**Comment by whatwewant** [comment]
@liuyaochen04
// 直接生成taro项目 => yarn create @webafe/taro [appName?]
https://github.com/webafe/create-taro

// 封装的库
https://github.com/zcorky/dva-for-taro
