### ISSUE TITLE
import { useSelector, useDispatch } from 'dva-core';

### ISSUE THREAD

**Issue by liuyaochen04** [dvajs/dva#2218]
## What happens?
TypeError: (0 , _index3.useDispatch) is not a function
没有useDispatch？ undefined？

dva-core 2.0.0

环境
taro+dva+hooks

**Comment by sorrycc** [comment]
hooks 接口是 react-redux 提供的，dva-core 里没有。

**Comment by damaohub** [comment]
import { useSelector, useDispatch } from 'dva';还是报一样的错误

**Comment by BigKongfuPanda** [comment]
> hooks 接口是 react-redux 提供的，dva-core 里没有，dva 里才有。

文档上面没有写怎么引入啊？
