### ISSUE TITLE
[Bug] connect装饰后无法获取ref

### ISSUE THREAD

**Issue by JhonXY** [dvajs/dva#2222]
## What happens?
使用umi@2.9.5默认依赖的dva@2.6.0-beta.6
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
dva connect与antd Form同时包裹一个class组件时，使用wrappedComponentRef取该组件ref时会警告，但会直接抛错无法执行
![image](https://user-images.githubusercontent.com/21687167/67355151-16999780-f589-11e9-8d85-bdfbe4124068.png)
非beta版本使用正常。

## Mini Showcase Repository(REQUIRED)
https://codesandbox.io/s/gifted-snyder-e2s45?fontsize=14

## How To Reproduce

**Expected behavior**
因为项目涉及的内容较多，希望能够在不修改ref的使用方式下恢复正常

## Context
- **Dva Version**: >=2.6.0-beat.1
- **antd Version**: *
- **Node Version**: *
- **Platform**: *

**Comment by huxiaoqi567** [comment]
参考 https://stackoverflow.com/questions/53819335/withref-is-removed-to-access-the-wrapped-instance-use-a-ref-on-the-connected-c

**Comment by JhonXY** [comment]
> 参考 https://stackoverflow.com/questions/53819335/withref-is-removed-to-access-the-wrapped-instance-use-a-ref-on-the-connected-c

redux是有什么机制改变了吗，之前的withRef是不影响的，希望能够请教一下

**Comment by NgeKaworu** [comment]
It's work for me
```js
import { forwardRef } from "react";
import { connect } from "dva";

export default compose(
  Comp =>
    forwardRef((props, ref) => {
      return <Comp {...props} forwardRef={ref} />;
    }),
  connect(state => state),
)(CategoryList);

function CategoryList({ forwardRef, ...resProps }) {
  return <div ref={ref => (forwardRef.current = ref)}></div>;
}

function compose(...fns) {
  return fns.reduceRight(
    (prevFn, nextFn) => (...args) => nextFn(prevFn(...args)),
    value => value,
  );
}

```
[doc](https://zh-hans.reactjs.org/docs/forwarding-refs.html#forwarding-refs-in-higher-order-components)

**Comment by fengyun2** [comment]
同问

**Comment by Tenodec** [comment]
更新antd版本：yarn  add antd@4.0.0@beta   这个版本为函数组件重构了很多组件，可以直接拿到ref
重点来了！！！！！
你得同时有 antd  和antd-4.0.0@beta，在同一个项目下不能同时install ，所以最好新建一个文件夹。运行：yarn  add antd@4.0.0@beta @ant-design/icons ；
重命名antd为antd@beta（名字随便取）
拷贝改名字后的antd文件夹到项目，
更改Form引入，例如 import  {Form} from ‘antd@beta’
yarn start 会报错
报缺少module，在刚刚install beta版antd 中去拷贝，找不到icons，修改路径就是
我现在的项目就是这样解决的

**Comment by oldfeel** [comment]
react hooks 不用 connect,用 useDispatch, useSelector
````
import { useDispatch, useSelector } from 'dva'

    const dispatch = useDispatch()
    console.log("dispatch", dispatch)
    const userInfo = useSelector(({ global }) => global.userInfo)
    console.log("userInfo", userInfo)
````

**Comment by Censwin** [comment]
这是 `react-redux` 的问题，可以这么解决：

childrenComponet
```js
import { connect } from 'dva';
class Child extends React.Component {...................}

const mapStateToProps = ({description})=> ({description})
export default connect(mapStateToProps,null,null,{withRef: true})(Child)
```
设置参数 `withRef` 为 `true` 后，父组件中拿到的`ref`会多出来一个 `wrappedInstance`, `state` 等参数都在这个对象内
> 我使用的是V5，据说V6将 withRef 删除了，请自行查阅文档  

parentComponent
```js
componentDidMount () {
    let childrenState = this.componentRef.wrappedInstance.state; //  想干嘛干嘛
}
render () {
   return (
     <Child ref={ref => this.componentRef = ref}  />
   )
}
```
