### ISSUE TITLE
请教一个form的问题

### ISSUE THREAD

**Issue by BillBillBillBill** [dvajs/dva#223]
现在有多个form,而提交前需要校验这些form中的数据,现在是用onFieldsChange的方法把数据更新到state中,那么如果需要校验数据的话我是不是应该在effect里提交数据前调用form.validateFields? 问题是怎么能够拿到form对象呢?谢谢
如果在创建时把这些form放到state中会提示Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`

**Comment by sorrycc** [comment]
我的想法是：在这些 form 的父组件或 routeComponent 里执行校验(通过 props 往下传)，校验完所有的 form 之后，走 action 传给 effect 做后续处理。

**Comment by BillBillBillBill** [comment]
例如我在父组件里这样创建:
CustomizedForm = Form.create({})(CustomizedForm);
那我应该怎么在父组件中获取CustomizedForm里面的form呢?

**Comment by BillBillBillBill** [comment]
知道了,在父组件中通过ref来访问,问题解决了,谢谢
