### ISSUE TITLE
dva组件开发问题请教。

### ISSUE THREAD

**Issue by xiemms** [dvajs/dva#224]
dva 开发组件的时候 models层 的subscriptions 方法是否可用当做componentDidMount来使用？
组件没有入口文件，发现需要配置空路由和空start才能触发models里面的内容。 app.router(()=>({})); app.start();
是否可以提供一个组件开发方案呢？ :D

**Comment by xiemms** [comment]
dva 开发组件的时候 models层 的subscriptions 方法是否可用当做componentDidMount来使用？
组件没有入口文件，发现需要配置空路由和空start才能触发models里面的内容。 app.router(()=>({}));  app.start();
是否可以提供一个组件开发方案呢？  :D

**Comment by sorrycc** [comment]
组件建议尽量纯粹点，只负责 UI 的渲染，不要和数据绑定，数据操作放 model 里。
