### ISSUE TITLE
请问一下   dva-loading如何清空loading中的状态   初始接口loading从undefined—true—false     二次加载接口loading从false—true—false    如何清空接口loading为初始状态？

### ISSUE THREAD

**Issue by wo-de-ping-er** [dvajs/dva#2240]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，选择 `app`，然后选上 `dva`，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xblj** [comment]
在redux connect的时候设置默认值

**Comment by wo-de-ping-er** [comment]
> 在redux connect的时候设置默认值

这个应该如何设置？attendanceListLoading: loading.effects['attendanceInfo/getAttendanceList']   我们一般使用这样方式设置初始值，关键我如何在第二次加载时将初始值设置为undefined?

**Comment by ldwonday** [comment]
@wo-de-ping-er 解决了吗？
