### ISSUE TITLE
使用dva-cli 创建项目报错

### ISSUE THREAD

**Issue by sir-ran** [dvajs/dva#2242]
## What happens?
使用dva-cli 创建项目报错

## Mini Showcase Repository(REQUIRED)
无

## Context

- **Dva Version**: 0.10.1
- **Node Version**: 10.14.2
- **Platform**: windows
![image](https://user-images.githubusercontent.com/26730748/68598004-e0d93600-04d8-11ea-801e-78bf61aecdec.png)

**Comment by dujuanxian** [comment]
降级node版本试试，我使用node12也是安装出错，降级到8.10.0是OK的
