### ISSUE TITLE
路由模式改成了createBrowserHistory，不是hash模式，每次点击链接跳转是不会有#的，但是每次刷新页面最后就会被加上/#，请问能去掉这个吗

### ISSUE THREAD

**Issue by 2295109582** [dvajs/dva#2260]
路由模式改成了createBrowserHistory，不是hash模式，每次点击链接跳转是不会有#的，但是每次刷新页面最后就会被加上/#，请问能去掉这个吗

import dva from 'dva';
import { createBrowserHistory as createHistory } from 'history';
import injectionModel from '@m';
import RouterConfig from '@r';

// 1. Initialize
const app = dva({
  history: createHistory(),
});

// 2. Plugins
// app.use({});

// 3. Model
injectionModel(app);

// 4. Router
app.router(RouterConfig);

// 5. Start
app.start('#root');

版本
"dva": "^2.4.0",
"eslint-plugin-react-hooks": "^2.1.2",
"history": "^4.10.1",
 "react": "16.8.6",
"react-codemirror2": "3.0.7",
"react-dom": "16.8.6"

**Comment by mankeheaven** [comment]
这个应该是你配置问题

**Comment by 2295109582** [comment]
> 这个应该是你配置问题

配置全在这了

**Comment by HawserC** [comment]
你是不是修改了dva/lib/index.js 里的 var _createHashHistory = _interopRequireDefault(require("history/createHashHistory"));

**Comment by HawserC** [comment]
> 你是不是修改了dva/lib/index.js 里的 var _createHashHistory = _interopRequireDefault(require("history/createHashHistory"));

我这边是因为报Warning，修改了它，就出现了这个问题，不修改就没有#/ 了

**Comment by feWei1997** [comment]
请教下最后是如何解决的呢？我改造老项目也遇到了这个问题。
