### ISSUE TITLE
onError的参数err，ts类型校验是什么

### ISSUE THREAD

**Issue by webxiaobian** [dvajs/dva#2262]
onError的参数err，ts类型校验是什么？在哪里可以找得到呢有文档的话给一份地址多谢

**Comment by yuchen100** [comment]
node_modules\dva\index.d.ts
`
export interface Hooks {
  onError?: (e: Error, dispatch: Dispatch<any>) => void,
  onAction?: onActionFunc | onActionFunc[],
  onStateChange?: () => void,
  onReducer?: ReducerEnhancer,
  onEffect?: () => void,
  onHmr?: () => void,
  extraReducers?: ReducersMapObject,
  extraEnhancers?: StoreEnhancer<any>[],
}
`
