### ISSUE TITLE
请问有多个Model，当dispatch一个action更新了state后，dva会render哪些组件呢？

### ISSUE THREAD

**Issue by effapp** [dvajs/dva#2268]
## What happens?

请问有多个Model，当dispatch一个action更新了state后，dva会render哪些组件呢？
比如user Model的dispatch更新了currentUser之后，就会render所有connect user Model的组件吗？

**Comment by wangxujie** [comment]
会render所有的。感觉dva不太适合前端，比较适合后端

**Comment by wangxujie** [comment]
会render所有的
