### ISSUE TITLE
请问如何通过返回值做全局消息

### ISSUE THREAD

**Issue by kevin0137** [dvajs/dva#228]
通过接口异步请求数据 返回的数据内容是用户操作成功与否 比如这样
```
const {data} = {
    result: 1000,
    message: 'success',
};
```
请问如何监听返回结果 再通过`message.success(...)`做全局消息?

**Comment by sorrycc** [comment]
```js
const {data} = {
    result: 1000,
    message: 'success',
};
```

没理解这句是什么意思。在 effect 中拿到结果后，调 `message.success` 不就好了吗?

**Comment by kevin0137** [comment]
示例如下: 管理员修改个人信息
```
const {data} = yield call(modifyAdminInfo, payload);
if(data){
  yield put({
    type: 'querySuccess',
    payload: {
      result: data
    }
  });
}
```
然后根据`result`的更变 在`Component AdminInfo`中执行对应的`message.success(..)`或者`message.error(...)` 
我就是不知道在`Component`中怎么实现... =。=

**Comment by kevin0137** [comment]
示例如下: 管理员修改个人信息
```
const { data } = yield call(modifyAdminInfo, payload);
if(data){
  yield put({
    type: 'querySuccess',
    payload: {
      result: data
    }
  });
}
```
effect得到数据后 如何在`Component AdminInfo`中监听result的变化 然后调用`message.success`或者`message.error`?

**Comment by sorrycc** [comment]
为啥要在 AdminInfo 里监听 result 的变化，不能在 effect 里做?

**Comment by kevin0137** [comment]
我想的是effect的作用仅仅只是`put/call reduce` 对于数据的渲染和交互(如`message`)我认为应该放到`Component`中 不知道我这样的理解对不对...
这个问题在详细一点: 用户点击修改信息后 调用`message.load(...)` 数据响应后应该在什么位置调用`message.success(...)` 就酱紫

**Comment by afc163** [comment]
这个和我之前的疑问是类似的。

**Comment by kevin0137** [comment]
抱歉我不是很明白你的意思... 有没有实例可以让我参考一下?

**Comment by afc163** [comment]
我的意思是我也有同样的疑问。

**Comment by sorrycc** [comment]
message 方法应该放在 effect 里，这是触发一个 action 之后要做的事。

**Comment by anhuiliujun** [comment]
如何做全局的loading显示呢？

**Comment by sorrycc** [comment]
@anhuiliujun 使用 dva-loading，然后封装一个 react 组件，监听 loading state，执行 message.load 等方法。

**Comment by anhuiliujun** [comment]
谢谢回复，我起初也是这么想的，如果是在react中，我就会在最顶层组件里（比如react-router的顶层路由中），处理这个全局的load展示，以避免每个组件里都需要引用我这个处理load的展示。
但是我现在是在react-native中，我不清楚可否在最顶层弄

**Comment by sorrycc** [comment]
也可以的。
