### ISSUE TITLE
[Feature Request] 有没有办法给 component 绑定一个默认的 namespace，这样这个 component 内 dispatch 的 action 默认就是在这个 namespace 内的，除非另外指定前缀？

### ISSUE THREAD

**Issue by glacjay** [dvajs/dva#2281]
## Background

感觉这样在 component 内就能省写很多遍 namespace 前缀了。

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by running-snail-sfs** [comment]
意义并不大

**Comment by glacjay** [comment]
@running-snail-sfs 嗯，我已经找到一种方法了，就是定义个 dispatchLocal 的 method，给 action.type 加个前缀就好了。
