### ISSUE TITLE
为什么我npm install dva-cli -g 安装不了，一直报错？

### ISSUE THREAD

**Issue by Vinsurs** [dvajs/dva#2282]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi`, select `app`, choose `dva`, then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Dva Version**:
- **Node Version**:
- **Platform**:

**Comment by lindazhang102** [comment]
maybe you meet permission error. you can try  ` sudo npm install dva-cli -g `
