### ISSUE TITLE
ts使用修饰符connect组件的时候，组件放props VsCode报错。 怎么编写Props类型呢

### ISSUE THREAD

**Issue by greenking19** [dvajs/dva#2285]
## What happens?

这个是我connect了一个自己写的组件
![微信截图_20200225042004](https://user-images.githubusercontent.com/43332372/75188061-6fbb4700-5786-11ea-9a4d-4ad3e38fd8a5.png)
然后我在父组件想传Props的时候vscode 报Props错误
![微信截图_20200225042419](https://user-images.githubusercontent.com/43332372/75188239-bc068700-5786-11ea-83cc-054063344e07.png)
请问怎么写这个props接口属性呢，我不知道在哪里写 急急急

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，选择 `app`，然后选上 `dva`，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本*2.13.3*：
- **Node 版本*v12.13.1*：
- **操作系统*win10*：

**Comment by exvu** [comment]
我也是，只要升级2.6就会这样，是定义文件变动了
