### ISSUE TITLE
在typescript中，dispatch返回的数据类型为传入参数的类型，如何改变？

### ISSUE THREAD

**Issue by DougFlands** [dvajs/dva#2288]
## What happens?
需求: 在view层对返回的数据做处理，个人觉得不应将大量业务逻辑存放于model - effects 中

图一: 自动填充了dispatch传参的类型
![](https://s2.ax1x.com/2020/03/03/34cbAH.png)
图二: 声明类型则提示类型不符
![](https://s2.ax1x.com/2020/03/03/34cqNd.png)

目前只能声明any解决，有更好的解决方式吗？

## 相关环境信息

- **Umi 版本**：^2.13.0
- **Dva 版本**：^2.6.0-beta.16
- **Node 版本**：12+
- **操作系统**：win10

**Comment by dlt1111** [comment]
有同样疑问，怎么解决的？
