### ISSUE TITLE
react16 React.forwardRef() 包装的组件如何 connect

### ISSUE THREAD

**Issue by calmcth** [dvajs/dva#2289]
const Child = (props,ref) => {   
    // 接收父组件的传值
     const { params1,params2,handlerClick} = props;
     const childRef = useRef();
    // 暴露的子组件方法，给父组件调用
    useImperativeHandle(ref,() => {
         return {
            _childFn() {
                // something….
            }
        }
    })
    // handlerClick子组件调用父组件方法
     return <div 
        ref={childRef} onClick={handlerClick}>
        </div>
}

const Table = connect(mapStateToProps, mapDispatchToProps)(React.forwardRef(Child))
这样报错

**Comment by long-zhuge** [comment]
升级dva版本，目前我所使用的版本 `2.6.0-beta.14`
Hooks组件可以使用 useSelector 方法来获取 model 数据，如：
```
import { useSelector, useDispatch } from 'dva';

const Child = (props,ref) => {
    const dispatch = useDispatch();
    const { data } = useSelector((state) => state.global);
    // you code
}
```

**Comment by liuxiaoy** [comment]
最近刚好用过
```
1.
ref = React.createRef<Xxx>();

2.
 <Xxx ref={this.ref}  />

3.
export default connect(
  mapStateToProps,
  null,
  null,
  { forwardRef: true }
)(React.forwardRef(Xxx));
```
