### ISSUE TITLE
dva开发请教

### ISSUE THREAD

**Issue by Nokecy** [dvajs/dva#229]
在做后台管理项目时 ，会有大量重复逻辑的页面，只是数据源不同，比如：

>  用户列表
>  客户列表

上述两个页面可能只有Table的列不同和数据源不同其他逻辑一致。这样会导致model里面有很多重复的逻辑。这样的页面可能会有无数个 ，请问这样有什么好的办法解决吗？

**Comment by lincenying** [comment]
models 里多写几个路由判断就好了.

**Comment by sorrycc** [comment]
可以通过高阶函数的方式，比如定义 `createTableModel` 方法封装公用逻辑，通过 opts 进行配置：

```js
app.model(createTableModel(opts));
```
