### ISSUE TITLE
Hooks时代dva会继续更新维护吗，往哪个方向走

### ISSUE THREAD

**Issue by eeBryant** [dvajs/dva#2294]

**Comment by K68** [comment]
犀利的问题。
dva 跟 RN 的结合示范有些过时了，最近新项目用 RN 选型也接触了 hooks，用 rxjs + hooks 封装一个简易的数据和事件层给同事用，还挺方便的。
回到数据中台类的项目，dva 、umi、ant-design 目前还是首选。

**Comment by chenyangyang123** [comment]
在自定义hook中怎么使用model中定义的数据?
