### ISSUE TITLE
如何取消ClassName的Hash?

### ISSUE THREAD

**Issue by cnahliu** [dvajs/dva#230]
在自己的项目使用了Ant Design，不过需要把一些样式要覆盖掉，但是发现在dva项目书写的ClassName都被加上Hash值，避免冲突时解决了，但却给样式覆盖带了麻烦。

**Comment by sorrycc** [comment]
删除 `webpack.config.js` 中的以下部分：
https://github.com/dvajs/dva-cli/blob/1a4cb33/boilerplates/app/webpack.config.js#L21-L38

**Comment by cnahliu** [comment]
嗯，这样会把所有的Hash取消掉，新项目可以这样搞，因为已经写的比较多了，所以采用的是这种方式
@import "./base.less";
:global(.ant-table-pagination){
    margin: 16px 30px;
    float: right;
    >li{
        border-radius: @base-border-radius;
    }
}
