### ISSUE TITLE
require("history").createHashHistory  的问题

### ISSUE THREAD

**Issue by running-snail-sfs** [dvajs/dva#2301]
建议尽快修复呢
index.js:2177 Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release

**Comment by mikexfreeze** [comment]
https://github.com/dvajs/dva/issues/2035 
问题不修复，就直接关掉，都TM什么骚操作，我以后再用阿里的东西我TM就是SB。

**Comment by janyin** [comment]
`var _createHashHistory = _interopRequireDefault(require("history").createHashHistory);
`
一行代码
