### ISSUE TITLE
Translate docs to English

### ISSUE THREAD

**Issue by cddumanov** [dvajs/dva#2306]
Translate docs to English. It's impossible to learn.

**Comment by AmirHosseinKarimi** [comment]
Please do this dear developer and maintainer.

**Comment by bravoeguizabal** [comment]
Any chance to include this in the product roadmap?

**Comment by klementtan** [comment]
I would like to start working on this feature. Is there anyone working on it now?

**Comment by AmirHosseinKarimi** [comment]
@klementtan We'll be happy if you do it. Thank you!
