### ISSUE TITLE
推荐打包文件使用hash命名

### ISSUE THREAD

**Issue by xialvjun** [dvajs/dva#231]
如题，而且打包后的文件直接注入index.html，不需要人手动修改index.html，且index.html设置无缓存标签。

我目前的是：
```
output: {
  filename: '[name].[chunkhash:8].js'
},
plugins: [
  new ExtractTextPlugin('[name].[contenthash:8].css', { allChunks: true }),
  new HtmlWebpackPlugin({ template: path.resolve('src', 'index.html') }),
]

// index.html  无缓存
<meta http-equiv="expires" content="0">
```

另外希望，只要vendor没变，那每次打包得到的vendor.[hash].js 中的 hash 不变。。。

**Comment by xialvjun** [comment]
另外，希望使用 react-router v4，而不是 v2.。。。 v4 里有个 Match 组件非常好用。。

**Comment by sorrycc** [comment]
路由会考虑升级到 react-router v3，但不会直接到 v4，v4 是 beta 版。另外下个版本 dva 1.2 的路由会和路由解绑。

**Comment by sorrycc** [comment]
前面打包的需求直接查 webpack 文档吧，和 dva 无关。
