### ISSUE TITLE
example中的with-nextjs，如果在page下添加_document.js会报错

### ISSUE THREAD

**Issue by gongfuxiaocai** [dvajs/dva#2314]
代码如下：
![image](https://user-images.githubusercontent.com/20085964/78751429-cbdbd280-79a4-11ea-8051-504899ea9fda.png)

跑的时候会报如下错误：
![image](https://user-images.githubusercontent.com/20085964/78751312-8d461800-79a4-11ea-8737-316e3cc1e22c.png)
希望帮忙看下

**Comment by Hypocrisy-Cc** [comment]
那个demo在现在版本nextjs上已经不能用了 而且就算修改也不支持现在的ssg模式打包 望更新
