### ISSUE TITLE
不觉得 */yield 很难用吗？不打算支持一下async/await?

### ISSUE THREAD

**Issue by AspenLuoQiang** [dvajs/dva#2315]

**Comment by wellenzhong** [comment]
[https://github.com/dvajs/dva/issues/1919](url)

**Comment by rex-mark** [comment]
整个工程都用async await。。。就这突然出来个generator，你们不难受吗？没人要求飞机会飞上天，它怎么上天了。

**Comment by guyue88** [comment]
> 

看不懂你在怼什么，你觉得好用你就用呗，你觉得不好用，就别用，不用在我的建议下怼我！
