### ISSUE TITLE
[Feature Request] 2.4.1升2.6.0有什么注意事项么

### ISSUE THREAD

**Issue by victorWuxz** [dvajs/dva#2316]
2.4.1升2.6.0有什么注意事项么
目前我们项目umi版本是2.10.6,dva版本是2.4.1
2.4.1没有dva-immer,也没有一些自定义hooks，我们想升级到2.6，有什么注意事项么

**Comment by linesh-simplicity** [comment]
我这边遇到一个问题是2.4.1以前redux里的`routing.location`到了2.6版本以后变成了`router.location`。这种非兼容式的升级感觉对用户不是很友好。
