### ISSUE TITLE
build的时候package.json的homepage字段无效，不知该如何处理呢

### ISSUE THREAD

**Issue by x19990416** [dvajs/dva#2318]
build的时候package.json的homepage字段无效
![图片](https://user-images.githubusercontent.com/9440757/79296903-48276600-7f0f-11ea-961c-5e33a2e0f85f.png)
![图片](https://user-images.githubusercontent.com/9440757/79296910-4e1d4700-7f0f-11ea-956d-9fef520f4cbe.png)

**Comment by x19990416** [comment]
![图片](https://user-images.githubusercontent.com/9440757/79296939-5e352680-7f0f-11ea-9e8c-19dea83c6438.png)

**Comment by x19990416** [comment]
![图片](https://user-images.githubusercontent.com/9440757/79296959-68572500-7f0f-11ea-9c30-cb287cade2d9.png)

**Comment by sorrycc** [comment]
这是你自己的项目吧，删掉不就好了？

**Comment by sorrycc** [comment]
homepage 字段是拿来干嘛的？好像没有这个配置。

**Comment by x19990416** [comment]
package.json 有一个 homepage字段 用来设置应用的根路径，我们的项目打包后是要运行在一个域名之下的，有时候可能是运行在跟域名下，也有可能运行在某个子域名下或或域名的某个目录下，这时候我们就需要让我们的应用知道去哪里加载资源，这时候就需要我们设置一个跟路径，而且有时候我们的资源会部署在 CDN 上，你必须告诉打包工具你的CDN地址是什么。
@sorrycc

**Comment by bonniePxx** [comment]
> package.json 有一个 homepage字段 用来设置应用的根路径，我们的项目打包后是要运行在一个域名之下的，有时候可能是运行在跟域名下，也有可能运行在某个子域名下或或域名的某个目录下，这时候我们就需要让我们的应用知道去哪里加载资源，这时候就需要我们设置一个跟路径，而且有时候我们的资源会部署在 CDN 上，你必须告诉打包工具你的CDN地址是什么。
> @sorrycc

这个怎么解决的呀
