### ISSUE TITLE
请问如何终止程序 或 exit？

### ISSUE THREAD

**Issue by xjdata** [dvajs/dva#232]
我有几个model a/b/c/d  每一个中 我都使用了。`subscriptions： setup` 打印一句话 `console.log('model xxx setup');`

```
app.model(require('./models/a'));
app.model(require('./models/b'));
app.model(require('./models/c'));
app.model(require('./models/d'));
```

之后我在 model b 中 抛出了一个异常。
```
throw new Error('is error');
```

这个时候 无论我是否有使用onError事件监听,程序都是可以运行完毕的。 
就是说 我的console.log 里 依然是
```
model a setup
model b setup
//如果加了onerror 那会多下面这句
//Error: [object Object](…)
// 如何实现 这里抛出异常 程序就终止呢？
model c setup
model d setup
```
请问如何做到 b 中抛出异常之后的所有代码 都不会在继续执行呢？ app只有app.start(). 
前端菜鸟还请各位指导。多谢。

**Comment by sorrycc** [comment]
model 注册时理论上不会出错，不知这个需求是在什么场景下需要? 另外，`onError` 只捕获 `effect` 和 `subscription` 的报错。
