### ISSUE TITLE
在runtime时dva 实例如何获取？

### ISSUE THREAD

**Issue by jockey100332** [dvajs/dva#2323]
我使用的umi集成的qiankun插件，在app.js中有异步请求，我需要将请求来的数据进行存储，但是因为app.js 不是组件，所以没有办法拿到dispatch，请问我如何存储比较合适？或者如何才能拿到该实例？

**Comment by jimtang9527** [comment]
+1

**Comment by jimtang9527** [comment]
我的使用场景是微信小程序。此前使用的是subscriptions接受来自服务器端的消息推送。小程序存在自动中断的情况。这个方案存在不稳定性。我的解决方式是这样的。

在app.js创建dva的时候

`const store = dvaApp.getStore()`
`global.gStore = store`

然后在非页面处这样使用，可以达到预期

`global.gStore.dispatch(type:'xxxx',payload:xxxx)`

**Comment by jockey100332** [comment]
> 我的使用场景是微信小程序。此前使用的是subscriptions接受来自服务器端的消息推送。小程序存在自动中断的情况。这个方案存在不稳定性。我的解决方式是这样的。
> 
> 在app.js创建dva的时候
> 
> `const store = dvaApp.getStore()`
> `global.gStore = store`
> 
> 然后在非页面处这样使用，可以达到预期
> 
> `global.gStore.dispatch(type:'xxxx',payload:xxxx)`
我的是umi集成的dva，在runtime 的时候是拿不到实例的，这种相当于在runtime 的时候对dva的创建确实是可以
