### ISSUE TITLE
[Feature Request] Dva 3 会是怎么样的

### ISSUE THREAD

**Issue by ifibercc** [dvajs/dva#2324]
会有 Dva 3 嘛?
Dva 3 什么时候出?
Dva 3 会是怎样的?

**Comment by xc1427** [comment]
@sorrycc 来回答一下 ？

肯定要完美支持 ts。immer 默认。升级到 redux-saga 1.x。

我认为不应该再有 reducer 和 subscription，因为 dva -core 合理定位应该是 redux-saga 的更好的封装，redux 只是 redux-saga 的底层支持，不应该把 redux 的没必要的概念暴露出来。在 hooks 大行其道的前提下，subscription 的能力也基本被覆盖了。

保留 effects ，watcher 变为一等公民。因为 effect/watchers 代表了 redux-saga 的两种 API 模式：push & pull。

```
const model:Model<{ foo?: { bar: string[] } }> = {
  namespace,
  state: {},
  effects: {
    //..
  }
 watchers: {
   watcher1: [function*() {}, { type: 'trivial' }],
   watcher2: [function*() {}, { type: 'action', (s) => {s.titi?.toto} }],
  }
}
```

**Comment by cike8899** [comment]
什么时候发正式版？在线等

**Comment by cike8899** [comment]
什么时候发正式版？在线等
