### ISSUE TITLE
dva用BrowserRouter时候页面加载完后url有个#号，不符合BrowserRouter行为

### ISSUE THREAD

**Issue by m430** [dvajs/dva#2328]
## What happens?

dva用BrowserRouter时候页面加载完后url有个#号，不符合BrowserRouter行为，用ReactDOM.render去渲染路由的话没有这个问题，但是用dva加载路由后，用app.start('selector')的方式会出现这个问题，路由跳转过程中没问题，但是随便一个页面刷新一下，原来的url后面会出现#/

## Mini Showcase Repository(REQUIRED)

[https://codesandbox.io/s/dva-url-bug-9zwdq](https://codesandbox.io/s/dva-url-bug-9zwdq)

## Context

- **Dva Version**: 2.4.1
- **Node Version**: 12.10.0
- **Platform**: macos

**Comment by wuyanan** [comment]
这个解决了吗？

**Comment by m430** [comment]
@wuyanan 没有，这项目感觉没人维护了一样

**Comment by ZY2071** [comment]
@m430 给的链接没能复现，确定已经按此配置 https://dvajs.com/knowledgemap/#%E5%88%87%E6%8D%A2-history-%E4%B8%BA-browserhistory
