### ISSUE TITLE
生成一个全新的组件被重复渲染的问题

### ISSUE THREAD

**Issue by huang6349** [dvajs/dva#233]
大神，我在进行开发的时候，做了一个弹出层添加的功能，我将弹出层的显示和隐藏交给model管理，但是现在的需求是，弹出层显示后再去获取下拉菜单中的数据，获取数据就改变了model的值，这样组件就会被重新渲染，然而弹出层包含了表单，我就将弹出层包在一个函数中这样每次都会生成一个新的弹出层。
现在的问题就是model的值一旦发生了改变弹出层就会重新浮现一次

**Comment by sorrycc** [comment]
弹层为啥要包在函数中? @nikogu 好像也有遇到这个问题?

**Comment by huang6349** [comment]
不包含在函数中这个弹出层表单中的值需要每次关闭后重置，关键是，点击保存提交，这是一个异步的操作，我不能确定什么时候清空表单的值，

**Comment by huang6349** [comment]
我实现这个功能方式类似你在user-dashboard中实现Users弹出层添加功能那样，但是我多了一个步骤就是打开弹出层后需要去API中加载SELECT中的值，请求完成会改变model中的值，这样组件就会被重新渲染了，弹出层就会重新浮现一次

**Comment by denzw** [comment]
为什么不把数据都准备好再显示这个弹出层？可以将数据都拉取了再传给组件呀

**Comment by huang6349** [comment]
因为我这是一张表的树形结构数据，每次添加的下拉列表框中的数据丢需要是最新的实时的，所以每次打开都需要获取数据，我想了一下，我可能要为这个功能专门写一个effects来实现这个功能，把数据一一获取好再打开弹出层

**Comment by huang6349** [comment]
我的想法很美好，

我在effects中添加了一个叫做OPEN_SAVE_MODAL的方法

```
    'OPEN_SAVE_MODAL': function* ({ payload }, { select, call, put }) {
      yield put({ type: 'course_str/FIND_ALL', payload: {} });
      yield put({ type: 'FIND_ALL', payload: {} });
      yield put({ type: 'SHOW_SAVE_MODAL', payload: {} });
    },
```

但是最终的结果仍然是先弹出model,然后加载下拉菜单的数据的时候出一行数据弹出层再浮现一次

**Comment by huang6349** [comment]
我将这个方法改了一下，最后的结果确实是实现了，加载数据完成后再打开弹出层

```
    'OPEN_SAVE_MODAL': function* ({ payload }, { select, call, put }) {
      yield put({ type: 'course_str/UPDATE_STATE', payload: { lists: [] } });
      const loading1 = message.loading('课程大纲正在加载中，请稍等片刻...', 0);
      const list1 = yield call(query, '/test/course_str');
      loading1();
      if (list1) {
        yield put({
          type: 'course_str/UPDATE_STATE',
          payload: {
            lists: list1,
          },
        });
      }
      yield put({ type: 'UPDATE_STATE', payload: { lists: [] } });
      const loading2 = message.loading('课程分类正在加载中，请稍等片刻...', 0);
      const list2 = yield call(query, '/test/course_type');
      loading2();
      if (list2) {
        yield put({
          type: 'UPDATE_STATE',
          payload: {
            lists: list2,
          },
        });
      }
      yield put({ type: 'SHOW_SAVE_MODAL', payload: {} });
    },
```

如果是这样，那么是不是说在effects中的yield并不会等effects和reducers中的方法执行完成后再向下执行，而是只会等待call方法执行完成才会向下执行呢？

**Comment by sorrycc** [comment]
是的，只有 `call` 会等待异步完成。

**Comment by hanagm** [comment]
@huang6349  如果提交的时候按钮loading，等服务端数据返回成功后再隐藏modal， 我现在会出现 #349 
问题，你是如何解决的？
