### ISSUE TITLE
[Feature Request] 2.6 正式版何时发布？

### ISSUE THREAD

**Issue by whinc** [dvajs/dva#2333]
dva@2.6.0-beta.19 依然是 2019.11月发布的，现在已经 2020.5月了，请问2.6版本正式版什么时候发布？

**Comment by chimisu** [comment]
同问

**Comment by cike8899** [comment]
同问

**Comment by xc1427** [comment]
应该会在下半年直接 dva 3.0。

hook 和 dva 并没有任何冲突之处。

**Comment by cike8899** [comment]
> 应该会在下半年直接 dva 3.0。
> 
> hook 和 dva 并没有任何冲突之处。

即将到下半年了，应该有点动作了，项目没有roadmap吗？

**Comment by peng20017** [comment]
期待3.0
