### ISSUE TITLE
how to use dispatch without connect?

### ISSUE THREAD

**Issue by 510846** [dvajs/dva#2335]
https://dvajs.com/guide/introduce-class.html#dispatch-%E6%96%B9%E6%B3%95
dispatch 方法从哪里来？被 connect 的 Component 会自动在 props 中拥有 dispatch 方法。

—— 就如文档中说的，dispatch 从 connect 的组件 props 来，但如果这个 Component 不使用 connect 呢？又该如何使用 dispatch？

**Comment by Cheng007** [comment]
同问，我的使用场景是在普通JS中要调用dispatch修改state，而不是在React的组件中使用，不知道有没有处理办法？

**Comment by zjxpcyc** [comment]
从 store 中可以拿到

**Comment by Johnjiang2016** [comment]
> 从 store 中可以拿到
老哥，具体怎么用到可以贴下代码么，thks

**Comment by Johnjiang2016** [comment]
> 同问，我的使用场景是在普通JS中要调用dispatch修改state，而不是在React的组件中使用，不知道有没有处理办法？

我最近也碰到类似问题

**Comment by Johnjiang2016** [comment]
> 从 store 中可以拿到

老哥，具体怎么用到可以贴下代码么，thks

**Comment by zjxpcyc** [comment]
@Johnjiang2016 你看下你的项目直接 `window.g_app._store` 有没有。如果没有。在你  `createApp` 的地方设置 `window.g_app = app` 。这样你就能全局用了

**Comment by dongkun** [comment]
1. 参数传入；
2. hooks -> useReducer；
