### ISSUE TITLE
dva 跨model的通信失败

### ISSUE THREAD

**Issue by aiyuchen** [dvajs/dva#2336]
## What happens?
参考官方文档https://dvajs.com/guide/develop-complex-spa.html#%E8%B7%A8model%E7%9A%84%E9%80%9A%E4%BF%A1
当在`effects`方法中使用`call`通信会提示参数类型错误
```
yield call({ type: 'b/foo' });
```

报错信息说参数objct不是function，但是官网文档说明文档的确传的是object
![21590744691_ pic_hd](https://user-images.githubusercontent.com/578141/83244777-5df89e00-a1d2-11ea-970a-9ff2fe9df2a0.jpg)

> uncaught at check call: argument [object Object] is not a function 

## Mini Showcase Repository(REQUIRED)
演示链接：https://codesandbox.io/s/agitated-cache-141vs?fontsize=14&hidenavigation=1&theme=dark

<img width="1465" alt="WX20200529-172617@2x" src="https://user-images.githubusercontent.com/578141/83244159-89c75400-a1d1-11ea-8874-bfcff86daeb6.png">

## Context

- **Dva Version**: 2.4.1
- **Node Version**:
- **Platform**: codesandbox

**Comment by xiaosongxiaosong** [comment]
文档有点问题，具体可以看 react-saga 的文档，dva 是没有修改这些接口的属性的

**Comment by dongkun** [comment]
文档有误，跨model通讯使用`put`，而不是`call`
````
 effects: {
    * foo(_, { put }) {
      yield put({ type: "b/foo" });
    }
  }
````

**Comment by iversonwool** [comment]
> 文档有误，跨model通讯使用`put`，而不是`call`
> 
> ```
>  effects: {
>     * foo(_, { put }) {
>       yield put({ type: "b/foo" });
>     }
>   }
> ```

老哥正解
