### ISSUE TITLE
require("history/createHashHistory")报错

### ISSUE THREAD

**Issue by fengzhenfz** [dvajs/dva#2337]
## What happens?
使用dva组建，运行umijs
控制台报错
Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.

## 相关环境信息

- **Umi 版本**：3.2.2
- **Node 版本**：14.3.0
- **操作系统**：macOS

**Comment by tsinglemon** [comment]
我也遇到同样问题了，请问解决了吗？

**Comment by dongkun** [comment]
````
import { createBrowserHistory } from 'history';
const history = createBrowserHistory();
const app = dva({
  history,
});
````

**Comment by fengzhenfz** [comment]
> 我也遇到同样问题了，请问解决了吗？

我是在使用umijs遇到的问题，目前将需要dva包该用从umi上获取就没有问题了

**Comment by tsinglemon** [comment]
> > 我也遇到同样问题了，请问解决了吗？
> 
> 我是在使用umijs遇到的问题，目前将需要dva包该用从umi上获取就没有问题了

好的，谢谢！

**Comment by willdreame** [comment]
有比较的好的解决方法？

**Comment by fengzhenfz** [comment]
因为项目是要发布到远端node环境，不再本地打包，所以修改包中的代码就没有意义；如果本地打包的项目，可以到node_modules下dva包下的lib下的index.js中，将require("history/createHashHistory")改成require("history").createHashHistory或者其他语法形式

**Comment by fengzhenfz** [comment]
还是希望官方经dva包的错误解决，这样大家开发也方便

**Comment by LOVEwitch** [comment]
同求解决

**Comment by smithyj** [comment]
```
npm i --save @smithyj/dva@2.4.2
```
我修复了这问题并发了一个包，该包基于 `dva@2.4.1` 进行修复，需要增加 webpack alias 配置
```
{
    alias: {
        dva: "@smithyj/dva"
    }
}
```
