### ISSUE TITLE
Poll effects can't be called by "yield put" in models

### ISSUE THREAD

**Issue by EGBAR** [dvajs/dva#2348]
## What happens?
effects 里面实现了一个poll， 在组件中使用dispatch 可以调用成功， 但是在models里面使用 put 无法调用其它 poll的effects

**Comment by EGBAR** [comment]
补充：
原因是put是非阻塞的， 所以调用不成功， 可以在
yield put({
  type:'actionName-start'
})
后面加上
yield take({
  type:'actionName-start/@@start'
})
来阻塞调用。

但是这样引入了一个新的问题， 就是take始终不会返回， take后面的代码始终无法执行。

**Comment by EGBAR** [comment]
发现问题是当要调用的poll effects和写put的effects在同一个model里面的时候会发生这个问题。 
如果分别实现在两个model里面的话，put是可以正常调用的。

**Comment by dongkun** [comment]
effects 和 reducer 里面的 api 同名了？
