### ISSUE TITLE
dispatch 接受数组，同时触发多个reducer或者effect

### ISSUE THREAD

**Issue by yangjiedage** [dvajs/dva#2359]
## 背景
有的时候业务比较复杂，会dispatch多个reducer或者effect，但是dva的dispatch只支持object，没有办法dispatch 数组。这个时候只能多次调用dispatch。
## 比如说
- dispatch两个reducer，现在是这样
```
dispatch({
  type: 'user/set'
})
dispatch({
  type: 'order/test'
})
```
- 期望可以这样
```
dispatch([{
  type: 'user/set'
}, {
  type: 'order/test'
}])
```
让dispatch接受数组，这样感觉写起来优美一点，当dispatch很多个的时候。

**Comment by EEETA** [comment]
也遇到相关问题，目前我这边是通过promise.all处理。网上还有一种说法是使用redux-thunk做中间件。如果action调的是effects异步请求多个接口也可以试试 yield all([call(api1), call(api2), ...api]) 这种
