### ISSUE TITLE
subscriptions监听,然后effects里面路由跳转

### ISSUE THREAD

**Issue by ah-kevin** [dvajs/dva#236]
在subscriptions里面监听了 路由变化 检测登陆状态 ,然后effects里面用   yield put(routerRedux.push('/home'))路由跳转 ,多次触发 - -push...但换成hashhashHistory 没有问题

**Comment by sorrycc** [comment]
subscriptions 监听了要判断 pathname 的，参考 https://github.com/sorrycc/dva-tutorial/blob/5f48e34/src/models/posts.js#L41-L53
