### ISSUE TITLE
为什么reducers中取到的state是一个空的proxy呢？

### ISSUE THREAD

**Issue by ShellyWang94** [dvajs/dva#2360]
### 代码
```
state: {
    tableList: ['1', '2', '3'],
    count: 0
  },
  effects: {
  },
  reducers: {
    add(state) { 
      console.log(state); 
      return {
        ...state,
        count: state.count + 1
      }
    },
  }
```
### 结果： 
打印出：
`Proxy {scope: ImmerScope, modified: false, finalized: false, assigned: {…}, parent: undefined, …}
[[Handler]]: null
[[Target]]: null
[[IsRevoked]]: true
`
### 疑问：
1. 为什么state是一个proxy，可以详细解释一下么？
2. 为什么也必须执行手动合并（return部分）？手动合并state原来的部分如何如何取到呢？
3. 参数state加类型定义是不是直接用proxy定义吗
## 相关环境信息

- **Umi 版本**："umi": "^3.1.2",
- **Node 版本**：v12.13.1
- **操作系统**：mac

**Comment by harshithmullapudi** [comment]
您找到任何解决办法了吗？

**Comment by linlinNB** [comment]
@ShellyWang94 @harshithmullapudi 请把.umi.ts配置文件中的dva的hmr设置成为false即可解决问题，默认在umi中这个是开启的，配合hooks设置的

**Comment by Rooike-Q** [comment]
Do you know the answer? I have the same question...
