### ISSUE TITLE
第三级路由切换，会导致挂载该第三级路由的 二级路由组件重新进componentDidmount

### ISSUE THREAD

**Issue by CcXxWw112233** [dvajs/dva#2361]
//路由配置router.js     hash模式
`
const routes = [
  path: '/a',
  component:()=> import('./routes/A.js'),
  ...
]
`
`
<Router history={history}>
`
`
        <Switch>
`
`
          {
`
`
            routes.map(({ path, ...dynamics }, key) => {
`
`
              return (
`
`
                <Route 
`
`
                   path={path}
`
`
                   component={dynamic({
`
`
                     ...dynamics,
`
`
                   })}
`
`
                />
`
`
              )
`
`
            })
`
`
          }
`
`
       </Switch>
`
`
 </Router>
`

//A.js  组件
`const routes = [
   path: '/a/achild',
   component:()=> import('./routes/AChild.js'),
    ...
]`

`<div>
`
` {`
` routes.map(({ path, ...dynamics }, key) => {
`
`
         return (
`
`
              <Route
`
`
                      path={path}
`
`
                      component={dynamic({
`
`
                        ...dynamics,
`
`
                      })}
`
`
                    />
`
`
                )
`
`
       })
`
`
   }
`
`</div>
`

//Achild.js 组件
` <div>`
 

> `<Route path="/a/achild/agrandson_1" component={AGgrandson} />`

> ` <Route path="/a/achild/agrandson_2" component={BGgrandson} />`

` </div>`

页面结构如上，在‘#/a/achild/agrandson_1’路径下，当在 AGgrandson组件中，用routerRedux.push('/a/achild/agrandson_2')切换路由时, A组件不会重新componentDidMount ，但AChild组件会重新进入componentDidMount ，如何能让AChild不会重新进入componentDidMount

**Comment by ayiaq1** [comment]
我是在入口做了判断：
``` 
 shouldComponentUpdate(nextProps) {
    // 处理切换头部大菜单的时候，返回被unmount、mount问题
    const {
      location: { pathname },
    } = this.props;
    return nextProps?.location?.pathname !== pathname;
  }
```
