### ISSUE TITLE
官网 dvajs.com 域名正在出售？无法访问了呢。。。

### ISSUE THREAD

**Issue by 1402848990** [dvajs/dva#2364]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，选择 `app`，然后选上 `dva`，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
续费了，等更新。
