### ISSUE TITLE
两个model 的交互问题

### ISSUE THREAD

**Issue by DWNEWS-jixiaohong** [dvajs/dva#2366]
dva当中 我有两个model

A: user model , fetch user 信息, 初始state 是 userInfo，

B: page model , 根据Amodel de 用户信息 获取 页面内容，

但是在 B model 里 通过select 获取的 都是A初始state
const { userInfo } = yield select((state) => state.userInfo);

怎么在B里面获取A里面fetch的结果呀

**Comment by UlyC** [comment]
> dva当中 我有两个model
> 
> A: user model , fetch user 信息, 初始state 是 userInfo，
> 
> B: page model , 根据Amodel de 用户信息 获取 页面内容，
> 
> 但是在 B model 里 通过select 获取的 都是A初始state
> const { userInfo } = yield select((state) => state.userInfo);
> 
> 怎么在B里面获取A里面fetch的结果呀

A fetch的结果你用`reducers`存了吗？
还有 B取A的时候加上`namespace`试试呢
```js
const { userInfo } = yield select((state) => state.A.userInfo);

**Comment by DWNEWS-jixiaohong** [comment]
> A fetch的结果你用`reducers`存了吗？
> 还有 B取A的时候加上`namespace`试试呢
> 
> ```js
> const { userInfo } = yield select((state) => state.A.userInfo);
> ```
存了reducers，也用了 state.A.userInfo  但是 还是拿不到，
现在还是先执行的B的请求 然后才执行的A的请求，导致初始化的时候老是有问题
