### ISSUE TITLE
ui 重用共用一个model

### ISSUE THREAD

**Issue by hujialianghuwei** [dvajs/dva#2367]
问题如下：
从商品列表进入到详情A(详情里面也有相似商品列表),详情A又进入到详情B，他们共用一个model，当页面返回的时候详情A的数据
还是详情B的 。这种情况怎么解决？

**Comment by EEETA** [comment]
返回的时候可重新请求页面数据覆盖或者区分Astore,Bstore，因为如果存在B->C->D->B->A这种非固定顺序，我觉得每次请求是最妥当的
