### ISSUE TITLE
使用webpack插件 webpack-bundle-analyzer

### ISSUE THREAD

**Issue by Allen-vip** [dvajs/dva#237]
这个插件是分析页面js主要构成的，会额外启动一个默认的8888端口
如果在webpack.config.js直接使用webpackConfig.plugins.push(new BundleAnalyzerPlugin()); 
则页面会空白，什么都不显示。

但是如果使用webpackConfig.plugins.push = [new BundleAnalyzerPlugin()];
这个额外启动的8888 是有效果的。。

**Comment by sorrycc** [comment]
用 `webpack-visualizer-plugin` 吧。
