### ISSUE TITLE
如何获取dispatch之后的最新state？

### ISSUE THREAD

**Issue by deyinliu** [dvajs/dva#2372]
有如下代码，此时输出是旧的key值，期望获取最新值
```
this.props.dispatch({
        type: 'doSomething',
        payload: {
          key: newValue,
        },
})
console.log(this.props.key)
```

**Comment by miaozilong** [comment]
await this.props.dispatch({
        type: 'doSomething',
        payload: {
          key: newValue,
        },
})
console.log(this.props.key)

**Comment by w602542704** [comment]
dispatch的有回调函数，那里可以
