### ISSUE TITLE
ts：useSelector中state的类型问题

### ISSUE THREAD

**Issue by okilled** [dvajs/dva#2373]
Property 'loading' does not exist on type 'DefaultRootState'.ts(2339)

这里的state类型该如何处理

<img width="933" alt="图片" src="https://user-images.githubusercontent.com/23131376/91943259-e1281380-ed2e-11ea-8803-90362509e9e7.png">

**Comment by xj-m** [comment]
+ 1

**Comment by xgenem** [comment]
+1
