### ISSUE TITLE
effects 方法 throw Error  之后dispatch 完全失效， debug进去 subscribers 变为空?

### ISSUE THREAD

**Issue by xingyuzhe** [dvajs/dva#238]
触发effects里的函数a后， 如果函数a内部throw Error， 再次 dispatch 就无法进入函数a了

**Comment by sorrycc** [comment]
这个问题好像测过没问题的，迟点我再测下看。

**Comment by sorrycc** [comment]
试过没有问题，用例：https://github.com/dvajs/dva/blob/9f76294/test/effects-test.js#L105-L136
