### ISSUE TITLE
引用fetch时typescript警告

### ISSUE THREAD

**Issue by tomwang1013** [dvajs/dva#2383]
## 复现步骤：
```
yarn create @umijs/umi-app
```
然后引用fetch：
```
import { fetch } from 'dva';

await fetch(...)
```
使用fetch时typescript发生警告：
![image](https://user-images.githubusercontent.com/1826003/95572195-30631180-0a5c-11eb-93da-ac3a5880b470.png)

**Comment by UnicornXU** [comment]
同遇到
