### ISSUE TITLE
history路由的问题

### ISSUE THREAD

**Issue by huiye98** [dvajs/dva#2384]
## What happens?

项目启动时遇到警告信息：
Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.
![image](https://user-images.githubusercontent.com/39940860/95651349-623bad00-0b1c-11eb-8448-242049d215c3.png)

## 相关环境信息

- **Umi 版本**：未使用
- **dva版本**：2.4.1
- **Node 版本**：v12.16.1
- **操作系统**：win10

**Comment by smithyj** [comment]
```
npm i --save @smithyj/dva@2.4.2
```
我修复了这问题并发了一个包，该包基于 `dva@2.4.1` 进行修复，需要增加 webpack alias 配置
```
{
    alias: {
        dva: "@smithyj/dva"
    }
}
```
