### ISSUE TITLE
被connect包裹的子组件，父组件怎么通过ref拿到组件里的函数

### ISSUE THREAD

**Issue by cater111** [dvajs/dva#2385]
connect的第四个参数{forwardRef : true}和{withRef : true}都用了，不好使。拿到的依然是被connect包裹的组件

**Comment by luxiaowu** [comment]
> connect的第四个参数{forwardRef : true}和{withRef : true}都用了，不好使。拿到的依然是被connect包裹的组件

connect 的第四个参数使用 `{withRef: true} `后，获取到的 ref 对象包含一个 `current.wrappedInstance` 属性，就是被 connect 包裹的组件了 https://stackblitz.com/edit/dva-example-count-5yvkmz
