### ISSUE TITLE
dva无法在js工具里获取的实时共享状态，mobx可以，I was angry！

### ISSUE THREAD

**Issue by w602542704** [dvajs/dva#2389]
dva作为一个状态管理工具，不能在js里很方便获取到共享状态数据很不理解，导致我只能在组件那里获取数据，因为达不到前面说的需求开发成本很高，但是mobx可以做到，刚接手项目想重写项目时间又很赶，方法和数据和监听器都只能在页面组件hooks函数里写,耦合在一起惨不忍睹，虽然可以在js工具dispatch回调里获取状态数据，但是非常不方便，难道就没有一定的页面逻辑代码解耦思想么？
**mobx 在utils.js or utils.ts or Eventlistener.js工具中获取实时数据状态**

![image](https://user-images.githubusercontent.com/24689873/96966268-14716c80-1540-11eb-83ef-103aebcb463d.png)

![image](https://user-images.githubusercontent.com/24689873/96966174-ef7cf980-153f-11eb-8fca-a2c97e83ae89.png)

**Comment by w602542704** [comment]
> dva作为一个状态管理工具，不能再js里很方便获取到共享状态数据很不理解，导致我只能再组件那里获取数据，开发成本很高，mobx可以做到，刚接手项目想重写项目时间又很敢，方法和数据和监听器都只能再组件hooks函数里写,耦合在一起惨不忍睹，虽然可以在js工具dispatch回调里获取状态数据，但是非常不方便，难道就没有一定的解耦思想么？
> **mobx 在js工具中获取实时数据状态**
> ![image](https://user-images.githubusercontent.com/24689873/96966313-2521e280-1540-11eb-9e69-c4ce2affa213.png)
> 
> ![image](https://user-images.githubusercontent.com/24689873/96966268-14716c80-1540-11eb-83ef-103aebcb463d.png)
> 
> ![image](https://user-images.githubusercontent.com/24689873/96966174-ef7cf980-153f-11eb-8fca-a2c97e83ae89.png)

**Comment by yoyo837** [comment]
你需要的应该也不是dva的所有功能，个人建议拆了dva自己封装个简单的，主要是router处理和saga那部分留下，其他看需要，因为看上去维护不是很积极。
