### ISSUE TITLE
讨论：插件机制

### ISSUE THREAD

**Issue by sorrycc** [dvajs/dva#24]
dva 提供各种 hooks，然后通过 `.use()` 来接入。使用方法：

```javascript
const app = dva();
app.use(hmr());
app.use(log());
```

hooks 列表：

- `onError`，effects 和 subscriptions 出错时触发，比如可以有个 `dva-plugin-antd-error`，用于整理处理应用的出错信息
- `onStateChange`，可以让 state 和 localStorage 或者远程的 service 建立连接
- `onAction`，等同于 redux middleware
- `onHmr`，热替换，目前支持 components 和 routes
- `extraReducers`，这个比较纠结，唯一风格不同的，不知是否有更好的命名

然后 `app.start()` 不再提供 `middlewares` 和 `reducers` 参数，这些配置本质上和 `models` 同级，而和 `start` 本身并无关系。

**Comment by sorrycc** [comment]
@ChrisFan @yiminghe @nikogu @afc163

**Comment by nikogu** [comment]
是否可以理解为 `app.use` 就是`middleware`，有一个问题是：hooks是需要额外封装的，还是直接使用redux的middleware也可以，像这样

```
import createLogger from 'redux-logger';
const logger = createLogger();

...
app.use(logger);
```

**Comment by sorrycc** [comment]
`app.use` 加载的是  hooks，其中包含 redux 的 middleware 功能 (onStateChange)。

比如，一个出错时通过 message 输出信息的插件：

```javascript
import { message } from 'antd';
function antdErrorPlugin() {
  return {
    onError: (err) => { message.error(err.message); },
  };
}
app.use(antdErrorPlugin());
```

比如 `redux-logger` 使用：

```javascript
import createLogger from 'redux-logger';
const logger = createLogger();

app.use({
  onStateChange: logger,
});
```

**Comment by ChrisFan** [comment]
onAction 做什么用的？跟 redux-middleware 不是一样的么

**Comment by afc163** [comment]
都走 redux middleware 如何？多出来那几个 onXxx 是否有必要？

**Comment by ChrisFan** [comment]
我觉得考虑插件机制，除了 middleware 之外应该考虑类似 redux-form 这种，有自己的视图跟 reducer 的，怎么样集成更方便。

**Comment by yiminghe** [comment]
应该可以很方便得使用现有redux 中间件

**Comment by sorrycc** [comment]
@afc163 

插件机制如果只考虑 redux middleware，感觉对于框架而言会不够用。我把自己想到的每个 hook 的用途在主贴更新了，然后觉得 hooks 之间配合作用应该会发挥更大的作用，比如 fetch 和 saga 的结合，可以做 `loading` state 的自动处理。

---

@ChrisFan 前面说错了，onAction 才是对应 redux 的 middleware 。

---

@yiminghe Redux 中间件使用感觉已经挺简单了，其他建议? 

例子：

```javascript
import createLogger from 'redux-logger';
app.use({
  onAction: createLogger(),
});
```

支持数组：

```javascript
app.use({
  onAction: [m1, m2],
});

**Comment by sorrycc** [comment]
@ChrisFan redux-form 的视图是指啥? 不是加一个 reducer 就可以了吗?

**Comment by ChrisFan** [comment]
当我没说，目前能想到的好像就一个 reducer。。  
我们这有类似 GlobalMessage 的场景，用户需要 1. 引入 reducer 2. 引入 GlobalMessage 放在根目录下
想想也没必要再封装了，这种类型的应该不多

**Comment by Menq** [comment]
主贴在哪里了？
