### ISSUE TITLE
请问什么时候Dva用typescript重构一下？

### ISSUE THREAD

**Issue by XiaRunxi** [dvajs/dva#2400]

**Comment by joker8023** [comment]
同问，Dva不用typescript，导致项目用起来有点不顺手了

**Comment by Kunduin** [comment]
试试这个 [dva-toolkit](https://github.com/Kunduin/dva-toolkit), 好用的很

**Comment by xgenem** [comment]
+1 if this would be on typescript too

**Comment by fwh1990** [comment]
用typescript重构不太现实，因为TS约束太多，代码就骚不起来了。或者像我一样自己撸一个
