### ISSUE TITLE
改造比较大的React项目，能局部接入dva吗？

### ISSUE THREAD

**Issue by taoyingsong** [dvajs/dva#2404]
## What happens?

手里有一个比较大的前端项目，技术栈为React + Redux（路由未使用react-router），能局部引入dva，然后一点点改造替换吗？
我看文档中没有相关情况的介绍，通过文档感觉dva做了挺好的封装，但是都是对整个应用来说的。

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，选择 `app`，然后选上 `dva`，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by steveleeh** [comment]
不行，dva都是全局流的，umi中做了page级别的model处理但是也很大，如果是组件级的我现在都用unstated-next(或unstated)效果还不错，基本能实现数据隔离了，

**Comment by taoyingsong** [comment]
> 不行，dva都是全局流的，umi中做了page级别的model处理但是也很大，如果是组件级的我现在都用unstated-next(或unstated)效果还不错，基本能实现数据隔离了，

感谢回答～，
我大概看了下umi， 我看文档上也是从一个整体项目的角度介绍的，局部引入比较大的项目不知道会不会有什么麻烦。
unstated-next我过了下README, 我看处理的都是同步数据，没看到异步数据处理的介绍。

dva这个项目官方是不是都不怎么维护了，issue处理的都好慢TT

**Comment by fantasticsoul** [comment]
如果想渐进式的接入，可以试试 concent哦 https://github.com/concentjs/concent
无顶层Provider，内置依赖收集，即插即用的特性让你无痛极速接入并可以局部使用起来，在逐渐全局替换
