### ISSUE TITLE
多个相同 effects ，其中一个结束，会导致 loading 值提前为 false  有解决办法吗

### ISSUE THREAD

**Issue by bobsivian** [dvajs/dva#2405]
Expected behavior: (预期的正常效果)
时间	loading值
1s	true
2s	true
3s	true
4s	false
多个相同 effects ，其中一个结束，会导致 loading 值提前为 false。
建议是全部结束，才会恢复为 false。
建议增加，计数功能。和

Actual behavior: (实际效果)
时间	loading值
1s	true
2s	true
3s	false
4s	false
Versions of packages used: (哪个库的哪个版本出现的问题)
最新版本 dva loading 库

**Comment by Madridspark** [comment]
请问怎么解决的

**Comment by chenhaomk** [comment]
使用loading.global吧

**Comment by fwh1990** [comment]
多次执行同一个effect肯定会覆盖loading，除非升级数据结构，不然无解。可以参考这个做法 https://foca-js.github.io/foca/#/advanced?id=执行状态隔离
