### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by u0x01** [dvajs/dva#242]
不论是 本地调试的时候还是build的时候都会报一个警告：
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: network timeout at: http://10.244.30.23:7001/monitor?version=0.3.2
```
但是不影响使用。

10.244.30.23 看起来是个内网地址。

能否修复下这个 Warning 以及 ```DeprecationWarning: 'GLOBAL' is deprecated, use 'global'```

**Comment by sorrycc** [comment]
1. 你是内网用户? 不是的话打开 http://ip.taobao.com/ipSearch.php ，看下运营商是啥
1. `GLOBAL` 的错误应该是依赖库的问题，在 node 6.9? 或者比较新的版本里会报

**Comment by u0x01** [comment]
1. 是内网用户
2. node 版本  6.9.1

**Comment by blog-lyn** [comment]
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: network timeout at: http://10.244.30.23:7001/monitor?version=0.3.2 


same error with  node version  6.9.1, any idea?

**Comment by DanielJyc** [comment]
我也碰到了这个问题。antd-init初始化的项目。这个是什么原因？ @sorrycc 
`56/140 build modulesatool-monitor 网络错误： { FetchError: network timeout at: http://10.244.30.23:7001/monitor?version=0.3.3`

![image](https://cloud.githubusercontent.com/assets/6802154/20524504/c2b3ce68-b0f5-11e6-96a6-d15154cfe4b7.png)

**Comment by sorrycc** [comment]
应该已经修复了。

**Comment by magicdawn** [comment]
加一下这个吧 ... 
https://nodejs.org/dist/latest-v7.x/docs/api/all.html#process_event_unhandledrejection
这个 deprecated 有点唬人, v6 还没有 ...
