### ISSUE TITLE
React.memo 和connect的包裹问题

### ISSUE THREAD

**Issue by zhaozedong** [dvajs/dva#2421]
function mapStateToProps ({ common }:{ common:CommonModelState }) {
    return { common }
}

function compare (prevProps: Readonly<PropsWithChildren<NewPeopleProps>>, nextProps:Readonly<PropsWithChildren<NewPeopleProps>>) {
    return prevProps.common.shopBasic.uid_status == nextProps.common.shopBasic.uid_status
}

export default withRouter(connect(mapStateToProps)( memo(NewPeopleModal,compare))) 

报错
Uncaught Invariant Violation: You must pass a component to the function returned by connect. Instead received {}

react17 antd-mobile2.3.4

**Comment by sin1ght** [comment]
同样的问题，版本是2.4.1
"react-redux": "5.0.7",react-redux版本被写死了，5.1修复了
