### ISSUE TITLE
sass 的支持

### ISSUE THREAD

**Issue by qdlike** [dvajs/dva#243]
请问下作者 可否给个sass 接入的案例，本人尝试了安装sass-loader 和 node-sass并在webpack配置后一直报错（不知道是不是配置错了），感谢 。

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues/84#issuecomment-256302105

**Comment by zhenxianluo** [comment]
您好,roadhog2.0.中.webpackrc文件可以配置sass,找了好久没有看到一个示例
