### ISSUE TITLE
页面刷新，状态丢失，怎么解决

### ISSUE THREAD

**Issue by lhc0229** [dvajs/dva#2432]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，选择 `app`，然后选上 `dva`，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by Big-Devils** [comment]
可以尝试放在session里

**Comment by 574495412** [comment]
这个库不是永久保存状态的

**Comment by xiaoma-FrontEnd** [comment]
我也碰到了，同样的问题，页面刷新，数据丢失，请问你是怎么解决的？

**Comment by Big-Devils** [comment]
> 我也碰到了，同样的问题，页面刷新，数据丢失，请问你是怎么解决的？

如果需要长久存储的数据比较少，可以在存储的时候在本地（storage）里存一份，如果比较多，可以使用一下长久存储的第三方库

**Comment by fwh1990** [comment]
使用 redux-persist
