### ISSUE TITLE
history

### ISSUE THREAD

**Issue by HyoukaM** [dvajs/dva#2433]
Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.

老哥这个报错看着难受呀，每次都要改lib呢

**Comment by smithyj** [comment]
```
npm i --save @smithyj/dva@2.4.2
```
我修复了这问题并发了一个包，该包基于 `dva@2.4.1` 进行修复，需要增加 webpack alias 配置
```
{
    alias: {
        dva: "@smithyj/dva"
    }
}
```
