### ISSUE TITLE
bigfish和antdpro有什么不一样？

### ISSUE THREAD

**Issue by SugarCreate** [dvajs/dva#2438]
bigfish和antdpro有什么不一样？为什么你们官方都不用antdpro 而用bigFish呢？

**Comment by chenhaomk** [comment]
antdpro只是一种前端应用的解决方案，基于antDesign沉淀出来的一套中后台应用的模板/组件等，开发者可在没有设计的情况下快速的构建一个中后台应用。bigfish功能更加强大，它是基于umi整合了前端工具的一个框架（umi将andD、dva、ts、react、webpack等等集成在一起），开发者从构建项目到上线都有完整的技术方案和相应生态系统支持，使开发者专注业务本身
