### ISSUE TITLE
不好意思，问个题外话，组件中怎么读取webpack配置或者node环境变量呢？

### ISSUE THREAD

**Issue by xjdata** [dvajs/dva#244]
搜了很多都是针对构建的，比如webpack中，现在有个env可以读取，来判断当前是开发环境还是生产环境。

但是组件中怎么判断呢？
```
//model/user.js
let a = 'dev'
if(XXXXXX)//开发环境
{
}
```

不好意思，实在搜不到答案了，才来问下。

**Comment by sorrycc** [comment]
如果你用 atool-build，可以判断 `process.env.NODE_ENV` 是否为 production。https://github.com/ant-tool/atool-build/blob/62a49ce/src/build.js#L35

**Comment by xjdata** [comment]
谢谢， 云谦， 你是我的js，es6，js开发思想的老师。
