### ISSUE TITLE
[Feature Request] useDispatch and useSelector

### ISSUE THREAD

**Issue by tai-votan** [dvajs/dva#2446]
how to using useDispatch and useSelector in repo dva with nextjs, pls help

**Comment by whoisdominic** [comment]
You use it like you normally would but I only use DVA core with regular redux

**Comment by tai-votan** [comment]
@whoisdominic I can't use it and I tried it with Dva core but error

**Comment by fernandoxu** [comment]
use redux-toolkit instead
