### ISSUE TITLE
文档太简单了

### ISSUE THREAD

**Issue by zhangxiaochunxy** [dvajs/dva#2449]
之前都是自己通过react和redux来写项目。这次接手了一个新的项目，用dva写的。感觉文档太简单了，好多问题都得自己摸坑。建议能把文档写的详细一点。

**Comment by mengbo-ji** [comment]
> 之前都是自己通过react和redux来写项目。这次接手了一个新的项目，用dva写的。感觉文档太简单了，好多问题都得自己摸坑。建议能把文档写的详细一点。

文档好多年都不更新了，淡定。

**Comment by SkyWongHZ** [comment]
毕竟kpi项目,晋升了还需要什么之前的轮子

**Comment by crsgyj** [comment]
看了一圈文档，这个东西太复杂了，本质是修改数据，视图更新，非要搞那么多概念。
react就是限制太多，state不能脱离组件，甚至不能脱离了函数。导致他的衍生框架一个比一个复杂，感觉要弃坑了

**Comment by Richard-Choooou** [comment]
> 看了一圈文档，这个东西太复杂了，本质是修改数据，视图更新，非要搞那么多概念。 react就是限制太多，state不能脱离组件，甚至不能脱离了函数。导致他的衍生框架一个比一个复杂，感觉要弃坑了

确实，写出来的代码不利于维护，接手了一个用 dva 的项目，都没法改，这个项目也就起个 dva 的名字才拉一些小白入坑，不然谁脑子有坑用这玩意，好用的状态库多了去了。

**Comment by fwh1990** [comment]
> > 看了一圈文档，这个东西太复杂了，本质是修改数据，视图更新，非要搞那么多概念。 react就是限制太多，state不能脱离组件，甚至不能脱离了函数。导致他的衍生框架一个比一个复杂，感觉要弃坑了
> 
> 确实，写出来的代码不利于维护，接手了一个用 dva 的项目，都没法改，这个项目也就起个 dva 的名字才拉一些小白入坑，不然谁脑子有坑用这玩意，好用的状态库多了去了。

antd用户量十分大，最佳实践用的就是dva。
https://ant.design/docs/react/practical-projects-cn
https://github.com/ant-design/ant-design-pro
