### ISSUE TITLE
请问什么时候会更新新版本？

### ISSUE THREAD

**Issue by tianwawawa** [dvajs/dva#2450]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by fuxianwei** [comment]
同问

**Comment by RolkerMan** [comment]
我不想再用 dva 了，对 typescript 支持很弱。
react 相关的状态管理工具有很多。例如 rematch

**Comment by SixYearsInFebruary** [comment]
@sorrycc
