### ISSUE TITLE
dva如何结合typescript使用

### ISSUE THREAD

**Issue by zhouxingting** [dvajs/dva#2462]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi`, select `app`, choose `dva`, then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Dva Version**:
- **Node Version**:
- **Platform**:

**Comment by fwh1990** [comment]
dva应该是JS first的框架。

**Comment by Big-Devils** [comment]
推荐看一下这篇文章文章 ： https://juejin.cn/post/6994371175186956319
