### ISSUE TITLE
import { useSelector } from 'dva'; is not work! 

### ISSUE THREAD

**Issue by AlonDeng** [dvajs/dva#2466]
## What happens?

無法引入 redux hook

![image](https://user-images.githubusercontent.com/42921951/132195464-c4cdaa0a-cc51-4deb-b7ee-65133cd93b53.png)

**Comment by athrunsun** [comment]
你用的是哪个版本的dva？

**Comment by juvenile-bin** [comment]
那个版本也不可以  dva没有对react-redux 升级 所以无法使用,现在useSelector,useDispatch 都在umi中集成.并没有在dva中

**Comment by juvenile-bin** [comment]
> ## What happens?
> 無法引入 redux hook
> 
> ![image](https://user-images.githubusercontent.com/42921951/132195464-c4cdaa0a-cc51-4deb-b7ee-65133cd93b53.png)

那个版本也不可以  dva没有对react-redux 升级 所以无法使用,现在useSelector,useDispatch 都在umi中集成.并没有在dva中

**Comment by athrunsun** [comment]
我用的2.6.0-beta.22，是没问题的。

**Comment by juvenile-bin** [comment]
> 我用的2.6.0-beta.22，是没问题的。

最新版本确实有但是需要provide包装组件.

**Comment by athrunsun** [comment]
> 但是需要provide包装组件
没明白你的意思，能说明一下吗？

**Comment by juvenile-bin** [comment]
> > 但是需要provide包装组件
> 
> 没明白你的意思，能说明一下吗？

我在用webpack+react+dva 使用时dva默认安装版本是没有hooks 语法的,但是我升级为最新版beta版本时.他会让我用Provide上下文包装给 react 组件. 不然是无法使用的.
![image](https://user-images.githubusercontent.com/55374776/150713627-af24e8ca-2ee2-47ef-9580-6e3bda55fe54.png)
具体请看codeSandbox:https://codesandbox.io/s/amazing-kirch-clk9b?file=/src/App.js

**Comment by juvenile-bin** [comment]
> @juvenile-bin 你的这个repo里引用的dva版本不对，而且你也并没有用到dva啊？
> 
> 就算不用dva，也需要在index.js里初始化一个redux store并加上一个`<Provider>`：
> 
> ```js
> import { Provider } from 'react-redux';
> 
> // 初始化redux store
> const store = ...
> 
> ReactDOM.render(
>   <StrictMode>
>     <Provider store={store}>
>       <App />
>     </Provider>
>   </StrictMode>,
>   rootElement
> );
> ```

是的
