### ISSUE TITLE
dynamic-load 多级路径时分离出来的js路径有问题

### ISSUE THREAD

**Issue by liurq** [dvajs/dva#247]
使用dva new filename 新生成的项目

url是二级时， 分离出来时的js路径会带上一级路径名称， 如果去掉一级路径名称，实际上是能访问到的

![problem3](https://cloud.githubusercontent.com/assets/4696576/20046941/632ed760-a4ea-11e6-94bd-1d13b0998c24.png)

![problem1](https://cloud.githubusercontent.com/assets/4696576/20046927/3def3210-a4ea-11e6-95de-0343e55fcd94.png)
![problem2](https://cloud.githubusercontent.com/assets/4696576/20046928/3df2c56a-a4ea-11e6-831a-f11fff358a0e.png)

**Comment by sorrycc** [comment]
解决了?
