### ISSUE TITLE
HELP：dispatch 第一次能进effects的事件，第二次不能进effects中的事件！

### ISSUE THREAD

**Issue by JakeQuen** [dvajs/dva#2474]
## What happens?
   当我dispatch的时候，第一次的effects事件可以触发，但是当我第二次的时候effects里的事件没有触发。

## 最小可复现仓库
jsx 文件：
const submit = () => {
  console.log("submit envents");
  dispatch({type: "namespace/effectSubmit",payload: data});
}
<Button onClick={submit}/>

model:
effects: {
    *effectSubmit({payload},{call}){
          console.log("第一次提交能达到这点，但是第二次+就不能到达这点");
         yield call(submitToBackEnd,payload);
   }
}

## 复现步骤，错误日志以及相关配置
点击button提交，第一次出发了effects里的effectSubmit事件，第二次没有触发，为啥？？？

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：16.7
- **操作系统**：Mac

**Comment by Big-Devils** [comment]
这个问题解决了么？

**Comment by JakeQuen** [comment]
解决了
一种方法是在错误的effects方法trycatch
另一种是直接进行错误配置
[app.ts/app.js配置链接](https://github.com/umijs/umi/blob/umi%402.3.1/docs/zh/guide/with-dva.md#%E9%85%8D%E7%BD%AE%E5%8F%8A%E6%8F%92%E4%BB%B6l)
