### ISSUE TITLE
effects里面的方法可以互相调用吗

### ISSUE THREAD

**Issue by kunzhijia** [dvajs/dva#248]
例如
`
{
 ...,
 effects:{
   *auth(),
   *login(){
       yield response = call(auth,action,{put})
       ....
    }
 }
}
`
如果要调用effect里面的方法，得怎么写

**Comment by sorrycc** [comment]
两个方案：

1. 通过 put `action` 去调? `yield put({ type: 'auth' });`，缺点是不会等待完成
1. `auth` 抽到 model 外，然后在 effect 里用 `yiled *` 去调他

**Comment by kunzhijia** [comment]
我现在就是使用你第二种方法，谢谢你这么及时回复

**Comment by miaojiuchen** [comment]
@sorrycc 请问如何在effect里同步等待另一个effect的完成？

**Comment by RJAVA1990** [comment]
还可以yield take('auth/@@end')

**Comment by HankBu** [comment]
> 还可以yield take('auth/@@EnD')

可行，好办法
