### ISSUE TITLE
在外层router.js中如何调用model中的方法

### ISSUE THREAD

**Issue by liurq** [dvajs/dva#249]
models目录下有个 `a.js` 已经在外层`src/index.js`中注册了
```javascript
app.model(require('./models/a'));
```
然后我在`src/router.js`中，如何获取a.js中的state信息？

**Comment by YueHui** [comment]
router.js不是做路由转发的吗， 为何要获取state信息？

**Comment by liurq** [comment]
想让路由信息由后台提供并可修改
