### ISSUE TITLE
求在组件中switch的用法

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#250]
我尝试过用三元运算法没有问题，
但是用switch就有问题，
请教朋友们在组件里面如何使用 switch 
求写法，谢谢！

**Comment by junmaqiang** [comment]
我的写法是这酱紫的
```
<Menu mode="horizontal" selectedKeys={[MenuKey]}>
              {
                switch (MenuKey) {
                  case 'config':
                      return '<Menu.Item key="config"><Link to="/config">配置</Link></Menu.Item>'
                    break;
                  default:
                    return '<Menu.Item key="order"><Link to="/order">订单</Link></Menu.Item>'
                }
              }
            </Menu>
```

**Comment by lincenying** [comment]
```javascript
const a = 1
    let b
    switch (a) {
        case 1:
            b = <div>1</div>
            break
        case 2:
            b = <div>2</div>
            break
        default:
            b = <div>3</div>
    }

//////////

{ b }
```

**Comment by junmaqiang** [comment]
搞定了，谢谢楼上的朋友，非常感谢！

**Comment by junmaqiang** [comment]
我又出问题啦
就是一个Menu.Item 没问题，两个Menu.Item 连起来就出问题，求助！


`    case 'spider':
        SelectMenu = <Menu.Item key="gua"><Link to="/gua">配置</Link></Menu.Item>
        break
    case 'tun':
        SelectMenu = <Menu.Item key="tun"><Link to="/tunmo">吞没算法</Link></Menu.Item><Menu.Item key="gua"><Link to="/gua">易经算法</Link></Menu.Item>
        break
    default:
        SelectMenu = <Menu.Item key="other"><Link to="/other">其他算法</Link></Menu.Item>

**Comment by lincenying** [comment]
用挂号包起来

**Comment by junmaqiang** [comment]
谢谢，按照您说的我增加了 <div> 包裹起来就OK了。非常感谢
