### ISSUE TITLE
官网不维护了吗

### ISSUE THREAD

**Issue by gaofeng222** [dvajs/dva#2518]
官网不维护了吗

**Comment by yzkkunshao** [comment]
dva应该不维护了，现在主流都是函数式组件，但dva里面用不了hook。我看了下valtio的设计跟dva是比较相似的https://github.com/umijs/umi/discussions/12387#discussioncomment-9448150

**Comment by gaofeng222** [comment]
感谢解惑！ @yzkkunshao 我自己搞了个静态的文档
