### ISSUE TITLE
effects的put如何延迟执行.

### ISSUE THREAD

**Issue by ah-kevin** [dvajs/dva#254]
effects 中的put action 如果 延迟执行..

**Comment by sorrycc** [comment]
put 前 delay 下? 

```js
yield call(delay, 1000);
yield put(action)
```

**Comment by ah-kevin** [comment]
ok 好了

**Comment by zhump** [comment]
@ah-kevin  不好意思 我不太懂yield call(delay, 1000); 中的 delay从哪来的，怎么实现延迟执行呢

**Comment by pszh** [comment]
yield call(delay, 1000); 这个delay 怎么引入

**Comment by xufei** [comment]
delay 就是一个函数，参见这里面的回复：

https://github.com/dvajs/dva/issues/1108

**Comment by j3r0lin** [comment]
redux-saga里面有，
```javascript
import { delay } from 'dva/saga';
````
