### ISSUE TITLE
 对象不支持“startsWith”属性或方法，开发浏览ie不抱错，build后运行就报这个

### ISSUE THREAD

**Issue by longzb** [dvajs/dva#257]
我非常明确我没有用startsWith这个es6的功能，并且npm start模式下，用ie访问也没任何问题，就是build后直接用ie打开index.html报 对象不支持“startsWith”属性或方法，扔到服务器里也是一样。

我怀疑是不是build后给我加了这个startsWith属性，现在几乎崩溃了。

还有build后样式也跟开发的时候不同了，

我就不明白，为什么npm start运行效果跟npm run build后总是有差别。

不知道原因就关了把！明天我重新构建，再一个文件一个文件的复制到新项目。

**Comment by sorrycc** [comment]
引 babel-polyfill，https://github.com/babel/babel/issues/2026#issuecomment-122330126
