### ISSUE TITLE
effects中怎么能yield throw Error 还有全局异常捕获中如何获取dispatch

### ISSUE THREAD

**Issue by jindada** [dvajs/dva#259]

**Comment by sorrycc** [comment]
effect 中直接 `throw Error` 就行了，不用 `yield`。捕获 `dispatch` 是什么意思? 没明白。

**Comment by jindada** [comment]
我用yield是希望抛出异常之后继续往下走 我做了一个全局的异常捕获 捕获到异常的时候 有个需求是跳转页面 但是我看基于action的跳转页面 需要dispatch(routerRedux.push('/login')) 但是我怎么能在onError中获取到dispatch那

**Comment by yinlsea** [comment]
试试把dva对象export，然后用dispatch = app._store.dispatch;

**Comment by sorrycc** [comment]
dva@1.1.0 的 onError 是包含 `dispatch` 的，详见：https://github.com/dvajs/dva/releases/tag/1.1.0

**Comment by jindada** [comment]
好的 已经升级到1.1 感谢
