### ISSUE TITLE
关于文件结构与加载的建议

### ISSUE THREAD

**Issue by t04041143** [dvajs/dva#26]
现在我们需要显式的去声明，model router 自定义middleware的加载，这部分是否可以考虑使用约定大于配置的规则。比如设置工程默认指定的model router等目录，自动扫描下面的包文件，自动调用app.model等方法加载，这样初始化的地方可以省去不少代码

**Comment by t04041143** [comment]
不过压缩合并后的js如何调用是个问题

**Comment by sorrycc** [comment]
最终我们会通过 `dva-cli` 提供脚手架，详见 #21 讨论。在生成脚手架之后，我们再提供 fine generator，比如 `dva g model user`，会生成一个叫 user 的 model，并且注册到 app 上。

不知这样是否能解决你的问题?

**Comment by t04041143** [comment]
明白了，也是个办法，我只是想不要枚举已经定义过的model这样代码里看起来不优雅，或者是否可以模拟angular这样，有一个类似angular的全局变量，这样在model文件里直接dvaApp.model来定义model的同时，也把model加入到dva的model容器里

**Comment by sorrycc** [comment]
webpack 里有个 `require.context` 可以做批量 require 的事情的。参考：https://github.com/ant-design/antd-init/blob/master/boilerplates/redux/src/reducers/index.js

**Comment by t04041143** [comment]
好的，我看看
