### ISSUE TITLE
app.model: namespace should be defined(…)

### ISSUE THREAD

**Issue by yinlsea** [dvajs/dva#261]
不用atool-build打包，用标准webpack打包时，打包后文件运行报错
![image](https://cloud.githubusercontent.com/assets/21033870/20162464/37331ffc-a730-11e6-9746-6238710f6c0c.png)

**Comment by sorrycc** [comment]
出错信息很明确了，model 没有 `namespace` 属性。

**Comment by yinlsea** [comment]
不是这样的，所有的model肯定是有namespace的，同样的源码，用atool-build打出来的就正常，我也是奇怪。用atool-build打包的时候有个很神奇的问题，做的按需加载，超过是10个模块的时候，就一直卡在哪里，所以才试着换成标准webpack来尝试，用webpack打包，不卡死，但是报这个错误。
路由的配置就是很标准的splitcode写法
![image](https://cloud.githubusercontent.com/assets/21033870/20163371/04563df6-a737-11e6-9e02-3ac0e8ee660c.png)

**Comment by sorrycc** [comment]
看下报错堆栈信息看? https://github.com/dvajs/dva/blob/831b7d9/src/createDva.js#L242-L245 这一行抛的错。

**Comment by yinlsea** [comment]
我在createDva中加断点，看到的是这样
![image](https://cloud.githubusercontent.com/assets/21033870/20165512/d4e6f7d8-a748-11e6-918e-58ff5a30d9cc.png)
model有值，default有，但是
![image](https://cloud.githubusercontent.com/assets/21033870/20165525/f348ac26-a748-11e6-89a4-ad4a7864a095.png)

**Comment by yinlsea** [comment]
刚对比了一下用atool-build打包出来的，model就是直接有值的
![image](https://cloud.githubusercontent.com/assets/21033870/20166455/d6730306-a74f-11e6-8f05-aa2c7124a176.png)
webpack打包的是这样的：
![image](https://cloud.githubusercontent.com/assets/21033870/20166485/281a56fa-a750-11e6-9d93-5bd16f2dafa7.png)

**Comment by sorrycc** [comment]
没加 `babel-plugin-add-module-exports` ?

**Comment by yinlsea** [comment]
确实，是这个问题，加了export default{}的就可以了。

**Comment by yinlsea** [comment]
但是还是不懂为什么atool-build打包的时候，为什么卡住不动，这个问题很神奇，少一个模块就很快处理了。

**Comment by fomenyesu** [comment]
atool-build 加入到维护中的项目里确实有点怪怪的。

**Comment by ycjcl868** [comment]
换成 `import` 导入就ok了，

```js
import indexModel from './model/index.js';
app.model(indexModel);
```

**Comment by tylerrrkd** [comment]
最终解决，还是需要`add-module-exports`才可以
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": "cjs",
        "useBuiltIns": "entry",
        "corejs": 3,
        "targets" : "> 0.25%, not dead"
      }
    ], "@babel/preset-react"
  ],
  "plugins": [
    ["add-module-exports", { "addDefaultProperty": true }],
  ]
}
```
