### ISSUE TITLE
除了reducers中的方法可以访问state，effects、subscriptions中如何访问state

### ISSUE THREAD

**Issue by linginging** [dvajs/dva#262]
除了reducers中的方法可以访问state，effects、subscriptions中如何访问state。
感觉非常不方便

**Comment by sorrycc** [comment]
effect 中可以通过 [select](https://github.com/dvajs/dva-knowledgemap#select) 访问全局 state，subscription 不允许访问 state。

**Comment by iwege** [comment]
是否意味着subscription如果使用了其他的component的state，必须要自己copy一份？

**Comment by sorrycc** [comment]
@iwege subscription 只做订阅，订阅后具体的事情放到 effect 中。

**Comment by mynameisbxh** [comment]
那如果我想订阅某个state的变化呢
