### ISSUE TITLE
import ant布局 组件的css为啥不起作用

### ISSUE THREAD

**Issue by ulongx** [dvajs/dva#265]
import './mainLayout.css'

**Comment by sorrycc** [comment]
用 dva-cli 初始化的项目? 默认是开启了 css-modules 的。https://github.com/dvajs/dva-cli/blob/1a4cb33/boilerplates/app/webpack.config.js#L19-L38

**Comment by ulongx** [comment]
谢谢解答，项目是用dva-cli 初始化的，默认是开启了css-modules；后来我修改了css文件和引入方式就可以了，如：**import styles from './mainlayout.less'**，使用的时候： **className={styles.antlayoutaside}**，如果这样，像antd的组件拿过来就是需要修改一遍css的调用，不能直接像 **className="antlayoutaside"** 这个方式使用
