### ISSUE TITLE
在model 中添加多个reducers  同时引起多个reducer 改变

### ISSUE THREAD

**Issue by johnsky123** [dvajs/dva#269]
想要控制 一个reducer  改变状态    在一个model中添加不同的 reducers  ,dispatch一个reducers  引起了其他的reducers 改变

**Comment by sorrycc** [comment]
- 只能 dispatch action, reducer 是接受 action 做后续处理
- dispatch 一个 action 后触发多个 reducer，可以通过 effect 做，在 effect 里 put 多个 action
