### ISSUE TITLE
渲染不出内容，提示<!-- react-empty: 1 -->

### ISSUE THREAD

**Issue by ca7pe** [dvajs/dva#270]
一开始构建是没有问题的，
集成了antDesign之后，本来好好的，
但是过了一阵子，无缘无故突然渲染不出内容，提示
控制台提示bundle大小过大，我看了一下index.js有4M，于是改成了babel-plugin-import的做法，现在index.js只有1.6M了
但是还是渲染不出来，不知道发生了什么，
![qq 20161114175620](https://cloud.githubusercontent.com/assets/1556699/20260423/86b8551c-aa94-11e6-8f4d-0c67e181b1b4.png)
好神奇，有人遇到过吗？

**Comment by sorrycc** [comment]
没报错? 感觉和 dva 无关。

**Comment by sorrycc** [comment]
http://stackoverflow.com/questions/38923805/what-is-react-empty

**Comment by ca7pe** [comment]
找到原因了，是这段代码的问题，我想去掉queryKey，这样写不对吗？
![qq 20160716204053](https://cloud.githubusercontent.com/assets/1556699/20266075/56f28e90-aaaf-11e6-9fe9-54e7d2b26488.png)

**Comment by ca7pe** [comment]
找到原因了，是这段代码的问题，我想去掉queryKey，这样写不对吗？
![qq 20161114211406](https://cloud.githubusercontent.com/assets/1556699/20266181/f82cf160-aaaf-11e6-94ae-7db6f53c8616.png)

**Comment by sorrycc** [comment]
别去掉 queryKey，你可能会遇到奇怪的问题的。
