### ISSUE TITLE
How to access history in effects?

### ISSUE THREAD

**Issue by miaojiuchen** [dvajs/dva#271]

**Comment by miaojiuchen** [comment]
@sorrycc

**Comment by sorrycc** [comment]
What property of history do you want to access?

**Comment by miaojiuchen** [comment]
@sorrycc router history

**Comment by sorrycc** [comment]
```js
const routing = yield select(state => state.routing);
```

![image](https://cloud.githubusercontent.com/assets/35128/20290850/9dbd3334-ab1d-11e6-9556-1f6899454a91.png)

**Comment by miaojiuchen** [comment]
exactly i want to access the <b>history.push</b> api, 
but I can only get a location obj by selecting the "routing" state in store
so..... any other solutions?

**Comment by sorrycc** [comment]
push history in effect? try this.

```js
import { routerRedux } from 'dva/router';

// Inside Effects
yield put(routerRedux.push('/logout'));
```

**Comment by miaojiuchen** [comment]
thx a lot!

**Comment by prionkor** [comment]
Need to make a list of these tickets on dvajs homepage.
