### ISSUE TITLE
从props中取值(为数组时)报错

### ISSUE THREAD

**Issue by ethanzhanxd** [dvajs/dva#272]
const frm= ({
  item,
  form: {
    getFieldDecorator,
    validateFields,
    getFieldsValue,
  },
}) => {
return (
<div>
  <div>{item.name}</div>             
 <div>{item.users[0].name}</div> 
 <div>{item.users.map(u =>{return u.name})}</div> 
</div>
)
}

frm.propTypes = {
  item: PropTypes.any
}

export default Form.create()(frm)

cons frmProps = {item:{user:'a',users:[{name:'q'},{name:'r'}]}}
<frm {...frmProps} />

请问是哪里不对吗？

**Comment by ethanzhanxd** [comment]
{item.users[0].name}
{item.users.map(u =>{return u.name})}  这两种报错

{item.name} 这个可以显示。

**Comment by afc163** [comment]
无法阅读：https://guides.github.com/features/mastering-markdown/

**Comment by sorrycc** [comment]
请调整下格式。

**Comment by ethanzhanxd** [comment]
```js
//model.js
export default {
  namespace: 'app',
  state: {
        user:{}
},{
subscriptions:{},
effects:{},
reducers:{}
}

//frm.jsx
const frm= ({
item,
form: {
getFieldDecorator,
validateFields,
getFieldsValue,
},
}) => {
return (
<div>
  <div>{item.name}</div>  //这里显示正常 'Jimmy'
  <div>{item.users[0].name}</div> //这里显示name of undefined
  <div>{item.users.map(u =>{return u.name})}</div> //这里显示map of undefined
</div>
) }
frm.propTypes = {
item: PropTypes.any
}

export default Form.create()(frm)

//container.jsx
import Frm from 'frm.jsx'

function Container({location, dispatch, app}) {
  const {
      user
    } = app
//user = {name:'Jimmy',users:[{name:'Tony'},{name:'Mark'}]}
const frmProps = {item:user}
  return (
    <div>
       <Frm {...frmProps} />
   </div>
)
}
function mapStateToProps({ app}) {
  return { app}
}

export default connect(mapStateToProps)(Container)

```
是不是使用props的方法不对？

**Comment by sorrycc** [comment]
item 打印出来看看，应该是没数据吧。

**Comment by codering** [comment]
试试
```js

//model.js
export default {
  namespace: 'app',
  state: {
        user:{
           name: '',
           users: []
        }
},{
subscriptions:{},
effects:{},
reducers:{}
}

```

**Comment by ethanzhanxd** [comment]
item有数据的。
内容：
```js
 {name:'Jimmy',users:[{name:'Tony'},{name:'Mark'}]}
```
如果取 item.name是有值的，为：Jimmy
取item.users[0].name 就报：Cannot read property '0' of undefined
显示 {typeof item.users} 为object，但怎么都取不出来值
@codering item的值是在effects里从服端取下来的

**Comment by codering** [comment]
可能在服务端数据还没返回前就已经渲染了一次了，这时 user = {} ，里面时没有users属性的，你自己断点调试下就可以看出来了吧

**Comment by ethanzhanxd** [comment]
在服务端是一次拿下来的，用Chrome Redux DevTools看到state数据都是有的。所以应该不是渲染的时候还没有数据的问题。
放到这里又是没有问题的，应该是我对这个用法没有理解好
```js
 {getFieldDecorator('username', {
          })(
            <Select>
            {
              item.users.map(u=>{
               return(<Select.Option key={u.name} value={u.name}>{u.name}</Select.Option>)
              })
            }
            </Select>
 )}
```

**Comment by codering** [comment]
没有异步请求的时候，页面能正确渲染吗？

**Comment by ethanzhanxd** [comment]
的确是异步的时候才出错，如果在model里初始就有值的话，是可以显示数组中的值的。
我是在subscriptions里根据url中的id加载了异步请求，然后这样显示就报错了。
正确的做法是怎样的呢？

**Comment by ethanzhanxd** [comment]
解决了，是个好低级的问题。。。
应该根据loading状态决定是否渲染组件。

多谢。

**Comment by hst-Sunday** [comment]
@ethanzhanxd  
我也出现这样的问题，请问是state那里没有给初始值的问题吗？你是怎么解决的？
