### ISSUE TITLE
dva 构建项目的时候怎么给index.js和index.css加版本号

### ISSUE THREAD

**Issue by liSong5713** [dvajs/dva#273]
dva build的工具用的是atool，在项目build的时候怎么加入版本号，还有index.html 怎么能引入版本号map的地址，因为版本号是可变的不能引入绝对的地址，麻烦博主给个建议

**Comment by sorrycc** [comment]
`atool-build -o ./dist/$npm_package_version` 或者 `atool-build --hash`。
