### ISSUE TITLE
fetch设置headers失效

### ISSUE THREAD

**Issue by xaviertung** [dvajs/dva#277]
@sorrycc utils/request.js中设置headers，在浏览器查看http请求，发现未在request headers中生效：
request.js代码：
```
fetch(url, {
    body:"name=%E4%B8%AD%E6%96%87&mobile=121212121&password=111111&captcha=sdsds",
    method:"post",
    mode:"no-cors",
    headers:{
        Accept:"application/json",
        Authorization:"Bearer dfdfdfdfdfdfdf",
        Content-Type:"application/json"}
});
```
浏览器中Request Headers显示未生效：
accept:application/json
content-type:text/plain;charset=UTF-8

请教一下，如何设置headers头信息呢？比如将token塞进header中？

**Comment by sorrycc** [comment]
参考 https://www.npmjs.com/package/whatwg-fetch#post-json，不过你的代码看起来好想也没问题。

**Comment by xaviertung** [comment]
OK，谢谢，我再尝试一下。

**Comment by lincenying** [comment]
Content-Type 是不是该加个引号包起来.

**Comment by huzhengke** [comment]
@xaviertung 该问题你解决了吗，怎么解决的，能否请教下，我折腾了好久还是不行。

**Comment by monkindey** [comment]
hi, @huzhengke , @lincenying 的方式应该是正解

**Comment by huzhengke** [comment]
@monkindey 加引号，按照官网的写法依然没用呀。

**Comment by JayM0826** [comment]
@huzhengke 请问解决了吗？新人又入坑了。。。。

**Comment by linonetwo** [comment]
得这样
```js
fetch(
    new Request(`${API}${path}`, {
      headers: new Headers({ Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json' }),
    }),
  )
    .then(res => res.json());
```
关键是用 Request 和 Headers 对象。

**Comment by crazylxr** [comment]
@xaviertung 你把 mode 设置为 'cors' 就行了，不要用 'no-cors'

**Comment by suedar** [comment]
请问有解决方法吗

**Comment by linonetwo** [comment]
@suedar 你看我那个行不行

**Comment by hoipo** [comment]
跨域的时候还会出现header缺失问题，只能返回部分header头

> If a request is made for a resource on another origin which returns the CORs headers, then the type is cors. cors and basic responses are almost identical except that a cors response restricts the headers you can view to Cache-Control, Content-Language, Content-Type, Expires, Last-Modified, and Pragma.
