### ISSUE TITLE
在service中使用'post','delete'和'put'每次都发送两次HTTP请求

### ISSUE THREAD

**Issue by mrzysv5** [dvajs/dva#280]
![_076](https://cloud.githubusercontent.com/assets/20341141/20344013/ed4948d4-ac2b-11e6-900b-a2dfc78732f0.png)
第一次发送的请求:
```
OPTIONS /admin/users HTTP/1.1

```
第二次:
```
DELETE /admin/users HTTP/1.1
Payload: {"uid":"10000000005"}
```

请问这是怎么回事啊?明明只调用了一次`fetch`方法.

**Comment by sorrycc** [comment]
加 `debugger` 看下是否执行了两次。

**Comment by lincenying** [comment]
这是跨域的问题. 和dva没有关系

**Comment by yuzhouisme** [comment]
是的，跨域时，会先发送一次OPTIONS请求，再发DELETE/PUT等；

**Comment by mrzysv5** [comment]
@yuzhouisme 谢谢了,我用`dora-plugin-proxy`代理了一下,害有没有其它的解决办法?

**Comment by lincenying** [comment]
只要是ajax请求跨域, 就没有办法, 跨域遇到复杂请求, 都会先发option去请求是否有权限跨域
这个没什么影响, 实在不想看到, 只能同源服务器去做代理

**Comment by whaty** [comment]
hi,你好，我也遇到这个问题了，怎么解决的呢？还请不吝赐教
