### ISSUE TITLE
急求！！！！

### ISSUE THREAD

**Issue by MaYing929** [dvajs/dva#281]
有办法在constructor里面调用render方法吗

**Comment by sorrycc** [comment]
react 组件? 不可以。

**Comment by MaYing929** [comment]
一个不是纯粹静态的组件  我如何控制在请求回来再渲染页面呢？ 例如edit页面可以根据重置上面的时间段来重置本页面下方表格的定价规则。用ES6  和constructor里面初始化放在state里面，但是只会渲染一次，放render里面又会渲染多次，真不知道该怎么办了

**Comment by sorrycc** [comment]
你需要理解下 react 的渲染机制，render 依赖的 props 或 state 变化了就会重新执行，然后走 virtual-dom 渲染。

**Comment by MaYing929** [comment]
constructor是进行初始渲染的，当真实值来的时候不会进行替换吗，constructor只执行一次

**Comment by yuzhouisme** [comment]
生命周期里有一个这个函数componentWillReceiveProps，你可以考虑下能否在这个里面解决你的问题

**Comment by MaYing929** [comment]
恩  好的 我试一下，

**Comment by MaYing929** [comment]
问题解决了  谢谢谢谢
