### ISSUE TITLE
关于优化问题。

### ISSUE THREAD

**Issue by Allen-vip** [dvajs/dva#283]
你好，我想个问下，dva是怎么去进行性能优化的。
比如我一个antd组件table，我触发50次action，新增了50行，每行每列都是可编辑的，进行编辑的时候会有卡顿。

使用Immutable。
但是发现shouldComponentUpdate返回的nextprops和this.props的值永远是一样的。

**Comment by sorrycc** [comment]
增加 50 行为啥要触发 50 次 action，不能一次 action ?

**Comment by sorrycc** [comment]
性能优化我能想要的是几点：

1. 用 [reselect](https://github.com/reactjs/reselect) 对 mapStateToProp 中的计算方法做缓存
1. 用 shouldComponentUpdate 减少 render() 方法的执行

**Comment by Allen-vip** [comment]
@sorrycc 嗯，我只是打个比方，我是一个新增的功能，点击新增按钮一次，触发一次action，添加一条数据，
理论上，新增是没有条数限制的。

好的，我明白了，我多在上面的2点进行琢磨。 非常感谢。

**Comment by tanzhihang** [comment]
@sorrycc 这里所说的增加50行，每增加一行state就发生改变了，当然会触发50次action啊。reselect对于相同的state才会返回缓存的结果，这里已经发生改变了会重新计算啊
