### ISSUE TITLE
用户如何编写 models/effects的测试代码？

### ISSUE THREAD

**Issue by zachshelter** [dvajs/dva#285]
如题， 是否只能引 dva在测试代码中，然后通过 dva().model(...)等方法编写测试代码？

我想只需要测effects是否能够发送正确的 actions ， 这些actions可能是其他model的。

应该怎么测试呢？

**Comment by sorrycc** [comment]
参考 https://github.com/yelouafi/redux-saga/blob/master/examples/counter/test/sagas.js 和 https://github.com/yelouafi/redux-saga/blob/master/examples/shopping-cart/test/sagas.js 。

**Comment by zachshelter** [comment]
谢谢，通过例子发现 其实也可以 在测试里 mock put select 等 传入 model 然后检测是否被调用且以什么参数调用。这样也比较方便

**Comment by jakietwo** [comment]
> 谢谢，通过例子发现 其实也可以 在测试里 mock put select 等 传入 model 然后检测是否被调用且以什么参数调用。这样也比较方便

请问如何测试 select 呢
