### ISSUE TITLE
user-dashboard sample - Route to /users consistent behaviour?

### ISSUE THREAD

**Issue by visvadw** [dvajs/dva#288]
Hi @sorrycc ,

While playing around with user-dashboard example, I have noticed that:
- if starting from / and clicking on Users link, the users view shows as normal:
![image](https://cloud.githubusercontent.com/assets/14140226/20399948/8f7d4e46-acfb-11e6-8514-47de0a50c453.png)
- but if going directly to /users, a 404 is returned:
![image](https://cloud.githubusercontent.com/assets/14140226/20400093/00a7e0e0-acfc-11e6-86b8-7ce8a7733818.png)

I just extracted the example from distribution and simply install the deps and ran it.
I could not find any reason why this behaviour is different.
Have you encountered such complains?

Thanks.

**Comment by sorrycc** [comment]
The default history should be `hashHistory`, have you changed it to `browserHistory`?

**Comment by visvadw** [comment]
Indeed. Here is the change that I made to `src/index.js`:
```
...
import { browserHistory } from 'dva/router';

// 1. Initialize
// const app = dva();
const app = dva({
    history: browserHistory
});
```

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/commit/799f8e8445d4f2fe648bea126dd4266377db40c6

**Comment by visvadw** [comment]
As always, good quality code and feedback! 👍 Thank you very much! 😄

I just made a small PR to include a link to this user-dashboard example that is now using `browserHistory`.
