### ISSUE TITLE
[QUESTION] How to integrate redux-persist?

### ISSUE THREAD

**Issue by marvelousmishig** [dvajs/dva#289]
What is the best way to integrate redux-persist (https://github.com/rt2zz/redux-persist) with DVA? By the way, thanks for creating DVA, it is a game changer!

**Comment by sorrycc** [comment]
Dva should support [redux enhancer](https://github.com/dvajs/dva/issues/258) to integrate redux-persist, and it will be supported in next version.

Before that, if want to do store persist, you can try the `onStateChange` hook: 

```js
const app = dva({
  onStateChange() {
    save(app._store.getState());
  },
});
```

**Comment by marvelousmishig** [comment]
Thank you very much for your reply!

**Comment by mutoulbj** [comment]
1.2版本还没有加入redux-persist吧？

**Comment by nihgwu** [comment]
dva不会集成redux-persist的，通过 `extraenhancers` 自己集成 https://github.com/dvajs/dva/blob/master/docs/API.md#extraenhancers

**Comment by mutoulbj** [comment]
@nihgwu 好的，感谢~
