### ISSUE TITLE
app.router: router should be function

### ISSUE THREAD

**Issue by summerinsect** [dvajs/dva#290]
用create-react-app构建的
```javascript
 import React from 'react';
import dva from 'dva';
import App from './App';
import './index.css';

const app = dva();
// app.model(require('./models/login'));
app.router(require('./router'))
app.start('#root'); 
```

报错：Uncaught Invariant Violation: app.router: router should be function

--------------------------------------------------
改成：
```javascript
import Router from './router';
app.router(Router);
```
就可以了

---------------------------------------------------

```javascript
//router.js
import React, { PropTypes } from 'react';
import { Router, Route } from 'dva/router';
import Login from './routes/login';

export default function({ history }) {
  return (
    <Router history={history}>
      <Route path="/login" component={Login} />
    </Router>
  );
};```

**Comment by anhuiliujun** [comment]
app.router接受一个function做参数吧，

**Comment by lincenying** [comment]
把./router的代码贴出来看下.

**Comment by sorrycc** [comment]
要 require 生效，需要加 [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports)。create-react-app 应该是没加这个。

**Comment by jindada** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
@sorrycc 报错app.router: router should be function  把dva-hmr去掉就

**Comment by jindada** [comment]
@sorrycc  用import的方式引入路由的 配置dva-hmr就报Uncaught Invariant Violation: app.router: router should be function 去掉dva-hmr之后就正常运行了
