### ISSUE TITLE
stateless functional component怎么处理生命周期的逻辑呢？

### ISSUE THREAD

**Issue by homkai** [dvajs/dva#292]
```js
const Main = ({dispatch, status, content}) => {
   return (
      <div>
         <button onClick={dispatch({type: 'togglePage'})}>
            toggle page
         </button>
         {status ? <PageOn {content}/> : <PageOff {content}/>}
      </div>
   );
};
```
button click的时候，会触发PageOn和PageOff组件的willMount和willUnmount
```js
const subscriptions = {
   // subscriptions 比如可以在加载组件或者加载整个项目的时候就执行
   onPageToggle({on}) {
      const off = on('action', (action, getState) => {
         if (action.type === 'togglePage' && getState().status) {
            // 这个条件是说要切换到PageOff
            // do something PageOn willUnmount / PageOff willMount
         }
         // do something PageOn willMount / PageOff willUnmount
      });
      // unlisten if necessary
   }
};
```
这个思路就是说，把对组件生命周期的依赖转为对状态的订阅。
组件之所以会挂载、更新、移除是因为整个项目的状态改了。
那么我通过订阅状态，来完成生命周期里的逻辑，应该是可行的吧，是不是数据驱动的意味更强点。

**Comment by homkai** [comment]
大神们多多指教，小弟是来取经的

**Comment by sorrycc** [comment]
`onPageToggle({on}) {` 这个 on 是哪里来的? component 要 hook mount 和 unmount 就不要用 stateless component 了，用 class 吧。

**Comment by homkai** [comment]
app.use()方法可以有onAction的嘛，所以on肯定是可以来的。先不说具体代码怎么来的，先说这个思路怎么样？
通过订阅状态，来完成生命周期里的逻辑。
纯函数的组件跟class的组件，主要就是少了生命周期，少了this（state、ref之类的），this的问题应该对业务影响不大，主要是生命周期。针对生命周期提出了上面的替代方案。
然后如果团队里 强制推让大家必须都用纯函数的component，用这个思路来完成可能的依赖生命周期的逻辑感觉怎么样？
这样的话，那么我对react的依赖是很小的，后面react想替换成vue其实也没多大成本。
而且组件是纯函数的话，各种好处，无依赖、测试方便、静态代码分析等等。
想听大神说说看强去推纯函数组件，值不值得
pp.use()方法可以有onAction的嘛，所以on肯定是可以来的。先不说具体代码怎么来的，先说这个思路怎么样？
通过订阅状态，来完成生命周期里的逻辑。
纯函数的组件跟class的组件，主要就是少了生命周期，少了this（state、ref之类的），this的问题应该对业务影响不大，主要是生命周期。针对生命周期提出了上面的替代方案。
然后如果团队里 强制推让大家必须都用纯函数的component，用这个思路来完成可能的依赖生命周期的逻辑感觉怎么样？
这样的话，那么我对react的依赖是很小的，后面react想替换成vue其实也没多大成本。
而且组件是纯函数的话，各种好处，无依赖、测试方便、静态代码分析等等。
想听大神说说看强去推纯函数组件，值不值得~

**Comment by sorrycc** [comment]
我们是推荐用纯函数，但不强推，个别场景还是需要生命周期的。
