### ISSUE TITLE
action 进行页面跳转

### ISSUE THREAD

**Issue by sevennights** [dvajs/dva#293]
请问使用routerRedux 进行页面跳转 下个页面接收参数的写法
            routerRedux.push({
              pathname: '/',
              data: {
                data: data,
              },
            })

**Comment by sorrycc** [comment]
https://github.com/reactjs/react-router-redux#pushlocation-replacelocation-gonumber-goback-goforward

**Comment by roc2539** [comment]
所有的页面逻辑都是在models中控制的，对吗？ 页面跳转也是直接写在里面的。

**Comment by nikogu** [comment]
@roc2539 我们推荐将逻辑抽象到 models 中，但也是要根据具体场景的，有些在组件中更合理的添加跳转的行为，没必要非要放到 models 中

**Comment by roc2539** [comment]
@nikogu 好的，感谢

**Comment by roc2539** [comment]
比如我登录成功了。跳转应该是怎样？ 在effects中 
yield put(routerRedux.push({
            pathname: '/main'
          }));  是可以的 ？
有没有另外一种。我改变了state 在组建中跳转呢？ 组件我是用 stateless component ，怎么接收状态改变？有类似 componentWillReceiveProps 这样的吗？还是我要改组件写法。

**Comment by liSong5713** [comment]
@nikogu ，请问model的分割 是基于每个page model 还是业务model

**Comment by nihgwu** [comment]
这个看你的粒度吧，个人推荐按业务划分
