### ISSUE TITLE
dva webpackConfig 怎么设置入口文件 和输出文件 

### ISSUE THREAD

**Issue by wangchunling** [dvajs/dva#294]
我看dva-ci里面的默认webpackConfig 没有设置输出文件 默认打包成了一个index.js 但在文件路径中找不到这个文件  怎样配置webpackConfig  进行发布呢

**Comment by sorrycc** [comment]
可以在 package.json 中配：
https://github.com/dvajs/dva-cli/blob/3c4e8a8/boilerplates/app/package.json#L4

也可以在 webpack.config.js 里配：

```js
webpackConfig.entry = {};
```

**Comment by wangchunling** [comment]
![image](https://cloud.githubusercontent.com/assets/6300399/20473969/e8b007aa-affe-11e6-8803-75ac8d8e7d99.png)
这么配置了一下webpack 的输出目录  不知道为什么  目录里没有对应打包的js  看目录也是没问题的啊

**Comment by sorrycc** [comment]
`/dist/` 换成 `dist` 试试？

**Comment by wangchunling** [comment]
![image](https://cloud.githubusercontent.com/assets/6300399/20474569/f9eeafa0-b001-11e6-9a55-b8e1799976e3.png)
试过了 还是不行  还试了/dist    dist/ 都是不行 你们的都可以正常输出么？

**Comment by sorrycc** [comment]
`npm start` 是不输出文件的，文件在内存里，`npm run build` 会输出。

**Comment by nikogu** [comment]
@wangchunling `run start` 没有实体文件，走的是内存

`run build` 才会有实体文件哈

**Comment by linyongping** [comment]
这个配置输出的是哪个文件，根目录只有一个webpack.config.js,但是没有输出output，是要在atools-build里面去配置吗

**Comment by sorrycc** [comment]
`webpack.output = ...` 在 webpack.config.js 里改完返回出来就好了。
