### ISSUE TITLE
404 (Not Found)   antd.css.map 

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#295]
请问出现下面这个提示如何解决？

`Failed to load resource: the server responded with a status of 404 (Not Found)       http://localhost:8989/antd.css.map       `

**Comment by sorrycc** [comment]
没遇到过，有载入 http://localhost:8989/antd.css ?

**Comment by junmaqiang** [comment]
有啊，`在 index.js 里面 载入了 import 'antd/dist/antd.css';`

**Comment by sorrycc** [comment]
推荐用 babel-plugin-import 的方式载入 antd，https://ant.design/docs/react/practical-projects#使用-antd 。

**Comment by junmaqiang** [comment]
正是用的 ` babel-plugin-import ` 这种方式安装导致！

**Comment by sorrycc** [comment]
没用对，检查下代码看。

**Comment by nikogu** [comment]
@junmaqiang 参看这个例子的配置：https://github.com/dvajs/dva/tree/master/examples/user-dashboard

**Comment by leeguooooo** [comment]
@sorrycc  remix.run 项目中如何解决这个问题
