### ISSUE TITLE
browserHistory 路由地址栏输入、刷新（not fount）问题

### ISSUE THREAD

**Issue by a573367014** [dvajs/dva#301]
通过Link点击能够跳转，但是刷新，或者直接从地址栏输入，会显示 not fount（只有根路径没问题）

**Comment by sorrycc** [comment]
参考这个 commit，https://github.com/dvajs/dva/commit/799f8e8445d4f2fe648bea126dd4266377db40c6 。

**Comment by nikogu** [comment]
1. `npm install dora-plugin-browser-history --save-dev`
1. 改 `package.json`的 `script`-> `"start": "dora --plugins \"proxy,webpack,webpack-hmr,browser-history?index=/src/index.html\"",`
1. `tnpm start`
