### ISSUE TITLE
怎么在effects  中发起dispatch

### ISSUE THREAD

**Issue by johnsky123** [dvajs/dva#305]
在effects  直接发起dispatch报错  ，
![image](https://cloud.githubusercontent.com/assets/11240977/20510694/57cb5d52-b0ad-11e6-8160-19724e5be6b9.png) 
需要进行什么操作 ，才能修改这个错误

**Comment by codering** [comment]
```js
 *xxxx(action, { call, put }) {
      yield put({ type: 'add' });
    },

```

**Comment by johnsky123** [comment]
effects 中发起了一个异步请求 ，需要判断请求状态码进行路由跳转  直接发起dispatch(routerRedux,push({pathname:'/XXX}))   报错

**Comment by sevennights** [comment]
yield put(
            routerRedux.push({
              pathname: '/',
              payload: ...,
            })
        );可以用这种 但是这种怎么传值的话 我还木有搞明白
