### ISSUE TITLE
项目根目录生成很多文件，请问哪里配置导致的

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#307]
项目使用dvajs做的，前端用ant组件，根目录生成很多类似如下的文件
`1a1a9f1b6b02d22cb472411ea1555f86f0b203ba.json.gzip`
请问这是在哪里配置导致的？
我猜可能是调试模式下生成的文件，请问可以统一放一个目录管理？

**Comment by nikogu** [comment]
@junmaqiang 截个完整目录的图看看

**Comment by junmaqiang** [comment]
![59406e0f-4de4-45ce-b697-281df18fcdb5](https://cloud.githubusercontent.com/assets/1819457/20550753/e5a03b90-b173-11e6-9de7-4deef15b67c7.png) 目录就是这样子

**Comment by nikogu** [comment]
@junmaqiang 这个跟dva没关系哈，你检查下你的编辑器

**Comment by sorrycc** [comment]
在 `webpack.config.js` 里关闭 babel 的 `cacheDirectory` 试试。

```js
webpackConfig.babel.cacheDirectory = false;
```
