### ISSUE TITLE
dva能否兼容react-native-router-flux做路由

### ISSUE THREAD

**Issue by chinacoolboyzz** [dvajs/dva#310]
https://github.com/aksonov/react-native-router-flux

**Comment by nikogu** [comment]
这个可能需要考察一下

**Comment by chinacoolboyzz** [comment]
https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md
// reducers/routes.js
import { ActionConst } from 'react-native-router-flux';
const initialState = {
  scene: {},
};
export default function reducer(state = initialState, action = {}) {
  switch (action.type) {
    // focus action is dispatched when a new screen comes into focus
    case ActionConst.FOCUS:
      return {
        ...state,
        scene: action.scene,
      };
    // ...other actions
    default:
      return state;
  }
}
// app.js
const app = dva({
    extraReducers: { routers: routes },
});
这里导入rnrf的路由无效

**Comment by chinacoolboyzz** [comment]
建议dva采用react的做法
*react
*react-dom
*react-native
将dav进行核心玻璃形式的发布
如：
*dva-code
*dva-route
*dva-mobile
这样我们可以分别根据需求自行组合

**Comment by rendongsc** [comment]
@sorrycc 我们也准备用dva来做native的开发，希望可以考虑chinacoolboyzz 的建议。

**Comment by codering** [comment]
dva只是简单封装，每个文件都很小，没必要分开吧。。。

**Comment by linonetwo** [comment]
在 React-Native 中我们已经开始使用 react-router 4.0 了， 用它的 memory-router 来导航。
  
而且 4.0 之后能直接和 redux 链接，不需要额外的库，所以可以考虑直接支持 react-router 4.0

**Comment by sorrycc** [comment]
@linonetwo 感谢提供信息，我找时间再看下 react-native 和 react-router@4 。

**Comment by sorrycc** [comment]
这里先关了，有兴趣请到 #530 跟进进度。
