### ISSUE TITLE
error TS2503: Cannot find namespace 'HistoryModule'.

### ISSUE THREAD

**Issue by bang88** [dvajs/dva#311]

**Comment by bang88** [comment]
https://github.com/dvajs/dva/blob/master/index.d.ts#L52-L69

TypeScript 的项目编译的时候的错误信息。

**Comment by nikogu** [comment]
@bang88 pr is welcome

**Comment by sorrycc** [comment]
参考这个，添加这些依赖呢? https://github.com/sorrycc/dva-boilerplate-typescript/blob/0035536/typings.json

**Comment by bang88** [comment]
没必要了，让用户自己选择吧。

**Comment by sorrycc** [comment]
不添加这些，并不能完整地写完 dva 项目吧，这也是我没添加 History 依赖的原因。

**Comment by bang88** [comment]
可以的。  因为之前你加那个HistoryModule找不到，我只是用了你Router里面的typings

**Comment by sorrycc** [comment]
那路由部分的代码不还是需要自己加 react-router 的 typings 依赖吗?

**Comment by bang88** [comment]
`HistoryModule` 哪里来的。

**Comment by sorrycc** [comment]
typings/globals/react-router/history/index.d.ts

**Comment by bang88** [comment]
你还是用以前的typings 不用@types 吗？

**Comment by sorrycc** [comment]
typings 是已经过时了吗? 👻  typescript 圈我关注地不多。

**Comment by bang88** [comment]
用以前的就对的，但是用@types就有问题，如果你跟`Router.d.ts`里面保持一致的话应该都能兼容吧

**Comment by bang88** [comment]
没有过时 是可以直接通过`npm i @types/pkg`来安装`typings`

**Comment by bang88** [comment]
其实@types里面的文件也是 `dt`里面的内容生成的，你那个`repo`的代码没有什么问题的。只是把`typings`的依赖管理放到`package.json`里面而已。

**Comment by sorrycc** [comment]
把依赖放到 package.json 中就会有问题吗?

**Comment by bang88** [comment]
我的意思是可以不用`typings.json `.

可以使用npm来安装对应的typings
```js
 "devDependencies": {
    "@types/react": "^0.14.48",
    "@types/react-dom": "^0.14.18",
    "@types/history": "^2.0.39",
    "@types/react-router": "^2.0.39",
    "@types/react-router-redux": "^4.0.34"
}
```
