### ISSUE TITLE
前端开发的应用架构请教

### ISSUE THREAD

**Issue by small752** [dvajs/dva#314]
我之前一直是做后台的，所以对前端开发的架构不是很了解；
请教个问题，我如何能在脱离后台架构的环境下单独用dva开发前端代码，  要请求数据时再向后台服务器请求。
这里目前设计到两个问题：
     1是web的跨域请求， 这个虽然我现在用nginx先简单的解决一下，感觉并不是很好的一个办法； 
      2是登陆信息是记录在后台session的，前端跨域请求并不能把cookie带上

**Comment by small752** [comment]
大神求指教。 真是纠结很久了

**Comment by seamys** [comment]
现在dva有开发服务器的. dora 加上反向代理配置就行了.

**Comment by small752** [comment]
好的  感谢

**Comment by nikogu** [comment]
看下这个例子：https://github.com/dvajs/dva/tree/master/examples/user-dashboard
相关文档：https://github.com/dvajs/dva-docs/blob/master/v1/zh-cn/tutorial/09-mock%E6%95%B0%E6%8D%AE.md
