### ISSUE TITLE
下面这种情况，怎么才能防止import 的时候 自动安装npm包？

### ISSUE THREAD

**Issue by edire** [dvajs/dva#316]
webpackConfig.externals = [{
        jQuery: 'window.jQuery',
        jquery: 'window.jQuery'
    }]

    webpackConfig.resolve.alias = {
        'user': __dirname + '/src/www/User'
    }

我require('user/abc.js') 的时候如何防止自动安装npm包？

**Comment by sorrycc** [comment]
配 `disableNpmInstall`，详见 https://github.com/dora-js/dora-plugin-webpack#options
