### ISSUE TITLE
dva对react的生命周期怎么处理的呢？

### ISSUE THREAD

**Issue by xwinie** [dvajs/dva#317]
dva处理react的生命周期是怎么处理的呢？

**Comment by sorrycc** [comment]
推荐不用，直接用 stateless function component 的方式，https://github.com/dvajs/dva-knowledgemap#stateless-functional-components

**Comment by xwinie** [comment]
componentDidMount componentWillMount 这些方法 也不在推荐使用了吗？

**Comment by lichinlichin** [comment]
那如何将draftjs的生命周期转换过来呢？

**Comment by sorrycc** [comment]
抱歉，对 draftjs 不了解。不强求 stateless function component，也可以用 class 的方法的。

**Comment by grunmin** [comment]
draftjs是通过修改自身state来进行内容更新的, 类似双向绑定, 用stateless的方式确实非常麻烦
