### ISSUE TITLE
dva component如果嵌套层级很深怎么处理呢？

### ISSUE THREAD

**Issue by zllc** [dvajs/dva#318]
比如  comA->comB->comC 。是在route component 中把comA comB comC  所需要的props都传递下去么？这样comA 会接收很多参数，还是comB comC 自己 调用dva的connect方法获取state呢

**Comment by seamys** [comment]
软件开发,其实是一种平衡艺术. 嵌套过深的组件可以独立封装成一个封闭的组件. 让组件自身维护

**Comment by zllc** [comment]
貌似还有使用 context 来解决的方案，只是没有找到例子

**Comment by sorrycc** [comment]
个人倾向于使用 `connect`。

**Comment by seamys** [comment]
@sorrycc 感谢你的建议 没有尝试这样做过. 等下重构过程中没有出问题. 会从新修改上面的答案
