### ISSUE TITLE
dva报错信息查看

### ISSUE THREAD

**Issue by zllc** [dvajs/dva#320]
开发dva应用时，有时会遇到js报错。比如

warning.js:36Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

但是不太好定位到是源码的哪个地方，有没有什么好的方法

**Comment by sorrycc** [comment]
非 dva 范围内的问题了，是否在 `render` 里使用 `setState` 了?

**Comment by zllc** [comment]
谢谢
