### ISSUE TITLE
less 无法热更新

### ISSUE THREAD

**Issue by xiangfengsu** [dvajs/dva#321]
使用dva new 一个项目 为什么less文件 无法热更新？

**Comment by sorrycc** [comment]
是个问题，dva-cli 下个版本会改进。

**Comment by cnptu** [comment]
改个东西总是要手动刷新,很不方便

**Comment by xiangfengsu** [comment]
@cnptu 我目前的解决办法是修改 webpack.config.js

if (env === 'development') {
    webpackConfig.babel.plugins.push(new webpack.HotModuleReplacementPlugin());
    webpackConfig.devtool = '#eval';
    
    // webpackConfig.babel.plugins.push(['dva-hmr', {
    //   entries: [
    //     './src/index.js',
    //   ],
    // }]);

  }
npm install --save-dev webpack-hot-middleware

这个可以自动刷新，但不是热更新，修改文件后会刷新页面

**Comment by haobingwang** [comment]
每次添加 ant 的新组件都要刷新下才可以显示样式，期待新版本的解决方案。

**Comment by sorrycc** [comment]
已解决，老用户参考这里升级下工具层，https://github.com/sorrycc/blog/issues/17 。
