### ISSUE TITLE
在处理类似进度问题的时候，saga effects的问题。

### ISSUE THREAD

**Issue by IveChen** [dvajs/dva#322]
因为需要在普通ajax请求或者file upload的时候，需要做一些进度的处理。
而effects的generator函数在处理这方面的方式有些复杂和蛋疼 https://stackoverflow.com/questions/40685288/redux-saga-upload-file-progress-event
所以您看能否在effect中返回一个dispatch函数供我们使用，用来处理那些非yield的异步写法中put函数失效的问题。= = 这样我们就不会限定死了一定要写成generator函数了。

**Comment by nikogu** [comment]
@IveChen 像这种情况，个人感觉不一定非要走 `effects`，异步回调反而更清晰

**Comment by mdluo** [comment]
https://github.com/dvajs/dva/issues/733
