### ISSUE TITLE
mac下dva new permission denied

### ISSUE THREAD

**Issue by jasminecjc** [dvajs/dva#323]
![image](https://cloud.githubusercontent.com/assets/13568376/20646063/e36bc118-b4ad-11e6-8a06-187ce6060444.png)
问题如上，全局安装了dva-cli，然后dva new就会报错，如果sudo dva new的话生成的项目就会变成只有root用户有权限，改所有者改成功了，还是无法保存文件,这问题已经折腾我几个小时了
![Uploading image.png…]()

**Comment by sorrycc** [comment]
用 [nvm](https://github.com/creationix/nvm) 安装 node，绕开权限问题，不要用 sudo 。

**Comment by jasminecjc** [comment]
@sorrycc 请教一个nvm的问题 。https://github.com/creationix/nvm/issues/1329   这个怎么解决呀

**Comment by nikogu** [comment]
@jasminecjc 重新装 node、npm、nvm 试试
