### ISSUE TITLE
请问如何配置使用 Redux Dev/Tool ?

### ISSUE THREAD

**Issue by zjxpcyc** [dvajs/dva#324]
RT

**Comment by sorrycc** [comment]
https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en

**Comment by zjxpcyc** [comment]
@sorrycc 看到官网了，没怎么看懂。都是说在 createStore 中插入使用，但是dva中有暴露的接口，或者我应该放到哪里吗？

**Comment by sorrycc** [comment]
dva 内置支持这个 chrome 插件的，不需要额外配置。https://github.com/dvajs/dva/blob/831b7d9/src/createDva.js#L167

**Comment by appLhui** [comment]
@sorrycc 你好 ，我在使用dva 1.2.1 这个版本的时候 ，突然 不能唤起 redux-devtools 了，我在源码里进行了搜索，发现没有把  window.devToolsExtension 打进 store里 ，是不是 改漏掉了？

**Comment by mmaiIconfont** [comment]
> @sorrycc 你好 ，我在使用dva 1.2.1 这个版本的时候 ，突然 不能唤起 redux-devtools 了，我在源码里进行了搜索，发现没有把 window.devToolsExtension 打进 store里 ，是不是 改漏掉了？

我们的dva版本是2.4.1（dva-core是1.4.0）也同样没法集成edux-devtools，所以只能改动了源码
`diff --git a/node_modules/dva-core/lib/createStore.js b/node_modules/dva-core/lib/createStore.js
index d82be98..2877720 100644
--- a/node_modules/dva-core/lib/createStore.js
+++ b/node_modules/dva-core/lib/createStore.js
@@ -45,6 +45,8 @@ function _default(_ref) {
     devtools = _window.default.__REDUX_DEVTOOLS_EXTENSION__;
   }

+  const composeEnhancers = _window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || _redux.compose;
+
   var enhancers = [_redux.applyMiddleware.apply(void 0, (0, _toConsumableArray2.default)(middlewares))].concat((0, _toConsumableArray2.default)(extraEnhancers), [devtools(_window.default.__REDUX_DEVTOOLS_EXTENSION__OPTIONS)]);
-  return (0, _redux.createStore)(reducers, initialState, _redux.compose.apply(void 0, (0, _toConsumableArray2.default)(enhancers)));
+  return (0, _redux.createStore)(reducers, initialState, composeEnhancers.apply(void 0, (0, _toConsumableArray2.default)(enhancers)));
 }`

然后通过[patch-package](https://www.npmjs.com/package/patch-package)把改动的部分patch到了这个版本上

**Comment by jxintang** [comment]
> @sorrycc 你好 ，我在使用dva 1.2.1 这个版本的时候 ，突然 不能唤起 redux-devtools 了，我在源码里进行了搜索，发现没有把 window.devToolsExtension 打进 store里 ，是不是 改漏掉了？

我们的dva版本是2.4.1（dva-core是1.4.0）也同样没法集成edux-devtools，所以只能改动了源码

diff --git a/node_modules/dva-core/lib/createStore.js b/node_modules/dva-core/lib/createStore.js
index d82be98..2877720 100644
--- a/node_modules/dva-core/lib/createStore.js
+++ b/node_modules/dva-core/lib/createStore.js
@@ -45,6 +45,8 @@ function _default(_ref) {
     devtools = _window.default.__REDUX_DEVTOOLS_EXTENSION__;
   }
  
+  const composeEnhancers = _window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || _redux.compose;
+ 
   var enhancers = [_redux.applyMiddleware.apply(void 0, (0, _toConsumableArray2.default)(middlewares))].concat((0, _toConsumableArray2.default)(extraEnhancers), [devtools(_window.default.__REDUX_DEVTOOLS_EXTENSION__OPTIONS)]);
-  return (0, _redux.createStore)(reducers, initialState, _redux.compose.apply(void 0, (0, _toConsumableArray2.default)(enhancers)));
+  return (0, _redux.createStore)(reducers, initialState, composeEnhancers.apply(void 0, (0, _toConsumableArray2.default)(enhancers)));
 }

然后通过[patch-package](https://www.npmjs.com/package/patch-package)把改动的部分patch到了这个版本上
