### ISSUE TITLE
css 样式问题。

### ISSUE THREAD

**Issue by roc2539** [dvajs/dva#327]
请问dva组件的样式是否必须是
import styles from './IndexPage.css'; 类似这样导入，
 di  v className={styles.normal}>
      di  v className={styles.title}  >Yay! Welcome to dva! 这样使用
而不能。
import './index.less';这样导入，
 di  v className="ant-layout-aside"> 这样使用？

**Comment by sorrycc** [comment]
不想用 css-modules，把这段删了就好了，https://github.com/dvajs/dva-cli/blob/1a4cb33/boilerplates/app/webpack.config.js#L19-L38 。

**Comment by roc2539** [comment]
@sorrycc  好的。 使用CSS-modules ，两个是否可以一起使用？

**Comment by sorrycc** [comment]
二选一吧。

**Comment by roc2539** [comment]
@sorrycc  好的 谢谢

**Comment by roc2539** [comment]
自己写的，样式，与antd的混用的时候。或是我要覆盖antd的部分样式的时候。 生效不了 ，比如这样。
.ant_layout_aside_collapse .ant_layout_sider > .ant_menu > .ant_menu_item:hover {
  background: #2db7f5;
  color: #fff;
  transition: all 0s ease;
}

**Comment by roc2539** [comment]
就得必须自己重新写样式。对吗？

**Comment by LuoTuxiu** [comment]
@sorrycc 能否class加hash和不加hash两者同时共存,该如何配置
