### ISSUE TITLE
支持同构应用吗

### ISSUE THREAD

**Issue by cllgeek** [dvajs/dva#328]
就是用dva怎么做服务器端渲染

**Comment by sorrycc** [comment]
https://github.com/sorrycc/dva-boilerplate-isomorphic

**Comment by cllgeek** [comment]
谢谢,太感谢了

**Comment by afc163** [comment]
问题解决建议自行关闭 issue，给官网维护人员减负。@cllgeek

**Comment by cllgeek** [comment]
@afc163 ok

**Comment by skyFi** [comment]
这里自己更新了下你这个服务器渲染，更加好用了，遂分享之。https://github.com/skyFi/dva-starter

**Comment by alexayan** [comment]
https://github.com/alexayan/express-dva-ssr
