### ISSUE TITLE
当前页面是一个表单，如果表单正在编辑，切换到其他的路由时，弹出一个提示框提示是否保存修改，这个在dva 中如何实现比较好？

### ISSUE THREAD

**Issue by summerwang0915** [dvajs/dva#329]

**Comment by ImJoeHs** [comment]
建议不做，单做这个无法处理直接改地址栏到其他网址的场景，要兼顾又只能统一使用丑陋的onunload，不如直接存localstorage。

**Comment by xutou12** [comment]
> 这个需求在表格编辑类的界面用的比较多，因为数据量很大很复杂。

**我现在的做法：**
做一个高阶组件封装```router.setRouteLeaveHook```函数套在表单的界面上层向下传递onChange()，hasChange()两个函数，实现未保存提示。

**Comment by nikogu** [comment]
楼上说的差不多，切换路由的事件就是 `routeLeaveHook`，至于是向下传递 `props`还是通过 `modal` 来做，看你的具体业务情况，一般推荐放到 `modal` 里
