### ISSUE TITLE
examples里面只有最后一个直接可以运行

### ISSUE THREAD

**Issue by jShi-git** [dvajs/dva#330]
系统环境:
macos Sierra

`$ node -v
v6.7.0`

`$ npm -v
3.10.3`

代码今天clone的，根目录执行了npm install，根目录执行了npm run build，lib目录正常生成了。然后在examples目录中，各个子目录下npm install之后，执行npm start，只有最后一个demo可以运行

都指向同一个错误：

`ERROR in /Users/shizuwu/sites/sources/react/dva/index.js
Module not found: Error: Cannot resolve module 'babel' in /Users/shizuwu/sites/sources/react/dva
 @ /Users/shizuwu/sites/sources/react/dva/index.js 7:18-34`

`ERROR in /Users/shizuwu/sites/sources/react/dva/mobile.js
Module not found: Error: Cannot resolve module 'babel' in /Users/shizuwu/sites/sources/react/dva
 @ /Users/shizuwu/sites/sources/react/dva/mobile.js 7:18-41`

看到以前有过同样问题的issues #53 ，现在的版本依旧不能使用npm3安装包吗？

===============
安装了npminstall

在根目录和子目录npminstall之后，npm run build直接报错
`$ npm run build

> dva@1.1.0 build /Users/shizuwu/sites/sources/react/dva
> rimraf lib && babel src --out-dir lib

module.js:457
    throw err;
    ^

Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/shizuwu/sites/sources/react/dva/node_modules/.6.18.0@babel-cli/lib/babel/index.js:4:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)`

**Comment by sorrycc** [comment]
在 dva 根目录也要 `npm i`。

**Comment by jShi-git** [comment]
@sorrycc
根目录有npm i

是包的访问路径的原因，修改demo中相关的引用就可以执行npm start，是在example的子目录中import根目录的index.js会报错

比如example->count 中
修改index.js
`import { connect } from '../../index';
改为
var connect = require('react-redux').connect;
`

`import dva from '../../src/index';
改为
import dva from 'dva'
`
