### ISSUE TITLE
同一台服务器上不能启两个dva

### ISSUE THREAD

**Issue by deific** [dvajs/dva#331]
和#179最后评论同样的问题。

`// 项目 A
"start": "dora -p 8000--plugins \"proxy?port=8002&watchDirs=./mock,webpack,webpack-hmr\"",
// 项目 B
"start": "dora -p 8001 --plugins \"proxy?port=9002&watchDirs=./mock,webpack,webpack-hmr\"",
`
启动后，先任意项目，另一个项目就会退出。
退出错误：
`Caught exception: Error: ENOENT: no such file or directory, open 'C:\Users\lix\.anyproxy\cache_r170601\res_body_1'
    at Error (native)
AnyProxy is about to exit with code: 0
`

**Comment by linginging** [comment]
对啊，没人回应这个问题，等回应

**Comment by nikogu** [comment]
看情况貌似是 Anyproxy 代理的问题，如果急的话，可以先把 `proxy` 这个插件去掉，如果不用代理的话
