### ISSUE TITLE
多个组件循环获取数据

### ISSUE THREAD

**Issue by s591698611** [dvajs/dva#332]
整个页面是一个大的数组，通过循环数组渲染页面
每个组件都有不同的dataUrl来获取后台数据
面临的问题是相同的组件每增加一个，都要在componentDidMount里设置
如果dataUrl是abc，就dispatch abc，如果是cba，就dispatch cba

这样有几个就要写几个，很麻烦
请问有没有什么解决办法

**Comment by nikogu** [comment]
我觉得可以，封装 `dispatch` 方法，抽象 `model` 对应的数据为数组
