### ISSUE TITLE
common.css生成不了？

### ISSUE THREAD

**Issue by zhump** [dvajs/dva#335]
求教
我注释了webpack.config.js下面的代码
`
  // Don't extract common.js and common.css
  webpackConfig.plugins = webpackConfig.plugins.filter(function(plugin) {
    return !(plugin instanceof webpack.optimize.CommonsChunkPlugin);
  });

`
npm run build 后
 common.js 生成了，但是  common.css 没有生成 ，dist文件夹下 只有 index.css，是不是要配置什么，才能把公共的css和业务的css分离呢？

**Comment by sorrycc** [comment]
这是 webpack 的问题，没有公共部分时并不会抽出 common.css 。

**Comment by YueHui** [comment]
有多个入口的时候才会生成common.css吧
