### ISSUE TITLE
全局异常捕获不到

### ISSUE THREAD

**Issue by l745230** [dvajs/dva#337]
![3a4a8fd4-62b1-46db-8cc0-c4e0c183aaf5](https://cloud.githubusercontent.com/assets/15940920/20745880/33949f1c-b71e-11e6-853f-f1b62ee9e7d8.png)
![a5f2f0a5-af80-475a-b858-7094d6fed19a](https://cloud.githubusercontent.com/assets/15940920/20745885/351851da-b71e-11e6-90aa-d900a80fd2d9.png)
按dva文档中加了parseErrorMessage,抛出异常,onError无法捕捉到

**Comment by codering** [comment]
去掉 
![image](https://cloud.githubusercontent.com/assets/2271825/20749731/91247f16-b72e-11e6-8fe5-c3a6bb7e43f7.png)
