### ISSUE TITLE
封装request.js接收不到返回的数据

### ISSUE THREAD

**Issue by wm3445** [dvajs/dva#339]
浏览器的statusCode  200 能查看到返回值

request.js 里返回错误 Error at checkStatus (webpack:///./src/utils/request.js?:23:15)

**Comment by nikogu** [comment]
@wm3445 具体场景描述下呢

**Comment by sorrycc** [comment]
跨域了?

**Comment by sorrycc** [comment]
Duplicated, https://github.com/dvajs/dva-cli/issues/26
