### ISSUE TITLE
请问是否支持异步请求的 abort 操作

### ISSUE THREAD

**Issue by xutou12** [dvajs/dva#340]
我在做SPA应用，路由频繁切换就必须要断开无用的请求，否则会出现 A 界面弹出 B 界面的请求完成提示
之前我不用redux做项目，ajax请求是高阶组件封装，跟随组件销毁而断开，很方便
**现在用dva不知道有什么方法可以让请求可以跟随组件销毁而断开？**

**Comment by sorrycc** [comment]
如果之前有效，可以按照你原来的方式来，数据层和视图层是分离的，所以不可能做到随组件销毁而做什么事。

**Comment by xutou12** [comment]
我之前的方式是在组件内部发起异步请求，逻辑与组件有一部分耦合，现在既然用了dva，还是想要尽量使数据层和视图层分离，我再想想其他方法吧

**Comment by nikogu** [comment]
我建议可以在 `router` 上面加 hook，然后自己封装一下 request，每次切换路由，处理所有请求 abort
