### ISSUE TITLE
下个版本升级一下history包？

### ISSUE THREAD

**Issue by ecafe8** [dvajs/dva#341]
index.bundle.js:1225 Uncaught Invariant Violation: You have provided a history object created with history v2.x or earlier. This version of React Router is only compatible with v3 history objects. Please upgrade to history v3.x

刚看了下，是react-router，history版本不一致，建议升级一下~

**Comment by sorrycc** [comment]
试了下 dva-cli 创建一个项目，并没有这个报错。我们现在 react-router 是 2.x, history 也是 2.x，应该没有问题。你在项目中有自己引 react-router 或 history 吗?
