### ISSUE TITLE
请问Webpack.config.js中的env参数是如何设置的？

### ISSUE THREAD

**Issue by yutingjin** [dvajs/dva#345]
![image](https://cloud.githubusercontent.com/assets/2681766/20822415/886b6e86-b885-11e6-8f6f-32ada4ee3b1f.png)

我尝试设置node_env到production，但是这里的参数始终是development，请问要如何配置才能让这里的env生效呢？

我得配置：
"start": "cross-env NODE_ENV=production dora -p 8089 --plugins \"webpack,browser-history?index=/src/index.html\"",

谢谢

**Comment by sorrycc** [comment]
不需要配的。`npm run build` 是 `production`，用于生产环境；`npm start` 是 `development`，用于开发环境。

**Comment by sunOpar** [comment]
有什么办法能自己手动改么

**Comment by sorrycc** [comment]
为啥要手动改？

**Comment by sunOpar** [comment]
我这边的后台接口有不止两种环境。
想在打包的时候自动根据环境修改后台接口

**Comment by sorrycc** [comment]
可以用非 NODE_ENV 的环境变量，然后在 `webpack.config.js` 里判断。

**Comment by sunOpar** [comment]
```
"build": "SELF=local && atool-build dev"
```
这样可以么，我用process.env.SELF读不到

**Comment by sorrycc** [comment]
`SELF=local atool-build` 就可以了，在 `webpack.config.js` 里判断 `process.env.SELF`。

**Comment by sunOpar** [comment]
多谢！！
