### ISSUE TITLE
dva基于action的路由跳转是否可以支持链接在新窗口中打开

### ISSUE THREAD

**Issue by jindada** [dvajs/dva#347]
基于action的路由跳转 put/dispatch(routerRedux.push(URL)) 这种方式 是否可以在浏览器的新窗口中打开

**Comment by nikogu** [comment]
不支持，两回事，如果有新开窗口的需求，直接调用 `window.open`，然而大多数时候都会被阻止

**Comment by jindada** [comment]
不是window.open 可能是我描述的有些歧义 是指在浏览器新标签页打开 例如a标签的 target=“_blank”

**Comment by afc163** [comment]
为何不直接使用 `<a target="_blank" />`

**Comment by zhouyingkai1** [comment]
@afc163 因为是在事件中去跳转，  你说为何不直接使用   `<a target="_blank" />`

**Comment by xiaowangmm2** [comment]
我也有这个问题，目前好像确实只能使用window.open
