### ISSUE TITLE
组件重复渲染的问题

### ISSUE THREAD

**Issue by zhump** [dvajs/dva#348]
以user-dashboard例子参考(实际项目也发现了这个问题)

在 src/routes/Users.jsx 16行处，填入  console.log("list",users.list)

在浏览器中敲入 http://localhost:8989/users ,控制台会打印出，list =>[]  ,list=>[{xx},{xxx}]， 这个代码被执行了两次，其实也可以理解，第一进来的时候 list为空，进去一次，后来ajax回来了，list改变，又进去一次，

这个时候，点击搜索按钮，控制台打印出 list=>[{xx},{xxx}] ，list=>[{xx},{xxx}] ，又进来两次，他第一次拿着上一次的数据进去渲染了，然后ajax回来了，又渲染一次了。

我在 组件 return 处 打印了 日志，发现确实进去了，但是其实真实dom并没有去渲染，不知道是不是react内部判断没有变化，没有渲染dom,

说这么多，我就想问一句。。我是不是得写个 shouldComponentUpdate 判断 (JSON.stringify(xx) === JSON.stringify(next.xxx)) .....不让他去 render .... 
 感觉好不严谨，但是我也没有什么好的办法。。。

如果真这样的话，关联models的组件，都不能用无状态组件，因为要写shouldComponentUpdate 。。。

大神们 你们是怎么解决的。

**Comment by nikogu** [comment]
个人感觉没必要，react 自己会做 dom diff，除非是遇到了性能问题，否则不需要自己单独做额外处理

**Comment by sorrycc** [comment]
1. 重复渲染是因为 connect 的数据变了，可以借助 [reselect](https://github.com/reactjs/reselect) 做缓存，避免不必要的重复渲染
1. 如 @nikogu 所言，性能问题在遇到前先不用考虑，react 通过 dom diff 已经能保证大部分场景下不会有性能瓶颈问题

**Comment by zhump** [comment]
感谢回复 请问 reselect会整合到dva中吗， 能出个dva使用reselect示范吗?万谢....

**Comment by sorrycc** [comment]
不会，reselect 放在 connect 的时候用就好了，详细的看他的文档吧。

**Comment by zhump** [comment]
我现在是离开一个路由清除某个model.namespace的state数据，防止再进去二次渲染。。这么解决的。。

**Comment by jasminecjc** [comment]
希望出重复渲染解决方案的教程
