### ISSUE TITLE
dva项目如何做服务器端渲染（从而提高首屏加载速度）？

### ISSUE THREAD

**Issue by wanthering** [dvajs/dva#350]
在网站部署过程中，发现仅仅是基出nginx的gzip配置，仍然无法让一个dva项目加载速度控制下去，大量的解决方案指向了“服务器渲染”技术。

例如这篇文章：https://cnodejs.org/topic/5660f8f9d0bc14ae27939b37

它的关键点在于将初始状态存入store，再用renderToString转为html代码后，通过store.dispatch进行交互。
const initialState = window.__INITIAL_STATE__;
const store = configureStore(initialState);

但是！由于dva的封装并不暴露store，要进行服务器端渲染应该怎么做呢？

**Comment by sorrycc** [comment]
https://github.com/sorrycc/dva-boilerplate-isomorphic

**Comment by cycgit** [comment]
我也遇到同样的问题。
需要暴露store 这样服务端能够通过dispatch 生成 state。

**Comment by sorrycc** [comment]
@cycgit 可以参考 https://github.com/sorrycc/dva-boilerplate-isomorphic ，只不过目前有个 bug #303 ，会尽快修复。

p.s. 如果一定要用 store，可以先通过 `app._store`。

**Comment by szwork2013** [comment]
现在的主要问题是子路由f5刷新后(或用户直接从子路由ex: /about) 还是要从服务器访问：我觉得ssrMiddleware.js里的路由不能那么写，服务器的路由是不能跟客户端的路由冲突的。

**Comment by wanthering** [comment]
我找到了这个神器 [https://github.com/wssgcg1213/koa2-react-isomorphic-boilerplate](url)

**Comment by sorrycc** [comment]
先 Close 了，有问题再开 issue 。
