### ISSUE TITLE
fetch以post方式提交，php后台拿不到提交的值

### ISSUE THREAD

**Issue by dan-me** [dvajs/dva#352]
官方示例代码中get和post 两种请求方式，为什么php后台可以拿到get提交的params，而post提交的拿不到params

```
export async function create(params) {
  return request('/api/users', {
    method: 'post',
    body: qs.stringify(params)
  });
}

export async function create(params) {
  return request('/api/users?{qs.stringify(params)}',);
}
```

**Comment by wanthering** [comment]
/*  services/***.js  */
import request from '../utils/request';
import qs from 'qs';

export async function query(params) {
  return request(config.server.local+`creations/renderonline?${qs.stringify(params)}`);
}

export async function queryonedetail(params) {

  return request('http://write.your.site.here/port.php', {
    method: 'POST',
    headers:{'Content-Type':'application/json'},
    body: JSON.stringify(params)
  });
}

**Comment by dan-me** [comment]
@wanthering  你的这种方法不行哦！

**Comment by lincenying** [comment]
配置header的Content-Type:"application/x-www-form-urlencoded; charset=UTF-8"

**Comment by dan-me** [comment]
问题解决了 !
https://segmentfault.com/a/1190000003982703
http://www.kuitao8.com/20140727/2867.shtml
