### ISSUE TITLE
ant-design 样式问题

### ISSUE THREAD

**Issue by MaYing929** [dvajs/dva#353]
想实现table 列宽度，然后超出部分省略号表示

 {
      "title": "商户名称",
      "dataIndex": "name",
      "key": "name_2",
       width:'150px',
       className:'nameWidth'
    },

 .nameWidth{
    display: inline-block;
    overflow: hidden;
    text-overflow:ellipsis;
    white-space: nowrap;
    background-color: aqua;
  }

不起作用，有小伙伴遇到过吗

**Comment by cycgit** [comment]
```{
"title": "商户名称",
"dataIndex": "name",
"key": "name_2",
width:'150px',
render(text) {
  return (<div className="nameWidth">{text}</div>)
}
}
```

**Comment by nikogu** [comment]
@MaYing929 建议自己调试哈，这属于前端基础
