### ISSUE TITLE
dva能不能不依赖react，这样就可以和小程序结合。

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#354]
dva用在网页端和rn都不错，这样让开发网页的和开发手机的可以互通。现在希望dva在微信小程序中使用，可是我发现它需要依赖react和react-dom，因为小程序限制1M，所以能够小尽量小，我知道在rn中已经不需要react-router了，能不能进一步不需要依赖reactjs呢？

**Comment by sorrycc** [comment]
我试着把数据流和视图绑定分离看看。

**Comment by roc2539** [comment]
额 前段直接用html5？

**Comment by zerozaki0752** [comment]
最近在开发小程序 reactjs分离已经列上日程了吗？

**Comment by sorrycc** [comment]
@zerozaki0752 YES 。

**Comment by neeboo** [comment]
@sorrycc
看到有人尝试 参考一下
https://github.com/maichong/labrador

**Comment by zerozaki0752** [comment]
@neeboo
知道这个项目 就是想结合dva的modal模块
现在需要在dva中去掉react的依赖

**Comment by sorrycc** [comment]
这里先关了，有兴趣请到 #530 跟进进度。
