### ISSUE TITLE
favicon.ico 引用不成功，打包后也不存在？

### ISSUE THREAD

**Issue by zhump** [dvajs/dva#355]
我把favicon.ico放在与index.html同级目录中
index.html中 引用并没有成功 
 `<link rel="Shortcut Icon" href="favicon.ico" />`

**Comment by sorrycc** [comment]
需要自己配 webpack 配置，比如通过 WebpackCopyPlugin 复制过去。

**Comment by zhump** [comment]
搞定了，多谢。。
`
 webpackConfig.plugins.push(
      new CopyWebpackPlugin([
         { from: __dirname+'/src/favicon.ico', to: 'favicon.ico' },
      ])
   )
`
