### ISSUE TITLE
向 DefinePlugin 里面添加值

### ISSUE THREAD

**Issue by nianhua110** [dvajs/dva#358]
由于有两个系统，只有少部分不同，我决定用类似于C语言宏的方式来实现预编译。
所以打算在DefinePlugin里面添加一个字段，用来区分是哪个项目。
请问该如何实现呢？

**Comment by sorrycc** [comment]
在 webpack.config.js 里通过 DefinePlugin 配就好了。

**Comment by nianhua110** [comment]
谢谢，解决了。
  webpackConfig.plugins.push(new webpack.DefinePlugin({ UK: true }));
