### ISSUE TITLE
项目选型疑问

### ISSUE THREAD

**Issue by zxtyjx** [dvajs/dva#361]
目前公司在做前端框架选型，基本确定使用React+Redux来完成，但是突然看到dva后觉得很方便，大大降低了员工对React和Redux的学习成本，不过针对dva有以下几个问题希望作者抽空可以为我解惑：
1、该项目是什么时候推出的？
2、该项目是由支付宝的技术团队在做维护吗？
3、该项目有无阶段性的更新计划、或者更新频率如何？
4、目前该项目的实际使用情况如何？比如有无中大型项目采用dva？
5、能否支持async/await代替Generator函数？
6、采用model概念后，要如何维护全局的Store，因为我们首屏需要进行服务器端渲染，所以需要在Server端初始化Store

麻烦作者看看我的问题，帮忙解答谢谢~~~

**Comment by afc163** [comment]
https://github.com/sorrycc/blog/issues/6

**Comment by afc163** [comment]
5: https://github.com/dvajs/dva/issues/134
6: https://github.com/sorrycc/dva-boilerplate-isomorphic

先搜索是个好习惯。

**Comment by zxtyjx** [comment]
@afc163
了解了，谢谢！
