### ISSUE TITLE
请教下ant design的tree与dva的结合问题

### ISSUE THREAD

**Issue by logyLiang** [dvajs/dva#363]
antd异步加载的tree感觉是局部页面刷新，而不是整个组件刷新，也就是说是否不适用于dva脚手架的component、route、model三层？没思路了，按三层做蒙圈了

**Comment by sorrycc** [comment]
state 放 component state 还是 dva model 的区别，局部刷新是 react 做的，所以渲染上不会有差别。

**Comment by logyLiang** [comment]
不是很理解。感觉后台程序猿一弄复杂的组件就萎了。有参考的链接么？

**Comment by sorrycc** [comment]
没有。建议参考 dva 的文档把概念理解清楚了，Tree 和其他组件并没啥区别。

**Comment by logyLiang** [comment]
好吧

**Comment by jindada** [comment]
我也遇到了同样的疑问 @logyLiang @sorrycc 怎么才能dispatch action之后在执行 resolve() 那
```js
const onLoadData = (treeNode) => {
    return new Promise((resolve) => {
      dispatch({ type: 'demo/filter' });
      resolve();
    });
  }

<Tree loadData={onLoadData}>
````

**Comment by xufei** [comment]
@jindada  https://github.com/dvajs/dva/issues/175

需要把resolve放在action上传进去……

**Comment by jindada** [comment]
嗯嗯 刚刚已经想到了 谢谢你
