### ISSUE TITLE
any guide for non-SPA page?

### ISSUE THREAD

**Issue by pixystone** [dvajs/dva#365]
I want to create a component to do some complex things, with models and services only, without any routes and mount point

**Comment by sorrycc** [comment]
Create a component containing view, model, services? Then how to use it? And need to customise it when using it?

**Comment by pixystone** [comment]
Yes, a component with same view and models, different services across  different projects.

**Comment by pixystone** [comment]
In another situation, how to use dva in a multi-entry(in package.json) project? That is what "non-SPA" means, a structure like `antd-init` created
