### ISSUE TITLE
mock数据取不到

### ISSUE THREAD

**Issue by hellheaven** [dvajs/dva#367]
以前可以用的，现在会出现访问不到数据的情况。
试了下在request的时候，加上端口则可以访问
如：
export default function request(url, options) {
  url='http://localhost:8989'+url;

**Comment by sorrycc** [comment]
没明白问题，是 mock 了访问不到，还是请求的 url 不对?

**Comment by hellheaven** [comment]
mock了访问不到，fetch('/api/xxx')不行。
fetch('http://localhost:8989/api/xxx')可行。

**Comment by sorrycc** [comment]
html 页面的端口不是 8989 ?

**Comment by hellheaven** [comment]
之前没注意，一直用的8000。。。
