### ISSUE TITLE
install后出错    帮忙看下为啥

### ISSUE THREAD

**Issue by sexyios** [dvajs/dva#369]
![ysfs smr0xmb ph2k 0a6ek](https://cloud.githubusercontent.com/assets/8684040/21003290/80b4a52e-bd65-11e6-813f-9da579759a4d.png)

**Comment by sexyios** [comment]
除了最后一个小例子   其它的案例应该都有报这样的错误

**Comment by sorrycc** [comment]
在 dva 目录也要 `npm install`。

**Comment by sexyios** [comment]
感谢你的回复  安装完后提示没有lib这个文件  
![rsy242i3 iab87 4 kyi](https://cloud.githubusercontent.com/assets/8684040/21036622/2dac698c-be02-11e6-8afe-146d24480ce2.png)

**Comment by sorrycc** [comment]
`npm run build` 试试。

**Comment by sexyios** [comment]
谢谢   但是还是报一样的错  构建不了啊

**Comment by sorrycc** [comment]
那帮不上忙了，windows 下没试过是否可以。

**Comment by zhangxueru** [comment]
报这个错，不知道什么意思，这个GLOBAL是什么？请问……
> @ start D:\bbb\dva-master\examples\user-dashboard
> dora --plugins "proxy,webpack,webpack-hmr,browser-history?index=/src/index.html"

          proxy: load rule from proxy.config.js
(node:3128) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8989
Caught exception: Error: listen EADDRINUSE :::8989
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at D:\bbb\dva-master\examples\user-dashboard\node_modules\.3.8.4@dora-anyproxy\proxy.js:125:38
    at D:\bbb\dva-master\examples\user-dashboard\node_modules\.0.9.2@async\lib\async.js:607:21
    at D:\bbb\dva-master\examples\user-dashboard\node_modules\.0.9.2@async\lib\async.js:246:17
    at iterate (D:\bbb\dva-master\examples\user-dashboard\node_modules\.0.9.2@async\lib\async.js:146:13)
    at D:\bbb\dva-master\examples\user-dashboard\node_modules\.0.9.2@async\lib\async.js:157:25
AnyProxy is about to exit with code: 0

**Comment by sorrycc** [comment]
>  Error: listen EADDRINUSE :::8989

端口被占用了。
