### ISSUE TITLE
classnames 如何使用模块化的css

### ISSUE THREAD

**Issue by l745230** [dvajs/dva#370]
这样写,全局的css会生效
![2cc01d86-14ca-4c10-8e39-c5944b047067](https://cloud.githubusercontent.com/assets/15940920/21003519/c6f5d566-bd66-11e6-93bb-93efac47c760.png)

如何改成使用模块化的css
![e3a27be9-e1a4-480c-b2aa-99e71aeeefa5](https://cloud.githubusercontent.com/assets/15940920/21003544/efb2e44e-bd66-11e6-9029-eff226d396a0.png)

**Comment by l745230** [comment]
![6dbab0d6-2311-4ed4-9682-0e0018608032](https://cloud.githubusercontent.com/assets/15940920/21003610/53914186-bd67-11e6-9a86-d9ed35f12d9d.png)
去classnames的github上找到了...

**Comment by sorrycc** [comment]
`[styles.left]` 就好，`[]` 里支持变量的。
