### ISSUE TITLE
dva model问题请教

### ISSUE THREAD

**Issue by kimoziiiii** [dvajs/dva#372]
我是新手，以前经常写些JS操作DOM，对前端的了解也仅此而已。最近因为要调研后台项目的前端选型，这周花了些时间对DVA的技术栈了解了一些，然后学习了[教程：教你如何一步步完成一个中型应用](https://github.com/dvajs/dva-docs/blob/master/v1/zh-cn/tutorial/01-%E6%A6%82%E8%A6%81.md) 。 这里我突然会有各疑问，是不是比如侧边栏也要设计Model，然后对侧边栏定义一些状态和Reducer，组件设计中对侧边栏设置属性，然后在容器组件中对其中的属性值进行传递。有垫颠覆我以前使用传统的WEB设计不一样，但直觉是好这么做好麻烦。很惭愧，很多参数我其实还是没看懂，非常希望有个应用比较丰富的模版来模仿并学习其中的思想。

**Comment by sorrycc** [comment]
有数据就要定义 State，有交互才要定义 Reducer 。如果侧边栏是全静态的，那么写死到 Component 里也是可以的。

**Comment by kimoziiiii** [comment]
感谢你的回复。有计划做些更为系统详细的教程吗？ 什么从开始到精通系列的 :)

**Comment by sorrycc** [comment]
可以先看看这些：

- https://github.com/dvajs/dva-knowledgemap
- https://github.com/dvajs/awesome-dva
