### ISSUE TITLE
dva中关于类似ant design 中Upload的受控组件用法

### ISSUE THREAD

**Issue by xyzget** [dvajs/dva#373]
项目中使用了dva，dva是一个很棒的项目
但是在使用Upload组件时遇到了问题，Modal中嵌套Form，FormItem中嵌套Upload，但是Upload是受控组件，我封装成了一个React Component，在数据切换的时候（例如create切换到edit）因为Upload已经初始化了，导致Upload的fileList属性没有更新，像这种场景有最佳实践吗？
是不是需要专门定义一个model，通过redux来管理Upload的state呢？

**Comment by pixystone** [comment]
给Upload一个key属性，强制每次都重新mount一个新组件，是否满足你的需求？
