### ISSUE TITLE
URL路径和路由及参数的疑问

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#374]
我们本地搭建起来项目之后访问地址是：`http://localhost:8989/#/user`

其中 `user` 是 routes 下面的一个路由模块，

要是 `user` 下面还有 子级，要如何设定呢？ 如下
 `http://localhost:8989/#/user/info` 

我好像从来没看到过谁用 dva 搭建的项目用了类似上面这样的路径

 `info` 可以理解为 `user` 下属的小组件，但是，按照我目前的理解，

dva项目所有路径都是一个路由模块，都要写到 `routes` 下，才可以访问到，是这样？

请问大家有方案么？能让我实现，下列的路径访问

 `http://localhost:8989/#/user/info`

**Comment by sorrycc** [comment]
https://github.com/ReactTraining/react-router/blob/v2.8.0/docs/guides/RouteConfiguration.md
