### ISSUE TITLE
我在model中只能取本model的state 如何取全局的state，一定是在effects中吗？

### ISSUE THREAD

**Issue by roc2539** [dvajs/dva#375]
我在model中只能取本model的state 如何取全局的state，一定是在effects中吗？
还有资源权限拦截是在router中做吗？用React Router的，那我在那里怎么获取全局的state？ 比如我要判断是否已经登录了！或是获取state中的权限数据。

**Comment by sorrycc** [comment]
> 我在model中只能取本model的state 如何取全局的state，一定是在effects中吗？

是的，只能在 effect 中取，其他地方没有取的必要。https://github.com/dvajs/dva-knowledgemap#select

> 还有资源权限拦截是在router中做吗？用React Router的，那我在那里怎么获取全局的state？

在请求时判断返回值，如果未登录，Promise.reject 掉。在 effect 中 try...catch 这个请求，捕获出错，判断出未认证状态时可做跳转或其他操作。(类似场景多，可以提取到全局的 onError hook，统一处理未认证状态的跳转)

**Comment by roc2539** [comment]
请求是判断？ 您是指登录请求吗？
那如果我需要在进入其他页面的时候判断登录状态呢？ 在全局的 hook中做？ 那还是要取全局状态吧？

**Comment by roc2539** [comment]
现在我只能在subscriptions监听事件，然后发到effects处理。对吧？

**Comment by roc2539** [comment]
然后effects中该跳转，还是怎么处理就直接做掉。对吗？
