### ISSUE TITLE
一个组件加载，我如何拦截？ 或是要怎么初始化数据。不是router，是组建。

### ISSUE THREAD

**Issue by roc2539** [dvajs/dva#376]

**Comment by roc2539** [comment]
这种情况是不是只能使用React的生命周期来弄了？

**Comment by wangking873** [comment]
可以使用高阶组件包装 拦截

**Comment by roc2539** [comment]
@wangking873  高阶组建？ 包装起来?

**Comment by roc2539** [comment]
@wangking873 好处是什么？

**Comment by sorrycc** [comment]
没明白意思，拦截组件加载是什么意思?

**Comment by roc2539** [comment]
@sorrycc 我组建就是一个页面。使用antd的tabs包起来的。使用的时候在加载组建的时候我要初始化里面的Table

**Comment by roc2539** [comment]
@sorrycc  您明白我意思了吗？就是和react组件生命周期一样的。我需要对一个封装了组件做一些数据初始化

**Comment by sorrycc** [comment]
> 组建就是一个页面

不就是 route component ? 

> 我需要对一个封装了组件做一些数据初始化

走 dva 的 model 不能满足需求?

**Comment by roc2539** [comment]
不是 route component  ，
类似下面的函数 antd的Tabs,中添加。我直接添加了一个组件。 也就是一个页面。没有走路由的。
  add() {
    const panes = this.state.panes;
    const activeKey = `newTab${this.newTabIndex++}`;
    panes.push({ title: 'New Tab', content: 'New Tab Pane', key: activeKey });
    this.setState({ panes, activeKey });
  },
![image](https://cloud.githubusercontent.com/assets/22289965/21085098/303178da-c048-11e6-940a-0593a8f513e0.png)

**Comment by sorrycc** [comment]
走 setState 就和 dva 没啥关系了，按照传送的 react 方式处理就好了。

**Comment by roc2539** [comment]
没有，上面只是antd的例子。我的代码不是这样。我主框架页面的代码还是在model中管理的state，只是我使用了antd的Tabs标签。每个标签也中加载都是一个页面。然后每个页面都是一个组件 ，不是 route component ，没有走路由，我不知道怎么订阅监听他。
下面是加添tab的代码
 const panes = state.panes;
        const activeKey = key;
        panes.push({ title: name, content: pages(key), key: activeKey });
        return { ...state, panes, activeKey };


![image](https://cloud.githubusercontent.com/assets/22289965/21085168/f8771b92-c048-11e6-9d60-030f118d5966.png)


下面是获取组件的代码
import React, { Component, PropTypes } from 'react';
import Users from './Admin/Users';
import Roles from './Admin/Roles';
import Resources from './Admin/Resources';
import NotFound from './NotFound';
import Welcome from './Welcome';

const pages = (key) => {
    if (key == '/welcome') {
        return (<Welcome />);
    }
    if (key == '/admin/users') {
        return (<Users />);
    }
    if (key == '/admin/roles') {
        return (<Roles />);
    }
    if (key == '/admin/resources') {
        return (<Resources />);
    }

    return (<NotFound />);
}
export default pages;

**Comment by roc2539** [comment]
@sorrycc  你们做这种的时候使用其它的方法做的。加载的时候用了route component  ？

**Comment by roc2539** [comment]
![image](https://cloud.githubusercontent.com/assets/22289965/21085218/ebd5c392-c049-11e6-821f-81a9598a7360.png)
上面有些kan'bu'qing'c看不清楚。

**Comment by roc2539** [comment]
还是我使用上面那位大哥提到的 高阶组件，再封装一下。来管理生命周期

**Comment by roc2539** [comment]
@wangking873 您做的时候就是用高阶封装了一次的吗？

**Comment by roc2539** [comment]
@sorrycc 如果我是直接加载route component，可以走model的state管理吗？ 还能做进入页面的监听吗？

**Comment by sorrycc** [comment]
需求是用 antd 的 tab，但是切换的时候不走路由(URL 跳转)?

**Comment by sorrycc** [comment]
> 需求是用 antd 的 tab，但是切换的时候不走路由(URL 跳转)?

如果是这样的话，推荐用 dva 的 model 存数据，tab 切换时触发 reducer 修改数据，component 里根据数据渲染不同的 tab 。(当然，也可以不存 dva model，用 react 的 component state 或 Hight Order Component 管理 state 都可以的)

**Comment by roc2539** [comment]
用 antd 的 tab ，切换的时候可以走路由吗？ 我明白你意思了。我直接在在tab事件函数里面触发数据加载。我找找看。

**Comment by roc2539** [comment]
state管理走dva的model。我觉得很方便。统一。 只是在触发数据加载的时候。找不到触发的地方。 如果是route component 可以是还可以subscriptions中定于定history的路由事件。对吧？

**Comment by tianlizhao** [comment]
@roc2539 #506
