### ISSUE TITLE
当有错误发生时，我的console 错误信息闪一下就不见了，页面变成空白

### ISSUE THREAD

**Issue by sunui** [dvajs/dva#379]
console里面只剩下

`[HMR] inited with babel-plugin-dva-hmr`
`client.js:58 [HMR] connected`

用的linux 系统，我什么也没做，使用dva-init生成了模板就有这个问题，不能调试，只要有错误就一片空白，不显示错误信息．
控制台输出：
`(node:15778) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
`
`(node:15778) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
`

**Comment by sorrycc** [comment]
有错误发生时这样? 没有错误发生时正常?

**Comment by sunui** [comment]
没有错误页面正常，控制台看不到任何eslint输出，可能是热加载和哪个loader有冲突？

**Comment by nikogu** [comment]
@sunui 截个图吧？

**Comment by sunui** [comment]
已经解决了，解决办法是更改 webpack.config.devtool 为 ' source-map '　，默认的是 eval 但我想不通为什么会影响输出控制台报错．
```
  // Support hmr
  if (env === 'development') {
    webpackConfig.devtool = '#source-map';
    webpackConfig.babel.plugins.push('dva-hmr');
  } else {
    webpackConfig.babel.plugins.push('dev-expression');
  }
```

一开始的状况就是当有错误发生时（比如有变量未定义）页面一片空白，报错信息一闪而过，页面刷新控制台只输出
`[HMR] inited with babel-plugin-dva-hmr`
`client.js:58 [HMR] connected`

**Comment by sorrycc** [comment]
可以换 cheap-module-source-map，比 source-map 快很多。

**Comment by sunui** [comment]
OK 谢谢！
