### ISSUE TITLE
无状态组件内部控制元素的隐藏,非得借助model的state么?

### ISSUE THREAD

**Issue by truhangle** [dvajs/dva#380]
官方很多空间的例子都是有状态的,看了很多官网推荐的文章跟例子,都是基于无状态的,那么无状态的页面组件上,当某个change或click事件触发以后,要控制同页面某些控件的样式或属性值改变,怎么做?
1:把组件改成有状态的(改动太多)
2:组件不用改成有状态,但是通过model的state设置属性去控制(改动太多)
3:还有其它办法吗?

**Comment by sorrycc** [comment]
推荐方法 2。无状态的目的就是把状态提出去，不然为啥用无状态组件呢?

**Comment by grunmin** [comment]
我的想法是容器组件无状态, 只有逻辑, 数据全放store. 展示组件有状态, 数据从props传进来, 组件没有connect到store, 全靠容器组件传入actions.

**Comment by zhouzefei** [comment]
我也有一个类似的疑问：
![image](https://cloud.githubusercontent.com/assets/8566935/23575717/ddeaffae-00cc-11e7-92b8-fa60c3b9639d.png)
这种写法不去dispatch就不会挂到一颗总的state树，，可能我dva的用法有问题，现在通过model的写法状态都通过dispatch，，如何维护内部而不暴露状态
