### ISSUE TITLE
页面加载顺序问题

### ISSUE THREAD

**Issue by sevennights** [dvajs/dva#383]
在项目里有时候会用到图标之类的插件，这些类插件大多会需要ID确认插件的加载位置，这个时候就需要类似于react中componentDidMount的方法在dom操作之后进行加载插件，想问下dva有没有能实现类似的方法或者思路解决此类问题

**Comment by afc163** [comment]
这和 dva 有什么关系么，dva 没有限制你不能用 `componentDidMount` 吧？

**Comment by sevennights** [comment]
是的 我理解你说的 我现在的解决方案也是写react的组件 想了解下 在dva中有没有遵循dva的写法的处理方式 毕竟现在用的是这个框架 如果能够按照框架规则写的话 尽量还是不用之前写法

**Comment by afc163** [comment]
dva 没有限制这个规则。

**Comment by sevennights** [comment]
👌  了解了 那我先用 componentDidMount 这种写法写一下 再想想能不能不用这种办法解决 谢谢
