### ISSUE TITLE
models 中如何获取路由参数

### ISSUE THREAD

**Issue by liyunsong** [dvajs/dva#384]
![这个图点击能看到](http://tbfile.ixiaochuan.cn/img/view/id/32005214)
 如图

我的路由设置是“browserHistory”,有一个详情页需要根据帖子 ID 获取数据，我怎么在models中获取这个 id

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva-knowledgemap#异步数据初始化

**Comment by liyunsong** [comment]
谢谢  完美解决
