### ISSUE TITLE
怎么替换mockjs，请求服务器数据？

### ISSUE THREAD

**Issue by dongfangx** [dvajs/dva#39]
Hi, 
在使用dva的过程中，参照user-model的demo。遇到一个问题，
怎么替换mockjs，请求服务器数据？

**Comment by nikogu** [comment]
```diff
// package.json
"scripts": {
-  "start": "dora --plugins \"proxy,webpack,webpack-hmr\"",
+  "start": "dora --plugins \"webpack,webpack-hmr\"",
    "lint": "eslint --fix --ext .js,.jsx .",
    "build": "atool-build"
  }
```
package.json里面修改一下script即可

**Comment by dongfangx** [comment]
Thank you!

**Comment by CodingMonkeyzh** [comment]
@nikogu Hi，我现在跟队友合作开发应用，我负责前端部分，队友负责提供 Restful API 并部署到服务器。 请问我在本地开发过程中（通过 `npm start` 进行调试），调用服务器的API时存在跨域的问题，请问如何处理比较好？

**Comment by CodingMonkeyzh** [comment]
再起一个node.js服务器做中间件是最好的方案吗？或者有没有不需要在本地运行中间件就能搞定的

**Comment by sorrycc** [comment]
https://github.com/dora-js/dora-plugin-proxy#规则定义
可以 forward 到你队友的服务器。
