### ISSUE TITLE
React Native 如何热更新？

### ISSUE THREAD

**Issue by r4ggj** [dvajs/dva#390]
每次都手动刷新，影响开发效率，在考虑是否用dva了

**Comment by nikogu** [comment]
https://github.com/dvajs/babel-plugin-dva-hmr

**Comment by Liuthx** [comment]
@sorrycc
React Native的热更新有近期处理的计划吗?

**Comment by sorrycc** [comment]
> React Native的热更新有近期处理的计划吗?

近期没有计划，如果谁有做过，可以提供点线索。RN 的热替换和 React 的有啥区别吗?

**Comment by bcgenevev7** [comment]
我開發react native時，Component如果用const 建立就無法hot reloading，用class建立就可以，可以試試看。

**Comment by bcgenever7** [comment]
詳細一點，就是使用es6 class建立的component可以hot reloading, 使用stateless function建立的無法，我現在是使用class 建立 container component，用 stateless function 建立presentational component 。

**Comment by r4ggj** [comment]
经过无数次尝试，证明楼上的的说法有一定道理，但不完全正确，更正如下：
1.app 顶层 与 创建dva 应用同一目录用ES6 class的方法创建顶层Component；
2.顶层Component引入定义路由的 Stateless function;(注意：第二层一定要是function组件！！！不要问我为什么，我也不知道；试出来的。。。)；
3.第三层其它页面，随便你用那种方式创建组件，都可以热重载了！！！
结语：自己提出的问题，还是自己解决了。。。。

**Comment by vance-liu** [comment]
@r4ggj 有没有例子呢，现在很烦
