### ISSUE TITLE
如何做权限校验

### ISSUE THREAD

**Issue by ityao** [dvajs/dva#395]
1. 在auth的model里面判断是否做过登录, 未做登录则去做自动登录
subscriptions: {
    //全局登录检查
    setup({ dispatch, history }) {
      history.listen(location => {
        if (['/login','/signup'].indexOf(location.pathname) == -1) {
          //非登录页面都要检查是否已经登录过才能显示
          dispatch({type: 'isLogined', payload:{path:location.pathname}});
        }
      });
    },
  },

2. 在需要身份校验的model做检查
subscriptions: {
    setup({dispatch, history}) {
      history.listen(location => {
        //列出所有可关注的项目
        if (location.pathname === '/') {
          dispatch({type: 'dashboard/isInited'});
        }
      });
    },
  },

3. 问题来了, 直接访问"/"的时候两个model同时触发, 而实际是2步骤想登录1的自动登录结束后才执行, 可以怎么弄呢?

**Comment by ityao** [comment]
是不是初始化的自动登录不应该在model里面做呢

**Comment by sorrycc** [comment]
试试这样：

```
const services.login = Promise;

setup({ history, dispatch }, done) {
  history.listen(({ pathname }) => {
    const needLogin = [].indexOf(pathname) > -1;
    if (needLogin) {
      services.login
        .then(() => {
          // 根据 pathname dispatch 不同 model 的初始化 effect
        })
        .catch(() => {
          // 跳转到登录页面
          dispatch(routerRedux.push('/login'));
        });
    }
  });
}
```

**Comment by ityao** [comment]
感觉有点难理解, 有实际应用的例子么?

**Comment by grunmin** [comment]
可以参考antd.admin
https://github.com/zuiidea/antd-admin
