### ISSUE TITLE
使用 effects 中报错，不知道原因

### ISSUE THREAD

**Issue by linyongping** [dvajs/dva#397]
dva 版本 0.60
使用dva-cli 构建的项目
使用effects中报错，put 方法无法发送action。
代码：
![capture2](https://cloud.githubusercontent.com/assets/13087561/21225462/fce451c0-c30b-11e6-972c-de76a9777bac.PNG)

出错信息
![capture](https://cloud.githubusercontent.com/assets/13087561/21225416/b704bd16-c30b-11e6-8eb7-4e5ff5821344.PNG)

**Comment by afc163** [comment]
call 要用 yield 来调用。

**Comment by linyongping** [comment]
使用yield 后还是抛出一样的错误，，，
![capture](https://cloud.githubusercontent.com/assets/13087561/21249645/7d788eaa-c37a-11e6-9a1f-c1cb9c984740.PNG)

**Comment by linyongping** [comment]
有一个现象是，之前正常的，后来添加了一些功能以后，出现了问题，

**Comment by sorrycc** [comment]
![image](https://cloud.githubusercontent.com/assets/35128/21249794/85ea8718-c37b-11e6-9680-e7a3ce8a8873.png)

changeUserLoginPassword 里报的错吧，和你贴的代码无关?

**Comment by linyongping** [comment]
effects 里的每一个都会报这个错误，，很奇怪，，但是同样的代码，之前却没出现任何问题，就是在增加饿了某个功能以后才出现的这个问题，，，可能是我那个地方写得有问题吧，，，我再仔细检查一下
![capture](https://cloud.githubusercontent.com/assets/13087561/21250505/b835d5c4-c380-11e6-9252-45c608f34371.PNG)

**Comment by nikogu** [comment]
看报错信息提示就好了：
![image](https://cloud.githubusercontent.com/assets/1179603/21250637/e402c0c6-c381-11e6-87df-42c6ab01ef3d.png)

多半是没有写 services
