### ISSUE TITLE
现在这个架构下如何通过state验证来做路由跳转

### ISSUE THREAD

**Issue by itiwll** [dvajs/dva#40]
# 现在这个架构下如何通过`state`验证来做路由跳转
我想实现的是`state`保存登陆状态，未登录跳转到`/login`路由下  
- 在`router.js `无法获取`state`，无法通过`onEnter`来实现；
- `IndexPage.jsx`里做路由跳转必须使用有状态组建；

还是说在 api 请求的时候验证登录状态而不是通过`state`?

**Comment by nikogu** [comment]
#### 我的理解：

登陆状态不应该用 `state` 来管理，当然也是可以的：

```jsx

import { connect } from 'dva';

const RouterContainer = (props)=>{

  console.log(props); // 包含users信息

  return (
    <Router history={props.history}>
      <Route path="/" component={HomePage} />
      <Route path="/users" component={Users}  onEnter={()=>{  }}/>
      <Route path="*" component={NotFound} />
    </Router>
  );
}

function mapStateToProps({ users }) {
  return {users};
}

export default connect(mapStateToProps)(RouterContainer);

```

这样会报 warning `browser.js:49 Warning: [react-router] You cannot change <Router routes>; it will be ignored`

所以这也说明了一个问题，`connect` 了组件以后，就会通过props更新而更新，我想你一定不想你的路由跟这个扯上关系，所以该怎么办呢？

__我觉得用一个全局变量管理就挺好__

**Comment by sorrycc** [comment]
这类逻辑应该放在 effect 里吧。

**Comment by codering** [comment]
@sorrycc  login是单独一个model还是放入user model 好？

**Comment by t04041143** [comment]
我遇到的问题是使用onEnter加载子路由上没反应，加到根路由上才行，何解？

**Comment by sorrycc** [comment]
@t04041143 是 bug，已修复，还没发。

**Comment by t04041143** [comment]
好的，期待

**Comment by t04041143** [comment]
@sorrycc 还想问下：如果我的state中存有user数据，如果这些我想通过路由的onEnter事件，访问user信息，根据user信息做判断，该怎么做（不用connect的办法，是否有store变量可以获取或者传递进来）

**Comment by sorrycc** [comment]
还没用过 react-router 的 onEnter，我需要找时间先了解下。

**Comment by nikogu** [comment]
@t04041143 我觉得你可以通过 `app._store` 访问到当前的状态 `const app = dva()`，试试

**Comment by t04041143** [comment]
@nikogu 我在其他文件调用获取app为一个html tag      <div id="app">

**Comment by nikogu** [comment]
@t04041143 能否详细说明下，dva() 返回的应该是如下一个 object

https://github.com/dvajs/dva/blob/master/src/createDva.js#L34

**Comment by t04041143** [comment]
@nikogu 没错，在定义dva的文件里，你看到的是一个object，但是我是在另一个文件里直接饮用app这个全局变量，就编程tag了，貌似被覆盖了

**Comment by nikogu** [comment]
@t04041143 这个问题是否已经解决了？如果没有麻烦再详细说一下，贴个代码？
