### ISSUE TITLE
Dva 打包问题

### ISSUE THREAD

**Issue by tianez** [dvajs/dva#401]
使用官方示例

发现打包后报错
`Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr

    at o (index.js:17)
    at Object.<anonymous> (index.js:17)
    at Object.<anonymous> (index.js:17)
    at t (index.js:1)
    at Object.<anonymous> (index.js:17)
    at t (index.js:1)
    at Object.<anonymous> (index.js:1)
    at t (index.js:1)
    at index.js:1
    at index.js:1`

经反复猜测  发现和组件书写方式有关
方式一：报错
> var Example = React.createClass({
  render: function() {
    return (
      < div >
      Example
       < Link to='/' >
Example</Link >
    < /div >
    );
  }
});
export default connect()(Example);

方式二：报错
> class Example extends React.Component {
  render() {
    return (
      < div >
      Example
       < Link to='/'>Example< /Link>
    < /div>
    );
  }
}
export default connect()(Example);

方式三：正确不报错

> const Example = (props) => {
  return (
    < div>
      Example
       < Link to='/'>Example</ Link>
    </ div>
  );
};
export default connect()(Example);

第一种写法不推荐可以放弃，但第二种写法却要用到，求该如何修改配置，让第二种写法不报错。新手，请见谅！

**Comment by sorrycc** [comment]
为啥会有这个 react-transform-hmr ?

**Comment by tianez** [comment]
找到问题了，原来是在 已有的项目下 新建的文件夹  所以受到原有 .babelrc 配置文件影响 
@sorrycc  十分感谢，一语惊醒梦中人
