### ISSUE TITLE
有没有在组件中类似于验证表单相关的解决方案

### ISSUE THREAD

**Issue by xaviertung** [dvajs/dva#402]
在诸如做表单验证需要依赖远程数据的情况下，我现在是在验证方法里直接调用service方法获取数据再做验证。dva的有没有提供dispatch后直接返回值的方案，比如回调函数之类的？

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues/325#issuecomment-267041877

**Comment by xaviertung** [comment]
谢谢
