### ISSUE TITLE
关于model 连接view 数据出错的问题

### ISSUE THREAD

**Issue by MaYing929** [dvajs/dva#405]
@sorrycc 

model已经获取数据了 [，但是通过dva提供的方式对象显示是空的，但是下拉出来又有显示，求解，之前做过两三个项目都用到了 没啥问题，不知道这次是怎么回事，求解答，一对比代码，之前的dva版本比现在低，是因为这个吗？？
<img width="915" alt="wechatimg1" src="https://cloud.githubusercontent.com/assets/10259789/21300043/095995be-c5dc-11e6-8fd3-02af9fc4b9aa.png">
<img width="881" alt="wechatimg2" src="https://cloud.githubusercontent.com/assets/10259789/21300042/0958ec68-c5dc-11e6-9137-900bc0543c0a.png">
<img width="900" alt="wechatimg3" src="https://cloud.githubusercontent.com/assets/10259789/21300045/098837ca-c5dc-11e6-9dc9-f457d229b484.png">

**Comment by sorrycc** [comment]
model 贴出来看下。

**Comment by MaYing929** [comment]
[model.js.zip](https://github.com/dvajs/dva/files/660027/model.js.zip)

**Comment by MaYing929** [comment]
@sorrycc

**Comment by MaYing929** [comment]
@sorrycc  不知道为啥 又好了。。。 我觉得这个本来不应该是个问题，现在又正常了
