### ISSUE TITLE
考虑将services合并到models里面吗

### ISSUE THREAD

**Issue by grunmin** [dvajs/dva#408]
大部分api请求都只是更新store, 因此service下的函数基本都只是提供url和data数据. 如果将其合并到model, 每次写方法就可以少编辑一个文件. (纯redux流程通过一些请求封装差不多能做到类似dva这样)(当然异步组合除外)

**Comment by sorrycc** [comment]
你可以把 service 写在 model 文件里。

**Comment by nikogu** [comment]
service 本身就是纯函数，随便写在那里都可以
