### ISSUE TITLE
app.model热加载的时候，会把执行过的dispatch在热加载后重复执行一次？

### ISSUE THREAD

**Issue by jianhuifan** [dvajs/dva#41]
场景：app.start()渲染页面出来后，进行交互操作， 发送了一个addItem的dispatch到reducer, 改变state, 导致重新渲染视图，同时热加载app.model(a),  此时的app.model，执行的是redux的replaceReducer, 查看源码发现replaceReducer执行了dispatch({ type: ActionTypes.INIT }); 
而这个dispatch会将热加载之前调用过的所有dispatch-addItem(其他的dispatch也一样，只要是热加载前调用过的dispatch)，全部都触发一次，为什么会是这样？

**Comment by sorrycc** [comment]
没太理解问题，热加载之后，state 是保留的，只是替换了 reducer，触发的 `ActionTypes.INIT` 是为了让刚载入进来的 reducer 输出初始值。

最好能提供个例子。

**Comment by sorrycc** [comment]
先关了，有问题再开 issue 。

**Comment by jianhuifan** [comment]
问题一： 每次执行app.model后，会将之前操作所有的diapatch全部执行一次，导致热加载功能在项目中不可用（仅开发过程中出现，正式打包后正常）

        重现步骤： 1. 点击count1的"＋"按钮, 发送一个add的 dispatch
                    //  dispatch: count1/add
                    //  connect: 1
                 2. 再点击count1的"－"按钮, 发送一个minus的 dispatch
                    //  dispatch: count1/minus
                    //  connect: 1
                 再点击"增加一个count2"按钮，执行hot()热加载model, 此时会执行之前所执行过的所有dispatch
                    //  dispatch: count1/add
                    //  dispatch: count1/minus
                    //  connect: 1
                    //  dispatch: count1/addCount
                    //  connect: 1
                    //  connect: 2

问题二：存在多个model的情况下，触发任意一个dispatch（包含type不存在的情况），为何会触发所有connect执行
        
          重现步骤： 1. 代码11行注释去掉，直接执行hot(); 同时加载count1 和count2 的model，或者直接点"增加一个count2"按钮
                 2. 点击count1/count2的"+－"按钮
                    //  dispatch: count1/add
                    //  connect: 2
                    //  connect: 1

```
import dva, { connect } from 'dva';
import { Router, Route } from 'dva/router';
import fetch from 'dva/fetch';
import React from 'react';

// 1. Initialize
const app = dva();

let App2;

// hot();

//热加载一个新的model
function hot(){
  app.model({
    namespace: 'count2',
    state: 0,
    reducers: {
      ['add']  (count) { return count + 1 },
      ['minus'](count) { return count - 1 },
    }
  });
  // 3. View
  App2 = connect(({ count2 }) => {
    console.log("connect: 2");
    return { count2 }
  })(function(props) {
    return (
      <div>
        <h2>{ props.count2 }</h2>
        <button key="add" onClick={()   => { console.log('dispatch: count2/add'); props.dispatch({type: 'count2/add'})}}>+</button>
        <button key="minus" onClick={() => { console.log('dispatch: count2/minus'); props.dispatch({type: 'count2/minus'})}}>-</button>
      </div>
    );
  });
}

// 2. Model
app.model({
  namespace: 'count1',
  state: 0,
  reducers: {
    ['add']  (count) { console.log('dispatch: count1/add'); return count + 1 },
    ['minus'](count) { console.log('dispatch: count1/minus'); return count - 1 },
    ['addCount'](count) { console.log('dispatch: count1/addCount'); return count+10 },
  },
});

// 3. View
const App = connect(({ count1 }) => {
  console.log("connect: 1");
  return { count1 }
})(function(props) {
  return (
    <div>
      <h2>{ props.count1 }</h2>
      <button key="add" onClick={()   => { props.dispatch({type: 'count1/add'})}}>+</button>
      <button key="minus" onClick={() => { props.dispatch({type: 'count1/minus'})}}>-</button>
      <button key="addCount" onClick={() => { hot(); props.dispatch({type: 'count1/addCount'}) }}>增加一个Count2</button>
      <br/>
      {App2 &&
        <App2 />
      }
    </div>
  );
});



// 4. Router
app.router(({ history }) =>
  <Router history={history}>
    <Route path="/" component={App} />
  </Router>
);

// 4. Start
app.start('#root');

```

**Comment by sorrycc** [comment]
1. 是 redux chrome 插件引起的，但我觉得并不影响功能
2. state 有变化后 connect 会全部执行的，然后根据 connect 第一个参数返回的数据是否有变化来决定是否重新 render 组件

**Comment by jianhuifan** [comment]
1.  redux chrome - 插件引起的，但该问题在开发环境会导致热加载后页面进入渲染的死循环，在项目中，目前我要在shouldComponentUpdate 中nextProps上增加reLoadModel进行标识，return false的方式处理，才能避免死循环
2. 第二点上学习了，谢谢

**Comment by sorrycc** [comment]
问题 1 没啥办法，影响功能的话就卸载插件吧，使用了 `replaceReducer` 的 redux 应用都会遇到。
