### ISSUE TITLE
本地开发时，更改源文件后，页面不停刷新

### ISSUE THREAD

**Issue by zllc** [dvajs/dva#410]
npm start的配置    dora --plugins "proxy,webpack,webpack-hmr,webpack?publicPath=/webjars/"

**Comment by sorrycc** [comment]
没遇到过这个问题，参考这个 [commit](https://github.com/dvajs/dva-cli/commit/203f2ffdd91a06f0b1538899e7509edc7ba2764e)，把工具换成 [roadhog](https://github.com/sorrycc/roadhog) 试试。

**Comment by kimoziiiii** [comment]
以后dva主打roadhog了？ 看了下 user-dashboard都换了...

**Comment by sorrycc** [comment]
是的，体验会好很多，https://github.com/sorrycc/roadhog#特性
