### ISSUE TITLE
dva effects 中promise对象的处理

### ISSUE THREAD

**Issue by zllc** [dvajs/dva#411]
effects中有个put 返回一个promise对象，比如显示一个modal，promise 的then中会处理一些逻辑，这时候then中会用到put 和 call。then函数中可以用生成器么？比如 function *(a)，貌似不会生效。还有put 和 call 前面一定要加yeild么？

**Comment by nikogu** [comment]
你的意思是？
```
yield put(showModal);

// 这里就写你的逻辑好了，用了 `yield` 不需要写 `then` 了吧，同步着写就好了吧

```

**Comment by sorrycc** [comment]
> effects中有个put 返回一个promise对象

put 并不会返回 promise。

> 还有put 和 call 前面一定要加yeild么？

是的。
