### ISSUE TITLE
浏览器获取的index.js非常大

### ISSUE THREAD

**Issue by Lourenjie** [dvajs/dva#412]
"start": "dora -p 9010 --plugins \"proxy?port=8011,webpack,webpack-hmr,browser-history?index=/dist/index.html\"",
打开网页之后，浏览器获取的index.js有2.2M，但是服务器上的index.js之后650K。这是怎么回事呢~

**Comment by afc163** [comment]
gzip

**Comment by Lourenjie** [comment]
@afc163  请问怎么开启gzip，还有为何浏览器获取的index.js会变大

**Comment by afc163** [comment]
http://lmgtfy.com/?q=gzip+http
