### ISSUE TITLE
effects中有将put用于回调的情况如何处理

### ISSUE THREAD

**Issue by zllc** [dvajs/dva#415]
比如显示一个通知，而这个通知组件中有个onclick回调，点击的时候隐藏自己，目前想到的逻辑是
onClick: ()=>put({type:'hide'})
这样貌似不太好使，求指导

**Comment by codering** [comment]
把put改成diapatch试试

**Comment by nikogu** [comment]
组件中调用 `effects` 使用 `dispatch`

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues/325#issuecomment-267041877

**Comment by hz251** [comment]
saga有个方法是put.sync，那个不能用吗？

**Comment by sorrycc** [comment]
put.sync 是用来处理 promise 格式 action 的，这个场景下不适用。
