### ISSUE TITLE
请问：dispatch一个不存在的action，是否会报错？是否能在onError中捕获到？

### ISSUE THREAD

**Issue by qingfengmy** [dvajs/dva#416]
dispatch一个不存在的action，是否会报错？是否能在onError中捕获到？

**Comment by sorrycc** [comment]
感觉应该直接抛错，但这是逻辑错误，不会走 onError。我自己写项目时也遇到过好几次。

**Comment by qingfengmy** [comment]
我觉得框架应该在没有action匹配时至少报个警告错误。我自己无法判断该action是无效的。

**Comment by xutou12** [comment]
不需要报错吧...因为在某些场景下是正常情况

比如: 
两个页签的内容是按需加载的分别用的是两个 model, 第一次打开时才加载
一个页签打开后发生数据变化需要通知另一个页签更新界面
这种情况判断不了另一个页签到底有没有加载,
因此第一个页签 dispatch/put 第二个页签的 action, 这种情况 action 存在则运行不存在则无所谓

完全不用考虑 action 是否存在

**Comment by longzb** [comment]
的确。今天我不小心写错namespace了，dispatch调model时控制台不提示报错页面也没啥任何反应。

**Comment by afc163** [comment]
直接报错可能不是好的实践。

1. flux 是一套 UI 和业务逻辑分离的架构，带有 dispatch 的 UI 和 reducer 是可以互相分离和各自复用的。如果 UI 单独开发，可以不考虑 reducer/sagas 是否已经实现。
2. 当然如果在一个系统中，给一个插件进行 warning，是有用的。
