### ISSUE TITLE
请问 subscriptions 下面的  setup 是内置方法？

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#417]
`
subscriptions : {
    setup({dispatch}) {
      dispatch({type: 'queryUser'})
    }
  },
`

**Comment by codering** [comment]
https://github.com/dvajs/dva/issues/174

**Comment by ntfs32** [comment]
不是的 放在subscriptions下的订阅可以理解为一个个任务吧，标示下而已，别的名字也可以执行的

**Comment by whwnow** [comment]
@ntfs32 任务是只会执行一次么，在什么时机执行啊？

**Comment by ntfs32** [comment]
可以访问了就执行的 ，比如监听着路由，访问过来就会执行了

**Comment by deanrobin** [comment]
我有两个路由监听，可以保证执行顺序吗

**Comment by lcoder** [comment]
google进来的，真的希望官网能加个触发时机，一脸懵逼
