### ISSUE TITLE
react-router页面滚动时，页面位置问题？

### ISSUE THREAD

**Issue by cllgeek** [dvajs/dva#420]
就比如有两个页面，第一个页面没滚动，点进去第二个，滚到底，返回第一个页面也滚到底了。这问题怎么解决，不解决都没法用了？

查了一下 
```
<Router onUpdate={() => window.scrollTo(0, 0)} history={createBrowserHistory()}>
  ...
</Router>
```
用这个在没有用dva情况下是能解决的, 但在dva下不起作用,请问怎么解决呢
```
export default function({ history }) {
  return (
    <Router onUpdate={()=>window.scrollTo(0,0)} history={history}>
      { routes }
    </Router>
  );
}
```
代码如上,不起作用

**Comment by sorrycc** [comment]
感觉和 dva 应该无关。试试加个 subscription 试试：

```
function({ dispatch, history }) {
  return history.listen(() => {
    window.scrollTo(0, 0);
  });
}
```

**Comment by cllgeek** [comment]
(node:5736) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: window is not defined

按你的方法加了个 subscription显示 window is not defined  我在组件中用componentWillMount 方法
```
componentWillMount() {
    window.scrollTo(0,0);
    console.log(window);
  },
```
能打印window,但是没有回到顶部,刷新后提示window is not defined

在没有用dva 下,这些方法都是正常工作的, 我用的是 dva-boilerplate-isomorphic 这个项目来测试的

**Comment by sorrycc** [comment]
dva-boilerplate-isomorphic 里 model 是 server 和 web 共用的，不能直接引 window，可借助 https://www.npmjs.com/package/global

**Comment by cllgeek** [comment]
(node:1792) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: window.scrollTo is not a function
借助 https://www.npmjs.com/package/global 引用window后 提示 window.scrollTo is not a function
然后我 console.log(window.scrollTo); 打印,在服务器端提示undefined,
在浏览器端提示是一个function。也就是window.scrollTo(0,0) 还是回不到顶部。:cry:

**Comment by cllgeek** [comment]
我找到什么原因了....原来是我搞错了,谢谢你的耐心解答

**Comment by chaelaugh** [comment]
> (node:1792) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: window.scrollTo is not a function
> 借助 https://www.npmjs.com/package/global 引用window后 提示 window.scrollTo is not a function
> 然后我 console.log(window.scrollTo); 打印,在服务器端提示undefined,
> 在浏览器端提示是一个function。也就是window.scrollTo(0,0) 还是回不到顶部。😢

虽然年代久远,但是想问下是怎么解决的,亲

**Comment by cllgeek** [comment]
@chaelaugh 抱歉，这么久才看到，我是这样解决的，代码如下：

```
function handleUpdate() {
  let {
    action
  } = this.state.location;

  if (action === 'PUSH') {
    window.scrollTo(0, 0);
  }
}

export default function({ history }) {
  return (
    <Router history={history} routes={ routes } onUpdate={handleUpdate} />
  );
}
```

**Comment by chaelaugh** [comment]
谢谢您的回复 我已经自己解决了 thank you

来自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: Chen Li Li <notifications@github.com>
发送时间: 2018年10月15日 10:15
收件人: dvajs/dva
抄送: chae cho; Mention
主题: Re: [dvajs/dva] react-router页面滚动时，页面位置问题？ (#420)


@chaelaugh<https://github.com/chaelaugh> 抱歉，这么久才看到，我是这样解决的，代码如下：

function handleUpdate() {
  let {
    action
  } = this.state.location;

  if (action === 'PUSH') {
    window.scrollTo(0, 0);
  }
}

export default function({ history }) {
  return (
    <Router history={history} routes={ routes } onUpdate={handleUpdate} />
  );
}


―
