### ISSUE TITLE
能否完善关于mockjs与dva的调用案例

### ISSUE THREAD

**Issue by sz30313484** [dvajs/dva#421]
新手一名，https://github.com/dvajs/dva/tree/master/examples/user-dashboard ，看到半截结果没了，新写的教程中，没有mockjs的调用，能否加下呢？另外，dva的调试是否介绍下，现在出了问题，完全找不到方向，网上几乎没有人解答。

**Comment by sorrycc** [comment]
解释如何与 mockjs 整合有点麻烦，可以先按老的方式走。这里有代码：https://github.com/dvajs/dva/tree/9727d87ac756aafaff51ab96f8f2ba2e67887cfb/examples/user-dashboard

**Comment by jeremy-zhao** [comment]
@sorrycc 请问有办法实现这种路由么？ 'PUT /api/user/{userId}'
