### ISSUE TITLE
a problem about dva-cli 0.7.0 

### ISSUE THREAD

**Issue by empty94cn** [dvajs/dva#423]
<img width="624" alt="2016-12-22 4 02 22" src="https://cloud.githubusercontent.com/assets/14255498/21419479/cfadfca4-c862-11e6-8005-9aa42a987fd5.png">

the file **webpack.config.js** will not be created by dva(version 0.7.0)

**Comment by sorrycc** [comment]
dva-cli@0.7 don't need `webpack.config.js`, if you want to customize webpack configuration, checkout [roadhog#Configuration](https://github.com/sorrycc/roadhog/blob/master/README_en-us.md#configuration).

**Comment by empty94cn** [comment]
Thx for answering , it works! But the doc of ant design hasn't been updated yet, you can check it here
https://ant.design/docs/react/practical-projects
----------------------------------------------------

**Comment by sorrycc** [comment]
@afc163 啥时候能发布最新版的文档上去?

**Comment by afc163** [comment]
已更新。
