### ISSUE TITLE
Container Component里面添加componentWillMount类似的生命周期方法

### ISSUE THREAD

**Issue by keenoor** [dvajs/dva#426]
目前需求：
每个Container Component对应一个route，里面有当前页面的小title，当父组件加载到这个children时候，需要把小title回传到父组件，两个组件共用一个model，因此想在children加载的回调里把参数传到model state。
我采用的是推荐的纯函数写component，但是，Container Component里面除了return 纯组件之外，并不知道如何写react的生命周期回调方法，但是又不希望以传统方式写component，请问dva如何处理？

**Comment by sorrycc** [comment]
别强求 stateless function component，有需要 component state 时就用吧。

**Comment by keenoor** [comment]
明白，3Q

**Comment by roc2539** [comment]
@sorrycc  是不是可以理解。如果需要在某些组件需要生命周期，这个时候通过subscriptions 也订阅不到事件的时候，就只用就React component，这个时候state还可以是在model中管理吗？如果单独管理。就会比较乱了吧？

**Comment by roc2539** [comment]
@sorrycc  是不是可以理解。如果需要在某些组件需要生命周期，这个时候通过subscriptions 也订阅不到事件的时候，就只用就React component，这个时候state还可以是在model中管理吗？如果单独管理。就会比较乱了吧？
