### ISSUE TITLE
请问Dva为什么所有的代码全部都到了 index.js 文件？有分块打包 demo 吗？

### ISSUE THREAD

**Issue by xflife** [dvajs/dva#427]
请问Dva为什么所有的代码全部都到了 index.js 文件？有分块打包 demo 吗？

**Comment by sorrycc** [comment]
可参考 https://github.com/sorrycc/blog/issues/18 ，对于的库是 https://github.com/dvajs/dva-example-user-dashboard

**Comment by xflife** [comment]
我看了一下，这个打包是到同一个文件，并没有分离开来？

**Comment by sorrycc** [comment]
按需加载? 参考：https://github.com/dvajs/dva/tree/master/examples/dynamic-load

**Comment by xflife** [comment]
不是按需加载，是分块打包...

**Comment by sorrycc** [comment]
一个 entry 里要拆包，可以试试 [CommonsChunkPlugin](http://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin) 。

**Comment by xflife** [comment]
我写过的 Vue 的项目，Vue 的项目是这样实现的：
路由：
`const Login = r => require.ensure([], () => r(require('../components/login/Login.vue')), 'group-user')
export default new Router({
  mode: 'history',
  scrollBehavior: () => ({ y: 0 }),
  routes: [
    { name: 'login', path: '/login', component: Login }
  ]
})
`
webpack：
`  output: {
        path: config.build.assetsRoot,
        publicPath: process.env.NODE_ENV === 'production' ? config.build.assetsPublicPath : config.dev.assetsPublicPath,
        filename: '[name].js'
    },`

**Comment by sorrycc** [comment]
这不就是按需加载吗?

**Comment by xflife** [comment]
不是，它也实现了分块打包，比如我系统上有二个路由：a,b;
 dva 项目中
        无论访问 a 还是 b，请求的 index.js;都是包含 a 和 b 的逻辑代码的；
vue 项目中
       访问 a 页面，请求的 js 是 a.index.js，访问 b 页面，请求的 js 是 b.index.js。是不相互包含的

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/blob/master/examples/dynamic-load/router.js#L6-L27
这段是用来实现你描述的 vue 项目的效果的。

**Comment by xflife** [comment]
我有看到这个动态的路由的代码，但是并没有实现 vue 项目中的想过，我现在的代码是这样的
`const Login = c => require.ensure([], require => (
    app.model(require('./models/login/loginModel')),
      c(null, require('./routes/login/Login'))
  ));

  const Main = c => require.ensure([], require => (
    app.model(require('./models/main/mainModel')),
      c(null, require('./routes/main/Main'))
  ));

  function interceptPermissions() {
    const token = kits.getCookies('tf-token');
    const uid = kits.getCookies('tf-uid');
    if (!uid || !token) {
      app._store.dispatch(routerRedux.replace('/login'))
    }
  }

  return <Router history={history}>
           <Route name="login" path="/(login)"
                  getComponent={(location, callback) => Login(callback)}/>
           <Route name="main" path="/main"
                  onenter={interceptPermissions()}
                  getComponent={(location, callback) => Main(callback)}>
             <IndexRedirect to="/main/dashboard" />
             <Route path="/main/actives" component={ require('./routes/actives/Actives') } />
             <Route path="*" component={ require('./routes/common/Error') }/>
           </Route>
         </Router>`
并没有实现，无论是run start 还是 build 所有的代码都输出到了一个 index.js 文件

**Comment by jiangbo2015** [comment]
`
const cached = {};
function registerModel(app, model) {
  if (!cached[model.namespace]) {
    app.model(model);
    cached[model.namespace] = 1;
  }
}

function RouterConfig({ history, app }) {
  const routes = [
    {
      path: '/',
      name: 'IndexPage',
      getComponent(nextState, cb) {
        require.ensure([], (require) => {
          cb(null, require('./routes/IndexPage'));
        });
      },
    },
    {
      path: '/users',
      name: 'UsersPage',
      getComponent(nextState, cb) {
        require.ensure([], (require) => {
          registerModel(app, require('./models/users'));
          cb(null, require('./routes/Users'));
        });
      },
    },
  ];

  return <Router history={history} routes={routes} />;
}

export default RouterConfig;`

**Comment by jiangbo2015** [comment]
https://github.com/dvajs/dva-example-user-dashboard/blob/master/src/router.js

**Comment by henryzp** [comment]
mark

**Comment by minzhenyu** [comment]
mark

**Comment by DaDaDaDaDaBocai** [comment]
mark

**Comment by AlaiNiGuests** [comment]
https://github.com/dvajs/dva/tree/master/examples/dynamic-load
被移走了，按需加载的dva配置我可以从哪里看到？谢谢

**Comment by minzhenyu** [comment]
mark

**Comment by tcstory** [comment]
@AlaiNiGuests 你地址里的文档,我看了一下,应该已经不能再2.x以上使用了吧?
那个react-router的语法,是3.x版本的还是4.x版本的?

**Comment by ChangerHe** [comment]
mark

**Comment by jkhmnk** [comment]
楼主是怎么解决的？  能贴下代码吗？ 万分感谢！
