### ISSUE TITLE
删除select列表的某个选项(数据后台读的)之后，select的值自己变成已删除option的key值了

### ISSUE THREAD

**Issue by jasminecjc** [dvajs/dva#428]
现在有一个列表，数据是从后台读的list
![image](https://cloud.githubusercontent.com/assets/13568376/21453173/8f4ecd06-c947-11e6-99b8-d2b78e765cea.png)

有一个按钮，删除当前选中的option，
![image](https://cloud.githubusercontent.com/assets/13568376/21453179/9945929a-c947-11e6-8c6c-8b33661562c9.png)

删除完毕后，后台返回新的list，已经确认后台的数据没问题，返回的是删除后的数据，展示list也没有问题，就是选择框的值自己变成了已删除option的key值
![image](https://cloud.githubusercontent.com/assets/13568376/21453181/a1610ca2-c947-11e6-9339-907710342da9.png)

**Comment by sorrycc** [comment]
应该是 antd 组件或者数据的问题。
