### ISSUE TITLE
dva-cli 0.7.0 和加上antd-mobile中的项目实战，出现错误

### ISSUE THREAD

**Issue by zouli0731** [dvajs/dva#429]
dva-cli 0.7.0 和加上antd-mobile中的项目实战，出现
Error in ./src/routes/IndexPage.js
Module not found: 'antd-mobile/lib/button/style/css' in /project/dva1/src/routes

 @ ./src/routes/IndexPage.js 7:11-54

Error in ./~/.0.9.12@antd-mobile/lib/button/index.js
Module not found: 'react-native' in /project/dva1/node_modules/.0.9.12@antd-mobile/lib/button

**Comment by sorrycc** [comment]
我今天找时间试试 antd-mobile 。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/issues/602 的第二条。

**Comment by zouli0731** [comment]
@afc163 你的意思是需要设置 resolve.extention 这个吗？
因为dva-cli 0.7  换成了 roadhog配置，我找了下没有 resolve.extention 的配置地方

而babel-plugin-import这个是已经配置的

**Comment by zouli0731** [comment]
@sorrycc 好像是resolve.extensions 没有添加'.web.js' 导致的。我在源码里修改了下，运行后正常

**Comment by sorrycc** [comment]
发布 roadhog@0.3.2，已修复这个问题。并更新 https://github.com/sorrycc/dva-example-antd-mobile 的工具为 roadhog 。
