### ISSUE TITLE
dva 跨域请求

### ISSUE THREAD

**Issue by tianez** [dvajs/dva#430]
求问 dva跨域请求
post请求直接发起了post请求  而没有先发起一次options请求
而put和del请求先发起一次options请求后返回204 ，然后没有发起第二次的真正的操作请求？

**Comment by tianez** [comment]
![image](http://7xiqax.com1.z0.glb.clouddn.com/1.png)
 ![image](http://7xiqax.com1.z0.glb.clouddn.com/0.png)

**Comment by longzb** [comment]
跨域请求跟dva没有任何关系。

如果你后端允许跨域，用的dva自带的请求的话就去查下fetch跨域，如果用axios就去查下axios跨域

加个配置就可以了。

**Comment by sorrycc** [comment]
204 是服务端返回的吧，那应该是服务端的问题。
