### ISSUE TITLE
connect的组件，在函数中创建会报错，有啥办法？

### ISSUE THREAD

**Issue by linginging** [dvajs/dva#433]
Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(SupplierSelectList)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(SupplierSelectList)".

**Comment by sorrycc** [comment]
代码贴出来看下。

**Comment by linginging** [comment]
这是connect了model的组件
import { connect } from 'dva';

import React, { PropTypes, Component } from 'react';
import { WhiteSpace, WingBlank, Icon, Card, Tag, Badge, Flex, Button, List, Radio, Checkbox, } from 'antd-mobile';  
const Item = List.Item;
const Brief = Item.Brief;
const RadioItem = Radio.RadioItem;
const CheckboxItem = Checkbox.CheckboxItem;

class SupplierSelectList extends Component {
  constructor(props) {
    super(props);
  }
  componentDidMount() {
  }
  render() {
    return (
      <List renderHeader={() => 'CheckboxItem 演示'}> 
        <CheckboxItem key="disabled" data-seed="logId" disabled defaultChecked multipleLine>
          初中<List.Item.Brief>辅助文字内容</List.Item.Brief>
        </CheckboxItem>
      </List>
    );
  }
}

SupplierSelectList.propTypes = {
  supplierSelect: PropTypes.object,
  location: PropTypes.object,
  dispatch: PropTypes.func,
  multiple: PropTypes.bool,
  onSelect: PropTypes.func,
  onCancel: PropTypes.func,
  queryParams: PropTypes.object,
};


function mapStateToProps({ supplierSelect }) {
  return { supplierSelect };
}
export default connect(mapStateToProps)(SupplierSelectList);

在另外的组件中
import React, { PropTypes, Component } from 'react';
import { WhiteSpace, WingBlank, Icon, Flex, List, Popup, } from 'antd-mobile';
const Item = List.Item;
const Brief = Item.Brief;

import SupplierSelectList from './SupplierSelectList';

class SupplierSelect extends Component {
  constructor(props) {
    super(props);
    this.state = {
      visible: false,
      selectRows: this.props.value || [],
    };
  }
  componentWillReceiveProps(nextProps) {
    this.setState({ selectRows: nextProps.value || [] });
  }


  render() {
    const { extra, label, multiple, onChange, allowClear, queryParams } = this.props;
    const { visible, selectRows } = this.state;
    console.log(this.props) 
    const SupplierSelectModalGen = () => <SupplierSelectList />;
    function handleSelect() {
      Popup.show(<SupplierSelectModalGen />, {
        animationType: 'slide-up',
        maskClosable: false
      });
    }

    return (
      <Item arrow="horizontal" extra={<span onClick={handleSelect}>{extra || '请选择'}</span>}>{label || '供应商'}</Item>
    );
  }
}

SupplierSelect.propTypes = {
  extra: PropTypes.string,
  label: PropTypes.string,
  title: PropTypes.string,
  multiple: PropTypes.bool,
  allowClear: PropTypes.bool,
  disabled: PropTypes.bool,
  value: PropTypes.array,
  onChange: PropTypes.func,
};

export default SupplierSelect;


在handleSelect函数中使用之前connect过的组件会报错，直接render中创建不会报错

**Comment by sorrycc** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by linginging** [comment]
`import { connect } from 'dva';

//省略组件代码

function mapStateToProps({ supplierSelect }) {
  return { supplierSelect };
}
export default connect(mapStateToProps)(SupplierSelectList);`

另一个不需要connect的组件中调用
`function handleSelect() {
      const SupplierSelectModalGen = () => <SupplierSelectList />;
      Popup.show(<SupplierSelectModalGen />, {
        animationType: 'slide-up',
        maskClosable: false
      });
    }`

函数中调用会报错，render中直接调用不会报错

**Comment by afc163** [comment]
https://segmentfault.com/markdown

**Comment by linginging** [comment]
```javascript
import { connect } from 'dva';

//省略组件代码

function mapStateToProps({ supplierSelect }) {
return { supplierSelect };
}
export default connect(mapStateToProps)(SupplierSelectList);
});
```

下面的组件报错，在函数handleSelect中
```javascript
import React, { PropTypes, Component } from 'react';
import { WhiteSpace, WingBlank, Icon, Flex, List, Popup, } from 'antd-mobile';
const Item = List.Item;
const Brief = Item.Brief;

import SupplierSelectList from './SupplierSelectList';

class SupplierSelect extends Component {
  constructor(props) {
    super(props);
    this.state = {
      visible: false,
      selectRows: this.props.value || [],
    };
  }
  componentWillReceiveProps(nextProps) {
    this.setState({ selectRows: nextProps.value || [] });
  }

  handleSelect = () => {
    //每次创建一个全新的组件，SupplierSelectModal内部visible为true时才会加载数据
    const SupplierSelectModalGen = () => <SupplierSelectList />;
    Popup.show(<SupplierSelectModalGen />, {
      animationType: 'slide-up',
      maskClosable: false
    });
  }

  render() {
    const { extra, label, multiple, onChange, allowClear, queryParams } = this.props;
    const { visible, selectRows } = this.state;

    return (
      <Item arrow="horizontal" extra={<span onClick={this.handleSelect}>{extra || '请选择'}</span>}>{label || '供应商'}</Item>
    );
  }
}

SupplierSelect.propTypes = {
  extra: PropTypes.string,
  label: PropTypes.string,
  title: PropTypes.string,
  multiple: PropTypes.bool,
  allowClear: PropTypes.bool,
  disabled: PropTypes.bool,
  value: PropTypes.array,
  onChange: PropTypes.func,
};

export default SupplierSelect;
```

**Comment by linginging** [comment]
只在dva中用过redux，应该是redux相关的问题，请帮忙看下？

**Comment by sorrycc** [comment]
为啥要每次创建新的 Modal ?

**Comment by linginging** [comment]
可以不创建，这是测试的，用了form才需要重新创建。直接在render的return中返回<SupplierSelectList />不会报错，在函数中会报错。

**Comment by sorrycc** [comment]
参考 https://github.com/dvajs/dva-example-user-dashboard/blob/master/src/components/Users/UserModal.js ，不用每次创建的。

**Comment by linginging** [comment]
主要是想用ant-mobile的Popup，这个只提供show方法，就必须把组件标签放在函数中。form重新创建就是看到ant的demo中有例子，例子说是避免一个bug。现在问题是在函数中使用一个connect过的组件会报错，百度到一些解释，但是不知道怎么在dva中处理？

**Comment by jaikensai888** [comment]
@linginging  同样遇到了此问题，看到你的案例后，受到了启发，发现是antd-mobile 的popup引起的，antd-popup 是使用直接触发（直接触发：act-》ui）。而非传统的行为上的间接触发（间接触发：act-》state-》render-》ui）。直接触发会成为了单一实力化，如果是使用stateLessComponent是没有问题，当当使用stateComponent的时候就出现你遇到的问题，所以建议你要不使用statelessComponent，要不就自己写一个可以间接触发的Popup ，我是自己写了一个popup来解决这个错误的。希望可以帮到你

**Comment by xiaochunyong** [comment]
@linginging @jaikensai888 我也遇到了这个问题, antd-mobile中用 Popup.show一个stateComponent组件, 导致 Could not find "store" in either the context or props 的一个错误, 你们解决了吗

**Comment by jaikensai888** [comment]
@xiaochunyong  我是写一个popup 来解决这个问题的。

**Comment by xiaochunyong** [comment]
@jaikensai888 我换了种解决方法, 不用connect了, 而是在新的组件内, 直接调用异步请求, 更新组件内部的state

**Comment by HankinsPan** [comment]
@sorrycc 
我也出现了同样的问题，用dva来写ReactNative，在ios上可以运行，但是到了android上就会出现问题。
错误描述：Could not find "store" in either the context or props of "Connect(RootScene)"【RootScene是我定义的根视图】.Either wrap the root component in a <Provider>,or explicitly pass "store" as a prop to "Connect(RootScene)"

**Comment by HankinsPan** [comment]
// ------- index.js 文件
import React from 'react';
import dva from 'dva/mobile'
import { registerModels } from './model'
import Router from './RootScene'

// 1. Initialize
const app = dva();

// 2. Model
registerModels(app);

// 3. Router
app.router(() => <Router />)

// 4. Start
export default () => {
  return app.start()
}

// 关闭全部的警告
console.disableYellowBox = true;

//--------RootScene
**** 省略部分引入
import {connect} from 'dva';
@connect(({router}) => ({router}))
class RootScene extends PureComponent {
  render() {
    const {dispatch, router} = this.props
    const navigation = addNavigationHelpers({dispatch, state: router})

    return (
        <Navigator navigation={navigation}/>
    );
  }
const Tab = TabNavigator(
*** 省略部分tab页面
);

const Navigator = StackNavigator(
    {
      Tab: {screen: Tab},
    },
    {
      navigationOptions: {
*** 省略部分tab页面
},
    }
);
export function routerReducer(state, action = {}) {
  return Navigator.router.getStateForAction(action, state)
}

export default RootScene
}


//-------- model=>  router.js
*** 省略部分引入

export default {
  namespace: 'router',
  state: {
    ...routerReducer(),
  },
  reducers: {
    apply(state, {payload: action}) {
      return routerReducer(state, action)
    },
  },
  effects: {

    watch: [function*({take, call, put, select}) {
      while (true) {
        const payload = yield take(actions);
        yield put({
          type: 'apply',
          payload,
        });
        yield call(delay, 500);// debounce, see https://github.com/react-community/react-navigation/issues/271
      }
    }, {type: 'watcher'}],
  },
}

**Comment by TaumuLu** [comment]
@jaikensai888 我遇到了同样的问题，想问一下你这个popup是怎么写
