### ISSUE TITLE
npm run build多页面构建问题

### ISSUE THREAD

**Issue by sexyios** [dvajs/dva#435]
大师好。请问dva支持构建时多页面打包吗？而不是所有代码全部压缩到一个文件里，而是分类分页面打包。有什么好的建议吗？看了webpack的配置，跟自己配置的有很大出入，所以不知道怎么下手...先谢谢啊

**Comment by codering** [comment]
https://github.com/sorrycc/roadhog#entry

**Comment by spiroo** [comment]
@sexyios 请问多页面之间是如何跳转的？
