### ISSUE TITLE
dynamic-load 时，路由有多级路径时,一级路径刷新没问题,二级路径刷新就找不到js文件

### ISSUE THREAD

**Issue by lhg0302** [dvajs/dva#438]
![qq 20161227162856](https://cloud.githubusercontent.com/assets/7666346/21495347/c375b5ba-cc51-11e6-91ed-17d2d0c0559d.png)

**Comment by lhg0302** [comment]
人气不旺啊,dva文档太少,版本也不出来给大家指点指点

**Comment by sorrycc** [comment]
没试过这个场景，需要找时间还原，你先探索下。。

**Comment by xutou12** [comment]
做 browser history 的 SPA 要把项目目录下的所有子路径设置定向到 index.html 就行了, react-router 官方例子的 server.js 你参考下是不是你需要的

**Comment by xttianma** [comment]
我试过这个，　不过碰到的问题是一切正常，　但是嵌套子目录里面的 定义路径,访问无效.

**Comment by pmg1989** [comment]
同问，确实有这个bug存在，期待解决方案

**Comment by sorrycc** [comment]
[publicPath](http://webpack.github.io/docs/configuration.html#output-publicpath) 配了吗?

**Comment by pmg1989** [comment]
@sorrycc ,已解决，万分感谢！！！
