### ISSUE TITLE
dva  1.1.0 安装后版本显示 dva -v ：  "0.7.0"

### ISSUE THREAD

**Issue by chimmyhuang** [dvajs/dva#444]
发生问题的环境是：Mac osx 10.12.2

重现步骤:  

    1. npm uninstall dva

    2. npm install dva@latest -g 
       /usr/local/lib   
      ├─┬ dva@1.1.0 
     │ └── UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0-0 || ^15.4.0-0
      ├── UNMET PEER DEPENDENCY react@15.x
     └── UNMET PEER DEPENDENCY react-dom@15.x
    3.  dva -v
  
        0.7.0

    4. npm uninstall dva

    5. npm install dva@1.1.0 -g 
        /usr/local/lib
       ├─┬ dva@1.1.0 
      │ └── UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0-0 || ^15.4.0-0
      ├── UNMET PEER DEPENDENCY react@15.x
     └── UNMET PEER DEPENDENCY react-dom@15.x

    6.  dva -v
        0.7.0

您期待的结果是:
      1.1.0 

实际上的结果是:
      0.7.0

**Comment by h-wei** [comment]
这个是 dva-cli 的版本号，dva 对应的是 dva-cli

**Comment by afc163** [comment]
dva 和 dva-cli 最好分开，现在容易混淆。

**Comment by sorrycc** [comment]
`dva -v` 时把相关的 version 都打印出来吧。

```bash
$ dva -v
dva-cli@0.7.0
dva@1.1.0
roadhog@0.3.0
atool-build@0.8.0
dora@0.1.0
```

**Comment by chimmyhuang** [comment]
明白了。谢谢afc163，h-wei ，sorrycc   。 

angular-cli 的处理，跟sorrycc建议一样，将相关version都打印出来了。

$ ng -v
angular-cli: 1.0.0-beta.22-1
node: 6.5.0
os: darwin x64
