### ISSUE TITLE
当我在弹出框（ant modal）里面更新state 的时候 弹出框里面页面内容没有重新渲染，

### ISSUE THREAD

**Issue by mlbao** [dvajs/dva#445]
当我在弹出框（ant modal）里面更新state 值 的时候 弹出框里面页面内容没有被重新渲染，
只有我把弹出框关掉，再打开才能渲染根据最新的state 生成的页面内容。这个问题怎么解决比较好？

**Comment by sorrycc** [comment]
更新的是 dva 的 state? 是的话用 redux devtool 检查 action 和 state 找找原因看。

**Comment by mlbao** [comment]
对，更新的是 dva 的state ， 把state集中的写在Model 下面，组件使用stateless 的写法写的，组件里有个弹出框（使用蚂蚁的  <Modal {...modalOpts}> 实现的）， 弹出里面有些操作会改变state 状态，我用devtool 查看状态是state 值是有变化的，但是Modal 里面的页面不会被重新渲染

**Comment by sorrycc** [comment]
检查两点：

1. 是否绑对了数据
2. 更新数据的方式是否正确，即是否返回了新数据，而不是修改老数据

**Comment by mlbao** [comment]
恩。。 是我修改了老数据引起的。

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/27640502-16dc7808-5c4c-11e7-8ba9-81bff7b264f2.png)

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/27641657-1279779a-5c4f-11e7-8782-81fbb620a6bf.png)
