### ISSUE TITLE
首页加载的样式不起作用吧? <link rel="stylesheet" href="index.css" />  

### ISSUE THREAD

**Issue by roc2539** [dvajs/dva#446]
<link rel="stylesheet" href="index.css" />

:global {
  html, body, #root {
    height: 100%;
  }
}

这里设置的高度。没有作用呀

**Comment by sorrycc** [comment]
用的 css modules，看了下是有效的：

![image](https://cloud.githubusercontent.com/assets/35128/21516352/4df15d28-cd12-11e6-89f3-1a91c8738ba9.png)

**Comment by roc2539** [comment]
![image](https://cloud.githubusercontent.com/assets/22289965/21516448/5c494a10-cd13-11e6-8933-af5a2f614bb5.png)
![image](https://cloud.githubusercontent.com/assets/22289965/21516452/61517244-cd13-11e6-8980-943a876641e1.png)
![image](https://cloud.githubusercontent.com/assets/22289965/21516470/8f7d6858-cd13-11e6-889a-45bf8a7d4ca7.png)
我这里没有用是。。奇怪。。

**Comment by roc2539** [comment]
必须要在html页面中写样式才有效。  CSS module写的无效.

**Comment by sorrycc** [comment]
`.root` 不能用，className 会被转成 hash 的。

**Comment by roc2539** [comment]
html body 也没有样式

**Comment by roc2539** [comment]
#root 也没有用

**Comment by sorrycc** [comment]
搞不定 css modules 的话，就把他禁用掉吧。https://github.com/sorrycc/roadhog#disablecssmodules

**Comment by qiutiaoming** [comment]
我也没有搞定这个全局的样式 @roc2539 ,这个问题你解决吗，还是直接禁用 css-modules

**Comment by christtrc** [comment]
通过 `dva new app`构建的模板工程，安装antd文档里的步骤，已执行`npm install antd babel-plugin-import --save`添加了**antd**和**babel-plugin-import**。但是执行`npm start`时，浏览器提示如下错误：

1. Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8000/index.css".

2. You are using a whole package of antd,
please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.

**Comment by sorrycc** [comment]
@christtrc 

问题 1，忽略，因为开发模式下 css 是内联载入的。

问题 2，应该是 babel-plugin-import 没配对。

**Comment by christtrc** [comment]
检查了一下，问题2是因为我将`babel-plugin-import `的配置放置到了`production`环境下，`development`环境没有配置，所以出错。

**Comment by zackfly** [comment]
@qiutiaoming 我也遇到了这个问题，我的项目里出错原因有两个，1：其实是样式实际打包进了页面里，所以在页面引入css，在开发环境是不行的，2：而打包出来的样式里的#root 被转成了带hash的模式，照理来说global 不会被hash，而我这么写:global(#root){
    height: 100%;
}就ok，为啥那种写法不行呢


。。。
于是说了这么多 ，我更新了下全局的webpack ，就好了。。。。。只是语法不支持的问题

**Comment by zackfly** [comment]
@qiutiaoming 我也遇到了这个问题，我的项目里出错原因有两个，1：其实是样式实际打包进了页面里，所以在页面引入css，在开发环境是不行的，2：而打包出来的样式里的#root 被转成了带hash的模式，照理来说global 不会被hash，而我这么写:global(#root){
height: 100%;
}是可以的，这我也不知道为什么
