### ISSUE TITLE
使用browserHistory时无法获取其他model的数据，只能获取原始state

### ISSUE THREAD

**Issue by sessionboy** [dvajs/dva#447]
使用browserHistory时无法获取其他model的数据，只能获取初始化的state，假如用hashHistory就没有这个问题，请问这是什么原因

**Comment by sorrycc** [comment]
> 无法获取其他model的数据

怎么获取的?

**Comment by sessionboy** [comment]
function mapStateToProps({ lists,roots,items }) {
  // hashHistory模式下，这里可以获取多个其他model的完整state（包含已有的数据）
  // browserHistory模式下，这里只能获取多个其他model的初始化state
  return { lists,roots,items }; 
}

**Comment by sessionboy** [comment]
切换为browserHistory模式就不行了

**Comment by sorrycc** [comment]
这个和 history 类型无关的，检查下其他地方是否有问题吧。

**Comment by sessionboy** [comment]
好的，感谢
