### ISSUE TITLE
请问如何结合express

### ISSUE THREAD

**Issue by cheart-gh** [dvajs/dva#448]
怎样把express结合到项目中？

**Comment by sz30313484** [comment]
脚手架没法混用吧？.roadhogrc中可以解决跨域请求的问题，应该够用了

**Comment by yvanwangl** [comment]
请教一下，dva有没有结合express使用的实践 @sorrycc

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues/490#issuecomment-272328633
