### ISSUE TITLE
项目clone下来，运行examples中的demo时，会报错

### ISSUE THREAD

**Issue by FEliuyg** [dvajs/dva#449]
缺少babel-loader和需运行npm run build才能正常运行

**Comment by sorrycc** [comment]
参考这个 example 吧，https://github.com/dvajs/dva-example-user-dashboard

**Comment by FEliuyg** [comment]
恩，这个example有跟着学，受益很大。dva 有提供update吗?之前安装的是0.6.0的  现在想安装最新的0.7.0以上的，需要uninstall才可以重新安装。

**Comment by sorrycc** [comment]
最新是 1.1，你看到的 0.7 应该是 dva-cli 的版本，可参考 https://github.com/dvajs/dva/pull/42#issuecomment-241323617 升级。
