### ISSUE TITLE
support redux-router

### ISSUE THREAD

**Issue by vagusX** [dvajs/dva#45]
目前仅支持 react-router-redux
希望可以提供选项支持 redux-router

**Comment by nikogu** [comment]
@vagusX 其实你也可以自己引入直接用。。。。

**Comment by vagusX** [comment]
@nikogu 已经自己fork改了下 就是想来说一声

**Comment by nikogu** [comment]
@vagusX 其实我的意思不是改`dva`，可以在你的项目中引入，然后在路由中使用，因为这块跟dva还是比较独立的，后面如果发现`redux-router` 用的人很多，就会集成到 dva 当中来，免得自己再去引了

**Comment by sorrycc** [comment]
redux-router 有啥优势?

**Comment by vagusX** [comment]
@sorrycc 目前我们在项目中使用了 redux-router，将一些配置放在route 的 props 上面，在effect 里 将从 store.router 上读取部分配置；此外，部分 effect 需要去拿 store.router 对象做一些操作

**Comment by yuluyi** [comment]
@sorrycc react-router-redux 在store里面只有locationBeforeTransitions. 而redux-router可以在store里获取到react-router的整个上下文，这样方便redux和react-router的解耦。比如saga中有side effect依赖路由的一些状态，可以直接从store里去取而不需要通过action传过来。 另外因为redux-router需要apply一个store enhancer， dva没暴露相应的接口，没法直接用。

**Comment by sorrycc** [comment]
@yuluyi 迟点我看下 redux-router。不过路由信息在 react-router 里是异步解析的，因为要支持动态路由。https://github.com/reactjs/react-router-redux#how-do-i-access-router-state-in-a-container-component
