### ISSUE TITLE
页面路由变了，但是视图却没有更新数据，需要刷新才能做数据初始化

### ISSUE THREAD

**Issue by chenfengyanyu** [dvajs/dva#450]
我在model中想初始化查询，如下：
```js
subscriptions: {
        setup({ dispatch, history }) {
            history.listen(location => {
                if (location.pathname === '/notice') {
                     dispatch({
                         type: 'query',
                         payload: location.query,
                     })
                }
            })
        },
    },
```
我期待的是，当点击到notice路由时，该页面渲染数据，但是并非如次，我需要刷新页面，数据才可以出来。请问，我该如何做数据初始化？

**Comment by sorrycc** [comment]
打日志看切换路由时，这里的 `location.pathname` 是啥。

**Comment by chenfengyanyu** [comment]
问题解决了，页面刷新location.pathname='/notice'，链接跳转时，location.pathname='notice'，所以并未触发action，谢谢提醒。
路由是这么写的：
<Route path="notice" component={Notice} />
链接跳转这么写，就ok了
<Link  to="/notice">
再次感谢🙏
