### ISSUE TITLE
使用hashHistory如何添加自定义的查询字符串参数

### ISSUE THREAD

**Issue by rentj1** [dvajs/dva#452]
http://localhost:8989/?#/home?_k=lljcya&abc=123 
这个url在 subscriptions setup里 location.pathname变成了"/home&abc=123"

**Comment by sorrycc** [comment]
http://localhost:8989/?#/home?abc=123&_k=lljcya
这样就好了，参考[这里](https://github.com/dvajs/dva-knowledgemap#%E5%9F%BA%E4%BA%8E-action-%E8%BF%9B%E8%A1%8C%E9%A1%B5%E9%9D%A2%E8%B7%B3%E8%BD%AC)做 url 跳转，会自动把 `_k` 参数放到最后的。
