### ISSUE TITLE
静态资源图片引用

### ISSUE THREAD

**Issue by wm3445** [dvajs/dva#454]
以下为我引入的全局样式
![image](https://cloud.githubusercontent.com/assets/5467635/21561929/954a856c-ceae-11e6-9c38-7f90ceb9982e.png)
但是打包后会多出来一个img文件,不应该是编译为base64吗？
![image](https://cloud.githubusercontent.com/assets/5467635/21561935/9fea03b2-ceae-11e6-821f-ad6a4ca242fc.png)

**Comment by afc163** [comment]
图片大于 10k 就不会内联了。

**Comment by chenkan** [comment]
这个大于 `10k` 就不能内联的限制可以配置么

@afc163
