### ISSUE TITLE
effect报错未处理，则之后不接收此action

### ISSUE THREAD

**Issue by xialvjun** [dvajs/dva#455]
effect 函数中没有 trycatch，也没有设置全局的错误处理 onError。。。然后当 effect 中的异步操作报一次错后，之后再 dispatch 这个 effect 就压根不起作用了，effect 函数根本不运行。

**Comment by sorrycc** [comment]
这是预期的结果，加 try...catch 或者 onError 处理下出错吧。

**Comment by xialvjun** [comment]
好的，谢谢。
