### ISSUE TITLE
在一个model中，发起更新另一个model的action，无效

### ISSUE THREAD

**Issue by t04041143** [dvajs/dva#46]
比如我在model A的一个effect方法中发起

`yield put ({ type: 'B/update'})`

没有调用到model B的reducer方法 update

**Comment by nikogu** [comment]
@t04041143 提供下你的 dva 的版本号

**Comment by t04041143** [comment]
0.0.16

**Comment by sorrycc** [comment]
这个算基础功能，应该不会有问题吧。。检查下自己的代码看呢?

**Comment by t04041143** [comment]
@sorrycc 我贴下代码，你看看，我建了2个model， captcha和error，captcha处理验证码，error处理服务器返回错误。

captcha相关代码
`   effects: { `
`    *get({payload}) {`
`      try {`
`        yield put({type: 'error/clear'});  -- 没效果`
  `      yield call(getCaptcha, payload);  -- 成功`

error中的reducer
`  reducers: {`
`    clear(state, action) {`
`        return {};`
`    }`

**Comment by t04041143** [comment]
我在component里用dispatch是可以调用得到

**Comment by sorrycc** [comment]
要升级到 1.0.0-beta1 才会给 reducers 和 effects 自动加 namespace 前缀。用 0.0.16，error 中的 reducer 需要是：

```
'error/clear'() {}
```

**Comment by t04041143** [comment]
哦，啥时候升级到 1.0.0呢

**Comment by sorrycc** [comment]
下周发布。

**Comment by t04041143** [comment]
好的
