### ISSUE TITLE
优化 effect 抛错信息

### ISSUE THREAD

**Issue by sorrycc** [dvajs/dva#462]
现在是这样的，难以阅读，应该明确提示是哪个 effect 报的错。

<img src="https://zos.alipayobjects.com/rmsportal/btEXhFkDkZNzHjduGlTK.png" />

**Comment by kulwe** [comment]
![Uploading 快照1.png…]()
![1483682365 1](https://cloud.githubusercontent.com/assets/1769161/21709018/7b357474-d418-11e6-9a3d-911621783a54.png)
我在使用时做了如上处理，每个model都可以定义effectsError来处理错误，省得effects中大量try catch
