### ISSUE TITLE
getting-started 文档的几个问题

### ISSUE THREAD

**Issue by ZoeyYoung** [dvajs/dva#463]
```
$ dva -v
0.7.5
```

1、

```
          proxy: listened on 8989
     livereload: listening on 35729
📦  173/173 build modules
webpack: bundle build is now finished.
```

当前版本输出为

```
Compiled successfully!

The app is running at:

  http://localhost:8000/

Note that the development build is not optimized.
To create a production build, use npm run build.
```

2、

使用 css module 还要设置　.roadhogrc 中　`disableCSSModules`　为　`false` 才能生效

3、

> 这里我们不需要手动安装 keymaster 依赖，在我们敲入 import key from 'keymaster'; 并保存的时候，dva-cli 会为我们安装 keymaster 依赖并保存到 package.json 中。输出如下：

当前版本并没有自动安装依赖

4、

npm run build 输出

```
> @ build /private/tmp/dva-quickstart
> roadhog build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  88.02 KB  dist/index.js
  235 B     dist/index.css
```

望更新

**Comment by sorrycc** [comment]
重复了，https://github.com/dvajs/dva-docs/issues/46

**Comment by ZoeyYoung** [comment]
[dvajs/dva-docs](https://github.com/dvajs/dva-docs) 这个库看着已经Deprecated，所以那个ISSUES关掉了，看这个库下面也有这往篇文档，所以如果更新文档的话会更新哪里的？

**Comment by sorrycc** [comment]
目前还有点分散，以这个为入口吧，https://github.com/dvajs/dva 。后续有时间的话会整一个 dvajs.com，[库](https://github.com/dvajs/dvajs.com)。
