### ISSUE TITLE
在browserHistory下的动态路由按需加载中，第二次其换到某个路由时报错

### ISSUE THREAD

**Issue by Jessie-D** [dvajs/dva#466]
![bug](https://cloud.githubusercontent.com/assets/10069496/21666063/77938db8-d32a-11e6-93b6-e03d9451f712.png)

**Comment by Jessie-D** [comment]
[issue @460](https://github.com/dvajs/dva/issues/460) 
```

  现在简单处理我想可以这样:首页一次性加载完model, 在routes里就只动态加载
route页面：
比如：
app.unmodel('app');
app.model(require('./models/app')); 
```
按照其说明的方法不报错了，但是不能动态加载modal了

**Comment by szwork2013** [comment]
@Jessie-D 就看你怎么平衡了，多个route页面要共用modal时候呢，还不如一次性加载完算了。

**Comment by szwork2013** [comment]
当然，如果项目很庞大，绝大多数的modal应该要能按需加载，现在不是临时救急吗？ 😂😂

**Comment by xutou12** [comment]
dva@1.1.0 版本中重复运行 model 只要注意数据的清理就完全没问题

**Comment by xttianma** [comment]
此类问题的解决办法:
``` 
if(!app._models.some(val=>(val.namespace ===  'home')) {
        app.model(require('./models/home'))
}
```
----
＃　建议开发者：　错误信息能否明确指出XXX, 重复加载,错误文件和行号?

**Comment by sorrycc** [comment]
对动态加载的问题总结了下，有问题在 #533 里跟进。
