### ISSUE TITLE
dva.hasModel ( model | namespace )

### ISSUE THREAD

**Issue by kulwe** [dvajs/dva#468]
升级1.2.0后发现model冲突，代码中有一些动态加载的模块依赖某个全局公用的model，这个model可能会在app启动时预加载，也可能会被其他模块提前加载。期望能提供hasModel来检测是否已经加载

**Comment by sorrycc** [comment]
这周没时间了，下周我会好好考虑下这个问题，看来大家用 dynamic router 还是挺多的。

**Comment by xutou12** [comment]
刚 dva@1.1.0 版本升级到 1.2.1 悲剧了, 有共用 model 的按需加载歇菜了

**Comment by ityao** [comment]
加油, 加油, @sorrycc 赶紧加上, 或者在dva.model那自动判断已经加载过没有

**Comment by sorrycc** [comment]
@xutou12 先用 dva@1.1 吧，按需加载我需要找时间好好看看。

**Comment by sorrycc** [comment]
对动态加载的问题总结了下，有问题在 #533 里跟进。
