### ISSUE TITLE
在windows平台下.构建 Android App.dva 和 react-native-vector-icons不兼容.

### ISSUE THREAD

**Issue by AdamChrist** [dvajs/dva#470]
入坑react native用了 ant mobile 和 dva ; 后来引入了react-native-vector-icons 之后就炸了..各种build不过.
最后发现去掉dva就可以.
build的错误如下.
`
> Execution failed for task ':react-native-vector-icons:prepareComFacebookFrescoDrawee0110Library'.
> \>Could not expand ZIP 'C:\Users\haojiachen\.gradle\caches\modules-2\files-2.1\com.facebook.fresco\drawee\0.11.0\7c8a4d211b2334b6d52b9de614b52423b16f7704\drawee-0.11.0.aar'.
>
`
dependencies如下:
`
>   "dependencies": {
    "antd-mobile": "^0.9.13",
    "dva": "^1.2.1",
    "moment": "^2.17.1",
    "rc-form": "^1.1.0",
    "react": "15.4.1",
    "react-native": "0.39.2",
    "react-native-nav": "^1.1.4",
    "react-native-navigator-router": "^0.2.0",
    "react-native-vector-icons": "^3.0.0"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-plugin-import": "^1.1.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "18.1.0",
    "react-test-renderer": "15.4.1"
  }

**Comment by AdamChrist** [comment]
@sorrycc 帮忙看下..用redux写法感觉好原始..回不去了

**Comment by nikogu** [comment]
@AdamChrist 感觉是打包配置的原因（webpack?），看下你的 build 的脚本呢

**Comment by AdamChrist** [comment]
@nikogu 是指这个么?我之后重新用 cli创建了一个新的项目.先加入vector-icons没有问题,运行成功.之后一个一个往里面添加引用.添加dva之后就报错了.去掉就好了.
   
    apply plugin: "com.android.application"

    import com.android.build.OutputFile

    apply from: "../../node_modules/react-native/react.gradle"

    def enableSeparateBuildPerCPUArchitecture = false

    def enableProguardInReleaseBuilds = true

    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.1"

        defaultConfig {
            applicationId "com.rnpolymerpo"
            minSdkVersion 16
            targetSdkVersion 22
            versionCode 1
            versionName "1.1"
            ndk {
                abiFilters "armeabi-v7a", "x86"
            }
        }

        signingConfigs {
            release {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }

        splits {
            abi {
                reset()
                enable enableSeparateBuildPerCPUArchitecture
                universalApk false  
                include "armeabi-v7a", "x86"
            }
        }
        buildTypes {
            release {
                minifyEnabled enableProguardInReleaseBuilds
                proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
                signingConfig signingConfigs.release
            }
        }
        applicationVariants.all { variant ->
            variant.outputs.each { output ->
                def versionCodes = ["armeabi-v7a":1, "x86":2]
                def abi = output.getFilter(OutputFile.ABI)
                if (abi != null) {
                    output.versionCodeOverride =
                            versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
                }
            }
        }
    }

    dependencies {
        compile fileTree(dir: "libs", include: ["*.jar"])
        compile "com.android.support:appcompat-v7:23.0.1"
        compile "com.facebook.react:react-native:+"  // From node_modules
        compile 'com.pgyersdk:sdk:2.4.0'
    }
    task copyDownloadableDepsToLibs(type: Copy) {
        from configurations.compile
        into 'libs'
    }

**Comment by AdamChrist** [comment]
@nikogu 引入"react-dom": "^15.4.1" 之后就可以正常用运行了...应该是react-dom的冲突造成的..
