### ISSUE TITLE
编译后className出现后缀名的问题。

### ISSUE THREAD

**Issue by xhmaoxx** [dvajs/dva#471]
在less文件中定好class名，在主键中直接使用class名，但是发现所有的class名都带有后缀。
如：
less文件中  .MainHead
编译后变成  .MainHead__csyx
请问如何配置才能将后缀去掉？

**Comment by afc163** [comment]
https://github.com/css-modules/css-modules

**Comment by nikogu** [comment]
https://github.com/dvajs/dva/issues/327
