### ISSUE TITLE
关于树型节点模型设计

### ISSUE THREAD

**Issue by jnotnull** [dvajs/dva#472]
当前使用dva构建了一个树，有多个层级，最后的叶子节点上有些信息需要统计到父节点上，比如叶子节点对象是一个qq群，那要在其所有父节点中展示下面所有叶子节点的qq群人数总和，另外群人数还在动态变化着，这个通过订阅websocket实现。websocket如果来了新的数据，每次去找到所有的父节点的数据去更新，感觉性能太低，是否有好的思路呢。

**Comment by kulwe** [comment]
人数总和的数字不要存入redux的state，在render时进行统计，这种计算属性不要放到redux的state中

**Comment by jnotnull** [comment]
计算属性确实不应该放到state中，但是如果计算属性太复杂，可能性能太低哦。直接在属性中计算好再给react去diff是否会好点

**Comment by kulwe** [comment]
先保持代码简洁，再考虑性能，计算属性优化直接用 _.memoize
