### ISSUE TITLE
fetch 中文乱码问题

### ISSUE THREAD

**Issue by yimi8126** [dvajs/dva#474]
请问使用
import fetch from 'dva/fetch';
浏览器直接get可以正常返回，使用fetch就乱码了，有什么解决方案吗

**Comment by ityao** [comment]
export default function request(url, options) {
  options = {...options, credentials: 'include', headers: {'Content-Type': 'application/json; charset=utf-8'}, } //包含cookie信息
  return fetch(url, options)
    .then(checkStatus)
    .then(parseJSON)
    .then((data) => ({ data }))
    .catch((err) => ({ err }));
}

**Comment by ityao** [comment]
我这样用暂时没发现有乱码的问题

**Comment by sorrycc** [comment]
试试 @ityao 的方案看看。
