### ISSUE TITLE
effects里数据请求的回调函数里调用put，没有执行到reducers

### ISSUE THREAD

**Issue by small752** [dvajs/dva#475]
原先是用fetch异步请求，但是因为某环境下浏览器内核不支持fetch， 改成用reqwest向后台请求数据。
在effects里调用reqwest，在回调函数里调用了put想改变state，但是没有执行
回调函数是这样定义的
function(ret) {
  put({
       type: 'queryGoods',
       payload: {}
   });
}

**Comment by seamys** [comment]
刚好这几天遇到这个问题. 我觉得还是切换回去之前的. 下面的是浏览器兼容情况, Android 4.6 一下的版本都不能正常使用.
![c6e19fc8-6791-11e5-8ac2-bfede76df6b4](https://cloud.githubusercontent.com/assets/7090368/21914913/3f75103a-d971-11e6-883e-f673ec793b22.png)

下面是解决方案

https://github.com/camsong/blog/issues/2

原生支持率并不高，幸运的是，引入下面这些 polyfill 后可以完美支持 IE8+ ：

由于 IE8 是 ES3，需要引入 ES5 的 polyfill: es5-shim, es5-sham
引入 Promise 的 polyfill: es6-promise
引入 fetch 探测库：fetch-detector
引入 fetch 的 polyfill: fetch-ie8
可选：如果你还使用了 jsonp，引入 fetch-jsonp
可选：开启 Babel 的 runtime 模式，现在就使用 async/await
Fetch polyfill 的基本原理是探测是否存在 window.fetch 方法，如果没有则用 XHR 实现。这也是 github/fetch 的做法，但是有些浏览器（Chrome 45）原生支持 Fetch，但响应中有中文时会乱码，老外又不太关心这种问题，所以我自己才封装了 fetch-detector 和 fetch-ie8 只在浏览器稳定支持 Fetch 情况下才使用原生 Fetch。这些库现在 每天有几千万个请求都在使用，绝对靠谱 ！

终于，引用了这一堆 polyfill 后，可以愉快地使用 Fetch 了。但要小心，下面有坑：
