### ISSUE TITLE
如何设置更新不刷新浏览器？

### ISSUE THREAD

**Issue by liekkas** [dvajs/dva#479]
这个功能应该支持吧，有地方配置吗？现在随便改个地方都要刷新浏览器，没热加载方便。

**Comment by nianhua110** [comment]
调用你的query方法？

**Comment by xttianma** [comment]
修改 package.json 中的start 为:　roadhog server --no-open

加上--no-open 参数, 就可以了.

**Comment by liekkas** [comment]
@xttianma 谢谢

**Comment by sorrycc** [comment]
感觉 `--no-open` 并不是你的答案，现在并不能禁用 HMR，后来会考虑下是否支持的。

**Comment by xttianma** [comment]
是的, 我也体验了--no-open,  我现在去除了. 主要问题是当配置文件修改后,频繁的弹出新的页面, 新的页面.这个很烦. 不能热更新到当前调试的页面上.

**Comment by sorrycc** [comment]
> 当配置文件修改后,频繁的弹出新的页面, 新的页面.

估计是个 bug 。。我排查下。
