### ISSUE TITLE
奇怪的动态加载时候的model重复加载

### ISSUE THREAD

**Issue by ityao** [dvajs/dva#480]
`{
          path: 'profile/phone',
          getComponent(nextState, cb) {
            require.ensure([], (require) => {
              if(!checkModel['profile/phone']){
                let result = app.model(require('../models/phone'));    //手机绑定
                checkModel['profile/phone'] = true //防止重复加载
              }              
              cb(null, require('./profile/PhonePage'))
            })
          }
        }`

在require.ensure([], (require) => { 里面去做app.model的时候第一次进入没错, 后面进入就报重复加载model, 有没有一个model有否重复加载的机制去防止, 现在我自己实现checkModel对象去保存加载情况, 有点啰嗦

**Comment by ityao** [comment]
#460

**Comment by sorrycc** [comment]
对动态加载的问题总结了下，有问题在 #533 里跟进。
