### ISSUE TITLE
项目太大，页面有几十个的时候，model要如何组织更合理

### ISSUE THREAD

**Issue by linyongping** [dvajs/dva#481]
如果每个页面都写一个model的话，几十个model对性能的影响会不会很大，如果好几个页面公用一个model，每个model又会变得很大，纠结哪一个才是比较好的方式，或者说这两种方式哪一个更不会影响性能

**Comment by xutou12** [comment]
不管几个共用还是一对一, 只要保证 model 的逻辑简单用好按需加载就好了,

**Comment by sorrycc** [comment]
对性能无影响，model 尽量拆小点。

**Comment by pmg1989** [comment]
@sorrycc ，如linyongping所问，model 尽量拆小点，或者说model细化，代码上可以怎么实现呢，或者有文档类的可以参照下么。
就比如如果我用reducer的话，我可以
combineReducers({
  model1,
  model2,
  model3
})
合成state tree，但dva应该怎么把细化后的model重新组织到一起呢

**Comment by pmg1989** [comment]
![image](https://cloud.githubusercontent.com/assets/13361827/22237464/f1603800-e246-11e6-83e1-c393f07078e1.png)
我可能期望能达到这样的model结构，希望把model拆分细化，然后再把细化的model重新合成新的model tree，可以怎么实现呢

**Comment by sorrycc** [comment]
dva 不支持 combineReducer，建议拍平数据层级，用 accountUser, accountRole 这种形式。

**Comment by pmg1989** [comment]
ok，了解了，那以后可以考虑实现类似于combineReducer的功能么，感觉项目越来越大的时候，这种方式还是存在可拓展性的优势的呢
