### ISSUE TITLE
typescript 中 import fetch from 'dva/fetch' 出错

### ISSUE THREAD

**Issue by airt** [dvajs/dva#486]
`dva version: 1.2.1`

```typescript
import fetch from 'dva/fetch'

console.log('fetch', fetch)
// => fetch undefined
```

ts 编译出来的 js 里引用的是 `fetch_1["default"]`..

fix:
```js
Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = require('isomorphic-fetch');
```

**Comment by qzhong1028** [comment]
碰到同样的问题，请问是如何解决的？

**Comment by airt** [comment]
@qzhong1028 
现在直接用的 [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch)..
如果需要 types 可以用 [@types/whatwg-fetch](https://www.npmjs.com/package/@types/whatwg-fetch)
