### ISSUE TITLE
npm run build 生成的文件不可访问

### ISSUE THREAD

**Issue by wq123456** [dvajs/dva#491]
npm run build 后生成到dist 目录下的index.html文件访问时一片空白

**Comment by afc163** [comment]
和没问区别不大，需要提供更多信息。

---

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by lincenying** [comment]
你需要架设html服务器来访问, 不能直接双击打开...

**Comment by wq123456** [comment]
sorry,原来build的时候需要把browerHistory去掉const app = dva({history: browserHistory,}); =》const app = dva();  那么各位大神解释下原因拜

**Comment by wq123456** [comment]
@lincenying 不需要架设服务器也可以哦，而且如果把fetch 用superagent 替换的话都不用担心跨域的问题，这样的好处就是不用设置代理，开发后的东西甚至可以直接打包成本地应用，比如使用electron打包成桌面客户端，亲测可用

**Comment by lincenying** [comment]
你用F12的network看下, 里面的静态文件是否正常加载.

**Comment by Mjian-chen** [comment]
你是不是想使用同一套代码在web端、原生app静态资源加载?
