### ISSUE TITLE
npm run build 之后 生成的index{num}.js 文件 无法按照相对路径访问

### ISSUE THREAD

**Issue by KingDomPan** [dvajs/dva#492]
比如 index.html 引入index.js的方式为 ./js/index.js
按照动态加载之后某个路由, 请求的js 仍然为/index{num}.js 而不是./js/index{num}.js

请问, 如何关闭动态路由配置. index.js里面全部app.model也没效果

**Comment by sorrycc** [comment]
配 publicPath，参考：https://github.com/sorrycc/roadhog#publicpath
