### ISSUE TITLE
请教一下 如何处理全局dispatch

### ISSUE THREAD

**Issue by ufohjl** [dvajs/dva#493]
#### 请教下如何处理dispatch全局异常
数据走restful请求, 如果服务端session过期会返回http status code 401,
我需要在request.js里作全局处理判断 response status = 401,
然后 dispatch一个全局action {type: 'showLogin'}, 再作统一跳转登录视图处理.

请教一下使用dva, 这个全局action要在哪里dispatch, 在哪里处理reducer?

**Comment by nikogu** [comment]
感觉 `dispatch` 不是这么用的，你可以直接跳转到登陆吧，或者 `showLogin` 本身是个方法

**Comment by nianhua110** [comment]
在request里面抛异常，然后在index.js里面捕获。这儿可以调用dispatch.
```javascript
const app =
  dva({
  onError(ex) {
      app._store.dispatch(routerRedux.push('/login')); 
  },
});
```

**Comment by ufohjl** [comment]
感谢大家
