### ISSUE TITLE
请问50个100个路由的时候怎么优雅的处理呢?

### ISSUE THREAD

**Issue by xjdata** [dvajs/dva#494]
大型应用有太多的page了. 数量少还好说,但是到一定量后router.js基本上没办法看了.

本想

```js
const ensureModule = (name, entry) => (location, callback) => {
  require.ensure([], require => {
    callback(null, require(entry))
  }, name)
}

```

但是不支持. 我搜了下,有朋友说
>rquire函数太特别了，他是webpack底层用于加载模块，所以必须明确的声明模块名，require函数在这里只能接受字符串，不能接受变量 。所以还是忍忍算了

可是page确实有那么多...怎么办呢?

有注意到这个项目 https://github.com/dvajs/dva-ast 但是不确定是不是适合我的需求.

谢谢大家.

**Comment by nianhua110** [comment]
可以参考proxy.config.js文件。遍历router文件，动态添加。不过我没实现过，只是个想法。
```javascript
const mock = {}

require('fs').readdirSync(require('path').join(`${__dirname}/mock`)).forEach((file) => {
  Object.assign(mock, require('./mock/' + file))
})

module.exports = mock
```

**Comment by sorrycc** [comment]
用 webpack 的 require.context ? 可以批量 require 的。http://webpack.github.io/docs/context.html#require-context
