### ISSUE TITLE
拦截动作?或者专业的名词应该是什么,请大家指导.

### ISSUE THREAD

**Issue by xjdata** [dvajs/dva#495]
需求如下:

>比如,数据库恢复操作,或者一些其他对应用影响较大的动作.  设:当前用户是有这个权限进行这个操作的.
>但是因为操作比较敏感,所以希望在这些动作执行前,需要第三人审计该操作被容许.

设想思路如下:

![image](https://cloud.githubusercontent.com/assets/4524983/21954009/bceb295e-da80-11e6-9411-08fc83087223.png)

但是因为需要被拦截的effects比较随机. 全部手写比较麻烦.

所以想问下各位朋友,有没有比较优雅的办法实现. 谢谢.

**Comment by sorrycc** [comment]
在 onAction 中通过 redux 中间件处理? 特殊的 effect 加个特殊的标记。
