### ISSUE TITLE
用antd的表格组件表头的对齐问题

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#496]
![wx20170114-184552](https://cloud.githubusercontent.com/assets/1819457/21954386/fcd1964e-da89-11e6-8c1b-b3c14a9514ef.png)

我是有办法让列内容右对齐，但是没办法让列头右对齐，大兄弟前来求助亲爱的小伙伴们！

**Comment by codering** [comment]
你应该去antd提问。。。。。。。

**Comment by afc163** [comment]
你应该去 https://segmentfault.com/t/antd 提问
