### ISSUE TITLE
请教，我可以在routes配置中，使用模型state和dispatch吗？

### ISSUE THREAD

**Issue by lllyyylll2** [dvajs/dva#500]
具体场景例如，在 Router onEnter时判断登录状态，redirect到login，或根据cookie自动登录。
我希望在onEnter 事件中获取app model的hasLogin state，并dispatch autoLogin的effect。

**Comment by sorrycc** [comment]
router.js 中可以获取到 app 的。

```js
export default function({ history, app }) {
  app._store.dispatch()
  app._store.getState()
}
```
