### ISSUE TITLE
dva-cli创建项目无法启动问题

### ISSUE THREAD

**Issue by ddliao** [dvajs/dva#501]
你好，我根据 `12 步 30 分钟，完成用户管理的 CURD 应用 (react+dva+antd) #18`搭建新项目，但是无法启动
以下是命令行报错信息：
![image](https://cloud.githubusercontent.com/assets/11850305/21961100/cf0a1260-db3b-11e6-8786-047fd76e4949.png)
以下是谷歌浏览器报错信息：
![image](https://cloud.githubusercontent.com/assets/11850305/21961113/02dbdd62-db3c-11e6-9c26-1b10aa753293.png)
操作系统：win7
node版本：v7.2.0
dva-cli版本：0.7.8

**Comment by sorrycc** [comment]
看出错是找不到 babel 依赖，依赖没装好?

**Comment by xttianma** [comment]
dva安装完成后, 你就修改文件了.是否忽略了这个教程当中需要安装ant 和bagel import的依赖?
请,仔细的看教程每一步,90%的坑都是自己挖的.

**Comment by ldd911127** [comment]
我在项目目录中执行过npm install，ant 和bagel import也都是安装了的
对应package.json文件如下：
![image](https://cloud.githubusercontent.com/assets/11850305/21975358/378b26a0-dc07-11e6-8e9c-eed87610ed32.png)
对应roadhogrc文件如下：
![image](https://cloud.githubusercontent.com/assets/11850305/21975448/b41de19e-dc07-11e6-9d61-6b6a6e412657.png)

**Comment by sorrycc** [comment]
试试用 [cnpm](https://github.com/cnpm/cnpm) 安装依赖。

**Comment by ldd911127** [comment]
试过了的，显示的全部安装成功，我先试下删除node_modules再次安装

**Comment by xttianma** [comment]
@sorrycc 我提了一个问题,在dva上,怎么替代react的生命周期的写法. 给解决一下呗. 

dingtalk的应用page 组件加载的时候, 需要使用dingtalk api 去设置标题栏. 我的项目都是在componentDidMount完成的. 在dva里面怎么办呢?

**Comment by ldd911127** [comment]
重装依赖也无法解决，并且我还重新new 了一个新的项目还是不对，请问此问题有什么解决方法不，以前是用的0.4x版本，准备升级下，结果卡在第一步

**Comment by sorrycc** [comment]
node 是什么版本?

**Comment by ldd911127** [comment]
node是v7.2.0

**Comment by sorrycc** [comment]
换 6.9 试试，7.x 和 webpack 有不兼容的情况。

**Comment by ldd911127** [comment]
好的，我试下，谢了哈

**Comment by ldd911127** [comment]
安装node6.9.4还是不得行，也试过安装babel依赖，都不行

**Comment by ldd911127** [comment]
我将dva降级到0.7.0，可以运行哈，最新版0.7.8不可以

**Comment by mohong122** [comment]
我直接创建项目后也报对应的错误

**Comment by sorrycc** [comment]
@mohong122 你也是 windows 系统?

**Comment by mohong122** [comment]
@sorrycc 是的。dva的版本是0.7.8 antd 的版本2.6.3

**Comment by le0zh** [comment]
遇到了一样的错误。

```
$ dva new dva-quickstart
$ cd dva-quickstart
$ npm start
```

mac系统

```
➜  ~ dva -v
0.7.8
➜  ~ node -v
v6.9.4
➜  ~
```

**Comment by sorrycc** [comment]
@le0zh npm 版本?

**Comment by ddliao** [comment]
我用最新的0.7.8 dva-cli，将roadhog从0.5.2版本降级到0.4.3版本，编译正常

**Comment by sorrycc** [comment]
升级 npm 试试？https://github.com/sorrycc/roadhog/issues/99#issuecomment-273964812 后续在 sorrycc/roadhog#99 跟进
