### ISSUE TITLE
如何在dva初始化时候，创建全局对象

### ISSUE THREAD

**Issue by hanagm** [dvajs/dva#505]
目前是基于webscoket实现的一个小项目，但是在每次都是在model中创建一个新的连接。
是否可以在app初始化 时，创建一次连接，后续的model中可以直接使用已创好的连接？

那么涉及到几个问题

- 如何在new dva() 时候初始化websocket对象。
-如何在后续的model, react component中获取到创建好的对象?

我记得以前有一个mantra框架有实现类似的处理，连接如下:
[mantra init demo ](https://github.com/mantrajs/mantra-sample-blog-app/blob/master/client/configs/context.js)

是否有相关的解决方法?

**Comment by sorrycc** [comment]
封装成一个 service 吧，已连接就不需要重新建立了，model 的 subscription 是调用者。
