### ISSUE TITLE
文档中说可以在effects中获取全局state数据, 请教一下要如何获取

### ISSUE THREAD

**Issue by ufohjl** [dvajs/dva#507]
> ## effects
> 
> 以 key/value 格式定义 effect。用于处理异步操作和业务逻辑，不直接修改 state。由 action 触发，可以触发 action，可以和服务器交互，**可以获取全局 state 的数据**等等。
> 
> 格式为 *(action, effects) => void 或 [*(action, effects) => void, { type }]。

官方文档说, 可以在effects中获取全局state数据, 请教一下如何获取

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva-knowledgemap#select

**Comment by ufohjl** [comment]
thanks~
