### ISSUE TITLE
关于一个[npm start]调试环境下的性能问题

### ISSUE THREAD

**Issue by DickyT** [dvajs/dva#509]
使用默认npm start运行App的时候, 就是那个监测代码更新的功能开着, npm的CPU占用率会暴涨, 请问下这个是正常情况还是有什么地方出问题了...感觉这个占用率有点可怕...
![screen shot 2017-01-17 at 2 46 50 pm](https://cloud.githubusercontent.com/assets/4535844/22034801/d0d08f28-dcc3-11e6-9f2e-ba5b1775be34.png)

**Comment by DickyT** [comment]
发现是webpack的devserver的一个问题 https://github.com/webpack/webpack-dev-server/issues/172

**Comment by DickyT** [comment]
FYI, 在dva项目根目录
`npm install fsevents --save`
即可解决此问题

**Comment by sorrycc** [comment]
后续在 https://github.com/sorrycc/roadhog/issues/93 跟进。
