### ISSUE TITLE
怎么样做页面间跳转 类似于 context.router

### ISSUE THREAD

**Issue by hbrls** [dvajs/dva#51]
我现在在做的类似于从列表视图跳转到详情视图。

`history.push('/roles/xxxx-xxxx-xxxx/users')` 用下来有很多奇怪的问题，当然也可能和我使用的方式不对有关。

想请问官方有推荐的方式吗？

**Comment by sorrycc** [comment]
1. 用 `<Link />` 标签
2. 在 effects/subscriptions 里 put/dispatch 一个 action，详见：https://github.com/dvajs/dva/issues/48#issuecomment-242625661

**Comment by hbrls** [comment]
想问的是第2种情况，那把这边关掉过去讨论吧
