### ISSUE TITLE
Ok, you asked, you got it!

### ISSUE THREAD

**Issue by plandem** [dvajs/dva#510]
I started #195 some time ago and still sure it's actual, because I don't see any positive steps at colossus on clay legs.

Here is implementation of router concept that do what exactly needed without any prediction or wheel invention. Easy concept with only 5-10 minutes to learn and remember how to use. I stabilized API (it was partially used in internal projects, so took some time to make as npm) and don't see any changes (as I said it was used internally for quite long time).

I'm still working on examples and documentation, but you can look and decide - to use or not to use.

Here is links:
---
https://github.com/plandem/rrrouter

https://github.com/plandem/rrrouter-provider-history

https://github.com/plandem/rrrouter-provider-redux

P.S.: DVA is quite small library and  the only reason we can't use it - hardcoded support of colossus on clay legs that you can't replace.

If you have any question - ask :)

**Comment by sorrycc** [comment]
dva@2 will try to seperate view and data, then we can choose other router implement when using dva. Track progress in #530
