### ISSUE TITLE
eslintrc造成代码提交报错的临时处理办法

### ISSUE THREAD

**Issue by xttianma** [dvajs/dva#511]
刚刚开始使用dva的时候,首次可以提交成功. 后续提交npm报错了. 因为对node/npm..没有经验. 一直在git找问题. 最后一个朋友告知是eslintrc的规则的问题. 这才开始注意看 本地git仓库的hook, 
对eslintrc的规则是在看不懂. 您写的知识库也没有说明. 当前我只能删除了hook,和eslintrc.

能否给讲讲eslintrc和hook? 如何写才能符合规则进行提交?

**Comment by sorrycc** [comment]
提交出错时有明确提示的。

**Comment by xttianma** [comment]
npm的报错看不懂呀, 请站在学习阶段的小白的角度来理解一下为啥有这个问题.

**Comment by sorrycc** [comment]
* https://github.com/airbnb/javascript
* http://eslint.org/

看下这两个网站了解下规则和 eslint 工具吧。
