### ISSUE TITLE
多个route公用一个model，又想异步加载model，结果有问题

### ISSUE THREAD

**Issue by Slngle** [dvajs/dva#516]
直接上代码
    const loginComponent = (nextState, cb) => {
        require.ensure([], require => {
            app.model(require('models/loginregforget'));
            cb(null, require('routes/login'));
        });
    }

    const regComponent = (nextState, cb) => {
        require.ensure([], require => {
            app.model(require('models/loginregforget'));
            cb(null, require('routes/reg'));
        });
    }

    const forgetComponent = (nextState, cb) => {
        require.ensure([], require => {
            app.model(require('models/loginregforget'));
            cb(null, require('routes/forget'));
        });
    }

用懒加载加载js文件 3个route想用一个model  结果报错
Uncaught Error: app.model: namespace should be unique
请问这种情况要怎么处理 不想在index.js 里面直接引用model

**Comment by xttianma** [comment]
此类问题的解决办法:
``` 
if(!app._models.some(val=>(val.namespace ===  'home')) {
        app.model(require('./models/home'))
}
```
----
＃　建议开发者：　错误信息能否明确指出XXX, 重复加载,错误文件和行号?

**Comment by hehaibo** [comment]
@Slngle 可以提供代码参考？
