### ISSUE TITLE
动态路由进行app.mode注册model, 出现 Uncaught Error: app.model: namespace should be unique

### ISSUE THREAD

**Issue by xttianma** [dvajs/dva#517]
动态路由写法,是参照这个例子写的:
[react-router huge-apps ](https://github.com/ReactTraining/react-router/tree/master/examples/huge-apps)

目录结构是:
routername
|-- index.js: 动态路由
|-- filenameMode.js  : model文件
|-- filenmaePage.js  :   router文件
|-- components.js : 私有组件
|-- ...

分离加载的路由为: 
/routername/index.js 
```
module.exports=(app)=>{
    return {
        path: '/',
        name: 'home',
        
        getComponent(nextState, cb) {
            require.ensure([], require => {
                app.model(require('./HomeModel'));
                cb(null, require('./HomePage.js'));
            });
      },
    }
}
```
---
反复测试,无论任何方式,访问这个路由url, 就出现如题错误. (之后刷新这个路由不报错,也不能继续代码执行),

**Comment by xttianma** [comment]
此类问题的解决办法:
``` 
if(!app._models.some(val=>(val.namespace ===  'home')) {
        app.model(require('./models/home'))
}
```
----
＃　建议开发者：　错误信息能否明确指出XXX, 重复加载,错误文件和行号?

**Comment by juanpengke** [comment]
错误提示不是很明确了吗？你的model文件中namespace  有重复的

**Comment by xttianma** [comment]
不够明确,否则,不会有四五个人都提问类似问题了.

**Comment by sorrycc** [comment]
动态加载的问题需要找时间再看下，你可以先用 dva@1.1 。

**Comment by xttianma** [comment]
参照dvademo 和react-router的动态路由方式, 将路由和model注册分散到子目录index中,遇到的3个问题.
1. app对象的传递: 用import 传递了props, 貌似解决子目录的index的app.model不存在的问题;
    这样做有隐患吗?
2. 重复注册model : 当前临时的对model 是否存在做了一个判断，暂时性的排除了这个问题．
3. 用getChildRoutes挂上了深层次的路由, 但是不渲染,有说是module.exports和export default的区别,导致,用es6语法的需要require('components/layer/ReportPage')).default. 这个我还在测试. 还没有解决.

**Comment by sorrycc** [comment]
对动态加载的问题总结了下，有问题在 #533 里跟进。
