### ISSUE TITLE
同一个model中如何在一个effect方法中调用另外一个effect方法

### ISSUE THREAD

**Issue by wangyibin** [dvajs/dva#521]
```
effects: {
    *query({ payload }, { call, put }) {
      // do query
    },
    *'delete'({ payload }, { call, put }) {
      // do delete
      yield query //  I want to invoke *query here
    },
}
```

**Comment by linyongping** [comment]
yield put({
     type:"query"
})
这样应该就可以啦。。。。

**Comment by wangyibin** [comment]
果然可以，谢谢 ;-)

**Comment by muchengit** [comment]
重新npm i 后 npm start 报以下错误，求助
> cross-env NODE_ENV=development ESLINT=none roadhog dev

Starting the development server...


  build [==================  ] 91%
<--- Last few GCs --->

[1632:000000FBFE2CA5E0]   117339 ms: Mark-sweep 1414.8 (1477.4) -> 1414.8 (1477.4) MB, 1523.3 / 0.0 ms  last resort GC in old sp
ace requested


<--- JS stacktrace --->
