### ISSUE TITLE
dva现在是否支持使用Immutable，有没有示例？

### ISSUE THREAD

**Issue by miserylee** [dvajs/dva#522]
RT

**Comment by sorrycc** [comment]
理论上应该是可以用的。我还没用过 immutable，准备在下一个项目里试试。

**Comment by joahCN** [comment]
@sorrycc immutable.js 是在reducer中修改state的property用，把当作一个独立的工具库用就可以了吧？

**Comment by zhump** [comment]
同求

**Comment by byk04712** [comment]
同求

**Comment by MinJieLiu** [comment]
同求

**Comment by MinJieLiu** [comment]
关注这个[pr-1002](https://github.com/dvajs/dva/pull/1002)
