### ISSUE TITLE
routerRedux.pop方法

### ISSUE THREAD

**Issue by qingfengmy** [dvajs/dva#523]
比如当前是表单页面，提交表单后，回退到前一个页面，同时刷新数据。使用routerRedux.goBack()方法，虽然回退到前一个页面，但浏览器的history还存在之前的表单页面。

如何像pop一样，把当前表单页pop出浏览器的history，同时页面也回退？在dva里如何处理这类需求？

**Comment by sorrycc** [comment]
没具体试过 `routerRedux.goBack()`，没有触发 `history.listen` 吗?
