### ISSUE TITLE
Effect和Subscription可以再出一个经典的教程吗?

### ISSUE THREAD

**Issue by xttianma** [dvajs/dva#525]
#### 个人水平比较差, Subscription和Effect, 看过写提问和demo, 还是没有理解掌握.
**能否在浅显些讲解?**
---

阅读参考来自:
1.  [dva-knowledgemap](https://github.com/dvajs/dva-knowledgemap#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%88%9D%E5%A7%8B%E5%8C%96)

2. [Concepts](https://github.com/dvajs/dva/blob/master/docs/Concepts_zh-CN.md)

> 说明: 两个文档对Effect和 Subscription的讲解各有侧重, 只能合并起来看. 
---

## 问题1: 
图例中, 显示只有dispatch 和Subscription 可以触发Aciton,而Reducer和Effect则是接受Aciton,进行处理的作用. 可是文档中: Effect的 yield put 方法,也可以触发Action,
>  理解: 是否应该立即为: dispatch | Effect |  Subscription ,3个都可以触发Aciton, 而不是图例的两个? 

## 问题2
Reducer: 可以接收dispatch触发的Aciton 函数方式处理state, 也是可以唯一的改变state的地方.
Effect: 可以接收到dispatch触发的Aciton, 异步方式处理state, 但是不可以改变state. 
> 理解: 
    由于 Reducer不可异步操作,也就是不能和server产生来往, 所以凡是异步的state操作都调用effect来完成.

> 也就是说Aciton需要**同步处理**state的就由Reducer完成, 
                  Aciton需要**异步处理**的就由Effect完成,再由yield put触发Aciton,跳到Reducer里面改变state 

## 问题3 
Effects中描述  select  用于从 state 里获取数据。
理解: 用yield select(state => state.todos);方式, 是从项目的整个state树里面获取数据进行操作, 如同mapStateToProps一般绑定数据. 

这样的理解对吗?不对是否给纠正一下?

**Comment by sorrycc** [comment]
> 问题1

- 接收 action 的地方有：reducer 和 effect
- 触发 action 的地方有：subscription、effect、被 connect 的 component、[onError hook](https://github.com/dvajs/dva/blob/master/src/createDva.js#L167)

> 问题2

理解正确。

> 问题 3

理解正确。
