### ISSUE TITLE
怎样在dva中用react-router 4？

### ISSUE THREAD

**Issue by gitcyrabbit** [dvajs/dva#529]
我看文档中可以创建一种不需要router的项目，是不是这个

**Comment by sorrycc** [comment]
目前不可以，dva@2 里会考虑把 router、view 和 model 分离。

**Comment by sorrycc** [comment]
后续在 #530 中跟进。

**Comment by wuyanghou** [comment]
function RouterConfig({ history, app }) {
  const routes = [
    {
      path: '/',
      name: 'IndexPage',
      getComponent(nextState, cb) {
        require.ensure([], (require) => {
          cb(null, require('./routes/IndexPage'));
        });
      },
    }
  ];

  return <Router history={history} routes={routes} />;
}



你好，为什么现在这种路由写法页面渲染不出来？也不报错

**Comment by sorrycc** [comment]
@wuyanghou 你用 dva@2 了？dva@2 的路由写法变了。

**Comment by wuyanghou** [comment]
@sorrycc 还真是，谢谢你了

**Comment by zi-qiong** [comment]
那应该怎么写呢
