### ISSUE TITLE
关于程序运行不出来的原因

### ISSUE THREAD

**Issue by MaYing929** [dvajs/dva#53]
各位大神    为什么clone下来的dva项目中的examples 只有最后一个能够正常运行呢

**Comment by sorrycc** [comment]
dva 根目录执行下 `npm install` 。

**Comment by MaYing929** [comment]
根目录下执行了 npm install   又进入了example下的子项目下进行了npm install
依然报错 貌似是模块错误，只有最后一个正常

**Comment by sorrycc** [comment]
报什么错?

**Comment by MaYing929** [comment]
我再运行一次 等下给你贴出来

**Comment by MaYing929** [comment]
ERROR in /Users/my/Workspace/React/dva/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib in /Users/my/Workspace/React/dva
 @ /Users/my/Workspace/React/dva/index.js 3:17-33

ERROR in /Users/my/Workspace/React/dva/src/index.js
Module not found: Error: Cannot resolve module 'babel' in /Users/my/Workspace/React/dva/src
 @ /Users/my/Workspace/React/dva/src/index.js 11:17-39
我看 大都是这个错误

**Comment by MaYing929** [comment]
却少./lib文件

**Comment by sorrycc** [comment]
在根目录运行 `npm run build` 。

**Comment by MaYing929** [comment]
ERROR in /Users/my/Workspace/React/dva/src/index.js
Module not found: Error: Cannot resolve module 'babel' in /Users/my/Workspace/React/dva/src
 @ /Users/my/Workspace/React/dva/src/index.js 11:17-39

ERROR in /Users/my/Workspace/React/dva/index.js
Module not found: Error: Cannot resolve module 'babel' in /Users/my/Workspace/React/dva
 @ /Users/my/Workspace/React/dva/index.js 3:17-33

 babel 又报错了  新手求指导

**Comment by sorrycc** [comment]
可能和 npm 版本有关，我本地试了 npm3 是会有你报的问题的，试试用 npminstall 安装依赖。

```bash
$ npm install npminstall --g
```

然后在 dva 根目录和相应的 example 目录下都执行：

```bash
$ rm -rf node_modules
$ npminstall
```

**Comment by MaYing929** [comment]
我的npm版本是3.10.2
 可能就是这个原因，之后应该升级npm的版本，请问什么版本最稳定最合适呢

**Comment by sorrycc** [comment]
推荐 [npminstall](https://github.com/cnpm/npminstall) 。我们是用 npminstall 的内部版，安装速度比普通的 npm 快很多，目录结构是 npm2 的。

**Comment by MaYing929** [comment]
谢谢大神了，确实速度快， 以后尽量用nominstall
看文档发现一个问题
https://github.com/dvajs/dva-docs/blob/master/zh/tutorial/07-%E6%B7%BB%E5%8A%A0Effects.md

subscriptions: {
    setup({ dispatch, history }) {
      history.listen(location => {
        if (location.pathname === '/users') {
          dispatch({
            type: 'querySuccess',
            payload: {}
          });
        }
      });
    },
  },

新版本接收的也应该是一个数组而并非对象吧，明显报错了～～，改过之后貌似没啥问题了又

**Comment by sorrycc** [comment]
subscriptions 在 1.0.0-beta 下是 Object，和 reducers 和 effects 保持一致。

**Comment by MaYing929** [comment]
好吧 容易误导吃瓜群众。谢谢解答～～～
