### ISSUE TITLE
Separate data and view (including router and react)

### ISSUE THREAD

**Issue by sorrycc** [dvajs/dva#530]
So we can use dva with 微信小程序、支付宝小程序 and other architectures, and we can choose other router implement.

- #529 
- #510 
- #354 
- #310 
- #195

**Comment by plandem** [comment]
no estimates?

**Comment by hbrls** [comment]
As you said, [dva is a framework not a library](https://github.com/dvajs/dva/issues/1). I'd like to see it focusing on an opinionated practice.

For @plandem, if it worths to replace `react-router` with `redux-router` or else, I'd be happy to that improvement. But if it's to support both and more, the effort and concept behind is not attractive.

**Comment by sorrycc** [comment]
It's just do some abstraction, e.g. a library called `dva-model`. And the export of dva will not change, and will not affect the existing use of dva users.

**Comment by nihgwu** [comment]
I'm using dva in React Native and NavigationExperimantal as the router component, the only concern for me is to detach irrelevant dependencies such as `react-dom` and `react-router`.

**Comment by plandem** [comment]
@hbrls yep, but there must be core concept of routing in terms of dva. E.g. at https://github.com/plandem/rrrouter I exposed next **required** props for any provider implementation:
```jsx
	route: PropTypes.shape({ ...locationPropTypes }).isRequired,
	go: PropTypes.func.isRequired,
	back: PropTypes.func.isRequired,
	forward: PropTypes.func.isRequired,
	navigate: PropTypes.func.isRequired,
```

so it's up to user how he is going to implement it (e.g. at HOC). But! I know nothing about dva's routing requirements. Especially it's can't work without redux, so we need some kind of middleware. E.g. at: https://github.com/plandem/rrrouter-provider-redux I created one. But as I said - I need to know some specification of dva routing abstraction .

**Comment by plandem** [comment]
ok, it tried to play a little with DVA (btw, sources quite hard to read. E.g.: https://github.com/d-band/fef   (fork of dva) is much easier and cleaner to read).

Here are step to make it work with my router (https://github.com/plandem/rrrouter):
```jsx
import React from 'react';
import createDva from 'dva/lib/createDva';

import { createMiddleware, HashHistory, reducer as routing } from 'rrrouter-provider-redux';

export default createDva({
	mobile: false,
	initialReducer: {
		routing,
	},
	defaultHistory: new HashHistory(),
	routerMiddleware: (history) => createMiddleware(history),
	setupHistory(history) {

	},
});
```

and init app like this:
```jsx
import './index.html';
import React from 'react';
import dva from './utils/dva';
import Router from 'rrrouter';
import { Provider } from 'rrrouter-provider-redux';

const app = dva();

const IndexPage = (props) => <div>index page</div>;
const NotFound = (props) => <div>Not Found</div>;

// 2. Model
app.model(require('./models/app'));

// 3. Router
app.router((props) =>(
	<Provider stateKey='routing' initHref='/'>
		<Router>
			<Router.Match path="/" handler={IndexPage}/>
			<Router.Miss handler={NotFound}/>
		</Router>
	</Provider>
));

// 4. Start
app.start('#root');
```

It remove dependency of React-Router and do some code cleanup, then I would be quite happy with current implementation.

**Comment by sorrycc** [comment]
Done in dva@2.
