### ISSUE TITLE
有多页面的示例供参考使用吗?

### ISSUE THREAD

**Issue by Liuthx** [dvajs/dva#531]
我看到文档中有 `multipage: true` 的配置, 说明是可以将公共js抽出, 但没有找到示例查看, 希望能提供下示例或配置指导, 感激不尽!

**Comment by sorrycc** [comment]
配 `multipage: true` 后会打包出公共的 common.js 和 common.css，其他没有变化。

**Comment by Liuthx** [comment]
我如果只配`multipage: true`的话, 运行dev时会报`index.js:1 Uncaught ReferenceError: webpackJsonp is not defined` 的错误. 
我在网上查到的结果是需要在自己的js之前引入公共文件, 但没有说具体应该怎么做, 能讲下吗?

**Comment by sorrycc** [comment]
在 html 里还需要引入 common.js 和 common.css 。
