### ISSUE TITLE
按需加载antd组件库nam run build 打包时，antd lib 里的文件报WARNING，是否有运行隐患？

### ISSUE THREAD

**Issue by maccyluo** [dvajs/dva#534]
参考antd官网使用import Button from 'antd/lib/button'; 这个方式按需加载antd组件库。在nam run build 打包时，antd lib 里的文件报WARNING 下面日志。组件可以正常运行使用，但这个warning 是否有隐患，是否需要处理，如何处理？ antd 版本号：  "antd@2.6.1"  ，dva版本号："dva@1.2.1"

日志：
WARNING in ./~/antd/lib/button/index.js
    There is another module with an equal name when case is ignored.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Rename module if multiple modules are expected or use equal casing if one module is expected.
    
    WARNING in ./~/antd/lib/Button/index.js
    There is another module with an equal name when case is ignored.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Rename module if multiple modules are expected or use equal casing if one module is expected.

**Comment by afc163** [comment]
路径是 `antd/lib/button` 不是 `antd/lib/Button`，是否代码里写错大小写了？

https://unpkg.com/antd@2.6.1/lib/button/

**Comment by maccyluo** [comment]
多谢支持。回复这么快。
仔细检查下，的确有个别文件路径写成大写的了， 抱歉。
