### ISSUE TITLE
是否可以支持next.js

### ISSUE THREAD

**Issue by hanagm** [dvajs/dva#537]
[next.js](https://github.com/zeit/next.js)

dva也可以支持服务端渲染，我觉得在这部分应该没有太大问题，
但是
next的router主要是基于systemfile来实现的
dva有没有好点方案可以实现支持?可以探讨一下

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/tree/master/packages/dva-example-nextjs

**Comment by didilinkin** [comment]
链接 已变更

最新 链接： https://github.com/dvajs/dva/blob/master/examples/with-nextjs/package.json
