### ISSUE TITLE
dva 路由onEnter会进入多次

### ISSUE THREAD

**Issue by sophiaMouse** [dvajs/dva#54]
想做登录拦截，打算放到路由中处理
但实际路由切换时，发现onEnter进入了多次

经验证：
router的function会进入两次，第一次没有传入app,第二次传入了app
route的onEnter 会进入多次（规则为2+订阅了history的model个数）

dva 版本 ：1.0.0-beta1

**Comment by sophiaMouse** [comment]
打算降级到0.0.6了，修改一下dva的render，就可以在路由中使用store了
router的function 跟 onEnter也不会进入多次
就是不能像1.0.0-beta1 一样写model了...

**Comment by sorrycc** [comment]
看起来像是这里引入的，https://github.com/dvajs/dva/blob/deafb9466d2f2272ebbd5767d09aea59a0c7c7ca/src/index.js#L23

**Comment by sophiaMouse** [comment]
嗯，确实是这部分引起的
我用onEnter 跟 onLeave话，订阅history就不是很有必要了，我先注释了

感谢

**Comment by sorrycc** [comment]
这段逻辑有些不妥，加的时候就担心会有副作用，我想想要不要去掉。

**Comment by sorrycc** [comment]
match 的逻辑下个 beta 版里会去掉，然后 params 通过 path-to-regexp 获取，参考：https://github.com/dvajs/dva-hackernews/commit/3314c7cf0751def7a87b351b87983aba0ba4b100

**Comment by sorrycc** [comment]
bumped dva@1.0.0-beta2
