### ISSUE TITLE
subscriptions在react-native中如何才能做到在特定的情况下去加载数据.?

### ISSUE THREAD

**Issue by HengCC** [dvajs/dva#542]
subscriptions在react-native中如何才能做到在特定的情况下去加载数据.?

路由用的是react-native-router-flux. 比如我只想在进入到某个列表页面才会根据条件去加载数据. 

还是说现在没办法支持. 只能通过组件的生命周期去写这样的过程.

**Comment by sorrycc** [comment]
react-native 里能获取到当前是在哪个页面吗?

**Comment by HengCC** [comment]
history是空的. 这个只有react-router才有. native没有办法判定当前是哪个页面. https://github.com/aksonov/react-native-router-flux

**Comment by nihgwu** [comment]
RNRF 本身就支持 redux，在其他 model 里面 select 出当前路由的 state 就行了
