### ISSUE TITLE
npm run build时env为undefined

### ISSUE THREAD

**Issue by hansnow** [dvajs/dva#543]
dva版本: 1.2.1

在 #345 中提到的，`npm start`的env为`development`，但是`npm run build`的env实际为`undefined`，并非预期的`production`

**Comment by sorrycc** [comment]
怎么配置的? 工具用的什么?

**Comment by hansnow** [comment]
@sorrycc 项目是使用`dva new`创建的，除了在package.json中添加了包之外其他并没有改什么东西

**Comment by sorrycc** [comment]
env 在哪获取的?

**Comment by hansnow** [comment]
@sorrycc 在`webpack.config.js`的
``` javascript
module.exports = function(webpackConfig, env)
```
函数内。
我刚刚试了一下，用`dva new`新建项目之后不做任何其他操作就能重现这个问题

**Comment by sorrycc** [comment]
升级 dva-cli 到最新，然后创建项目实施。

```bash
$ npm install dva-cli@0.7 -g
```

**Comment by hansnow** [comment]
@sorrycc 唔...dva-cli升级到了`0.7.8`之后`dva new`了一下，发现已经是基于roadhog的了。目前项目已经写的比较大了，暂时不准备换成其他方案，所以就先`env || 'production'`解决吧
