### ISSUE TITLE
dva/fetch 在微信的中能否正常使用！

### ISSUE THREAD

**Issue by jingchenxu** [dvajs/dva#547]
因为打算在用dva这个框架完成一个微信项目的开发，所以下下讨论下在微信中dva/fetch能否正常使用，如果不能的话，有没有什么比较好的替代方案。

**Comment by ityao** [comment]
可以啊

**Comment by sorrycc** [comment]
iOS safari 应该是[不支持](http://caniuse.com/#search=fetch)的，不确定微信是否支持。还可以试试 https://github.com/mzabriskie/axios
