### ISSUE TITLE
关于上测试、UAT、生产等不同的环境的时候的缓存问题

### ISSUE THREAD

**Issue by programmer-yang** [dvajs/dva#549]
大哥大神新年好，我想请问一下，在使用dva的时候代码开发完毕到了测试阶段
```
npm run build
```
编译后的代码上到不同的测试环境，是如何解决js、css、图片、等其他一些静态资源的缓存问题的？
> 我的想法是构建index.html的加载js、css的标签加上随机数或者版本号，但这样就需要roadhog的支持，总不会自己手动去加吧

**Comment by sorrycc** [comment]
已记 issue，在 https://github.com/sorrycc/roadhog/issues/69 跟进。
