### ISSUE TITLE
initialState参数配置

### ISSUE THREAD

**Issue by carlos121493** [dvajs/dva#55]
initialState参数，必须要将namespace里面的所有state全部写出来
类似这样的结构
```
 {
 namespace: {
   ...state
  }
}
```

initialState能不能只写namespace中部分的state，因为state部分是在model中设置了初始化值的。
而动态创建dva的时候只希望部分initialSate有用。

**Comment by sorrycc** [comment]
动态创建 dva ? 具体场景是啥? 

---

initialState 和 model.state 区别如下：

- initialState 是初始值，通常来自服务器端给的数据，或者 localStorage 里取的数据
- model.state 是初始化 model 时的默认值
- 优先级上，initialState 大于 model.state

**Comment by carlos121493** [comment]
嗯,就是initialState里的state可不可以只给部分？
还会报错。
![](https://zos.alipayobjects.com/rmsportal/OSdrMtGmOgkYmff.png)

dva已经更新到1.0.0-beta1 版了

**Comment by sorrycc** [comment]
initialState 的数据给多了?

**Comment by carlos121493** [comment]
sorry 我发现可以只给部分 state，只是，报错还是会有

**Comment by sorrycc** [comment]
印象中，给多了才会报错吧。

**Comment by carlos121493** [comment]
没多，发现initialState可以给少的，只是会全局将Modal中的state替换掉，然后还会报错。

**Comment by carlos121493** [comment]
可能是我model里的state给的比initialState多？

**Comment by sorrycc** [comment]
给个能重现的代码示例，我跑跑看。

**Comment by carlos121493** [comment]
加了你的权限 http://gitlab.alipay-inc.com/ladybug/ladybug-core
