### ISSUE TITLE
为什么我用$ dva命令创建出来的项目，node_modules里面的文件夹都是快捷键文件夹

### ISSUE THREAD

**Issue by yemingsha** [dvajs/dva#550]
根据官方文档，用这个命令创建自己的项目
$ dva new 自己的项目名
![image](https://cloud.githubusercontent.com/assets/19774585/22451531/53e9cc12-e7aa-11e6-90d9-8fc153e3800b.png)
导致我用webstorm打不开这种含有快捷键文件夹的项目

**Comment by sorrycc** [comment]
1. 关闭 webstorm
1. npm i webstorm-disable-index
1. 重新开 webstorm

**Comment by yemingsha** [comment]
谢谢sorrycc，但是为什么会创建出这种带快捷键的文件夹啊。我的环境有问题？
![image](https://cloud.githubusercontent.com/assets/19774585/22455603/88cea204-e7c8-11e6-9c24-7373ec817b5e.png)

**Comment by afc163** [comment]
https://github.com/cnpm/cnpm/issues/106#issuecomment-257499243
