### ISSUE TITLE
如何部署?

### ISSUE THREAD

**Issue by mansters** [dvajs/dva#551]
想请教一下如何部署, 运行`$ npm build` 之后, 打包好的文件如何部署到服务器上? 放到静态服务器上直接指向 index.html 文件? 还是要整合到后台代码之中? 现在因为方便多个人一起看, 直接将代码上传到服务器上, 然后运行 `$ npm start`. 相应的端口都已经开放了, 但是外网访问不了, 不知道什么原因, 希望可以给一些指点

**Comment by sorrycc** [comment]
部署可以参考 https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment
