### ISSUE TITLE
打包未包含antd样式

### ISSUE THREAD

**Issue by sz30313484** [dvajs/dva#552]
start下页面正常，build后页面不正常，经检测发现antd样式没有被打包。package.json如下：
{
  "private": true,
  "scripts": {
    "start": "roadhog server",
    "build": "roadhog build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "engines": {
    "install-node": "6.9.2"
  },
  "dependencies": {
    "antd": "^2.6.4",
    "babel-runtime": "^6.9.2",
    "dva": "^1.2.1",
    "react": "^15.4.0",
    "react-dom": "^15.4.0"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "babel-plugin-dva-hmr": "^0.2.0",
    "babel-plugin-import": "^1.1.0",
    "babel-plugin-transform-runtime": "^6.9.0",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "expect": "^1.20.2",
    "husky": "^0.12.0",
    "redbox-react": "^1.3.2",
    "roadhog": "^0.4.0"
  }
}

**Comment by sorrycc** [comment]
检查下 `.roadhogrc`，是否只在 development 时加载了 babel-plugin-import 插件。

**Comment by sz30313484** [comment]
嗯，是这个问题，已经解决了

**Comment by zchuhui** [comment]
@sz30313484 请问如何解决的？

**Comment by sz30313484** [comment]
@zchuhui 
"env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }]
      ]
    }
  }
