### ISSUE TITLE
roadhog 提供css、js按文件导出，而不是默认script到html

### ISSUE THREAD

**Issue by beiyeren** [dvajs/dva#555]
![image](https://cloud.githubusercontent.com/assets/3363044/22625398/1bd695f6-ebd0-11e6-86e2-4c89c3be1a04.png)

**Comment by sorrycc** [comment]
开发模式下用内链样式的，原因是为了样式的热替换；生成环境下是用 `<link>` 链的。

**Comment by beiyeren** [comment]
收到，多谢
