### ISSUE TITLE
connect 的时候，是否可以结合reselect使用

### ISSUE THREAD

**Issue by pmg1989** [dvajs/dva#558]
![image](https://cloud.githubusercontent.com/assets/13361827/22639470/33660f44-ec89-11e6-8f04-c0a76b6e308e.png)
@sorrycc ，烦请问下，如图用法我尝试了下，是没有问题的，不知道是否多余，
也就是默认的connect(({ app }) => ({ app }))(App)，是否已经优化了reselect的功能呢？
我这里结合ant-design时遇到一个问题，初步解决方案如图，请问有更好的处理方案么？
https://github.com/zuiidea/antd-admin/issues/61

**Comment by sorrycc** [comment]
connect 目前没有集成 reselect，要优化性能需自己加 reselect 。
