### ISSUE TITLE
dva在使用roadhog时是否可以集成express？

### ISSUE THREAD

**Issue by YutHelloWorld** [dvajs/dva#560]

**Comment by sorrycc** [comment]
目前就是基于 webpack-dev-server （背后是 express）实现的，具体需求是啥?

**Comment by YutHelloWorld** [comment]
我们想用express+mongo作为后端数据源，但是在在usr-dashboard这个demo中，看到打包编译采用roadhog，数据采用的是代理。尝试着把express放进去，不知道如何实现？

**Comment by strommmm** [comment]
express+mongo做数据源，就是API服务器喽，这样前后端分离，为啥要加进去？单独一个工程呗，然后用nginx反向代理放在同一个域下，或者直接开了跨域
