### ISSUE TITLE
老的user-dashboard例子加了个登录model，如何使用登录model修改user model的keyword呢？

### ISSUE THREAD

**Issue by zyx4986** [dvajs/dva#561]
登录后，如何修改user model中keyword的值呢？或者讲model之间如何交互呢？

**Comment by nikogu** [comment]
表意不清楚，想要修改数据使用 dispatch 调用 reducer 就好了

**Comment by zyx4986** [comment]
改一下表述，就是登录后访问 /user 这个网址，想加一个搜索条件，登录后访问 /user?key=...
这个key怎么在登录后就加入进去，并且在换页时一直存在

**Comment by mansters** [comment]
@zyx4986 
在 model 中引用 routerRedux
`import { routerRedux } from 'dva/router';`

登录成功时候使用 routerRedux.push 跳转到指定页面
`yield put( routerRedux.push( ... ) );`

若需要 key 一直存在, 不建议存放在 url 中, 可以放入 state 中, 需要的时候从 state 中获取.

**Comment by hst-Sunday** [comment]
@zyx4986
请问你是怎么解决的？
