### ISSUE TITLE
页面发起一个异步请求如何在请求返回后回调页面函数

### ISSUE THREAD

**Issue by taven-liu** [dvajs/dva#563]
例如A页面有个按钮 点击后`dispatch`了 `model`一个`effects`然后如何根据`call`后的`service`的返回值去回调页面A的方法

A页面
`dispatch({type: 'app/regist', payload: data})`
modal
``` 
*regist({
  payload
}, {call, put}){
//调用service中的regist方法
  const data = yield call(regist, payload);
  if(data.code === '0'){
    //TODO 如何回调页面A中的方法
  }
}
```

**Comment by nikogu** [comment]
一般来说建议将页面方面抽象为数据状态，但是如果必须调用的话，可以将页面方法通过参数传递到 effects 中调用（callback）

**Comment by taven-liu** [comment]
嗯，已解决，谢谢
