### ISSUE TITLE
为什么？

### ISSUE THREAD

**Issue by WangZi1997** [dvajs/dva#564]
You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

**Comment by sorrycc** [comment]
开发模式下出现的?

**Comment by WangZi1997** [comment]
生产模式

**Comment by sorrycc** [comment]
那应该是你打包方式不对，没用 roadhog 或者 atool-build 吧?

**Comment by WangZi1997** [comment]
用的 atool-build

**Comment by WangZi1997** [comment]
![image](https://cloud.githubusercontent.com/assets/19681693/22766413/3f93776a-eeb0-11e6-9136-0fa9ba8c992e.png)
![lvrw4_6 0d c8yj hh ev 1](https://cloud.githubusercontent.com/assets/19681693/22766435/5effa704-eeb0-11e6-8419-59e0750f19d2.png)

**Comment by sorrycc** [comment]
https://github.com/ant-tool/atool-build/blob/e4bd295/src/build.js#L35
atool-build 有加这一段，应该不会出现你这个问题才对。

**Comment by sorrycc** [comment]
可以排查下 `process.env.NODE_ENV` 是否为空。

**Comment by WangZi1997** [comment]
对  undefined

**Comment by sorrycc** [comment]
这个问题有解决吗?

**Comment by huanhub** [comment]
这个问题后面怎么解决呢？我现在也遇到这个问题了
