### ISSUE TITLE
如何取数组中的前两个值组成新的数组

### ISSUE THREAD

**Issue by RaeZeva** [dvajs/dva#569]
const mapTableData =(tableData)=>{
    	let arr = [];

    	tableData.map((i,value)=>{
    		if(i.parentsname){
    			arr.push(i.parentsname);

    			let sonnameSource = i.data;
			
				if(sonnameSource.length>1){
					sonnameSource.map((i,value)=>{
						arr.push(i.sonname);
					})
				}
				console.log(arr);
				
    		}

	})
	return arr;
    };

**Comment by afc163** [comment]
你不应该在这里问 js 的问题。

**Comment by RaeZeva** [comment]
我以为框架不一样呢，已经写出来了。
