### ISSUE TITLE
表格控件td中内容是遍历出来的，如何在两条数据中加分隔符，在最后加...

### ISSUE THREAD

**Issue by RaeZeva** [dvajs/dva#570]
这是两条数据，遍历出来单元格内就显示这样huaweichangxiang5
想实现类似这样的效果：
huawei  |  changxiang5...

**Comment by nihgwu** [comment]
DO NOT SPAWN

**Comment by mansters** [comment]
@RaeZeva 使用 React 原生去遍历 还是 antd 的表格拆件? 原生的话可以使用es6的[字符串模板](http://www.infoq.com/cn/articles/es6-in-depth-template-string)来实现例如` ${arg1} | ${arg2} `, antd 的表格插件的话, 可以参考 antd 表格的[Column设置](https://ant.design/components/table-cn/#Column)中的 render 选项

**Comment by RaeZeva** [comment]
@mansters 两条数据中我加上了间隔，但是后面的...是拼接的字符串，代码如下，不知是否合理：
           {
			title: '终端',
			dataIndex: 'brandcontents',
			key: 'brandcontents',
			render: (text, record, index) => (
	                         mapTableData(record.brandcontents)
	                ),
           },
           {
			title: '地区',
			dataIndex: 'areacontents',
			key: 'areacontents',
			render: (text, record, index) => (
	                        mapTableData(record.areacontents)
	                 ),
	    },
	   {
			title: '已设置项目',
			dataIndex: 'modulecontents',
			key: 'modulecontents',
			render: (text, record, index) => (
	                      mapTableData(record.modulecontents)
	                ),
	 },
function如下：
 const mapTableData =(tableData)=>{
    	let arr = [];
    	let dataArr= [];
    	let flag = false;


    	tableData.map((i,value)=>{
     		//终端，地区
    		if(i.parentsname){
    			flag = true;
    			arr.push(<span key={i.parentsid} className={styles.item}>{i.parentsname}</span>);

    			let sonnameSource = i.data;
			
				if(sonnameSource.length>1){
					sonnameSource.map((j,value)=>{
						arr.push(<span key={j.sonid} className={styles.item}>{j.sonname}</span>);
					})
				}
    		}

			//已设置项目
			if(i.modulename){
				flag=false;
				arr.push(<span key={i.moduleid} className={styles.item}>{i.modulename}</span>);
			}

		})

    	if(flag){
    		if(arr.length>2){
	    		let a = arr[0];
				let b = arr[1];
				dataArr.push(a);
				dataArr.push(b);
		
				dataArr.push("...");
			
				return dataArr;
	    	}else{
	    		return arr;
	    	}
    	}else{
    		return arr;
    	}
    };
