### ISSUE TITLE
dom标签是否可以像js一样自定义属性

### ISSUE THREAD

**Issue by RaeZeva** [dvajs/dva#572]
我要对表格数据执行删除操作，而删除要用到每条数据的id
是否可以给每条数据的tr加自定义属性，将本条数据的id值存上，比如<tr dataId="xxx"></tr>

如果是jq的话，点击删除按钮时获取到id作为参数之一即可跑接口了，那dva如何实现呢

**Comment by nihgwu** [comment]
你把这里当记事本吗？再继续就举报
