### ISSUE TITLE
请问如何调用 put.resolve() 方法

### ISSUE THREAD

**Issue by sunzd116** [dvajs/dva#573]
saga 的文档里有一个阻塞的 put 方法 put.resolve(action) [saga api](https://redux-saga.github.io/redux-saga/docs/api/index.html#putresolveaction) 但是在 dva 里找不到

**Comment by sorrycc** [comment]
`put.resolve` 目前是不支持。

**Comment by sunzd116** [comment]
我最后找了个办法 用 call 包裹 put
`
function * xxx({call, put}){
   yield put({
     *******
   })
};
`
`
yield call(xxx,{put, call});
 `

**Comment by anson0370** [comment]
想请问一下有什么特殊的原因不支持吗？看了下代码发现 dva 是为了在同 model 里省略 namespace 所以覆盖了 put 方法，但是没有额外覆盖 put.resolve 。如果没什么特殊原因的话，我来提个 PR 。

**Comment by sorrycc** [comment]
感觉没啥理由使用 `put.resolve`，完全可以用 `call` 代替吧。

**Comment by pedroteixeira** [comment]
Can we `call({'type': 'action'})`? I think call expects a function, not an action.
That is the point of put.resolve.. am I missing something?

**Comment by fritx** [comment]
@sunzd116 not works, I tried:

```js
function *xxx(arg) {
  return yield put(arg);
}
const meta = yield call(xxx, {
  type: 'getStaffModalMeta',
  payload,
});
console.log('meta', meta); // got Promise {<pending>}
```

**Comment by fritx** [comment]
Okay, it works

```js
const promise = yield put({
  type: 'getStaffModalMeta',
  payload,
});
const meta = yield call(() => promise);
```

**Comment by WavinFlag** [comment]
For anyone wondering can use or not, `put.resolve` was added in PR #1690 (21 May 2018) and included in releases since v2.3.0.

v2.3.0 开始已经可以使用 `put.resolve`。
