### ISSUE TITLE
多页面应用中 需要全局Store 应该存在哪个文件里面比较合适？

### ISSUE THREAD

**Issue by thomastao0215** [dvajs/dva#574]
比如要做一个控制整个App的应用 要在页面跳转中仍然保持登录状态，想到用一个全局Store，然后这个Store应该放在哪里比较合适？是index.js还是router.js

**Comment by sorrycc** [comment]
`router.js` 肯定不合适，放 `index.js` 或者另外抽一个文件出来都可以吧。

**Comment by zyx4986** [comment]
sessionstorge或者localstorge
