### ISSUE TITLE
build后的文件放在tomcat或者nginx下面，页面空白，看页面源码正常。

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#577]
开发调试都正常，现在想发布版本，npm run build后也提示经过gzip压缩优化的结果，文件也小了些，放在tomcat里面访问的时候，页面空白，页面源码也没有问题，看控制台也没有问题...

官方的userboard也是一样，难道是我哪儿做的不对？

还有个疑问，我build userboard时，会有1.1.js...我自己的项目又没有...

**Comment by GrayChoi** [comment]
服务器路由路径和页面路由一致吗

**Comment by bjwulin** [comment]
确实是路由不一致，我放在tomcat的Root的dist目录下，访问http://127.0.0.1:8080/dist/就显示空白页，如果直接放在Root下，访问http://127.0.0.1:8080就没问题。

只能调整redux router?

**Comment by bjwulin** [comment]
我让服务端路由路径为空，http://localhost:8080/main，main是页面路由路径，这个时候，如果f5刷新，向服务器发请求，服务器拦截/main，结果又报错...大家是咋整的？

**Comment by sorrycc** [comment]
这是服务端配置问题，自行找方案解决吧，主要是要让请求 `/main` 时能正确的输出 html 内容。也可以参考下这里的文档：https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

**Comment by GrayChoi** [comment]
@bjwulin 服务器重写url到/
