### ISSUE TITLE
按照项目实战里的步骤搭建了一个简单的dva工程,然后访问，发现css加载异常

### ISSUE THREAD

**Issue by dunmengjun** [dvajs/dva#582]
1.按照官网的教程操作
![1](https://cloud.githubusercontent.com/assets/14136848/22819301/73a48bc8-efac-11e6-92dd-16b0d7f7d334.png)

2.访问 http://localhost:8000 
![2](https://cloud.githubusercontent.com/assets/14136848/22819309/7c77c7d8-efac-11e6-9ec2-14dae14b4a82.png)

3查看了一下加载的资源
![3](https://cloud.githubusercontent.com/assets/14136848/22819315/816d61bc-efac-11e6-957a-005d11b10173.png)

发现加载的是主页的html 我并没有做任何其他操作，只是按照教程创建了一个项目，后面导致antd的样式都加载不出来 这是否是bug?

**Comment by sorrycc** [comment]
1. 调试状态下 CSS 是通过 JS 载入的，所以 CSS 文件内容不对的问题可以忽略
2. 是不是没有配 babel-plugin-import 插件？参考 https://github.com/sorrycc/blog/issues/18 第二步

**Comment by dunmengjun** [comment]
@sorrycc  谢谢您的解答
您说的第二步我做了的
![11](https://cloud.githubusercontent.com/assets/14136848/22926936/a7252e9a-f2e9-11e6-8aad-0f46eb650f03.png)
![44](https://cloud.githubusercontent.com/assets/14136848/22927141/b2d7c2ce-f2ea-11e6-9ef9-1e10ce966af8.png)
这是我全部做完之后的，我检查了很多遍，不知道问题出在哪里
![22](https://cloud.githubusercontent.com/assets/14136848/22926967/d9bfca4a-f2e9-11e6-96ed-db34a8fab33c.png)
![33](https://cloud.githubusercontent.com/assets/14136848/22927006/0e4886d0-f2ea-11e6-8112-53642b25ea04.png)
由此可见，好像css并没有被加载进来
界面能正常点击，能删除，不能取消

我全程用的是cnpm,不知道和这是否有关系

**Comment by dunmengjun** [comment]
ok,问题解决了，是我自己忘记在.roadhogrc文件中加代码了，我只加了production 的，其实要加两个地方
![55](https://cloud.githubusercontent.com/assets/14136848/22956847/760ad97e-f35f-11e6-9f19-da0406ff8e13.png)

**Comment by yinsang** [comment]
我也是不能用，加了production中的代码也不能用。
我用rm -rf node_modules,然后重新npm i之后好了。

**Comment by zhangxi337** [comment]
@dunmengjun 按你说的加上就好了
