### ISSUE TITLE
关于nginx反向代理后的按需加载问题

### ISSUE THREAD

**Issue by programmer-yang** [dvajs/dva#584]
大神们好，小弟最近在使用dva的时候遇到了一个关于按需加载的问题
实现按需加载后不同的路由在`npm run build`分别编译为不同的js文件
`1.1.js 2.2.js 3.3js `
我在`index.html`中使用
```html
<script src="index.js"></script>
```
导入核心js
在浏览器中使用域名访问这个index.html
http://xxxxxx.com/xxx
这时遇到问题，index.html标签里的index.js能正常获取到，但index.js里的按需加载x.x.js无法正常获取。
原因是在获取index.js的时候会带上http://xxxxxx.com/xxx/二级域名，但x.x.js会直接去http://xxxxxx.com上获取没有二级域名无法获取到。
不知道各位大神有没有遇到同样的问题，还是我设置有问题

**Comment by hirohe** [comment]
设置一下[publicPath](https://github.com/webpack/docs/wiki/configuration#outputpublicpath)为你的二级域名

**Comment by programmer-yang** [comment]
@hirohe 谢谢大神
