### ISSUE TITLE
Chrome Dev Tools中model文件怎么没有办法断点调试， 打不了断点

### ISSUE THREAD

**Issue by suweya** [dvajs/dva#585]
Chrome Dev Tools中model文件怎么没有办法断点调试， 打不了断点

**Comment by nihgwu** [comment]
model 本来就只是个 JSON 数据而已，里面的 reducers/effects 都会被重新组装

**Comment by suweya** [comment]
@nihgwu 那有没有什么办法可以调试的？

**Comment by nihgwu** [comment]
![image](https://cloud.githubusercontent.com/assets/2595058/22834152/31df5e5a-efef-11e6-9b2b-26fc5e05700f.png)
经测试，可以打断点
