### ISSUE TITLE
路由使用browserHistory，获取js文件返回了页面

### ISSUE THREAD

**Issue by gitoneman** [dvajs/dva#588]
import { browserHistory } from 'dva/router';
const app = dva({
  history: browserHistory,
});
把路由设置成browserHistory后，刷新页面，获取资源文件都是返回了页面

![image](https://cloud.githubusercontent.com/assets/4230192/22876022/968b5c02-f209-11e6-80a8-bbd355a1207f.png)

用roadhog启动的该怎么配置

**Comment by sorrycc** [comment]
资源文件要被访问到，需要[放在 public 目录](https://github.com/sorrycc/roadhog#使用-public-目录)。
