### ISSUE TITLE
在react-native环境下使用dva，必须要安装react-dom，不然会报错。

### ISSUE THREAD

**Issue by vxzhong** [dvajs/dva#590]
react-native: 0.41
dva: 1.x

import dva from 'dva/mobile'

虽然createDva里使用require('react-dom')的代码实际是跑不到的，但是在react-native的react-native run-ios的启动打包阶段还是会包含react-dom，如果react-dom不存在就会报错。必须安装react-dom。

**Comment by sorrycc** [comment]
目前是必须安装 react-dom ，但在 react-native 中不会真正用上。是一个待改进的点。

**Comment by nihgwu** [comment]
@sorrycc 还有个建议就是下个版本建议改成 `dva/native`
