### ISSUE TITLE
roadhog mock中的post方法req无法获取body

### ISSUE THREAD

**Issue by zhangyezeng** [dvajs/dva#593]
.roadhogrc.mock.js文件中
'POST /api/login': function (req, res) {
    const userItem = req.body
    //req.body始终都是undefined
    const response = {
      success: false,
      message: ''
    }
    
    res.json(response)
  }
请问一下这是什么原因啊，body总是获取不到,这样就拿不到post传来的值了

**Comment by sorrycc** [comment]
抱歉，还不支持，在 https://github.com/sorrycc/roadhog/issues/86 跟进吧，最近时间少，欢迎动手 PR 。
