### ISSUE TITLE
引用form时报错

### ISSUE THREAD

**Issue by RaeZeva** [dvajs/dva#595]
Warning: `Form.Item` cannot generate `validateStatus` and `help` automatically, while there are more than one `getFieldDecorator` in it.

为了给radioGroup赋初值用到了form，控制台报错，但未影响运行

**Comment by nihgwu** [comment]
去 https://github.com/ant-design/ant-design 报，跑这里捣什么乱

**Comment by RaeZeva** [comment]
好的，多谢
