### ISSUE TITLE
执行npm run build然后直接双击dist/index.html，dva下已经无法访问了吗？

### ISSUE THREAD

**Issue by yuzhouisme** [dvajs/dva#596]
执行命令后得到dist目录如下：
.
├── 0.0.js
├── 2.2.js
├── 3.3.js
├── 4.4.js
├── 5.5.js
├── 6.6.js
├── index.css
├── index.html
└── index.js

环境：
node v6.9.4
npm 3.10.10
dva 0.7.8

报错：
Failed to load resource: net::ERR_FILE_NOT_FOUND

请教

**Comment by sorrycc** [comment]
如果是用 browserHistory，要要启 server 才能访问，否则路由匹配不到。

**Comment by yuzhouisme** [comment]
@sorrycc 

我是工程中，没有使用browserHistory，代码如下述：
// 1. Initialize
const app = dva({
  // history: browserHistory,
  onError(e) {
    message.error(e.message, ERROR_MSG_DURATION);
  },
});

我准备新建一个工程然后打包，直接双击再试试

**Comment by forbreak** [comment]
我也是这种情况用浏览器的开发者工具查看，发现 页面引入 0.0.js 时候是<script type="text/javascript" charset="utf-8" async="" src="/0.0.js"></script> 这样的，如果去掉／ 应该就可以了，不知道怎么去掉。

**Comment by sorrycc** [comment]
为啥一定要双击访问呢? 要去掉 `/`，把 [publicPath](https://github.com/sorrycc/roadhog#publicpath) 配成空的试试。

**Comment by forbreak** [comment]
@sorrycc  把publicPath 改成"",也没效果，publicPath 好像并没起到作用。

**Comment by sorrycc** [comment]
那应该没啥办法了。。不要本地双击访问了吧。
