### ISSUE TITLE
请教一下使用function创建的组件如何拿到this

### ISSUE THREAD

**Issue by taven-liu** [dvajs/dva#597]
使用function方式创建的组件A与model绑定后，可以在函数体内拿到 `location`, `routes`, `history`等参数，现在需要在手动去跳转，我用`history.goBack()`提示" Warning: [react-router] `props.history` and `context.history` are deprecated. Please use `context.router`. http://tiny.cc/router-contextchanges",
在使用`React.createClass`可以直接通过`this.context.router`去操作，那么用function方式该如何操作呢，谢谢各位亲哥帮忙看看。

**Comment by hnsylitao** [comment]
`
static contextTypes = {
    router: React.PropTypes.object
  }
`

**Comment by taven-liu** [comment]
没明白哈，这种不是限制props的类型的吗

**Comment by taven-liu** [comment]
app-add.js
```
function AppAdd(state) {
	const {
		appAdd,
		dispatch,
		history,
		form
	} = state;

	const fn = () => {
		//TODO 这个方法被执行时有警告  " Warning: [react-router] props.history and context.history are deprecated. Please use context.router. http://tiny.cc/router-contextchanges"
		//那么如何进行调整
		
        history.goBack();
   }
   retun (
		<div>
			.
			.
			.
		</div>
   )
}


export default connect(({appAdd}) => ({appAdd}))(Form.create()(AppAdd))
```

**Comment by taven-liu** [comment]
以前是通过
```
static contextTypes = { router: React.PropTypes.object }

this.context.router.goBack()
```
这种方式去做跳转的，现在通过function方式创建的是拿不到这个this的，那么有什么办法拿到这个router呢

**Comment by sorrycc** [comment]
https://facebook.github.io/react/docs/context.html#referencing-context-in-stateless-functional-components
第二个参数就是 context 。

**Comment by taven-liu** [comment]
感谢云谦大神，收下我的膝盖

**Comment by taven-liu** [comment]
刚仔细看了下，虽然还是不很明白，大概就是不建议使用`context`，既然不建议使用那么还有其他更好的方式进行跳转吗

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva-knowledgemap#%E5%9F%BA%E4%BA%8E-action-%E8%BF%9B%E8%A1%8C%E9%A1%B5%E9%9D%A2%E8%B7%B3%E8%BD%AC

**Comment by wuyunjiang** [comment]
哈哈，遇到了同样的问题，感谢大神
