### ISSUE TITLE
更改代码的时候会报warning,但是刷新就不会

### ISSUE THREAD

**Issue by ouzhou** [dvajs/dva#599]
![image](https://cloud.githubusercontent.com/assets/7693866/22980643/09c9e176-f3d5-11e6-8015-bbfa89cbd99f.png)
![image](https://cloud.githubusercontent.com/assets/7693866/22980656/126a2426-f3d5-11e6-8588-a607c7c8bccc.png)

这个错误的意思是我没写reducer? 但是我写了的呀，而且这个错误只在更改代码热跟新的时候出现，刷新就没有这个

**Comment by sorrycc** [comment]
热更新的 warning 先忽略吧。
