### ISSUE TITLE
在ant官方项目实战 遇到一些问题？

### ISSUE THREAD

**Issue by next2014** [dvajs/dva#601]
![_20170216135913](https://cloud.githubusercontent.com/assets/7641722/23009481/201b1874-f451-11e6-97b0-fe087a106b69.png)
![_20170216135839](https://cloud.githubusercontent.com/assets/7641722/23009498/3f71ae90-f451-11e6-98c3-5dda893a8c2e.png)
![_20170216135759](https://cloud.githubusercontent.com/assets/7641722/23009504/457d5758-f451-11e6-99d8-b0b8b1097faf.png)

**Comment by sorrycc** [comment]
出错信息很明显了，IndexPage 使用前未引入或者未定义吧。
