### ISSUE TITLE
demo 裡面的組件設計方法和文件為什麼不同?

### ISSUE THREAD

**Issue by is7and11** [dvajs/dva#603]
參考 **组件设计方法** 裡面的說明.

components 下面應該要是 Presentational Component 組件

下面是解釋：
除了写法上订阅数据的区别以外，在设计思路上两个组件也有很大不同。 Presentational Component是独立的纯粹的，这方面很好的例子，大家可以参考 ant.design UI组件的React实现 ，每个组件跟业务数据并没有耦合关系，只是完成自己独立的任务，需要的数据通过 props 传递进来，需要操作的行为通过接口暴露出去。 而 Container Component 更像是状态管理器，它表现为一个容器，订阅子组件需要的数据，组织子组件的交互逻辑和展示。

但為什麼 demo 裡面的程式碼做法不同. 

dva-example-user-dashboard/src/components/Users/Users.js 

function mapStateToProps(state) {
  const { list, total, page } = state.users;
  return {
    loading: state.loading.models.users,
    list,
    total,
    page,
  };
}

export default connect(mapStateToProps)(Users);

反而要監測數據？

謝謝

**Comment by sorrycc** [comment]
推荐 demo 里那种方式，在需要 connect 时 connect，而且这样性能会更好。
