### ISSUE TITLE
如何将react的依赖通过外部引入

### ISSUE THREAD

**Issue by charsunny** [dvajs/dva#604]
程序直接在钱包中运行，直接通过外链的方式链接react和react-dom的库，webpack的config也配置了：
webpackConfig.externals = {
    'react': 'React',
    'react-dom': 'ReactDOM',
  };

但是进行atool-build的时候 压缩包还是把react和react-dom打包进去，是不是还需要什么额外的配置?

**Comment by sorrycc** [comment]
是不是应该配成这样：

```js
externals: {
  react: 'window.React',
  'react-dom': 'window.ReactDOM',
},
```

**Comment by charsunny** [comment]
是的，配置已经加上这样子了。但是运行antd-build的时候，还是会把react打包进去。

**Comment by ethanzhanxd** [comment]
期待解决

**Comment by K-walker** [comment]
哥们我现在也遇到这个问题，我也想将react相关的包通过外部链接引入，配置了externals如下：
```
externals: {
  react: ’window.React‘,
  react-dom: ‘window.ReactDOM’,
}
```
打包后虽然 index.js 文件是小了，但是访问index.html 却报错了，我在inde.html中也引用了react 和react-dom的js，请问你是如何做的啊，有没有解决啊！
