### ISSUE TITLE
dva 里如何实现离开当前页面(刷新或关闭)时执行确认操作？ 

### ISSUE THREAD

**Issue by sven0726** [dvajs/dva#607]

**Comment by sven0726** [comment]
是否用window.onbeforeunload？放置在哪里 ？

**Comment by sorrycc** [comment]
离开当前页面是指关闭当前页面还是切换到另一个路由?

**Comment by sven0726** [comment]
都是吧，离开或者切换都是我要处理的情况。 也就是对于一个编辑页面，尚未保存情况做提示用户保存

**Comment by sorrycc** [comment]
> 关闭当前页面

用 `window.onbeforeunload` 就可以，放 `index.js` 里。

> 切换到另一个路由

[用 action 控制路由的切换](https://github.com/dvajs/dva-knowledgemap#%E5%9F%BA%E4%BA%8E-action-%E8%BF%9B%E8%A1%8C%E9%A1%B5%E9%9D%A2%E8%B7%B3%E8%BD%AC)，切换前加代码提示。

**Comment by sven0726** [comment]
“放 index.js 里” 这是控制了全局，我需要的是一个页面的。 为了实现 “离开当前页面，确认是否保存修改内容”这个功能，要用上述两者都实现才能实现，代码是不是不优雅了？

能否使用routeLeaveHook 来监听离开时间，然后判断相应逻辑，做相应处理。

抑或能有像componentWillUnmount 那样在UI 容器组件Unmount时处理相应业务逻辑，不知道在dva这块怎么做比较好

**Comment by YueHui** [comment]
那就直接用componentWillUnmount呗

**Comment by szwork2013** [comment]
@sorrycc 我的问题也类似，在移动antd-mobile 导航常常需要有 返回 操作 ,比如在分页的list.js 页面访问到详细页面detail.js后要返回到list.js 页面，list.js 页面的组件怎么判断原来的分页(或数据)状态,

在以前的组件可以这样做：

```javascript

shouldComponentUpdate(nextProps, nextState) {
    if(this.props.nowPlayingList !== nextProps.nowPlayingList || this.props.comingSoonList !== nextProps.comingSoonList || this.state.type !== nextState.type){
      return true;
    }else{
      return false;
    }
  }

 但是在dva架构下，这样功能的函数组件怎样写？

**Comment by szwork2013** [comment]
主要的问题是在model 里做了pathname 监听，页面返回后会自动按监听的功能执行了,与组件里的功能似乎矛盾了，model 里 subscription可以读取nextProps, nextState这些信息吗？

**Comment by sorrycc** [comment]
model 和 view 是解绑的，所以 subscription 也不会读 nextProps 等属性。

**Comment by sorrycc** [comment]
`shouldComponentUpdate` 之前怎么写就怎么写，和是否用 dva 没啥相关性。

**Comment by sven0726** [comment]
我现在也把一些无状态的组件改成了有状态的组件，继承Component来暴露生命周期。   除此问题之外，如果要做Modal里的组件动态添加，感觉使用无状态的也是很难受的。 不知道@sorrycc  dva这边有好的方案吗

**Comment by noyobo** [comment]
```js
import React, { Component, Fragment } from 'react';
import moment from 'moment';
import { Prompt } from 'dva/router';

class Detail extends Component {
  componentDidMount() {
    window.onbeforeunload = () => true;
  }

  componentWillUnmount() {
    window.onbeforeunload = null;
  }

  render() {
    return (
      <Fragment>
        <Prompt message={(location) => `Are you sue you want to go to ${location.pathname}?`} />
        <div>{moment().format('YYYY-MM-DD HH:mm:ss')}</div>
      </Fragment>
    );
  }
}

export default Detail;
```
