### ISSUE TITLE
运行在服务器上，无限刷新？

### ISSUE THREAD

**Issue by forever4313** [dvajs/dva#608]
我将所有的文件，都上传到服务器，用来给其他用户展示，由于是开发环境，所有数据均为mock，
但是，我在访问的时候，发现会无限循环的刷新页面。
是我做错了什么吗？求助~~~~

**Comment by sorrycc** [comment]
npm run build 之后上传的?

**Comment by forever4313** [comment]
不是的，我直接上传源码，然后直接运行了cnpm start
其他地方用ip:8989访问，然后无限刷新，不太明白是为什么，求教~，如何使用mockjs 来mock数据的同时，让所有都能正常浏览demo呢，

**Comment by sorrycc** [comment]
本地访问不会无限刷新?

**Comment by sorrycc** [comment]
无线刷新可能和 HMR 有关，你可以排查下。

**Comment by forever4313** [comment]
@sorrycc 本地访问不会，本地运行的时候，只有在程序保存时才会刷新

**Comment by sorrycc** [comment]
看端口，应该是用的 dora ? 不要加载 dora-plugin-webpack-hmr 插件试试。

**Comment by forever4313** [comment]
我记得刚开始用dva的时候好像还是1.0.0的样子。
这是package.json

{
  "private": true,
  "entry": {
    "index": "./src/index.js"
  },
  "dependencies": {
    "antd": "^2.7.1",
    "babel-plugin-import": "^1.0.1",
    "babel-preset-es2015": "^6.16.0",
    "components": "^0.1.0",
    "dva": "^1.0.0",
    "dva-loading": "^0.2.0",
    "echarts-for-react": "^1.1.6",
    "jquery": "^3.1.1",
    "moment": "^2.17.1",
    "qs": "^6.2.1",
    "react": "^15.1.0",
    "react-dom": "^15.1.0"
  },
  "devDependencies": {
    "atool-build": "^0.7.6",
    "atool-test-mocha": "^0.1.5",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-dva-hmr": "^0.1.0",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-runtime": "^6.9.2",
    "dora": "0.3.x",
    "dora-plugin-proxy": "^0.7.0",
    "dora-plugin-webpack": "0.6.x",
    "dora-plugin-webpack-hmr": "^0.1.0",
    "expect": "^1.20.2",
    "mockjs": "^1.0.1-beta3",
    "redbox-react": "^1.2.10"
  },
  "scripts": {
    "start": "dora --plugins \"proxy,webpack,webpack-hmr\"",
    "build": "atool-build",
    "test": "atool-test-mocha ./src/**/*-test.js"
  }
}


去掉dora-plugin-webpack-hmr  这个插件也依旧无限刷新呢。

**Comment by sorrycc** [comment]
```diff
+ "start": "dora --plugins "proxy,webpack,webpack-hmr"",
- "start": "dora --plugins "proxy,webpack"",
```

这样去的?

**Comment by forever4313** [comment]
太感谢了，搞定了～～～我删错地方了删除成Dependencies了，　刚入门，问的问题会比较低级，感谢大神~~~
