### ISSUE TITLE
图片src的cdn地址被转换成了hash

### ISSUE THREAD

**Issue by linyongping** [dvajs/dva#609]
项目中有本地的图片，，类似` url('../assets/some.png' )`这种引用的图片在打包后可以正常使用，但是有一些图片的地址是 `<img src='http://cdn.net/some.jpg' /> ` 这种打包后地址会被替换成一个 xxxxxx.jpg ,但是线上的图片没有能在dist文件夹中找到。有没有一种方法可以让本地地址的图片打包，如果是cdn地址就不要做任何改变

**Comment by sorrycc** [comment]
我理解下，是在 React 组件里写的 `<img src='http://cdn.net/some.jpg' />` 被转了路径?

**Comment by linyongping** [comment]
是的

**Comment by sorrycc** [comment]
@pigcan 有空看下这个问题。

**Comment by pigcan** [comment]
cdn 地址按理来说不可能加上 hash 的.

可以提供案例么

**Comment by linyongping** [comment]
就是 这样的地址 `<img src = 'http://cdn.net/xxx.png' />`
变成打包后的地址 `<img src = 'xxxxxxxxxxx.png' />`

**Comment by sorrycc** [comment]
@linyongping 解决了?
