### ISSUE TITLE
请问有没有dva的react native开发的实例？

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#61]
目前做的应用网页版用的dva，感觉很赞，应用要求有app版，考虑用reactnative来开发，想用dva框架，因为rn不需要router，大部分都是导航，看到作者说dva支持reactnative，不知道是否有个简单的实例参考？

再为dva点赞！学习了很多！

**Comment by sorrycc** [comment]
```javascript
import dva from 'dva/mobile';
```

这个版本是没路由的，适合 h5 mobile 和 react-native 。例子：https://github.com/sorrycc/dva-example-react-native

**Comment by bjwulin** [comment]
谢谢 @sorrycc ，学习下。
