### ISSUE TITLE
关于跨域访问

### ISSUE THREAD

**Issue by chenghuama** [dvajs/dva#611]
今天被跨域的问题给折腾死了，看到好些人被折腾。如果是正式环境里要跨域访问，设置mode=cors，服务端在header里增加Access-Control-Allow相关的设置就好了，能百度出好多文档。

但我相信，不是大多数正式环境里是不想跨域访问，如果设置mode也会带来很多麻烦。而很多人都是在本机做测试的时候遇到这样的问题。研究了半天，终于发现，原因是roadhog作为proxy的时候，没有转发主机名，导致通过代理后的请求变成了跨域访问。
只要在配置代理的时候，把主机名加上，就不会存在问题了。
"proxy": {
    "/api": {
      "target": "http://cxxxxx.cn/",
      "headers":{
               "host":"cxxxxx.cn"
      }
    },
   
@sorrycc 本来dva用的很舒服，很也喜欢，但是每次dva升级，都会让人挺蛋疼的。

**Comment by sorrycc** [comment]
感谢反馈。roadhog 的 proxy 换成了 webpack-dev-server 的 proxy，和之前的方案完全不同，变化是比较大。

**Comment by HeSwift** [comment]
@chenghuama   我今天也碰见这样的问题了，使用了proxy，但是还是报跨域错误。请问还有其他的要配置嘛。
