### ISSUE TITLE
dva 1.2.1 with ant-design custom font path does not work.

### ISSUE THREAD

**Issue by qiutiaoming** [dvajs/dva#612]
![image](https://cloud.githubusercontent.com/assets/5118099/23067525/b8c6bd76-f55a-11e6-9cc6-2740c0b2a8c7.png)

![image](https://cloud.githubusercontent.com/assets/5118099/23067573/eb1028da-f55a-11e6-9c0b-84d4237d20eb.png)

我在设置ant.design的font路径的时候，网页直接打开不能显示图标，chrome下报图一的错误，不过，能够点开路径看到font(路径设置应该没有问题)，图二是我的配置。

dva-cli: verison 0.7

谢谢。

**Comment by sorrycc** [comment]
参考 [roadhog#117](https://github.com/sorrycc/roadhog/issues/117) 呢?

**Comment by qiutiaoming** [comment]
@sorrycc , I just download the font files, and let nginx to serve the files.But I still think it's a bug.
