### ISSUE TITLE
如何实现多页程序

### ISSUE THREAD

**Issue by alvin198761** [dvajs/dva#614]
有两个入口
index.html
login.html 
webpack 增加 ：
 webpackConfig.entry = {
    index: "./src/index.js",
    login: "./src/login.js"
  }
如果只用其中一个来编译，都是好的
两个一起编译，样式就没有了，怎么破

**Comment by sorrycc** [comment]
可能需要在 html 中额外引入 `common.css` （多页面时被提取成公用的了）。
