### ISSUE TITLE
是否有推荐的富文本编辑器组件库？

### ISSUE THREAD

**Issue by maccyluo** [dvajs/dva#619]
项目中创建商品页面需要使用富文本编辑器录入商品详情信息。请教各位大神DVA中是否有推荐的富文本编辑器组件库？antd是否有现成组件可以使用？多谢支持！

**Comment by afc163** [comment]
可以关注下这里：https://github.com/ant-design/ant-design/issues/1083 。回复里有一些业界编辑器的推荐。
