### ISSUE TITLE
有没有好的方法检测router改变

### ISSUE THREAD

**Issue by hightall** [dvajs/dva#620]
在切换router的时候，页面可以显示一个加载的状态，目前如果切换router的时候，加载的js比较大的话，会没有任何反应，用户会感觉点击没有任何反应。怎么可以添加检测router改变的listener，然后添加一个loading的状态。

**Comment by YueHui** [comment]
在跳转后的页面的订阅里面可以改吧

**Comment by hightall** [comment]
那个时候已经跳转到新的页面了，我想要的是在老的页面有一个loading的显示，提示用户现在正在加载新的页面的js，现在的状态是等待下载新页面的js的时候，页面没有任何提示，用户会以为点击没有任何作用。

**Comment by codering** [comment]
看看 https://github.com/dvajs/dva-loading 能否可行。

**Comment by hightall** [comment]
@codering 谢谢啦。现在可以了。再问一下，dva用的atool-build，具体要怎么优化js？可以更小？我现在没有压缩的时候3.11M，压缩后是949k，这个是我的截图。https://snag.gy/96WFXs.jpg，不知道还有没有好的优化方法，默认atool-build的webpack应该是打开了所有的优化插件的吧？

**Comment by codering** [comment]
这个只能多研究下webpack的配置了。
到感觉没压缩前有这么多大的js，肯定不合理。
