### ISSUE TITLE
dynamic load的例子无法访问

### ISSUE THREAD

**Issue by loveholly** [dvajs/dva#621]
`README.md` 里面提到的 dynamic load 无法访问，能否修正一下？

**Comment by yyyyy210** [comment]
同问

**Comment by sorrycc** [comment]
参考 https://github.com/dvajs/dva-example-user-dashboard，以及[这个 Commit ](https://github.com/dvajs/dva-example-user-dashboard/commit/df2a7a0e1e7295840cfd2032a677f5e69c968c8a)。
