### ISSUE TITLE
ant-design-mobile升级到1.0.0版本后,iconfont改为了svg,该怎么配置

### ISSUE THREAD

**Issue by yxl2628** [dvajs/dva#622]
大版本升级到1.0.0后,图标不再使用iconfont了,改为了使用svg了,然后官网上提供了webpack的配置方式,但是我用了dva,而且感觉dva很好用,不过不会配置,求大神帮忙配置一下
https://mobile.ant.design/components/icon/

**Comment by afc163** [comment]
https://mobile.ant.design/docs/react/practical-projects 这个例子要根据 1.0.0 重新写过。

**Comment by warmhug** [comment]
@yxl2628 先参考这里 https://github.com/ant-design/antd-mobile-samples/tree/master/web-dvajs

**Comment by sorrycc** [comment]
等这个 [PR](https://github.com/sorrycc/roadhog/pull/144) 吧。

**Comment by paranoidjk** [comment]
@yxl2628

 roadhog `0.6.0-beta1` 已经添加API `svgSpriteLoaderDirs`,  [文档链接](https://github.com/sorrycc/roadhog#svgspriteloaderdirs)

对应 antd-mobile 的文档也已经更新 https://mobile.ant.design/components/icon

**Comment by paranoidjk** [comment]
@sorrycc dva 方便给我加个权限吗？ 可以帮忙处理这类的 issue ：）

**Comment by afc163** [comment]
上手文档和项目实战还是要更新一下，放在 icon 里没法发现。

**Comment by paranoidjk** [comment]
@afc163 ok, 我check下

**Comment by sorrycc** [comment]
@paranoidjk 👍，已邀请。
