### ISSUE TITLE
能简单跟我们讲讲dva是如何封装的么

### ISSUE THREAD

**Issue by Slngle** [dvajs/dva#623]
最近在看源码有点晕呼呼的，想让给讲讲思路 。谢谢~

**Comment by xiandongw** [comment]
co-ask

**Comment by xiandongw** [comment]
There is simplify fork version of dva.  It will help you to understand the concept. But reading the dva source code is not that hard.

**Comment by xufei** [comment]
这个我来写个详解吧。
