### ISSUE TITLE
如何支持webpack的配置？ 比如scss等；看了半天没明白

### ISSUE THREAD

**Issue by 18559909452** [dvajs/dva#624]
你好；根目录都没有webpack.config配置；不知道怎么去处理打包构建的scss、hash等  
在线等，谢谢

**Comment by yxl2628** [comment]
同问同问,用dva-cli生成出来的目录文件结构,根本没有webpack.config,然后ant-design上的文档全都是让配置webpack,我都晕菜了

**Comment by xufei** [comment]
也可以手动加的，比如这个里：https://github.com/dvajs/dva-hackernews

**Comment by sorrycc** [comment]
可以写 webpack.config.js 的配置，但不推荐，详见 [roadhog#配置](https://github.com/sorrycc/roadhog#配置)。
