### ISSUE TITLE
antd-admin not able to view the jsx in chrome developer console

### ISSUE THREAD

**Issue by cronusti** [dvajs/dva#626]
All the js under webpack is the generated js instead of jsx when debug with chrome developer tool.

It works after modify devtool of webpack.config.js from
webpackConfig.devtool = '#eval'
to
webpackConfig.devtool = 'source-map'

Should it be source-map?

**Comment by sorrycc** [comment]
You can use `source-map`, and it's a problem of antd-admin.

**Comment by 102010cncger** [comment]
package.json
"lint": "eslint --ext .js,.jsx src test",

all config

{
  "private": true,
  "scripts": {
    "start": "roadhog server --no-open",
    "build": "roadhog build",
    "lint": "eslint --ext .js,.jsx src test",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "antd": "^2.7.3",
    "babel-runtime": "^6.9.2",
    "dva": "^1.2.1",
    "dva-loading": "^0.2.0",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",

    "@types/react": "^15.0.2",
    "@types/react-dom": "^0.14.21",
    "@types/react-router": "^2.0.46",

    "classnames": "^2.2.5",
    "js-cookie": "^2.1.3",
    "qs": "^6.2.0",
    "react-countup": "^1.3.0",
    "recharts": "^0.19.0",

    "superagent": "2.3.0",
    "react-draft-wysiwyg": "^1.8.1",
    "react-helmet": "^5.0.0",
    "draftjs-to-markdown": "^0.4.0",
    "lodash": "^4.17.4"

  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "babel-plugin-dva-hmr": "^0.2.1",
    "babel-plugin-import": "^1.1.0",
    "babel-plugin-transform-runtime": "^6.9.0",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "expect": "^1.20.2",
    "husky": "^0.12.0",
    "redbox-react": "^1.3.2",
    "roadhog": "^0.5.0",

    "atool-build": "^0.7.6",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-runtime": "^6.9.2",
    "dora": "^0.4.3",
    "dora-plugin-browser-history": "^0.2.0",
    "dora-plugin-proxy": "^0.8.5",
    "dora-plugin-webpack": "^0.8.1",
    "dora-plugin-webpack-hmr": "^0.2.1",

    "glob": "^7.0.5",
    "mockjs": "^1.0.1-beta3",
    "rc-tween-one": "^1.0.0",
    "robe-ajax": "^1.0.0",
    "watchjs": "^0.0.0",

    "typescript": "~2.2.1",
    "typescript-babel-jest": "^0.1.5",

    "babel-core": "^6.17.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "css-loader": "^0.25.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "ts-loader": "^0.9.1",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.16.2",

    "draftjs-to-html": "^0.7.0",
    "axios": "^0.15.3",
    "babel-polyfill": "^6.23.0"
  },
  "theme": "./src/theme.js",
  "standard": {
    "parser": "babel-eslint",
    "globals": [
      "location",
      "localStorage"
    ]
  }
}
