### ISSUE TITLE
使用的时候遇到一个问题，命名空间不同内容同样的models一个能用一个用不了

### ISSUE THREAD

**Issue by files3** [dvajs/dva#629]
dva版本是1.1.0的
比如我的里面models有两个文件，一个是首页的，一个商品详情的
命名空间肯定是不一样的，其他都写成一样的了，
首页的models是能用的
商品详情页使用的时候老报如下图问题：
<img width="1272" alt="wx20170222-212136 2x" src="https://cloud.githubusercontent.com/assets/15240870/23213901/b8cb159c-f947-11e6-82ac-f9bf053a549e.png">

为了找是什么问题，我把routes.js文件里models改成和首页一样结果就能用，感谢帮忙解答
<img width="625" alt="wx20170222-213408 2x" src="https://cloud.githubusercontent.com/assets/15240870/23213912/c379a120-f947-11e6-9c75-78e790bf4922.png">

补充：我是dva new的项目，然后下载react-weui，准备做移动端的项目

**Comment by codering** [comment]
同学，错误信息已经很清楚了，ArDesc.jsx第九行，断点调试一下出现undefine的原因就可以解决了。

**Comment by files3** [comment]
@codering 恩好的，我调试一下吧，虽然是第9行，可是我把名字啥的都换成indexpage就可以用models
