### ISSUE TITLE
link本地 css问题

### ISSUE THREAD

**Issue by files3** [dvajs/dva#630]
首先项目里用到了swiper.min.css，现在是用的cdn的方式，但是没有网络的情况下加载不出来样式就会有问题，所以想下载到本地使用，但是不管是在index.html页面link，还是在less文件里@import都不管用，想问下是因为dva需要配置哪里的问题吗？

**Comment by codering** [comment]
试试在js里import, 比如index.js里

```js
import 'swiper.min.css'
…
```

还有种方式就是建个public目录，与src平级，把swiper.min.css放在public目录，然后在index.html里link, 试试看

**Comment by files3** [comment]
@codering 这两种都不行，最后我把文件移到node_modules里倒是管用了，不过有一点不明白的是部署到线上之后node_modules这块是怎么办的呢？

**Comment by sorrycc** [comment]
不需要打包的文件可以放到 [public 目录](https://github.com/sorrycc/roadhog#使用-public-目录)，public 目录不会做打包，然后在 html 文件里引用他。

**Comment by joahCN** [comment]
有遇到类似的问题，在component js中import css文件不生效。
原因是css loader默认开启了css module功能，import的css中class name已经变了。简单粗暴的做法是在 .roadhog中加上 _**_disableCSSModules: true,_**_ 。禁用css module

**Comment by files3** [comment]
怪不得我加在node_module里面，再import就可以了

**Comment by JimShawn** [comment]
@sorrycc 我的dva版本是 "dva": "^2.1.0",css文件放在cdn或者另外一个域名是可以的，放在node_modules里面，然后在页面import也是可以的。
但是放在public文件下面，在页面link引入不起作用，在控制台显示的也是可以看见css文件，但是里面的内容是引入也得html文件，
如果在页面引入，import '../../../public/css/common.css'; 则会报：
./public/css/common.css
Module parse failed: Unexpected token (1:6)
You may need an appropriate loader to handle this file type.
| input::-ms-clear{display:none;}
| body{
|     background-color: #f7f7f7;
这个要怎么处理？

**Comment by bingoran** [comment]
在.webpackrc.js文件里边加上下面这个配置
//定义第三方直接用Script引入而不需要打包的类库
  "externals": {
    "swiper" : "Swiper",
  },
然后在使用的地方导入import Swiper from 'swiper' 就可以正常使用了
