### ISSUE TITLE
initialState 报错，使用 redux-persist也报错

### ISSUE THREAD

**Issue by zix2002** [dvajs/dva#631]
```
const app = dva({
  initialState: { count: 1 },
});
app.model({
  namespace: 'count',
  state: 0,
});
```
报错 

`Unexpected key "count" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "routing", "@@dva", "loading". Unexpected keys will be ignored.`

另外使用 redux-persist也报错

```
import { persistStore, autoRehydrate } from 'redux-persist';
const app = dva({
  extraEnhancers: [autoRehydrate()],
});
persistStore(app._store);
```
如下

`Uncaught TypeError: Cannot read property 'subscribe' of null`

**Comment by nihgwu** [comment]
persistStore 要放在 app.start()之后，或者在其他组件的生命周期里调用

**Comment by zix2002** [comment]
persistStore 要放在 app.start()之后了，没有报错但是 没有任何效果 @nihgwu ，能否提供一个例子？dva": "^1.2.1",

**Comment by sorrycc** [comment]
试了下 initialState 并不会抛错。

代码：

```js
import dva, { connect } from 'dva';
import { Router, Route } from 'dva/router';

// 1. Initialize
const app = dva({
  initialState: { count: 1 },
});

// 2. Model
app.model({
  namespace: 'count',
  state: 0,
});

// 3. View
const App = connect(({ count }) => ({
  count,
}))(function (props) {
  return (
    <div>
      <h2>{ props.count }</h2>
    </div>
  );
});

// 4. Router
app.router(({ history }) =>
  <Router history={history}>
    <Route path="/" component={App} />
  </Router>
);

// 5. Start
app.start('#mountNode');
```

示例：

![image](https://cloud.githubusercontent.com/assets/35128/23242558/62461cae-f9b4-11e6-9c73-5fe4da3ab996.png)
