### ISSUE TITLE
dva框架开发时用dora-plugin-proxy反向代理请求时sessionid每次都不一样

### ISSUE THREAD

**Issue by small752** [dvajs/dva#632]
现在用dva的框架，npm start 时用dora-plugin-proxy进行反向代理向指定的后台服务器请求数据。
问题是每次请求里的的sessionid都不一样，后台就拿不到之前的session。

咨询下大神如何设置请求里的seeeionid一致呢。

**Comment by small752** [comment]
seeeionid每次不一致是否是因为cookie没有保存。
后台返回的sessionId没有记录下来呢，  感觉有可能是记录到了dva创建的node服务器去了，没有传到浏览器端

**Comment by sorrycc** [comment]
不用 dora-plugin-proxy 时会有问题吗?

**Comment by small752** [comment]
我现在是参考dora-plugin-proxy里的自定义代理请求修改了下，手动在request的header里塞了cookie，解决了遇到的这个问题。

'use strict';
var http = require('http');

/**
 * 自定义mock代理的工具方法
 * dora-proxy 的自定义代理请求
 *
 * req: 请求对象
 * res: 响应对象
 * hostname： 代理到的目标服务器
 * port： 代理到的目标服务器端口
 * method: 请求方法类型 POST,GET...
 * cookie: 要自定义的cookie
 */
function mockRequestUtil(req, res, hostname, port, method, cookie) {
    res.set('Content-Type', 'application/json;charset=UTF-8');
    var buf = req.body; //dora-plugin-proxy对req、res进行了封装

    var options = {
            hostname: hostname,
            port: port,
            path: req.url,
            method: method,
            headers: Object.assign({},  req.headers, {
                    'host':hostname,
                    'Origin':hostname,
                    'referer':hostname,
                    'Content-Type': 'application/json;charset=UTF-8',
                    'cookie': cookie
            })
    };

    //新建一个http.request来负责与真正提供api服务数据的服务器通信
    var _req = http.request(options, function(_res){
            var data = "";
            _res.setEncoding('UTF-8');
            _res.on('data', function(chunk){//代理响应接受到服务器数据返回
                    data += chunk ;
            })
            .on('end', function(){//提供数据服务的数据接受完毕
                    res.end(data); // 由本地的响应实例来响应代理服务器接受到的数据内容
            })
    }).on('error', function(error){
            res.end(); //本地响应实例返回空内容
    });
    _req.write(buf); //由http.request生成的请求实例来完成请求真正的提供数据服务的服务器
    _req.end();
}
