### ISSUE TITLE
关于 Authentication 和 Authorization 的最佳实践

### ISSUE THREAD

**Issue by gzbigegg** [dvajs/dva#633]
能不能提供一些教程？谢谢。

**Comment by miaoyinjun** [comment]
这是我的代码，在请求头增加Authorization字段，内容放后台返回的token
` return Ajax.ajax({
    url: url,
    method: options.method,
    data: body,
    // processData:options.method=='get'?true:false,
    dataType: 'JSON',
    contentType: 'application/json',
    headers: {Authorization: Authorization},
  }).fail((data) => {
    // console.log("223");
    // console.log(data);
  })
    .done((data) => {
      checkData(data);
      return data
    })
}`
