### ISSUE TITLE
model中是否可以拿到reactRouter提供的URL内的参数信息？

### ISSUE THREAD

**Issue by xiaosansiji** [dvajs/dva#636]
我在URL中写了一个参数：`localhost:8000/#/customview/1`
因为用了reactRouter所以之前只要在路由中这样写
![image](https://cloud.githubusercontent.com/assets/7600149/23298669/86f3355e-fab9-11e6-9c72-d3650d9b6533.png)
在组件中就可以通过props.params.customViewId直接拿到对应的参数。
但是现在如果用model中的subscriptions，则只能拿到location后用正则或者其他方式直接处理pathname：
![image](https://cloud.githubusercontent.com/assets/7600149/23298798/fa33d49c-fab9-11e6-96cb-d64c566158ec.png)
看起来就有点龊，这里更好的处理方式是不是不用subscriptions？而是把对应的路由组件改为非stateless写法，在组件的componentDidMount方法内拿到props.params.customViewId再发起异步请求比较好？
还是说model内能有比较方便的方式拿到URL内的参数？
`

**Comment by paranoidjk** [comment]
https://github.com/dvajs/dva/issues/174#issuecomment-261773625

**Comment by xiaosansiji** [comment]
谢谢 @paranoidjk ，这里model确实不应该去直接处理下层组件里的数据，它应该是抽象的一层

**Comment by jnotnull** [comment]
初始化模型的时候，按理需要活动url参数的，这个涉及到模型的入口参数初始化问题，这个参数我不认为处于下层，更应该处于最上层。
其实history.listen中有这些信息，只是dva的例子中从来没有这样写过，不知道是不是故意为之，但是我认为这个获得URL信息的口子应该给出来，使用split不也就是这个目的么 为了取到url数据。
`subscriptions: {
    setup({ dispatch, history}) {
      history.listen((url, state) => {
        if (pathToRegexp('/static/room/ctrlmemberdetail').test(url.pathname)) {
          alert(url.query.id);
        }
      });
    }
  },`

**Comment by TonyChanNJU** [comment]
附议，我也认为应该提供更好的获取参数的方式
