### ISSUE TITLE
router路由能配置拦截器吗？

### ISSUE THREAD

**Issue by zhangyezeng** [dvajs/dva#637]
请教前辈，我想实现一个通过权限去拦截路由的功能
当使用dispatch(routerRedux.push('/someting'));或点击菜单进行路由跳转的时候如果当前用户没有权限，可以阻止本次跳转吗？

**Comment by paranoidjk** [comment]
- A方案，你完全可以在`dispatch`之前做权限判断
- B方案，你也可以利用 react-router `onEnter` 这类的hook来做权限判断和重定向

**Comment by zhangyezeng** [comment]
谢谢，问题已经解决

**Comment by bowencool** [comment]
v4已弃用...

**Comment by lovemegowin** [comment]
@paranoidjk 如果是大面积的判断的话A方案不是很合适把

@zhangyezeng 我也遇到这个问题了 您是怎么解决的 方便告知一下不

**Comment by imaxing** [comment]
v4...已弃用， 期待更好的解决方案

**Comment by AlwaysOnTheWay** [comment]
@zhangyezeng 楼主是怎么解决的？dva1.2支持吗？
