### ISSUE TITLE
IE EDGE/10/9均不能运行

### ISSUE THREAD

**Issue by kifever** [dvajs/dva#638]
我用官方的例子，在IE下不能运行，请问是完全不兼容任何IE？

**Comment by longzhaobi** [comment]
能运行的！

**Comment by paranoidjk** [comment]
不能运行是指？请给出具体的报错信息，比如 console 的报错日志，不然很难帮你定位问题

> 强烈推荐阅读 [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)、[《如何向开源社区提问题》](https://github.com/seajs/seajs/issues/545) 和 [《如何有效地报告 Bug》](http://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)，更好的问题更容易获得帮助。

**Comment by zjafei** [comment]
我这里EDGE报 promise的问题
