### ISSUE TITLE
用dva1.0生成的项目在调试的时候没有源代码

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#64]
用老版本时，用chrome开发者工具时可以看到webpack://下面有src目录，用1.0时没有，就不知道如何进行断点调试了。

**Comment by sorrycc** [comment]
打开 webpack.config.js 看看有这行没，https://github.com/dvajs/dva-cli/blob/master/boilerplates/app/webpack.config.js#L9

**Comment by bjwulin** [comment]
有的，我是用dva init生成的项目。但是dav0.0.12生成的没问题。

现在生成的：
  // Support hmr
  if (env === 'development') {
    webpackConfig.devtool = '#eval';
    webpackConfig.babel.plugins.push(['dva-hmr', {
      entries: [
        './src/index.js',
      ],
    }]);
  } else {
    webpackConfig.babel.plugins.push('dev-expression');
  }

不过1.0的dva比上个版本的hmr要好太多了，windows环境下，基本上都能hot load，赞一个。

**Comment by sorrycc** [comment]
换成其他的 sourcemap 生成方式试试，http://webpack.github.io/docs/configuration.html#devtool

**Comment by bjwulin** [comment]
换成这个：webpackConfig.devtool = 'source-map';就好了，谢谢@sorrycc

**Comment by ohmyauthentic** [comment]
@sorrycc 你好，我build的时候提示unkown plugin dev-expression，是不是缺啥了
