### ISSUE TITLE
routerRedux.push 跳转路由时如何传递参数？

### ISSUE THREAD

**Issue by HongXiaoMing** [dvajs/dva#640]
yield put(routerRedux.push( {
        pathname: '/addressEdit',
        data: {item：2},
      }));

页面怎么取到data的值？

**Comment by paranoidjk** [comment]
- `routerRedux`实际上是`react-router-redux`的一个alias，你看官方文档就可以了https://github.com/reactjs/react-router-redux#pushlocation-replacelocation-gonumber-goback-goforward

- push的参数是一个`location`, 并没有data属性，你可以通过query传递参数
