### ISSUE TITLE
Failed to parse mock config. 

### ISSUE THREAD

**Issue by forrest23** [dvajs/dva#642]
mac    dva 0.7.8     node v6.9.5

用dva new user-dashboard 命令创建一个新项目，然后npm start 就报

Failed to parse mock config.

Error in Maximum call stack size exceeded (While processing preset
RangeError: "/Users/fgmh/Project/React/PalmHospitalAdmin/node_modules/roadhog/node_modules/babel-preset-es2015/lib/index.js")

这是什么原因

**Comment by forrest23** [comment]
自己已解决，但是解决的莫名其妙。
我把.roadhogrc 文件改成了js格式的文件，.roadhogrc.js，就好了
文件内容为

`export default {
  entry: "src/index.js",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "style": "css", "libraryName": "antd", "libraryDirectory": "lib" }]
      ],
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "style": "css", "libraryName": "antd", "libraryDirectory": "lib" }]
      ],
    }
  }
}`

**Comment by sorrycc** [comment]
之前的 .roadhogrc 能贴出来看下吗? 我排查下原因。

**Comment by lidianhao123** [comment]
MAC: X EI Caption 10.11.6
dva: 1.2.1
nodejs: 6.9.2
npm : 3.10.9
npm start 

```shell
Starting the development server...

Failed to parse mock config.

Error in Maximum call stack size exceeded (While processing preset
RangeError: "/Users/demo/admin/node_modules/roadhog/node_modules/babel-preset-es2015/lib/index.js")
```

.roadhogrc 文件如下
```js
{
  "entry": "src/index.js",
  "disableCSSModules": true,
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }],
        ["module-resolver", {
          "root": ["./src"],
          "alias": {
            "style": "assets/style",
            "images": "assets/images"
          }
        }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }],
        ["module-resolver", {
          "root": ["./src"],
          "alias": {
            "style": "assets/style",
            "images": "assets/images"
          }
        }]
      ]
    }
  },
  "proxy": {
    "/api": {
      "target": "http://localhost:8888",
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    }
  }
}
```

**Comment by sorrycc** [comment]
@lidianhao123 `.roadhog.mock.js` 贴出来看下。

**Comment by lidianhao123** [comment]
@sorrycc 
.roadhog.mock.js 是默认的没有修改过
内容如下：
```js

export default {
};

```

**Comment by lidianhao123** [comment]
@sorrycc 这个问题解决了？

**Comment by toplan** [comment]
我也同样遇到这个问题。dva: 0.7.8 node: 6.10.2

**Comment by lidianhao123** [comment]
@toplan 过去太长时间忘记如何处理的，不过你的 dva 版本太老了，用 v1.2.1 以上吧

**Comment by lumeng689** [comment]
1.2.1 上也碰到了，把  .roadhog.mock.js这个文件删除就好了。
