### ISSUE TITLE
onError中如何能获取到state

### ISSUE THREAD

**Issue by jindada** [dvajs/dva#643]
onError中如何能获取到state

**Comment by sorrycc** [comment]
onError 里不能获取到 state，但他的第二个参数是 [dispatch](https://github.com/dvajs/dva/blob/bb98c16/src/createDva.js#L167)，可以触发 action，在 effect 里拿到 state 再做判断。

**Comment by nihgwu** [comment]
```js
onError() {
  console.log(app._store.getState())
}
```
