### ISSUE TITLE
可否介绍下是因为哪些功能导致不支持IE8？

### ISSUE THREAD

**Issue by enozr** [dvajs/dva#644]
可否介绍下dva是因为哪些功能不支持IE8？
有没有对应的降级方案？比如 es5 shim/sham 等？

**Comment by codering** [comment]
因为redux-saga不支持， fetch也不支持

**Comment by sorrycc** [comment]
新版的 react 和 react-router 也不支持了。

**Comment by miaozilong** [comment]
有哪个版本的dva支持IE8吗？
