### ISSUE TITLE
使用dva如何优雅的处理在渲染组件前需预先处理好props数据

### ISSUE THREAD

**Issue by ufohjl** [dvajs/dva#646]
比如route /user/update 渲染 UserUpdateForm component
这时需要想要预先异步加载好user数据， 然后再渲染<UserUpdateForm user={user}/>

请问下在dva中如何优雅处理这类情况？

**Comment by sorrycc** [comment]
这样不行么? 

1. 先加载数据
2. 通过 action 切换路由

**Comment by ufohjl** [comment]
@sorrycc 感谢回复。

事实上，这种方式尝试过了，但是会有一个问题，就是用户刷新当前地址，这个时候进入route时状态为空，页面渲染也为空。但是如果此时去监听history，就又回到了一开始提的那个问题...

**Comment by nikogu** [comment]
> 比如route /user/update 渲染 UserUpdateForm component
> 这时需要想要预先异步加载好user数据， 然后再渲染

@ufohjl 你的根本目的是想：1. 提高用户体验，让有数据的时候才展现出良好的页面；2. 还是为了性能（懒加载）

如果是：
1. 那么没必要预先加载，通过信号量判断更改样式即可；
2. 那么就是加载数据和页面展示分离异步就好，在合适的时机优先调用数据，然后进入路由再 reducer；

**Comment by ufohjl** [comment]
@nikogu 恩，最终采用的是你说的1、2结合的方式。想了想预先加载好数据，毕竟会造成阻塞，不利于用户体验。
