### ISSUE TITLE
按需加载的js如何跟cdn一起使用

### ISSUE THREAD

**Issue by Slngle** [dvajs/dva#647]
我们现在的做法是将build目录放到nginx静态目录下 如何能将js放到cdn呢？

**Comment by Slngle** [comment]
output: {
    path: "/home/proj/cdn/assets/[hash]",
    publicPath: "http://cdn.example.com/assets/[hash]/"
}

找到了

**Comment by ufohjl** [comment]
@Slngle 请问下你这边是如何配置nginx使得不论什么url都是访问index.html?
