### ISSUE TITLE
babel 的transform-decorators-legacy  插件不能够正常的使用

### ISSUE THREAD

**Issue by Dirmond** [dvajs/dva#648]
在项目中安装了babel-plugin-transform-decorators-legacy ，并且在.roadhogrc的extraBabelPlugins 里面配置了transform-decorators-legacy，编译js 文件报错.不正确的编译js 文件。请问该怎么解决

**Comment by sorrycc** [comment]
报错贴出来看下。

**Comment by wuzhuzhu** [comment]
` bash
Creating an optimized production build...
Failed to compile.

Module build failed: SyntaxError: Decorators are not officially supported yet in 6.x pending a proposal update.
However, if you need to use them you can install the legacy decorators transform with:

npm install babel-plugin-transform-decorators-legacy --save-dev

and add the following line to your .babelrc file:

{
  "plugins": ["transform-decorators-legacy"]
}

The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.
    

  10 | @translate('sample')
  11 | @connect(mapStateToProps)
> 12 | class Container extends React.Component {
     | ^
  13 |   render() {
  14 |     const { t } = this.props
  15 |     const msgs = {

`

**Comment by chezhe** [comment]
```
Creating an optimized production build...
Failed to compile.

Module build failed: SyntaxError: Decorators are not officially supported yet in 6.x pending a proposal update.
However, if you need to use them you can install the legacy decorators transform with:

npm install babel-plugin-transform-decorators-legacy --save-dev

and add the following line to your .babelrc file:

{
  "plugins": ["transform-decorators-legacy"]
}

The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.
    

   5 | 
   6 | @DragDropContext(HTML5Backend)
>  7 | class TagWrapper extends Component {
     | ^
   8 |   render() {
   9 |     const { heads } = this.props;
  10 |     return (

```

**Comment by amanoooooooooooooooo** [comment]
extraplugin  有env 和production 吧， 都加了吗
`{
  "entry": "src/index.js",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        "transform-decorators-legacy"
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        "transform-decorators-legacy"
      ]
    }
  }
}
`

**Comment by linsage** [comment]
@chezhe 我也遇到一样的问题，本地构建没问题，但是在服务器构建就有，请问你后面怎么解决的？

**Comment by 25juan** [comment]
他有两个配置，你检查一下生产模式的配置是不是配置上了这个插件的，我之前是只配置生产模式，没有配置开发模式
