### ISSUE TITLE
在做服务端渲染时，subscriptions中的内容实际是不需要执行的

### ISSUE THREAD

**Issue by strommmm** [dvajs/dva#649]
如题， 我在使用dva的时候，subscriptions中的函数主要是做监听或者加载初始化数据的作用。而在服务端渲染时，初始化数据是通过initialState传进去的，所以这部分代码是不需要执行的，反而会让服务器去做一些没意义的请求。请问能不能为服务端渲染简化dva的执行流程，谢谢~

**Comment by sorrycc** [comment]
可以通过环境变量判断是否服务端。

**Comment by strommmm** [comment]
@sorrycc 谢谢 ~ 我现在就是这样处理的。
不过对于服务端渲染来说，model里的effect执行大都是没有意义的，因为ssr的需求只是根据传入的initialState生成对应的DOM tree就够了。所以在想是否可以在app.start()({ renderProps }) 的时候传入isServer的参数，直接禁止effect的执行。

**Comment by nikogu** [comment]
@strommmm 服务端渲染是服务端，`effect` 是处理不纯（如异步）情况的，两者并没有什么关系，如果你的页面都只是展现（只用 initialState ）,你就不写 `effect` 就好了，也不用写 `subscriptions`

**Comment by strommmm** [comment]
@nikogu 谢谢回复 ~ 
如果只是内容展示的页面，确实不需要effect和subscription
但是一般服务端渲染都是部分渲染，主要目的是首屏速度和seo，比如一个文章页面，文章的内容是通过服务端渲染出来的，但是评论部分很可能是在客户端后续加载出来的，而这部分还是需要effect和subscription的
又因为需要同构开发，所以effect和subscription还是得写...所以我才希望在服务器端执行的时候可以禁用effect...
谢谢 ~

**Comment by sorrycc** [comment]
SSR 有不同层次的代码共用方式，按需求的不同会有仅视图层的、视图加路由层的、全部公用的（包含 Model 层）。

**Comment by cycgit** [comment]
我觉得应该让执行。 完全自动化去dispatch数据
