### ISSUE TITLE
dva的一些疑问

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#65]
1、dva用了redux，这样实际上所有的组件是不是都是stateless functions？容器组件也应该是stateless functions，只不过容器组件在redux的store里面的状态变化（简单判断是不是同一个实例）之后触发刷新？stateless functions无生命周期，无后台实例，这样是不是每次都重新生成，没有diff这个动作，是不是反而没有用到reactjs的vdom。

2、在dva里面展现树，编辑树节点，由于树节点要递归生成（我原来想采用parent.children.push(child)的方式，发现不可行），那么传入的数据就由很多层，对于state的数据一般不建议多层，因为更新困难，那么树这个数据应该怎么处理好一点呢？

3、我对redux还有点迷糊的就是，redux就一个store，整个应用一直运行，数据一直放在store里面，比如说，我的web有5个列表的功能，每个列表功能上拉加载了1000条，那么5000条数据一直存在store里面？这样对内存是不是占用较多？

谢谢@sorrycc的dva！

**Comment by sorrycc** [comment]
1. stateless function 不是必须的，可以用 React.createClass 或 class 的方式组织代码，也可以适当地使用 Component 的 state
2. Component 用什么写法和 vdom 没有关系的
3. 树遍历的 state 可以设计成扁平的，比如 `{ itemsById:{}, items:[] }`，items 里只存 id，然后根据 children 和 parentId 之类的进行遍历。可参考 https://github.com/dvajs/dva-hackernews/blob/2c3330b1c8ae728c94ebe1399b72486ad5a1a7a0/src/models/item/index.js#L27，这里的评论列表就是递归生成的
4. 5000 条是有点多，所以一般下拉加载在载到一定数据量的时候会有个跳转到下一页，不管是否用 redux 都会有这个问题。

**Comment by bjwulin** [comment]
@sorrycc ，我看网上有种说法，说应该定义stateless的组件，在shouldComponentUpdate是判断props是否变化来决定是否应该重新生成，而stateless function是每次都会被容器组件重新生成，不管它所接受的props是否发生变化。

redux的state是不是可以人为清除一些数据？发送一些action，因为在手机端，上拉加载太正常了，结果数据都在内存里面，有点不合适。

还有点不明白，stateless function按照官方说的，就不在vdom差异比较里面，因为没有后端实例，那么我觉得这个stateless function没有用到vdom？

**Comment by sorrycc** [comment]
1. `shouldComponentUpdate` 已经在 connect 时处理过了，组件层不需要再加，追求性能的话可以在 connect 时引入 [reselect](https://github.com/reactjs/reselect) 做缓存处理
1. state 可以根据需求只存部分数据，这个在 reducer 里处理就好了。不过不存内存里，以为着用户滚动回去的时候又要重发服务端请求了

**Comment by bjwulin** [comment]
谢谢sorrycc
