### ISSUE TITLE
dva框架下，前后端分离如何调试。

### ISSUE THREAD

**Issue by jingchenxu** [dvajs/dva#650]
目前前台采用dva，后端采用springMVC，虽然可以通过mock实现接口的模拟，但是还是需要集成后进行测试，后台在eclipse中启动，每次集成测试都要build后重启tomcat方能测试。

**Comment by strommmm** [comment]
roadhog中可以配置proxy呀

**Comment by nikogu** [comment]
> 但是还是需要集成后进行测试，后台在eclipse中启动，每次集成测试都要build后重启tomcat方能测试

集成测试跟 dva（前端） 的关系是？
