### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by zhouyingkai1** [dvajs/dva#655]
把打包的静态文件放上虚拟空间之后 报这个错误 是什么原因

**Comment by zhouyingkai1** [comment]
![image](https://cloud.githubusercontent.com/assets/19966486/23492150/bc0b76d8-ff3d-11e6-8711-3438ae914f23.png)
![Uploading image2.png…]()

**Comment by zhouyingkai1** [comment]
![image2](https://cloud.githubusercontent.com/assets/19966486/23492194/f27d2824-ff3d-11e6-9ab0-c1e41cc8aba8.png)

**Comment by liupeng110112** [comment]
重新打包下 ，我之前也遇到过 ，没改就好了

**Comment by zhouyingkai1** [comment]
@liupeng110112   是的，重新打包就好了，很纳闷。。。谢谢啦
