### ISSUE TITLE
dva 如何在外部修改model的值

### ISSUE THREAD

**Issue by tianez** [dvajs/dva#657]
比如说我在名为app的 model中定义了登陆状态true  表示登陆成功了
现在我自定义了get  post方法做了统一的请求错误处理
如果请求返回403状态，此时我如何修改登陆状态为false

**Comment by paranoidjk** [comment]
> model中定义了登陆状态true 表示登陆成功了

我理解你说的即是在 Model 中定义了 state

关于如何修改state，请仔细看文档和示例代码，dispatch action --> reducer

https://github.com/dvajs/dva/blob/master/docs/API_zh-CN.md#model

**Comment by tianez** [comment]
我自定义了get和post方法，对返回状态进行了统一处理，而不想在每个页面或者model中分别对每次请求都做错误处理，这有什么好的处理方式吗？

**Comment by paranoidjk** [comment]
统一的错误处理和你issue的标题有什么关系？你完全可以就在你的ajax层做统一的错误处理

**Comment by tianez** [comment]
服务器返回 403状态 未登陆或登陆超时，我想改变state中的登陆状态为未登录，让用户回到 登陆界面

**Comment by paranoidjk** [comment]
也可以简单粗暴，location.hash = '#/403' 或者 browserHistory.push('/403')
 https://react-guide.github.io/react-router-cn/docs/guides/advanced/NavigatingOutsideOfComponents.html

**Comment by paranoidjk** [comment]
改变state的唯一方法就是dispatch action

**Comment by tianez** [comment]
@paranoidjk thanks
