### ISSUE TITLE
开发时我想通过localhost:8000/dva访问项目,而不是localhost:8000访问项目,请问如何设置

### ISSUE THREAD

**Issue by 102010cncger** [dvajs/dva#661]
开发时我想通过localhost:8000/dva访问项目,而不是localhost:8000访问项目,请问如何设置,谢谢了

**Comment by ouzhou** [comment]
![image](https://cloud.githubusercontent.com/assets/7693866/23574373/b238d994-00b8-11e7-9aa8-24c3defe2cd1.png)
https://github.com/sorrycc/roadhog

**Comment by 102010cncger** [comment]
谢谢大神!

**Comment by sorrycc** [comment]
可以通过 publicPath 和 outputPath 的组合修改 js 文件的地址。
