### ISSUE TITLE
编译之后的代码在IE11 一下运行报错

### ISSUE THREAD

**Issue by Dirmond** [dvajs/dva#662]
在react 15.4 版本中，用dva 搭建的开发环境应该怎么解决项目中出现的这个bug。https://github.com/facebook/react/issues/8379 ，我尝试性的用babel-polyfill解决。但是由于dva 的底层封装机制。对配置文件.roadhogrc entry 的类型做了限制。导致不能够有效的解决的该问题。请问作者该怎么处理。

**Comment by monteshy** [comment]
遇到了同样的问题，请问如何解决的

**Comment by vipcxj** [comment]
同问，最后怎么搞定的？
