### ISSUE TITLE
.roadhogrc的publicPath修改的是什么？

### ISSUE THREAD

**Issue by yangbin1994** [dvajs/dva#663]
index.html的路径没有改变，但是js里生成了一个变量对应的值为publicPath，不知道为什么~~~~(>_<)~~~~

**Comment by sorrycc** [comment]
修改的是 js 里的一个变量，这个变量用来动态加载额外的 js、css 或者其他资源文件。详见 webpack.github.io/docs/configuration.html#publicPath
