### ISSUE TITLE
朋友们帮忙看下 给 headers 里面带参,这样写有问题吗?

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#666]
![1](https://cloud.githubusercontent.com/assets/1819457/23586740/9c66ea6a-01d6-11e7-9240-3242381e5735.png)

我向同事写的接口POST一条新数据,
经过一番测试同事反应是提交的时候没有申明 json导致接口那边无法录入. 
于是就找到了配置headers的方法,
结果出现了图片中的错误. 请朋友们帮忙看看,可有解决方案!

**Comment by sorrycc** [comment]
和服务端联调下吧，错误提示很明显了，服务端不允许这个 header，客户端却传了。
