### ISSUE TITLE
如何插入components，而且异步加载数据？

### ISSUE THREAD

**Issue by hehaibo** [dvajs/dva#667]
src/router/order.js
 
`<Col lg={8} md={24}>`
       ` <Card bordered={false} bodyStyle={{...bodyStyle.bodyStyle, padding: 0}}>`
        `  <OrderUser {...user} />`
      `  </Card>`
    `  </Col>`
比方说我 要增加一个 

` <Card bordered={false} bodyStyle={{...bodyStyle.bodyStyle, padding: 0}}>`
        `  <OrderFileDetail {orderId} />`
      `  </Card>`

而我 的这个OrderFileDetail 定义的是一个订单文件详情 的数据 不是查询进去的，而是传递一个参数比方说orderId，通过这个参数去取数据，在 OrderFileDetail components里面 如何加载数据？
请问这个如何实现？`

**Comment by hehaibo** [comment]
``

**Comment by sorrycc** [comment]
路由定义比如 `/orders/:orderId`，然后就能取到 orderId，根据 orderId 去查询，然后渲染?

**Comment by hehaibo** [comment]
路由定义比如 /orders/:orderId，然后就能取到 orderId，根据 orderId 去查询，然后渲染?
@sorrycc 是的，需要在components去加载数据数据？

**Comment by nihgwu** [comment]
这个有什么问题，你拿到了orderId然后dispatch一个fetchDetail的effect拿到detail，OrderDetail直接connect这个detail不就好了

**Comment by nihgwu** [comment]
@sorrycc 我一直觉得dva的issue功能被滥用了，大部分都是跟dva无关的基础问题或者逻辑实现问题，其中还有很多antd的问题，把这里变成了一个问答论坛，这对我们这些watcher不太好吧

建议还是加个 ISSUE_TEMPLATE 吧

**Comment by hehaibo** [comment]
@nihgwu 老兄，有没有什么例子

**Comment by hehaibo** [comment]
@sorrycc 我的问题 是 我有一个页面，有很多tab，但是我每个tab想异步加载，

**Comment by nihgwu** [comment]
磨刀不误砍柴工，这些都是很简单的 state 问题，跟 dva 无关

**Comment by hirohe** [comment]
@hehaibo 试试看我的练习？[antd-dva-admin](https://github.com/hirohe/antd-dva-admin)
