### ISSUE TITLE
为啥我的新建弹出框，在完成了第一次提交后，再次点开就没有赋初始值了

### ISSUE THREAD

**Issue by ldc4** [dvajs/dva#668]
无论是点取消还是提交。
总之第一次打开模态框能正常渲染，附上初始值。
不刷新，后面几次打开模态框，它就不赋初始值了。
请问，这个是怎么解决的？

**Comment by sorrycc** [comment]
参考 https://github.com/dvajs/dva-example-user-dashboard 这里的 modal 实现吧。

**Comment by longzhaobi** [comment]
你用的是antd吗？？
如果是的话，可以给表单设置初始值后，每次打开modal时使用
```
this.props.form.resetFields();  就可以初始化。
```

**Comment by ldc4** [comment]
@longzhaobi 恩，我后来查看到了。我很好奇为啥antd-admin那个项目没有使用resetFields就能行。
现在，我在考虑如何重置自定义的表单控件。。。

**Comment by longzhaobi** [comment]
@ldc4 官方那个教程估计是每次都重新创建一次。跟dva之前12步教程类似。
const ModalGen = () => <UserModal />

**Comment by ldc4** [comment]
@longzhaobi 是啊，重新渲染了。。
但是我的表单是分三步完成的。一点击下一步，前面的数据就没有了。。。
有什么好的方法重置自定义表单空间么

**Comment by grunmin** [comment]
form类组件是受控的, 你可以主动给他们赋值.
