### ISSUE TITLE
dva 中如何不通过reducer维护内部state

### ISSUE THREAD

**Issue by zhouzefei** [dvajs/dva#669]
dispatch 发起一个 action，如果是同步行为会直接通过 Reducers 改变 State ，如果是异步行为（副作用）会先触发 Effects 然后流向 Reducers 最终改变 State。

dva中貌似都到reducer，，如果我只是内部维护一个状态，例如一个标签的显示隐藏，我并不需要到reducer上，这种场景如何处理？？？

**Comment by nihgwu** [comment]
component 的 state 是干什么的。。。

**Comment by sorrycc** [comment]
要么存 model 的 state，要么存 component 的 state 。

**Comment by zhouzefei** [comment]
component 的 state 是根据原始的写法例如这种么：
![image](https://cloud.githubusercontent.com/assets/8566935/23594056/bb58fd5c-0251-11e7-8f1c-387d5a5c65e1.png)
如果是的话可以混用么？？？ @sorrycc

**Comment by sorrycc** [comment]
是的，可以混用。
