### ISSUE TITLE
'roadhog' 不是内部或外部命令,也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by fanerge** [dvajs/dva#672]
输入yarn add reqwest 然后运行就报错了，
'roadhog' 不是内部或外部命令,也不是可运行的程序 或批处理文件。

**Comment by sorrycc** [comment]
reqwest ? 

> 'roadhog' 不是内部或外部命令,也不是可运行的程序 或批处理文件。

找不到文件，通常是环境变量没配对吧。

**Comment by fanerge** [comment]
对的，就是reqwest。谢谢你百忙之中为我解答。

**Comment by sorrycc** [comment]
解决了? 没解决的话检查下环境变量，或者重新安装依赖吧。

**Comment by fanerge** [comment]
解决了，谢谢了哈
