### ISSUE TITLE
Given action "mainLayout/checkLink", reducer "mainLayout" returned undefined. To ignore an action, you must explicitly return the previous state.

### ISSUE THREAD

**Issue by Nothingexp** [dvajs/dva#673]
Given action "mainLayout/checkLink", reducer "mainLayout" returned undefined. To ignore an action, you must explicitly return the previous state.

这个是报的什么错，没看懂？

**Comment by sorrycc** [comment]
执行了一个 action，但 reducer 没有返回值?

**Comment by nihgwu** [comment]
这个肯定是自己代码写的有问题吧，提问题又不贴代码，reducer 必须返回一个 state，如果没有进一步补充我觉得可以关了，跟 dva 无关
