### ISSUE TITLE
总结解决Modal闪现和初始化值问题

### ISSUE THREAD

**Issue by miaoyinjun** [dvajs/dva#674]
参考
#3426  #349  #4165  #3426 
在显示modal的情况下，更改state的内容，modal会闪下
发现是因为Modal的visible属性放在state里，然后修改state的其他数据， 会闪现，总结下，解决方法在3
1.写法，不会出现闪现问题，但隐藏再显示modal的值不会被初始化
`return (
  <div className='content-inner'>
    <UserSearch {...userSearchProps} />
    <UserList {...userListProps} />
    <UserModal {...userModalProps} />
  </div>
)`
2.写法，解决了隐藏再显示modal的值会被初始化，但会闪现
`const UserModalGen = () =>
  <UserModal {...userModalProps} />

return (
  <div className='content-inner'>
    <UserSearch {...userSearchProps} />
    <UserList {...userListProps} />
    <UserModalGen/>
  </div>
)`
3.写法，同时解决闪现和modal初始化
const UserModalGen = () =>
  <UserModal {...userModalProps} />

return (
  <div className='content-inner'>
    <UserSearch {...userSearchProps} />
    <UserList {...userListProps} />
    {modalVisible ? <UserModal {...userModalProps} /> : null}
  </div>
)
4.如果因为其他原因不能用写法3，但只是像修改modal的按钮的loading状态可以在modal内部用this.state解决

**Comment by ldc4** [comment]
什么闪现？

**Comment by pmg1989** [comment]
可以新建一个modal的models，剥离一个单独的弹框模型，就解决闪屏问题了，多次异步请求也不会出现闪屏bug，可参见[dva-admin](https://github.com/pmg1989/dva-admin)
