### ISSUE TITLE
路由页面后不能滚动到新路由页面的顶部

### ISSUE THREAD

**Issue by Superman-wc** [dvajs/dva#676]
dva@1.1
antd@2.7.4

dora --plugins \"proxy,webpack,webpack-hmr\"

import {Link} from 'dva/router';

<Link to="">新的页面</Link>

当前页面滚到底部， 点击链接Link, 转到新页面的时候页面还是在底部的， 
正常情况应该是到达新路由页面的顶部

**Comment by Superman-wc** [comment]
使用browserHistory 依旧是同样的问题

**Comment by sorrycc** [comment]
`window.scrollTo(0, 0)` ?

**Comment by Superman-wc** [comment]
使用window,scrollTo(0,0)  也存在一个小问题 ，

 componentDidMount() {
    window.scrollTo(0, 0);
  }

跳转到新页面后滚动到底部， 浏览器后退 再前进 ，页面回到了顶部（理想状态是刚才的底部）

有没有更好的办法

**Comment by sorrycc** [comment]
在跳转之前执行 scrollTo ?

**Comment by sorrycc** [comment]
也可以试试：

```js
<Router onUpdate={() => window.scrollTo(0, 0)}>
        {routes}
</Router>
```

**Comment by Superman-wc** [comment]
谢谢

**Comment by huangzonggui** [comment]
同样遇到这个奇怪的问题。不知道是什么原因。跳转到新页面的时候，scrollY不为0。请问有没有正路的解决方法，而不是额外做一个动作去scroll
