### ISSUE TITLE
文档中《动态加载 Model 和路由：按需加载加快访问速度 (例子)》链接失效

### ISSUE THREAD

**Issue by michaelzx** [dvajs/dva#677]
显示404页面

**Comment by sorrycc** [comment]
文档地址贴下?

**Comment by michaelzx** [comment]
![image](https://cloud.githubusercontent.com/assets/1799421/23640497/1986c9ea-0329-11e7-8d6e-f10a03763e6c.png)

**Comment by nihgwu** [comment]
目前的model的动态加载有问题，所以例子被作者删了吧，参考 #533 
话说新版本什么时候上路 😃  @sorrycc

**Comment by sorrycc** [comment]
@nihgwu 等公司项目忙完，最近完全没时间投入在 dva 上。
