### ISSUE TITLE
编译打包之后的文件过大

### ISSUE THREAD

**Issue by Dirmond** [dvajs/dva#678]
作者，您好！
我现在正在书写一个SPA。由于页面比较多。所以路由组件我决定实现按需加载。这个是我路由的配置。
![q_gfxs um d7 nb m zy](https://cloud.githubusercontent.com/assets/14308183/23642919/5778ae20-0339-11e7-98a6-2809ef631dcf.png)
但是我发现这样打包出来的单个组件都是比较大的。一个路由组件接近１ＭＢ。请问该怎么处理。

**Comment by sorrycc** [comment]
用的 roadhog ? 

配上 [`multipage`](https://github.com/sorrycc/roadhog#multipage) 提取 common 文件试试会不会减少。然后可以通过 `roadhog --analyze` 分析下文件构成。

**Comment by Dirmond** [comment]
嗯用的roadhog！是不是我实现按需加载之后chunk出来的js文件重复打包了react，react-dom等一系列的三方资源。导致我打包出来的文件过大！

**Comment by Dirmond** [comment]
我分析了一下，就是重复打包了

**Comment by sorrycc** [comment]
把重复的东西通过 [externals](webpack.github.io/docs/configuration.html#externals) 或者其他方式提取出来吧。

**Comment by spiroo** [comment]
@Dirmond 重复打包是指？

**Comment by liuxingling** [comment]
@Dirmond 问题解决了吗

**Comment by Dirmond** [comment]
@sorrycc  作者能够提供提供一个demo吗？

**Comment by sorrycc** [comment]
理解下 webpack 的 externals，抱歉，项目忙，没时间提供 Demo 。
