### ISSUE TITLE
public 下面index.html 里面的资源引入问题

### ISSUE THREAD

**Issue by Dirmond** [dvajs/dva#679]
作者，您好!
请问在public 文件夹下的index.html 里面引入的css资源和js 资源可以通过.roadhogrc 这个文件来进行配置吗？这个涉及到文件编译之后的输出路径。
![d2zs 6rzrf1ad gutw n e](https://cloud.githubusercontent.com/assets/14308183/23643381/57352abc-033c-11e7-83ff-1092a27977c5.png)

**Comment by sorrycc** [comment]
public 文件夹下的会被 copy 到输出目录下，详见[文档](https://github.com/sorrycc/roadhog#使用-public-目录)，剩下的自由发挥吧。
