### ISSUE TITLE
[react-router] `props.history` and `context.history` are deprecated. Please use `context.router`

### ISSUE THREAD

**Issue by WhatAKitty** [dvajs/dva#68]
第一次获取的时候可以拿到router，但是不知道为什么，router.replace后，router这个变量就消失了。

**Comment by nikogu** [comment]
贴下具体代码吧

**Comment by WhatAKitty** [comment]
这个是router配置：
```
<Router history={ history }>
      <Route breadcrumbName="首页" path="/" >
        <IndexRedirect to="example" />
        <Route path="login" component={ LoginPage } />
        <Route component={ IndexPage } >
          <Route breadcrumbName="样例" path="example" component={ Example } />
        </Route>
      </Route>
    </Router>
```
第一次跳转，未认证，跳转到login页面，这个时候是存在router变量的：
```
const IndexPage = ({ oauth, dispatch, history, children }) => {
  if (!oauth.access_token) {
    history.replace('/login');
    return false;
  }
  ...
}
```
第二次跳转，是登录成功后，跳转到首页，这个时候，router变量消失，并且跳转成功后，也没有router变量。
```
const LoginPage = ({ login, oauth, dispatch, history }) => {
  if (oauth.access_token) {
    history.replace('/');
    return false;
  }
  ...
}
```

**Comment by WhatAKitty** [comment]
不小心关错了

**Comment by nikogu** [comment]
@WhatAKitty 

> `[react-router] `props.history` and `context.history` are deprecated. Please use `context.router`

这个提示还是说的比较清楚，你需要使用 `context`

具体可以参看：[upgrade-guides/v2.0.0](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#mixins-are-deprecated)

和 [router context配置](https://github.com/reactjs/react-router/issues/975#issuecomment-84463196)

**Comment by WhatAKitty** [comment]
@nikogu 传递过来的并没有router这个变量，在上下文中。

**Comment by nikogu** [comment]
@WhatAKitty 可以参考：http://reactjs.cn/react/docs/context.html

其实就是需要设置 `contextTypes `，在需要使用的的 `router` 相关的组件中

**Comment by WhatAKitty** [comment]
@nikogu dva为什么没有在上下文中自动加入router？既然已经加入了history，而且比较怪异的是第一次加载的时候，是的确有router这个变量的。

**Comment by nikogu** [comment]
@WhatAKitty 其实来说，react-router中的`router`不是每个项目必要的，只有你在项目中需要操作 history 的时候才引入，并且他是组件里面去设置 `contextTypes`，而 dva 是整体的应用架构，不关心你组件里面的具体逻辑，所以这部分需要自己添加。

还有就是，之前加入了history，后面访问不到，应该是 `react-router` 的使用问题，所以我们推荐采用最新的写法来跳转路由。

所以你这里的问题其实就是参考：[router context配置](https://github.com/reactjs/react-router/issues/975#issuecomment-84463196) 这个评论的写法应该就可以解决了。

**Comment by WhatAKitty** [comment]
@nikogu 哦哦，好的。还有一个问题是dva-cli构建的项目中使用了dora，但是不知道如何支持browser-history.

**Comment by nikogu** [comment]
@WhatAKitty 可以参看 https://github.com/dvajs/dva-snippets/blob/master/how-to-config-router.js

dora跟 `browserhistory` 没关系的，dora只是构建调试工具

**Comment by WhatAKitty** [comment]
@nikogu 我也是这么用的，然后发现这样使用了后，每次刷新会导致出现react-router的not found错误，然后查了下资料，是服务器需要支持rewrite，而dva-cli启动的服务，并没有支持这个。

**Comment by WhatAKitty** [comment]
@nikogu http://react-china.org/t/react-router-browserhistory/5191

**Comment by nikogu** [comment]
@WhatAKitty 哦，你说调试的时候是吧，应该可能需要配置一下，我看看

**Comment by WhatAKitty** [comment]
@nikogu 好的，谢谢

**Comment by WhatAKitty** [comment]
@nikogu 有找到吗？比较急，不好意思。

**Comment by nikogu** [comment]
@WhatAKitty 试试这个，https://github.com/dora-js/dora-plugin-browser-history

**Comment by WhatAKitty** [comment]
```
cjdeMacBook-Pro:react-dva-example cj$ npm install dora-plugin-browser-history --save-dev
/Users/cj/git/react-dva-example
├── UNMET PEER DEPENDENCY dora@0.3.3 -> /Users/cj/git/react-dva-example/node_modules/.0.3.3@dora
└─┬ dora-plugin-browser-history@0.2.0 
  └── connect-history-api-fallback@1.2.0 

npm WARN dora-plugin-browser-history@0.2.0 requires a peer of dora@0.4.x but none was installed.

```
安装的时候提示的，而且"start": "dora --plugins \"proxy,webpack,webpack-hmr,browser-history\"",
然后启动npm start，仍旧没有作用

**Comment by WhatAKitty** [comment]
@nikogu 重新安装了下：
```
cjdeMacBook-Pro:react-dva-example cj$ npm install dora-plugin-browser-history@0.1.2 --save-dev
/Users/cj/git/react-dva-example
└─┬ dora-plugin-browser-history@0.1.2 
  └── connect-history-api-fallback@1.2.0
```

然后更改了start为：`"start": "dora --plugins \"browser-history,proxy,webpack,webpack-hmr\"",`这样更改后，正常启动，rewrites生效。

**Comment by nikogu** [comment]
👍 好的
