### ISSUE TITLE
关于分页total的处理

### ISSUE THREAD

**Issue by sz30313484** [dvajs/dva#681]
user-dashboard中对total是通过headers['x-total-count']实现的，我想改接口格式为{total:10,rows:[]}，然后再解析，多次尝试均失败。请问，该如何正确解析？ 还是说，只能用headers这种方式？

**Comment by nihgwu** [comment]
什么叫多次尝试均失败？代码呢？我一直都是用你说的这种接口格式做的，再说了分页功能跟dva有什么关系？

**Comment by sz30313484** [comment]
接口数据：{"total":4,"rows":[{"key":1,"name":"Sarah","age":2,"address":"重庆市"},{"key":2,"name":"Thomas","age":81,"address":"台中市"},{"key":3,"name":"Anthony","age":20,"address":"上海市"},{"key":4,"name":"Maria","age":23,"address":"宜春市"}]}
调用：
const {data} = yield call(aService.fetch, {page});
      console.log(data);
      yield put({
        type: 'save',
        payload: {
          data[“rows”],
          total: 3,
          page: parseInt(page, 10),
        },
      });

说明：对这个data，我怎么操作都不对，如data.rows,data["rows"]，正确的写法是什么？

**Comment by sz30313484** [comment]
我知道是什么原因了，const data = yield call(aService.fetch, {page})输出的是Object {data: Object}，我少写了一个对象，非常感谢！
