### ISSUE TITLE
css modules 样式不生效

### ISSUE THREAD

**Issue by Gitter110** [dvajs/dva#687]
import dva, { connect } from 'dva';
import { Router, Route } from 'dva/router';
import React from 'react';
import './index.html';
import styles from './index.less';

// 1. Initialize
const app = dva();

// 2. Model
// Remove the comment and define your model.
//app.model({});
app.model({
	namespace:'count',
	state:{
		record:0,
		current:0,
	},
	reducers:{
		add(state){
			const newCurrent=state.current+1;
			return {
				record:newCurrent>state.record?newCurrent:state.record,
				current:newCurrent,
			};
		},
		minus(state){
			return {
				...state,current:state.current-1
			};
		},
	},
	effects:{
		*add(action,{call,put}){
			yield call(delay,1000);
			yield put({type:'minus'});
		},
	},

});

const CountApp=({count,dispatch})=>{
	return (
		<div className={styles.normal}>
			<div className={styles.record}>Highest Record: {count.record}</div>
			<div className={styles.current}>{count.current}</div>
			<div className={styles.button}>
				<button onClick={()=>{dispatch({type:'count/add'});}}>+</button>
			</div>
		</div>
	);
};

function mapStateToProps(state){
	return {count:state.count};
}
const HomePage= connect(mapStateToProps)(CountApp);

// 3. Router
//const HomePage = () => <div>Hello Dva.</div>;

app.router(({ history }) =>
  <Router history={history}>
    <Route path="/" component={HomePage} />
  </Router>
);

// 4. Start
app.start('#root');

//---------
//Helpers
function delay(timeout){
	return new Promise(resolve=>{
		setTimeout(resolve,timeout);
	});
}

**Comment by guoxuequan** [comment]
.roadhogrc中"disableCSSModules": true 改成 false
