### ISSUE TITLE
 时间戳转换为中文时间的插件有哪些?

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#688]
请问朋友们是如何把时间戳转换为 用户体验 友好的?
用了那些插件?

**Comment by nihgwu** [comment]
这里不是StackOverflow

**Comment by forever4313** [comment]
moment

**Comment by monkindey** [comment]
可以尝试下 [date-fns](https://github.com/date-fns/date-fns), moment可能有点大了@forever4313 

可以参考 https://twitter.com/dan_abramov/status/805030922785525760

**Comment by forever4313** [comment]
@monkindey 
好的，谢谢，正好觉得moment有点大
