### ISSUE TITLE
roadhog已经升级到了0.6.0-beta1,ant-mobile升级到了1.0.4,但是icon不能用

### ISSUE THREAD

**Issue by yxl2628** [dvajs/dva#689]
roadhog已经升级到了0.6.0-beta1,ant-mobile升级到了1.0.4,也安装了svg-sprite-loader,也按照[文档](https://github.com/sorrycc/roadhog#svgspriteloaderdirs)中配置了,但是引用的时候
```
<Icon type={require('../assets/svg/clock-circle-o.svg')} />
<Icon type={require('./clock-circle-o.svg')} />   
<Icon type={require('clock-circle-o.svg')} />
```
这几种写法都不行,完全访问不到,是为什么,甚至连自带的样式也访问不到,求帮助~~~

**Comment by sorrycc** [comment]
@paranoidjk 帮忙看下。

**Comment by paranoidjk** [comment]
@yxl2628 

> 这几种写法都不行

参考官方的demo检查你的配置 https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog


> 自带样式访问不到

没有使用 babel-plugin-import 的话，你要自己引用样式

**Comment by yxl2628** [comment]
已经解决了,非常低级的bug,实在不好意思,版本升级的时候,忘记删除.roadhogrc文件了,导致.roadhogrc和.roadhogrc.js都存在,估计启动的时候还是读取的.roadhogrc的配置

**Comment by paranoidjk** [comment]
自己close
