### ISSUE TITLE
开始用dva + antd在项目中，首先对你们的付出表示感谢。

### ISSUE THREAD

**Issue by fanerge** [dvajs/dva#690]
开始用dva + antd在项目中，首先对你们的付出表示感谢，在dva中css module怎样使用media媒体查询的啊，我还没有找到答案。

**Comment by sorrycc** [comment]
Google 下 [css modules media query](https://www.google.com/search?{google:acceptedSuggestion}oq=css+module+media&{google:instantFieldTrialGroupParameter}sourceid=chrome&ie=UTF-8&q=css+module+media#newwindow=1&q=css+modules+media+query&*)
