### ISSUE TITLE
How to use react-handsontable in dva?

### ISSUE THREAD

**Issue by gavin9402** [dvajs/dva#691]
[react-handsontable](https://github.com/handsontable/react-handsontable) 是一个非常棒的表格控件。但是在使用dva集成react-handsontable的过程中，我遇到了一些困难，控制台总是报错 Cannot find module 'numbro' ，请教下，能否帮忙写个引用了[react-handsontable](https://github.com/handsontable/react-handsontable) 控件的demo？

**Comment by sorrycc** [comment]
这个和 dva 无关。numbro 是 react-handsontable 的依赖，应该是你依赖没安装好吧，删除 node_modules 重装试试。
