### ISSUE TITLE
分页组件的问题

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva#692]
后端小伙伴提供了api接口,url如下
`http://192.168.1.11/user?page=1&per-page=20`
其中 page  和 per-page 是动态参数可以调整的
当我访问后,表示我只请求接口中的第1页并且每页显示20条数据而已.

但我用ant的分页组件之后,感觉ant是把这个请求后的数据再次做分页处理了.
这说明一个问题: ant的分页组件认为一次请求即是请求所有.

那么问题是 我要后端提供可以获取数据库中所有数据的接口?
如果数据库中有千万条数据, 那么一次性从接口获取那么多数据不合理吧?

**Comment by nikogu** [comment]
https://ant.design/components/pagination-cn/

可以自定义组件属性实现你的需求
