### ISSUE TITLE
注册app.model 前进行数据注入

### ISSUE THREAD

**Issue by NumerHero** [dvajs/dva#693]
在app.start 和 app.model 注册前有一个后端返回的数据，我想将其传递到app模块，
这个数据只能在组件都未注册之前返回

![image](https://cloud.githubusercontent.com/assets/12696061/23734491/6ee0f798-04ba-11e7-9bfb-ea6b3bc4e584.png)

应该如何传递？

**Comment by ityao** [comment]
构造 initialState对象初始化model的数据
const app = dva({
  //初始化state
  initialState: init_state,
  onError(error) {
    message.destroy();
    message.error(error);
  },
});
