### ISSUE TITLE
后台返回302重定向 在dva中如何捕获?

### ISSUE THREAD

**Issue by kevin0137** [dvajs/dva#695]
当后台返回302重定向到登录页 页面并没有跳转 onError中也没有报错

![image](https://cloud.githubusercontent.com/assets/14232336/23741865/740b69f8-04e5-11e7-8fe3-f0e130c22b99.png)

请问上述情况应该如何处理?

**Comment by monkindey** [comment]
response报文头有加上Location么

参考 https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.3

> The temporary URI SHOULD be given by the Location field in the response

而且重定向的话浏览器会帮你执行的哦。

如果有说的不对请指正。

**Comment by kevin0137** [comment]
感谢你的帮助 报文头有Location 我也很奇怪浏览器没有自动跳转

![image](https://cloud.githubusercontent.com/assets/14232336/23742740/072afd90-04e9-11e7-81f6-892b5da8a000.png)

所以我在想是不是应该前端捕获302来做重定向 或者说有更好的方法

**Comment by monkindey** [comment]
来, 参考 http://stackoverflow.com/questions/3356838/how-does-http-302-work 这个。

302与301的某个区别就是302会保留之前的url，不会直接跳转的，你看你的getAuditedUserListByStatus下面有一个Login，就是浏览器帮你访问的。你可以把302改成301, 可能就可以了, 因为301会直接跳转到Login了

**Comment by kevin0137** [comment]
后台只能返回302..

**Comment by 3pointer** [comment]
我也遇到这个问题，请问一下 @kevin0137 后来有什么好的方式解决吗 ？

**Comment by kevin0137** [comment]
@3pointer 我是在`utils/fetch`中做处理的
```
function checkStatus(response) {
  // 判断302
  if( response.url === '/login'){
    return window.location.href = response.url;
  }
  if (response.status >= 200 && response.status < 300) {
    return response;
  }
  const error = new Error(response.statusText);
  error.response = response;
  throw error;
}
```

**Comment by 3pointer** [comment]
明白，多谢 @kevin0137

**Comment by maiboy** [comment]
@kevin0137  你好，有个问题：如果返回302，在fetch中是拿不到response的吧？
