### ISSUE TITLE
使用 browserHistory 二级路由 刷新找不到 js文件 

### ISSUE THREAD

**Issue by WangZi1997** [dvajs/dva#696]
解决了

**Comment by WangZi1997** [comment]
我看很多人都问过了这个问题 有回应已经解决的也  
使用了 useRouterHistory(createHashHistory)({queryKey: false})   但也不是使用的 
 所以使用    hashHistory.push() 来进行页面的跳转 但跳转后还是会 带K 不符合我们项目要求 #也不想看到  
求问

**Comment by nihgwu** [comment]
解决了就关掉啊

**Comment by trihtm** [comment]
@WangZi1997 how you solve this issue?

**Comment by WangZi1997** [comment]
@trihtm #598
