### ISSUE TITLE
注册 model 时为什么要用 require 而不是 import

### ISSUE THREAD

**Issue by hbrls** [dvajs/dva#698]
用 require 而不想写 default 的话就必须引入 babel-plugin-add-module-exports，而这个插件和 webpack2 有[冲突](https://ntucker.true.io/ntucker/webpack-2-uncaught-referenceerror-exports-is-not-defined/)。

项目整体都是用的 import，这里没有保持一致是有什么特殊的收益吗。

**Comment by nihgwu** [comment]
deferred import for dynamic load

**Comment by sorrycc** [comment]
看个人喜好吧，我在这里用 require 是不想注册一个 model 写两行代码。

**Comment by WhatAKitty** [comment]
目前直接app.model(import('../xxx'))会报`https://github.com/babel/babel/issues/2212`

**Comment by Can2Nya** [comment]
import要放在首行

**Comment by WhatAKitty** [comment]
@Can2Nya 使用的是动态引入。dva的app.model未对动态引入做兼容。
