### ISSUE TITLE
How can I use dotenv with Roadhog & dva?

### ISSUE THREAD

**Issue by trihtm** [dvajs/dva#699]
Apologize for writing English.

How can I use dotenv with Roadhog & dva? I've been searching but found nothing, anyone can help?

**Comment by K-walker** [comment]
https://ant.design/docs/react/practical-projects

**Comment by sorrycc** [comment]
Roadhog don't support dotenv, you can try to use [roadhog#env](https://github.com/sorrycc/roadhog#env).
