### ISSUE TITLE
如何在Route离开的时候清除某个model.namespace的state数据。

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#70]
我在开发中，很多最下层的route，离开后它的一些state数据其实没有用了，我希望在对应的route离开的时候清除这些state的数据，减少内存中的数据。

我看subscription是适合写route leave的地方，现在官方的例子有history.listen，我要怎么写才是监听onLeave？再有就是我怎么清除store里面某个model.namespace的数据？在注销的时候，我怎么清除整个redux的state？

**Comment by sorrycc** [comment]
> 我看subscription是适合写route leave的地方，现在官方的例子有history.listen，我要怎么写才是监听onLeave？

判断不是当前页面就可以吧。

> 再有就是我怎么清除store里面某个model.namespace的数据？

model 里需要有个类似 clear 的 reducer，然后 `dispatch({ type: `${model.namespace}/clear` })`

> 在注销的时候，我怎么清除整个redux的state？

可以调所有 model 的 clear，也可以写一个全局的 reducer enhancer 。

**Comment by bjwulin** [comment]
谢谢sorrycc

**Comment by WhatAKitty** [comment]
@sorrycc 

> 可以调所有 model 的 clear，也可以写一个全局的 reducer enhancer

请问下，这个如何创建? 是否有具体样例？

**Comment by sorrycc** [comment]
全局的 reducer enhancer ? 参考这个：https://github.com/dvajs/dva/blob/f13e7eb1d56a2bf3d55d79daee43b11a681529c7/test/reducers-test.js#L92-L108

**Comment by WhatAKitty** [comment]
@sorrycc 全局的reducer调用model，主要是这个不了解

**Comment by zikeng** [comment]
如何清空数据，具体有没有例子？

**Comment by flicker85** [comment]
>我看subscription是适合写route leave的地方，现在官方的例子有history.listen，我要怎么写才是监听onLeave？
>>判断不是当前页面就可以吧。
@sorrycc 
```js
subscriptions: {
    setup({ dispatch, history }) {
      return history.listen(({ pathname, query }) => {
        if (window.previousUrl == '/test' && pathname != '/test') {
           dispatch({ type: 'clearRedux'});
        }
        window.previousUrl = pathname;
      });
    },
  }
```
请问，我想保存前一个view的路由url，不想放在全局变量，把这个url保存在哪里比较好呢？

**Comment by trexguo** [comment]
我现在的想法是在页面跳转的时候，在 app.model(newModel)之前，先调用app.unmodel来清理旧的models。但是看了一下源码，unmodel()这个方法似乎没有把对应的namespace从store里清除？是否可以把这个功能加进去？

> model 里需要有个类似 clear 的 reducer，然后 dispatch({ type:${model.namespace}/clear})

这样只能清空该model的state里的属性，不能移除整个namespace吧？

另外，如果store中一直保留着之前页面的model不去清理，随着用户访问多个页面，state树会越来越大，对性能是否有影响？(目前已经遇到了个别页面下交互卡顿的情况，不知道是否相关)

请大神解答 @sorrycc  谢谢！

**Comment by jdfdcc** [comment]
怎么控制页面前进的时候清除数据,页面回退的时候保留数据呢?
