### ISSUE TITLE
请问基于dva的情况下,如何优雅的实现 延迟搜索呢? 

### ISSUE THREAD

**Issue by xjdata** [dvajs/dva#700]
选择控件,数据是动态加载的,这个时候如何实现例子中的300毫秒延迟呢?
https://ant.design/components/select-cn/

记得以前入门的例子计数器 是有延迟1秒的 但是刚才翻了一遍,发现没了.

请问基于dva的情况下,如何优雅的实现 延迟搜索呢? 

谢谢.

**Comment by nihgwu** [comment]
参看 redux-saga 的debounce，在generator里面加delay 然后 takeLatest
