### ISSUE TITLE
打包roadhog 设置问题

### ISSUE THREAD

**Issue by tianez** [dvajs/dva#701]
![image](https://cloud.githubusercontent.com/assets/6291579/23779169/c8958852-0579-11e7-9792-eecdfbcdf3bc.png)
发现即使这样设置了，打包出来的文件大小和 没有这样设置 打包出来的文件大小是一样的，也就是说这样设置没有起作用是无效的？

**Comment by sorrycc** [comment]
设置了 env 为 development 的配置，然后打包? 打包走的是 production env，所以无效吧。
