### ISSUE TITLE
 atool-build 如何开启reduxDevTools

### ISSUE THREAD

**Issue by zllc** [dvajs/dva#703]
目前使用atool-build打包时默认关闭了reduxDevTools，但是在一些场景下，需要用atool-build -w 调试，需要开启。有没有好的方法呢

**Comment by ishenli** [comment]
这个dva调试的加上`NODE_ENV=development` 应该就可以开启

**Comment by sorrycc** [comment]
生成环境是关闭 reduxDevTools 的。
