### ISSUE TITLE
"hash history needs a DOM"

### ISSUE THREAD

**Issue by bestotem** [dvajs/dva#706]
react-native 中用了dva

```
import dva, { connect } from 'dva/mobile';

const app = dva();

app.model(require('./models/HomePage'));

app.router(require('./router'));
```

ios模拟器上显示：
"hash history needs a DOM"

**Comment by nihgwu** [comment]
dva使用的react-router只适用于web开发，所以做react-native开发的时候要自己选其他的router，比如RNFR或者react-navigation

**Comment by horiuchie** [comment]
A workaround could be to replace default history with memory history by [createMemoryHistory](https://github.com/ReactTraining/history#usage).
Let me introduce [react-native-dva-starter-with-builtin-router](https://github.com/horiuchie/react-native-dva-starter-with-builtin-router) I created.
