### ISSUE TITLE
warning和invariant加上生产环境区分

### ISSUE THREAD

**Issue by monkindey** [dvajs/dva#707]
比如 ~https://github.com/dvajs/dva/blob/master/src/createDva.js#L471-L475~

warning和invariant在生产环境是可以尽量去掉的代码, 可以参考React

----

#### 2017.9.18 updated 

上面的链接已经失效了
https://github.com/dvajs/dva/blob/master/packages/dva/src/index.js#L48-L52

**Comment by sorrycc** [comment]
同意，可以在打包时处理。
