### ISSUE TITLE
AntDesign/dva在ipad上无法加载数据，在PC上和手机端都是正常的。求解决方案

### ISSUE THREAD

**Issue by softlvye123** [dvajs/dva#709]
@sorrycc   求解答

**Comment by sorrycc** [comment]
自己调试下吧。理论上没有兼容问题的，我们有不少 H5 项目都在用 dva 。

**Comment by softlvye123** [comment]
感谢回答，目前PC上以及手机端UC  QQ浏览器  iphone safari都是正常的，唯独在ipad上无法正常加载数据，网上也找了好久，没有准确的答案。貌似有fetch有关，请问你们有有AntDesign/dva做移动端pad适配的项目么 ？@sorrycc

**Comment by yautah** [comment]
加polyfill

**Comment by nalantianyi** [comment]
webpack打包的时候加入babel-polyfill试试呢
