### ISSUE TITLE
跳转到外部url的问题

### ISSUE THREAD

**Issue by xwy55555** [dvajs/dva#710]
类似下面代码中，需要跳转到外部的CAS登录页面时，这个跳转代码怎么写呀？请高手们指教一二，谢谢

> subscriptions: {
    --setup({ dispatch, history }) {
    --history.listen(location => {
    ----if (location.pathname === "/" || location.pathname === "/login") {
    ----if (location.query.userid === null || location.query.userid === undefined) {
    ------dispatch(routerRedux.push({
    --------pathname: 'http://cas.xxx.com/login.aspx?url=http://myhost:8000',
    ------}));
    ----} else {
    ------dispatch({
    --------type: 'initProjectInfo'
    ------});
    ----}
    --}
    --});
    -},
 },

**Comment by sorrycc** [comment]
跳转到路由以外的就用 `location.href = ''` 好了。

**Comment by xwy55555** [comment]
谢谢！@sorrycc

**Comment by xwy55555** [comment]
试了一下，用 `location.href= ''`不行，得用`window.location.href=''`，谢谢！

**Comment by zhouzefei** [comment]
@sorrycc  location.href = ''的这种形式好像会有问题。。。来回跳转重复刷新会显示空白页(查看body为空)，，，重新转到才可以，，，是否栈被清空了，，，

复现过程：
react-router中跳转外部链接a href='*****',点击浏览器返回，刷新，重复操作必现（页面为空白页）

设备：手机（pc不复现）

pc模式不复现，iphone手机下出现这种情况

**Comment by ankyo** [comment]
chrome 下 window.location.assign('')  我这边用了可以，只不过离开页面会提示 VM 错误，前进后退都正常的
