### ISSUE TITLE
model间的数据能相互引用么？

### ISSUE THREAD

**Issue by zyx4986** [dvajs/dva#713]

**Comment by xufei** [comment]
不要直接引用，你所谓的引用应该是指复用state吧，不同的model，其state是位于不同分支下的，如果要同步，需要借助action去做

**Comment by xiaoheicoder** [comment]
可以，const {  departments } = yield select((state) => state.patients)；

**Comment by zyx4986** [comment]
实际中是这个例子，antd-admin中登录后获取了一个key，本来把key放在sessionStorge，登录后主页页面需要使用这个key，但主页订阅数据源这个sessionStorge始终为空，需要刷新一遍才有值，于是想直接把key放在app的model中，然后在后面页面取这个model，这个做法是否合理呢？

**Comment by nihgwu** [comment]
也可以写个 service，随时调取，这种跟 ui 无关的没必要放到 state 里面

**Comment by forever4313** [comment]
@nihgwu  看到好多答案在说service，请问， 你们这里所说的service是什么，网络请求？？？？

**Comment by nihgwu** [comment]
``` js
// dataService.js
let data = 1;
export const getData = () => data;
export const setData = x => data = x;
```

**Comment by monkindey** [comment]
可以参考下 https://github.com/dvajs/dva-example-user-dashboard/blob/master/src/services/users.js 

应该说的就是网络请求层

@nihgwu  不知道我这样子理解是否正确呢

**Comment by nihgwu** [comment]
我都已经给出代码了啊，谁说service只能是网络请求了。。

**Comment by monkindey** [comment]
不好意思我误解了, 那是否可以添加到FAQ或者文档上? 我在文档上并没有找到相应的资料, 还是我错过了一些内容, 如果是, 请告诉我。

**Comment by nihgwu** [comment]
这个跟dva无关啊，就是代码逻辑的问题

On 14 Mar 2017, at 12:35, Kiho Cham <notifications@github.com<mailto:notifications@github.com>> wrote:


不好意思我误解了, 那是否可以添加到FAQ或者文档上? 我在文档上并没有找到相应的资料, 还是我错过了一些内容, 如果是, 请告诉我。
