### ISSUE TITLE
Getting Started教程的.less无法加载?

### ISSUE THREAD

**Issue by hjistc** [dvajs/dva#716]
被人安利了dva学习中，
跟着https://github.com/dvajs/dva/blob/master/docs/GettingStarted.md教程走的，
但是走到Add StyleSheet这一步的时候，.less无法加载，console.log(styles);出来为空？
复制了最下面的完成品code好像也不行？

**Comment by guoxuequan** [comment]
.roadhogrc中"disableCSSModules": true 改成 false
