### ISSUE TITLE
models的数据量比较大的时候dispatch会出现明显的延迟

### ISSUE THREAD

**Issue by zerozaki0752** [dvajs/dva#717]
请问当models数据量比较大时应该如何处理，以优化性能呢？

https://segmentfault.com/q/1010000008672014

**Comment by xufei** [comment]
区分一下你这个数据是不是都要渲染，如果不是，放一个service里，不要挂在props上，也不要拿去map导致层层都传，每层动态从其中取需要的部分展示

**Comment by zerozaki0752** [comment]
结构非常简单
model-->router-->component 只传递了一次 
router 加载了2个component 一个tabel 一个chechbox 
tabel中的list存在model中 
chechbox的state也存在model中
list数组内容比较多导致 chechbox发起dispatch到完成改变状态会比较慢
这种情况怎么处理会比较好？
拆分多个model？使用immutable？

**Comment by forever4313** [comment]
我也有同样的疑问。

@xufei 没有太明白，我现在是，所有的子组件依赖的内容，都是通过props传进去，现在也导致有卡顿现象，
求正确的解法。

> 放一个service里，不要挂在props上，也不要拿去map导致层层都传，每层动态从其中取需要的部分展示

这个是什么意思，service是指？不挂props 我还可以用mapStateToProps，你说，也不要map导致层层都传，那我应该怎么做比较合适呢。

**Comment by forever4313** [comment]
@zerozaki0752  你不分页吗？一页数据多大

**Comment by zerozaki0752** [comment]
@forever4313
分页啊
一页100条 每条数据内容多

**Comment by zerozaki0752** [comment]
@forever4313
你问题是一页组件多，我问题是组件少但是有一个数据量大的组件
2者看来都会导致出现卡顿

**Comment by forever4313** [comment]
@zerozaki0752  我有个页面是 有全选框的，不会卡顿，可能是我数据只有一页20条。

召唤神龙 @sorrycc

**Comment by SunXinFei** [comment]
> 

什么是service？
