### ISSUE TITLE
routerRedux.push/replace/... 没有起作用

### ISSUE THREAD

**Issue by WhatAKitty** [dvajs/dva#72]
@sorrycc @nikogu 
`import { routerRedux } from 'dva/router';`

导入routerRedux后，replace或者push都没有作用：

1. replace：
`routerRedux.replace('/login');`

2. push（我在effects中使用，用来设置url的查询参数，与dva样例的代码相同）
```
yield call(routerRedux.push, {
        query: payload,
      });
```

**Comment by sorrycc** [comment]
试试 `yield put(routerRedux.push('/path'))`，详见：https://github.com/dvajs/dva-knowledgemap#%E5%9F%BA%E4%BA%8E-action-%E8%BF%9B%E8%A1%8C%E9%A1%B5%E9%9D%A2%E8%B7%B3%E8%BD%AC

**Comment by WhatAKitty** [comment]
@sorrycc 如果只是`routerRedux.push({query: {'q': 'ddd'}})`是不行的，会自动跳转到/下，如果加上pathname:`routerRedux.push({pathname: '/config/manager', query: {'q': 'dddd'}})`会出现死循环。

另外，这个是样例代码
```
subscriptions: {
    setup({ dispatch, history }) {
      history.listen(location => {
        dispatch({
          type: 'setQuery',
          payload: location.query.q,
        });
      });
    },
  },
  effects: {
    setQuery: [function*({ payload }, { put, call }) {
      yield delay(300);
      yield call(routerRedux.push, {
        query: { q: payload || '' },
      });
      const { success, data } = yield fetch(`/api/search?q=${payload}`)
        .then(res => res.json());
      if (success) {
        yield put({
          type: 'setFriends',
          payload: data,
        });
      }
    }, { type: 'takeLatest' }],
  },
```
这个不会死循环吗？subscriptions在页面加载的时候，自动将query进行setQuery操作，但是在setQuery里面又有call push的操作，会跳转到新的页面，从而再次触发setQuery操作？

**Comment by codering** [comment]
要对location.path做判断的，不是你想要的路径就不要触发dispatch, 参https://github.com/dvajs/dva/blob/master/examples/user-dashboard/src/models/users.js

**Comment by WhatAKitty** [comment]
@codering 我根据这个做了判断了的
```
subscriptions: {
    setup({ dispatch, history }) {
      history.listen(location => {
        if (location.pathname === '/config/manager') {
          dispatch({
            type: 'setQuery',
            payload: location.query.q,
          });
        }
      });
    },
  },
```

**Comment by yjjqrqqq** [comment]
看来是挖坟了， 我的情况是： 地址栏的地址已经刷新了，但是UI没有任何响应，需要手动refresh才行。

**Comment by zjzjgxw** [comment]
@yjjqrqqq 我 也是这种情况，你解决了吗？

**Comment by grunmin** [comment]
地址栏刷新而UI无响应问题, 检查下index.js和router.js的写法

[index.js](https://github.com/dvajs/dva/commit/8480aac309b19364b13d1c88b435d310eec0d86a)
[router.js](https://github.com/dvajs/dva/blob/master/packages/dva-example-user-dashboard/src/router.js)

**Comment by Cody1988** [comment]
```javascript
// 1. Initialize
const app = dva({
  // history: browserHistory,
  onError(e, dispatch) {
    if (e && e.code === 403) {
      console.log('onError', e, routerRedux, app);
      if(不是登陆页面){
        跳转到登陆页面
      }
    }
  },
});

```

请问routerRedux如何获取当前pathname呢

**Comment by HengCC** [comment]
我也遇到了地址栏路由变化了 但是页面没有刷新

这是为什么呢?? 我的写法
```
appInstance._store.dispatch(routerRedux.replace({ pathname: path }));
```

appInstance 是 dva实例.

**Comment by dgeibi** [comment]
@HengCC 用 ConnectedRouter 而不是 Router https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux

**Comment by HengCC** [comment]
@dgeibi  
我用了dva封的router 

```
import { Router } from 'dva/router';
.....
return <Router history={history} routes={routes} />
```
初始化的时候这样
```
app.router(require('./router'));
```

跳转的时候类似这样写:

```
import { routerRedux} from 'dva/router';
dispatch(routerRedux.replace({ pathname: path }));
```
或者类似这样
```
dispatch(routerRedux.push( path));
```

你说的用`ConnectedRouter ` 的意思是要替换掉上面的Router吗, 不用从dva中引用吗?

**Comment by dgeibi** [comment]
@HengCC

这样

``` js
import { routerRedux } from 'dva/router'
const { ConnectedRouter } = routerRedux

function RouterConfig({ history }) {
  return <ConnectedRouter history={history}>...</ConnectedRouter>
}
```
