### ISSUE TITLE
dva 如何处理轮询请求的循环中也能渲染页面？

### ISSUE THREAD

**Issue by zachshelter** [dvajs/dva#721]
如题， 我们想在 effects 里的某个generator函数中采用轮询的方式对服务器某些数据进行请求。
用  yield call(delay, 1000)  + while 的方法的确可以实现轮询

但是使用过程中发现 action可以通过yield put(...)被正常发送， 但是页面的渲染被阻塞 （组件的render方法却又能到达，只是页面不发生变化）

想请问有什么好的办法可以解决此问题吗？

**Comment by nikogu** [comment]
组件 `render` 会执行，页面就会变得，检查你的数据是否正确
