### ISSUE TITLE
Integration dva with create-react-app

### ISSUE THREAD

**Issue by xiandongw** [dvajs/dva#722]
dva很好用 代码组织看起来很简洁。 能不能直接集成到 create-react-app （react official create app utility tool）？ 有没有人试过?

**Comment by sorrycc** [comment]
[roadhog](https://github.com/sorrycc/roadhog) 已集成大部分 create-react-app 的优点，所以没必要用 create-react-app 创建 dva 应用，用 [dva-cli](https://github.com/dvajs/dva-cli) 创建就好。

**Comment by aislanmaia** [comment]
[roadhog](https://github.com/sorrycc/roadhog) can scaffold a [Progressive Web App](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app) compliant just like the create-react-app does?
