### ISSUE TITLE
生产环境下 报错！regeneratorRuntime  

### ISSUE THREAD

**Issue by WangZi1997** [dvajs/dva#723]
![r_7dqxy5 ofk w a bsf2q](https://cloud.githubusercontent.com/assets/19681693/23888835/ee423606-08c4-11e7-825f-8aec2c5369d0.png)

**Comment by monkindey** [comment]
这个你需要的是上stackoverflow搜索下哦, 应该是你的配置问题, http://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await, 如果是用webpack的的话, 可以尝试下,

```js
entry: ['babel-polyfill', '你自己的文件']
```

**Comment by WangZi1997** [comment]
谢了

**Comment by WangZi1997** [comment]
不关这个   路霸 环境变量的锅

**Comment by WangZi1997** [comment]
路霸的环境 我们变量不够用  项目智能改源码解决
