### ISSUE TITLE
dva里为何找不到router.setRouteLeaveHook

### ISSUE THREAD

**Issue by Slngle** [dvajs/dva#725]
我想再离开该路由的时候清空state 于是想到了router.setRouteLeaveHook 但是看下props里面并没有router 如何解决啊 在线等！！

**Comment by nikogu** [comment]
参看 router 的文档：https://github.com/ReactTraining/react-router

应该是配个 `context` 就可以了

**Comment by yautah** [comment]
withRouter这个hoc包裹一下

例如
`import { Link,withRouter } from 'dva/router';

export default withRouter(requireBind(connect(mapStateToProps, mapFuncToProps)(Menus)));
`

然后props里面拿router

**Comment by Stephenzd** [comment]
用history.listenBefore好像也行的

**Comment by shiyuwudi** [comment]
放一个Prompt也可以 
```
import { Prompt } from 'react-router';
<Prompt
  when={isBlocking}
  message={location =>`Are you sure you want to go to ${location.pathname}` }
/>
```
