### ISSUE TITLE
fetch response 中文乱码 ？

### ISSUE THREAD

**Issue by wuyongdec** [dvajs/dva#726]
![qq 20170314164237](https://cloud.githubusercontent.com/assets/7280016/23892435/86c16ea0-08d5-11e7-9708-138a0d86e573.png)

后端返回的json中文全是乱码

**Comment by jeffhtli** [comment]
这与dva有何关系？

应该检查服务端编码，估计服务端编码是GBK

**Comment by wuyongdec** [comment]
@jeffhtli 确实没有关系，只是觉得这里提问大家比较热心，回答也认真些。后端说和他没有关系，很尴尬。

**Comment by nikogu** [comment]
@wuyongdec 查看请求头相关信息

**Comment by wuyongdec** [comment]
@nikogu response里面编码是 ：Content-Type:text/plain;charset=ISO-8859-1
我的请求头：
 `Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8
Connection:keep-alive
Content-Length:238
content-type:multipart/form-data; boundary=----WebKitFormBoundaryWzfO0AavBrBvADmj
Cookie:JSESSIONID=D166B5A7B9C9584F96EA3E41E486D09C; _dfAccess_=E74F0B299E3410808AE4D2AE878D6956; userPin=1355540
Host:test.srm.dongfang.com
Origin:http://srmfront.dongfang.com:8000
Referer:http://srmfront.dongfang.com:8000/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36`

**Comment by monkindey** [comment]
这个是一个有趣的问题, response charset改成utf-8是否可行呢?

相关问题 [Why can't I write Chinese characters in nodejs HTTP response?](http://stackoverflow.com/questions/10470426/why-cant-i-write-chinese-characters-in-nodejs-http-response)

下面一些小建议, 我也尝试着慢慢地这么做
* 前端还是要了解下HTTP(虽然我也很菜);
* 粘贴代码或者报文格式化下也许会让其他人更好理解点;
* 可以先到stackoverflow google获取一些信息, 也许比做伸手党好点;

希望对你有帮助

**Comment by wuyongdec** [comment]
@monkindey 问题解决了，后端spring 默认返回的是 ISO-8859-1，改一下返回字符集就好了。
