### ISSUE TITLE
.roadhogrc配置问题

### ISSUE THREAD

**Issue by zyMacro** [dvajs/dva#728]
关于编辑
https://ant.design/docs/react/practical-projects-cn#使用-antd
其中的内容似乎与0.7.8版本并不一致，而且不太确定那幅图中想表达的内容，是将
`
{
  "entry": "src/index.js",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime"
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime"
      ]
    }
  }
}`
中的production下面的extra部分改成那个样子吗，谢谢！

**Comment by nikogu** [comment]
@zyMacro 建议升级 dva，并使用最新的 roadhog 工具，`0.7.8` 这个版本的 dva 脚手架还是用的 webpack 在配置
