### ISSUE TITLE
Failed to decode font.

### ISSUE THREAD

**Issue by K-walker** [dvajs/dva#729]
我将官方提供的demo [https://github.com/dvajs/dva-example-user-dashboard](url) clone下来之后，
修改其.roadhogrc ，在theme中添加

  `"@icon-url":"'/src/assets/fonts/iconfont/iconfont'"` 

但是浏览器却提示如下警告：
```
Failed to decode downloaded font: http://localhost:8000/src/assets/fonts/iconfont/iconfont.woff
OTS parsing error: invalid version tag
```
不知为何，有劳给位给我解答下，谢谢了！

**Comment by sorrycc** [comment]
http://localhost:8000/src/assets/fonts/iconfont/iconfont.woff
单独访问这个地址，有返回吗?

**Comment by K-walker** [comment]
@sorrycc 没有任何返回，这个问题困扰我很久了，我昨天了提供了两个repo，其中一个可以通过theme的方式使用iconfont，另一个就是出现这个问题的demo，麻烦您帮我看看吧。[#5308](https://github.com/ant-design/ant-design/issues/5308)

**Comment by K-walker** [comment]
已经解决了 [#5308](https://github.com/ant-design/ant-design/issues/5308) ，将字体文件放到public目录下就可以了
然后再theme.js 中引用
` "icon-url" :"/fonts/iconfont/iconfont" ` 
不要带public目录即可。
