### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#73]
代码：
`const OrganView = ({organ}) => {
    return (
        <div>
          {organ.title}
        </div>
    );
};`

错误：`OrganView.jsx:6 Uncaught TypeError: Cannot read property 'title' of undefined`

原因：因为我在初始状态时organ={}，而这个数据是在subscription里面发一个effect action获取的，组件最开始渲染，organ={}。

我这个应该怎么写呢？

**Comment by sorrycc** [comment]
数据 connect 时或往下传 props 时处理地不对吧，自己 debug 定位下。

**Comment by bjwulin** [comment]
我写成{organ && organ.title}就没有问题了，我在初始状态确实设定的{organ:{}}，怎么回事undefined呢？从后台获取数据后，显示也正常。

**Comment by bjwulin** [comment]
后来我在改为({organ={}})=>{}也就好了，只是不明白，为啥我在model设定初始状态值为{}，connect后的组件里面organ是undefined。

**Comment by sorrycc** [comment]
外面传 initialState 了没?

**Comment by bjwulin** [comment]
外面没有传，我就通过connect 到Route的页面，Route页面里面的组件在用这个属性。

**Comment by nikogu** [comment]
@bjwulin `({ organ })` 跟 `( organ)` 不一样哦，你贴个 jsfiddle.net 的例子吧

**Comment by WhatAKitty** [comment]
@bjwulin 查一下reducers里面的set动作，还有就是selectors里面的数据删选，问题应该会在这两个方面上。
