### ISSUE TITLE
其他A model里yield call拿到的数据，在B model中select获取不到

### ISSUE THREAD

**Issue by yangbin1994** [dvajs/dva#730]
A model的请求是先发起的，拿到数据之后，发送action去保存data到state中。
在B model中的effects需要拿到data去发起另外的请求，但是select A model中的data为undefined

**Comment by nihgwu** [comment]
这个操作本身是没问题的，提问题请帖代码

**Comment by yongningfu** [comment]
有可能是Bmodal请求的时候 A还没获取数据，两种modal在不同的生成器系统里面运行的，具体看源码 [here](https://github.com/dvajs/dva/blob/master/src/createDva.js#L249)

**Comment by Syzmex** [comment]
肯定是运行顺序不对，要么A请求玩发一个action让B运行，要门AB一起运行，然后B用take阻塞，直到A完成存放数据然后发出aciton解除B的阻塞

**Comment by Alexorz** [comment]
遇到同样问题，请问 take 的API可以在哪看？ @Syzmex

**Comment by yangbin1994** [comment]
@Syzmex 现在就是take，异步的数据肯定是在之后拿到并派发action
