### ISSUE TITLE
请问request.js的fetch问题

### ISSUE THREAD

**Issue by sd632367** [dvajs/dva#731]
fetch引用的是dva/fetch，我设置了ajax请求，下面是代码
export async function login(payload) {
  return request('/api/', {
    method: 'POST',
    headers: {
      'credentials': 'include',
      'Accept': 'application/json',
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    data:JSON.stringify(payload)
  });
}
问题：我用php做后端接收数据，$_REQUEST无数据，只能通过file_get_contents("php://input") 这种方式来获取，为什么$_REQUEST获取不到请求的数据，是我设置问题吗？

**Comment by afc163** [comment]
建议此类问题到 http://segmentfault.com/ 提问，看描述和 dva 自身关系不大，属于前后端接口问题。

**Comment by jszcl** [comment]
后来解决了吗
