### ISSUE TITLE
antdesign bug 动态添加一行表格 只要删除中间任意行就报错

### ISSUE THREAD

**Issue by Slngle** [dvajs/dva#732]
应该是react diff算法导致表格的dom被删除 所以我想给一行的元素加上key 可是不知道如何给一行的元素加key

**Comment by Slngle** [comment]
![image](https://cloud.githubusercontent.com/assets/8002651/23936635/3caac460-098e-11e7-92b0-e94714e467e1.png)

**Comment by Slngle** [comment]
就是给TableRow加唯一的key
现在是自动加的

**Comment by Slngle** [comment]
找到了 在datasource里面加上唯一的key就行

**Comment by nihgwu** [comment]
这个跟dva有什么关系？

**Comment by Slngle** [comment]
ant不让提问。。。

**Comment by afc163** [comment]
@Slngle 如果确认是 Ant Design 的 bug，为啥不让提问？
