### ISSUE TITLE
触发多个 model 时，如何管理多个 subscription 的执行顺序

### ISSUE THREAD

**Issue by zhangda47** [dvajs/dva#734]
router: `/driver`   model: `driver`
router: `/` model: `app`

直接进入 `/driver`
`driver` 中的 subscription 依赖于 `app` 中 subscription/effect 执行完毕

**Comment by xufei** [comment]
这个可能不是subscription要解决的问题，你可以试试用put和take的组合去解决，app的effect结束之后，发put，并且在driver里take
