### ISSUE TITLE
什么时候换成webpack 2.0 ?

### ISSUE THREAD

**Issue by wxa1048989080** [dvajs/dva#736]
打包速度相当慢..

**Comment by nihgwu** [comment]
这跟 dva 有半毛钱关系？

**Comment by wf123537200** [comment]
同想问下这个问题，dva底层打包是怎么写的？和webpack版本没有关系的话，那怎么支持webpack配置写在roadhogrc，里面写webpack配置的？
另外，看dva-cli生成出来的包里面webpack版本还是1.14.0，是不是如果写webpack配置的话，只能按照webpack1.x的样子来写？

**Comment by zjxpcyc** [comment]
@wf123537200 roadhog 已经升级了，但是对 svg 的处理还有点问题

**Comment by wf123537200** [comment]
@zinkey 感谢，but，我刚看dav-cli装的还是 1.15.0，是需要重新安装一次么~~
另外，如果要配置的话，是不是直接按照webpack 2的配置就OK了~~
除了svg都OK对吧~
