### ISSUE TITLE
use browserHistory refresh problem

### ISSUE THREAD

**Issue by havefive** [dvajs/dva#74]
when use browserHistory such as:

const app = dva({
  history: browserHistory,
}); 

open browser to http://localhost:8989/about
and refresh got 404

open browser to http://localhost:8989 and click to http://localhost:8989/about works

**Comment by nikogu** [comment]
https://github.com/dvajs/dva/issues/68#issuecomment-245201207

**Comment by havefive** [comment]
Get it! But how can i use in production?

After npm run build ,the same issue

**Comment by nikogu** [comment]
@havefive if u want to use browserHistory in production, your server code need to be support to browserHistory. https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#browserhistory

**Comment by havefive** [comment]
Ok,thanks
