### ISSUE TITLE
【咨询】请问下如何在request.js请求的时候获取到redux全局state 

### ISSUE THREAD

**Issue by ufohjl** [dvajs/dva#740]
因为登陆后会有一个sessionId，存在redux store，以后每次请求都要带上，拼接在请求url里，请问使用dva有没有什么好的办法在发送网络请求的时候去获取到redux全局state，然后组装参数

**Comment by lokewei** [comment]
参考这个 #713 ， 用select取

**Comment by ufohjl** [comment]
@lokewei 可以用select取，但仅限于在model中获取。
如果每个请求都要去取诸如 yield sessionId = select(state => state.app.sessionId) 再去调用fetch，实在是有点麻烦。最好能在fetch的时候，直接从store中取到这个sessionId

**Comment by nihgwu** [comment]
设计如此

**Comment by ufohjl** [comment]
@nihgwu 那就只有用点hack手段了。。

**Comment by ufohjl** [comment]
最终在effect中把sessionId绑定到了window上，然后fetch的时候去取

**Comment by yinlsea** [comment]
我是这样做的，先创建一个createDVA.js
import createDva from 'dva';

export var app = {};
export function createDvaApp(opts) {
  // new instance
  app = createDva(opts);
  return app;
}
创建app时候用这个createDvaApp函数创建

然后在其他要引用的地方
import { app } from './createApp';
app._store.getState()[namespace];

**Comment by mhpyzzy** [comment]
window.g_app._store.getState()[namespace] 就可以获取到
