### ISSUE TITLE
如何设置路由的 basename？

### ISSUE THREAD

**Issue by shichenda** [dvajs/dva#741]
react-router 官方给出的方法：

import { useRouterHistory } from 'react-router'
import { createHistory } from 'history'

const history = useRouterHistory(createHistory)({
  basename: '/base-path'
})

但是不行

**Comment by zhangda47** [comment]
+1

**Comment by monkindey** [comment]
在我这边是可行的, 或者你可以提供更多信息出来

**Comment by shelwinnn** [comment]
`npm ls history`

看是否你装了额外的 react-router、history, dva 本身已内置，且是 2.x

**Comment by huamaolin** [comment]
+1 按官方的操作 首页可以加载 其他路由无法刷新

**Comment by huamaolin** [comment]
需要同时修改下index.html  index.js 路径为/index.js
