### ISSUE TITLE
Failed prop type： 这种错误如何调试

### ISSUE THREAD

**Issue by taven-liu** [dvajs/dva#744]
![qq 20170317110532](https://cloud.githubusercontent.com/assets/11688796/24027328/ab8d4280-0b01-11e7-9e64-14dc52318305.png)

**Comment by nikogu** [comment]
很明显的呀，说 `App` 这个组件的 `chidren` 这个 `props` 类型不正确，去 `App` 组件看一下不就好了

**Comment by taven-liu** [comment]
问题找到了，只是有点不明白下面两段代码有啥区别
```
getIndexRoute(nextState, cb) {
        require.ensure([], require => {
          cb(null, { component: require('./containers/t1Info') })
        }, 'test/t1/count')
}
```
```
getComponent(nextState, cb) {
      require.ensure(['../../common/index'], require => {
        cb(null, require('./containers/t2Container'))
      }, 'test/t2')
}
```
`cb(null, { component: require('./containers/t1Info') })`和`cb(null, require('./containers/t2Container'))`这个有啥区别，这个写错了就会报上述错误。
