### ISSUE TITLE
model 之间如何交互

### ISSUE THREAD

**Issue by xoptimal** [dvajs/dva#745]
场景:
* A页面, 点击添加按钮,  跳转到B页面 , 处理完后将数据带回去A界面 , 
* 现在有2个model ~  需要更改 modelA的 state 数据

**Comment by nikogu** [comment]
数据跟页面不存在耦合关系，哪个页面需要哪个数据，`connect` 相关的 `model` 就好了

**Comment by xoptimal** [comment]
我的意思是, 如何在modelB 里 , 更新modelA的数据 ~   因为modelA中有个数据跟modelB是关联的 , 我需要做同步操作, 而不是 connect ,

**Comment by nihgwu** [comment]
view 跟 model 又不是耦合的，你同时dispatch 两个 action就好了啊，或者在model B的effects里面dispatch model A 的action
还有，问问题的时候最好附上代码

**Comment by xoptimal** [comment]
@nihgwu   请问如何在 在model B的effects里面dispatch model A 的action

code:
```

pageA:
fun1(state, {payload: {list}}) { ... }

pageB:
      yield put({
        type   : 'pageA/fun1',
        payload: {
          list :.....
        }
      })
```

**Comment by nihgwu** [comment]
dva 版本多少，这么做应该没错啊

**Comment by xoptimal** [comment]
调用成功,   但是后面会跟了这个一个错误, 版本:1.2.1

**Comment by xoptimal** [comment]
哦哦 , 没写完整 ~ 弄笑话了 !!!  没有返回结果 .... 写的示例没注意,  感谢您的耐心解答 !  不过返回错误误导我了 0.0
