### ISSUE TITLE
输入框的 defaultValue 无法跟随 state 变化吗？

### ISSUE THREAD

**Issue by sandywk** [dvajs/dva#747]
给 input 组件 设置 value 会导致输入框无法被修改。
所以换成设置 defaultValue ，这样输入框可以被修改。
问题是页面的 state 变化后 defaultValue 值还是不变。

比如用户列表，我点击页面列表的用户，右侧会显示一个面板（没有全部遮挡），里面可以设置用户属性。
因为左侧还可以看到用户列表，所以这个时候还可以选择别的用户，问题是选择之后右侧 input 里的值没有变化（非 input 的值都有变化）。

我试过先隐藏右侧面板（也是通过 state ）然后再延迟 100 毫秒显示右侧面板，这样就能正常了，但是界面体验感不理想。

不知道有没有好的解决办法？

**Comment by nihgwu** [comment]
再问一遍，这个跟 dva 有什么关系？ 问问题请移步 https://segmentfault.com/

**Comment by longzhaobi** [comment]
first
```
const InputGen = () => <input defaultValue={name} />
```
then 
```
<InputGen />
```
这样试试看可以不！

**Comment by sandywk** [comment]
可以！非常感谢！ @longzhaobi
