### ISSUE TITLE
表单 Form 组件问题

### ISSUE THREAD

**Issue by sandywk** [dvajs/dva#748]
我看到官方文档里的示例代码都是用 react 原生 Component
`class TimeRelatedForm extends React.Component {
}
`
那如果用
`const SettingGrouping = ({ user, dispatch }) => {
}`
这样的格式，该怎样获取 this.props.form ？

**Comment by nihgwu** [comment]
这个跟 dva 有什么关系？

**Comment by Slngle** [comment]
const SettingGrouping = ({ user, dispatch }) => { }
这种方式{ user, dispatch }你把这种方式换成const SettingGrouping = (props) => {console.log(props)}
打出来看看你就明白了

**Comment by sandywk** [comment]
解决了，非常感谢！@Slngle
