### ISSUE TITLE
onStateChange does not work as well

### ISSUE THREAD

**Issue by ufohjl** [dvajs/dva#749]
```
// 1. Initialize
const app = dva({
  history: hashHistory,
  onStateChange: e => console.log(e)
});
```
always output ‘undefined’

**Comment by nihgwu** [comment]
`onStateChange` is actually a listener, and listener takes no params, see http://redux.js.org/docs/api/Store.html#subscribelistener

you can achieve in this way `onStateChange: () => console.log(app._store.getState())`

I think we should document this @sorrycc 
and `onAction: () => next => action => next(action)`

**Comment by ufohjl** [comment]
thanks!
