### ISSUE TITLE
复合领域对象的model的设计 : container components 是否可以嵌套 

### ISSUE THREAD

**Issue by qzhong1028** [dvajs/dva#750]
我的使用场景:

Entity A 包含 Entity B 包含 Entity C -> ...

每一个Entity都有一个单独的页面，在页面展示中可以通过wizard或者树状菜单联系在一起。

一开始的想法，是把Entity A 做成root, 用一个container component connect.

但实际由于领域对象比较复杂，嵌套层次太多，考虑对每一个Entity 做成一个container component. 这样就会有container component嵌套。想问下以下问题：

1） Redux/DVA是否支持 container component嵌套？
2）根据我对model的认识，每一个view可以有一个相应的model 对应。针对这种复合领域对象（大都出现在企业软件中如ERP系统），model/state之间关系如何处理，model/state可以设计成父子关系的吗？有没有相关系统的最佳设计实践？

对Redux和DVA都是新手，请高手指正？（如有样例代码参考，将不胜感激）

**Comment by nihgwu** [comment]
谁说 view 跟 model 是一一对应的？随便自由组合
