### ISSUE TITLE
表单嵌套有什么好的建议吗？

### ISSUE THREAD

**Issue by ldc4** [dvajs/dva#751]
不想在modal框上再弹一个modal框。
而B表单又需要放在A表单的中间。
还想使用dva提供的Form。

例如：
```
类别：（下拉框）   |  创建
   - 类别中文名：前端    [X]
   - 类别英文名：FE
姓名：（输入框）
```

外层为A表单（类别、姓名），已经在一个modal框中
内层为B表单（类别中文名、类别英文名）
点击创建显示B表单，B表单可以单独提交，并在类别下拉框中添加刚刚创建的项。

貌似这种需求很常见，但是直接写会看到警告：
`Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>. `

有人分享一下这种场景的最佳实践么

**Comment by nihgwu** [comment]
你确定这个跟 dva 有关系？提问可以去 segmentfault

**Comment by ldc4** [comment]
讲道理，segmentfault根本就没什么人。
另外，我只是询问使用dva的Form，能不能做到嵌套表单的需求

**Comment by nihgwu** [comment]
讲道理，dva没有所谓的Form，dva 只是提供了另外一种写 redux 和 redux-saga 的方式，如果不是 dva 本身的bug，其他问题都应该去问 redux 和 redux-saga 还有 react-router，如果你觉得 segmentfault 没人回答，你可以去 stackoverflow，

**Issues 是用来做 bug tracking 的，而不是用来 Q&A**
