### ISSUE TITLE
component和model重复利用问题

### ISSUE THREAD

**Issue by Zuckjet** [dvajs/dva#754]
我的应用场景是：
网页左边有好几个菜单栏，点击菜单栏，在右侧区域都会显示表格信息，而且这些表格都有类似的增加、删除等操作。
我的问题是：
既然点击这几个菜单栏，右侧区域显示的页面是相似的，那么我是否可以只写一个component和model，完成这几个页面。但是这样做的话，又会把这个model和component弄的有些复杂，因为它需要根据点击不同菜单来作出不同的展示（尽管这些展示页面很相似）

**Comment by Stephenzd** [comment]
可以写一个MainLayout组件和多个component,重复的东西写在MainLayout里

**Comment by zjxpcyc** [comment]
我觉得这样做不好
1、首先假设你成功了， 页面  A -> B -> A 就是页面有折返的情况下，你的 model 都要刷新。 如果你拆分model 就不存在这个问题
2、component 可以复用，但不是所有都要复用。model 不建议复用， model 跟业务强相关。小系统用一个可能没问题，大系统就完全不合适。
