### ISSUE TITLE
多个 model 异步处理顺序的问题

### ISSUE THREAD

**Issue by sandywk** [dvajs/dva#755]
场景是用 dva 开发的是客户端，所有数据都是通过异步获取。
用户登录后我会储存一个 cookie hash 。
这样我需要在用户登录后初始化（异步从服务器获取用户配置信息），比如models目录里有个dashboard.js获取顶层的配置信息并更新到state。

然后在用户进行功能操作的时候需要根据配置信息再异步获取数据，而这些逻辑是在另外的 model 里面。

那么问题来了，所有 model 的 subscriptions 是同步执行，我怎样确保在 dashboard 异步进行初始化之后再执行别的 model 的异步事件？

**Comment by sorrycc** [comment]
一个 subscription 入口，然后调 effect，然后按需调其他 model 的 effect，这样就能保证顺序了。

**Comment by yeelone** [comment]
@sorrycc  请问如何调用其它model的effect?

**Comment by xufei** [comment]
在call或者put的时候，type带上对方model的namespace就可以了
