### ISSUE TITLE
求教多个异步的请求问题？

### ISSUE THREAD

**Issue by zhump** [dvajs/dva#756]
```
subscriptions : {
        setup({dispatch, history}) {
            history.listen(location => {
                if (location.pathname === '/xxx') {
                    var id = location.query.id;
                    dispatch({type: 'xx1', payload: {id}});
                    dispatch({type: 'xx2', payload: {id}});
                    dispatch({type: 'xx3', payload: {id}});
                }
            })
        }
    },
```

因为用了dva-loading， 当xx1请求结束后，loading就为falsel了，其实 xx2 xx3还没有结束。把他们3个放到一起是可以的，但是 这样就会串行了，他们三个其实是并行的。串行耗时太长，求教怎么解决这种情况，谢谢

**Comment by sorrycc** [comment]
在 effect 里写 dispatch 的串行，做流程的控制，不要在 subscription 做异步流程处理。

**Comment by ouzhou** [comment]
@sorrycc 如果是同时发起多个并行的异步请求，怎么在 effect 里面实现等待所有请求完成后的逻辑？

**Comment by nihgwu** [comment]
yield * []

**Comment by ouzhou** [comment]
@zhump  我现在的方案是用eventproxy 或者 async 的 every方法，不知道有没有更好的方法，

**Comment by ouzhou** [comment]
@nihgwu 感谢🙏 请接受我的follow

**Comment by ouzhou** [comment]
@zhump 也就是说现在有多种方法，一是 yield [] 二是Promise.all([A请求,B请求])  三是各种奇怪的框架

**Comment by zhump** [comment]
@sorrycc 求一个串行的demo  :pray: :pray:

**Comment by ouzhou** [comment]
啊 感觉只能用callback了，说句题外话，既然你要一个全局loading为什么还要分谁先谁后，那还不如在组件内部维护一个state loading的状态，loading就不要放到model里面了，直接在组件里面发起请求，然后组件自己维护自己的loading

**Comment by DrakeXiang** [comment]
@nihgwu 怎么effects里面没有这个 all 的方法哇。。

**Comment by nihgwu** [comment]
@DrakeXiang 之前是 `yield []`, 后来 dva 升级了 saga 的版本之后就推荐用 `yield all`

**Comment by elowes** [comment]
@DrakeXiang ```*effects({}, { all }) {}```
