### ISSUE TITLE
对model进行目录划分，有什么快捷命令类似:dva g route ***

### ISSUE THREAD

**Issue by zhouzefei** [dvajs/dva#757]
当功能模块多的时候，相对model进行按功能划分文件模块
我现在是手动创建
![image](https://cloud.githubusercontent.com/assets/8566935/24134879/08859ca6-0e42-11e7-837f-207f3c0b7848.png)

在index.js中引入方式（不加.js会报错找不到orderTrack模块？？？）
<pre>app.model(require("./models/order/orderTrack.js"));</pre>

namespace
<pre>namespace: 'orderTrack',</pre>

如果用dva g route order/orderTrack这种方式，namespace就会变成order/orderTrack，
请问这种方式是可取的么

**Comment by sorrycc** [comment]
工具短时间应该没时间开发，先手动吧。

**Comment by zhouzefei** [comment]
为什么手动修改model目录后，在index.js中require model不加.js文件会找不到模块 @sorrycc

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues/565#issuecomment-282215368
是这个原因吗 ？
