### ISSUE TITLE
怎么做到subscription执行完成 再render页面

### ISSUE THREAD

**Issue by xiandongw** [dvajs/dva#758]
subscription 调用异步effect做一些页面初始化操作. 在异步执行完成前 页面已经开始render. 我现在是在jsx加 undefine  check来避免报错. 但是有些数据 比如global state 还是前一个记录的。要等到effect完成才能reset. 所以当然页面有时还是前一个记录的数据。 请问一般怎么处理这种页面初始化操作？  是不是不应该这么用subscription？

**Comment by sorrycc** [comment]
用 React 就没法避免这种情况，在 root component 里做判断吧。
