### ISSUE TITLE
在dva中引入fs模块使用不了，是怎么回事啊

### ISSUE THREAD

**Issue by zhanghuiming2016** [dvajs/dva#762]
酱紫

**Comment by nihgwu** [comment]
dva 是前端框架好吗，fs 是哪的，这里也不是问答网站

**Comment by ALiIsReal** [comment]
你好：
        现在有这样一个问题 ， 通过dva创建的项目 引用fs报错 
![default](https://user-images.githubusercontent.com/22163736/43704425-33bbfae6-9992-11e8-9e25-7c0852fe81ae.png)
fs模块可以正常操作在非dva创建项目中测试过 请问这样的问题如何解决？
或者在dva中有其他模块可以进行文件的读写，有的话能给个简单的demo嘛？

**Comment by ALiIsReal** [comment]
@sorrycc

**Comment by zhanghuiming2016** [comment]
@ALiIsReal fs模块是node.js在后端使用的，dva是前端框架
