### ISSUE TITLE
快来救救我，网络请求不知道为啥会重新请求

### ISSUE THREAD

**Issue by forever4313** [dvajs/dva#763]
事情是这样的，
我们在调试antd的一个上传控件（实现导入功能），测试跟我们说，当导入的过程过长就会出现莫名失败，
失败原因未知，因为如下图，只提示红色，
![tim 20170322175513](https://cloud.githubusercontent.com/assets/5886162/24192112/e31e1b2c-0f28-11e7-83f4-13ae295784d8.png)
但是response里没有任何东西返回，提示
![tim 20170322175554](https://cloud.githubusercontent.com/assets/5886162/24192113/e3775f34-0f28-11e7-845a-f74a21282e06.png)
并且每次都是4分钟失败（曾经测试到过6分钟，像是链接被断开了），查了各种服务器配置没问题，用postman与服务器请求，没有任何问题，多久都不会报错，使用antd upload里的customRequest 改成用dva里的fetch 问题依旧，改用ajax，问题依旧。只有postman不会出问题。现在只能求救了

还有一个就是重发请求的问题，
当等待回复过程超过一定时间的时候，发现dva的后台又打印了一次 刚才上传的接口，也就是说，dva帮我重新上传了一次。。。服务器收到两次上传请求。。。。怎么办。。。
![tim 20170322175808](https://cloud.githubusercontent.com/assets/5886162/24192266/528c2300-0f29-11e7-92f7-a439f004d10c.png)

@sorrycc 

使用的控件如下
```javascript
 const props = {
            name: 'file',
            multiple: false,
            showUploadList: true,
            accept:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel",
            action: '/nol/import/importDelivOrd.action',
            headers:header,
            onChange:this.handleChange,
            onRemove:this.onRemove
}
<Dragger {...props} >

```
在服务器打断点即可测试出超时的问题。

**Comment by forever4313** [comment]
开始怀疑重传是,webpack-hmr 导致的，但是，删除掉，重新请求，问题依旧还是会在，

**Comment by forever4313** [comment]
最新猜测：
框架会将超过2分钟的请求 尝试重传，如果重传失败，则失败。
看源码没看到有相关内容。

**Comment by sorrycc** [comment]
dva 没有做这件事的，检查下上传组件是否有做吧。

**Comment by forever4313** [comment]
但是我尝试用其他的接口，同样后台做断点，2分钟后也会有第二个请求发出去，4分钟后报红

**Comment by sorrycc** [comment]
试试：

1. 换浏览器（怀疑和 Chrome devtool 或者其他插件有关)
2. 不要用 dora-plugin-proxy

**Comment by forever4313** [comment]
换过FF，依旧2分钟超时
换了roadhog，依旧超时。
没辙了。。。
@sorrycc

**Comment by sorrycc** [comment]
检查下代码逻辑。。会不会自己逻辑里写了? 没遇到过这个反馈。

**Comment by forever4313** [comment]
没有写任何逻辑，就算我使用ajax 加timeout 也无效，依旧是2分钟，被这个折腾了好几天了。没查出来

**Comment by forever4313** [comment]
问题解决，是跨域问题，跨域导致了这个，放到同一个测试环境进行测试没有出现该问题。

**Comment by latel** [comment]
@forever4313 为啥跨域就会有时间限制？
