### ISSUE TITLE
如何刷新页面而又不会无限死循环?

### ISSUE THREAD

**Issue by ityao** [dvajs/dva#767]
现在微信支付页面的hash无法搞定, 唯一的可行方法就是进入订单页面刷新一下当前页面让微信知道这是URL入口, 应该怎么写这个进入一个页面只刷新一次的方法呢

**Comment by notedown** [comment]
微信支付页面的url例如/#/order 改成  /#!/order    加一个!或者? 
单页应用的纯#号url是发不起支付的.安卓和苹果都兼容只能 加!或者? 
不影响单页应用的页面显示.但是会出现状态机有可能清空的情况.
状态机store中的用户填写的例如表单你可能你需要手机cookie缓存来储存了
如果你发现更好的方法.可以@ 我
