### ISSUE TITLE
Avoid blocking calls

### ISSUE THREAD

**Issue by trihtm** [dvajs/dva#768]
Hello, who knows how to remove XHR blocking?

All my requests, which called by model (using redux-saga), are run sequently.

How to running tasks in parallel (https://redux-saga.github.io/redux-saga/docs/advanced/RunningTasksInParallel.html), and avoid blocking calls?  

Thanks.

**Comment by sorrycc** [comment]
Does this don't work? 

```js
const [users, repos]  = yield [
  call(fetch, '/users'),
  call(fetch, '/repos')
]
```

**Comment by nihgwu** [comment]
call a request without `yield`

**Comment by trihtm** [comment]
@sorrycc I've called effects from different model's subscriptions. So not able to join to single yield.
