### ISSUE TITLE
关于model state 中数据的生命周期

### ISSUE THREAD

**Issue by CN-YUANYU** [dvajs/dva#769]
请问， 所有model 当中的state  是否 在 app 存活期 里面的数据也是一直存在的？

如此的话， 假设我的model 很多， 数据也很多，是否会导致内存崩溃

举个具体的场景

假设 model a  在 页面a 中被调用， 并且在state 中存入了 一部分数据， 
此时页面跳转至 页面b   接着 c  d  e  f ， 而这些页面 并没有 引用model a，
那么在此中场景下， 是否model a 中缓存的数据 会一直存在，

请原谅我比较懒，没有自己亲自去实验

**Comment by CN-YUANYU** [comment]
小白第一次在github 上提问， 好紧张

**Comment by nihgwu** [comment]
会一直存在，至于 OOM 的问题，view 是依据 model state 来渲染的，所以如果确实有大量的数据，你应该考虑的时候如何维护你的 state 结构

**Comment by CN-YUANYU** [comment]
@nihgwu  数据量的大小  跟 结构有本质性的关联关系吗？

**Comment by nihgwu** [comment]
数据的内存占用跟数据结构有本质联系，这个答案满意吗
还有，这个问题与 dva 无关，这种问题还是去 Stackoverflow 或者 Segmentfault 上去提，会更有收获

**Comment by CN-YUANYU** [comment]
@nihgwu  不是很满意，  我认为任何形式的数据结构  也必然会存在  内存占用的瓶颈问题，  并不是说你数据结构好  就能不占用内存了。

不过还是感谢你的建议和回答
