### ISSUE TITLE
UserSearch.jsx界面切换field选择，怎么清空keyword的值？

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#77]
因为切换了field，那么应该把上一次填入的值即keyword的值清除掉？

是不是只能在切换的时候，通过onChangeField将model里面的状态改变来刷新UserSearch？

我还想根据field来更改keyword是输入框，还是下拉选择，或者日期范围...有没有其他更好的办法？

**Comment by sorrycc** [comment]
感觉这个地方用 component state 会比较合适。

**Comment by bjwulin** [comment]
好的，我试试。

**Comment by WhatAKitty** [comment]
@sorrycc 是不是建议，如果只是单纯的本组件内部状态，直接使用component state？现在配套使用了antd，类似form，就直接通过form.create存储在component state里面，不过其他的状态还是通过redux

**Comment by sorrycc** [comment]
@WhatAKitty 是的。

**Comment by wonyun** [comment]
@sorrycc 
看了你的答复，我又来疑问了，您说单纯本组件内部状态使用component state，那么单纯列表页中的列表数据和分页相关数据是否也可以置于component state而不用置于model的state中啊？如何更好的区分什么情况下state该置于model中还是component中呢？

**Comment by sorrycc** [comment]
推荐全部放 model 里。

**Comment by WhatAKitty** [comment]
@sorrycc 这里有一个问题，如果全部放在model内部，会不会造成state树过于庞大，APP运行不流畅？我在用的过程中有时候会出现这种情况。还是说，对于复杂的业务系统，不推荐使用redux？

**Comment by sorrycc** [comment]
还没遇到过这样的情况，再说担心 state 过大，可以通过 reducer 清理不需要的 state 。

**Comment by WhatAKitty** [comment]
@sorrycc 清理的话，是使用全局清理还是说在需要的时候进行清理一下对应的model，如果是按需清理的话，这样会不会造成代码复杂度提升，增大开发工作量？

**Comment by WhatAKitty** [comment]
https://github.com/reactjs/redux/issues/1287
