### ISSUE TITLE
app.use(plugin) 这个只能使用一次？

### ISSUE THREAD

**Issue by beiyeren** [dvajs/dva#771]
翻了一下源码
![image](https://cloud.githubusercontent.com/assets/3363044/24331628/c3a6e248-126a-11e7-97c4-7e51345f5b02.png)

我理解按照这样写法，就只能使用一个插件。我的情况是：使用dva-loading，同时我希望自己写一个插件，去统一捕获effect抛出的异常。就没法实现了吧。

**Comment by nihgwu** [comment]
捕获 effects 的异常可以再 onError 里做啊，不过这个地方是如果你要用 extraEnhancers 直接写到 extraEnhancers 里就好了，其他的插件照样可以用 use

**Comment by sorrycc** [comment]
捕获 Effect 异常可以在 onEffect 里或 onError 里做，可以参考 https://github.com/jaredleechn/dva-sentry

**Comment by beiyeren** [comment]
我是假设了一个场景：如果定义了两个plugin A、B， 假设A、B都定义了extraEnhancers，然后使用app.use(A);
app.use(B);
则A的extraEnhancers会被B的覆盖掉，对吧。

不过onEffect 里或 onError确实可以解决我捕获异常的问题，只是看了这段代码，觉的不能定义多个extraEnhancers有点奇怪。
