### ISSUE TITLE
大神求关注  附上git地址

### ISSUE THREAD

**Issue by 624508914** [dvajs/dva#773]
https://github.com/624508914/dva

npm start 正常
但是打开网页 console 报错

**Comment by 624508914** [comment]
@sorrycc

**Comment by xufei** [comment]
test: /\.(js|jsx)$/,
loader: 'babel?cacheDirectory=.cache',
// 加这句：* exclude: /node_modules/ *

**Comment by 624508914** [comment]
非常感谢

**Comment by xufei** [comment]
好了吗，好了就关掉这个issue吧……
