### ISSUE TITLE
dva多页面开发

### ISSUE THREAD

**Issue by sunshinefull** [dvajs/dva#774]
用react+dva怎么实现多页面开发，本地怎么访问。有没有demo可以参考。

**Comment by ShadowRambler** [comment]
同求

**Comment by sorrycc** [comment]
多页不就是多个单页，打包时配多个 entry 不就好了吗?

**Comment by ShadowRambler** [comment]
entry好像只支持字符串，跟webpack的entry配法不同，而且开发环境下的后端路由怎么匹配到不同入口的不太清楚,不同的页面如何配置各自的html模版。roadhog的文档不多，麻烦指点一下

**Comment by sorrycc** [comment]
https://github.com/sorrycc/roadhog#entry
entry 的用法文档里已经写了。
