### ISSUE TITLE
dva热替换如何实现 有小的demo可以看看么

### ISSUE THREAD

**Issue by Slngle** [dvajs/dva#775]
如题 dva热替换如何实现 有小的demo可以看看么

**Comment by sorrycc** [comment]
[dva-example-user-dashboard](https://github.com/dvajs/dva-example-user-dashboard) 是支持 HMR 的，要了解如何实现可以看下：

- https://github.com/dvajs/babel-plugin-dva-hmr
- dva 的 onHmr hook
