### ISSUE TITLE
yield call   下面的代码不执行   拿不到返回的数据

### ISSUE THREAD

**Issue by struggle-lulu** [dvajs/dva#776]
刚开始用这个，yield call发了一个请求，这句代码下面的不执行，请求结果也拿不到，哪里的问题呢

**Comment by xufei** [comment]
贴完整代码呢？是不是出异常了

**Comment by sorrycc** [comment]
- [如何向开源项目提交无法解答的问题](https://zhuanlan.zhihu.com/p/25795393)
