### ISSUE TITLE
dva 应用在react-native 是否可行，是否稳定，有项目案例么？

### ISSUE THREAD

**Issue by ninjai001** [dvajs/dva#777]
dva 应用在react-native 是否可行，是否稳定，有项目案例么？
现在用dva 应用在 react-native  是否成熟

**Comment by nihgwu** [comment]
不看 README 的吗？

**Comment by ninjai001** [comment]
我看了，能跑起来；dva是将react-saga的封装，到底用dva对react-native 稳定么，还是采用react-saga好呢？给个建议？

**Comment by yuzhouisme** [comment]
可以的，一样健壮、稳定

**Comment by ninjai001** [comment]
subscriptions: {
    setup({ dispatch }) {
      console.log('dispatch homw')
      dispatch({
              type: 'getList',
              payload: {}
        });
        //  history.listen(location => {
        //     if (location.pathname === '/ProductPlan') {
        //       dispatch({
        //         type: 'query',
        //         payload: {}
        //       });
        //     }
        //   });
    },
  },



我在model 中如何判断路由呢，不然每次model都会请求数据

**Comment by ninjai001** [comment]
我在用dva 开发 react-native 的时候，如何 在订阅的时候通过路由，来更新不同的数据；

**Comment by nihgwu** [comment]
dva 用于 react-native 不支持 router 功能，如果订阅路由？

**Comment by ninjai001** [comment]
那是不是 我么牛仔订阅的时候如何过来dispatch 时间呢

**Comment by kala888** [comment]
RN 里react-navigation如何使用subscriptions
