### ISSUE TITLE
关于model的问题

### ISSUE THREAD

**Issue by wishingweed** [dvajs/dva#779]
您好，我是一个react和redux的新手，我刚刚开始用dva来搭建自己的一个项目，之前写过react+redux，习惯把不同reducer的state值传到component一起用，也就是直接把combine reducer的state直接传到component一起使用，可能一个component渲染所需要的数值是从不同的reducer的state中拿到的。不知道dva中model支不支持combine reducer这样的概念？类似于一个namespace下面有些子namespace。还是我的这种开发习惯有问题，麻烦您解答，谢谢！

**Comment by xufei** [comment]
不一定要是namespace的嵌套，在select的时候，是可以select到其他namespace下面的东西的啊

**Comment by wishingweed** [comment]
谢谢民工叔解答，是需要把一个component和多个model connect 么？
我刚才自己测了下比如我有两个model A，B 然后有一个componentX

我这么写 export default connect(({A,B})=>({A,B}))(X)
然后在 X开始的时候写
const X = (A,B,dispatch)=>{
}
然后输出A，B发现只有A可以输出值。
不好意思，麻烦您给举个例子可以么？
感谢！

**Comment by xufei** [comment]
不是，我意思是说，如果你有两个model，然后可以在界面上用两个组件分别connect进来，只要都加载了，在任意一个的effect里面用select都能拿到另外一个的状态：

```JavaScript
*effectA({ payload }, { call, put, select }) {
  const { a, b } = yield select();
  console.log(a, b);
}
```

**Comment by wishingweed** [comment]
谢谢耐心解答！
