### ISSUE TITLE
dva中如何引用redux-devtools这类的开发工具?

### ISSUE THREAD

**Issue by zerozaki0752** [dvajs/dva#78]
希望dva能够打包一下常用的开发插件

**Comment by sorrycc** [comment]
用这个插件，内置支持的。
https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en

**Comment by zerozaki0752** [comment]
@sorrycc 这个插件是不是还要配合在代码中添加一些内容？

**Comment by sorrycc** [comment]
@zerozaki0752 代码已经内置了的。
