### ISSUE TITLE
开发环境下重命名models后报错

### ISSUE THREAD

**Issue by David-zzg** [dvajs/dva#781]
原先在models目录中有个ItemSelect文件，后来我把ItemSelect重命名了，并在index.js制定了重命名后的model。。然后就报错了，报错日志如下
webpackHotDevClient.js:231 Error in ./src/index.js
Module not found: [CaseSensitivePathsPlugin] `xxx(隐藏了目录细节)/models/ItemSelect.js` does not match the corresponding path on disk - File does not exist.

 @ ./src/index.js 73:48-78 74:4-81:6 77:18-48 86:49-79 87:4-94:6 90:18-48

我试过重新创建一个新文件，内容跟更改名字文件内容一致，就可以正常运行。

关于CaseSensitivePathsPlugin 我有看过插件介绍，大概是解决跨平台的文件路径冲突。我本人的系统是OSX,猜测这个issues跟这个插件有关？

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues/565#issuecomment-282215368
是否这个问题？

**Comment by b9AobJ** [comment]
今天遇到了这个问题，原因跟大家说下：
同事将一个文件重命名了下，IDE竟然对文件的大小写不报错，直接通过了。真是蛋疼菊花紧了一波；
原因就是文件驼峰写法的大小写更换了下，其他引用文件名的时候未更改，程序不报错；
解决：修改引用。
希望以后遇到的huber们提供一种思路
