### ISSUE TITLE
关于model的脏数据问题

### ISSUE THREAD

**Issue by sven0726** [dvajs/dva#784]
项目中我们一般会在model里state保存一些数据，而这些数据只是当时页面逻辑需要。在完成当时处理后，如何清理，以免成为下次重新使用时的脏数据？

**Comment by junmaqiang** [comment]
量不大的话应该不重要吧!  除非代码洁癖晚期!

**Comment by nikogu** [comment]
@sven0726 写个 clear 的 reducer 清理 model 就好了
