### ISSUE TITLE
npm run build之后，antdesign样式丢失

### ISSUE THREAD

**Issue by Zuckjet** [dvajs/dva#785]
隔壁解决了在create-react-app中，npm run build之后antdesign样式丢失丢失问题
<https://github.com/ant-design/create-react-app-antd/pull/1>

我用dva创建的项目，目录结构中没有webpack.config.prod.js文件，请问类似问题怎么解决？

**Comment by sorrycc** [comment]
dva-cli 创建的项目，不存在这个问题吧，参考 https://github.com/dvajs/dva-example-user-dashboard

**Comment by Zuckjet** [comment]
我是按照你的教程使用dva-cli创建的项目，使用npm run build之后，把打包后dist文件夹下的文件放在nodejs服务器下，然后再访问页面就没有了antdesign样式。
之前使用create-react-app的时候，有webpack.config.prod.js配置文件，
在dva中，有类似webpack.config.prod.js这样关于打包的配置文件吗？
还是说，楼主使用npm run build部署生产环境后，访问页面，没有出现类似我的antdesign样式丢失问题。
谢谢解答！

**Comment by sdli** [comment]
确实存在，ant-design自带的样式全都丢失了。

**Comment by Zuckjet** [comment]
![zyj](https://cloud.githubusercontent.com/assets/17976139/25032037/8d5192f4-2103-11e7-8275-9c4ecc1093bc.png)
之前只在开发环境中引入antdesign，所以打包后样式丢失，如果在生产环境也引入这个antdesign样式，问题就解决了。主要是当时对这个dva不是很了解，所以出现问题就来麻烦大神。前段时间看到他们阿里负责antdesign团队在知乎上吐槽，说开源难做，也是很体谅他们。
