### ISSUE TITLE
dva1.3.0-beta2 lib onStateChange 编译错误

### ISSUE THREAD

**Issue by Superman-wc** [dvajs/dva#786]
源代码 src/createDva.js 第240-247  其中244行
```
// store change
const listeners = plugin.get('onStateChange');
    for (const listener of listeners) {
      store.subscribe(() => {
        listener(store.getState());
      });
  }
```
编译后 lib/createDva.js 第352-354行
```
var listener = _step3.value;
store.subscribe(listener);
```

编译后是错误的，没有把store.getState() 传递给 listener

您的原意是：解决Plugins的onStateChange方法没有传递state的问题？

最好是能够传递 正在改变的东西，但是 createStore.js 中的185-187行
```
for (var i = 0; i < listeners.length; i++) {
      listeners[i]();
    }
```
没有带参数过来

createStore.js 已经在你的dva之外了。。。

**Comment by sorrycc** [comment]
应该是忘记 build 了，已发布 dva@1.3.0-beta.3 修复。

**Comment by Superman-wc** [comment]
这个方法还是比较鸡肋的，你现在传递是整个state，而我想知道的是改变的部分！！！

**Comment by sorrycc** [comment]
那要自己处理了，框架处理 diff 不合适，大部分场景下不需要。
