### ISSUE TITLE
示例中fetch的使用疑问

### ISSUE THREAD

**Issue by 275287902** [dvajs/dva#79]
在user-dashboard中utils/request.js
```
export async function create(params) {
  return request('/api/users', {
    method: 'post',
    body: qs.stringify(params)
  });
}
```
这样传过去的参数，后台接收是context-type是text文本，我查了相关的资料，好像要自行设置为
```
export async function create(params) {
  return request("/api/regexes", {
    method: 'post',
    body: JSON.stringify(params),
    headers: {
      "Content-Type": "application/json"
    },
  });
}
```
这样的话很麻烦，我还查了下，[MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API/Using_Fetch)这里有说

> request 和response (也包括fetch() 方法)都会试着自动设置content type.如果没有设置Content-Type值，发送的请求也会自动设值.

我试了下，关没有自动设置content-type为json，如下：
```
export async function create(params) {
  return request("/api/regexes", {
    method: 'post',
    body: JSON.stringify(params), //或者body:params，这样好像连参数都没有传过去
  });
}
```
是我哪里操作不对么？这个总是本不应该出现在这里，我看示例上有用，请问，您有更好的解决方案么？

**Comment by sorrycc** [comment]
为啥要设 `Content-Type`，你的服务端要求必须设吗?

**Comment by 275287902** [comment]
@sorrycc 后端说是要设，要不拿不到值。那如果后端要拿到json数据的话，用
`body: JSON.stringify(params)`
这样应该是可以的。

**Comment by sorrycc** [comment]
那就在 `src/utils/request.js` 里整体设下好了。

**Comment by 90h** [comment]
@275287902 请问为什么用qs.stringify，body就发不出去呢？

**Comment by 275287902** [comment]
你好：
	可以发出去的，只是后端解析方式不同，qs.stringify会把对象序列化成key=value&key=value这样，JSON.stringify的话会把对象序列会成JSON字符串。具体可以用devtools看下request。

**Comment by khahux** [comment]
@275287902 哈哈，谢谢，是我搞错了，qs.stringify 当value是undefined，时序列化就不存在了，没注意

**Comment by dan-me** [comment]
@275287902  
export async function create(params) {
  return request('/api/users', {
    method: 'post',
    body: qs.stringify(params)
  });
}

我也是这样写，为什么后台 $_POST 获取不到值呀？

**Comment by sorrycc** [comment]
@dan-me 换 post form 的方式看看? https://www.npmjs.com/package/whatwg-fetch#post-form

**Comment by dan-me** [comment]
@sorrycc  我不是用form表单提交东西，我是随便传个params， get方式提交的的php后台可以通过$_GET拿到值，post方式提交的 $_POST 是拿不到值的 怎么办？

**Comment by lincenying** [comment]
默认用的数据流的方法, 用$_POST自然取不到, 要用 file_get_contents(php://input)

**Comment by dan-me** [comment]
@lincenying  谢谢 搞定了
