### ISSUE TITLE
资源文件问题

### ISSUE THREAD

**Issue by spiroo** [dvajs/dva#790]
开发时，在less文件中写的背景图片样式：
![image](https://cloud.githubusercontent.com/assets/7858201/24537011/a6ff4478-1611-11e7-8231-8d3b661b5e9f.png)

`npm run build`完以后变成了绝对路径：
![image](https://cloud.githubusercontent.com/assets/7858201/24537023/cae765a0-1611-11e7-91fb-116193465b29.png)

如果我把程序部署在了二级目录下（如：我ngnix 8010端口指向html目录，我把构建完的文件放在了`html/dist/`目录下），就找不到资源文件了，请问除了放在一级目录，有没有别的办法可以解决？

**Comment by grunmin** [comment]
把nginx的root指向html/dist目录咯

**Comment by spiroo** [comment]
@grunmin html目录下我可能放多个项目，如dist1，dist2，还有其他办法吗？

**Comment by yangbin1994** [comment]
```javascript
"env": {
    "production": {
        "publicPath": process.env.CI_BUILD_REF_NAME ? `http://cdn.tarsocial.com/bluefocus/${process.env.CI_BUILD_REF_NAME.replace(/\./ig, '')}/` : '/'
    }
}
```
