### ISSUE TITLE
关于 dva 中 action 的疑问

### ISSUE THREAD

**Issue by ymjrcc** [dvajs/dva#793]
刚学习 dva 不久，对其中的 action 概念有些疑问。之前学习 redux，了解了 action 和 reducer 之间的关系，但是学习 dva 的过程中，对这个概念有点困惑。

1. 在 model 里，只有 reducers，那 actions 从何体现呢？

2. 有的 reducer 函数参数只有 state，而在 redux 里是有 action 参数的，为什么这里第二个参数可以省略呢？有的 reducer 函数同时有 state 和 action 两个参数，那这个 action 是从哪来的呢？

3. 我们都知道 dispatch 函数是用来触发 action 的，但是在实际使用的时候，其传入的 type 却是 reducers 的函数名，这是为什么？

问题有点小白，还望不吝赐教，谢谢！

**Comment by zzh-a** [comment]
你把action 和 action creator的概念搞混了， 可以再去看看[redux的action定义](http://cn.redux.js.org/docs/basics/Actions.html)

**Comment by yongningfu** [comment]
这个问题问的有点广泛，从redux上面讲的话，dispatch(action) 会调用reducer,返回新的state, 从dva上面来讲的话，dva对redux做了一层封装，它会把modal里面的 reducers函数, 进行一次key的遍历，每个key为一个reducer,当然它加上命名空间， [here]( https://github.com/dvajs/dva/blob/master/src/createDva.js#L333)， 这样不就有 action type对应的reducer了么
