### ISSUE TITLE
关于table中Modal的渲染问题

### ISSUE THREAD

**Issue by forever4313** [dvajs/dva#794]
在dva的 user-dashboard项目中 table中最后一列为操作列，代码如下
```
<UserModal record={record} onOk={editHandler.bind(null, record.id)}>
    <a>Edit</a>
</UserModal>
```
那么table在渲染的时候，UserModal不就会被渲染掉了吗？比如，table里面有200条数据，就会渲染200个Modal？这是不是有问题啊~~~

所以，还是应该绑定某个model里的state，判断state 是否为visible
```
modalVisible?<ModalA/>:""
```
这样的话，只需要在某个时机渲染一次Modal就好了。

**Comment by zjxpcyc** [comment]
我没看过这个代码，但是，我感觉，即使换成你说的方式，也是需要 200 多个 Modal 。

要不然，一个 modal 可能会出现数据不能更新的现象。

我打个比方， User A 的 name 是 'aa',  User B 中的 name 是空的。 你先用 Modal 打开 User A 的数据，显示是正常的， 但是 再 打开 User B 的数据，你可能发现 name 属性，居然是 'aa'。

我只是理论上觉得用一个 Modal 会出现上述的现象。如果你一个 Modal 不同 key 可能会避免上述问题。

**Comment by zjxpcyc** [comment]
@Yingkaixiang 具体的原因，我也不太清楚。感觉应该是使用 Modal 的子组件的状态管理有问题。就是你用 Modal 组件包裹起来的组件的状态管理有问题。你看看有没有方法把你的组件强制进行状态刷新，比如加 key 试试。
