### ISSUE TITLE
model 根据路由变化加载(app.model)和销毁（app.unmodel），（开发环境）redux 抛出warning

### ISSUE THREAD

**Issue by SijieCai** [dvajs/dva#795]
背景大概如下，我们开发的spa 是个大项目，有几十个页面，而且model是和页面绑定（view model的形式）。为了节约内存和保持一个干净的state，需要注销model。整个程序的state 大致如下
{
     app， // 长期存在，包含 menu，通用逻辑
     pageModel1,  // pageModel 就是页面模型，简单的我们希望页面关闭的时候注销掉这个
     pageModel2,
     ...
}

    var modelCache = {};
    AuthRoute.entering = (route, l)=>{
      console.log('entering', l.location.pathname);
      route.getModel(model=>{
        if(!modelCache[model.namespace]) {
          app.model(model);
          modelCache[model.namespace] = 1;
        }
      });
    }

    AuthRoute.leaving = (route, l)=>{
      console.log('leaving', l.location.pathname);
      route.getModel(({namespace})=>{
        if(modelCache[namespace]) {
          app.unmodel(namespace);
          modelCache[namespace] = 0;
        }
      });
    }

然而比较烦人的是，在开发环境里面 redux 的combineReducer 抛 warning

Unexpected key "demo" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "routing", "users", "@@dva". Unexpected keys will be ignored.

1. 看了源码是因为 combineReducer  这个函数回去检查两次 state 的差异然后给出警告。
问题： 有方法去掉这个警告吗

2. 想去掉警告的另一个方案是不去注销model，而是去重置model的到初始状态（初始状态的内存占用比较小）
问题： 在某个时刻让一个model 回复到初试状态的最佳做法是什么，这个时刻我能获取的对象有，app，model 本身。

**Comment by SijieCai** [comment]
https://github.com/reactjs/redux/issues/1636  
这个问题目前还没有解。看来有不少人有同样的问题，其实不是dva实现造成的，大家可以看看有什么想法

**Comment by bingqichen** [comment]
@SijieCai 老铁，你这个问题解决了么？

**Comment by SijieCai** [comment]
想了一个临时方案，既然只有在开发环境抛警告，那我销毁model 的代码前面加上仅仅生产环境才去销毁


      // on route leaving
      if (process.env.NODE_ENV === 'production') {
         // remove reducer here
      }

**Comment by hwep** [comment]
这个问题的解决 ： https://github.com/hwep/rva
