### ISSUE TITLE
如何在一个页面销毁的时候，清除所有异步请求？

### ISSUE THREAD

**Issue by yongningfu** [dvajs/dva#796]
我们常在页面进入的时候，发起异步请求数据，有可能请求还没结束，用户又跑到其他页面去，目前的需求是，如果在页面消失的时候，取消当前页面所有异步请求，我发现源码里面有这个 ```yield sagaEffects.take(`${model.namespace}/@@CANCEL_EFFECTS`);```[here](https://github.com/dvajs/dva/blob/master/src/createDva.js#L379), 用了以后，发现不行，因为modal里面的effect全部是在app start的时候，进行fork监控的，后面把任务取消了，它们并不会再fork，所以这个modal里面的effect也无效了，所有该怎么办呢？
```javascript
  componentWillUnmount() {
    //https://github.com/dvajs/dva/blob/master/src/createDva.js#L379
    //文档没有提供 但是看源码 里面有这个
    this.props.dispatch({type: 'QuestionDetail/@@CANCEL_EFFECTS'});
  }
```

**Comment by behind2** [comment]
为啥一句话不说就close掉了？
