### ISSUE TITLE
dva为啥会用generator。。我认为异步操作现在没有理由不直接用async function

### ISSUE THREAD

**Issue by ninjai001** [dvajs/dva#798]
其次我觉得dva很好的继承了redux，、。。过度重复render

**Comment by 3610cn** [comment]
因为redux-saga用了generator,dva只是整合了一些react技术栈的最佳实践

**Comment by sorrycc** [comment]
generator 对于流程更可控，这里需要处理的不仅仅是异步操作。

**Comment by youngjuning** [comment]
mobx++, redux--

**Comment by brizer** [comment]
> generator 对于流程更可控，这里需要处理的不仅仅是异步操作。

方便列举几个现实场景到底相比async语法糖更可控在哪里吗？

**Comment by Nicolaschinc** [comment]
相比async/await, generator我也想知道流程更可控表现在哪方面，目前感觉是只有复杂度更高一点
