### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by sorrycc** [dvajs/dva#8]
没有集成在 [1.0 RoadMap](https://github.com/sorrycc/dva/issues/6) 里的先放这里，可能 2.0 或者之后的版本再做。
- Framework
  - SSR Support
  - ReactNative Support
  - HMR Support: reducer, effects
  - Fetch Wrapper
  - Build Size
  - ImutableJS Support
- Addons
  - i18n
  - auto loading status
- Tools
  - dva-devtools
  - dva-app

**Comment by netfishx** [comment]
SSR 的支持非常期待，另一个希望能考虑的是：代码的分割，动态加载。

**Comment by sorrycc** [comment]
> SSR

应该已经可以用了，但没试，会在 https://github.com/dvajs/dva-hackernews 试下

> 代码的分割，动态加载

model 已经支持动态注入了，所以 web 端结合 react-router 的 dynamic config 可以拆分代码，动态加载。详见：https://github.com/dvajs/dva/tree/master/examples/dynamic-load

**Comment by sorrycc** [comment]
It's outdated, close.
