### ISSUE TITLE
实际投产困难……

### ISSUE THREAD

**Issue by fireyjy** [dvajs/dva#80]
能否提供一下如何进行webpack打包可以投入其他的服务器运行的方法。您提供的demo之类内容中webpack.config.js文件完全为dev-server服务，通常情况很罕见，而且也是在dva项目demo中第一次看到dora，proxy之类的而不是webpack-dev-server --watch。dva本身的讲解还是很好入门，但是如果要加上去学习这些的话就感觉有些蛋疼了。

**Comment by sorrycc** [comment]
不想基于 dora，那就用 create-react-app 吧。看这里的说明 https://github.com/dvajs/dva/issues/58#issuecomment-243435470 ，不过 webpack 还是要知道的。

**Comment by fireyjy** [comment]
谢谢回复，我再回去研究一下吧。之前对webpack都是一套入口+loader+插件这么组合着套用。

**Comment by sorrycc** [comment]
dva 就是一个 npm 包，之前怎么用 webpack 就可以怎么用。不过也不妨试试 dora 这一套，基于 webpack-dev-server 封装的。
