### ISSUE TITLE
mock 下 req.body 拿不到请求的参数

### ISSUE THREAD

**Issue by peterlevel1** [dvajs/dva#800]
module.exports = {
  "POST /api/users": (req, res) => {
    console.log("[POST /api/users]: ", req)
    setTimeout(() => {
      res.json({
        result: "success",
        data: {
          yes: "ooo"
        },
        msg: ""
      })
    }, 300)
  }
}

----------------------------------------
req.body是undefined
前端的参数拿不到的话，对于模拟请求是很蛋疼的事，望改进

**Comment by dicklwm** [comment]
https://github.com/sorrycc/roadhog/issues/86

**Comment by sorrycc** [comment]
try roadhog@0.6.0-beta.3
