### ISSUE TITLE
css里import图片的问题 

### ISSUE THREAD

**Issue by Slngle** [dvajs/dva#801]
我的图片都放在public／img／里面 
在jsx里我可以
```javascript
import sidebar_arrow from 'public/img/sidebar_arrow.png';
```
然后使用sidebar_arrow这个变量到img标签里 build之后也会将图片打包到build的img里面的，但是我在css里用background的时候我该怎么做呢 ？
我试过将import写入在jsx里面然后这样写（因为css最后编译到build里面的main.css同级目录为img）
background: url(./img/sidebar_arrow.png) no-repeat;
可是不行 报错，求一个解决方案

**Comment by zxuqian** [comment]
请问是怎么解决的？
