### ISSUE TITLE
model中的reducers、effects、subscriptions应该都怎么理解？

### ISSUE THREAD

**Issue by doterme** [dvajs/dva#802]
本人后端开发，react+es6+webpack+babel都了解一些，最新公司有个内部项目用了dva+antd，自己依葫芦画瓢把负责的东西写出来了，但是model中的reducers、effects、subscriptions，看文档说是elm-lang中的概念，我去elm-lang官网也没看到具体有用的信息，不知道是不是我没找到还是什么。Google之也没有更相近的资料，现在我有3个问题求解答。
1、我自己对subscriptions的理解就是订阅数据源，那我如果要订阅多个数据源要setup要怎么写？
2、reducers我的理解是同步更新state的操作，effects里面是异步操作。还是不清楚具体都有什么用，为什么这么设计。
3、前后端分离，后端的接口要怎么保证后端接口的安全性呢？

求赐教，不慎感激。

**Comment by zjxpcyc** [comment]
1、多次 dispatch
2、远程数据 -> effects 获取 -> reducers 更新 state -> 刷新组件
3、这个方法有很多，直接的用 session, 或者 每次请求 用 token ，网上应该有很多方法

**Comment by doterme** [comment]
@zjxpcyc 多谢

**Comment by OptimusYang** [comment]
是不是能这样理解,：

1.`effects`里面应该是比较单一的数据获取，比如写CRUD，就是四个effects。

2.然后`reducer`可能是一个复杂的业务操作，包含多个effects的调用或者多个reducer的调用，取其结果更新state。比如新增用户数据，需要新建机构，用户信息，用户权限，那么就可以调用三个effects： 
1. 新建机构
2. 新建用户
3. 新建用户权限


3.`subscriptions`的理解，我能理解为就是针对某一个module的一个初始化的工具，就等于是这个module和这段数据源是绑定的，如果是初始化状态就是load这些数据。 比如，一个下拉框里的值来自于后台的一个表里的定义数据，那么是不是subscriptions就可以dispatch一个公用的表获取的api，取到表里的数据，然后显示在下拉框中。


本人也是在初学，不知道理解的对不对。

**Comment by apersonw** [comment]
我的理解：
1.effects里面是多个操作的集合，如：页面正在加载数据，然后从服务器获取数据，页面数据加载完毕
2.reducer是一些列对状态的单操作保存，如修改state中的loading为true，修改state中的loading为false，这就是2个reducer
3.subscriptions是对地址也是路由的监控，订阅顾名思义就是订阅地址变化，相对于做出变化，发出dispatch
