### ISSUE TITLE
多页应用跳转

### ISSUE THREAD

**Issue by young-lam** [dvajs/dva#805]
配置了多页面，默认打开的是index.html页面，可以不可以配置例如是访问地址是//localhost/login时访问的时候是转向login.html

**Comment by CodingMonkeyzh** [comment]
如果是多页面， 必须配合服务端做路由映射

**Comment by zchuhui** [comment]
楼主有解决方案了吗？ 默认是index.html页面，那如今如可打开login.html页面？ 如何实现页面间的跳转？？
