### ISSUE TITLE
generator函数使用问题

### ISSUE THREAD

**Issue by tigaly** [dvajs/dva#807]
https://github.com/airbnb/javascript/blob/master/README.md 11.2上推荐现在不使用generator函数，但是dva框架里面还是在大量使用，不知道对这个问题大家怎么看呢？

**Comment by xufei** [comment]
redux-saga的核心就是基于generator的，dva是封装的redux-saga，只能用它……

**Comment by tigaly** [comment]
原来如此，感谢徐老师解说
