### ISSUE TITLE
关于权限？

### ISSUE THREAD

**Issue by phnessu4** [dvajs/dva#808]
Dva从设计上有没有能做模块权限的方法？或者开发上的demo？

现在的权限判断都是从路由层onEnter处理，有没有更好的处理方法？

或者与RBAC方式验证结合比较好的三方库？

**Comment by yqwoe** [comment]
同上需求

**Comment by phnessu4** [comment]
@yqwoe  自己写吧，不指望了

https://gist.github.com/iNikNik/1eabfc6bcc132384368c
