### ISSUE TITLE
组件内部的生命周期发起action，this.props.dispatch不能用了吗？

### ISSUE THREAD

**Issue by ca7pe** [dvajs/dva#810]
@sorrycc 
旧文档中提到的在componentDidMount中使用this.props.dispatch，好像不生效了，请问现在该怎么在生命周期中发起action？
[dva-docs/v1/zh-cn/tutorial/06-添加Reducers.md](https://github.com/dvajs/dva-docs/blob/master/v1/zh-cn/tutorial/06-%E6%B7%BB%E5%8A%A0Reducers.md)

> 知道了如何发起一个 action，那么剩下的就是发起的时机了，通常我们建议在组件内部的生命周期发起，如：
> ```javascript
> componentDidMount() {
> 	this.props.dispatch({
> 		type: 'model/action',
> 	});
> }
> ```

**Comment by nihgwu** [comment]
贴完整代码

**Comment by wuyunjiang** [comment]
可以啊，是否是定义组件的方式不对，使用无状态函数式的组件不会触发componentDidMount，也没有this关键字
