### ISSUE TITLE
新创建的App自动使用最新版React.js deprecated的问题

### ISSUE THREAD

**Issue by DickyT** [dvajs/dva#811]
目前已知会导致HMR无法使用
```
Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

目前解决方法是限制react的版本
```
"react": "15.4.2",
"react-dom": "15.4.2"
```

**Comment by pinggod** [comment]
针对这一问题，react-router 的 issue: https://github.com/ReactTraining/react-router/issues/4932

这里说会更新 react-router@3.x 版本的相关问题，那么 dva 内部引用的 react-router@2.8.1 已经半年多没有更新了，dva 是推动 react-router@2.x 版本的更新还是有切换到 react-router@3.x 版本的计划？

**Comment by DickyT** [comment]
@pinggod 我觉得dva切到react-router v4才是正道, 继续用3的话一直会落后react-router一个版本 总感觉不讨好

**Comment by phnessu4** [comment]
刚才看了下@pinggod 的连接，看样子这两个都是一个原因了。

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by pinggod** [comment]
@phnessu4 第一个 warning 有可能是其他第三方依赖的问题，比如如果你的项目使用了 antd，那么也会抛出这一个 warning。

**Comment by phnessu4** [comment]
@pinggod 不排除antd也有问题，antd还没独立看。刚才找了个dva的demo看了眼，一开始没添加antd的[commit](https://github.com/dvajs/dva-example-user-dashboard/commit/a59c5b9c7bd13bbf762d0fd5ee84a5519a02c81c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)就有问题。

**Comment by jmas** [comment]
+1
