### ISSUE TITLE
如何获取其他组件中的Form字段的值？

### ISSUE THREAD

**Issue by doterme** [dvajs/dva#813]
![image](https://cloud.githubusercontent.com/assets/12495369/24913810/ea18df84-1f04-11e7-8603-3f864c475afa.png)
![image](https://cloud.githubusercontent.com/assets/12495369/24913833/f75942ba-1f04-11e7-91b6-e39d22a375ee.png)

UserFileter是一个查询Form，我想在表格的页数改变事件中获取查询Form中的字段的值，求指教，谢谢。

**Comment by nihgwu** [comment]
这个跟 dva 有关系吗，求指教，谢谢

**Comment by doterme** [comment]
已搞定
