### ISSUE TITLE
异步路由run billd出来的0.0.js,2.2.js路径问题,提示子js需放在根目录，可能是什么原因

### ISSUE THREAD

**Issue by zyx4986** [dvajs/dva#819]
网站放在  dist目录下，然后0.0.js,2.2.js提示需要放在 /根目录下，这个可能是什么原因呢？

**Comment by helloyou2012** [comment]
@zyx4986 `webpack` 设置 `publicPath` 到相应的路径。

**Comment by zyx4986** [comment]
ok,搞定，用roadhogrc 设置publicPath='./'就可以了
