### ISSUE TITLE
多组件间如何交流

### ISSUE THREAD

**Issue by sunshinefull** [dvajs/dva#820]
如引入antd里的table，设置选择操作rowSelection复选框，table组件外有另外一个组件‘编辑’，如何实现table里的复选框选中时，点击‘编辑’时改变选中那行记录的值。

**Comment by nihgwu** [comment]
这个是 bug 吗？
这跟 dva 有关吗？

**Comment by sunshinefull** [comment]
不是bug，是需求，这个是常用的功能，网上基本找不到解决方案。用的是dva的状态管理，怎么会没关呢？

**Comment by nihgwu** [comment]
因为你用了dva，所以你遇到问题解决不了还要dva负责咯？🙃 建议好好理解下 redux
还有 **Issuse** 是用来 bug tracking 的，既然你都说这不是bug，那你开这个issue的意义是什么呢

**Comment by Syzmex** [comment]
redux:  view -> action -> reducer -> store -> view
so  comp -> action -> reducer -> store -> comp
如果嫌麻烦 [可以用这个库](https://github.com/Syzmex/GolbalStore/blob/master/dispenser.js)
我还没写完但是可以用，自己拷贝过去用
大概原理是：一个组件监听数据，另一个组件发送数据
