### ISSUE TITLE
tomcat和dva怎么配合使用？

### ISSUE THREAD

**Issue by yipanbo** [dvajs/dva#821]
大神好，最近遇到个问题，想要把dva和tomcat配合使用，做到前后分离。tomcat只提供api，只返回json。前台dva build之后，放到dist文件夹中，然后把dist文件放入后台项目，启动tomcat访问。
现在的问题是，dva中有route，但是我怎么跳转到首页呢？
可能这个问题会有点小白了，但是还是求大神指点，谢谢！

**Comment by dicklwm** [comment]
dva的route是前端路由，单页面应该都是通过前端路由来控制的，既然你是前后分离的话，服务端只要提供接口数据就可以了，路由控制都是在前端管理的，建议你看一下[阮一峰的react-route@2.x.x](http://www.ruanyifeng.com/blog/2016/05/react_router.html)的文章，dva的react-route是@2.x.x，现在官方已经推出@4.x.x，所以记得不要看错文档了

**Comment by yipanbo** [comment]
@dicklwm 非常感谢！
有点启发，我刚才看了nginx，发现好像是可以满足我现在的需求的。
具体就是：
在nginx中配置nginx.conf文件，
location / {
    root myProject/dist
    index index.html
},
location ~*.do$ {
    proxy_pass http://location:8080
}
这样访问某个服务器时，直接访问到index.html页面，接口数据通过nginx反向代理tomcat。
以上是我的一点想法，有什么不对的地方请指正，谢谢！

**Comment by yipanbo** [comment]
@sorrycc  求大神给我想法做个点评，没有问题的话，我会推广这样的做法，帮助其他的一些小白，谢谢！
