### ISSUE TITLE
依赖的react-router版本低

### ISSUE THREAD

**Issue by sunganyu** [dvajs/dva#822]
依赖的react-router版本低，react版本15.5.0以后出现警告：
[https://github.com/callemall/material-ui/issues/6542](https://github.com/callemall/material-ui/issues/6542)
react-router在最新版4.4.1已经解决该问题。
[https://github.com/ReactTraining/react-router/commit/ef2f8f90d6243d007b32f262e1215a5d40f0577b](https://github.com/ReactTraining/react-router/commit/ef2f8f90d6243d007b32f262e1215a5d40f0577b)

**Comment by jiangbo2015** [comment]
## 升级了react-router 警告依然存在
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`
`Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

**Comment by sunganyu** [comment]
我现在的解决办法是在package.json中将我的项目依赖的react版本指定为“ "react": "~15.4.1",  ”（主版本号和次版本号不变，即15.4.X）；
最后实际安装的版本为react@15.4.2，警告消除。

**Comment by momogugu** [comment]
react的版本指定以后，还要指定react-router的版本吧
我之前的react-router版本就指定需要更高版本的react
两个都指定以后就不会提出警告了。
dva@1.3版本好像也还没有正式发布。

**Comment by YouNoCanNoBB** [comment]
Ok perfect, thanks for the clarification.

**Comment by gafish** [comment]
dva@1.3.0-beta2 依旧没解决这个问题，引用的版本还是 "react-router": "^2.8.1",

**Comment by DanielWLam** [comment]
暂时解决而已吧，关键还是要DVA升级版本？

**Comment by sumlight** [comment]
dva好久没升级了啊!

**Comment by afc163** [comment]
+1 可以无缝升级到 react-router@3.x 。
