### ISSUE TITLE
router里面可以获取state吗？

### ISSUE THREAD

**Issue by a755956503** [dvajs/dva#827]
比如跳转前获取isLogin,判断是否能跳转进去

**Comment by iceshu** [comment]
你可以这样 吧需要登录的页面放在一个路由里 顶级就是你的根路由 然后在里面判断是否登录

**Comment by a755956503** [comment]
嗯，后面也看到了，app里面可以拿到store,我直接getState了

**Comment by liuyulin666** [comment]
> 嗯，后面也看到了，app里面可以拿到store,我直接getState了

怎么拿到的呀  能具体说下吗 谢谢
