### ISSUE TITLE
whatwg-fetch并不支持IE9

### ISSUE THREAD

**Issue by codering** [dvajs/dva#83]
看官方文档，最新的whatwg-fetch并不支持IE9
https://github.com/github/fetch#browser-support
https://github.com/github/fetch/issues/326

**Comment by sorrycc** [comment]
感谢反馈，还没注意到这一点，我在 README 上提下。`dva/fetch` 不是必须的，如果要支持 IE9，可自行替换为其他的 http 处理库。http://andrewhfarmer.com/ajax-libraries/
