### ISSUE TITLE
model 的疑问

### ISSUE THREAD

**Issue by xoptimal** [dvajs/dva#831]
在编写 model的过程中, 发觉越来越多的 model 的代码是差不多, 只有参数不同,

但是由于 model 返回是一个对象,  我想请教下, 如果封装一个model , 让别的model 继承成呢 0.0

我记得前阵子有看到类似的提问,  我现在找不到了 (还是我记错了) .....

**Comment by xoptimal** [comment]
主要涉及到 model 的优化 ~

**Comment by dicklwm** [comment]
民工叔叔整理的文档，可以参考一下 https://github.com/dvajs/dva-example-user-dashboard/pull/15

**Comment by xoptimal** [comment]
@dicklwm  感谢, 就是这篇文章 !
