### ISSUE TITLE
can we init dva instance with custom store instance

### ISSUE THREAD

**Issue by daskyrk** [dvajs/dva#832]
i found a library(redux-auth-wrapper) to realize authentication, and the library need to init both store and history before using them;
```
// import some libraries

const store = createStore(reducer, enhancer)
const history = syncHistoryWithStore(browserHistory, store)

ReactDOM.render(
  <Provider store={store}>
    <div>
      <Router history={history}>
        <Route path="/" component={App}>
          <IndexRoute component={Home}/>
          <Route path="login" component={Login}/>
          <Route path="foo" component={UserIsAuthenticated(Foo)}/>
          <Route path="admin" component={UserIsAuthenticated(UserIsAdmin(Admin))}/>
        </Route>
      </Router>
      <DevTools />
    </div>
  </Provider>,
  document.getElementById('mount')
)
```
but the store is created inside `dva.start()` so i can't use the prepared store instance to init app with `new dva(ops)`.
is there a way to set custom store instance to dav instance?

**Comment by nihgwu** [comment]
`app. _store`

**Comment by daskyrk** [comment]
@nihgwu should i use the inner obj `app._store` to init history, and set the history to `app._history`? it seems a little weird...
