### ISSUE TITLE
组件是用es6的写法是否合理

### ISSUE THREAD

**Issue by jindada** [dvajs/dva#838]
之前一直都是用model的state控制应用的所有状态，但是发现全局状态树变得很大。
现在我想把异步，公用的状态放在model的state里面，把一些只有组件本身用到的属性放到state里面，这样的写法是否合理

**Comment by MrCuriosity** [comment]
我觉得挺合理的，我就是这样做的，只是要看状态和数据的抽象好不好

**Comment by jindada** [comment]
@MrCuriosity 我就担心会很乱 开发维护的成本加大

**Comment by ymjrcc** [comment]
我就是这样做的，而且我记得作者也说过没有强制要求用stateless component，可以合理使用class的方法生成组件。自己掌控好就好啦。

**Comment by zjxpcyc** [comment]
我现在是这样做的， model 中的 state 基本没有 状态控制的属性，大部分是 业务数据。

状态控制的属性，比如模态框的显示之类的，是放到 model 中。其余的基本都是用 class 封装的组件里面的。

我现在的常规写法， component 目录里面的组件大部分是 class 封装写法， routes 下面的都是 es6 箭头函数

这种解决之后，每个 model 中的 state 基本上只有 4, 5 个属性。也没有出现，我之前 一个 model state 一堆 属性的问题
