### ISSUE TITLE
build后，放在服务器，显示空白，控制台也不报任何错，请问是什么回事？

### ISSUE THREAD

**Issue by hst-Sunday** [dvajs/dva#841]
如题，是哪里配置不对吗？

**Comment by jindada** [comment]
你应该是缺少html文件吧

**Comment by hst-Sunday** [comment]
打包出来的有index.html   index.js   index.css 啊，把这三个文件放在服务器上没反应

**Comment by leek120** [comment]
配置文件 publicPath": "/appname/"
appname 是你的应用在服务器上的应用名,  即 xx.com/appname

**Comment by hst-Sunday** [comment]
@leek120 试了也无效，还有什么原因吗？

**Comment by sorrycc** [comment]
给的信息太少，判断不出啥原因。

**Comment by hst-Sunday** [comment]
![image](https://cloud.githubusercontent.com/assets/18478530/25310973/c87c4dfa-2825-11e7-9349-a967a6b9a2d6.png)
![image](https://cloud.githubusercontent.com/assets/18478530/25310979/00ac664c-2826-11e7-9ce1-104cb8485ab6.png)
我想放在这个服务器的这个文件夹里，在浏览器访问www.test.com/index2.htm的时候显示出来，现在我的配置文件如下
![20170423125636](https://cloud.githubusercontent.com/assets/18478530/25310945/fd57e71a-2824-11e7-9bd6-7cca6bc7d904.png)
已修改为"publicPath" : "/www.test.com/",打包上传，访问www.test.com/index2.html显示空白，控制台也不报任何错

**Comment by bobyuxinyang** [comment]
我也遇到类似的问题，我发现是是如下图window.location = '/login'，这里404了
dev时候ok，build后，放在服务器下面就会有这个问题

![image](https://cloud.githubusercontent.com/assets/1063822/25332210/345373ee-2918-11e7-83a4-30309678788a.png)

我尝试改成使用window.history.replaceState，结果在routes/app.js中使用location.pathname判断openPages失效
有点摸不着头脑，暂时还没解决

**Comment by icodytan** [comment]
提供的信息比较少，不知道是不是之前我遇到的输出路径问题，可以把 “publicPath”: "/"  修改为 “publicPath”: "./"  试试

**Comment by hst-Sunday** [comment]
@icodytan 这个也已经试过，请问还需要提供什么信息？

**Comment by icodytan** [comment]
看你上面的截图，没有 index.html，只有 index2.html
你打开 index2.html 文件，看看有没引入 index.css、index.js

**Comment by hst-Sunday** [comment]
@icodytan 打开了，Script、LINK标签引入了，你看下
![image](https://cloud.githubusercontent.com/assets/18478530/25488103/bb1617ba-2b98-11e7-9cc5-953a82ef6d7e.png)

**Comment by hst-Sunday** [comment]
解决了，服务器识别不了browserhistory，改为hashhistory就可以，有谁用browserhistory部署的，可以的话告诉我一下怎么用

**Comment by Jimi6** [comment]
@hst-Sunday 遇到同样问题；现在可以正常用browserhistory部署吗

**Comment by hst-Sunday** [comment]
@Jimi6 现在可以了的
