### ISSUE TITLE
如何在dva models 里面injectIntl

### ISSUE THREAD

**Issue by hightall** [dvajs/dva#847]
想在models里面使用react-intl国际化，但不知道怎么在models里面使用语言格式化，intl变量无法传入，希望指点。首先无法利用IntlProvider, 是不是可以通过injectIntl把intl传入models，使用国际化？

**Comment by Thomas080304** [comment]
似乎没有解决在model里面国际化的问题，怎么就关闭了这个issues?

**Comment by wefine** [comment]
我的解决方法是在某个组件里面，以window.intl的方式把intl对象保存为全局然后在model里面使用，不知正宗的处理方式是什么。
