### ISSUE TITLE
使用dva-cli本地roadhog启动server,设置为browserHistory，路由参数问题

### ISSUE THREAD

**Issue by springxiege** [dvajs/dva#849]
dva配置history如下：
``` js
const app = dva({
  history: browserHistory
})
```
然后路由设置如下：
``` jsx
<Route path="CampaignDetail/:id" component={CampaignDetail} />
```
最终编译后，在浏览器上查看，生成结果多了一层目录，如下图：
![f9a1a2f8-21e1-4c38-879c-a9338682718f](https://cloud.githubusercontent.com/assets/8267675/25300752/63b07e96-2749-11e7-9f0c-00eb8cef4264.png)

请问这个有额外配置能解决这个问题吗？
@sorrycc

**Comment by sorrycc** [comment]
script 引用路径改成 `/index.js` 吧。

**Comment by springxiege** [comment]
已经解决，谢谢 @sorrycc
