### ISSUE TITLE
dva 支持 SSR (服务端渲染)

### ISSUE THREAD

**Issue by lobinroromens** [dvajs/dva#85]
有没有关于dva服务端的实现方案

**Comment by sorrycc** [comment]
你指服务器端渲染?

**Comment by zpz1982** [comment]
我也想知道如何做服务器端渲染，能增加一个这样的例子吗？或者如何和其他已经实现服务器端渲染的脚手架做整合，比如react-redux-universal-hot-example

**Comment by lobinroromens** [comment]
@sorrycc 是想要了解服务端渲染方面的案例

**Comment by lobinroromens** [comment]
@zpz1982 给的例子不错研究一下

**Comment by sorrycc** [comment]
还在调研中，实现上理论上可行，因为背后依赖的 redux 和 react-router 都支持 SSR 。需要花时间考虑下如何整合以及 api 的设计。

**Comment by sorrycc** [comment]
试了下，发现 SSR 无需特殊处理，基于 dva@1.1 已可实现客户端和服务端在 components, routes 和 services 的共享。
https://github.com/sorrycc/dva-boilerplate-isomorphic

**Comment by vince-fly** [comment]
@sorrycc 打包出来之后，文件没有分离，`<Route exact path="/" component={require('./routes/IndexPage')} />`，不过没有分离出来单独的文件，dll.js文件更大，达到了4.5MB。。。
哪方面做优化？

**Comment by sorrycc** [comment]
build 出来怎么会有 dll? dll 是 dev 时用的。

**Comment by skyFi** [comment]
好像之前有弄过一个，提供一种思路：https://github.com/skyFi/dva-starter
