### ISSUE TITLE
react-redux@4 & react-router@2 导致 react15.5.4 出现 Warning

### ISSUE THREAD

**Issue by lishengzxc** [dvajs/dva#851]
![dingtalk20170422210810](https://cloud.githubusercontent.com/assets/12003270/25304733/d372dcfa-279f-11e7-958f-fb7922dbbf16.png)

**Comment by Rockcookies** [comment]
希望能解决该问题，升级react-router到4版本

**Comment by lishengzxc** [comment]
@Rockcookies 感觉 react-router@v4 不是很紧急，因为 API 改动过大，react 似乎是需要更新的

**Comment by OshotOkill** [comment]
React 15.5 将 `createClass` 和 `propTypes` 剥离并单独打包发布到 npm 上了，希望开发者能跟进。

**Comment by zheeeng** [comment]
+1

**Comment by markfredchen** [comment]
升级版本也没有用。@Rockcookies 现在有计划更新吗?

**Comment by not3** [comment]
希望这个warning能处理掉，强迫症很讨厌呀

**Comment by gafish** [comment]
每次都要看到这个报错，也不知道什么时候能修复
