### ISSUE TITLE
不同的model之间的effect能互相调用吗？

### ISSUE THREAD

**Issue by yeelone** [dvajs/dva#852]
你好，第一次发issues，实在搞不懂。求指教。

比如有一个group model ,一个 user model ,
在user model里，有

`
*query ({ payload }, { call, put }) {
      console.log(payload)
      const data = yield call(query, parse(payload))
      var page = {
        total: data.body.total ,
        current: Number(payload.page),
        pageSize: Number(payload.pageSize)
      } 

      if (data) {
        yield put({
          type: 'querySuccess',
          payload: {
            list: data.body.users,
            pagination:page,
          },
        })
      }
    },`

然后在group model里， 我有一个需求，就是组 会弹出一个对话框以供选择用户然后添加进组里。那么，我想在组触发添加 用户的对话框时，先请求所有用户的数据 ，代码如下：

` 
*queryUsers({ payload }, {select,call,put }){
        yield put({ type: 'showSelector'})
        const data = yield call(queryRelatedUsers, parse({id:payload}))
        const page = { page: 1, pageSize:9999  }

        // 第一种方案，发起 usersQuery 的service 
        // const usersdata = yield call(usersQuery, parse(page))
        
        // if (usersdata) {
        //   console.log(usersdata.body.users) 数据是请求到了，但是以下的put 没有执行啊，为什么呢？用法错了？
        //   yield put({
        //     type: 'users/querySuccess',
        //     payload: {
        //       list: usersdata.body.users,
        //     },
        //   })
        // }

        yield put({type:'users/query', payload:{page:1,pageSize:100}}) //这里也没有执行到user model 里的effect 
        const users = yield select(({users}) =>  users ) 
        if ( data && data.success ){
          yield put({
            type: 'queryUsersSuccess',
            payload:{
                relateUserList: data.body.group.users
            } 
          })
        }
    },`

结合以上代码，我想问的是，不同的model之间，能互相调用effect吗？怎么调用？

**Comment by nihgwu** [comment]
namespace搞错了还是没有注册？

**Comment by yeelone** [comment]
有注册，我在UserList.js 里调用user model就可以，但是在 group 里put user model就没有效果。

**Comment by yeelone** [comment]
奇怪的是，我先渲染 userlist ，此时先渲染了user model，再打开group 进行put({type:"users/query"}) 就有效果。而如果在group 列表页面直接刷新，此时就无法put 成功。为什么呢？

问一下大家，要重现代码，大家是用jsfiddle还是什么？

**Comment by xufei** [comment]
看描述有些像没有注册namespace啊，是不是路由用了model的懒加载？

**Comment by yeelone** [comment]
@xufei  你好，我的路由是这样的：
`
const cached = {}
const registerModel = (app, model) => {
  console.log(model)
  if (!cached[model.namespace]) {
    app.model(model)
    cached[model.namespace] = 1
  }
}

const Routers = function ({ history, app }) {
  const routes = [
    {
      path: '/',
      component: App,
      getIndexRoute (nextState, cb) {
        require.ensure([], require => {
          registerModel(app, require('./models/dashboard'))
          cb(null, { component: require('./routes/dashboard/') })
        }, 'dashboard')
      },
      childRoutes: [
        {
          path: 'users',
          getComponent (nextState, cb) {
            require.ensure([], require => {
              registerModel(app, require('./models/users'))
              cb(null, require('./routes/users/'))
            }, 'users')
          },
        },{
          path: 'groups',
          getComponent (nextState, cb) {
            require.ensure([], require => {
              registerModel(app, require('./models/groups'))
              cb(null, require('./routes/groups/'))
            }, 'groups')
          },
        },{
`

是不是我在直接刷新 groups页面时，就没有加载到users model ?

**Comment by xufei** [comment]
是的，你要这样的话，users model就在外面直接加载比较好，不要在路由里面搞。

路由这段里，只适合处理`仅在本路由有用的东西`

**Comment by yeelone** [comment]
@xufei 谢谢你的解答，我明白了。感觉这样局限性很大啊。我再重头看看。
