### ISSUE TITLE
model 方法的定义疑问

### ISSUE THREAD

**Issue by xoptimal** [dvajs/dva#856]
现在我写了一个基类 model, 关键代码:

```
export const = FuModel{
....
effects : {
  *request({payload}, {call, put, select}){
      const result = yield requestService();
  }
}
```

然后, 自定义一个Model , 继承基类 ~

通过这个继承: import modelExtend from 'dva-model-extend';

```
export default modelExtend(FuModel, {

//  我该如何实现 requestService 方法
}
```

**Comment by zjxpcyc** [comment]
没看懂你什么意思。

requestService  跟 继承没有什么关系吧？  

requestService  就跟正常的 service 一样写，难道不行？

**Comment by xoptimal** [comment]
我在父类的 effects 下 写了一个通用的 request 方法,  该方法里有个requestService 需要实现,  然而我在子类定义了 requestService 方法, 但是它并不会指向它 ~  look me code:

```
FuModel.js:

	export const = FuModel{
	....
	effects : {
	  *request({payload}, {call, put, select}){
	      const result = yield requestService();
	  }
	}


ZiModel.js: 

	requestService(){
		console.log("I came in");
	}

	export default modelExtend(FuModel, {

	//  我该如何实现 requestService 方法
	}
```

**Comment by zjxpcyc** [comment]
这种方式应该是不可以的。你需要把  requestService 抽象出来，放到其他地方，然后再  import 或者 require 进来。

实现的时候，requestService  应该返回的是一个 promise ，用 call 来调用。 直接跟在 yield 后面好像不行。

**Comment by vonxq** [comment]
可以看看这个https://github.com/dvajs/dva-model-extend/issues/1
