### ISSUE TITLE
action 能否被多个 reducer handle??

### ISSUE THREAD

**Issue by as02700** [dvajs/dva#857]
如果 action.type 是 [namespace]/[reducer-function-name] 的格式，是不是意味着一个 action 只能有一个 reducer 处理呢？如果一个 action dispatch from user，state 下有2个没有引用关系的数据要更新。又要怎样处理啊？（应该是说怎么广播到多个reducer）

**Comment by nihgwu** [comment]
把这个 reducer 写成 effects，然后在 effects 里面 put 相应的 reducers

**Comment by as02700** [comment]
@nihgwu 即使不需要执行副作用的情况下也只能这样实现吗？

**Comment by xufei** [comment]
也可以用take做，这样不用修改原来的代码
