### ISSUE TITLE
在RN项目里安装dva报错UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by sumlight** [dvajs/dva#859]
使用create-react-native-app创建的RN项目, 通过命令`npm i dva --save`进行安装, 然后就出现了:
`UNMET PEER DEPENDENCY react-dom@15.x`
`npm WARN dva@1.2.1 requires a peer of react-dom@15.x but none was installed.`

**Comment by nihgwu** [comment]
安装 dva@1.3.0-beta.3

**Comment by sumlight** [comment]
安装1.3.0-beta.3成功! 多谢nihgwu及时指点!
