### ISSUE TITLE
antd-admin (Demo)，ie访问http://localhost:8000的时候路径会有大量的undefined   ie路径：http://localhost:8000/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/login?from=/undefined/undefined/undefined/undefined/undefined/undefined/undefined/login

### ISSUE THREAD

**Issue by zhangjingge** [dvajs/dva#861]
antd-admin (Demo)，基于 antd 和 dva 的后台管理应用
ie访问的时候路径会变为：
http://localhost:8000/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/login?from=/undefined/undefined/undefined/undefined/undefined/undefined/undefined/login

**Comment by dicklwm** [comment]
这是antd-admin的问题，到antd-admin提issue去吧 https://github.com/zuiidea/antd-admin/issues
