### ISSUE TITLE
请问有没有基于mock（.roadhogrc.mock.js）的最佳实践

### ISSUE THREAD

**Issue by 18559909452** [dvajs/dva#865]

**Comment by songqiaoyi** [comment]
let mock = {}
let fs = require('fs');
let join = require('path').join;

let result=[];
function finder(path) {
    let files=fs.readdirSync(path);
    files.forEach((val,index) => {
        let fPath=join(path,val);
        let stats=fs.statSync(fPath);
        if(stats.isDirectory()) finder(fPath);
        if(stats.isFile()) Object.assign(mock, require(fPath))
    });

}
finder(join(__dirname + '/mock'));

module.exports = mock;

**Comment by xiaohuoni** [comment]
我觉得这个更好一点
```js
const mock = {}
require('fs').readdirSync(require('path').join(__dirname + '/src/mock')).forEach(function(file) {
	Object.assign(mock, require('./src/mock/' + file))
})
module.exports = mock
```
配置完，直接访问src/mock/下的对应文件 ，代码来源https://github.com/zuiidea/antd-admin

**Comment by zjjjjjjjjjjd** [comment]
同一个借口存在proxy代理的情况下是否使用mock无效
