### ISSUE TITLE
求助：react 子组件渲染是同步阻塞的，有办法改成异步的么？

### ISSUE THREAD

**Issue by zllc** [dvajs/dva#866]
比如一个parent组件，有500个子组件，我试了下这500个组件的shouldComponentUpdate方法是顺序阻塞调用的，如果子组件比较多，会浪费很多时间，有没有办法改成异步？

**Comment by xufei** [comment]
这个问题跟dva没有关系啊。。。

**Comment by zllc** [comment]
嗯  求助一下大神
