### ISSUE TITLE
可以使用material-ui吗？

### ISSUE THREAD

**Issue by hziee514** [dvajs/dva#867]
如果不用antd，可以用material-ui吗？

**Comment by nihgwu** [comment]
在提问之前先试一试是个好习惯

**Comment by hziee514** [comment]
@nihgwu 就问理论上能不能支持，我试了几下没折腾出来。

**Comment by nihgwu** [comment]
理论上肯定支持，实际上也支持，dva有没有跟任何ui库绑定

**Comment by hziee514** [comment]
@nihgwu 之前是在旧项目上乱搞，建一个新的工程从头开始就好了
