### ISSUE TITLE
使用proxy代理post请求跨域问题 

### ISSUE THREAD

**Issue by springxiege** [dvajs/dva#868]
我使用的roadhog来启动我的服务，然后我开启了代理，代理配置如下：
``` js
proxy:{
    "/api/*": {
        "target": "代理指向的地址",
        "changeOrigin": true,
        "secure":false,
    }
}
```
上面的代理我可以GET到线上的数据，可是PUT,POST等请求都报跨域错误，然后查阅了webpack里面的proxy配置，配置后仍然无效，请问这里有其他配置可以使PUT,POST 等请求成功吗？

**Comment by zjxpcyc** [comment]
需要设置 HOST


```
    "/api": {
      "target": "http://127.0.0.1:8080/",
      "headers":{

               "host":"127.0.0.1"
      }
    },
```

**Comment by springxiege** [comment]
这个问题解决了，除了设置以上配置之外，还要加上"origin": ""属性

**Comment by mei50923** [comment]
"/api": {
      "target": "http://ljj.dev.neoteched.com/",
      "changeOrigin": true,
      "secure":false,
      "headers":{
               "host":"ljj.dev.neoteched.com"
            },
            "origin":"http://ljj.dev.neoteched.com"

    }这样设置对吗，我的还是不行呢

**Comment by mei50923** [comment]
还需要配置其他地方吗@springxiege

**Comment by mei50923** [comment]
访问接口一直报404

**Comment by RisingSunYZ** [comment]
兄弟 解决了吗 我post也一直报404 get就ok

**Comment by RisingSunYZ** [comment]
dva2.23 post请求 后台接收不到参数啊？

**Comment by springxiege** [comment]
the valid config
``` js
"/api": {
      target : ‘http://localhost’,
        changeOrigin: true,
        ws: true,
        secure: false,
        pathRewrite: { "^/api": "" }
    },
```

**Comment by lzp979822781** [comment]
请问最后的post请求body传参问题是怎么解决的？

**Comment by zhanglong11** [comment]
> 访问接口一直报404
你的解决了吗
