### ISSUE TITLE
刷新浏览器时，parent route数据为空

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#87]
这个问题上次提过了，我仔细测试后发现这个问题确实存在，我详细描述下：
```
<Route path='main' component={MainPage}>
      <Route path='person' component={PersonPage}/>
</Route>
```
MainPage负责获得菜单数据，PersonPage负责获取人员列表。
地址栏访问：http://127.0.0.1:8989/#/main时刷新浏览器没问题。

地址栏访问：http://127.0.0.1:8989/#/main/person时，只要f5刷新时，main的数据丢失，我断点看也是丢失。

我后来想，要是把MainPage做成组件，在mount事件获取数据也许就没问题了，因为刷新浏览器这个事件会触发。如果不用组件，还有没有其它办法？

另外，我还是希望能够在某个connect的route页面unmount的时候，主动清除它的数据。我现在写在history.listen里面的。

**Comment by sorrycc** [comment]
没能完全理解你的问题，提供个能重现问题的库?

**Comment by bjwulin** [comment]
@sorrycc ，类似这个问题：http://stackoverflow.com/questions/35335883/react-redux-sttate-changed-to-initial-after-browser-refresh

**Comment by nikogu** [comment]
@bjwulin 我觉得你就使用react生命周期方法就好了，不用非要用history.listen...

**Comment by bjwulin** [comment]
@nikogu ，我是看看 @sorrycc 的dva有没有更优雅的办法。dva确实很赞。

**Comment by sorrycc** [comment]
理解了下这个问题，应该是访问 main/person 时没有加载菜单的数据，所以要调整下加载菜单数据的逻辑，比如 pathname 满足有 main 前缀时而不是等于 main 时加载。

**Comment by bjwulin** [comment]
@sorrycc ,这样就不合算了，每次都请求服务器获得菜单数据，不合算，只是刷新浏览器才出问题，其它点击菜单都正常。

**Comment by sorrycc** [comment]
设置只请求一次不就好了。。

**Comment by bjwulin** [comment]
@sorrycc ，还是不明白怎么做。

**Comment by sorrycc** [comment]
@bjwulin 比如有个 menu 的 model：

```js
app.model({
  namespace: 'menu',
  subscriptions: {
    setup({ dispatch, history }) {
      function loadDataOnce() {
        dispatch({ type: 'loadAsync' });
        loadDataOnce = function(){};
      }
      history.listen(loadDataOnce);
    },
  },
});
```

**Comment by bjwulin** [comment]
谢谢@sorrycc，我写成这样就可以了：
setup({ dispatch, history }) {
      const loadDataOnce = (function() {
        let executed = false;
        return function () {
          if (!executed && location.hash.includes('/main')) {
            executed = true;
            dispatch({type:'getLoginedInfo'});
          }
        };
      })();
      history.listen(loadDataOnce);
    },

**Comment by sorrycc** [comment]
```js
setup({ dispatch, history }) {
  function loadDataOnce() {
    if (location.hash.includes('/main')) {
      dispatch({ type: 'loadAsync' });
      loadDataOnce = function(){};
    }
  }
  history.listen(loadDataOnce);
},
```
