### ISSUE TITLE
在subscription

### ISSUE THREAD

**Issue by zhangshihuann** [dvajs/dva#873]
有个问题请教下

我想在`dva`中用`redux-thunk`来支持异步`action creator`函数，主要目的是用来封装一次fetch函数，在请求的发生的时候根据请求返回值调用`dispatch`来更新state

不过发现在`dva`中的无论是`model`中`subscriptions`还是`effects`，`dispatch`和`put`都被封装过一次了，在这里就拦截了`action`不是`object`的情况，`redux-thunk`生效不了，请问改怎么让`redux-thunk`生效？

![image](https://cloud.githubusercontent.com/assets/5877964/25555806/89223c12-2d22-11e7-9d34-786ae680121c.png)
![image](https://cloud.githubusercontent.com/assets/5877964/25555828/e884a776-2d22-11e7-8d33-56f86ef12216.png)

**Comment by Menq** [comment]
请求返回值更新数据是在model里面的reducers做的吧
