### ISSUE TITLE
感觉是dva的bug，请解答一下

### ISSUE THREAD

**Issue by sun4j** [dvajs/dva#874]
使用dva创建项目后，按照12步30分钟中的第4步创建的users路由，之后都是按照步骤完成的，页面可以正常显示，但是我修改routes/Users.css 文件后，routes/Users.js 文件就变成了 引入react-native的东西了，只要我修改样式，自动就给我把文件中的内容替换了，然后编译报错！

**Comment by pengfeiWang** [comment]
我记得  vscode 有插件会做这种事, 如果是vscode 的话 找到插件, 禁用后在试试

**Comment by sun4j** [comment]
好的 我试试 谢谢了  另外项目发布只能是根目录发布吗 感觉带个目录会更好 那怎么配置

**Comment by zhoulaiqing** [comment]
Vscode 的 code-react-instyle 插件造成的。禁用就好了。
