### ISSUE TITLE
dva的roadhog server占用cpu很高

### ISSUE THREAD

**Issue by MedusaLeee** [dvajs/dva#877]
经测试roadhog server在node的v7.9.0上占用cpu很高，达到120%.

系统： mac sierra 10.12.4 
node版本： v7.9.0
dva版本：1.2.1

在node v7.7.1上cpu占用正常

**Comment by nihgwu** [comment]
为什么不去roadhog提

**Comment by MedusaLeee** [comment]
@nihgwu 抱歉，我以为dva和roadhog是一起的呢

**Comment by MedusaLeee** [comment]
以在roadhog提交issue:  https://github.com/sorrycc/roadhog/issues/237
