### ISSUE TITLE
Is it possible to call an effect from another effect?

### ISSUE THREAD

**Issue by Tsury** [dvajs/dva#878]
Or at least fire an action from within an affect?

**Comment by sorrycc** [comment]
`yield put(action)` ?

**Comment by Tsury** [comment]
It's not working for me. To make sure, I am trying to call **an effect from another effect**. No reducers involved.

**Comment by xufei** [comment]
```JavaScript
yield put({ type: 'anotherModel/effectA', payload: 111 })
yield put({ type: 'effectInSameModel', payload: 222 })
```

**Comment by Tsury** [comment]
For some reason this is not working for me. Nothing happens.
If I take the dispatch function and call it then it works...
