### ISSUE TITLE
采用dva全局onError处理错误后，怎么处理model的状态

### ISSUE THREAD

**Issue by bjwulin** [dvajs/dva#88]
比如，用antd的table，获取服务端数据，但是获取过程失败，这个时候我让dva的onError显示错误信息，但是我也希望同时更改状态的loading为false。

我现在是判断返回data，如果为空，则put改loading的action，不好的地方是每个地方都要写这样的代码。
有没有更优雅的做法？

**Comment by sorrycc** [comment]
方案一：

```javascript
try {
  ...
} catch(e) {
  // passed to onError hook
  throw new Error(errorMsg);
}
yield put({ type: 'hideLoading' });
```

方案二：
https://github.com/dvajs/dva-loading

**Comment by bjwulin** [comment]
我采用方案二，不错的方案。赞。
