### ISSUE TITLE
dva如何处理下载的response呢？

### ISSUE THREAD

**Issue by zyx4986** [dvajs/dva#881]
yield call(download) 前台应该怎么响应呢？

**Comment by forever4313** [comment]
跟dva无关，我用的是file-saver 类似如下写法

function downloadFile(payload) {
    doGetFile(payload.downloadUrl, payload.params).then((data) => {
        FileSaver.saveAs(data, `${payload.storeNameAndSuffix}`);//将返回的数据 存储为文件。
        return true;
    });
}

**Comment by zyx4986** [comment]
搞定，用了file-saver
import FileSaver from 'file-saver'
export default function export(url,options)
{
    return fetch(url,options).then(function(response){
    return response.blob()
    }).then(function(blob){
     FileSaver.saveAs(blob,`newFile.${`exl`}`) 
    })
}
