### ISSUE TITLE
How to organize nested children routes?

### ISSUE THREAD

**Issue by oluckyman** [dvajs/dva#884]
I have a component for parent route and a component for child route. What is the better way to organize file structure?
### Nested structure
```
  const routes = [{
    path: '/',
    component: App,
    childRoutes: [{
      path: 'users',
      component: require('~/routes/Users'),
      childRoutes: [{
        path: ':user',
        component: require('~/routes/Users/User'),
      }],
    }],
  }];
```
the drawback is that `/Users` folder can contain more than one component:
```
/routes
   /Users
      UserListTable/
      User/
```
And it’s not obvious which is the route component

### Flat structure
```
  const routes = [{
    path: '/',
    component: App,
    childRoutes: [{
      path: 'users',
      component: require('~/routes/Users'),
      childRoutes: [{
        path: ':user',
        component: require('~/routes/User'),
      }],
    }],
  }];
```
this way each route is clearly separated, but it’s not obvious that `User` route is nested into `Users`..

Any best practices how to do this?

**Comment by feibi** [comment]
it work?

**Comment by Kunoky** [comment]
function RouterConfig({ history }) {
  return (
    <Router history={history}>
      <Route path="/" component={Test}>
          <Route path="users" component={Users} >
              <Route path="user" component={User} />
          </Route>
      </Route>
    </Router>
  );
}

**Comment by Kunoky** [comment]
`function RouterConfig({ history }) {
  return (
    <Router history={history}>
      <Route path="/login" component={Login} />
      <Route path="/" component={Test}>
        <IndexRoute component={User} />
        <Route path="" component={User} />
        <Route path="upload" component={Uploadcomp} />
        <Route path="log" component={Log} />
      </Route>
    </Router>
  );
}`
