### ISSUE TITLE
嵌套路由无法使用

### ISSUE THREAD

**Issue by mike8625** [dvajs/dva#885]
示例中没有嵌套路由的代码
然后我找了react router阮老师的文章 

```
>     <Router history={history}>
>       <Route path="/" component={IndexPage} >
>           <Route path="/about" component={AboutPage} />
>       </Route>
>     </Router>
```

发现输入/#/about 的时候 无法跳转 还是停留在一开始的页面

**Comment by Lulicai** [comment]
请问解决了吗，我也遇到这个问题。。。

**Comment by mike8625** [comment]
没有,放弃了,还是用jq做多页的了

**Comment by Lulicai** [comment]
我这边已经解决，少了IndexRoute,
![69418116-6126-4431-9289-18215ef78195](https://user-images.githubusercontent.com/23206872/27778595-a3d3bd5c-5fee-11e7-817e-1dce2e70fd94.png)
我想你那边应该也是这个问题，但是时间太长我不记得具体什么原因了

**Comment by mike8625** [comment]
十分感谢,这回知道了
