### ISSUE TITLE
dva init失败

### ISSUE THREAD

**Issue by miyoosan** [dvajs/dva#889]
![qq 20170506033711](https://cloud.githubusercontent.com/assets/25057968/25761463/75b0aeee-320d-11e7-822f-ddc9bcd1f437.png)
如上图所示，安装完dva后，初始化脚手架失败。
我的环境是WIN7 64位系统，npm, node, dva的版本在截图里都有，不知道是什么原因，在公司安装可以正常使用，回家里这台电脑安装就有问题。请问各位大佬，这种情况该怎么解决？

**Comment by zjxpcyc** [comment]
没见过，看着像是 node 启动报错。
