### ISSUE TITLE
browserHistory使用方法

### ISSUE THREAD

**Issue by zerozaki0752** [dvajs/dva#89]
我在dashboard那个example中加了browserHistory
可是并没有生效依然使用的是hash

```
import './index.html';
import './index.less';
import dva from 'dva';
import 'antd/dist/antd.css';
import { browserHistory } from 'dva/router';

// 1. Initialize
const app = dva({
  history:browserHistory,
  onError(error) {
    console.error(error.stack);
  },
});

// 2. Model
app.model(require('./models/users'));

// 3. Router
app.router(require('./router'));

// 4. Start
app.start('#root');

```

**Comment by sorrycc** [comment]
我试了下没有问题，和你同样的改法。

![2](https://cloud.githubusercontent.com/assets/35128/18605364/a9ffbb46-7cc2-11e6-8346-54dd1398dc30.gif)

**Comment by zerozaki0752** [comment]
@sorrycc 
```
import React from 'react';
import { Router, Route } from 'dva/router';
import HomePage from './routes/HomePage';
import NotFound from './routes/NotFound';
import Users from './routes/Users';
import { browserHistory } from 'dva/router';

/* eslint react/prop-types:0 */
export default function ({ history }) {
  return (
    <Router history={history}>
      <Route path="/" component={HomePage} />
      <Route path="/users" component={Users} />
      <Route path="*" component={NotFound} />
    </Router>
  );
}
```
我看到在初始化时修改history类型只修改了首页 users这个页应该在哪里修改呢？

**Comment by sorrycc** [comment]
没明白问题，browserHistory 只在全局配置一处就可以了。

**Comment by zerozaki0752** [comment]
users页的链接仍然是http://localhost:8989/users#/users?page=1&_k=d4hav6
这个不是还是hashHistory的吗？
我预期会是这样的
http://localhost:8989/users?page=1

**Comment by sorrycc** [comment]
这样访问首页 http://localhost:8989/，然后点 `/users`

**Comment by nikogu** [comment]
@zerozaki0752 https://github.com/dvajs/dva-snippets/blob/master/how-to-config-router.js

参看，代码中注释的 jsfiddle

**Comment by zerozaki0752** [comment]
@sorrycc 
直接点/users
还是会跳转 http://localhost:8989/users#/users?page=1&_k=9fpzjc
直接访问 http://localhost:8989/users 会提示 Not Found

**Comment by zerozaki0752** [comment]
@nikogu 恩 最外层的Route链接是没有问题的 http://localhost:8989/
但是再到下一级就又变回hash方式了 http://localhost:8989/users#/users?page=1&_k=f5hgm0

**Comment by sorrycc** [comment]
之前的 user-dashboard 例子不兼容 browserHistory，已修复。

**Comment by zerozaki0752** [comment]
@sorrycc 
这个问题是user-dashboard中写法的问题
还是dva本身的问题呢？
我看到引用了import { parse } from 'qs';

**Comment by sorrycc** [comment]
user-dashboard 的写法问题。

**Comment by TangMonk** [comment]
现在打包之后会变成hash模式
