### ISSUE TITLE
dispatch后获取state未更新

### ISSUE THREAD

**Issue by laughcat** [dvajs/dva#890]
在组件中使用dispatch调用effects方法，然后reducers更新state后，组件中dispatch方法后使用model调用state属性发现未更新，请问这是什么原因呢？

**Comment by ouzhou** [comment]
_组件中dispatch方法后使用model调用state属性发现未更新_是指？

**Comment by laughcat** [comment]
@ouzhou 就是发起一个dispatch调用， 在model里会更新state，然后紧接着在dispatch代码后获取state，发现state未更新。类似 dispatch(action);model.list;(list为state中变量，但是现在list未更新)

**Comment by ouzhou** [comment]
没能理解你的逻辑，你指的state未更新是指你在页面上的state没有更新吗？

**Comment by laughcat** [comment]
页面的数据更新是从model里的state取的，state未更新所以route页面中的值就未取到更新后的值 @ouzhou

**Comment by laughcat** [comment]
@sorrycc 请问能方便回答一下吗？

**Comment by xufei** [comment]
model里面怎么更新list的，贴代码看下呢

**Comment by grunmin** [comment]
我也遇到过, 我是用`setTimeout(xxx, 100)`暂时解决的2333.

**Comment by Menq** [comment]
dispatch 之后要在下一次render 之后才能更新props，请使用componentDidUpdate去取你需要的数据。
