### ISSUE TITLE
请问一下，model里面的state的只有一个字段为formList:[]的空数组，发生变化之后没有刷新页面

### ISSUE THREAD

**Issue by bnuephjx** [dvajs/dva#891]
操作是这样的，我点击按钮dispatch之后，就触发add这个事件，然后往formList添加了一个对象进去，这个数组长度发生变化了，然后返回这个添加内容之后的数组，为什么不会刷新页面

**Comment by ouzhou** [comment]
你需要检查页面中的state或者props是否改变

**Comment by nihgwu** [comment]
返回的还是原来的对象吧，返回之前 slice() 一下呢

**Comment by bnuephjx** [comment]
@ouzhou 我第二次点击的时候，state已经是添加了第一次点击的内容了，是有变化的，只是不会刷新页面

**Comment by bnuephjx** [comment]
@nihgwu 返回的就是formList这个数组，state里面就只有formList这个字段，我每次点击添加，都会往这个数组添加一个对象，然后返回这个数组，除非我在返回的对象中，随便添加一个字段，而这个字段只要能发生改变就会刷新页面，问题是，为啥我找个数组明明已经改变了，却不会刷新页面呢

**Comment by nihgwu** [comment]
没理解我的意思？Array是引用类型，你往里面push数据，他还是指向同一个对象
return { formList: formList.slice() }

**Comment by bnuephjx** [comment]
@nihgwu 我尝试用你说的方法，但是只能第一次的时候有效，当第二次点击就无法刷新页面了

**Comment by xufei** [comment]
@bnuephjx 用redux-devtools看一下这个action变化前后的state状况呢？只要你改了引用，变成了新数组，应该就是会刷新的

**Comment by bnuephjx** [comment]
@xufei 
![image](https://cloud.githubusercontent.com/assets/11852532/25787352/5f9c2fd0-33d3-11e7-97fe-14636e74f216.png)
我这里是用了上面说的slice(),这样就只有第一次会刷新页面，如果我没用，连第一次都不会刷新，图片上state的formList里面确实有两条数据，一个是title。一个是radio，但是图片左边展示的只有title这部分，第二次添加radio的就没有刷新页面出来
下面这是我的add操作
![image](https://cloud.githubusercontent.com/assets/11852532/25787477/462cd8fa-33d4-11e7-8a65-084425c483f7.png)

**Comment by nihgwu** [comment]
如果数据缺失改变了，会不会是你的render有问题

**Comment by bnuephjx** [comment]
@nihgwu 我也不清楚，怎么测试我的render有没有问题？如果render有问题的话，应该第一次也不会渲染吧，而且我在返回的数据中，添加一个字段，这个字段能发生改变的话，一样能渲染，例如return { formList:formList,length:formList.length};每次添加之后，长度不一样，这样就能每次都渲染，问题这个字段是多余的

**Comment by MrCuriosity** [comment]
试试从key上找问题。。。
