### ISSUE TITLE
运行build之后，显示文件大小与实际生成的文件大小不符，请问这是为什么？

### ISSUE THREAD

**Issue by yeelone** [dvajs/dva#892]
我运行 npm run build 之后，终端显示
`> roadhog build

Creating an optimized production build...
Compiled successfully in 90.0s.

File sizes after gzip:

  441.33 KB  dist/index.js
  115.93 KB  dist/3.async.js
  115.38 KB  dist/5.async.js
  115.14 KB  dist/4.async.js
  56.52 KB   dist/0.async.js
  50.6 KB    dist/6.async.js
  31.6 KB    dist/7.async.js
  25.5 KB    dist/8.async.js
  24.7 KB    dist/9.async.js
  24.57 KB   dist/index.css
  23 KB      dist/10.async.js
  7.11 KB    dist/1.async.js
  533 B      dist/11.async.js
`

![qq20170506-224320](https://cloud.githubusercontent.com/assets/2508385/25773270/841976dc-32ad-11e7-87f3-574e64716b1d.png)

文件夹显示index.js有1.6m

**Comment by zjxpcyc** [comment]
File sizes after gzip

**Comment by grunmin** [comment]
反向代理开下gzip试试?

**Comment by h31639347** [comment]
我打包出来都有600多k....想问下你怎么打包得这么小。。。是不是我react- react-dom或者一些公共库都一起打包了

**Comment by likepearl** [comment]
我也想知道什么原因？

**Comment by sorrycc** [comment]
gzip 之后和之前的区别。
