### ISSUE TITLE
模块交互，全局 state 相关问题

### ISSUE THREAD

**Issue by bolord** [dvajs/dva#895]
目前有一个数据字典模块，数据量比较大，几乎每个模块都可能会用到里面的数据，之前是每个模块只加载和处理自己需要的一部分数据，写起来比较麻烦，所以我将 state 移动到 app 模块，保证只会远程加载一次数据，然后在其他 model 里去 select。

然后问题就来了，各种因素可能会导致延迟，假设现在加载数据字典需要 3 秒，其他模块加载只需要 1 秒，那么其他模块则取不到数据，导致不能正确 render。

我目前的解决方案：
在 app 模块写一套发布订阅的方法，其他模块在 select 的时候先检查数据，数据已加载就直接 put，数据未加载完成就去注册监听器，然后等 app 模块加载数据完成时再统一发出事件让监听器去处理。

问题：
1. 有没有什么方法支持全局 state，并且 state 改变后其他地方用到的也可以重新 render
2. 目前的解决方案相当于 copy 一份 app state 到 model state，数据是引用还是复制？感觉有风险也不优雅
3. 模块之间交互有没有原生支持的事件型的解决方案，或者更好的

**Comment by icodytan** [comment]
想到两条思路：
① 在 mapStateToProps 获取当前 model 需要的 app model 数据
② app model 获取数据后，put 数据到其他需要的 model

**Comment by bolord** [comment]
@icodytan 
第 1 种不是太清楚，我也是刚接触 react 技术栈
第 2 种是我目前在用的方案，但是数据相当于存在多份，不清楚 react/redux 底层 state 怎么管理的，如果是引用数据还好，复制的话，数据量大了，加载的模块多了可能有隐患

**Comment by dicklwm** [comment]
@bolord 我个人是使用第一种方法的，在router组件里面的mapStateToProps 方法，将你的app model的数据映射到你的router组件的props里面

**Comment by xufei** [comment]
1. mapStateToProps是可以解决这个问题的
2. 一般来说其实是引用和复制兼有的，比如说：

```JavaScript
const a = {
  foo: {
    aaa: 1
  },
  bar: 1,
  arr: [1, 2, 3]
}

const b = { ...a, bar: 2}
```
在仅修改bar的时候，是可以用上面这句做的。这个时候，a跟b引用不同，可以算是一种复制，但是，它们内部的foo和arr又是同一份引用。

只要你能保证之后的所有对数据的修改，都不会直接改引用，如果要改，都是把要改的部分复制一份，就能避免这个问题。

如果你有大数组要共享，建议你把它搞成这种形态：

```JavaScript
const idArr = ['1', '2', '3']
const objMap = {
  '1': { id: '1', name: '111' }
  '2': { id: '2', name: '222' }
  '3': { id: '3', name: '333' }
}
```

这样分开存，可以有效避免视图模块中可能的直接在引用上的修改。对象的比较好处理，数组的麻烦，所以要用这种方式搞，修改了之后再组合起来。

3. model之间的交互，可以通过put或者call的时候，action的type加上对方的namespace，比如：

```JavaScript
yield call({ type: 'otherModel/effectA' })
```

另外，可以考虑一下take的使用，take的语义相当于添加事件监听，可以在某model里面去take其他model里面的action，这样，当对方有了这个action的时候，你这边就可以处理一些事情

**Comment by bolord** [comment]
@xufei 
1. 试了一下 mapStateToProps 是可以解决的，并且 state 改变后也会自动重新装载

2. 数据结构目前已经是优化过的，数据基本其他模块只会使用，不会修改，之前就是每个模块都要取一部分数据然后做 mapping 等操作，比较麻烦，又是重复代码，写个公共方法也会产生多个请求，所以想一次加载，一起加工，其他模块直接使用

3. 在仓库里搜到了下面的代码，put，call，select 都没问题，其他的怎么理解？好像还有一个 fork？
```javascript
export interface EffectsCommandMap {
  put: <A extends Action>(action: A) => any;
  call: Function;
  select: Function;
  take: Function;
  cancel: Function;
  [key: string]: any;
}
```

下面的 type 类型又怎么理解？takeEvery，takeLatest，throttle 看了测试代码比较好理解，文档好像不是很完善，看了下好像是 redux-saga 相关的内容，仓库迁移了，`docs/GettingStarted.md`里的链接还没修改过来，之前还是做的比较急，文档看少了。
> 格式为 `*(action, effects) => void` 或 `[*(action, effects) => void, { type }]`。
> 
> type 类型有：
> 
> * `takeEvery`
> * `takeLatest`
> * `throttle`
> * `watcher`

**Comment by xufei** [comment]
@bolord 你主要看下take的这两个吧，这两个还是比较有用的，大致相当于jq里面的on和once：添加一个事件监听；添加一个一次性的事件监听。

**Comment by VanquisherMe** [comment]
当页面刷新后， app 模块中请求用户数据，然后再 b 模块中 select =>app.state,得到的却是初始数据，我想获得已经重载的数据应该怎么做？ 场景是 b模块中需要 app.state 中用户状态的一个 参数
