### ISSUE TITLE
打包之后出现的一些常见问题的解决方案！

### ISSUE THREAD

**Issue by K-walker** [dvajs/dva#897]
相信大家在打包发布的时候都会出现一些常见的问题，下面我列举下几个常见的问题，以及相关的解决方法，希望能够帮助大家！

## 服务器端访问 ##
 > 打包后的文件放到服务器访问，需要配置 `history ` 为` browserHistory `
## 页面访问空白
>  服务器无法识别配置的 `browserHistory `，改为 `hashHistory`
## ant design 样式丢失
>  在生产环境配置  `["import" , {"libraryName":"antd" , "style":"css"}]`
## js文件打包过大
> 使用 require.ensure 加载js文件一般在配置动态加载model的时候，同时如果没有配置按需加载，也会造成js文件过大，这个我自己遇见的 ，不知道你们有没有碰到过。
## 打包后的js无法访问
> 配置`publicPath:’./’` 否则将无法访问打包后的js文件
## 无法访问本地iconfont
> 1.修改`["import" , {"libraryName":"antd" , "style":"css"}] `中`style:css `改为 `style:true`
2.打包前，修改icon-rul 路径，我的iconfont路径为：` '@icon-url':'"/fonts/iconfont/iconfont"' `
改为：` '@icon-url':'"项目名称/xxx/fonts/iconfont/iconfont"' `
因为浏览器访问字体的会自动加上服务器地址，此时需要你加上你自己的项目名称，如果没有加则浏览器就会 访问 `http://localhost:8080/xxx/fonts/iconfont/iconfont` 这个地址从而找不到iconfont

以上是我本人在打包的时候碰到的问题，可能不是很全面，解决方法也可能存在缺陷，但毕竟我这样做也是解决了这些问题，如果大家发现什么新的问题和解决方案，欢迎此留下您宝贵的方法，谢谢！

**Comment by yyyyy210** [comment]
+1

**Comment by zhangjingge** [comment]
@K-walker 你好，我配置了   publicPath:’/boss/’,打包出来路径没有变化，能帮忙看一下吗？
我们大概想实现在路径上面  http://XXXX.com/boss/zzz   这样的，有一个统一的boss
![1](https://user-images.githubusercontent.com/20674049/27362332-4cef3558-5660-11e7-8527-3e7dd751a2ac.png)

**Comment by haohailong1990** [comment]
在生产环境配置 ["import" , {"libraryName":"antd" , "style":"css"}]配置了不行，刷新样式就丢了
