### ISSUE TITLE
支持微信小程序？

### ISSUE THREAD

**Issue by zenjava** [dvajs/dva#900]
请问后续会考虑支持微信小程序么？

**Comment by forever4313** [comment]
这俩不是一个东西。

**Comment by zjxpcyc** [comment]
我就想着 dva 向这方面发展呢，不知道 dva 官方人员怎么想。
我想着，后期 dva 就脱离 react , 可以实现各种 spa 的开发，包括vue, 小程序在内的种种框架

**Comment by nihgwu** [comment]
下一个大的版本就会支持了

**Comment by zjxpcyc** [comment]
@nihgwu 你们果然在憋大招啊。
我之前在考虑如果下一个大版本，我现在程序怎么平滑升级的问题。
你们能把 Projects 维护起来吗?

**Comment by nihgwu** [comment]
会向后兼容的 #772

**Comment by Liqiankun** [comment]
@nihgwu 现在的版本是否支持？
