### ISSUE TITLE
指定build的outputPath后index.html未复制到指定的outputPath中

### ISSUE THREAD

**Issue by zhengdongjiang** [dvajs/dva#902]
如指定outputPath路径为："C:\\Users\\admin\\zdj\\workspace\\yh-merchant\\src\\main\\webapp\\app" 后build后app文件夹中没有包含public中的文件

**Comment by grunmin** [comment]
贴下目录结构, public放顶层了吗

**Comment by zhengdongjiang** [comment]
![k_ 8lktiygj s z vk c0](https://cloud.githubusercontent.com/assets/12556623/25891832/0c8aa992-35a5-11e7-8afb-a1ac42b9fb97.png)

**Comment by zhengdongjiang** [comment]
上面是目录结构 @grunmin

**Comment by grunmin** [comment]
为什么index.html会在那里...

**Comment by zhengdongjiang** [comment]
上面的目录结构是通过命令dva new app 生成的，我试了重新生成了项目结构都和上面的一致，index.html在public中。
![1](https://cloud.githubusercontent.com/assets/12556623/25901137/60d09a5c-35c8-11e7-901c-9e669e6e48f2.png)
![2](https://cloud.githubusercontent.com/assets/12556623/25901573/bfa7b230-35c9-11e7-8874-09adf52e6f57.png)
 @grunmin

**Comment by zhengdongjiang** [comment]
找到原因了[https://github.com/sorrycc/roadhog/issues/111](url)，这是roadhog的一个bug，roadhog 0.6.0版本已经修复了这个问题，非常感谢。
