### ISSUE TITLE
build 生产环境是否支持 hash文件名？

### ISSUE THREAD

**Issue by acmeid** [dvajs/dva#904]
build 生产环境是否支持 hash文件名？或者是其他防止缓存的策略？
我是使用dva-cli生成的项目，假如还没有这项功能，能不能提供一个临时的解决方法？

**Comment by grunmin** [comment]
https://github.com/sorrycc/roadhog/issues/100

**Comment by forever4313** [comment]
"build": "atool-build --hash"

**Comment by acmeid** [comment]
@forever4313 这个是配置在哪里的？

**Comment by forever4313** [comment]
package json 里 scripts " 当然前提是你用的不是roadhog，如果是用roadhog可能就是其他的配置了貌似
scripts": {
    "start": "dora --plugins \"proxy,webpack,webpack-hmr\"",
    "build": "atool-build --hash",
    "test": "atool-test-mocha ./src/**/*-test.js",
    "lint": "eslint src",
    "precommit": "npm run lint"
  }

**Comment by acmeid** [comment]
真不巧，就是使用了roadhog。我是使用dva-cli生成的项目。
`
"scripts": {
    "start": "PORT=8085 roadhog server",
    "build": "roadhog build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  }
`

**Comment by forever4313** [comment]
参考这个 吧https://github.com/sorrycc/roadhog/issues/69
貌似他们还没实现。。。

**Comment by grunmin** [comment]
看下我贴的那个不就可以了
