### ISSUE TITLE
一个页面管理三种资源，router、model该怎么写

### ISSUE THREAD

**Issue by blackmatch** [dvajs/dva#909]
dva的service、model、component必须是同一个资源么。比如我一个页面（路由）里面要管理三种资源，这时候的service、model、component可以分开来写么？
界面如下图：
<img width="920" alt="2017-05-12 16 31 47" src="https://cloud.githubusercontent.com/assets/12443954/25990002/ba4d2802-3730-11e7-80da-5b682b06fc26.png">

**Comment by blackmatch** [comment]
用子路由么？看了一些配置子路由的资料，不太懂。求指导。

**Comment by zjxpcyc** [comment]
分开是肯定可以的，也是必要的。
这种情况，应该是 service , model, componets 各自一套，最后在 route 里面合并。
不过， service 一般用一个就可以了。

至于是否用子路由，这个要看你的 tab 切换方式，我觉得如果权限分配不是很严格的话，就放到一个 route 就可以了，没有必要搞三个子路由

**Comment by blackmatch** [comment]
@zjxpcyc 

> 这种情况，应该是 service , model, componets 各自一套，最后在 route 里面合并。

我的想法也是这个，就是怎么在route里合并我不懂，假如这个页面的route名字是manage，能写个简单的示例我参考一下么？

**Comment by zjxpcyc** [comment]
// route 组件正常写， 该 import 就 import 
const Manage = () => {xxxx}

// 这个地方合并 model
export default connect(s => ({a:s.a, b:s.b, c:s.c}))(Manage)
