### ISSUE TITLE
dva脚手架如何调用百度地图？并且在return时展示

### ISSUE THREAD

**Issue by logyLiang** [dvajs/dva#910]
如题

**Comment by nihgwu** [comment]
请问如何写代码

**Comment by longzhaobi** [comment]
可以查react如何调用百度地图解决

**Comment by logyLiang** [comment]
没有例子啊！查过




发自网易邮箱大师
在2017年05月14日 13:51，龙小川 写道：

可以查react如何调用百度地图解决

**Comment by longzhaobi** [comment]
我也没查过，不过你不建议用高德地图的话可以看这个：https://github.com/ElemeFE/react-amap
个人也觉得高德地图比百度好

**Comment by longzhaobi** [comment]
@logyLiang

**Comment by CoderChow1994** [comment]
我就是用高德做的，感觉还行
