### ISSUE TITLE
antd table reducers同步方法不能触发表格重绘

### ISSUE THREAD

**Issue by Jaware** [dvajs/dva#913]
table绑定的是model的state，在reducers同步方法中加入的方法不能触发表格重绘，只能在effects中再添加一个方法再触发同步方法才能重绘。可有别的方法吗，这样写很啰嗦
  Table  loading={loading}
          columns={columns}
          dataSource={list}
          
       
```javascript
reducers: {
    save(state, { payload: { list, total, page} }) {
          list.push({...});
      return { ...state, list, total, page }
    }
。。。
```

**Comment by Jaware** [comment]
就这么关了？这么草率？

**Comment by nihgwu** [comment]
你怎么不说你这issue开的很草率？这个跟 dva 本身有什么关系？

**Comment by Jaware** [comment]
你们这么玩开源真的好吗，态度决定未来

**Comment by longzhaobi** [comment]
自己不去想办法解决问题，还态度决定未来。

**Comment by xufei** [comment]
return { ...state, list: list.slice(), total, page }

这样？

**Comment by Jaware** [comment]
我意思是直接dispatch 给reducers的一个方法是不会触发组件重绘（某些antd的组件，并不是全部）的，只能先dispatch给effects中的一个方法，然后通过put给reducer，这不是dva的问题吗？

**Comment by Jaware** [comment]
前端我确实不是很擅长，我职业是java架构师，前端单纯个人爱好罢了，dva给我的印象还是不错的，但是一些小菜鸟这样diss我可真够搞笑的

**Comment by nihgwu** [comment]
哇，架构师啊，好厉害哦，给你上三炷香

**Comment by nihgwu** [comment]
对了，牛逼的架构师，我这个小菜鸟随便请教下啊，你修改list的时候好像引用并没有变，为什么你觉得视图应该更新呢？

**Comment by zjxpcyc** [comment]
@Jaware 
是不是你 list.push 的问题?  是否应该换成 const newList = [ ...list, ...xxx]

**Comment by Jaware** [comment]
先给你自己上香吧！IT圈子很窄，小心你的前途！就这样的人也配当member？@sorrycc

**Comment by Jaware** [comment]
@zjxpcyc  effects与reducer里面的两个方法是一样的，不存在引用与状态没改变的问题
