### ISSUE TITLE
dva g model xxx 怎么指定 写入的 位置

### ISSUE THREAD

**Issue by jingzhongyue** [dvajs/dva#914]
dva g model xxx 怎么指定 写入register 的 位置
我改了下 文件的 目录结构。
dva generate 怎么指定写入的 位置。

register  to entry src/index.js
Error: ENOENT: no such file or directory, open

**Comment by jingzhongyue** [comment]
dva g 这种 的 api 地址在哪能看。

**Comment by nihgwu** [comment]
https://github.com/dvajs/dva-cli

**Comment by jingzhongyue** [comment]
看了下 https://github.com/dvajs/dva-cli 里面的源码。
其实我想要的答案是

dva g model user/user --entry src/pages/index/index.js

**Comment by sorrycc** [comment]
目前不支持，等时间再改进 dva-cli 吧。
