### ISSUE TITLE
多页面应用内包含单页面应用

### ISSUE THREAD

**Issue by bolord** [dvajs/dva#915]
例如前台的网站，主页和其他偏静态的页面我希望使用多页面编译好，用户中心做成单页面应用，有兼容方式或者解决方案吗？还是建议分开，单独两个项目？

**Comment by jingzhongyue** [comment]
我在 .roadhogrc  用 "entry": "src/*/*.js"
这样基本上就是多个单页应用 挤一起 的感觉。强行挤成一个多页。
