### ISSUE TITLE
更改state中原始数据，组件不会重新渲染？？？

### ISSUE THREAD

**Issue by Zuckjet** [dvajs/dva#918]
![dva](https://cloud.githubusercontent.com/assets/17976139/26195092/3a77596a-3bed-11e7-98a0-c5e99177803a.png)
使用案例如上图所示，点击button，使得右侧checkbox变为勾选状态。

组件代码：
```
`import React from 'react';
import {Checkbox,Button} from 'antd';
import { connect } from 'dva';
function HomeLayout({status,dispatch}) {
  const array = [];
  function check(){
    array[0] = true;            //语句1
    dispatch({type:'example/save',payload:array});    //语句2
    //status[0] = true;      //语句3
    //dispatch({type:'example/save',payload:status});    //语句4
  }
  return (
    <div>
      <Button onClick={check}>点击</Button>
      <Checkbox checked={status[0]}></Checkbox>
    </div>
  );
}
function mapStateToProps(state) {
  const status = state.example.status;
  console.log(status);
  return {
    status,
  };
}
export default connect(mapStateToProps)(HomeLayout);`
```

modal代码：
`export default {

  namespace: 'example',

  state: {
    status:[false],
  },

  subscriptions: {
    setup({ dispatch, history }) {  // eslint-disable-line
    },
  },

  effects: {
    *fetch({ payload }, { call, put }) {  // eslint-disable-line
      yield put({ type: 'save' });
    },
  },

  reducers: {
    save(state, {payload}) {
      state.status = payload;
      return { ...state };
    },
  },

};
`
在组件的check函数中，语句3和语句4的作用   完全可以等同于语句1和语句2的作用，但是为什么使用语句3和语句4替代语句1和语句2以后  点击button，右侧checkbox不会变为勾选状态？

**Comment by sorrycc** [comment]
reducer 要返回新的。

```js
save(state, { payload }) {
  return { ...state, status: payload };
}
```

**Comment by Zuckjet** [comment]
d

**Comment by xiandongw** [comment]
我觉得语句3工作是因为 status[0] 直接更新了jsx 而不是dispatch。 试试设个断点看dispatch之后页面有么有重新render
