### ISSUE TITLE
DVA,antd怎么获取组件ID

### ISSUE THREAD

**Issue by CoderChow1994** [dvajs/dva#919]
如图
![1495159772 1](https://cloud.githubusercontent.com/assets/23169397/26230443/8e8d8e6e-3c7b-11e7-89c8-bef2370cd7ee.jpg)
用document。getElementById找不到ID，该怎么办

**Comment by xufei** [comment]
这个问题跟dva没有关系吧。

你在这里加id是想做到什么？控制展示隐藏吗？如果是这个，搞个变量，把它绑定进去，然后改这个变量就行了

**Comment by CoderChow1994** [comment]
@xufei 
![image](https://cloud.githubusercontent.com/assets/23169397/26230786/071f176a-3c7e-11e7-8337-0720aa8b2f99.png)
这个AutoComplete的getPopupContainer需要绑定父元素的ID来定位，我获取不到Modal的id，该怎么办

**Comment by nihgwu** [comment]
用className

**Comment by CoderChow1994** [comment]
@nihgwu 具体怎么做？

**Comment by nihgwu** [comment]
className='area'
document.queryElement('.area')

**Comment by CoderChow1994** [comment]
Uncaught TypeError: document.queryElement is not a function
![image](https://cloud.githubusercontent.com/assets/23169397/26231608/08e06a90-3c83-11e7-881a-170db8d5a342.png)

不行啊，识别不了啊

**Comment by nihgwu** [comment]
querySelector....

**Comment by dicklwm** [comment]
```js
getPopupContainer(triggerNode=>triggerNode)
``` 
推荐这么用，不行就
```js
getPopupContainer(triggerNode=>triggerNode.parentElement)
```
一直向上找，找到对的为止
