### ISSUE TITLE
页面局部（展开，收拢）状态变更也必须在model里定义状态吗？

### ISSUE THREAD

**Issue by FatFatFox** [dvajs/dva#920]
页面局部（展开，收拢）状态变更也必须在model里定义状态吗？
有办法不通过dispatch触发reducer，让页面自己管理吗？

**Comment by CoderChow1994** [comment]
不行，任何状态的修改都必须通过modal进行更改，你可以多次调用model的save，也可以自己自定义。以前我也是这么想的，然而不行

**Comment by helloyou2012** [comment]
当然不必须，组件内可以自己管理局部状态，如：

```
class Clock extends React.Component {
  constructor(props) {
    super(props);
    this.state = {date: new Date()};
  }

  render() {
    return (
      <div>
        <h1>Hello, world!</h1>
        <h2>It is {this.state.date.toLocaleTimeString()}.</h2>
      </div>
    );
  }
}
```

**Comment by FatFatFox** [comment]
@helloyou2012 该怎么给这个React.Component组件传值呢？和dva传值方式一样吗？

`<Clock {...props}/>`?

**Comment by helloyou2012** [comment]
@FatFatFox 用 `connect`

```
class Clock extends React.Component {
  constructor(props) {
    super(props);
    this.state = {date: new Date()};
  }

  render() {
    const { dispatch } = this.props;
    return (
      <div>
        <h1>Hello, world!</h1>
        <h2>It is {this.state.date.toLocaleTimeString()}.</h2>
      </div>
    );
  }
}
export default connect()(Clock);
```

**Comment by FatFatFox** [comment]
我做了一个父页面嵌套，没用connect也成功了，为什么？
`  
const filterProps = {                    
    expand:false,
  }
   return (
    <div className="content-inner">
      <Filter {...filterProps}/>
    </div>
  )`

`
class Filter extends React.Component {
	
	constructor(props) {
    super(props);
    this.state.expand = props.expand;
  }

}


export default Filter
`
