### ISSUE TITLE
import 目录报错

### ISSUE THREAD

**Issue by yxl2628** [dvajs/dva#921]
求助一下：
我看demo中有这样的写法
```javascript
import { request, config } from '../utils'
const { api } = config
const { userLogin } = api

export async function login (data) {
  return request({
    url: userLogin,
    method: 'post',
    data,
  })
}
```
utils是目录，这么做相当于直接引入utils下的request和config，对吧
可是为什么我在我的工程中这么用，会报错呢
`Module not found: ../../utils`
哪里需要配置一下么？

**Comment by xufei** [comment]
那是因为他目录下定义了一个index.js，然后里面引用了其他的东西，有index的时候可以省略index这个词，直接写上级路径。

**Comment by yxl2628** [comment]
谢谢，原来是这样
