### ISSUE TITLE
表单中输入框值远程合法性验证问题

### ISSUE THREAD

**Issue by chenbaolou** [dvajs/dva#922]
问题是这样的，有一个输入框，我想在onBlur时机去验证该值在数据库中是否已经存在，就像我们平时注册邮箱的时候会实时提示该邮箱名称是否已经被使用。之前在jquery时代可以是指ajax请求为同步。但是，在antd+dva框架中请求都是通过dispatch发起的，在这种情况下该如何实现呢？

**Comment by zjxpcyc** [comment]
这个为啥一定要 同步？
(上面的问题忽略)， 如果你实在找不到好的方案，模态的菊花转，你能接受吗？

**Comment by chenbaolou** [comment]
是我理解有问题，实际上antd框架form组件validateFields方法会自动对异步操作进行阻塞，所以不需要同步请求。
