### ISSUE TITLE
在effects中call一个fecth请求，如何执行同步请求；在线等，很急！ 

### ISSUE THREAD

**Issue by 18559909452** [dvajs/dva#923]
在effects中call一个fecth请求，如何执行同步；在线等，很急！

**Comment by Zuckjet** [comment]
你的意思是，要对fetch取到的数据进行操作吗？
![ooo](https://cloud.githubusercontent.com/assets/17976139/26241686/308f12aa-3cb8-11e7-82a4-51a4fefbd929.png)

**Comment by 18559909452** [comment]
我是希望以下代码阻塞浏览器的js进程。。避免多个http的并发
const { data, code } = yield call(usersService.logout);

**Comment by Zuckjet** [comment]
const { data, code } = yield call(usersService.logout);
你的userService.logout方法的作用，大概就是发送http请求，你要设置这个http请求同步阻塞，应该是在这个方法里面设置吧

**Comment by guissy** [comment]
这个需要一开始就触发一个effect如 subscriptions: {setup:({dispatch}){dispatch({type: 'init'});}}
然后在init里设定条件，我这里是1分钟内捕捉到多个namespace/toFetch也只执行一次doFetch
*init({payload}, {call,put,throttle}) {
      yield throttle(60 * 1000, 'namespace/toFetch', function *() {
        yield put({type: 'doFetch', payload: {}});
      });
    },
*doFetch({payload}, {call}) {
    yield call(fetchSth); 
}
可参考以下
https://github.com/redux-saga/redux-saga/blob/ab89fa45fe95264d2ce2baf6b8ddc455ea292593/docs/recipes/README.md

**Comment by zjxpcyc** [comment]
个人感觉，一般出现这种问题，都是你的思路从根本上就有误区，或者不正确

**Comment by LarryLee8** [comment]
这个还是有必要的，我现在遇到一样的情况，多个effect出现大量重复代码，需要effect之间相互调用。

**Comment by LarryLee8** [comment]
#521  看了所有帖子，这个是用用的。
