### ISSUE TITLE
如何在dva中使用redux-immutable

### ISSUE THREAD

**Issue by not3** [dvajs/dva#924]
```
import {
  combineReducers
} from 'redux-immutable';

import {
  createStore
} from 'redux';

const initialState = Immutable.Map();
const rootReducer = combineReducers({});
const store = createStore(rootReducer, initialState);```

怎么替换combineReducers，怎么使用immutablejs，有示例吗

**Comment by pengfeiWang** [comment]
还是希望能尽快推出 dva + immutable 吧

**Comment by longlongago2** [comment]
react-native 如何加调试工具remote-redux-devtools
`
import { composeWithDevTools } from 'remote-redux-devtools';
 const store = createStore(
        rootReducer,
        initialState,
        composeWithDevTools(
            applyMiddleware(sagaMiddleware),
        ),
    );
`

**Comment by MinJieLiu** [comment]
[关注这个pull request](https://github.com/dvajs/dva/pull/1002)
