### ISSUE TITLE
关于软连接的问题

### ISSUE THREAD

**Issue by zhouningyi** [dvajs/dva#925]
经常在dva的工程代码里对依赖的库进行调节，过去的做法是做软连接到node_modules里面，但dva里没有成功，求教有没有方法可以做到

**Comment by zjxpcyc** [comment]
感觉不是 dva 的问题, 应该是 node 问题。
我的理解是，不管是加载 node_modules 还是，项目本身的代码，你只要告诉 node 环境包在哪里就可以了。按照这种思路，你试试绝对路径呢。

**Comment by zhouningyi** [comment]
谢谢快速的回复，我的包是es6的，带import，直接通过ln -s 软连接，目前会报错，console里显示 Uncaught SyntaxError: Unexpected token import， 因此我觉得是不是因为node_modules默认是不带babel转化的 有没有办法可以让某些包自动被babel后 再被引用

**Comment by zjxpcyc** [comment]
你少插件吧？
试试 官方推荐的  [babel-plugin-import](https://github.com/ant-design/babel-plugin-import)

**Comment by zhouningyi** [comment]
我试了一下 安装了插件后，babelrc的写法如下，还是报错哦，其中libraryDirectory删除亦是如此
{
  "plugins": [
    ["import", {
      "libraryName": "xxx",
      "libraryDirectory": "node_modules",
      "style": "css"
    }]
  ]
}

**Comment by zjxpcyc** [comment]
报什么错？
你先看下 [ dva cli   配置](https://github.com/sorrycc/roadhog/blob/master/README_en-us.md#configuration) 吧，这样可能错误会相对少点。

**Comment by zhouningyi** [comment]
仔细看了下babel-plugin-import 目的貌似是在import 已经编译为es5的包，让体积小一点
但目前遇到的困难是，库的代码是es6的，软连接到node_modules ，如何在项目中import不出错误。。。

**Comment by zjxpcyc** [comment]
错误是什么？ 你贴出来看看。

另外，你不需要去配置  “plugins” ， 使用  babel-plugin-import 是有前提的，你去看下它的源码就知道原因了。

再一个检查下你的 es6 库， main 入口。建议你把 package.json 贴出来。

只是简单的说几句“还是报错”, 我目前的水平还是定位不出来你的问题。

**Comment by zhouningyi** [comment]
开发中更新node_modules在项目中重新安装，非常费时， 因此可以通过软连接，可以改动包的代码同时，让项目实时变化。项目之前是work的，但如果引入软连接 console里显示 Uncaught SyntaxError: Unexpected token import，

然后我配置了 .roadhogrc
{
  "entry": "src/index.js",
  "extraBabelPlugins": ["transform-runtime", "import"],
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr"
      ]
    },
    "production": {
      "extraBabelPlugins": [
      ]
    }
  }
}

以及 .babelrc
{
  "plugins": [
    ["import", {
      "libraryName": "xxx",
      "style": "css"
    }]
  ]
}

现在的报错是 
Failed to compile.

Error in ./src/index.js
Module build failed: AssertionError: /Users/zhouningyi/git/project/chengshi3/static/src/index.js: libraryName should be provided
 @ multi index

**Comment by zhouningyi** [comment]
package.json里 
"babel-plugin-import": "^1.1.1",
无论 --save-dev
还是 --save
错误是一样的

**Comment by zjxpcyc** [comment]
智慧山穷水尽了，估计你还是要 es6 转一下，再引入了

**Comment by zhouningyi** [comment]
好的 谢谢 但还是希望开发组能够考虑一下这类需求 确实有需要的
在webpack里  是可以实现的 1.0和2.0都可行，期待dva能够方便的支持哦
