### ISSUE TITLE
webstorm 的热更新问题

### ISSUE THREAD

**Issue by aimaodeyuer** [dvajs/dva#927]
roadhog配置如下
![image](https://cloud.githubusercontent.com/assets/12092562/26339888/c0d146b4-3fbd-11e7-831d-d8266065ca50.png)
每次改动iterm显示的重新compile
![image](https://cloud.githubusercontent.com/assets/12092562/26339903/dc7bafe4-3fbd-11e7-9da8-cb26672d15f5.png)

每次改完了页面却不刷新，不知道是否是端口问题，如何修改呢？

**Comment by xufei** [comment]
你用的webstorm吗，它保存临时文件的方式不一样：

https://stackoverflow.com/questions/34213253/webpack-watch-not-working-on-webstorm-on-windows

**Comment by aimaodeyuer** [comment]
@xufei os系统 用的idea 前端编译后的文件是放在8000端口上的，然后ftl文件里面引用路径就是放dist文件的路径。每次改动倒是能够重新compile，就是页面不刷新QAQ。

**Comment by aimaodeyuer** [comment]
@xufei 这项也勾选了，还是不生效
![image](https://cloud.githubusercontent.com/assets/12092562/26340969/ec1354d8-3fc3-11e7-92fd-5aad12a6df9d.png)

**Comment by xufei** [comment]
saft write是要勾掉啊，不是勾上

**Comment by chensyn** [comment]
换其他编辑器，webstorm热更新确实有问题

**Comment by Mark24Code** [comment]
马克
