### ISSUE TITLE
异步加载的后的数据不会渲染

### ISSUE THREAD

**Issue by smallchicken** [dvajs/dva#928]
![image](https://cloud.githubusercontent.com/assets/21360019/26343827/0f44e3fc-3fd0-11e7-8b3b-0ca1449d561b.png)
异步请求之后每次进页面都会输出两次数据，但是由于页面是指对checkbox的默认选中进行设置，它只会渲染第一遍，第二遍不会渲染
![image](https://cloud.githubusercontent.com/assets/21360019/26343940/7ea06c30-3fd0-11e7-9602-15426089b461.png)
![image](https://cloud.githubusercontent.com/assets/21360019/26343960/8e55217a-3fd0-11e7-8320-dc01858cb76d.png)
![image](https://cloud.githubusercontent.com/assets/21360019/26343982/9ebfa1c0-3fd0-11e7-9f25-494268a11422.png)
请教下如何解决呢？或者让每次访问的数据都清空呢？

**Comment by xufei** [comment]
render的时候去this.props里面取checked啊

**Comment by smallchicken** [comment]
谢谢，已经解决了，请问下为什么在state里面取就不可以呢？我也把props里的属性给了state了啊？如果解释麻烦，可以给我推荐几个相关知识的博客或论坛的地址吗？谢谢您

**Comment by smallchicken** [comment]
如果在this.props里面取了checked，checkbox又无法点击了，这么怎么解决呢？

**Comment by smallchicken** [comment]
你好，我已经解决了，用到了componentWillReceiveProps

**Comment by xufei** [comment]
你在构造函数里面把props的属性给了state，但后续变更都是改在props上了，没人把它再赋值给state。在渲染的时候从props上取，肯定是最新的。

**Comment by smallchicken** [comment]
嗯嗯，知道了，谢谢您
