### ISSUE TITLE
websocket中如何监听事件的回调

### ISSUE THREAD

**Issue by stonelee** [dvajs/dva#929]
websocket中会监听某事件的响应，例如下面的service代码：

```
export function sub(id) {
  return new Promise(resolve => {
    some.sub(`/topic/net.alipay.luna.first_connect.12345`, () => {
      resolve({
        type:'first_connect'
      });
    });
  });
}
```

然后model中按照这个issue的方式进行调用：
https://github.com/dvajs/dva/issues/252

```
while (true) {
        const { type, payload:data } = yield call(someService.sub, id);
        console.log(type, data);
 }
```

然后发现，每次链接，都会附加一次监听事件，导致回调越来越多，难道只能在resolve时手工销毁事件监听吗？有没有更好的写法？

**Comment by sorrycc** [comment]
用 subscription?

**Comment by stonelee** [comment]
确实可以，感谢。

另外有个小问题，subscriptions里只有dispatch跟history。但是我要从state里拿点数据出来，然后来触发websocket，有什么好的方案呢？难道要放到window上来取？

**Comment by stonelee** [comment]
最终在service里维护一个变量来解决的，但是还是感觉比较绕，subscriptions中如果能提供一个方法，可以获取state，就完美了
