### ISSUE TITLE
学过angular和vue，是不是可以不学react直接学dva？

### ISSUE THREAD

**Issue by iloveyo123u1** [dvajs/dva#933]

**Comment by xiandongw** [comment]
react is view only, dva is framework help to build react app easily.

**Comment by zjxpcyc** [comment]
起码 react 基本常识要知道，比如声明周期之类的。另外，react 与 另外2个不同的是， react 只是 view , 其余的内容要靠  dva　和 一些 node 库来实现。不如  angular 大而全。

**Comment by iloveyo123u1** [comment]
tks @xiandongw  @zjxpcyc

**Comment by sorrycc** [comment]
可以看看 https://github.com/dvajs/dva-knowledgemap
