### ISSUE TITLE
dva中使用无状态组件，如何管理组件的生命周期？

### ISSUE THREAD

**Issue by Zuckjet** [dvajs/dva#936]
dva开发中一般都是使用stateless component组件，但是我的理解是，无状态组件是不能参与组件的生命周期管理的。
我在开发时遇到下面的问题：
![lll](https://cloud.githubusercontent.com/assets/17976139/26516988/4f34c780-42c2-11e7-98ce-5a6aa4b99e8b.png)

我查阅了资料  可能是因为我在组件的初始化阶段使用了dispatch改变state,但是无状态组件的生命周期，是无法管理的吧，我该如何解决这个问题？
或者说，我的dispatch应该放在无状态组件中的哪个位置，才可避免上述问题？

**Comment by xufei** [comment]
如果组件有自发的操作，还是应该搞成那种普通Component吧，不应当强制每个地方都用无状态组件

**Comment by LeezQ** [comment]
无状态组件是没有生命周期的，如果需要初始化阶段来触发 state 的改变 ，可以在 subscriptions 去 dispatch 一个 effect。

**Comment by longlongago2** [comment]
还可以使用HOC 高阶组件

**Comment by nalantianyi** [comment]
无状态组件叫stateless component，顾名思义当然没有生命周期管理，建议使用redux管理，在这里就是使用dva
