### ISSUE TITLE
（急） 手机端 请求完成状态未变更 偶现 

### ISSUE THREAD

**Issue by zhouzefei** [dvajs/dva#937]
使用dva1.2.1
web端请求：axios
此为h5项目，手机中偶现尤其ios系统中，app的webview中
页面中所有方式用call来发起
现象：
请求发送成功，charles抓包数据有返回但是页面state中的数据状态未变更..感觉哪个地方堵塞，一旦发生这个问题后面所有的请求都能成功但是页面中的状态不变更，个人猜测是saga堵塞，没有执行put，，但是偶现很难调试。不知道你们有没有类似的情况。。。如何解决@sorrycc
 pc中复现不出来
```javascript
import dva from 'dva';
```
```javascript
state: {
    isLoading: true
},
reducers: {
    renderData(state,{ payload: isLoading }){
        return {
            ...state,
            isLoading
        }
    }
  },
effects: {
     *getList({ payload },{ select, put, call }){
          const { data } = yield call(getOrderList,params);
         const isLoading = false;
          yield put({ type: 'renderData', payload: isLoading});
      }
  },
```

**Comment by sorrycc** [comment]
偶尔出现，应该是网络问题，和 dva 以及 saga 无关。

**Comment by zhouzefei** [comment]
谢谢您的回复。但是请求成功，charles抓包返回数据正常，有可能是redux-saga中的generator有问题吧，，，我引入了es6-shim,我看了下redux-saga git上说要用polyfill，，，，会是这个原因导致么 @sorrycc
