### ISSUE TITLE
关于redux-persist数据恢复的问题

### ISSUE THREAD

**Issue by liumin1128** [dvajs/dva#938]
使用redux-persist做持久化，在恢复数据时，当然希望persist能在其他reducer调用之前将数据恢复到redux中，而在使用dva开发时，persist总是在其他modal后面调用的，这导致很多功能都出现了异常。
比如验证用户信息，验证的方法先于persist，此时，用户肯定是没有登录的。。。望将redux-persist集成到dva中，并解决这些问题。

**Comment by icodytan** [comment]
[extraEnhancers: 指定额外的 StoreEnhancer ，比如结合 redux-persist 的使用](https://github.com/dvajs/dva/blob/master/docs/API_zh-CN.md#extraenhancers)

**Comment by liumin1128** [comment]
@icodytan 你好，redux-persist可以正常使用，但恢复数据的步骤比其他action慢，persist总是在其他modal后面调用的

**Comment by sorrycc** [comment]
> 但恢复数据的步骤比其他action慢 

这样会有什么问题?

**Comment by wuzhuzhu** [comment]
@liumin1128 
A common mistake is to fire actions that modify state before rehydration is complete which then will be overwritten by the rehydrate action. You can either defer firing of those actions until rehydration is complete, or you can use an action buffer.
https://github.com/rt2zz/redux-persist#action-buffer

可是，你的redux-persist可以正常使用么？为什么我的app里面 rehydrate action不会引起state的任何变化？(payload有正常的持久化的数值)
你的问题可以使用action-buffer去解决。

**Comment by sundayha** [comment]
我也遇到这个问题 不知道怎么解决

**Comment by sundayha** [comment]
@liumin1128 我是把登陆信息放到localstorage里了，你是怎么解决的？

**Comment by wuzhuzhu** [comment]
Action buffer

**Comment by wuzhuzhu** [comment]
注意redux persist v5 原生支持code splitting,并且已经可以通过@next标签安装

**Comment by sundayha** [comment]
@liumin1128 解决了 [Redux persist rehydrate previous auth state too late](https://stackoverflow.com/questions/43168801/redux-persist-rehydrate-previous-auth-state-too-late)

**Comment by longbaobao** [comment]
使用了 Action buffer，确实业务action在state恢复之后执行，但是在effect 中使用     const customer = yield select(state => state.customer); 无法获取正确的数据customer中值为空
![image](https://user-images.githubusercontent.com/2797015/29611329-b6b40d46-882f-11e7-93c5-f7a4b15ef85d.png)

**Comment by p2227** [comment]
@sundayha 你有一个解决的完整例子吗？我也遇到这个问题

**Comment by zhangfaliang** [comment]
怎么监听persist/REHYDRATE action

**Comment by sundayha** [comment]
@p2227  [Redux persist rehydrate previous auth state too late](https://stackoverflow.com/questions/43168801/redux-persist-rehydrate-previous-auth-state-too-late) 看这个链接

**Comment by ChaoYuLeo** [comment]
https://github.com/rt2zz/redux-persist/blob/master/src/integration/react.js
redux-persist本身提供了一个组件来解决这个问题的
