### ISSUE TITLE
请问如何把dva  跟 router剥离出来

### ISSUE THREAD

**Issue by lusess123** [dvajs/dva#940]
router跟url结合太深，我把dva组件跟url解耦，请问在不想用router的情况下 如何呈现组件？

**Comment by lusess123** [comment]
无route版本的应该是  dva/mobile ,请问是否有相关的使用文档

**Comment by sorrycc** [comment]
`import from 'dva'` 的时候改用 `import from 'dva/mobile'` 就好了。
