### ISSUE TITLE
调用同一个model，无法render

### ISSUE THREAD

**Issue by jaikensai888** [dvajs/dva#942]
有两个业务容器 LoginController、DashBoardController 分别都是stateComponent只是connect  loginModel。
当在loginController的时候一切正常，
但是当登录完跳转到DashBoardController调用dispatcher（“loginModel／save”）的时候没有触发，DashBoardController的render方法，但是在loginModel中的值是修改成功的。求解 @sorrycc  是否一个model 只能绑定一个render对象？

**Comment by xufei** [comment]
没有这样的限制啊

**Comment by jaikensai888** [comment]
@xufei  的确出现了这问题：
![question1](https://cloud.githubusercontent.com/assets/5178454/26708755/5e2818d8-4780-11e7-8692-d626f8553a1b.jpg)

**Comment by sorrycc** [comment]
没有这个限制的，检查下代码吧，比如 reducer 是否返回新的对象。

**Comment by jaikensai888** [comment]
问题已经解决，原因是引用类型更新问题，使用faceBook的Update就可以解决这个问题了
