### ISSUE TITLE
dva/mobile打包问题之后bundle.js过大问题

### ISSUE THREAD

**Issue by Slngle** [dvajs/dva#943]
你好 我手机上h5就一个列表页面用webpack打包之后大概文件大小有300k这正常么  是我多打包了东西么？

**Comment by nihgwu** [comment]
很正常，自己算一下 react+react-dom+redux+redux-saga+react-router 等等等的大小

**Comment by Slngle** [comment]
我没有引入react－router 感觉手机端上300kb的包还说太大了

**Comment by sorrycc** [comment]
```bash
-rw-r--r--   1 chencheng  staff   194K Jun  1 17:51 mobile-min.js
-rw-r--r--   1 chencheng  staff   297K Jun  1 17:51 mobile.js
```

mobile 版本框架代码 297K，压缩后 194K，不包含 react 和 react-dom。剩下的就是你额外引入的其他代码了。

**Comment by manan1234** [comment]
dva/mobile这个项目框架在哪里可以找到，我找了好久，没有找到，麻烦各位谁能告知一下
