### ISSUE TITLE
hashhistory下想去掉_k参数失败了

### ISSUE THREAD

**Issue by panyifei** [dvajs/dva#944]
hashhistory下想去掉_k参数失败了，照着教程写的，history是2.x的版本，dva版本是1.2.1

结果是还是会有_k参数，而且会在url尾部不停的叠加_k。

手动引入3.x的history，然后引3.x的react-router的useRouterHistory，dva会报错：让我引2.x的history。

然后我删掉dva node_modules下的react-router就可以去掉_k了。

想问下dva依赖的react-router能不能升级一下~~

**Comment by sorrycc** [comment]
不要尝试去 `_k参数`，后面使用时会遇到各种奇怪的问题的。react-router 在 dva@2 会进行解绑。 #772
