### ISSUE TITLE
roadhog

### ISSUE THREAD

**Issue by bucaixiaot** [dvajs/dva#945]
roadhog 怎么配置同时引入antd和antd-mobile的样式

     'transform-runtime',
        ['import', { 'libraryName': 'antd-mobile', 'libraryDirectory': 'lib', 'style': true }],
       ['import', { 'libraryName': 'antd', 'libraryDirectory': 'lib', 'style': 'css' }]

我这样配置不管用呀

**Comment by paranoidjk** [comment]
@bucaixiaot 能否将你的代码 push 到 github 并给出链接？

另外

> 我这样配置不管用呀--

这样无法理解问题，请描述清楚你遇到什么错误
