### ISSUE TITLE
package-lock.json文件如何commit

### ISSUE THREAD

**Issue by Kunoky** [dvajs/dva#946]
您好！最近我使用 npm i 安装package时，出现了如下的提示信息
npm notice created a lockfile as package-lock.json. You should commit this file.
请问我该如何解决？

**Comment by sorrycc** [comment]
不是 dva 的问题。。

**Comment by Kunoky** [comment]
我使用的是dva的框架，我在想是不是dva里的bug

**Comment by weishijun14** [comment]
@Kunoky https://docs.npmjs.com/files/package-lock.json

**Comment by weishijun14** [comment]
npm 5.0 新特性
