### ISSUE TITLE
I am looking for a way to use derivedState in dva.

### ISSUE THREAD

**Issue by whatwewant** [dvajs/dva#947]
As usual, we will use `connect` to computed the real data we need in our containers, but it will give more data logic in a container, I want to compute these in dva instead of `connect`.

**Comment by sorrycc** [comment]
You can write these `selectors` in model and `export`, then `import` them in container component.

**Comment by whatwewant** [comment]
@sorrycc If I just write these `selectors` in models, this is little better than in a `container`, and I will do more comands, like `export` and `import`. 
  Whether these derived State or `selectors` can go with dva(maybe redux)
