### ISSUE TITLE
dva框架的项目在tomcat下必须部署到更目录下吗?

### ISSUE THREAD

**Issue by cgd199158** [dvajs/dva#948]
1.工作场景: 用antd+dva建立了多个独立的子系统项目.
2.问题: 在部署到tomcat下的时候发现,每个子系统都必须部署到ROOT根目录下才能正在运行,否则无法正常获取到js路径.
请问有什么办法能将多个系统部署到tomcat下正常运行?或者怎么配置项目才能让项目不在tomcat的根目录正常跑起来?

**Comment by sorrycc** [comment]
配 publicPath，https://github.com/sorrycc/roadhog#publicpath

**Comment by cgd199158** [comment]
懂啦，谢谢。还有请问下dva如何实现像entry中说的多页应用？我想有没有可能将我的多个子系统集成到一个项目中去，请问有相关的资料和demo吗？
