### ISSUE TITLE
项目打包后放到tomcat能正常访问,但一但刷新就出现404

### ISSUE THREAD

**Issue by cgd199158** [dvajs/dva#949]
1.首次进入页面的路径(项目能正常显示但不会默认跳转到设定的默认路由,会跳到错误页面)
![image](https://cloud.githubusercontent.com/assets/18514077/26753941/8e5aca04-48a3-11e7-9bc8-cfc21557cf9a.png)
2.点击导航后能正常跳转,但是路径明显发生很大变化
![image](https://cloud.githubusercontent.com/assets/18514077/26753929/6026fbd0-48a3-11e7-824d-e3564ce17d22.png)
3.当手动刷新页面则跳转至tomcat返回的404
![image](https://cloud.githubusercontent.com/assets/18514077/26753948/a343970c-48a3-11e7-9f35-b5bd72ab521c.png)

请问如何配置tomcat才能使路由像在开发环境中正常跳转.
项目使用antd+dva进行开发.

**Comment by jnotnull** [comment]
browserHistory吧？需要服务端做下配置

**Comment by cgd199158** [comment]
@jnotnull 对的,是browerHistory.请问下服务器端应该如何配置呢?项目用的是tomcat,请问有相关的demo吗?

**Comment by jnotnull** [comment]
https://github.com/ant-design/ant-design/issues/2226
https://github.com/LoeiFy/Recordum/issues/15
