### ISSUE TITLE
ant design中table中动态生成的Input值的类型怎么校验

### ISSUE THREAD

**Issue by HuangLotus** [dvajs/dva#951]
现在有一个场景：
我有一个Form,Form中其中某一项数据是一个table,table中的数据是去异步获取然后生成的，且table中的最后一列是一个Input输入框，这个输入框中的值的类型需要我在提交的时候去校验。
可是这个input 不是formItem里面的一项（如果是formItem里面的，可以通过validator属性去设置校验），但是这里是table中的，而且是异步去获取的，所以这里我就不知道怎么校验了。

附上form的代码如下：
```
<Form layout="vertical">
            <FormItem label="表达式" {...formItemLayout}>
              {getFieldDecorator('ruleFormula', {
              })(<Input type="textarea" />)}
           </FormItem>
            <FormItem label="列表数据" {...formItemLayout}>
              <Table columns={columns} dataSource={formularList} pagination={false}
                     bordered size="small"/>
            </FormItem>
          </Form>
```
附上table的colums代码如下：
```
 const columns = [
      {
        title: '参数',
        dataIndex: 'paramName',
        key: 'paramName',
        width:'20%',
      }, {
        title: '类型',
        dataIndex: 'paramType',
        key: 'paramType',
        width: '20%',
      }, {
        title: '典型值',
        dataIndex: 'input',
        key: 'input',
        render: (text, record, index) => (
          <Input onChange={this.inputChange} placeholder="请输入合法的值校验"/>
        ),
      }];
```
这个onChange函数是在input有输入有改变的时候才会触发。
可是如果用户没有input,而是直接点击页面上的提交按钮了，我怎么自动校验，然后提醒用户呢？

**Comment by nihgwu** [comment]
走错片场了？

**Comment by HuangLotus** [comment]
@nihgwu 因为ant design的提问太不方便了。。
想到dva+ant design结合使用的多，就在这里提了，看有没有人遇到过，(⊙o⊙)

**Comment by forever4313** [comment]
我的 做法是，render方法 里使用getFieldDecorator 当然里面的key应该想办法搞个唯一的 ，用数据库返回的item的id就不错~
render: (value, row) => {
&nbsp;return (
                 &nbsp;&nbsp;&nbsp;&nbsp;<Form.Item>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{form.getFieldDecorator(\`${row.b2cSalesOrdItemId}_rtrnQty\`, {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;initialValue: value,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rules: [{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;required: false,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pattern: REG_ONLY_INTEGER,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;message: REG_ONLY_INTEGER_MSG
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}],
&nbsp;&nbsp;&nbsp;&nbsp;})(
                                  <InputInTable
                                    disabled={this.state.postRequest}
                                    maxLength="6"
                                    size="small"
&nbsp;&nbsp;&nbsp;&nbsp;/>,
&nbsp;&nbsp;&nbsp;&nbsp;)}
&nbsp;&nbsp;&nbsp;&nbsp;</Form.Item>
&nbsp;&nbsp;&nbsp;&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;}


哎，这玩意不知道咋贴代码，空格失效，凑合看吧。。。。

**Comment by HuangLotus** [comment]
@forever4313 好的，晚上试试！谢谢！
