### ISSUE TITLE
history.listen((location)  location参数bug

### ISSUE THREAD

**Issue by pmg1989** [dvajs/dva#953]
Link 路由跳转到`/detail/1210?token=xxx`时，发现监听函数`history.listen((location)`中 ，参数location.pathname错误的包含了location.query参数值，导致
`const match = pathToRegexp('/detail/:id').exec(location.pathname)`获取的match的值有误，页面刷新后，监听的参数就正常了

![image](https://cloud.githubusercontent.com/assets/13361827/26780282/9bc2b87c-4a1b-11e7-9623-3d2ced1f36d7.png)

**Comment by chezhe** [comment]
![1509091847085](https://user-images.githubusercontent.com/2902414/32094157-71e00eb4-bac4-11e7-9a06-fd311f13f3a0.jpg)
`history.listen`callback parameters `pathname` doesn't match the path of `this.props.match`. 
And the `pathname` is the right one, same with broswer.

When I go to `/project/:id` from `/projects`, it works fine; However go to `/project/:id1` from `/project/:id2`, it doesn't.
Have any idea?
