### ISSUE TITLE
sass 配置好，为什么不生效？

### ISSUE THREAD

**Issue by huyawei** [dvajs/dva#957]
webpack.config.js：
`webpackConfig.module.loaders.push({
    test: /\.scss$/,
    loaders: [
      'style',
      'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass'
    ]
  });`

..这个insert code 怎么回事，死活弄不好格式

之后index.js 引入sass，  给组件加上className，就是找不到风格，
npm run build,查看index.css 大小跟没导入sass之前一模一样

**Comment by sorrycc** [comment]
请跟进这个 issue，https://github.com/sorrycc/roadhog/issues/273

**Comment by huyawei** [comment]
.roadhogrc里配置？
"sass": true,
加了这个还是没生效




生产环境的配置 
倒是支持
webpackConfig.module.loaders.push({
      test: /\.scss$/,
      loader: _extractTextWebpackPlugin.extract('style', 'css!postcss!sass')
    })
dev 无解

**Comment by weiweiyx** [comment]
sass现在配置还是要在webpack里面配置嘛

**Comment by weiweiyx** [comment]
你这个配置好了嘛 我现在sass配置不行@sorrycc
