### ISSUE TITLE
.roadhogrc 怎么配置 import 绝对路径？

### ISSUE THREAD

**Issue by zchuhui** [dvajs/dva#958]
`import Menus from '../../components/Menu/Menu'`
如何配置，把前面的../../去掉？

**Comment by sorrycc** [comment]
不可以配，为啥要去掉，去掉之后 IDE 都无法跳转了。。

**Comment by zchuhui** [comment]
不能像webpack.config.js  那样配置的话，相对路径写起来有些繁琐，文件夹多层的话，好多` ../../../`

**Comment by sorrycc** [comment]
我不推荐配 alias，坚持要配的话，可以走 webpack.config.js，https://github.com/sorrycc/roadhog#配置

**Comment by zchuhui** [comment]
ok，谢谢指导。 @sorrycc
