### ISSUE TITLE
Failed to compile.Error in ./src/router.js [CaseSensitivePathsPlugin] 

### ISSUE THREAD

**Issue by thomastao0215** [dvajs/dva#959]
`Failed to compile.`
`Error in ./src/router.js`
`Module not found: [CaseSensitivePathsPlugin] /Users/jiachen215/PJDev/ytmanager/ytfrontend/src/routes/retailer.js does not match the corresponding path on disk Retailer.js.`

**Comment by nihgwu** [comment]
不觉得这是你自己代码的问题吗？

**Comment by Kunoky** [comment]
代码问题，你是不是copy别人的代码的

**Comment by liupeng110112** [comment]
是不是使用了create-react-app 重启下就好了吧

**Comment by thomastao0215** [comment]
我在routes下面创建了一个叫retailer的文件夹，里面包含一个index.js和index.css文件
import Retailer from './routes/retailer';
看爆粗是它去match 了'./routes/retailer.js' 这个文档，
我写成'./routes/retailer/index.js'就可以正常访问了
不应该直接访问'./routes/retailer'就可以找到下面的index.js吗

**Comment by nihgwu** [comment]
我还是那个意思，**这个问题跟dva无关，为什么要在这里开issue？**
你看看是不是文件名大小写的问题

**Comment by sorrycc** [comment]
`rm -rf ./node_modules/.cache` 然后重启试试。
