### ISSUE TITLE
为何在项目中使用iconfont加载字体文件会报错

### ISSUE THREAD

**Issue by GlacierXX** [dvajs/dva#96]
![image](https://cloud.githubusercontent.com/assets/7651252/18624801/de8313e8-7e7c-11e6-9adf-2053dba0adc3.png)
![image](https://cloud.githubusercontent.com/assets/7651252/18624815/f26d02c4-7e7c-11e6-9c8e-e7ab50c446b7.png)
![image](https://cloud.githubusercontent.com/assets/7651252/18624824/fd1d1286-7e7c-11e6-9820-41272fb4e4a3.png)
atool-build有配置字体文件的loader，但是好像不起作用，在webpack.config.js中webpackConfig.module.loaders.push 也还是不起作用，是哪里出了问题呢？

**Comment by sorrycc** [comment]
路径不对? 用 `./iconfont.eot` (加 `./` 前缀) 试试?

**Comment by GlacierXX** [comment]
@sorrycc 
![image](https://cloud.githubusercontent.com/assets/7651252/18625587/26de5512-7e82-11e6-8ebd-8d1c96479cd4.png) 直接import一个字体文件就可以，但是import less文件就报错，换了路径还是不行

**Comment by sorrycc** [comment]
@pigcan 有空看下。

**Comment by pigcan** [comment]
应该是 less-loader 的一个问题 https://github.com/webpack/less-loader/issues/76

可以在引用字体文件的路径上加上 

```diff
+ src: ~"url('./fonts/iconfont.eot')"
```

看看，不对的话自己再调整下 o.o

**Comment by GlacierXX** [comment]
@sorrycc @pigcan 问题已经解决 多谢 ！

**Comment by liupeng110112** [comment]
@GlacierXX  你那边是怎么解决的

**Comment by GlacierXX** [comment]
@liupeng110112  就是按作者的解决办法
![image](https://cloud.githubusercontent.com/assets/7651252/23894147/fa18235c-08db-11e7-8a14-1b391ae105ce.png)
