### ISSUE TITLE
IE8下redux-saga 报错

### ISSUE THREAD

**Issue by Thomas080304** [dvajs/dva#962]
IE8下redux-saga报错，报错位置定位如下：
(redux-saga\es\internal\channel.js)

return {take:take,put:put,flush:flush,close:close,
     get __takers__() {
         return takers;
     },
     get __closed__() {
        return closed
     }
};
查看了很多issues,发现redux-saga不支持IE8,不知道这个有没有polyfill可以解决，或者redux-saga有没有什么可以替代的方案？

**Comment by ChouUn** [comment]
这个恐怕要去 redux-saga 提 issue 吧，不过这里讨论下也不是不行

**Comment by codering** [comment]
别多想了，redux-saga官方早就不支持ie8了，也没有polyfill可以解决。

**Comment by Thomas080304** [comment]
https://github.com/rockallite/redux-saga-ie8，找到这个，不知道能不能解决这个问题，先分享出来

**Comment by Thomas080304** [comment]
@sorrycc  @codering 
https://github.com/rockallite/redux-saga-ie8，找到这个，不知道能不能解决这个问题，先分享出来

**Comment by Thomas080304** [comment]
@sorrycc  @codering 
找到这个，不知道能不能解决这个问题，先分享出来
https://github.com/rockallite/redux-saga-ie8
