### ISSUE TITLE
关于图片路径

### ISSUE THREAD

**Issue by FrankFei** [dvajs/dva#964]
![image](https://user-images.githubusercontent.com/3292846/26967441-d4b23eec-4d30-11e7-825e-a9a625cf674e.png)
开发时用的上面这个图片路径，通过npm run build后，这些图片全到了dist的根目录下了，有没有什么方法发布后生成到dist/images目录下？

**Comment by yinlsea** [comment]
![image](https://user-images.githubusercontent.com/21033870/27386302-f6881532-56c7-11e7-945f-7a4cf01c2826.png)

**Comment by FrankFei** [comment]
已经解决，非常感谢！

**Comment by hys421123** [comment]
请问具体是怎么解决的，loader.test这句话加在哪里啊？
