### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by iloveyo123u1** [dvajs/dva#969]
用dva cli 新建立的一个demo项目

出现了2个错误提示：
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

麻烦作者更新下

**Comment by sumlight** [comment]
同样问题

**Comment by qq645381995** [comment]
是的  这个  antd 那个项目前几周才升级好，改了，这个估计也快了
