### ISSUE TITLE
dva 路由会进入多次

### ISSUE THREAD

**Issue by lyzget** [dvajs/dva#97]
在dva-hackernews和user-dashboard都会出现该问题，使用的是dva-1.0.0版本。
以user-dashboard项目为例，输入地址/users ，根据路由：
` <Route path="/users" component={Users} /> `
会进入 routes/Users.js ，
在routes/Users内加入一句调试信息：
` console.log('---in---')`
会发现进入/users页面，控制台总会出现2条这个调试信息。（在dva-hackernews项目中会出现4条）

这个问题有点类似#54
问题是不是在models/users.js的subscriptions中，subscriptions里面的方法是异步的，在执行完subscriptions以后，会异步第一次进入routes/Users，此时数据是原始的state，等subscriptions内的dispatch执行完成后，又会重新刷新一次。
列表刷新2次，可能感觉不出问题，我在写update页面的时候，Form总是会初始化两次，这个看着就感觉别扭了。
这个问题怎么才能避免subscriptions内第一次原始的渲染，直接进入初始化以后的dispatch，只能在组件里写componentWillMount吗？

**Comment by sorrycc** [comment]
禁用 redux devtool 的 chrome 插件试试?

**Comment by lyzget** [comment]
刚试了一下，禁用了 redux devtool ，也把hmr关了，问题依旧，我也用ie11试了，也还是会进入2次

**Comment by lyzget** [comment]
调试的代码：

![image](https://cloud.githubusercontent.com/assets/20770995/18654571/e01a4954-7f14-11e6-8f85-524a3bb9cb74.png)

输出的结果：

![image](https://cloud.githubusercontent.com/assets/20770995/18654862/e72e108e-7f16-11e6-9644-27693c64e922.png)


在执行yield call 前，进入了componet了一次，等 yield call 方法结束以后，再进去了一次

**Comment by sorrycc** [comment]
这应该是正常的，初始是空数据，渲染一次，然后加载了新数据，又渲染一次。

**Comment by lyzget** [comment]
如果用redux-thunk 在componentWillMount中加载业务数据，就不会渲染2次。而在dva里面，获取数据我只知道用dispatch从effects里获取，dispatch获取数据就会渲染2次，那么dva还有其他方式获取业务数据吗？saga不是很了解@@。 而第一次的空渲染多数情况下，是没必要的

**Comment by sorrycc** [comment]
通常不都是先显示一个 loading 状态，然后有数据了再渲染一次的吗? 你是不希望有个 loading 状态?

**Comment by lyzget** [comment]
我使用dva-loading 也会再额外多渲染一次，变成3次了，没有避免空数据的那次渲染。

**Comment by sorrycc** [comment]
不用这么在意 render 次数，react 的 dom-diff 会解决性能问题的。

**Comment by lyzget** [comment]
好吧，先关闭

**Comment by K68** [comment]
会不会是这个原因
https://github.com/reactjs/react-router-redux/issues/481
