### ISSUE TITLE
关于路由相对路径问题

### ISSUE THREAD

**Issue by baixiaosh** [dvajs/dva#971]
问题是这样的，我在/user/list页面中使用：
```<Link to={`/user/list/${record.id}`}>详情</Link>```
可以访问到对应的页面，但：
```<Link to={`list/${record.id}`}>详情</Link>```
路由变化相同，但是访问不到详情页，不能匹配

**Comment by zjxpcyc** [comment]
这个可能要去研究下 react-router, 可能你认为的相对，跟 react-router 认为的不一致

**Comment by baixiaosh** [comment]
在dva配置的时候使用`{history: browserHistory}` 这个路径相对于浏览器的路径

目前使用location.pathname解决的
