### ISSUE TITLE
dva页面中嵌套react.component子页面，如何调用子页面里的方法？

### ISSUE THREAD

**Issue by FatFatFox** [dvajs/dva#973]
react的方法是
`this.refs.componentName.functionname()`
但是到了dva里在子组件中填写ref属性，报无状态组件不能嵌入的错误
网上查了一下可以用以下方法解决
` <ReactSwipe ref={e => (_ref = e)}/>`
但是我不知道怎么在dva中调用子组件的方法，求帮助，谢谢

**Comment by pimkle** [comment]
找到解决方案了吗？

**Comment by pimkle** [comment]
你好，找到解决方案了吗？

**Comment by FatFatFox** [comment]
找到了，也实现了,可以获得子页面对象，然后直接调用对象方法即可。。。
`
let this_child = null;
    function getDS(){
        console.log(this_child)
    }

function getChild(child){
        this_child = child;
    }
<IamReactComp { ...reactCompProps } ref={getChild}/>`

**Comment by pimkle** [comment]
后来我发现那个控件本身就支持定位到某一页 就不需要调用控件的跳转页的方法了😂😂😂 因为这违背了redux的思想 所以ref使用起来才这么麻烦吧

**Comment by FatFatFox** [comment]
也许违背了redux思想。而且使用中出现了react生命周期问题，即state变了，react控件不会自动刷新，于是我放弃用react写子控件的做法

**Comment by pimkle** [comment]
react控件会自动刷新啊 ‘https://github.com/akiran/react-slick’, ant design carousel的原型 她的`slickGoTo`属性就支持跟随react的state自动刷新啊

**Comment by FatFatFox** [comment]
能否稍微再详细些，我在dva中，调用react组件，怎么用slickGoTo来保证state变更后react会重新刷新初始化?谢谢

**Comment by pimkle** [comment]
jsx如下：
<div className={styles.bg_wrapper} onWheel={onWheel}>
  <Carousel slickGoTo={mdgj.index} afterChange={pageChange} vertical={true} dotsClass={styles.dotCls} verticalSwiping={true} draggable={true}>
</Carousel>
</div>

监听用户手势
onWheel里面调用
   dispatch({
      type: 'mdgj/indexChange',
      payload: {
        index
      }
    });

models下面的.js:
export default {
  namespace: 'mdgj',

  state: {
    index: 0
  },

  subscriptions: {
    setup({ dispatch, history }) {
    },
  },

  effects: {
    *indexChange({payload: index}, { put }) {
      yield put({
        type: 'change',
        payload: {
          index
        }
      });
    }
  },

  reducers: {
    change(state, {payload: index}) {
      return {...state, index: index.index.index };
    }
  }
};


重点就是reducers里面的方法，return之后 控件状态就会更新
