### ISSUE TITLE
官方user案例问题

### ISSUE THREAD

**Issue by zhangxiaoj** [dvajs/dva#976]
![qq 20170613124218](https://user-images.githubusercontent.com/19645467/27066314-c537ddc0-5035-11e7-93a2-6dfd04db51b5.png)

**Comment by zhangxiaoj** [comment]
不知道为什么重复

**Comment by MinJieLiu** [comment]
@zhangxiaoj 用 `immutable.js` 就可以减少这样的问题

**Comment by AnJT** [comment]
> @zhangxiaoj 用 `immutable.js` 就可以减少这样的问题

hh
