### ISSUE TITLE
说一下场景，我想在saga call接口之后根据返回的数据 写一个通用的方法来处理success和error，每一个接口的成功/失败回调的业务逻辑不同，两个回调以参数的方式传给这个通用方法。OK业务场景结束。现在问题在于在两个回调函数中put其他saga或者reducer调用不过去，这是我的问题

### ISSUE THREAD

**Issue by darkmood** [dvajs/dva#979]

**Comment by helloyou2012** [comment]
@darkmood 请自行理解下 `Generator` 语法，可参考 [Generator 函数的语法](http://es6.ruanyifeng.com/#docs/generator)

**Comment by darkmood** [comment]
整理了一下谦哥的思路，就是在request.js里将所有的通用回调逻辑（包括错误提示、成功提示等）写在request方法（fetch的回调）里，然后在effects里用try/catch（当然也可以全局），try里写成功之后需要put的saga/reducer，catch块捕获error然后在其中写逻辑（包括put saga/reducer等）
