### ISSUE TITLE
调用 mapStateToProps 后没有调用 render

### ISSUE THREAD

**Issue by oldfeel** [dvajs/dva#980]
弹出 antd 的 modal 时,同样的 mapStateToProps. modal 中的 mapStateToProps 引发了 render,而原页面中的 mapStateToProps 没有引发 render.原页面不弹 modal 时的 mapStateToProps 会引发 render

![56e2e39f-4f13-4704-bce5-d88e854dbca0](https://user-images.githubusercontent.com/1726280/27125391-b07a7c48-5126-11e7-8614-7c88abbb22ce.png)

添加了监听 updateTime 之后可以调用了.
````
    afterClose(state) {
      let {curveTabItem, groupItem} = state
      if (curveTabItem && curveTabItem.id == groupItem.id) {
        curveTabItem = groupItem
      }
      return ({
        ...state,
        curveTabItem,
        updateTime: new Date().getTime()
      })
    }
````

**Comment by helloyou2012** [comment]
@oldfeel 请自行谷歌 `React Lifecycle`，或参见官方文档：[the-component-lifecycle](https://facebook.github.io/react/docs/react-component.html#the-component-lifecycle)
