### ISSUE TITLE
请问组件层级深的时如何方便的传递 props

### ISSUE THREAD

**Issue by Alex1990** [dvajs/dva#984]
我看到文档有下面这句话：

> In dva, we restrict container components to route components, because we use page dimension to design container components.

一个页面会包含很多组件，有时组件嵌套层级比较深（而非几个 DEMO 那样），这是如果只在页面组件，也即 route component 里面 connect model 和 component，即需要数据从页面组件一层层传递到下面，会很麻烦。

当然，我可以 connect 任何 model 和 component，但是文档说了按照页面维度设计 container components，另外前半句说把 container components 限制为 route components，这个也让人以为只能使用 route components 也即页面组件来 connect model 和 component。

**Comment by zjxpcyc** [comment]
应该没啥特别好的办法。

1、如果嵌套很多层，建议换个角度，是否拆分的粒度太细了。
2、组件设计最好能符合 “单一职责” 原则，这样组件应该感觉不到很深的层次
3、connect 还是在 route 组件里面用吧，要不然太乱。

**Comment by Pines-Cheng** [comment]
state保持扁平化，页面也要保持扁平化。如果做不到，肯定是哪方面出了问题。

**Comment by Alex1990** [comment]
一个比较复杂的页面，比如类似 Google 统计的，是可以拆分成很多组件的，而且层级很深。另外组件符合”单一职责“原则，这与拆分粒度是否矛盾呢。

**Comment by zjxpcyc** [comment]
@Alex1990 
这要看 一 的定义, 我现在的项目是这样划分的。 route 里面都是 container components , stateless 组件，只有这个层级会去   connect 。 components 里面都是业务组件，这个地方体现了一， 比如, 文章 的 编辑。文章的新增就是另一个组件。 而不是说，这两个可以合并一个组件，然后根据某个 edit flag 去做子组件的划分。 

如果是纯技术或者开发的角度去看组件的拆分，那就会出现组件套组件的情况，就会出现很深的层次。最后，可能会发现，你拆分得这么细，还没有地方可以复用。为啥？因为 Antd 已经做得足够好，根本不需要自己再去做细分。

总结来说就是，用 dva + antd ，我们就关注业务角度就好了。如果你觉得 antd 不能满足你的业务需求，首先想到的是提交 issue ，再次看使用频次，最后才是自己封装。
