### ISSUE TITLE
能不能增加对应单个effects的loading值

### ISSUE THREAD

**Issue by ShadowRambler** [dvajs/dva#986]
### 能不能增加对应单个effects的loading值
-  首先effects之间互相调用就会有个问题，如下图，renderData的SHOW被process的HIDE给覆盖了，我不得不把renderData放到另一个model里，然后两个model的对应loading取个或，这个之前有人提过
![a27a2ce0-5b0f-417b-b15d-0502ed2cbeb0](https://user-images.githubusercontent.com/5702449/27223965-511ae760-52c5-11e7-9355-ed5a302ba6a8.jpg)

- 其次是我同一个model不能对应带不同loading状态的组件,经常按照数据设计的model最后被迫拆成多个来对应不同loading组件，结果就是我不是面向数据设计model，我是面向loading组件设计model
![timg](https://user-images.githubusercontent.com/5702449/27224244-a7a4abec-52c6-11e7-8c36-adabd8579339.jpeg)

结果就是我必须搞出好多不必要的model来，还求优化一下

**Comment by xufei** [comment]
可以设置到effect级别的。看这个：

https://github.com/dvajs/dva-loading

里面那个 opt.effects

**Comment by forever4313** [comment]
loading: loading.effects['products/queryProductsListData']
类似这种写法~

**Comment by ShadowRambler** [comment]
@xufei 没仔细看loading的文档，抱歉
