### ISSUE TITLE
annoying warning: Warning: dispatch: ns/ACTION_TYPE should not be prefixed with namespace ns

### ISSUE THREAD

**Issue by orzarchi** [dvajs/dva#988]
Is it possible to turn off the "helpful" warnings received when using the "dispatch" function in registrations or "put" effect?
Or at least make them optional.

I keep my action creators and actions types in dedicated files, which I believe is a general best practice for redux (see for example [here](https://jaysoo.ca/2016/02/28/applying-code-organization-rules-to-concrete-redux-code/#actions--action-creators)) 

This means that I always use my action creators in dva effects, registrations and components.

Example: 
actionTypes.js:
```javascript
export const TOKEN_RESTORED = 'auth/TOKEN_RESTORED';
```

actions.js:
```javascript
export default {
    tokenRestored: payload => ({type: TOKEN_RESTORED, payload: payload.token})
};

```
model.js: 
```javascript
app.model({
    namespace: ...,
    state: { ... },
    effects: { ... },

    subscriptions: {
        setup({dispatch}) {
            let token = localStorage.token;
            if (token) {
                dispatch(actions.tokenRestored({token}));
            }
        }
    }
});

```

I believe that users should be able to write code such as this, without receiving dozens of warnings of the type:
```
Warning: dispatch: auth/tokenRestored should not be prefixed with namespace auth
```

Code style is a manner of personal preference, and dva currently punishes users that don't directly use strings for action types.

**Comment by wiziple** [comment]
I have just experienced same issue.
Managing actions by redux-actions is convenient.
However, this cannot used in the models because of the warning.

**Comment by orzarchi** [comment]
I've created a pull request in case that helps this issue getting attention.
#1013

**Comment by sorrycc** [comment]
Recommend using https://www.npmjs.com/package/babel-plugin-dev-expression to strip invariant and warning for production.

**Comment by orzarchi** [comment]
What about development environment?
What if I cant use Babel plugins because I'm using create react app?

Why should I get warnings for using a common technique?

**Comment by oluckyman** [comment]
@orzarchi I believe @sorrycc is extremely busy and focused on opened issues only to be able to maintain this project. So you have to create a new issue in order to draw his attention.

BTW, did you manage to workaround these warnings?

**Comment by oluckyman** [comment]
I had a different problem. My model puts an action which is used only by other models:
```
// realtime.js
yield put({ type: 'message', payload: { message } });
```
and other models listen for messages from realtime:
```
// someModel.js
const message = yield take('realtime/message');
```

Since `realtime` model does nothing with `message` itself, it has no defined `message` effect. Because of that `yield put({ type: 'message', payload: { message } })` was not prefixed by dvajs internal algorithms and `realtime/message` never fired.
And if I prefix manually:
```
// realtime.js
yield put({ type: 'realtime/message', payload: { message } });
```
it throws warnings about namespace ('... should not be prefixed with namespace ...')

To workaround the problem I’ve added dummy effect into model:
```
// realtime.js
'effects': {
  // dvajs requires effect to be defined to auto-prefix it with namespace
  // if add prefix manually then dvajs throws annoying warnings
  // https://github.com/dvajs/dva/issues/988
  message: () => { },
}
```
Now I have no warnings and other models receive `realtime/message` action.

**Comment by orzarchi** [comment]
I don't see why opening the issue again will change his opinion.
You solution seems okay, however the extra effort isn't worth it when you have hundreds of actions.
Also it's common practice to use constants for action types (or action creator functions), and as such I always dispatch with the prefix.
I haven't found a workaround yet, so I'm considering forking dva for my current project, and then never using it again.

**Comment by zgriesinger** [comment]
I'm a little late to the party here, but this is a hack I used to work around the error. Definitely not a good solution but it at least stifles the error output.

`// my-model.js
console.error = message => {
  if (message.indexOf("prefixNamespace") === -1) {
    console.log(message);
  }
};`

**Comment by hiep294** [comment]
> I'm a little late to the party here, but this is a hack I used to work around the error. Definitely not a good solution but it at least stifles the error output.
> 
> ```
> console.error = message => {
>   if (message.indexOf("prefixNamespace") === -1) {
>     console.log(message);
>   }
> };
> ```

Can you clarify your code? where did you put the code?

**Comment by khiemhuynh** [comment]
You could put it in src/app.tsx. And if you want to keep console.error instead of converting all console.error to console.log, you could try this code
```tsx
const errorLog = console.error;
  console.error = (...rest) => {
    if (rest[0] && rest[0].indexOf('[sagaEffects.put]') === -1) {
      errorLog.call(console, ...rest);
    }
  };
```

**Comment by hiep294** [comment]
> You could put it in src/app.tsx. And if you want to keep console.error instead of converting all console.error to console.log, you could try this code
> 
> ```tsx
> const errorLog = console.error;
>   console.error = (...rest) => {
>     if (rest[0] && rest[0].indexOf('[sagaEffects.put]') === -1) {
>       errorLog.call(console, ...rest);
>     }
>   };
> ```

Thank you, and I found that I can put anywhere in the app, :))

**Comment by JonasJonny** [comment]
I know it's late, but `namespacePrefixWarning` can solved it.

```
const app = dva({
  history,
  onError,
  namespacePrefixWarning: false,
});
```
