### ISSUE TITLE
引入 babel-polyfill 方式疑问😫

### ISSUE THREAD

**Issue by MinJieLiu** [dvajs/dva#989]
以 dva-example-user-dashboard 为例，只写了 `babel-runtime` 引入方法，如果我需要引入 `babel-polyfill` 呢？

以下两种方式不可行，会出现 #723 的问题：
 * 在 `index.js` 中加入 `import 'babel-polyfill'`。虽然是引入了，但总是不是最先执行😢
 * 在 `.roadhogrc` 配置中 `entry` 值改为 `['babel-polyfill', 'src/index.js']`，没任何效果😢

目前最 low 的方式只能在 `index.html` 中所有 js 之前引入第三方 CDN 的模块。

我想问的是：不能通过 npm 模块引入吗？

还有一点是 index.html 可以作为模版吗，我现在看到的是

```html
<body>

<div id="root"></div>

<script src="roadhog.dll.js"></script>
<script src="index.js"></script>

</body>
```

这些 script 可以通过 webpack 的 `html-webpack-plugin` 方式做最好，目前是写死在里面了😭，
[sorrycc/roadhog#69 ](https://github.com/sorrycc/roadhog/issues/69)

**Comment by MinJieLiu** [comment]
解决了😀。。。

**Comment by Slngle** [comment]
@MinJieLiu 怎么解决的啊 我也遇到['babel-polyfill', 'src/index.js']我也这样配置的 打包不进去

**Comment by MinJieLiu** [comment]
@Slngle 在 `index.js` 中

最顶部加入
```js
import 'babel-polyfill';
```

**Comment by vito24** [comment]
@MinJieLiu thanks
