### ISSUE TITLE
stateless 组件应该怎么处理时钟？

### ISSUE THREAD

**Issue by u0x01** [dvajs/dva#99]
有一个路由有自动刷新的需求，设置了一个 setInterval 去 dispatch fetch 的动作，然后我在 model 中存储了 setInterval 的 handler。不知道应该何时进行 clearInterval。

现在的情况是 Interval 没有销毁，然后 Interval 就按照各自的 id 不停的刷新，表现出来就是页面上的信息不停轮换。

    state: {
      loading: false,
      auto_refresh: false,
      auto_refresh_timer: null,
    }

=========

    subscriptions: {
      setup({ dispatch, history }) {
        history.listen(location => {
          const match = pathToRegexp(`/contracts/:id`).exec(location.pathname);
          if (match) {
            const id = match[1]
            dispatch({ type: 'fetch', payload: {id: id} })
            dispatch({ type: 'onToggleAutoRefresh', payload: { checked: true, id: id, dispatch: dispatch }})  // 这里传入上一个 timer 的 handler 才能清掉
          }
        });
      },
    },

=========

    *onToggleAutoRefresh({ payload }, { select, call, put }){
      const dispatch = payload.dispatch

      let autoRefresh = payload.checked
      yield put({ type: 'toggleAutoRefresh' , payload: autoRefresh})

      if (autoRefresh) {
        if (payload.timer != null) {
          clearInterval(payload.timer)
        }
        let timer = setInterval(()=>dispatch({type: 'refresh', payload: {id: payload.id}}), 10000)
        yield put({ type: 'setAutoRefreshTimer' , payload: timer})
      } else if (payload.timer != null) {
        clearInterval(payload.timer)
        yield put({ type: 'setAutoRefreshTimer' , payload: null})
      }

    },

能否订阅 react-router 的 onleave 事件然后去 clearInterval？

也想过 setTimeout，每次判断当前是否刷新的 state，为 true 就继续 setTimeout，这样就不需要去 clearTimeout。可是不知道 effects 中怎么才能获取当前的 state（reducers 可以读到，但是不能 put/dispatch）。

还是说只能做一个标准的 react 组件 在 componentWillUnmount 的时候 clearInterval 了？

求指教思路。

**Comment by u0x01** [comment]
试了一下，用标准组件路由改变时并不会触发 componentWillUnMount …

**Comment by sorrycc** [comment]
需求是路由进入时启动定时器，出去时关闭定时器?

**Comment by sorrycc** [comment]
有问题再 reopen 。

**Comment by Kroderia** [comment]
@u0x01 `componentWillUnmount`是会触发的，你是typo了。
