### ISSUE TITLE
publicPath设置好后，build后生成的代码路径没有改变

### ISSUE THREAD

**Issue by zhangjingge** [dvajs/dva#991]
![1](https://user-images.githubusercontent.com/20674049/27324146-c1cd4908-55d6-11e7-8410-c035b40c7e7b.png)

如果直接在src的index里面改的话，起的本地服务index.js直接会加载为index.html

上图css，html为build后的

**Comment by haohailong1990** [comment]
我现在也遇到了，有什么好的解决方法吗
