### ISSUE TITLE
subscriptions里的dispatch能触发effects么？

### ISSUE THREAD

**Issue by whwnow** [dvajs/dva#996]
如果我想在subscriptions里执行异步操作，需要怎么触发其他modal里的effects。可以用dispatch么？

**Comment by ameol** [comment]
当然可以，subscriptions中的方法你可以这么写setup({ dispatch, history }){}

**Comment by whwnow** [comment]
看文档dispatch是用来出发action的，但是可以直接改变state的只有Reducer。我还以为dispatch只能触发Reducer。那如果Reducer，Effect是同名的话，dispatch会触发哪一个呢？

**Comment by zjxpcyc** [comment]
Reducer 跟 Effect 都是 Action，不能重名

**Comment by whwnow** [comment]
终于又搞清楚一个疑惑，多谢二位

**Comment by dicklwm** [comment]
@zjxpcyc 可以重名，只是先触发Reducer，再触发Effect

**Comment by zjxpcyc** [comment]
@dicklwm thx

**Comment by lenzzz** [comment]
@zjxpcyc 可以重名  具体可看 [React 应用框架在蚂蚁金服的实践](http://slides.com/sorrycc/dva) 里的demo
