### ISSUE TITLE
subscriptions 里 history 对象只能拿到当前的路由的 history，有没有方案可以做路由 transition 对比的呢？

### ISSUE THREAD

**Issue by zheeeng** [dvajs/dva#997]
某个获取数据 dispatch 想在地址真正变动的时候发出，history.listen 做不到前后路由的对比。目前只能手动维护一个路由记录去做这个工作。

**Comment by zjxpcyc** [comment]
是这个 [https://github.com/ReactTraining/react-router/blob/v2.8.1/docs/guides/ConfirmingNavigation.md](https://github.com/ReactTraining/react-router/blob/v2.8.1/docs/guides/ConfirmingNavigation.md) 意思吗 ？
