### ISSUE TITLE
容器组件注入的model  state  reset的问题

### ISSUE THREAD

**Issue by chengzhenping** [dvajs/dva#999]
routeA，用户交互产生数据后，切换到route B.再切回routeA.数据依然还在，每个容器组件在willMount或didmount中需要reset。有没有好的建议或者实践？

**Comment by zjxpcyc** [comment]
换多页面

**Comment by Renascence** [comment]
如果你使用的是第三方组件，先看看有没有提供重置的方法，例如antd的modal 组件和form组件
[https://ant.design/components/modal-cn/#清空旧数据](https://ant.design/components/modal-cn/#清空旧数据)
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

如果是自己实现的组件，可以这么写 this.state.A? <A> : '' 强制让组件重新挂载，清空里面的state

**Comment by yangbin1994** [comment]
https://github.com/yangbin1994/dva-atr 用reset事件很方便的就可以清理数据

**Comment by yirenkeji555** [comment]
reducers: {
        init (state) {
            return state = {}
        }
    }
